### ISSUE TITLE
provide more helpful message when you forget a ":"

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub#1284]
I had a pubspec with a transformers entry like this:

```
transformers:
- angular2
    entry_points: web/main.dart
```

It of course should've had "angular2:", not "angular2" (note the colon), but the message wasn't helpful:

```
$ pub serve
Error on line 8, column 16 of pubspec.yaml: Mapping values are not allowed in this context.
    entry_point: web/main.dart
               ^
```

If you could give a hint that a colon might be missing above, that would be fantastic. Or perhaps a link to a page that gives common solutions to the issue. Or a syntax checker that's smarter. If you can provide a different error message, I can work with you on its content.

(LOTS of people get burned by little problems like this, especially when they're starting out. Anything we can do to reduce their frustration would be helpful.)

**Comment by kwalrath** [comment]
cc @cbracken

**Comment by nex3** [comment]
Moved to dart-lang/yaml#11.
