### ISSUE TITLE
Using "pub get --offline" after a normal "pub get" seems in certain cases to fail

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub#1293]
The dart team provides base [Dockerfiles](https://github.com/dart-lang/dart_docker/blob/master/runtime/Dockerfile.template#L14) which make use of the `--offline` option the pub client provides.

The motivation for having two separate steps (i.e. `pub get` and `pub get --offline`) is to make use of Docker's layer caching functionality, which allows us to avoid re-running the slow `pub get` step in a developer cycle.

We've had repeated reports, from internal and external Dart users, that this causes sometimes issues of the following form:
```
...
INFO: --------------------  DOCKER BUILD  --------------------
DEBUG: "POST /v1.10/build?q=False&... HTTP/1.1" 200 None

INFO: # Executing 4 build triggers


INFO: Trigger 0, ADD pubspec.* /app/
INFO: Step 0 : ADD pubspec.* /app/
INFO: ---> Using cache
INFO: Trigger 1, RUN pub get
INFO: Step 0 : RUN pub get
INFO: ---> Using cache
INFO: Trigger 2, ADD . /app/
INFO: Step 0 : ADD . /app/
INFO: Trigger 3, RUN pub get --offline
INFO: Step 0 : RUN pub get --offline
INFO: ---> Running in 20d5b52f15d6
INFO: Resolving dependencies...
INFO: 
INFO: Unsupported operation: Cannot download packages when offline.
INFO: ../tmp/tmp_ldPtI/dart-1.10.0/dart/sdk/lib/_internal/pub/lib/src/source/hosted.dart 261  OfflineHostedSource._download
../tmp/tmp_ldPtI/dart-1.10.0/dart/sdk/lib/_internal/pub/lib/src/source/hosted.dart 88   HostedSource.downloadToSystemCache.<fn>
INFO: dart:isolate                                                                            _RawReceivePortImpl._handleMessage
INFO: This is an unexpected error. Please run
INFO:     pub --trace 'get' '--offline'
INFO: and include the results in a bug report on http://dartbug.com/new.

ERROR: The command [/bin/sh -c pub get --offline] returned a non-zero code: 1
...
```

The layer caching of docker should guarantee the following properties
  * The version of the dart SDK (and therefore pub's version) of both "pub get" steps is the same
  * The `pubspec.{yaml,lock}` files in both "pub get" steps are the same

The only possible explanation I can come up is that there is a bug in pub. The first successful `pub get` step should populate the pub cache with all necessary external dependencies. Any subsequent runs of `pub get --offline` with the same `pubspec.{yaml,lock}` files should never hit the network and all external dependencies should be available in the pub cache.

@nex3 @munificent Can you go through the code and look when this error can happen? Or do you see any other possible explanation?

cc: @enyo, @lukechurch, @sgjesse

**Comment by mkustermann** [comment]
@nex3  Thanks for looking at it so quickly.

Just to clarify this: The change in https://github.com/dart-lang/pub/commit/e47378e67dc1ce1774d611768e04429dddabd7ec only makes the error look nicer. It doesn't make `pub get --offline` succeed in the scenario described above in the bug report.

I guess you assume that the real problem outlined above is not a bug in the pub client?

**Comment by nex3** [comment]
As far as I could tell, the only way for the bug you're seeing to come up is if there was a legitimate error—in particular, if there was a locked version of a package that didn't exist in the local cache. That said, it's possible that the HTTP requests that were being made incorrectly had broader implications that could cause strange behavior. I think the only way to know for sure is to see how the Docker/Dart integration works with the new pub.

**Comment by lukechurch** [comment]
FWIW, I've just run into this. Cleaning all the docker images, and doing a pub cache repair solved the problem though it was inevitably somewhat slow as a process.

**Comment by nex3** [comment]
@lukechurch What version of pub did you see this with? Do you have a stack trace?
