### ISSUE TITLE
Self-references in generated .packages files point to the pubcache.

### ISSUE THREAD

**Issue by pq** [dart-lang/pub#1294]
Self-references are not properly encoded.  They point to the pubcache rather than the local source.

For example, given a package `foo`, the `.packages` reference will look something like this:

    foo:file:///Users/somebody/.pub-cache/hosted/pub.dartlang.org/foo-0.0.1/lib/

whereas it should look more like:

    foo:file:///Users/somebody/src/dart/pkg/foo/lib/

(Note that pub symlinks do this special-casing.  Which is to say we just need to get the `.packages` file URIs to agree with pub's symlink prior art.)

In the current state URI resolution for self-references in `analyzer` all fail.

**Comment by sethladd** [comment]
Thanks @nex3 !

**Comment by pq** [comment]
w00t.  Thank you!

On Thu, Jul 9, 2015 at 12:48 PM, Seth Ladd <notifications@github.com> wrote:

> Thanks @nex3 <https://github.com/nex3> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/pub/issues/1294#issuecomment-120124386>.
>



-- 
Phil Quitslund
Software Engineer
Google, Inc.

**Comment by pq** [comment]
I'm not sure this is fixed.  Running `pub` from a fresh build of the SDK I'm still seeing mappings to my `.pub-cache` for a self-reference.

```
[~/src/git/clones/analyzer_cli] (master) $ pub --version
Pub 1.12.0-edge.ec398a7385e634cd60b392d51a8650c140d4cb5f
[~/src/git/clones/analyzer_cli] (master) $ pub get
Resolving dependencies...
Warning: You are using these overridden dependencies:
! analyzer 0.25.1 from path /Users/me/src/git/clones/dart/sdk/pkg/analyzer
Got dependencies!
[~/src/git/clones/analyzer_cli] (master) $ cat .packages | grep analyzer_cli
analyzer_cli:file:///Users/me/.pub-cache/hosted/pub.dartlang.org/analyzer_cli-1.1.0/lib/
```

**Comment by pq** [comment]
Oh wait...  @nex3 : maybe we just need to update the `pub_rev` in `DEPS`?

**Comment by pq** [comment]
Running pub from the repo seems to do the right thing.
```
[~/src/git/clones/pub] (master) $ pub run pub get
Resolving dependencies...
Got dependencies!
[~/src/git/clones/pub] (master) $ cat .packages | grep pub:
pub:./lib/
```
So I think updating `DEPS` is all we need. :)

**Comment by pq** [comment]
Whoops.  Looks like I failed to re(sync) before I built.  I just confirmed that `DEPS` is actually up to date.  Closing out since I think we're actually good to go.
