### ISSUE TITLE
Another way to determine if a package is managed by git?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1296]
Hi,

We were trying to upload a package that contained a dot file to pub.dartlang.org. After reading the docs and talking to the engineer, we learned that our package needed a .gitignore file in the root of the package. We added it, and re-uploaded the package. Unfortunately, the dot file still wasn't uploaded.

We then learned that we also needed to have a .git directory at the root of our package. Apparently, the presence of a .git dir and a .gitignore file.

However, in our case, the package we were trying to upload is not at the root of the git repo. Our structure looks kind of like this:

```
project/
  .git/
  stuff/
  other_stuff/
  dart/
    package/
```

Our request is: instead of checking for a .git dir in the root of the package, could pub run some no-op git command to determine if the package is managed by git?

Thanks for reading!

**Comment by sethladd** [comment]
You rock, thank you!!

**Comment by sethladd** [comment]
@Sfshaza I think we need to rollback your doc tweak for this :)

**Comment by nex3** [comment]
![bashful](https://cloud.githubusercontent.com/assets/188/8629771/4f090392-2713-11e5-88e6-63e54e891e66.gif)
