### ISSUE TITLE
Feature: a way to bump version numbers when publishing

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1297]
Publishing a new Atom package is really nice, and maybe it's something we can emulate.

`apm publish major|minor|patch`

This will, among other things:

* bump your version in the package.json (by a major, minor, or patch)
* add a git tag
* push the git tag
* and upload to Atom's repo

I love how it auto-bumps the version. So helpful!

**Comment by nex3** [comment]
I think this is a better job for an external tool like [den](https://pub.dartlang.org/packages/den) combined with a task runner where users can set up the workflow they want. Right now pub has a strict policy of never modifying user files, and I think that's a good policy to stick to.
