### ISSUE TITLE
Global activation fails due to unknown transformer dep (Not clear what transformer is importing unknown package)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1300]
I just installed dartdoc via `pub global activate` and I saw some feedback that doesn't seem to be actionable / hard to determine what action to take. Could we tell the user what transformer is requesting the install of a package?

(in this case, I saw `A transformer imported unknown package "http" (in "package:http/http.dart").` ... what transformer?)

See output below:

```
~/tmp/docs $ pub global activate dartdoc
Resolving dependencies... (3.6s) 
+ analyzer 0.25.2
+ args 0.13.2
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.1.1
+ csslib 0.12.1
+ dartdoc 0.1.0+1
+ html 0.12.1+2
+ logging 0.11.1
+ markdown 0.7.1+2
+ matcher 0.12.0+1
+ mustache4dart 1.0.10
+ package_config 0.1.1
+ path 1.3.6
+ plugin 0.1.0
+ pub_cache 0.0.1+2 (0.1.0 available)
+ pub_semver 1.2.1
+ quiver 0.21.4
+ source_span 1.1.2
+ string_scanner 0.1.3+1
+ utf 0.9.0+2
+ watcher 0.9.6
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.3
Downloading dartdoc 0.1.0+1...
Downloading path 1.3.6...
Precompiling executables... 
Loading source assets... 
A transformer imported unknown package "http" (in "package:http/http.dart").
```

Thanks for taking a look!

**Comment by sethladd** [comment]
Is there a way to list transformers that were injected into a project?

**Comment by sethladd** [comment]
FWIW was using `Pub 1.12.0-dev.1.1`

**Comment by nex3** [comment]
> Is there a way to list transformers that were injected into a project?

Not with `pub`. You could pretty easily write a script to walk the paths in `.packages` and do this manually, though.

**Comment by sethladd** [comment]
Why would pub tell me that a transformer needs a dependency? Wouldn't the transformer's package have the dependency on http ?  (I'm confused why http isn't "just getting installed")

**Comment by sethladd** [comment]
> Not with `pub`. You could pretty easily write a script to walk the paths in `.packages` and do this manually, though.

Where is the .packages file written for a `pub global activate` command?

**Comment by sethladd** [comment]
I tried writing a simple script, which checks my dev copy of dartdoc's .packages for any transformers. I might have written this script incorrectly, but apparently none of my dependencies have transformers (at least, the dependencies in my local dev copy of dartdoc)

Check out the logic here: https://github.com/dart-lang/dartdoc/pull/655/files

**Comment by sethladd** [comment]
This may or may not be relevant/useful.

Apparently, installing from local source works:

```
~/tmp/docs $ pub global activate -s path /Users/sethladd/Code/dartdoc
Package dartdoc is currently active at path "/Users/sethladd/Code/dartdoc".
Activated dartdoc 0.1.0+4 at path "/Users/sethladd/Code/dartdoc".
Installed executable dartdoc.
```

**Comment by nex3** [comment]
Please try to avoid making a bunch of comments in a row; prefer editing comments in place to add new information.

> Wouldn't the transformer's package have the dependency on http ? (I'm confused why http isn't "just getting installed")

It *should*, but there's nothing stopping a package from writing an import statement for something it doesn't depend on. That's what's happening here.

> Where is the `.packages` file written for a pub global activate command?

Nowhere. You asked about listing transformers for a project, which I assumed meant a package you were working on in user space.

> I tried writing a simple script, which checks my dev copy of dartdoc's .packages for any transformers. I might have written this script incorrectly, but apparently none of my dependencies have transformers (at least, the dependencies in my local dev copy of dartdoc, which may or may not be what pub global activate sees or uses)
>
> This may or may not be relevant/useful.
>
> Apparently, installing from local source works:
> 
> ```
> ~/tmp/docs $ pub global activate -s path /Users/sethladd/Code/dartdoc
> Package dartdoc is currently active at path "/Users/sethladd/Code/dartdoc".
> Activated dartdoc 0.1.0+4 at path "/Users/sethladd/Code/dartdoc".
> Installed executable dartdoc.
> ```

It sounds like your local version has a different version constellation than the one you were trying to install globally.

**Comment by sethladd** [comment]
> Please try to avoid making a bunch of comments in a row; prefer editing comments in place to add new information.

I have deleted the previous comments and merged them into a single comment.

> Nowhere. You asked about listing transformers for a project, which I assumed meant a package you were working on in user space.

I am attempting to run `pub global activate dartdoc`, thus installing from pub.dartlang.org.

> It sounds like your local version has a different version constellation than the one you were trying to install globally.

> It should, but there's nothing stopping a package from writing an import statement for something it doesn't depend on. That's what's happening here.

So does that mean that `pub global activate` opens each .dart file and looks at the imports? My question is, maybe to help me debug this, can you help explain when pub is opening .dart files and looking at imports? Is it just for transformers? If so, how does it find those transformers?

Thanks!

**Comment by nex3** [comment]
> So does that mean that `pub global activate` opens each .dart file and looks at the imports? My question is, maybe to help me debug this, can you help explain when pub is opening .dart files and looking at imports? Is it just for transformers? If so, how does it find those transformers?
>
>
> (One difference... when installing from `pub global activate dartdoc`, it runs a "Precompiling executables" step... that doesn't seem to happen during a local `pub global activate -s path /foo/bar/dartdoc`)
>
> Thanks!

When you run `pub global activate` for an immutable package (that is, one *not* from the path source), it precompiles your executables, as the output indicates. If the package or any of its dependencies use transformers it needs to load those transformers to do the precompilation, since the output of the transformers is the canonical source code of a transformed package. Your failure is happening because one of those transformers is (possibly transitively) importing a package, `http`, that is not in the root package's dependency constellation. This in turn is presumably caused by whatever package has that transformer failing to include `http` as a dependency.

Packages from the path source work a little differently. Like path dependencies, executables for these packages use the actual code on the filesystem. Since the user might modify that code, we can't precompile path dependencies.

**Comment by sethladd** [comment]
Thank you for the helpful context!

My next action is to take the list of dependencies, as printed by `pub global activate`, and look in each of those for a `transformers:` in their pubspec.yaml and/or import http.
