### ISSUE TITLE
No obvious error if global activate fails and bin scripts not created

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1302]
Hi,

Just tried to `pub global activate dartdoc`, and I got this output:

```
~/tmp/docs $ pub global activate dartdoc
Resolving dependencies... (3.8s) 
+ analyzer 0.25.2
+ args 0.13.2
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.1.1
+ csslib 0.12.1
+ dartdoc 0.1.0+2
+ html 0.12.1+2
+ logging 0.11.1
+ markdown 0.7.1+2
+ matcher 0.12.0+1
+ mustache4dart 1.0.10
+ package_config 0.1.1
+ path 1.3.6
+ plugin 0.1.0
+ pub_cache 0.1.0
+ pub_semver 1.2.1
+ quiver 0.21.4
+ source_span 1.1.2
+ string_scanner 0.1.3+1
+ utf 0.9.0+2
+ watcher 0.9.6
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.3
Precompiling executables... 
Loading source assets... 
A transformer imported unknown package "http" (in "package:http/http.dart").
~/tmp/docs $ pub --version
Pub 1.12.0-dev.3.1
~/tmp/docs $ which dartdoc
```

Looks like I encountered a failure, not just a warning. The `dartdoc` command wasn't inserted onto the path.

Could we make it more obvious that the global install process failed? That way, the expectation is easier for the user... and they will know that the install failed.

(as it reads now, I interpreted it as an FYI and I expected dartdoc to work.)

Thanks!

**Comment by nex3** [comment]
What sort of output are you looking for? This follows the very common error pattern of printing a message describing the error and then exiting with a non-zero exit code. Short of printing all errors in red (which we definitely don't want), I'm not sure what else we could do.

**Comment by sethladd** [comment]
Here's some ideas:

```
Error: The transformer foo, from package bar, requires package http, which is not declared as a dependency.
Installation aborted.
```

This tells me two things:

1. the explicit error
2. that the installation stopped

(neither of which were clear to me in the beginning)

Hope that helps!

**Comment by nex3** [comment]
So is the issue that you don't like the message for this specific error, or that you don't like how error messages are displayed in general?

I'm not generally a big fan of adding annotations like "Error:" or "Installation aborted" all over the place. They often end up being redundant and creating visual noise, and they put the developer in the awkward position of trying to decide where in the code to add them. I'd rather let the primary error messages speak for themselves.

**Comment by sethladd** [comment]
The issue is, it's not clear that dartdoc wasn't installed. It's not clear that I was told an error. I interpreted it as a warning. It would really help to say "this install failed" or something similar. The error, as written, is opaque. I can't take action on it anyway (what transformer? does it matter? what do I do? is it my code, or a dependency's code?)

**Comment by nex3** [comment]
I understand that you found this confusing, but I don't think it's necessarily confusing in the absolute. Pub is very consistent in labeling its warnings as such and coloring them yellow, and it's rare across any command-line software that a warning would be the last thing printed before a program exits. Pub is also consistent about printing confirmation when actions succeed; in the case of `pub global activate` in particular, it will always print "Installed executable *name*" when it succeeds.

For this particular error message, I think it's also reasonable to expect users to connect an import failing to a fatal error. The output clearly indicates that pub is precompiling the package's executables; it shouldn't be surprising that an import being unresolvable would cause precompilation to fail.

I'm not saying you're wrong for being confused by this, but one person's confusion isn't inherently evidence that something needs to be changed. Almost everything about the system has probably confused one person or another, and it's not sustainable to play whack-a-mole by adding exactly the text that would have alleviated that specific confusion. Additional verbosity has a cost, and we need to carefully balance that cost against the benefit it provides.
