### ISSUE TITLE
Pub won't precompile an executable for a package that was already installed

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#1303]
Pub (correctly) doesn't precompile executables for transitive dependencies, since their executables can't be run by the entrypoint anyway. However, if a dependencies goes from being transitive to direct, pub should precompile its executables, even if the exact same version was already installed, because they could now be run directly.

**Comment by sigurdm** [comment]
I think this might already be working.

We compute the set of executables to precompile here: https://github.com/dart-lang/pub/blob/be6868ba132c782d9835b1638a634ecb73428579/lib/src/entrypoint.dart#L452

We compute that for every resolution - so if a package goes from transitive to direct I believe its executables should be precompiled.
