### ISSUE TITLE
Pub on Windows fails for users with accented characters in local user account

### ISSUE THREAD

**Issue by cedx** [dart-lang/pub#1304]
Unfortunately, my user account was automatically created by the Windows installer. So my home folder is: `C:\Users\Cédric` (with an accent on the last `e`).

Some features related to the Pub cache folder fails. Notably global commands.
For example, if I install a program globally: `pub global activate dartdoc`. The package install is OK (files located at the right place in: `C:/Users/Cédric/AppData/Roaming/Pub/Cache`), but I cannot use the program. Here is the output:

```
$ dartdoc.bat --help
Unhandled exception:
Load Error for "file:///C:/Users/C%E2%94%9C%C2%AEdric/AppData/Roaming/Pub/Cache/global_packages/dartdoc/bin/dartdoc.dart.snapshot": Error loading file:///C:/Users/C%E2%94%9C%C2%AEdric/AppData/Roaming/Pub/Cache/global_packages
/dartdoc/bin/dartdoc.dart.snapshot:
  FileSystemException: Cannot open file, path = 'C:\Users\CÔö£┬«dric\AppData\Roaming\Pub\Cache\global_packages\dartdoc\bin\dartdoc.dart.snapshot' (OS Error: Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable.
, errno = 3)
#0      _asyncLoadErrorCallback (dart:_builtin:116)
#1      _asyncLoadError (dart:_builtin:348)
#2      _handleLoaderReply (dart:_builtin:292)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[ + standard output from the '--help' switch ]
```

As you can see, the accented characters are not properly handled.

It also fails with `pubspec.lock` file: the `packages` symbolic links are properly created in the project directroy tree, but I must specify the `--package-root` argument when using Dart tools (dartanalyzer, dart2js), or the paths corresponding to the `pubspec.lock` hosted packages are not properly resolved (again, some encoding problem).
If I remove the `pubspec.lock` file, I don't need anymore the `--package-root` argument as the package paths are properly resolved to the local `packages` links.

EDIT: I'm using the Dart VM v1.11.1

**Comment by nex3** [comment]
Your OS error is itself corrupted; this isn't something pub touches at all. That suggests that there's either an encoding error between your terminal and GitHub or between your OS and Dart. On your local terminal, does the OS error look like "Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable" or does it have normal accents? What happens if you create a file named `é.txt` and run the following code?

```dart
import 'dart:io';

void main() {
  print("Reading from char codes...");
  new File(String.fromCharCodes([0xE9, 0x2E, 0x74, 0x78, 0x74]))
      .readAsStringSync();
  print("Reading from string...");
  new File("é.txt").readAsStringSync();
}
```

> It also fails with `pubspec.lock` file: the `packages` symbolic links are properly created in the project directroy tree, but I must specify the `--package-root` argument when using Dart tools (dartanalyzer, dart2js), or the paths corresponding to the `pubspec.lock` hosted packages are not properly resolved (again, some encoding problem).
> If I remove the `pubspec.lock` file, I don't need anymore the `--package-root` argument as the package paths are properly resolved to the local `packages` links.

This is very strange. As far as I know, no tools other than pub read the lockfile; the analyzer might invoke `pub list-package-dirs`, but dart2js certainly doesn't. I can't imagine why deleting the lockfile would change anything.

**Comment by cedx** [comment]
### Error 1: command line scripts of package executables installed globally

The error message is garbage in my console. The Dart output is UTF-8 encoded but not the Windows terminal which still uses Code Page 1252 Latin 1 (so most UTF-8 accented characters looks weird).

The error raised with `dartdoc` is also here with other packages installed globally:

```
$ pub global activate dev_compiler
[ install: OK ]

$ dartdevc.bat --help
Unhandled exception:
Load Error for "file:///C:/Users/C%E2%94%9C%C2%AEdric/AppData/Roaming/Pub/Cache/global_packages/dev_compiler/bin/devc.dart.snapshot": Error loading file:///C:/Users/C%E2%94%9C%C2%AEdric/AppData/Roaming/Pub/Cache/global_packag
es/dev_compiler/bin/devc.dart.snapshot:
  FileSystemException: Cannot open file, path = 'C:\Users\CÔö£┬«dric\AppData\Roaming\Pub\Cache\global_packages\dev_compiler\bin\devc.dart.snapshot' (OS Error: Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable.
, errno = 3)
#0      _asyncLoadErrorCallback (dart:_builtin:116)
#1      _asyncLoadError (dart:_builtin:348)
#2      _handleLoaderReply (dart:_builtin:292)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
usage: dartdevc [<options>] <file.dart>
[ + standard output from the '--help' switch ]
```

I tried with your code (a little bug near `String.fromCharCodes`, the `new` operator is missing) : no problem at all. Here is the output:

```
$ dart .\charset_test.dart
Reading from char codes...
Reading from string...
```

After looking at the scripts generated by Pub in the global `bin` folder, I think the problem is with the fact that the path to the snapshot of the Dart script is hard-coded, like in `dartdoc.bat`:

```
@echo off
rem This file was created by pub v1.11.1.
rem Package: dartdoc
rem Version: 0.1.0+4
rem Executable: dartdoc
rem Script: dartdoc
dart "C:\Users\Cédric\AppData\Roaming\Pub\Cache\global_packages\dartdoc\bin\dartdoc.dart.snapshot" %*

rem The VM exits with code 253 if the snapshot version is out-of-date.
rem If it is, we need to delete it and run "pub global" manually.
if not errorlevel 253 (
  exit /b %errorlevel%
)

pub global run dartdoc:dartdoc %*
```

If I replace :
`dart "C:\Users\Cédric\AppData\Roaming\Pub\Cache\global_packages\dartdoc\bin\dartdoc.dart.snapshot" %*`
by :
`%APPDATA%\Pub\Cache\global_packages\dartdoc\bin\dartdoc.dart.snapshot" %*`,
the error disappears.

Apart from the error message about the snapshot, the scripts work fine.

**Comment by cedx** [comment]
That's cool :) The second problem is not resolved but it is clearly not related to the "binstubs", so I'll open a new issue when I've enough time to give more details. Thanks.
