### ISSUE TITLE
Allow entrypoints in the root directory iff the package has a flat dartpad/gist like structure

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/pub#1307]
See this topic dart misc for more information: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/LbXGkjiwoL4

I picture it to work like this: `pub serve .` would serve the html files in the root directory.

Personally, I think this should only work if the entire package structure is flat. I can't really picture a usecase where someone would want to have both entrypoints in the root as in some other directory (web/test etc.). 

So maybe throw an error when someone does `pub serve .` in a non-flat package ?

And maybe, easier, the user could then just do `pub serve`. If the package is flat, this should then work as `pub serve .`, if the package is not flat, `pub serve` could work exactly the same as it works now.

**Comment by nex3** [comment]
In general, I'm not a fan of adding hidden conditions and switches to the behavior of pub commands. If we make this work, we should make it work regardless of the structure of the project and not silently switch on or off.

**Comment by kasperpeulen** [comment]
I think about this as something similar as, if there is only a test directory, `pub serve` works like `pub serve test`. And if there is a test and web directory, `pub serve` works like `pub serve test web`.

Now if there is a flat structure, `pub serve` could work like `pub serve .`

But I thought switching this behavior off, if there is a non-flat strucutre, as think would get complicated if there are entrypoints in both the root and let's say the `web` directory.

Say there is `web/entrypoint.html` file, the root is being served from `localhost:8080` and `web` is being served from `localhost:8081`. Do you serve this entrypoint also as `localhost:8080/web/entrypoint.html`? Or only as `localhost:8081/entrypoint.html` ?

Maybe a better thing is indeed not to silenty turn this off, but give an error when there are entrypoints in the root, and in a deeper directory (test/web etc) ?

**Comment by nex3** [comment]
If we do support this (which I'm not convinced we should) I don't think the package root should be automatically served under *any* circumstances. It's not good practice to put an app at the same level as your pubspec and other top-level files; even if we decide that the gist use-case is important enough to warrant allowing a generally bad practice, we shouldn't add a shortcut for it.

**Comment by kasperpeulen** [comment]
> If we do support this (which I'm not convinced we should) I don't think the package root should be automatically served under any circumstances.

Yes, agreed. I think it should be only served when the entire structure of the package is flat.

> It's not good practice to put an app at the same level as your pubspec and other top-level files.

I agree this would be really bad practice for real dart apps with lots of files. But I don't see why it would be a bad practice if your app only contains 2 or 3 files (pubspec.yaml, main.dart and maybe index.html). I agree more with the statement from @munificent in dart misc:
> It would make for a simpler layout for tiny packages, which would be great.

And I think more important, it would make the dart sharing snippets story easier. I don't think anyone would want to make a github repo just to quickly share a two-file dart snippet. 

I'm making some kind of 'community driven dart cookbook' website that completely depends on gist for adding snippets to the website, updating snippets and also for cloning the snippet to your local editor. The idea is that this would allow people to quickly explore the dart language, by getting dart snippets running in their editor. And also for people that already know the dart language, to easily explore any kind of dart library. 

So from my point of view, it would be really great if pub could serve gist without any trouble. Tonight I have some time to make a pull request for that, would you guys appreciate that ? Or should I wait for your guys to decide what you want to do with this situation ?

**Comment by kasperpeulen** [comment]
@munificent @nex3 

If you think this would be a really bad idea, I could also write a command line tool, something like `gist clone [gistId]` that tries to put the gist files in the right directory ?

Only downside of that would be, that you probably don't want to clone the gist as git repo then. So basicly  updating the gist with `git commit` and `git push` won't work anymore. I could of course then write some custom `gist push` thing, that would update the gist, and put the files in a flat structure again.

Any thoughts on this ?

**Comment by nex3** [comment]
> I agree this would be really bad practice for real dart apps with lots of files. But I don't see why it would be a bad practice if your app only contains 2 or 3 files (pubspec.yaml, main.dart and maybe index.html).

It would involve serving the pubspec, the lockfile, and any other top-level configuration files publicly for the world to see. That's fine *specifically* for the use case of a demo app, but for a real application it involves exposing private information in a way that may not be clear to the user.

> If you think this would be a really bad idea, I could also write a command line tool, something like `gist clone [gistId]` that tries to put the gist files in the right directory ?

In general I'm a fan of putting stuff in external executables rather than in pub itself. It might produce a simpler user interface to have it do custom *serving* behavior rather than custom *checkout* behavior.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
