### ISSUE TITLE
Pub should be able to read `--no-package-symlinks` from an environment variable 

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1311]
_From @zoechi on August 11, 2015 16:54_

I usually use `pub get`/`pub upgrade` from command line and find the argument quite cumbersome to use.  I'd prefer setting `export pub_options=--no-package-symlinks` and be sure it is applied everywhere. 

_Copied from original issue: dart-lang/sdk#24046_

**Comment by sethladd** [comment]
:) I just emailed about that exact question.

**Comment by nex3** [comment]
Given that `--no-package-symlinks` is the *only* pub argument that's meaningful to set globally, I'm reluctant to implement all the piping for global configuration to only have it be useful for one release.

**Comment by sethladd** [comment]
That's fair. We can open an issue on WebStorm to ensure there is a way for a user to add options for their runs of pub.

I guess a work-around is to write a shell alias.
