### ISSUE TITLE
All pub commands print 'find:> bin [:No such file or directory' when run from Windows 8.1 Powershell

### ISSUE THREAD

**Issue by Mixolyde** [dart-lang/pub#1314]
Only seeing this in Powershell (Git for Windows), not in regular windows CMD. On windows 8.1.

    [master]> pub --version
    find: >     bin [: No such file or directory
    Pub 1.11.3

    [master]> pub run
    find: >     bin [: No such file or directory
    Must specify an executable to run.

    Usage: pub run <executable> [args...]
    -h, --help    Print this usage information.
        --mode    Mode to run transformers in.
                  (defaults to "release" for dependencies, "debug" for entrypoint)

    [master]> pub deps
    find: >     bin [: No such file or directory
    my_app 0.0.1
    |-- http 0.11.3
    |   |-- http_parser 0.0.2+8

**Comment by nex3** [comment]
It looks like [this line](https://github.com/dart-lang/sdk/blob/master/sdk/bin/pub.bat#L50) is the culprit. It looks like it's in [a bunch of other scripts](https://github.com/dart-lang/sdk/search?l=bat&q=find+n1&type=Code&utf8=%E2%9C%93) as well—do dart2js and dartanalyzer also print this message for you?

@ricowind @aam It looks like you two were the last to touch this code. Can you shed any light on how to make it not barf for Powershell?

**Comment by seaneagan** [comment]
probably want to merge with https://github.com/dart-lang/sdk/issues/21770 which was a report of the same problem (and likely same solution) in cygwin.
