### ISSUE TITLE
Could pub tool support system proxy setting?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1317]
_From @taozuhong on August 14, 2015 1:59_

I have set the proxy for my machine, but dart can't read it, could pub tool support system proxy setting?

![image](https://cloud.githubusercontent.com/assets/13451009/9265809/f7a6b8ec-426a-11e5-87fd-bb9e1f6399ce.png)

''when run the pub tool (set proxy by manual),it will return the result as follow pictures:''
![image](https://cloud.githubusercontent.com/assets/13451009/9265836/60f9bc54-426b-11e5-93ee-9f8ed0abadba.png)

![image](https://cloud.githubusercontent.com/assets/13451009/9265841/71addce2-426b-11e5-9b26-a3ca2833d849.png)

_Copied from original issue: dart-lang/sdk#24080_

**Comment by kevmoo** [comment]
_From @zoechi on August 14, 2015 8:37_

Current support is by using environment variables:  
- https://www.dartlang.org/tools/editor/troubleshoot.html#pub-get-firewall
- http://stackoverflow.com/questions/24021315/network-connection-proxies-in-dart-editor

**Comment by kevmoo** [comment]
_From @taozuhong on August 14, 2015 11:9_

I know and have used the environment variables HTTP_PROXY/HTTPS_PROXY,but system setting are more flexable, so I hope pub command tool can support it .

**Comment by nex3** [comment]
Bounced back to dart-lang/sdk#24080 as a `dart:io` issue.
