### ISSUE TITLE
Feature request: Install package using pub

### ISSUE THREAD

**Issue by austincummings** [dart-lang/pub#1320]
It would be great to be able to install a single pub package using something that looks like `pub get redstone`. Also would be nice to be able to add the package to your pubspec using a `--save` option, e.g: `pub get --save redstone`.

**Comment by sethladd** [comment]
Check out den from @seaneagen https://pub.dartlang.org/packages/den

**Comment by nex3** [comment]
We've decided that pub shouldn't be in the business of modifying users' pubspecs, but den is a great tool if that's what you want.
