### ISSUE TITLE
pubspec.yaml file has changed since the .packages file was generated

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1322]
```
/usr/local/apps/dart/dart-sdk/bin/pub serve web --port=53452
The pubspec.yaml file has changed since the .packages file was generated, please run "pub get" again.
Pub Serve terminated
```

This is quite cumbersome. Not every change in `pubspec.yaml` is related to dependencies. I just modified an `entry_points` entry of a transformer configuration. No need to update the packages file by running `pub get`.
IMHO a warning would do instead of just terminating.

**Comment by nex3** [comment]
I've been frustrated by this as well. It looks like our simpler and faster heuristics for up-to-date checking are *too* simple. I don't want to just run anyway when we know it's out-of-date @munificent suggested an alternative: *if* the `.packages` file is out-of-date according to the mtime, do a slower and more complex check to decide whether actual dependencies have been modified. If not, touch the `.packages` file so we won't have to run the check again in the future.

**Comment by zoechi** [comment]
If the check is fast (local only) this would be nice otherwise I'd prefer just printing a warning and continue.
