### ISSUE TITLE
Way to list all bins available to me in my app?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1323]
I was just working with a customer and we were curious what I could run from `pub run ...`. We didn't find a way to discover what's available to us. Is there such a thing? Something like a `pub run --list` ?

**Comment by nex3** [comment]
There isn't, but that's a good idea.

**Comment by sethladd** [comment]
Neat!

**Comment by antonmoiseev** [comment]
Are you still considering adding this command? I would like to work on it, have a couple of questions.

**Comment by nex3** [comment]
Yeah, I'd accept a patch that adds this.

**Comment by antonmoiseev** [comment]
Nice! I'm thinking about the right way to implement this, and have two options in mind:

1. List all executables from `bin` and `.pub/bin` directories.
2. List all executables from `bin` and `bin` directories of the immediate dependencies.

I have a couple of concerns about the first option:

- Looks like it doesn't cover all the cases. For example snapshots are not generated for path dependencies.
- It requires `pub get` to be invoked before running `pub run --list`.

The second option looks good, but taking into account different types of sources, looks like it also requires `pub get` to be executed beforehand. However I'm still exploring this approach.

Could you advise what would be the correct way to get the complete list of executables?

**Comment by nex3** [comment]
The second option is definitely correct, for the reasons you've discovered. You'll always need `pub get` to be run though, since otherwise you won't have concrete dependency versions—and the executables in a dependency can change from version to version.

**Comment by antonmoiseev** [comment]
Could you answer several more questions:

1. `dartfmt` formats the entire file including the lines I haven't modified while addressing the issue. Should I leave or revert these changes?
2. Do you have any preference regarding the output format of the command? Right now I just print each executable on its own line:
  ![image](https://cloud.githubusercontent.com/assets/182853/16398124/36bbbfb2-3cd1-11e6-9a5c-666a16b42aff.png)
3. I believe we won't be able to list all possible executables that can be invoked with `pub run`, for example executables generated by transformers or located outside of the `bin` directory (in `tool`, `lib`, etc.) Can you confirm it's out of the scope of the issue?
4. I noticed the integration tests keep each file descriptor on its own line, however `dartfmt` not always preserve this formatting. Should I prefer `dartfmt` result or manually re-format descriptors?

**Comment by nex3** [comment]
> `dartfmt` formats the entire file including the lines I haven't modified while addressing the issue. Should I leave or revert these changes?

`pub` doesn't use `dartfmt` in general, so please revert any changes to code that you didn't author.

>Do you have any preference regarding the output format of the command? Right now I just print each executable on its own line:
>  ![image](https://cloud.githubusercontent.com/assets/182853/16398124/36bbbfb2-3cd1-11e6-9a5c-666a16b42aff.png)

It might be nice to group executables by package. Something like:

```
foo: foo, bar
baz:qux
test
```

Then only bold the executable names and not the package names, to add some contrast.

> I believe we won't be able to list all possible executables that can be invoked with `pub run`, for example executables generated by transformers or located outside of the `bin` directory (in `tool`, `lib`, etc.) Can you confirm it's out of the scope of the issue?

I think we should *only* list executables that are executable in the `foo:bar` form. So in your image, we would display `bin/baz.dart` as `app:baz`, and we wouldn't display `bin/sub/qux.dart` at all.

> I noticed the integration tests keep each file descriptor on its own line, however `dartfmt` not always preserve this formatting. Should I prefer `dartfmt` result or manually re-format descriptors?

Manually re-format them.

**Comment by gagoman** [comment]
Should be closed by #1680
