### ISSUE TITLE
Pub: support some form of authorization when downloading packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1327]
_From @maxwellpeterson-wf on June 16, 2015 15:15_

Our organization has setup a fork of the [pub repository](https://github.com/dart-lang/pub-dartlang-dart) for our private/non-OSS packages. 

The current authorization flow for publishing packages to it works, however after perusing though the code, it looks like nothing similar exists for downloading packages with a `pub get`.

It would be great if pub could support authorization on a per-server basis.

_Copied from original issue: dart-lang/sdk#23652_

**Comment by nex3** [comment]
You can set [the `PUB_HOSTED_URL` environment variable](https://www.dartlang.org/tools/pub/installing.html#optional-environment-variables) to configure where pub downloads dependencies from by default. You can also choose which package server they come from on a package-by-package basis by using a [full-form hosted dependency](https://www.dartlang.org/tools/pub/dependencies.html#hosted-packages).
