### ISSUE TITLE
pub serve: should have option to gzip served dart2js code

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/pub#1332]
It is currently hard to test application load performance using `pub serve` as JavaScript code produced by dart2js is not gzipped. It is most common for JS payloads to be gzipped for delivery via HTTP and so `pub serve` doesn't emulate the real world very well.

**Comment by nex3** [comment]
I think we used to do this, but the `dart:io` default got switched and we never re-enabled it.

**Comment by yjbanov** [comment]
Woohoo! Thanks for the quick turnaround!
