### ISSUE TITLE
Local churn w/ pubspec[.yaml, .lock] causes 'pub get' request when running global activated binary

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1334]
1. Activate a global package – simple_http_server or similar
2. Go to an unrelated Dart project dir
3. Run activated binary – notice things work okay
4. Tweak the pubspec for the unrelated project
5. Try to run activated binary

Expected: it just works
Actual: get an error about needing to run `pub get` first.

**Comment by zoechi** [comment]
Might be related to #1322. Do you have a recent Dart version including the fix?

**Comment by sethladd** [comment]
Is this still valid? I see https://github.com/dart-lang/pub/issues/1322 is closed.

**Comment by kevmoo** [comment]
@nex3 ?

**Comment by nex3** [comment]
I haven't had a chance to look into this yet. @kevmoo, can you confirm that this is still reproducing with a Dart version that includes the fix for #1322?

**Comment by kevmoo** [comment]
No repro as of `1.13.0-dev.7.0 (Wed Oct 14 05:51:27 2015)`

**Comment by kevmoo** [comment]
:metal:
