### ISSUE TITLE
Incorrect exit code if use dart2js transformer

### ISSUE THREAD

**Issue by Aetet** [dart-lang/pub#1336]
If we have dart files with `main() {}` then dart2js transformer will hide error exit code from another transformers.

For example we have transformer which take `.md` files and throw error while transformation. Transformer correctly log error, but when `pub build` will be finished we got error code 0, but not 65. If we remove dart files then we got correct exit code 65.

Example for reproduce:
https://github.com/Aetet/transformer-issue

**Comment by Aetet** [comment]
@nex3 What about this issue?

**Comment by natebosch** [comment]
I think I have a potential fix, but I don't expect to land super quickly - we have to think through the consequences.

**Comment by natebosch** [comment]
Fix should show up in the 1.24 dev releases once those are started.

**Comment by Aetet** [comment]
Thanks!
