### ISSUE TITLE
Failed to load resource: index.bootstrap.initializer.dart

### ISSUE THREAD

**Issue by raphway** [dart-lang/pub#1344]
I used `pub build` on a Dart project, and it generated an `index.html` and an `index.bootstrap.initializer.dart.js` among other files.

When I tried to run the project, I got the error: `Failed to load resource: index.bootstrap.initializer.dart`.

I looked into `index.html` and found this line:

`<script type="application/dart" src="index.bootstrap.initialize.dart"></script>`

And obviously this file doesn't exist, only a similar one that ends in `dart.js`. Changing this line to `<script src="index.bootstrap.initialize.dart.js"></script>` solves the problem, but I wonder if this is a bug.

**Comment by nex3** [comment]
Pub doesn't generate HTML files. I think the issue is in your transformer or your source code.

**Comment by zoechi** [comment]
There are two options to fix this
- add `<script src="packages/browser/dart.js"></script>` below your Dart script tag in your html file or 
- add this transformer to your `pubspec.yaml` file https://pub.dartlang.org/packages/dart_to_js_script_rewriter

**Comment by raphway** [comment]
@zoechi I already have that line, and the app is fully functional because it's loading the JS file, but as you mentioned I still get the error. And this is what I mean: is this a bug or is there any way to avoid getting this error without changing the URI on `index.html` from `.dart` to `.dart.js`?

**Comment by zoechi** [comment]
@raphway This is the way Dart is invoked on Dartium and as fallback JS is invoked on other browsers. There seems to be no way to avoid this error message. 
Another issue (in this repo but couldn't find it just yet) to create different output depending on whether dart2js is run or not was declined.
The best option currently is to use the transformer listed as 2nd option above which should exactly do what you want.

**Comment by raphway** [comment]
@zoechi OK, now I understand. Thanks for the explanation!
