### ISSUE TITLE
map dart2js hints to info or hint level

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/pub#1360]
Currently pub-build will show dart2js hints as warnings. To keep the nomenclature consistent, we should present the message also as a hint or at least info level.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
