### ISSUE TITLE
The null object does not have a getter 'pubspec'.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1364]
After each Dart SDK update I have to `pub global activate dart_style`, otherwise I get

>  (polymer1) $ pub global run dart_style:format --dry-run lib test tool
The null object does not have a getter 'pubspec'.
>
NoSuchMethodError: method not found: 'pubspec'
Receiver: null
Arguments: []
dart:core                                              Object.noSuchMethod
package:pub/src/barback/dependency_computer.dart 171   DependencyComputer._transformersNeededByPackage.traversePackage
package:pub/src/barback/dependency_computer.dart 199   DependencyComputer._transformersNeededByPackage
package:pub/src/barback/dependency_computer.dart 348   _PackageDependencyComputer.transformersNeededByLibrary.<fn>
dart:core                                              Iterable.fold
package:pub/src/utils.dart 722                         unionAll
package:pub/src/barback/dependency_computer.dart 346   _PackageDependencyComputer.transformersNeededByLibrary
package:pub/src/barback/dependency_computer.dart 100   DependencyComputer.transformersNeededByLibrary
dart:_internal                                         ListIterable.fold
package:pub/src/utils.dart 722                         unionAll
package:pub/src/barback/load_all_transformers.dart 41  loadAllTransformers.<async>
This is an unexpected error. Please run
>
    pub --trace global run dart_style:format --dry-run lib test tool
>
and include the results in a bug report on http://dartbug.com/new.
myuser@mypc ~/dart/bwu_polymer_routing
 (polymer1) $ 

Not sure if this is only with `dart_style` because I usually run a set of tools using a Grinder script. I just investigated with `dart_style` to find a reproducable case.

I update my SDK daily (bleeding edge) and built myself a little script that re-activates all activated packages to work around but that's not really a solution.

I experience this issue since quite some time but currently I'm using

> Dart VM version: 1.14.0-edge.d0ea4371c9bab943b31b41299e1627e48a22e1f3 (Tue Dec  1 17:47:48 2015) on "linux_x64"

**Comment by nex3** [comment]
Can you reproduce this with the latest `pub` from this repo? I suspect this was fixed by a1139b80c0230a429a468f9f411556a3fc183bba.

**Comment by zoechi** [comment]
This fix was a month ago, my SDK is 2 days old.

**Comment by nex3** [comment]
The SDK doesn't always have the latest version of pub. That's why I asked you to test with pub *from this repo*.

**Comment by zoechi** [comment]
I don't know how to find out how old my pub is. `pub --version` output doesn't tell much. `dart --version` at least contains a date. 
I didn't get this error after todays update to the latest bleeding_edge though. 
I'll reopen when I encounter the exception again.
