### ISSUE TITLE
Pub tests on buildbot failing - cannot find pub root

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub#1365]
Since the update of Pub to 8c091bf6332e8b392fdac63ae297426fb65ed925  in https://codereview.chromium.org/1491933003 , most of  the tests of pub on the buildbot have been failing with

00:08 +8 -40: test/build/copies_non_dart_files_to_build_test.dart: copies non-Dart files to build/
  ScheduleError: "Bad state: Can't find pub's root."
  Stack chain:
  | package:pub/src/io.dart 565:26                            pubRoot.<fn>
  | package:pub/src/io.dart 571:3                             pubRoot
  | package:pub/src/io.dart 552:14                            pubRoot
  | test/test_pub.dart 547:35                                 startPub
  | test/test_pub.dart 438:13                                 schedulePub
  | test/test_pub.dart 331:3                                  pubCommand
  | test/test_pub.dart 335:3                                  pubGet
  | test/build/copies_non_dart_files_to_build_test.dart 24:5  main.<fn>
  | test/test_pub.dart 396:9                                  _integration.<fn>
  | package:scheduled_test/scheduled_test.dart 68:27          test.<fn>.<fn>
  | package:scheduled_test/src/schedule.dart 85:16            Schedule.run.<fn>.<fn>
  | dart:async                                                runZoned
  | package:scheduled_test/src/schedule.dart 83:14            Schedule.run.<fn>
  | dart:async                                                Future.Future.sync
  | package:test/src/backend/invoker.dart 155:11              Invoker.waitForOutstandingCallbacks.<fn>
  | dart:async                                                runZoned
  | package:test/src/backend/invoker.dart 152:5               Invoker.waitForOutstandingCallbacks
  | package:scheduled_test/src/schedule.dart 82:28            Schedule.run
  | package:scheduled_test/scheduled_test.dart 66:28          test.<fn>
  | package:test/src/backend/declarer.dart 48:47              Declarer.test.<fn>.<fn>
  
  Error detected when waiting for out-of-band callbacks in queue "tasks".

**Comment by nex3** [comment]
@whesse I'm pretty sure I fixed the test errors, but there are still a bunch of failures and I can't figure out why. Are those related?

**Comment by whesse** [comment]
The errors I see in the actual "Running pub tests" step seem like timeouts
and communication problems, mostly.
The error on the analyzer is because pkg/lookup_map depends on
package:convert, but a new, incompatible version
of convert is being used.  pkg/lookup_map needs to be updated.

What failures exactly are you referring to?

On Thu, Dec 10, 2015 at 1:40 AM, Natalie Weizenbaum <
notifications@github.com> wrote:

> @whesse <https://github.com/whesse> I'm pretty sure I fixed the test
> errors, but there are still a bunch of failures and I can't figure out why.
> Are those related?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/pub/issues/1365#issuecomment-163448523>.
>



-- 
William Hesse

**Comment by whesse** [comment]
The safari failures are due to an xcode limitation on the size of a file list, and we have a target with all the third_party/pkg files in it.  I'm breaking up this target into smaller targets to solve the issue.

**Comment by nex3** [comment]
It looks like the issues I was seeing are gone now. I'll see if I can track down the Windows flakiness.
