### ISSUE TITLE
path based dev_dependency now causes failures for users?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1369]
I recently published a new version of the [initialize](https://pub.dartlang.org/packages/initialize) package, and it has started giving this error to users when they  upgrade:

```
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/initialize: Invalid description: "test_package" is a relative path, but this isn't a local pubspec.
```

This is not a new dependency (it has been around for many versions). It seems that maybe dev dependencies aren't being skipped over properly? I also go no errors on `pub lish`.

**Comment by jakemac53** [comment]
It also seems that this might be breaking the upgrade process, I have had to delete my `.pub` directory and rerun pub upgrade in order to actually get the new version (even though the pubspec.lock is updated with the new version).

**Comment by nex3** [comment]
What version of `pub` created the `.pub` directory, and what version of `pub` produced the error? Can you provide a simple way for me to reproduce tihs?

**Comment by jakemac53** [comment]
Initially you can create a project like [this gist](https://gist.github.com/jakemac53/0b32c118b1172125a012/). Then run `pub get`, `pub build bin`, and `dart build/bin/main.dart`, this should work and you will see `hello` print in the console.

Now edit your `pubspec.yaml` by removing the analyzer dependency and changing the initialize dependency to `initialize: '>=0.6.0 <0.7.0'`. Run `pub upgrade` and you will see the error message. If you then run `pub build` you will get a build error because the `initialize` package has not actually been upgraded.

Next, remove your `.pub` directly and run `pub upgrade` again. Now if you run `pub build` it will work and `dart build/bin/main.dart` should also work (and print `hello`).

**Comment by jakemac53** [comment]
Oh also fwiw I am on version `1.14.0-dev.4.0` of the sdk
