### ISSUE TITLE
Pub dependency resolver gives false error

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/pub#1370]
I get this error while running `pub get`. My pubspec file contains one path dependency, but nonetheless the error it gives is false. There might be a dependency inconsistency (I cannot find it though), but the message it prints is just incorrect.
```
Package zengen has no versions that match >=0.3.0 <0.4.0 derived from:
- stevenroose 0.1.1 depends on version >=0.3.0 <0.4.0
```
[zengen](https://pub.dartlang.org/packages/zengen) has v0.3.1 published December 13th.

**Comment by stevenroose** [comment]
This is the log of my `pub get` after deleting all the pub caches.
https://gist.github.com/stevenroose/543459ebdc52915d3d35

**Comment by stevenroose** [comment]
This seems to be the problem:
```
SLVR: | | | | | | | | | | | | | | | inconsistent constraints on quiver:
    | | | | | | | | | | | | | | | |   zengen 0.3.1 from hosted -> quiver ^0.20.0 from hosted (quiver)
    | | | | | | | | | | | | | | | |   angular2 2.0.0-beta.0 from hosted -> quiver ^0.21.4 from hosted (quiver)
```

So pub reports an incorrect error, the error is on quiver by zengen and angular2 instead on the zengen package.

**Comment by zoechi** [comment]
Dup of #912 (see references at the bottom)
