### ISSUE TITLE
API for pub.dartlang.org

### ISSUE THREAD

**Issue by nishanths** [dart-lang/pub#1373]
Is there a public JSON API for searching the package registry at pub.dartlang.org?

I'd like to build a client (either as part of the `pub` command or standalone) that searches the package registry.

**Comment by zoechi** [comment]
There is. There a several packages that use it like `pub` of course. 
There are packages like https://pub.dartlang.org/packages/pub_client, https://pub.dartlang.org/packages/bwu_pub_client. 
There is no documentation but pub.dartlang.org source is open
(https://github.com/dart-lang/pub-dartlang-dart and https://github.com/dart-lang/pub_server)

**Comment by nishanths** [comment]
Thanks for the links! :+1:
