### ISSUE TITLE
Cannot get pub serve to show colors in grinder task

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/pub#1377]
I have the following grinder task:

``` dart
@Task()
testTravis() async {
  // travis only supports firefox and content-shell it seems
  final platforms = ['firefox', 'content-shell'];
  final process =
      await Process.start('pub', ['serve', 'test', '--port', '3000']);
  process.stderr.map((l) => UTF8.decode(l)).forEach(stderr.write);
  await process.stdout
      .map((l) => UTF8.decode(l))
      .map((l) {
        stdout.write(l);
        return l;
      })
      .firstWhere((s) => s.contains("Build completed successfully"));
  await new TestRunner().testAsync(platformSelector: platforms, pubServe: 3000);
  process.kill();
}
```

For some reason, `pub` doesn't show colors when run in this way as a Process in Dart. The test do show colors:
![image](https://cloud.githubusercontent.com/assets/1035299/12218667/e5919f9c-b726-11e5-9723-6d0cc1f46bcc.png)

**Comment by zoechi** [comment]
I think this is the related issue dart-lang/sdk#24716

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
