### ISSUE TITLE
Pub hangs and is unkillable on windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub#1378]
This is a link to the issue filed on dart-lang/sdk about this problem.  These unkillable pub get processes are a major problem, and we have not made much progress on fixing it.  Comments should go on the original bug, on dart-lang/sdk.

The issue is dart-lang/sdk#24086

 It says:

The unkillable hung pub process shows up as doing 200 MB/s of "other" I/O, which is not read or write, but something like stat.

These flakily hanging pub processes are a big problem on the buildbot, and we have now switched to automatically rebooting all windows slaves that run pub, after each build.

@nex3 @munificent @ricowind @sgjesse

**Comment by nex3** [comment]
I think this must be a `dart:io` (or possibly `dart:isolate`) bug. As far as I know, there are no Dart APIs that are expected to render a process unkillable except maybe `ProcessSignal.watch`, which pub doesn't call on `pub get`.

Does this reproduce outside of a bot context?

**Comment by sigurdm** [comment]
I don't think this is an issue anymore, tentatively closing.
