### ISSUE TITLE
Include charset in pub serve when possible.

### ISSUE THREAD

**Issue by DavidSouther** [dart-lang/pub#1385]
Currently, pub serve [barback_server](https://github.com/dart-lang/pub/blob/31c48c9701ef88d5202e599a85a1402614363c10/lib/src/barback/barback_server.dart#L161) depends on [lookupMimeType](https://github.com/dart-lang/mime/blob/b19e022ed90180681044b53753a007640e86af06/lib/src/mime_type.dart) when setting `Content-Type` for served assets. It should also include the charset; `mimeType + "; charset=" + resolvedCharset`.

NB: Why is pub depending on dart-lang/mime, and not [dart:io](https://api.dartlang.org/1.14.0/dart-io/ContentType/charset.html)?

**Comment by munificent** [comment]
> NB: Why is pub depending on dart-lang/mime, and not dart:io?

I believe pub serve is older than dart:io's ContentType class. Also, I don't think dart:io's can guess a MIME type from a path, which pub uses.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
