### ISSUE TITLE
pub build should not modify pubspec.lock

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#1388]
_From @johnmccutchan on February 4, 2016 20:58_

This broke both Flutter and Mojo when they upgraded to Dart 1.14 and is a regression from 1.13.

$ ls -l pubspec.lock
-rw-r----- 1 johnmccutchan eng 9.6K Feb  4 12:54 pubspec.lock
$ pub build
...
$ls -l pubspec.lock
-rw-r----- 1 johnmccutchan eng 9.6K Feb  4 12:57 pubspec.lock

_Copied from original issue: dart-lang/sdk#25688_

**Comment by nex3** [comment]
This is important to pub's functionality. We use the modification time of `pubspec.lock` as an indication of whether it's up-to-date relative to the pubspec. If the pubspec's modification time is newer than the lockfile's, we need to do relatively expensive checks to determine whether the user needs to re-run `pub get`. If we determine that they don't, we update the lockfile's modification time so we don't have to do those checks again in the future.

Can you (or someone) go into more detail about what Flutter and Mojo are doing with this modification time? I bet we can find a way for them to structure their checks that works with what pub needs to do.

**Comment by johnmccutchan** [comment]
Step 1 in building Observatory involves invoking `pub get` and the output of that build rule is the `pubspec.lock` file. 
Step 2 is running `pub build` which expects a `pubspec.lock` file as an input.

Now that in 1.14, `pub build` modifies pubspec.lock, Observatory gets rebuilt every single time.because after step 2 is run, the .lock file is newer than the build output of step 2.

The fact that `pub build` never altered the modification time of 'pubspec.lock', until 1.14 makes this is a *breaking change* to our SDK. Please bump the sdk version to 2.0.0 or revert this breakage.

@mit-mit @kevmoo

**Comment by nex3** [comment]
How do Flutter and Mojo fit into this?

> Now that in 1.14, `pub build` modifies pubspec.lock, Observatory gets rebuilt every single time.because after step 2 is run, the .lock file is newer than the build output of step 2.

This definitely isn't ideal. The lockfile should only have its modification time updated if it was older than the pubspec's when `pub build` was invoked—was that the case? If so, why?

> The fact that `pub build` never altered the modification time of 'pubspec.lock', until 1.14 makes this is a *breaking change* to our SDK. Please bump the sdk version to 2.0.0 or revert this breakage.

It's only a breaking change if we guaranteed its stability, which we definitely didn't. Also, the SDK isn't semantically versioned (although I wish it were). We've had much more significant changes in the past without increasing the major version number, and I expect we'll do so again in the future.

**Comment by johnmccutchan** [comment]
Why couldn't pub build change the timestamp on pubspec.lock *before* generating the build output?

**Comment by nex3** [comment]
As far as I can tell, it does.

```
$ touch pubspec.yaml
$ mkdir whatever
$ pub build whatever
Loading source assets... 
Building json_rpc_2... 
Built 4 files to "build".
$ stat pubspec.lock
  File: ‘pubspec.lock’
  Size: 2739            Blocks: 8          IO Block: 4096   regular file
Device: fc04h/64516d    Inode: 17043092    Links: 1
Access: (0640/-rw-r-----)  Uid: (96759/   nweiz)   Gid: ( 5000/     eng)
Access: 2016-02-05 11:26:14.208189632 -0800
Modify: 2016-02-05 11:27:14.578090076 -0800
Change: 2016-02-05 11:27:14.578090076 -0800
 Birth: -
$ stat build/whatever
  File: ‘build/whatever/’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fc04h/64516d    Inode: 1966276     Links: 3
Access: (0750/drwxr-x---)  Uid: (96759/   nweiz)   Gid: ( 5000/     eng)
Access: 2016-02-05 11:27:15.490118786 -0800
Modify: 2016-02-05 11:27:15.490118786 -0800
Change: 2016-02-05 11:27:15.490118786 -0800
 Birth: -
```

**Comment by natebosch** [comment]
pub build no longer exists. The replacement `build_runner` doesn't have any places to modify `pubspec.lock`.
