### ISSUE TITLE
`Unable to spawn isolate` on `pub upgrade`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1397]
> Precompiling dependencies... 
Loading source assets... 
Loading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smoke/src/default_transformer transformers... 
Unable to spawn isolate: Unhandled exception:
Could not import "package:dart_style/dart_style.dart" from "package:angular2/transform/codegen.dart": Failure getting http://localhost:37270/packages/dart_style/dart_style.dart:
  404 Not Found
#0      _asyncLoadErrorCallback (dart:_builtin:162)
#1      _asyncLoadError (dart:_builtin:573)
#2      _handleLoaderReply (dart:_builtin:390)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
dart:isolate-patch/isolate_patch.dart      Isolate.spawnUri.<async>
dart:async-patch/async_patch.dart 34       _asyncErrorWrapperHelper.<fn>
dart:async/zone.dart 1142                  _RootZone.runBinary
dart:async/future_impl.dart 579            _Future._propagateToListeners.handleError
dart:async/future_impl.dart 641            _Future._propagateToListeners
dart:async/future_impl.dart 432            _Future._completeError
dart:async/future_impl.dart 56             _SyncCompleter._completeError
dart:async/future_impl.dart 27             _Completer.completeError
dart:isolate-patch/isolate_patch.dart 439  Isolate._spawnCommon.<fn>
dart:isolate-patch/isolate_patch.dart 148  _RawReceivePortImpl._handleMessage

**Comment by zoechi** [comment]
Looks similar to #1379

**Comment by zoechi** [comment]
Dart VM version: 1.16.0-edge.149ad3a2e9a9d21e8f2ec14faf72aff9c5ccc83b (Tue Mar 15 01:40:34 2016) on "linux_x64"

**Comment by nex3** [comment]
Please post your pubspec and lockfile as well, and the full output of running `pub upgrade --verbose`.

**Comment by zoechi** [comment]
`pub upgrade --verbose` output
[output.txt](https://github.com/dart-lang/pub/files/180503/output.txt)

**Comment by zoechi** [comment]
Didn't get this since a while.
