### ISSUE TITLE
Unclear error when package contains no entrypoints

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/pub#1398]
If you try to publish a package that does not have any `.dart` files in `lib/`, the following happens:

```bash
Uploading... (5.1s)
Bad state: The transaction has already been committed..
```

This happens because the `libraries` property on the `PackageVersion` entity does not get set, so the commit actually fails.

```bash
Error while committing: ApplicationError: Property "libraries" has no value., #0      _validateResponse.<anonymous closure> (package:googleapis_beta/src/common_internal.dart:880:11)
```

It would be great if there was a more clear error presented when this happens :)

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#49

**Comment by maxwellpeterson-wf** [comment]
Ah, that makes more sense. Thanks!
