### ISSUE TITLE
pub publish hangs in 1.16.0-dev.2

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/pub#1399]
I managed to publish one project but another one never worked. It would simply spin (updating the second count in the "Uploading (xxx seconds)" thingy but never complete.

I tried this several times over a couple of days and always the same. I left it running for many minutes.

Then I switched back to dart 1.14.0 and it published within a few seconds.

The package was https://pub.dartlang.org/packages/jefe version 0.3.0-pre.2.

Incidentally I was able to publish 0.3.0-pre.1 the other day, but can't remember if that was with 1.16.0-dev.1 or 1.16.0-dev.2

**Comment by munificent** [comment]
I am seeing this too on bleeding edge when I try to publish the markdown package. The verbose output from pub (with some stuff stripped in case it's secret) is:

    FINE: Pub 1.16.0-edge.6455b3e5911c7c5b13afe1585a4055948e6bca2d
    IO  : Spawning "git --version" in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    FINE: Determined git command null.
    IO  : Spawning "git check-ignore --quiet ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 1.
    IO  : Spawning "git ls-files --cached --others --exclude-standard ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    FINE: Archiving and publishing markdown 0.10.0 (.).
    MSG : Publishing markdown 0.10.0 to https://pub.dartlang.org:
    FINE: Creating .tag.gz stream containing:
    IO  : Spawning "git ls-files --cached --others --exclude-standard ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    IO  : Spawning "git ls-files --cached --others --exclude-standard ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    IO  : Spawning "git ls-files --cached --others --exclude-standard ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    IO  : Reading binary file ./README.md.
    IO  : Read 2851 bytes from ./README.md.
    IO  : Spawning "tar --create --gzip --directory /Users/rnystrom/dev/markdown/. --files-from /dev/stdin" in /Users/rnystrom/dev/markdown/.
    IO  : Spawning "git ls-files --cached --others --exclude-standard ." in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    IO  : Spawning "git ls-files --cached --others --exclude-standard bin" in /Users/rnystrom/dev/markdown/.
    IO  : Finished git. Exit code 0.
    FINE: Showing confirm message:
        | Looks great! Are you ready to upload your package
    FINE: Loading OAuth2 credentials.
    FINE: Saving OAuth2 credentials.
    IO  : Writing 309 characters to text file /Users/rnystrom/.pub-cache/credentials.json.
    MSG : Uploading...
    FINE: HTTP POST https://accounts.google.com/o/oauth2/token
    FINE: HTTP response 200 OK for POST https://accounts.google.com/o/oauth2/token
    FINE: HTTP GET https://pub.dartlang.org/api/packages/versions/new
    FINE: HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/versions/new
    FINE: HTTP POST https://storage.googleapis.com

It looks like the POST to cloud store is hanging, so I'm guessing this is a server issue. There have been very few changes to pub in the past few weeks, and I don't think any of them touch publishing.

I am also seeing issues *downloading* packages from cloud store.

@mkustermann, any idea what could be going on?

**Comment by munificent** [comment]
I was able to successfully publish a package using the latest version of pub running on top of the 0.14.2 version of the VM, so this does not seem to be a pub problem. I'm going to close and move the bug.

**Comment by mkustermann** [comment]
@munificent  Was this fixed by https://github.com/dart-lang/sdk/commit/5cee7ff634e715f6b2b0c8bfa3980206545d6916 ?

**Comment by munificent** [comment]
As far as I know, yes, but that's a @zanderso question.

**Comment by zanderso** [comment]
AFAIK, this is fixed.
