### ISSUE TITLE
Symlinks are ignored when publishing to a hosted pub repository

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/pub#1400]
We have a package that supplies most of our common frontend styling - SASS, CSS, icons, fonts, etc.

This repository existed long before we started using Dart, so most of the code is in top-level directories like `sass/` and `dist/`. When using the package as a github dependency we were able to symlink some the necessary directories into `lib/`. These symlinks persist upon download/git clone, and everything works great.

However, when we publish the package to our new hosted private pub repository, the symlinks do not make it into the tar archive which means we get a mostly empty `lib/` directory and cannot use our static assets.

It seems as though an [option](http://www.gnu.org/software/tar/manual/html_node/dereference.html) could be used with the `tar` command to include the symlinks before uploading it to the pub repository server.

@nex3 @trentgrover-wf @greglittlefield-wf

**Comment by aaronlademann-wf** [comment]
For reference, _our new hosted private pub repository_ - as a result of #1335 being closed.

**Comment by nex3** [comment]
I'm fine with passing an option to tar to fold in symlinks. Can you folks figure out how to do so in a cross-platform way? GNU tar often has different options than the BSD tar that Mac OS uses, and on Windows we use 7zip which is entirely different.

**Comment by aaronlademann-wf** [comment]
Thanks for the fix @nex3 !!!
