### ISSUE TITLE
pub seems broken for OS X 10.11.2

### ISSUE THREAD

**Issue by iamthemuffinman** [dart-lang/pub#1401]
I was following the Angular2 for Dart guide [here](https://angular.io/docs/dart/latest/quickstart.html) and when I run ```pub get``` it downloads everything, but then just hangs for a second and doesn't precompile anything. I just tried the same thing on an Ubuntu 14.04 VM and it worked just fine. All the relevant details are in this [gist](https://gist.github.com/iamthemuffinman/5fc865ae4c0a5ecbdd0705e54b332af1).

**Comment by iamthemuffinman** [comment]
Also should have mentioned I installed Dart using Homebrew.

**Comment by munificent** [comment]
I believe you're running into https://github.com/dart-lang/pub/issues/1399. It's fixed in the bleeding edge repo. You can either jump to that, or downgrade to the latest stable version of the Dart SDK until a new dev version is out with the fix.

Sorry about that!
