### ISSUE TITLE
Publishing packages from a Mac causes downstream tar warnings on Linux

### ISSUE THREAD

**Issue by krisgiesing** [dart-lang/pub#1402]
Running "pub get" on a Linux box, fetching a Mac-published package can cause a series of warnings that look like this:

tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'

etc.

See https://github.com/flutter/flutter/issues/2284 for a full log; this appears to be caused by publishing the flutter_gallery_assets package from a Mac.

**Comment by nex3** [comment]
This looks like #1069, which was fixed as of Dart 1.6.0. What version of `pub` was this user using?

**Comment by krisgiesing** [comment]
@HansMuller @vlidholt for comment on the question of pub versions.

**Comment by devoncarew** [comment]
Almost certainly this guy: `Dart VM version: 1.15.0 (Wed Mar  9 09:55:45 2016) on "macos_x64"`, which is what flutter's currently pegged to.

**Comment by nex3** [comment]
As I understand it, Mac OS shouldn't *ever* have warnings like this—they occur because the Mac OS version of `tar` produces output that the GNU version doesn't understand, but Mac OS should understand it fine.

**Comment by krisgiesing** [comment]
The 'pub get' occurred on a Linux box, while fetching a package published from a Mac. Updating the description.

**Comment by zoechi** [comment]
Looks similar to angular/angular#7395

**Comment by natebosch** [comment]
I think recent versions of the Dart SDK are not exhibiting this problem on either Mac or Linux. Please add a comment with repro instructions if this is still occurring.
