### ISSUE TITLE
Intermittent `pub serve` error

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub#1404]
I'm testing a bunch of samples, using the command `pub upgrade; pub serve`. (I do this every time angular2 upgrades. So much fun.) It usually works, but a few times today, I've gotten an error like this from pub serve:

```
Loading angular2 and dart_to_js_script_rewriter transformers... (2.3s) 
Class 'String' has no instance getter '_nextListener'.

NoSuchMethodError: method not found: '_nextListener'
Receiver: "set:trace"
Arguments: []
dart:isolate  _RawReceivePortImpl._handleMessage
This is an unexpected error. Please run

    pub --trace serve

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

The next time I ran it, it had no problems and --trace didn't produce any interesting output.

Might this be related to my recent update from 1.16.0-dev.3.0 to 1.16.0-dev.5.0?

```
$ pub --version
Pub 1.16.0-dev.5.0
```

cc @nex3

**Comment by nex3** [comment]
Pub doesn't include the token `_nextListener`, but `dart:async` does—it's conceivable this is a bug there.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
