### ISSUE TITLE
prevent publishing package with `PaxHeaders`

### ISSUE THREAD

**Issue by jeffbcross** [dart-lang/pub#1411]
When publishing `angular2`, there have been a couple of occasions where we've inadvertently published packages that include `PaxHeaders` directories in the artifact. This doesn't seem to be related to a dart SDK version, more the tar configuration on the machine of whomever is publishing the release. Including these `PaxHeaders` directories causes errors for users on Windows machines: https://github.com/angular/angular/issues/7395.

Maybe the best option would be to specify a format when calling `tar` here, though I'm not sure which format is most appropriate:
https://github.com/dart-lang/pub/blob/c1405b945c6d818c8cfe78334e8d4b11fd913103/lib/src/io.dart#L1005

**Comment by zoechi** [comment]
Looks like #1402
