### ISSUE TITLE
Weird message on pub get: "A transformer imported unknown package "args" (in "package:args/args.dart")."

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/pub#1414]
This issue appears when adding a dependency on the [archive package](https://pub.dartlang.org/packages/archive).

```sh
$ pub --version
Pub 1.16.0
```

Repro steps:
- create new folder
- create `pubspec.yaml' in new folder with following content:
```
name: bogus
dependencies:
  archive: ^1.0.20
```
- run `pub get`

Output:
```sh
Resolving dependencies... 
Downloading archive 1.0.20...
Downloading crypto 0.9.2+1...
Downloading charcode 1.1.0...
Downloading convert 1.1.1...
Downloading typed_data 1.1.2...
Got dependencies!
Precompiling executables... 
Loading source assets...
A transformer imported unknown package "args" (in "package:args/args.dart").
```

Note that I've used the `args` package in other projects so it is likely in the pub cache. However I ran the same commands after emptying the cache and the results were the same.

**Comment by nex3** [comment]
This is a bug in the `archive` package. [`bin/tar.dart`](https://github.com/brendan-duncan/archive/blob/master/bin/tar.dart) imports `args`, but its pubspec doesn't declare a dependency on it.

**Comment by brendan-duncan** [comment]
I updated the dependencies in archive.
