### ISSUE TITLE
pub cache repair uses hardcoded https rather than using protocol from pubspec

### ISSUE THREAD

**Issue by jeffascentis** [dart-lang/pub#1418]
Example pubspec.yaml:
     dart_example:
      version: "0.1.1"
      hosted:
       name: dart_example
       url: http://pub.company.com/

Error message when running "pub cache repair":
  Failed to repair dart_example 0.1.1 from https://pub.company.com/. Error: HandshakeException: Handshake error in client (OS Error: error:100bd10c:SSL routines:ssl3_get_record:WRONG_VERSION_NUMBER)

Notice the https in the error message.

**Comment by zoechi** [comment]
`pub cache repair` is not and can not be related to any `pubspec.yaml`. You might want to delete `~/.pub-cache/hosted/`manually and run `pub get` from a concrete project directory that contains a `pubspec.yaml`.

**Comment by jeffascentis** [comment]
I understand that.  I was just giving a way to reproduce the problem.  Even though those packages are downloaded via http by "pub get," "pub cache repair" is trying to download them with https.
