### ISSUE TITLE
Distribute-able command line applications using Dart

### ISSUE THREAD

**Issue by tejainece** [dart-lang/pub#1419]
We need a way to package and distribute Dart command line applications with no dependency on Dart VM.

It is not always guaranteed that the end user's system has DartVM installed.

A way to package DartVM and snapshot into single executable with no external dependencies would be great.

**Comment by zoechi** [comment]
You can ship the `dart.exe` with a snapshot file of your application. No need to install the whole SDK this way.

**Comment by nex3** [comment]
This is out-of-scope for pub. It's something that would need to be handled by the core SDK, in the form of a standalone executable compiler or something similar.
