### ISSUE TITLE
`--verbosity solver` should include sdk version constraints

### ISSUE THREAD

**Issue by johnbcoughlin** [dart-lang/pub#1420]
Trying to install a package which requires a different SDK version will just look like dart can't find the package. E.g:

```
$ curl https://pub.dartlang.org/api/packages/csv | python -mjson.tool
...
         {
            ...
                "environment": {
                    "sdk": ">=1.11.0 <1.16.0"
                },
                "name": "csv",
                "version": "3.0.1"
            },
            "version": "3.0.1"
        }
```

So the 3.0.1 version won't work on Dart v1.16.0. The `pub get` messages don't give an indication that this is why the install is failing. Instead, it looks like pub is just mysteriously skipping that version:

```
$ pub get
...
| | * select pub itself
| | | version 2.0.1 of csv doesn't match >=3.0.1 <4.0.0:
| | |   inscriptive_web 0.0.1 (root) -> csv ^3.0.1 from hosted (csv)
| | | version 2.0.0 of csv doesn't match >=3.0.1 <4.0.0:
| | |   inscriptive_web 0.0.1 (root) -> csv ^3.0.1 from hosted (csv)
BacktrackingSolver took 0:00:03.133700 seconds.
- Requested 24 version lists
- Looked up 2 cached version lists

Package csv has no versions that match >=3.0.1 <4.0.0 derived from:
- inscriptive_web depends on version ^3.0.1
```

It seems that you have to curl the package version list yourself to discover this SDK version dependency. Even just displaying that info, e.g. here: https://pub.dartlang.org/packages/csv would be a huge difference in interpretability.

Thanks!

**Comment by zoechi** [comment]
see #912

**Comment by johnbcoughlin** [comment]
Ah, cool, thanks. Ironically, the current name of that omnibus issue is just as bad as the error message I described. ;)

**Comment by nex3** [comment]
Yeah, I'm going to mark this as a duplicate. I've also updated the name of #912.
