### ISSUE TITLE
The "pub" script in the repo doesn't support ARM

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1422]
_From @Hixie on June 5, 2016 7:33_

The sdk/bin/ directory in the dart-sdk repository has various shell scripts. The "dart" shell script tries to find the "best" out/ directory and run dart from there. The "pub" shell script, however, only looks for ReleaseX64.

This means that when you're using a local Dart repo checkout on an ARM system, and have locally built the tools, the "pub" script doesn't work, even though the "dart" one does.

Copying the logic from the "dart" script to the "pub" script fixes it.

_Copied from original issue: dart-lang/sdk#26621_

**Comment by nex3** [comment]
This really shouldn't be in the pub repo; those scripts are maintained in the SDK repo, and usually only modified by the SDK maintainers.
