### ISSUE TITLE
Misleading relative path error message

### ISSUE THREAD

**Issue by jimbeveridge** [dart-lang/pub#1423]
I ran `pub get` and depended on a package that uses a relative path. The relative path couldn't be resolved, so an error message is expected. Here's what I got:

```
Running 'pub get' in myapp...                          
Error on line 16, column 11: Invalid description: "../flutter/packages/flutter" is a relative path, but this isn't a local pubspec.
    path: ../flutter/packages/flutter
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The problem with this error message is that the error is in Line 16 of the dependent package, not the current package. The error message needs to include the path to the `pubspec.yaml` where the error was found. Apparently, this path should be the antecedent for the word "this" as used in "but this isn't..."

**Comment by sigurdm** [comment]
We now do proper source-spans of formatexceptions when parsing a pubspec.yaml:

https://github.com/dart-lang/pub/blob/70a3884ad7f06b599325f8f42b858193eb167698/lib/src/exceptions.dart#L158

```
> dart pub get
Resolving dependencies... 
Error on line 5, column 3 of m/pubspec.yaml: "dependencies" field must be a map.
  ╷
5 │   []
  │   ^^
  ╵
```

(here `m` is a path dependency in the nested folder `m`)
