### ISSUE TITLE
FILEEXCEPTION - pubspecs.yaml

### ISSUE THREAD

**Issue by drk94** [dart-lang/pub#1426]
[logdart.txt](https://github.com/dart-lang/pub/files/333233/logdart.txt)

**Comment by zoechi** [comment]
> Could not find a file named "pubspec.yaml" in "/home/daw/eclipse/javascript-neon/eclipse/dart-sdk/bin".

`dart-sdk/bin` is not supposed to contain a `pubspec.yaml` file.
> Pub 1.17.1

As far as I know the Eclipse plugin is not supported anymore.

What were you trying to do when you got the error message?

**Comment by nex3** [comment]
What command did you execute that produced this error? Can you include a minimal package that reproduces the error?

**Comment by natebosch** [comment]
Please make sure your working directory is a pub package with a `pubspec.yaml` file before you run a `pub` command.
