### ISSUE TITLE
"pub run" doesn't run local binary unless ".dart" is added

### ISSUE THREAD

**Issue by skybrian** [dart-lang/pub#1428]
After creating a file named

     bin/hello.dart

I try to run it using "pub run":

    $ pub run hello.dart
    hello!
    $ pub run hello
    Could not find package "hello". Did you forget to add a dependency?

According to the documentation, the ".dart" extension shouldn't be necessary:

https://www.dartlang.org/tools/pub/cmd/pub-run.html

This is using Dart 1.17.1.

**Comment by nex3** [comment]
This is intended. The documentation is out-of-date.

**Comment by nex3** [comment]
I've filed dart-lang/www.dartlang.org#1588 to track updating the documentation.

**Comment by nex3** [comment]
Actually, the documentation is right. The crucial issue here is that `pub run` interprets a valid Dart identifier as identical to `hello:hello`, never as `hello.dart`.
