### ISSUE TITLE
Package tests fail on windows with incorrect paths

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub#1429]
On the windows package test bots pkg-win-be and pkg-win-debug-be, on the Dart waterfall, tests are failing when they report absolute windows paths where a different absolute unix path is expected, as in the error message

FAIL: AbstractContextManagerTest | test_setRoots_addFolderWithPackagespec
  Expected: '/home/somebody/.pub/cache/unittest-0.9.9/lib/unittest.dart'
    Actual: 'E:\\b\\build\\slave\\pkg-win-be\\build\\sdk\\home\\somebody\\.pub\\cache\\unittest-0.9.9\\lib\\unittest.dart'
     Which: is different.
  Expected: /home/some ...
    Actual: E:\\b\\bui ...
            ^
   Differ at offset 0

**Comment by whesse** [comment]
The tests that fail are:
pkg/analysis_server/test/context_manager_test
analysis_server/test/context_manager_test:
analyzer/test/generated/source_factory_test
analyzer/test/src/context/builder_test
analyzer/test/src/summary/linker_test
analyzer/test/src/summary/prelinker_test
analyzer/test/src/summary/summarize_elements_strong_test
analyzer/test/src/summary/summarize_elements_test

**Comment by nex3** [comment]
Why isn't this filed against the analysis server?

**Comment by whesse** [comment]
Because it has to do with package downloads and the pub cache.  I couldn't tell just from the first glance which component had the problem.  If this is working as intended, then I'll file it against the analyzer.  I'll link to this issue, so they can see that pub is working as intended.

**Comment by nex3** [comment]
The test that's making assertions about those paths is in the analyzer, so it's probably that test that's failing to handle Windows paths correctly.
