### ISSUE TITLE
pub global activate shows wrong error message about pub-cach/bin in PATH

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1430]
_From @MikeMitterer on July 6, 2016 9:5_

After making a package globally available I get this error message:

```bash
Warning: Pub installs executables into ~/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"~/.pub-cache/bin"
```
I don't know why pub thinks it is not on my path????
Everything works as expected but this message is a bit annoying.
 
![screenshot-1607063](https://cloud.githubusercontent.com/assets/116654/16612341/c6c1f54a-4366-11e6-9522-0c315e7c0bb6.jpg)

- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64"
Pub 1.17.1

_Copied from original issue: dart-lang/sdk#26829_

**Comment by nex3** [comment]
Pub runs `which` to determine whether the executable is actually detectable on your path. What happens if you run `which changelog`?

**Comment by MikeMitterer** [comment]
which cl - fails 
type cl - works
command cl - works
whatis cl - works

So maybe you shouldn't use which

**Comment by nex3** [comment]
It sounds like your `which` command is broken somehow. I don't think it makes sense to change pub's implementation to work around that—`which` is the most widely-available and simplest command that does exactly what we need.

**Comment by MikeMitterer** [comment]
Really - it doesn't work and you label it "as designed"????? 
Check this out: http://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

**Comment by floitschG** [comment]
Fwiw the link actually states that you might want to use `switch` when running an external command.
Otherwise you would need to spawn a new shell, which imho makes things again more complicated.

**Comment by nex3** [comment]
Okay, it looks like switching to `sh -c command` makes sense.

**Comment by hpoit** [comment]
Hi, do I have the same issue? 
```
-MBP:~ johnappleseed$ pub global activate peanut
Package peanut is currently active at version 3.2.1.
Resolving dependencies... (4.7s)
...
Precompiling executables... (1.8s)
Precompiled peanut:peanut.
Installed executable peanut.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated peanut 3.2.1.
-MBP:~ johnappleseed$ 
```
I've pasted `export PATH="$PATH":"$HOME/.pub-cache/bin"` onto `.bashrc`, `.bash_profile`, and `.profile`

**Comment by hpoit** [comment]
Hi, do I have the same issue? I've added `export PATH="$PATH":"$HOME/.pub-cache/bin"` to  `.bashrc`, `.bash_profile`, and `.profile`, but still get:
```
-MBP:~ johnappleseed$ pub global activate peanut
Package peanut is currently active at version 3.2.1.
Resolving dependencies... (4.7s)
...
Precompiling executables... (1.8s)
Precompiled peanut:peanut.
Installed executable peanut.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated peanut 3.2.1.
-MBP:~ johnappleseed$ 
```

**Comment by hpoit** [comment]
I'm sorry, I forgot to restart the terminal.

**Comment by Achille-Bosc** [comment]
I got the same problem but I don't find the `.zshrc` file or the `.bashrc`, `.bash_profile` and `.profile` files in my macOs Finder... it's so problematical to use the framework ! For me, it's to install the `flutterfire_cli` framework to work with flutter and use firebase. (it's write in the firebase doc to execute this command)

**Comment by sigurdm** [comment]
> I don't find the .zshrc

You need to create it. See https://superuser.com/a/886135

**Comment by Achille-Bosc** [comment]
> > I don't find the .zshrc
> 
> You need to create it. See https://superuser.com/a/886135

Thanks very much for your help ! It helped me so much !
