### ISSUE TITLE
Problem when try to run / debug project in eclipse

### ISSUE THREAD

**Issue by Vincent-ILM** [dart-lang/pub#1434]
Hi,

When I try to run / debug my project, this error occur:
"Could not start pub serve or connect to pub"

And I can see this in stack trace:
'package:web_socket_channel/src/channel.dart': malformed type: line 65: type 'SHA1' is not loaded
    var hash = new SHA1();

And when I run this command:
pub --trace serve web --port 8080 --admin-port 35506 --hostname localhost

All work perfectly, but I can't use eclipse debug mode like this

Dart editor version: 1.12.0.201509241517
Dart SDK version: 1.17.1
Eclipse version: eclipse-neon (4.6.0) - 20160613-1800

Cordially,
Vincent THIBAUT

**Comment by nex3** [comment]
Does this reproduce on a recent Dart SDK when using `pub serve` directly from the command line? If so, can you post your `pubspec.yaml`, `pubspec.lock`, and the full output of `pub serve --verbose`?

**Comment by Vincent-ILM** [comment]
pubspec.lock:

# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.26.4"
  animation:
    description:
      name: animation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.24"
  archive:
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.24"
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4+2"
  async:
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  barback:
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+8"
  browser:
    description:
      name: browser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0+2"
  charcode:
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  cli_util:
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description:
      name: code_transformers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.11"
  collection:
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  convert:
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  crypto:
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  csslib:
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.2"
  glob:
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  html:
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2+2"
  html5lib:
    description:
      name: html5lib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.1"
  logging:
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  package_config:
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  path:
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.9"
  plugin:
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  pool:
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  script_inliner:
    description:
      name: script_inliner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  source_maps:
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.1+1"
  source_span:
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.3"
  stack_trace:
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.6"
  string_scanner:
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  typed_data:
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  unittest:
    description:
      name: unittest
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.6+4"
  utf:
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+3"
  watcher:
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+2"
  when:
    description:
      name: when
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  which:
    description:
      name: which
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  yaml:
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.10"
sdk: ">=1.17.0-dev.6.2 <2.0.0"


pubspec.yaml:

name: OpenConcertoBlack
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  animation: any
  archive: any
  browser: any
  html: any
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- $dart2js:
    checked: true
    csp: true
    minify: true
    sourceMaps: true
    suppressHints: true
    suppressWarnings: true
    terse: true
    verbose: true
- script_inliner


pub serve --verbose:

FINE: Pub 1.17.1
FINE: Loading asset environment...
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
MSG : Loading source assets...
FINE: Providing sources for OpenConcertoBlack|lib.
FINE: Loading source assets finished (0.006s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
    | script_inliner: -
FINE: Using cached transformer snapshot.
MSG : Loading script_inliner transformers...
FINE: Loading transformers from [script_inliner]
FINE: Spawning isolate from ./.pub/transformers/transformers.snapshot.
FINE: Loading script_inliner transformers finished (0.051s).
FINE: Transformers from script_inliner: {ScriptInlining}
FINE: Loading transformers finished (0.175s).
FINE: Initializing barback finished (0.213s).
FINE: Loading asset environment finished (0.424s).
FINE: Providing sources for OpenConcertoBlack|web.
FINE: Bound "web" to localhost:8080.
MSG : Serving OpenConcertoBlack web on http://localhost:8080
MSG : Build completed successfully

I will try with development version

**Comment by Vincent-ILM** [comment]
----------- pubspec.lock ----------

packages:
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.26.4"
  animation:
    description:
      name: animation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.24"
  archive:
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.24"
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4+2"
  async:
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  barback:
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+8"
  browser:
    description:
      name: browser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0+2"
  charcode:
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  cli_util:
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description:
      name: code_transformers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.11"
  collection:
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  convert:
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  crypto:
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  csslib:
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.2"
  glob:
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  html:
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2+2"
  html5lib:
    description:
      name: html5lib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.1"
  logging:
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  package_config:
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  path:
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.9"
  plugin:
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  pool:
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  script_inliner:
    description:
      name: script_inliner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  source_maps:
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.1+1"
  source_span:
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.3"
  stack_trace:
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.6"
  string_scanner:
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  typed_data:
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  unittest:
    description:
      name: unittest
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.6+4"
  utf:
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+3"
  watcher:
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+2"
  when:
    description:
      name: when
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  which:
    description:
      name: which
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  yaml:
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.10"
sdk: ">=1.17.0-dev.6.2 <2.0.0"


----------- pubspec.yaml ----------

name: myProject
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  animation: any
  archive: any
  browser: any
  html: any
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- $dart2js:
    checked: true
    csp: true
    minify: true
    sourceMaps: true
    suppressHints: true
    suppressWarnings: true
    terse: true
    verbose: true
- script_inliner


----------- pub serve --verbose ----------

FINE: Pub 1.17.1
FINE: Loading asset environment...
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
MSG : Loading source assets...
FINE: Providing sources for myProject|lib.
FINE: Loading source assets finished (0.006s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
    | script_inliner: -
FINE: Using cached transformer snapshot.
MSG : Loading script_inliner transformers...
FINE: Loading transformers from [script_inliner]
FINE: Spawning isolate from ./.pub/transformers/transformers.snapshot.
FINE: Loading script_inliner transformers finished (0.051s).
FINE: Transformers from script_inliner: {ScriptInlining}
FINE: Loading transformers finished (0.175s).
FINE: Initializing barback finished (0.213s).
FINE: Loading asset environment finished (0.424s).
FINE: Providing sources for myProject|web.
FINE: Bound "web" to localhost:8080.
MSG : Serving myProject web on http://localhost:8080
MSG : Build completed successfully


I will try with dev version

**Comment by Vincent-ILM** [comment]
It's work with SDK 1.18.0-dev.4.4
