### ISSUE TITLE
Pub Tar issue

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1438]
_From @esnortel on August 8, 2016 18:22_

1.17.1 added in a change for cross-platform issues with tar (https://github.com/dart-lang/pub/issues/1411), unfortunately the ustar format doesn't handle large user ids. We use Active Directory and the user ids for our developers are large (876765912), the tar command errors out when this happens. stderr is not caught and there is no evidence that the command fails until the tar file is examined and is unreadable.

The error message that tar generates is
tar: catalina.out: Numeric user ID too largeNumeric group ID too large

pub version - 1.17.1
platform - mac (10.11.5), centos 7, windows

_Copied from original issue: dart-lang/sdk#27039_

**Comment by mit-mit** [comment]
@nex3, a regression from #1311

**Comment by nex3** [comment]
@esortel: If you run `tar --owner=_ --group=_ --format=ustar -czf some_directory` locally, does it work? We don't actually need valid user/group information in there, so it seems like the easiest way around this would be to omit it entirely.

**Comment by esnortel** [comment]
Short answer, for us —owner=0 —group=0 works (underscores don’t).

On linux (gnu tar 1.26) the owner and user arguments need to be numeric. 
On mac the default tar is bsd tar (2.8.3), which doesn’t support the owner and group arguments. 
Installed gnu tar on the mac (gnu tar 1.29) using _ for user and group doesn’t work, it tries to use the original uid/gid, however using 0 for the uid/gid works.
