### ISSUE TITLE
pub crash serving observatory

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1449]
_From @B3rn475 on September 2, 2016 16:38_

`pub serve` from `runtime/observatory/` crashes with error

```
Build error:
Transform IndexPageBuilder on observatory|all_entry_points threw error: 'package:$pub/serialize.dart': malformed type: line 103 pos 14: type 'LazyStream' is not loaded
  return new LazyStream(() {
```

_Copied from original issue: dart-lang/sdk#27228_

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
