### ISSUE TITLE
Change the default of --packages-dir to false

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1450]
It's currently `true`. We'd like to get this change in SDK 1.20

**Comment by alexander-doroshko** [comment]
> We'd like to get this change in SDK 1.23

@kevmoo You've set milestone to 1.20 in https://github.com/dart-lang/sdk/issues/27399, which number is correct? ;)

**Comment by kevmoo** [comment]
@alexander-doroshko our ever vigilant community 😉

**Comment by munificent** [comment]
On it.
