### ISSUE TITLE
'pub get' with proxy with authentication gives an error for Angular2 package

### ISSUE THREAD

**Issue by sinkevichmm** [dart-lang/pub#1452]
I had  error (Proxy with authentication).

in [quickstart](https://github.com/angular-examples/quickstart)

```
Resolving dependencies...
Got dependencies! Precompiling dependencies...
Loading source assets...
Loading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smoke/src/default_transformer transformers...
Transformer library "package:angular2/transform/codegen.dart" not found.
```

[pub_upgrade_verbose.txt](https://github.com/dart-lang/pub/files/494532/pub_upgrade_verbose.txt)

how to fix this?

WIN7 X64 without admin's privileges
Dart SDK 1.19.0

**Comment by sinkevichmm** [comment]
Dart SDK 1.20 - still not working

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
