### ISSUE TITLE
ProxyPass like feature for "pub serve"

### ISSUE THREAD

**Issue by woosanghun** [dart-lang/pub#1457]
It would be nice to be able to specify a path and redirect it to another server, for example to a rest server.   In the pubspec.yaml you'd write something like this: 

```
 proxypass: /rest   http://localhost:9090/myService/rest
```

Anything that is prefixed with /rest would then be redirected to a separate server.   That way my Angular Dart application could make the rest call because the application and server would look like they were from the same server/port to the browser.

Let me know if such a feature already exists or there was another way this was meant to be done.

Thanks!

Simon

**Comment by zoechi** [comment]
It's usually suggested to use it the other way around so that your development server or a proxy before the development server redirects calls for Dart sources to `pub`.

**Comment by woosanghun** [comment]
This is easy on my own PC, but at work, it's a hassle installing software, not everyone has admin to their own machine, so a feature like this makes it easier to setup the dev environment.   When we deploy, we'll use Apache to handle this.

**Comment by zoechi** [comment]
In deployment you don't need `pub serve` therefore this shouldn't be an issue.

**Comment by woosanghun** [comment]
Correct, this has nothing to do with production deployment.   The idea was to eliminate the need to install & configure Apache for the development environment, primarily to make adoption easier for Java developers that already have a REST service and want to update their front-end.

**Comment by unibeck** [comment]
What's the status on this? Any update on this to allow pub serve to act as a proxy for client side applications? Particularly one that works with AngularDart
