### ISSUE TITLE
Faster pub build

### ISSUE THREAD

**Issue by buchanae** [dart-lang/pub#1458]
`pub build` for my dead-simple angular2 quickstart project takes about 10-15 seconds. If I change one line and rebuild, that's a pretty slow process.

I'm using `pub build` and not `pub serve` on purpose. My use case is that I'm trying to develop an electron app. I'm sure there are other valid use cases for using your own server.

JS projects usually have solutions for this issue, and it seems `pub serve` has something as well (i.e. pub serve rebuilding is fast). Question is, can `pub build` support a similar solution? Or, taken from another angle, can `pub serve` write it's output to the file system?

I suspect most of the time is spent loading, because of lines like this:

```
Loading angular2 transformers... (5.1s)
```

Apologies if you've answered this before. I did search the issue tracker and saw some possibly related conversations, but I wasn't crystal clear.

Thanks!

**Comment by nemequ** [comment]
"Faster" is nebulous… maybe this bug should be renamed to target something specific.  I'm guessing incremental builds would be the largest single improvement here, followed by parallelization.

**Comment by abuchanan** [comment]
I agree, although I purposefully wrote a vague title because I'm not exactly sure what the actionable items and priorities are, and wanted to open a discussion more specific issues to target.

**Comment by zoechi** [comment]
DDC is work in progress and supports incremental build AFAIK.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
