### ISSUE TITLE
Pub "get" locks at "Loading transformers..."

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1460]
This is for `package:angular2`. Is there anyway I can debug this to help report what is going on?

(Work around is `pub get --no-precompile`)

**Comment by nex3** [comment]
You can always pass `--verbose` to get more debugging information, although the info around transformer loading isn't the best. If that doesn't provide the details you need, you could attach the observatory to pub by hacking the startup script in the SDK.
