### ISSUE TITLE
Don't change .packages if pub get doesn't change anything

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub#1464]
Currently, running pub get changes the timestamp in the .packages file, even if there is a pubspec.lock and no new package versions are fetched, and the .packages file isn't changed.

This makes it hard to have a committed .packages file, the way that is suggested for apps.

@sortie @nex3

**Comment by nex3** [comment]
This behavior is important to pub's logic for quickly determining if `pub get` needs to be run, e.g. before invoking the executable for `pub run`. We use relative timestamps as the fastest check for the common case where everything's up-to-date.

> This makes it hard to have a committed .packages file, the way that is suggested for apps.

No one should ever commit the `.packages` file to source control; its contents are highly contingent on the host machine. Applications should only commit the `pubspec.lock` file. Also, as far as I know most source control doesn't care about timestamps.
