### ISSUE TITLE
Pub lish should resolve symbolic link and grab file content

### ISSUE THREAD

**Issue by a14n** [dart-lang/pub#1465]
_Version: Pub 1.20.1_

I splitted my `zengen` package into 2 packages (one for annotations and one for the generator). To avoid file duplications I used symbolic links for `README.md`, `LICENSE` and `CHANGELOG.md` (you can see that in the [zengen](https://github.com/a14n/zengen) repository - `generator/README.md` points to `README.md`)

After `pub lish` for the 2 packages the README.md and CHANGELOG.md are not displayed on the [zengen pub page](https://pub.dartlang.org/packages/zengen) but it should.

**Comment by nex3** [comment]
I think the current behavior of preserving symbolic links in the tar file is important—it keeps users from accidentally making their uploaded artifact much larger than they expected. However, I encourage you to file an issue against [pub-dartlang-dart](https://github.com/dart-lang/pub-dartlang-dart) to handle this properly when detecting files for page generation.

**Comment by a14n** [comment]
@nex3 I agree for link internal to the tar file. But here the link is outside of it (you can check https://storage.googleapis.com/pub.dartlang.org/packages/zengen_generator-0.4.0.tar.gz) and the target of the link does not exist inside the tar. So [pub-dartlang-dart](https://github.com/dart-lang/pub-dartlang-dart) cannot do anything.

**Comment by nex3** [comment]
Maybe a better way to frame this is, we should match the behavior of `git archive` as much as possible. We've had requests in the past to support workflows based on publishing directly from Git rather than from the local filesystem, and the closer those two workflows can match up the better.

**Comment by a14n** [comment]
Thanks for the explanations. I will replace my symbolic links.
