### ISSUE TITLE
Pub serve

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub#1468]
_From @arcas0803 on November 4, 2016 17:17_

When i stop pub serve from terminal it doesn't close the socket, so when i start again it gives me this error:

> Failed to create server socket (OS Error: Address already in use, errno = 48), address = 127.0.0.1, port = 9095

_Copied from original issue: dart-lang/sdk#27761_

**Comment by anders-sandholm** [comment]
_From @zoechi on November 4, 2016 20:45_

What OS? What Dart version?

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
