### ISSUE TITLE
Confused by the docs for caret constraints

### ISSUE THREAD

**Issue by adamlofts** [dart-lang/pub#1469]
On this page: https://www.dartlang.org/tools/pub/dependencies#version-constraints

The first example of a caret constraint (right at the top of the page) is given as:

```
dependencies:
  transmogrify: ^=1.0.0
```
In the caret syntax section the syntax is given as ^version and the example is:
```
dependencies:
  path: ^1.3.0
```

Is ^= a valid syntax for a constraint? Or perhaps the version of transmogrify is "=1.0.0".

**Comment by zoechi** [comment]
I think https://github.com/dart-lang/site-www would be the right repo for reporting this issue

**Comment by nex3** [comment]
This issue was moved to dart-lang/site-www#168
