### ISSUE TITLE
Feature: ability to see all packages that use a package

### ISSUE THREAD

**Issue by gedw99** [dart-lang/pub#1470]
Use case:
I am looking at a package and want to see how others use it.
I might also want to see how popular the package is in terms of who uses the package.

It's a form of discovery and I use it allot with golang. Would be very nice to have this with dart.

In golang " go doc " supports this and it's super useful.
I can send you a link if your curious.

**Comment by gedw99** [comment]
Oh and my suggestion is for this to be added to the web UI. Adding it to the local tool is also good but web UI is where I see the most value for me and others initially

**Comment by zoechi** [comment]
This would be a a feature request for https://github.com/dart-lang/pub-dartlang-dart

You can use one of
https://pub.dartlang.org/packages/pub_client
https://pub.dartlang.org/packages/bwu_pub_client
to fetch the information yourself or use the source to learn how the API looks an use plain JSON REST to fetch the data.

**Comment by gedw99** [comment]
OK I created the issue on their github repository
