### ISSUE TITLE
Insufficient error message "A transformer imported unknown package"

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/pub#1473]
I added:
archive: any

... to my dependencies, after "pub get" I received following error message:
A transformer imported unknown package "args" (in "package:args/args.dart").

It's probably something wrong with "archive" package, but the error message should contain more information: which transformer and more importantly - which package.

(I added several dependencies in one step so it took some fiddling to find out which dependency broke my project).

**Comment by zoechi** [comment]
Could it be that some dependency limits the `archive` version to an older version?
This or a similar issue was reported and fixed a few months ago #1414

**Comment by Tomucha** [comment]
Resolved version is 1.0.27.
Let's focus on the error message here :-)

**Comment by nex3** [comment]
Yeah, this message is pretty busted, especially since the error in this case doesn't have anything to do with transformers at all.
