### ISSUE TITLE
Dart transformer unable to access local codegen.dart file for Angular2Dart quickstart

### ISSUE THREAD

**Issue by mvlazar** [dart-lang/pub#1474]
Given the following environment:
- windows 10 machine
- dart-sdk-1_20_1

When I try to create the AngularDart [quickstart project](https://angular.io/docs/dart/latest/quickstart.html) I get the following error when running pub get:

ERR : Transformer library "package:angular2/transform/codegen.dart" not found.

I am behind a firewall and proxy, but the http_proxy and https_proxy are set and the local pub cache is filled. The root of the error seems to be:

FINE: Wrapped exception: Unable to spawn isolate: Unhandled exception:
    | Could not import "package:angular2/transform/codegen.dart" from "file:///C:/Users/localUser/AppData/Local/Temp/pub_edec2900-b22e-11e6-8dab-50465d2e52ac/runInIsolate.dart": Failure getting http://localhost:1182/packages/angular2/transform/codegen.dart:
    |   503 Service Unavailable

Is it expected for the transformer to spawn a local process to serve the codegen.dart ? The file is downloaded and placed in the local pub cache.
Attached is the verbose output from the pub command.
[output.txt](https://github.com/dart-lang/pub/files/611173/output.txt)

This issue is similar to #1406 and #1397

**Comment by matanlurey** [comment]
@mvlazar Is this still occurring for you?

**Comment by mvlazar** [comment]
Yes, the issue occurred last time I've checked with SDK 1_21_1. Only behind corporate firewall.

**Comment by emvev** [comment]
I found out this behavior:

when http_proxy and https_proxy is set:
```
$ pub get
Resolving dependencies...
Got dependencies!
Precompiling dependencies...
Loading source assets...
Loading angular2/transform/codegen and dart_to_js_script_rewriter transformers...
Transformer library "package:angular2/transform/codegen.dart" not found.
```
after 
```
$ export https_proxy=
```
The result is the same, but after
```
$ export http_proxy=
$ pub get
Resolving dependencies...
Got dependencies!
Precompiling dependencies...
Loading source assets...
Loading angular2/transform/codegen and dart_to_js_script_rewriter transformers... (5.4s)
Precompiled angular2, dart_style, dart_to_js_script_rewriter and intl.
```

**Comment by jsarracco** [comment]
I was missing `127.0.0.1 localhost` from my hosts file after migrating to a new computer. After I added the host setting it started working again.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
