### ISSUE TITLE
Never run untransformed global executables against a barback server

### ISSUE THREAD

**Issue by John0x** [dart-lang/pub#1477]
Hey, I need to get the absolute path of my script which is being run with pub global run.
The problem is that Platform.script gives me a localhost uri and not the file path.

I need the file path since I need to iterate over files within my package directory.

**Comment by nex3** [comment]
`Platform.script` is generally unreliable and shouldn't be used. It's too sensitive to the exact circumstances under which the Dart entrypoint was loaded, which tools (including pub) need to be able to vary. If you need to find the location of your package on disk, I suggest using [`Isolate.resolvePackageUri()`](https://api.dartlang.org/stable/1.20.1/dart-isolate/Isolate/resolvePackageUri.html) or the [`package_resolver`](https://pub.dartlang.org/packages/package_resolver) package that wraps it.

**Comment by John0x** [comment]
@nex3 they both give me the uri not the path. And I cannot generate a path from that.

````
  String packPath = path.fromUri(await Isolate.resolvePackageUri(Uri.parse('package:dangular_cli/angular_cli.dart')));
````

Gives me:
````
Invalid argument(s): Uri http://localhost:44832/packages/dangular_cli/angular_cli.dart must have scheme 'file:'.
````

**Comment by nex3** [comment]
Ah, it looks like you're running in a transformer environment. In that case, I'm afraid there's no way to do this; as far as Dart knows, your code only exists on an HTTP server. And in general, that's accurate; transformers can do anything including adding files, so it's not safe to assume that what exists on disk has any particular bearing on what the "real" contents of your package is.

**Comment by John0x** [comment]
@nex3 no, it's not a transformer. It's just a cli being run with pub global.
Just a typical console application.

**Comment by nex3** [comment]
Oh, it looks like we may still be running global executables using a server when we don't need to. I'll look into it.

**Comment by John0x** [comment]
@nex3 great, thanks :)
Would be awesome to get this fixed soon, since I've got a project on hold because of this.
