### ISSUE TITLE
Allow pub serve to run a secure connection / pub serve fails if HTTP Strict Transport Security (HSTS) is enabled

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1484]
_From @MikeMitterer on December 6, 2016 10:21_

E.g. with python you can specify a certfile and a keyfile then it runs a secure connection
```python
    import http.server
    import socketserver
    import ssl

    PORT = 7000

    # 0.0.0.0 allows connections from anywhere
    httpd = http.server.HTTPServer(('0.0.0.0', PORT), http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./jetty.crt', keyfile='./jetty.key', server_side=True)

    print("serving at port", PORT)
    httpd.serve_forever()
```

We need something like this for pub (and also for tests via content-shell or dartium)

_Copied from original issue: dart-lang/sdk#28001_

**Comment by floitschG** [comment]
_From @MikeMitterer on December 6, 2016 11:56_

If HTTP Strict Transport Security is enabled on the server side the server tells the client to switch to https - if pub server cannot handle this request it brings a 404

**Comment by floitschG** [comment]
_From @MikeMitterer on December 6, 2016 12:53_

It's quite annoying! I have to turn off https on the server side because pub is not able to serve a secure connection.

**Comment by MikeMitterer** [comment]
OK - until pub supports this I implemented this functionality into **sitegen** 
More: https://pub.dartlang.org/packages/sitegen

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
