### ISSUE TITLE
pub.dartlang.org won't work thru firewall but github does

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1501]
_From @theiceguy on January 17, 2017 12:23_

Make it so all pub packages are mirrored in github, and can be downloaded via github.

_Copied from original issue: dart-lang/sdk#28419_

**Comment by floitschG** [comment]
_From @lrhn on January 17, 2017 12:55_

That's not really a thing the Dart team can do. Pub packages are managed by their individual authors, and while most of them do use github, not all do, and we don't want to force anyone to do so (even if we could).

If you're only talking about the Dart team authored packages, then *most* of them are on Github, like https://github.com/dart-lang/collection. A few only exists inside the SDK repo, but that is technically on Github (https://github.com/dart-lang/sdk/tree/master/pkg). 

Is there a specific package you are interested in?

**Comment by floitschG** [comment]
_From @theiceguy on January 17, 2017 13:27_

Maybe we just need a sample pubspec.yaml where all the base packages are pulled down from github?  And there is no dependency whatsoever on pub.dartlang.org.

**Comment by theiceguy** [comment]
Perhaps I'm asking for the moon.  Being able to resolve all pub dependencies automatically, somehow, via github, would be really nice.

**Comment by nex3** [comment]
GitHub explicitly discourages people from using it as a canonical package host. You're welcome to use Git dependencies where possible in your pubspec, but we won't be using it as a mirror.
