### ISSUE TITLE
'pub run test -r json' hangs

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/pub#1502]
I'm not sure whether the problem is at SDK, pub or package:test end. Filing it here because the bug is specific to the SDK version, but not specific to the package:test version.

OS: Windows 10, x64
Dart SDK: 1.22.0-dev.8.0 (**not** reproducible with 1.21.0)

Minimal project consists of 2 files. 
`pubspec.yaml`:
```
name: simple_test
dev_dependencies:
  test: any
```
`test/some_test.dart`:
``` 
import "package:test/test.dart";

main() {
  test("test 1", () {});
}
```

Process `pub run test -r json` started from the command line remains hanging forever after reporting test results.

**Comment by fsc8000** [comment]
I tried reproducing this on my Windows 10 machine, but did not see the same issue. Is there something else I'm missing to reproduce this?

```
C:\src\project>..\dartgit\sdk\out\ReleaseX64\dart-sdk\bin\pub --version
Pub 1.22.0-dev.8.0

C:\src\project>..\dartgit\sdk\out\ReleaseX64\dart-sdk\bin\dart --version
Dart VM version: 1.22.0-dev.8.0 (Wed Jan 18 10:48:22 2017) on "windows_x64"
```

I get the following output:

```
C:\src\project>..\dartgit\sdk\out\ReleaseX64\dart-sdk\bin\pub run test -r json
{"protocolVersion":"0.1.0","runnerVersion":"0.12.18+1","type":"start","time":0}
{"count":1,"type":"allSuites","time":0}
{"suite":{"id":0,"platform":"vm","path":"test\\some_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading test\\some_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":302}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":305}
{"test":{"id":3,"name":"test 1","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":4,"column":3,"url":"file:///C:/src/project/test/some_test.dart"},"type":"testStart","time":306}
{"testID":3,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":347}
{"success":true,"type":"done","time":353}

C:\src\project>
```

The same result when running repeatedly.

**Comment by kevmoo** [comment]
@alexander-doroshko did you run `pub get` first?

Would you copy-paste `pubspec.lock` for us?

**Comment by alexander-doroshko** [comment]
Yes, the same pub version, the same pub output, the only difference is that I do not get command prompt back after it, and see that the process remains alive in Process Explorer. I'm afraid I have no other clue to reproduce. Happy to try whatever you ask. Attaching pubspec.lock
[pubspec.lock.txt](https://github.com/dart-lang/pub/files/714762/pubspec.lock.txt)

**Comment by alexander-doroshko** [comment]
I managed to start the process with Observatory and can see its status while it hangs:
![image](https://cloud.githubusercontent.com/assets/4499789/22078969/237d28fa-ddcb-11e6-8fe7-96f6be5f5fc6.png)

**Comment by kevmoo** [comment]
Are all of the isolates idle?

**Comment by alexander-doroshko** [comment]
I started the following command: 
```
C:\dart\dart-dev-channel\bin\dart.exe --enable_vm_service file:\\\C:\dart\dart-dev-channel\bin\snapshots\pub.dart.snapshot run test -r json
```
got this output:
```
{"protocolVersion":"0.1.0","runnerVersion":"0.12.18+1","type":"start","time":0}
{"count":1,"type":"allSuites","time":0}
{"suite":{"id":0,"platform":"vm","path":"test\\some_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading test\\some_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":359}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":363}
{"test":{"id":3,"name":"test 1","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":4,"column":3,"url":"file:///C:/dart_projects/simple_test/test/some_test.dart"},"type":"testStart","time":364}
{"testID":3,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":400}
{"success":true,"type":"done","time":405}
```
and opened Observatory. There are 2 isolates, both idle:
![image](https://cloud.githubusercontent.com/assets/4499789/22079663/bc06b666-ddcd-11e6-93ce-ff2f2644651d.png)

**Comment by alexander-doroshko** [comment]
One isolate has no stack:
![image](https://cloud.githubusercontent.com/assets/4499789/22079940/a13e00d6-ddce-11e6-9f4e-53695e0314aa.png)

**Comment by alexander-doroshko** [comment]
screenshots with isolate details:
![image](https://cloud.githubusercontent.com/assets/4499789/22080042/1e184a62-ddcf-11e6-9257-9fac97b4c361.png)

![image](https://cloud.githubusercontent.com/assets/4499789/22080021/0a6e32ec-ddcf-11e6-9406-f9f48ae56fa1.png)

**Comment by a-siva** [comment]
Can you attach visual studio debugger to the process at this point and get stack traces of all the threads?

**Comment by alexander-doroshko** [comment]
I'm afraid I do not have Visual Studio installed.

But I noticed that I can press Enter in the console and this makes the process terminate!
With SDK 1.21 I do not have to press Enter, it terminates normally itself.

**Comment by fsc8000** [comment]
Which shell are you using? I was using cmd.exe.

**Comment by alexander-doroshko** [comment]
Yes, standard cmd.exe.

Checked on my colleague's PC - the same result.

Interesting observation:
- with `pub run test -r json` it is 100% reproducible both for me and for my colleague. Process kinda waits for input and exits on Enter only.
- with `pub run test` it is ~30% reproducible. In most cases the process terminates normally itself, but sometimes it waits for input and terminates on Enter only. The same on another PC.

**Comment by alexander-doroshko** [comment]
The same with SDK 1.22.0-dev.9.0.
Plus one more issue, may be Windows specific as well: https://github.com/dart-lang/pub/issues/1504

**Comment by a-siva** [comment]
We are unable to get a reproduction of this on our local windows 10 machine here, since you are able to consistently reproduce it could you try and capture a stack trace of all the threads in the process when it is hung and post it here.

You reported that you do not have Visual Studio installed but could you try other tools available for producing stack traces (e.g: procdump)

**Comment by alexander-doroshko** [comment]
Sure, [here's](https://drive.google.com/file/d/0B08iHspLVQF0ZFVkNkhidG01eDg/view?usp=sharing) the output of `procdump64.exe 3556` where `3556` is the PID of the process. Let me know if you want me to run procdump with any [other parameters](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx).

**Comment by a-siva** [comment]
Thanks, is the dump from SDK 1.22.0-dev.9.0 or SDK 1.22.0-dev.8.0

**Comment by alexander-doroshko** [comment]
1.22.0-dev.9.0

**Comment by fsc8000** [comment]
@alexander-doroshko It seems I can't debug the dmp file with symbol without the exact copy of the .pdb symbol files. Even if I build the same version locally, Visual Studio does not seem to accept the pdb files from by local build.

**Comment by fsc8000** [comment]
Never mind. I can reproduce this locally now with 1.22.0-dev.9.0. I'll update the bug when I have more info.

**Comment by fsc8000** [comment]
This is most likely related to dart-lang/sdk#28481. I'm working on fixing it.

**Comment by fsc8000** [comment]
The next dev-channel release should contain the bug fix.

**Comment by alexander-doroshko** [comment]
@fsc8000  Verified in today's nightly build, thanks a lot! 👍
