### ISSUE TITLE
Add the ability to deprecate a package

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1503]
Deprecated packages would give a warning when calling "pub get" if you depend on them, ideally with a configurable message. We could also make them either not appear on pub.dartlang.org at all or be obviously deprecated in some other way on the site.

This could be configured via pubspec.yaml, something like:

```yaml
deprecated: true
deprecation_message: "This package has been renamed to package:blah"
```

**Comment by a14n** [comment]
Will it be possible to un-deprecate a deprecated package ?

**Comment by jakemac53** [comment]
> Will it be possible to un-deprecate a deprecated package ?

Sure, just remove the `deprecated` field and publish a new version :)

**Comment by a14n** [comment]
I wonder what should appear on pub.dartlang.org for the each version in the following case:

- v1.0.0
- v1.1.0 -> depreacted
- v2.0.0 -> no more depreacted

**Comment by jakemac53** [comment]
maybe just add `(deprecated)` next to any version which was published with `deprecated: true`?

**Comment by nex3** [comment]
I'm not sure how much value this would provide over existing mechanisms. You can already mark libraries as deprecated, and it's easy to make a package visibly deprecated on pub.dartlang.org via its description and README. I guess you get to see a deprecation message earlier than you would otherwise, but I'm not sure that's worth adding more pubspec surface.

**Comment by jakemac53** [comment]
One of the main advantages would be helping on pub.dartlang.org. Clearly marking deprecated packages or hiding them altogether would reduce confusion.

**Comment by nex3** [comment]
I suppose hiding deprecated packages would require metadata, but marking them clearly is already doable by making the description "This package is deprecated and should not be used" and adding details to the README.

**Comment by jakemac53** [comment]
True, but I still think it's worthwhile to have the ability to completely hide deprecated packages or at least have them marked in a consistent manner.

**Comment by matanlurey** [comment]
Plus you could output something when `pub get` causes you to download a deprecated package - I'm sure people would like to know they can expect no more updates from a `foo_bar` package they depend on for production.

**Comment by kwalrath** [comment]
Also see dart-lang/pub-dartlang-dart#289

**Comment by kevmoo** [comment]
This is handled on the pub site now. https://github.com/dart-lang/pub-dev/issues/289 was fixed.
