### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jox81** [dart-lang/pub#1505]
Hey, I'm trying to build an app.

Could not find asset angular2|lib/reflection.dart.
package:pub/src/barback/pub_package_provider.dart 115  PubPackageProvider._assertExists
package:pub/src/barback/pub_package_provider.dart 109  PubPackageProvider.getAsset.<async>
This is an unexpected error. Please run

    pub --trace build --mode=debug --output=build

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

So here is the error log>>

...
... other mirror logs
...
MSG : [Info from Dart2JS on webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart]:
    | packages\webgl\src\webgl_objects\webgl_rendering_context.dart:20:1:
    | Import of 'dart:mirrors'.
    | import 'dart:mirrors';
    | ^^^^^^^^^^^^^^^^^^^^^^
MSG : [Info from Dart2JS on webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart]:
    | packages\webgl\src\context\context_attributs.dart:1:1:
    | Import of 'dart:mirrors'.
    | import 'dart:mirrors';
    | ^^^^^^^^^^^^^^^^^^^^^^
MSG : [Info from Dart2JS on webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart]:
    | packages\webgl\src\debug_rendering_context.dart:3:1:
    | Import of 'dart:mirrors'.
    | import 'dart:mirrors';
    | ^^^^^^^^^^^^^^^^^^^^^^
MSG : [Info from Dart2JS on webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart]:
    | packages\webgl\src\webgl_objects\webgl_active_texture.dart:14:1:
    | Import of 'dart:mirrors'.
    | import 'dart:mirrors';
    | ^^^^^^^^^^^^^^^^^^^^^^
MSG : [Info from Dart2JS]:
    | Took 0:00:25.513372 to compile webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart.
FINE: [Fine from Dart2JS on webgl|web/test_scenes/webgl_objects_tests/webgl_texture/webgl_texture.dart]:
    | Took 7:24.6s (0.0s awaiting secondary inputs).
FINE: Building webgl finished (7:33.3s).
ERR : Could not find asset angular2|lib/reflection.dart.
FINE: Exception type: AssetNotFoundException
ERR : package:pub/src/barback/pub_package_provider.dart 115   PubPackageProvider._assertExists
    | package:pub/src/barback/pub_package_provider.dart 109   PubPackageProvider.getAsset.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Completer.completeError
    | package:pub/src/barback/pub_package_provider.dart 114   PubPackageProvider.getAsset.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              Future.Future.microtask
    | package:pub/src/barback/pub_package_provider.dart       PubPackageProvider.getAsset
    | ===== asynchronous gap ===========================
    | dart:async                                              Stream.toList
    | package:barback/src/graph/static_asset_cascade.dart 49  StaticAssetCascade.availableOutputs
    | package:barback/src/graph/package_graph.dart 178        PackageGraph.getAllAssets.<fn>
    | dart:async                                              Future.wait
    | package:barback/src/graph/package_graph.dart 177        PackageGraph.getAllAssets
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets.<fn>
    | dart:async                                              _BroadcastStreamController.add
    | package:barback/src/graph/package_graph.dart 266        PackageGraph._tryScheduleResult.<fn>
    | package:barback/src/utils.dart 253                      newFuture.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets.<fn>
    | dart:async                                              _BroadcastStreamController.add
    | package:barback/src/graph/package_graph.dart 266        PackageGraph._tryScheduleResult.<fn>
    | package:barback/src/utils.dart 253                      newFuture.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets
    | package:barback/src/barback.dart 106                    Barback.getAllAssets
    | package:pub/src/command/build.dart 99                   BuildCommand.onRunTransformerCommand.<async>.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 236      AssetEnvironment.serveDirectory.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/io.dart 878                             bindServer.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:http_multi_server/http_multi_server.dart 136    HttpMultiServer._loopback.<async>
    | ===== asynchronous gap ===========================
    | package:pub                                             BuildCommand.onRunTransformerCommand.<async>.<fn>
    | package:pub/src/log.dart 408                            progress
    | package:pub/src/command/build.dart 90                   BuildCommand.onRunTransformerCommand.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 83       AssetEnvironment.create.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 508      AssetEnvironment._load.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 663      AssetEnvironment._withStreamErrors.<fn>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 506      AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/load_all_transformers.dart 117  loadAllTransformers.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/load_all_transformers.dart 116  loadAllTransformers.<async>.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/transformer_loader.dart 123     TransformerLoader.transformersForPhases.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/transformer_loader.dart 119     TransformerLoader.transformersForPhases.<async>.<fn>.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/barback/transformer_loader.dart 69      TransformerLoader.transformersFor.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              _asyncThenWrapperHelper
    | package:pub/src/command/build.dart                      BuildCommand.onRunTransformerCommand
    | package:pub/src/command/barback.dart 56                 BarbackCommand.run
    | package:args/command_runner.dart 177                    CommandRunner.runCommand.<fn>
    | dart:async                                              Future.Future.sync
    | package:args/command_runner.dart 130                    CommandRunner.runCommand
    | package:pub/src/command_runner.dart 128                 PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                              Future.Future.sync
    | package:pub/src/utils.dart 72                           captureErrors.<fn>
    | package:stack_trace                                     Chain.capture
    | package:pub/src/utils.dart 86                           captureErrors
    | package:pub/src/command_runner.dart 128                 PubCommandRunner.runCommand.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/command_runner.dart 221                 PubCommandRunner._validatePlatform.<async>
    | dart:async                                              _SyncCompleter.complete
    | package:pub/src/io.dart 695                             runProcess.<fn>.<async>
---- End log transcript ----

And the pubspec.yaml : 

name: 'webgl'
version: 0.0.5
description: Building a webgl application

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  vector_math: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]

**Comment by jox81** [comment]
The log show the error :

```
ERR : Could not find asset angular2|lib/reflection.dart.
FINE: Exception type: AssetNotFoundException

```
and if  I try to import reflection.dat in a test file :
`import 'package:angular2/reflection.dart';`
I can follow the link and find the file.

**Comment by zoechi** [comment]
you could try to delete the `.pub` dirctiry in your project and try agaun

**Comment by natebosch** [comment]
`pub build` is no longer supported. Check out the replacement: https://github.com/dart-lang/build/blob/master/docs/getting_started.md
