### ISSUE TITLE
Ability to deprecate transformer

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/pub#1506]
From what I can tell, there's no way to deprecate a transformer so that a user gets an error when including it in their `pubspec.yaml`.

For instance, when splitting a transformer out of a package into another one, it would be nice to be able to inform the user via an analyzer hint that the transformer they're using is deprecated, and that they should switch over to the new transformer.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
