### ISSUE TITLE
Support packages that are explicitly unlicensed.

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/pub#1512]
The Unlicense is a software license that explicitly disclaims copyright interest. Usage of the Unlicense usually involves placing the text in a file called UNLICENSE.

pub currently requires either a LICENSE or COPYING file in the root directory, otherwise, you will get this error message:
```
Missing requirements:
* You must have a COPYING or LICENSE file in the root directory.
  An open-source license helps ensure people can legally use your code.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: http://pub.dartlang.org/doc/pub-lish.html.
```

Please add support for the UNLICENSE.

**Comment by UnikZ** [comment]
#1553

**Comment by sigurdm** [comment]
Seems to have been fixed in: https://github.com/dart-lang/pub/pull/1553
