### ISSUE TITLE
running `pub run test` in a flutter project gives unexpected error when missing FLUTTER_ROOT

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub#1514]
I was just looking to get `pub run test` options (for other reasons) and didn't realize I was in a flutter project.  The error it gave was not very understandable (and it gave me incorrect directions to file a bug here).

This is not a high priority issue, but we could do a lot better from a UX perspective.  For example, we don't need to error out about missing flutter in the --help case, but more importantly, when we do error out we could give explanations on how to fix it and not direct folks to file a bug. :)

```
pub run test --help                                                                                                [/tmp/foo]
Bad state: Flutter is not available.
package:pub/src/flutter.dart 29       packagePath
package:pub/src/source/sdk.dart 108   BoundSdkSource.getDirectory
package:pub/src/system_cache.dart 97  SystemCache.load
package:pub/src/entrypoint.dart 552   Entrypoint._assertLockFileUpToDate
package:pub/src/entrypoint.dart 484   Entrypoint.assertUpToDate
package:pub/src/entrypoint.dart 105   Entrypoint.packageGraph
package:pub/src/executable.dart 59    runExecutable.<async>
This is an unexpected error. Please run

    pub --trace run test --help

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

**Comment by nex3** [comment]
I've put out a CL to improve the error message. Unfortunately it's not possible to special-case `--help`, because that's handled by the executable and the error prevents Pub from running it at all.
