### ISSUE TITLE
pub get: rename file denied

### ISSUE THREAD

**Issue by dbuendiab** [dart-lang/pub#1518]
I got this error 

> Failed to rename directory because access was denied

and running pub --trace get got this sequence of messages:

<pre>IO  : Renaming directory C:\Users\Diego Buendia\AppData\Roaming\Pub\Cache\_temp\
dir42b1fd75-f6bb-11e6-8327-40167e152c0c to C:\Users\Diego Buendia\AppData\Roamin
g\Pub\Cache\hosted\pub.dartlang.org\html-0.13.1.
IO  : Failed to rename directory because access was denied. Retrying in 50ms.
IO  : Renaming directory C:\Users\Diego Buendia\AppData\Roaming\Pub\Cache\_temp\
dir42b1fd75-f6bb-11e6-8327-40167e152c0c to C:\Users\Diego Buendia\AppData\Roamin
g\Pub\Cache\hosted\pub.dartlang.org\html-0.13.1.
IO  : Failed to rename directory because access was denied. Retrying in 50ms.
IO  : Renaming directory C:\Users\Diego Buendia\AppData\Roaming\Pub\Cache\_temp\
dir42b1fd75-f6bb-11e6-8327-40167e152c0c to C:\Users\Diego Buendia\AppData\Roamin
g\Pub\Cache\hosted\pub.dartlang.org\html-0.13.1.
ERR : Failed to rename directory because access was denied.
    | This may be caused by a virus scanner or having a file
    | in the directory open in another application.</pre>

It seems the process tries to rename a directory but fails. I tried to rename by hand and got an error because of the spaces in the path. Using quotes this op went fine.

I'm wondering if the lack of quotes could be the origin of this issue.

**Comment by nex3** [comment]
Pub doesn't use shell commands for renaming directories, it uses the [`Directory.renameSync()`](https://api.dartlang.org/stable/1.22.0/dart-io/Directory/renameSync.html) API. If that API is choking on paths with spaces, that's a `dart:io` issue. I suggest trying to reproduce this with a small Dart program that just uses `Directory.renameSync()` directly, and if that fails, reporting it on [dart-lang/sdk](https://github.com/dart-lang/sdk).
