### ISSUE TITLE
Command "pub get" is failed under windows 10

### ISSUE THREAD

**Issue by micrcx** [dart-lang/pub#1520]
Command "pub get" is failed under windows 10, for example:

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\micrcx> cd .\IdeaProjects\
PS C:\Users\micrcx\IdeaProjects> cd .\TimerTest\
PS C:\Users\micrcx\IdeaProjects\TimerTest> pub get
Resolving dependencies...
Downloading crypto 0.9.2+1...
Downloading convert 1.1.1...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
PS C:\Users\micrcx\IdeaProjects\TimerTest>

Not clear what to do in such a situation. What is the cause of the error?

**Comment by nex3** [comment]
The underlying cause here is probably an issue with your OS not having permissions, but you can figure out the exact rename being done by passing `--verbose` to `pub get`.

**Comment by micrcx** [comment]
I've found the cause of the error. OS's message close to the truth. If you disable the antivirus (scanning turn off, in my case it is McAfee), the command pub get is performed without problems. The first time I was faced with the usual upgrade procedure that conflicts with antivirus. However, there is hope that the issue will be solved by itself when McAfee will select dart as software.

**Comment by chandan641989** [comment]
Same error was on my laptop too. I pause  antivirus and firewall protection the it worked.
