### ISSUE TITLE
Support for packages with entrypoint

### ISSUE THREAD

**Issue by Paullo612** [dart-lang/pub#1522]
Suppose I have package named ```long_operation_computer```. It does some long and heavy computation in browser. It uses dart:isolate library to do a computation using spawnURI method. It has API library in lib and isolate's entrypoint in web directory as stated here: https://www.dartlang.org/tools/pub/package-layout.

The project directory structure is:

```
./long_operation_computer/
├── analysis_options.yaml
├── CHANGELOG.md
├── lib
│   └── long_operation_computer.dart
├── LICENSE
├── pubspec.lock
├── pubspec.yaml
├── README.md
└── web
    └── entrypoint.dart
```

Suppose I successfully published this package using ```pub publish```, and now I want to use ```long_operation_computer```'s API in my new project. When I add ```long_operation_computer``` as the dependency and try to build new project using ```pub build``` ```long_operation_computer```'s entrypoint is not compiled and I get error about isolate spawning failure.

How can I make ```long_operation_computer```'s entrypoint to compile as part of my new project? I have not found any documentation covering that.

**Comment by nex3** [comment]
*Everything* in your package that's meant to be used by downstream packages should go in `lib/`. The `web/` directory is only for entrypoints into a *web application package*—a package that's intended to be run on its own in a web browser.

**Comment by zoechi** [comment]
@Paullo612 if you move `entrypoint.dart` in your `package:long_operation_computer` package into `lib/`, then in your application package a file `web/entrypoint.dart` with
```dart
export 'package:long_operation_computer/entrypoint.dart';
```
should do.

**Comment by Paullo612** [comment]
```entrypoint.dart``` should not be imported or exported directly as it is isolate's entry point. It contains isolate's ```main``` function and should be compiled to separate ```dart.js``` file. spawnUri function starts WebWorker in the browser, and WebWorker requires separate js file to run. But I don't want users of ```long_operation_computer``` to care about all this isolate stuff. It is ```long_operation_computer```'s implementation detail.

Moved ```entrypoint.dart``` to ```./lib``` directory. Still have no ```entrypoint.dart.js``` in my build directory.
Exporting entrypoint in ```web/entrypoint.dart``` as @zoechi suggested does not work too.

**Comment by zoechi** [comment]
perhaps you want to generated and add `entrypoint.dart.js` to your long_operation_computer packages `lib` directory and then use a package URI that points to that file in `spawnUri`.
https://gitter.im/dart-lang/TALK-general might be a better place for support questions.
