### ISSUE TITLE
Paths in .package contain double slashes

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/pub#1524]
When `$HOME` ends with a `/`, pub produces a `.package` file with double `//` in the URIs:

```
web_socket_channel:file:///Users/goderbauer//.pub-cache/hosted/pub.dartlang.org/web_socket_channel-1.0.4/lib/
when:file:///Users/goderbauer//.pub-cache/hosted/pub.dartlang.org/when-0.2.0/lib/
```

Note the `//` just before `.pub-cache`.

**Comment by tvolkert** [comment]
Ideally it'd use `package:path` to normalize the paths in `.packages`

**Comment by eseidelGoogle** [comment]
We ran into another // bug a while back.  I should see if I can find it.   Some part of dart:io's uri handler was going down the wrong path when the path started with a // due to windows or some such.

**Comment by nex3** [comment]
I suppose we could normalize these, but the URLs we're generating *are* valid. If downstream code isn't able to consume them successfully, that's a bug in that code that should be fixed regardless of what pub generates.

**Comment by eseidelGoogle** [comment]
https://github.com/dart-lang/sdk/issues/28143 is the bug I was thinking of in my earlier comment btw, not necessarily related.

**Comment by sigurdm** [comment]
This is obsolete. We no longer produce `.packages` files.
