### ISSUE TITLE
Odd output of pub in Git Bash and Cygwin on Windows

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1540]
_From @goderbauer on March 17, 2017 18:41_

```
goderbauer@eseidel0-w MINGW64 /c/src/flutter/dev/tools (master)
$ pub.bat get
find: ‘>     bin [’: No such file or directory
Resolving dependencies...
Got dependencies!
```

The output `find: ‘>     bin [’: No such file or directory` seems odd. Other than that, it seems to work as expected.

_Copied from original issue: dart-lang/sdk#29102_

**Comment by floitschG** [comment]
_From @goderbauer on March 17, 2017 18:44_

Related: https://github.com/flutter/flutter/issues/8860.

**Comment by floitschG** [comment]
_From @kevmoo on March 17, 2017 19:33_

Has this changed w/ the new windows stdout/err work?

**Comment by floitschG** [comment]
_From @goderbauer on March 17, 2017 19:36_

> Has this changed w/ the new windows stdout/err work?

Nope. Previous Dart versions also had the same problem.

**Comment by johnniwinther** [comment]
I now see this 7 times while running presubmit commit checks (`git cl land`).

**Comment by goderbauer** [comment]
Flutter has at least one report of users seeing this message when running `pub` in a regular PowerShell: https://github.com/flutter/flutter/issues/9117. I was not able to reproduce this on my machine, though.

**Comment by nex3** [comment]
@floitschG I think this does actually belong in the SDK repo. That's where the batch script that starts pub on Windows lives. AFAIK that script (along with all the other SDK scripts, which are mostly identical) are maintained by SDK owners and not pub owners.

**Comment by sigurdm** [comment]
This seems stale now the top-level pub-commmand is going away.

Closing.
