### ISSUE TITLE
[1.23.0-dev.10.0-1] pub serve gives error and exits

### ISSUE THREAD

**Issue by andrey-zakharov** [dart-lang/pub#1548]
pub serve gives
`Trying to set 'Transfer-Encoding: Chunked' on HTTP 1.0 headers
`
and exits when accessing localhost from dartium.

for example pub 1.20.1-1 serves  very well.

**Comment by parnham** [comment]
This is still an issue in 1.23.0 stable.

**Comment by dougreese** [comment]
Is there a work around for this? I just came back to my Dart project after working on something else for a few months and ran in to this problem after upgrading to 1.23.0.

```
$ dart --version
Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"
```

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
