### ISSUE TITLE
Use the pool package to limit the number of concurrent dartdevc tasks

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1549]
Today you could end up with a process per package dependency in the worst case, although in reality this would never happen. Either way it would be good to limit the number of concurrent dartdevc processes to something reasonable (and possibly configurable?).

**Comment by jakemac53** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
Please.

Default to number of cores...or number of cores / 2 --- maybe?

**Comment by jakemac53** [comment]
No longer relevant in v2 integration, using the bazel_worker package to manage a pool of worker tasks.
