### ISSUE TITLE
Pub should handle pub server errors gracefully

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub#1556]
The pub server will sometimes return a 500 (internal error), if there is a temporary failure on the server.
pub get should handle these results, and retry the fetch of the object from the server.  If it doesn't retry, then it should return with a distinctive error code that indicates temporary failure.  Maybe this should happen for other network failures when running pub get as well.

This would make the testing of pub get less flaky, and allow us to test it on the buildbot.
This seems related to issue #1534 and pr https://github.com/dart-lang/pub/pull/1552

@mkustermann

**Comment by UnikZ** [comment]
I think, pub server should return 503 status code for temporary failures according to https://tools.ietf.org/html/rfc2616#section-10.5.4

**Comment by whesse** [comment]
@mkustermann

**Comment by jcollins-g** [comment]
This is a frequent source of temporary breakage on dartdoc's travis and appveyor.

**Comment by jakemac53** [comment]
+1 package:build gets flakes on Travis all the time due to this

**Comment by gspencergoog** [comment]
Also, if we are doing retries, they should be using an appropriate exponential backoff, not just fixed timeouts.  As we grow, this will become more and more important...

**Comment by kevmoo** [comment]
The pub site is having issues now – tried the pub client at https://github.com/dart-lang/pub/commit/932e76efcd813be84045da31d1c4e17b18b227f3

...no retries on 502 😕
