### ISSUE TITLE
Pub Serve Proxy

### ISSUE THREAD

**Issue by unibeck** [dart-lang/pub#1558]
About a week ago I asked on gitter about proxying requests from my webapp that's running with `pub serve --port=8081` to my Spring Boot back-end running on port 8080. The consensus was to use a reverse proxy s.t. my back-end grabs request from port 8081 and feeds it to itself on 8080. Though I just got around to start implementing this and I realized that if pub is serving on port 8081 then no other applications can listen on this port. So a reverse proxy this way doesn't make much sense. It seems much more appropriate for the front-end dev server (pub in this case) to proxy any request to port 8080. I, along with several others given the StackOverflow and articles on the issue, would like to see this implemented. Potentially `pub serve --port=8081 --proxyHost=localhost --proxyPort=8080`

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
