### ISSUE TITLE
`Bad state: Flutter is not available` is confusing to users

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub#1559]
See https://github.com/flutter/flutter/issues/9251.

They ran `pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart`
Following the instructions for package:intl (fyi @alan-knight) and got:

`Bad state: Flutter is not available.`

Which was confusing.  What they needed was FLUTTER_ROOT to be set and ideally that error message would tell them that?

**Comment by nex3** [comment]
We already include instructions about how to solve this ([here's where we generate the message](https://github.com/dart-lang/pub/blob/2895b1d52c7893854a81ba5feda0ae612998e278/lib/src/flutter.dart#L31-L34)). If you're *only* seeing the text "Flutter is not available", that's probably coming from somewhere other than pub.

**Comment by eseidelGoogle** [comment]
Yup, looks like this got fixed since I filed:
```
eseidel-macbookair% pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart

Flutter is not available. If this is a Flutter project, make sure to always run
pub through the "flutter" executable.
```
