### ISSUE TITLE
pub complains when I publish a package that depends on flutter

### ISSUE THREAD

**Issue by abarth** [dart-lang/pub#1560]
I created a new pub package that depends on `package:flutter`:

https://github.com/flutter/css_colors

When I publish that package, I get the following suggestion:

```
Suggestions:
* Don't depend on "flutter" from the sdk source. Use the hosted source instead. For example:
  
  dependencies:
    flutter: ">=0.0.20 <0.1.0"
  
  Using the hosted source ensures that everyone can download your package's dependencies along with your package.
```

I think I did things correctly and shouldn't get that message.

/cc @nex3 @eseidelGoogle @sethladd

**Comment by sethladd** [comment]
Good catch, thanks for the report!

**Comment by sethladd** [comment]
cc @kevmoo

**Comment by dgrove** [comment]
@munificent can you take a look?

**Comment by munificent** [comment]
Yeah, this should be a simple fix. I'll get on it.

**Comment by abarth** [comment]
Thanks!
