### ISSUE TITLE
Relative/local path dependencies should work

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/pub#1571]
In the Dart REPL, I wanted to use an embedded sandbox package within the actual REPL package. It is self-contained and locally:
```
  dart_repl_sandbox:
    path:
      sandbox/
```
is working.

However, pub publish does not allow path dependencies. Not sure if it makes sense to relax the requirements. For me, it would make things easier ^^ I now have to make sure I always publish two packages in lock step.

**Comment by natebosch** [comment]
This is definitely a pain I feel whenever I publish something from the `build` repo - however a path dependency isn't something we can support on a published package since it loses it's meaning once it is no longer on the host doing the publishing.
