### ISSUE TITLE
`pub serve` complains about `pubspec.lock` of a path dependency

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1572]
```
zoechi@zdev ~/dart/myproj/generated/demo2
 (master) $ pub serve
../../fhir_webui/pubspec.yaml has changed since the pubspec.lock file was generated, please run "pub get" again.
zoechi@zdev ~/dart/myproj/generated/demo2
 (master) $ 
```

In `demo2/pubspec.yaml`
```yml
dependencies:
  fhir_webui:
    path: '../../fhir_webui'
```

I deleted `fhir_webui/pubspec.lock` and recreated it using `pub upgrade --packages-dir`, therefore it's up-to-date and the error doesn't make sense.

Dart VM version: 1.24.0-edge.a73c8d0de14d003ec02250b55f09505891edf375 (Wed Apr 19 16:47:36 2017) on "linux_x64"

**Comment by zoechi** [comment]
I run `pub upgrade --packages-dir` (I need `--packages-dir` because of SASS) on all path dependencies.
This made `pub serve` work again. 

`pubspec.lock` files from path dependencies shouldn't matter to `pub serve`.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
