### ISSUE TITLE
Use a Dart-only library for archives instead of the 'tar' executable.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub#1602]
Calling the 'tar' executable makes pub vulnerable to various issues, dealing it with a Dart-only library makes it safer. This library seems to be able to deal with it adequately: https://pub.dartlang.org/packages/archive

See also: https://github.com/dart-lang/pub-dartlang-dart/issues/142

**Comment by nex3** [comment]
I'm strongly in favor of this, but some legwork needs to happen before it's feasible. TAR is an old format, and there are a lot of weird corner cases that may not be thoroughly documented. We need strong evidence that the `archive` package can correctly extract all the tarballs currently on pub.dartlang.org before we start using it in pub.

**Comment by brendan-duncan** [comment]
If you have a mechanism that I can use to walk the list of available tarballs on pub, I'd be happy to write a test to ensure they can be extracted correctly.

**Comment by nex3** [comment]
I think @isoos has a script for that [here](https://github.com/isoos/pub-dartlang-dart/blob/8349d9def9ba3aa5adbf9a13701078793da0031f/app/bin/tools_archive_validator.dart).

**Comment by isoos** [comment]
Tomorrow I'll get you a sampling of package URLs with known issues and also a few good ones too.

**Comment by brendan-duncan** [comment]
Thanks. As soon as I finish adding PAX_INTERCHANGE and PAX_RESTRICTED
extensions, that should be all known variants of tar. It's a pretty
straight forward format.

**Comment by rajveermalviya** [comment]
Hey @sigurdm  @jonasfj ,
What's the status on this?

Because I am using Clearlinux and it has pigz replaced by gzip so, `pub` is useless unless I change the defaults.
