### ISSUE TITLE
Dartdevc should use the `urlArgs` require.js config for cache-busting uris

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1617]
See http://requirejs.org/docs/api.html#config-urlArgs, by creating a map of module ids to hashed contents and appending that to the uri we can eliminate round trips for cached modules.

Note that we also would need to change the cache-control header returned from pub in this case to `public, max-age=31536000` (or some other large max-age).

**Comment by kevmoo** [comment]
Not planned
