### ISSUE TITLE
On clicking on the installing tab, add the #-pkg-tab-installing to the url. 

### ISSUE THREAD

**Issue by branflake2267** [dart-lang/pub#1621]
On clicking on the installing tab, it would be nice to add the hash and fragment to the url. This would allow for easy copy and paste. 

This would make much easier to share the installing link in other guides. 

For example: 
https://pub.dartlang.org/packages/google_sign_in#-pkg-tab-installing

![screen shot 2017-05-23 at 3 56 18 pm](https://cloud.githubusercontent.com/assets/1326504/26379927/7efff8d0-3fd0-11e7-879c-9e67476cecc0.png)

**Comment by natebosch** [comment]
moved this issue to the dart-lang/pub-dartlang-dart repo
