### ISSUE TITLE
Sdk sourcemaps don't work with --compiler=dartdevc 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1623]
The sourcemap does exist for the sdk but it doesn't seem to work properly so we currently disable it entirely. Specifically, you can't navigate into any of the sdk sources in devtools, they all appear as empty files.

cc @jacob314

**Comment by jakemac53** [comment]
Did a bit more digging, it looks like pub has special handling for the `$sdk` package, which refers to the dart sdk. The sourcemaps would need to be updated to use that package when referring to files in the dart sdk.

**Comment by kevmoo** [comment]
Not planned
