### ISSUE TITLE
PopPopWin broken on Safari with DDC

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/pub#1631]
This is on the Mac with Safari Version 10.1 (12603.1.30.0.34).

When I load PPW on Safari (with `--web-compiler=dartdevc`), I hit this FF line and get an exception:

https://github.com/dart-lang/pub/blob/master/lib/src/dartdevc/dartdevc.dart#L40

If I edit `lines` in devtools and force it to the Safari line, the app loads just fine.  `lines.length` is 3 for me.

@jakemac53 @kevmoo

**Comment by vsmenon** [comment]
@jacob314 - just the magical line above come from you?  :-)

**Comment by jacob314** [comment]
https://codereview.chromium.org/2939453002/
