### ISSUE TITLE
improvements to compile errors with pub server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#1635]
This is for running a web app with pub serve, compiled with dartdevc.

When I have a compile error in my app (`web/main.dart`), I see the following error:

```
Error compiling dartdevc module:webdev_sample|web/web__main.js

[error] A value of type 'String' can't be assigned to a variable of type 'int'. (/private/var/folders/67/yp_xxslx6118h12gmf82j3rr0000gn/T/pub_lqgxjl/web/main.dart, line 11, col 15)

Please fix all errors before compiling (warnings are okay).
```

Two possible improvements here:

- the path to the compile error is shown as `/private/var/folders/67/yp_xxslx6118h12gmf82j3rr0000gn/T/pub_lqgxjl/web/main.dart`, yet my code is in `web/main.dart` relative to the cwd. We should show a shorter version of the path, and we should probably not expose that long temp dir path
- re: `Please fix all errors before compiling (warnings are okay).` - we probably don't need to print that. It's already clear to the user that there were errors. And the message is a bit misleading; the action I took wasn't to issue a compile request on the cli, but to refresh my app's page in the browser. I'd recommend not having a summary line -

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
