### ISSUE TITLE
Support hooks for adding in custom validation

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1646]
Certain Flutter package types require custom validation steps. For example, for a flutter plugin, certain platform-specific artefacts are required to be present. 

To support these being of high quality, we would like some way of hooking into the pub tool so that we can perform custom validation for these types of packages.

**Comment by mit-mit** [comment]
cc @kevmoo 

I understand that concern, and yes flutter developers are not expected to interact with `pub` directly but rather use the `flutter` tool.

However, currently nothing prevents them from using `pub` directly. So if we were to do the validation in `flutter` I think we need some way of having `pub` bail out if run directly on a flutter package.

**Comment by nex3** [comment]
> However, currently nothing prevents them from using `pub` directly. So if we were to do the validation in `flutter` I think we need some way of having `pub` bail out if run directly on a flutter package.

We could do this if there's a reliable and inexpensive way of determining whether the root package is a Flutter package.

It's also worth noting, though, that no client-side validation is ever going to be foolproof. If you really want to ensure that no packages that violate these rules get uploaded, you'll need to enforce that on the server.

**Comment by kevmoo** [comment]
> you'll need to enforce that on the server.

What @nex3 said. I'd rather have some general logic that the client uses to run validation via the server and get a result back...

**Comment by sigurdm** [comment]
@mit-mit do we still want this?

**Comment by mit-mit** [comment]
I don't think we have any critical use cases for this right now, no
