### ISSUE TITLE
Request to delete a package from pub

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/pub#1653]
Very sorry for the inconvenience but I accidentally published my package twice by changing it's name in the pubspec (not realising that it would duplicate rather than rename the pub package).

Please could you delete the now obsolete package: 
https://pub.dartlang.org/packages/cellular_automaton

It was a very new package so I am confident nobody referenced/linked it.

**Comment by nex3** [comment]
Usually we only delete packages if they'll break the version solver (e.g. by claiming to be compatible in ways that they aren't), or if they contain sensitive information that wasn't supposed to be published. If this doesn't fit into either category, it probably won't cause any harm, and it may be easier to just leave it be.

**Comment by zoechi** [comment]
This can probably be closed
