### ISSUE TITLE
Treat missing upper bound in Dart SDK constraint as `<2.0.0`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1657]
This will ensure packages have to explicitly support the v2 SDK

**Comment by jakemac53** [comment]
Note that this means essentially no existing package will work in 2.0.0, all packages will have to rev a version with a <3.0.0 constraint on the sdk for them to be available, even though many are actually compatible today.

**Comment by kevmoo** [comment]
Exactly! You must be explicit!

**Comment by nex3** [comment]
Note that we're going with a default constraint of `<2.0.0-dev.infinity`, since we're encouraging users to use that as their constraint during the dev cycle anyway.

**Comment by kevmoo** [comment]
...because `2.0.0-dev.infinity` is > `2.0.0-dev.[any digit here]`  ... right?

**Comment by nex3** [comment]
Correct.
