### ISSUE TITLE
unable to publish

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#1666]
I was unable to publish a package w/ the most recent SDK:

```
Looks great! Are you ready to upload your package (y/n)? y
Uploading... 
Failed to upload the package.
```

This was for `Pub 1.25.0-dev.6.0`. @pq was able to publish the same package, using a `1.25.0-dev.4.0` version of the sdk. The repo in question is https://github.com/dart-lang/cli_util.

**Comment by nex3** [comment]
I'm guessing this is a server-side issue, but just in case what do you see if you run with `--verbose`?

**Comment by devoncarew** [comment]
```
IO  : HTTP response 400 Bad Request for POST https://storage.googleapis.com
    | took 0:00:00.067320
    | date: Thu, 13 Jul 2017 20:21:21 GMT
    | x-guploader-upload-result: invalid_content_type
    | x-google-backends: /bns/pf/borg/pf/bns/blobstore2/bitpusher/196.scotty,acseae16:443
    | x-google-gfe-response-code-details-trace: response_code_set_by_backend
    | x-guploader-uploadid: AEnB2UpfJpQq0DtIRgPObTBYuTFG0QteOanl--GUKVCON0S2aBlsBt5afFMiJ6s3AQGFTtFT7rLBH7Yc9ZCz09iWIeEUsTWzRPAuEnd5W8qlOd-XEHQBryc
    | x-google-shellfish-status: CA0gBEBJ
    | content-type: text/html; charset=UTF-8
    | x-google-service: bitpusher-cloud-storage
    | x-guploader-request-result: invalid_content_type
    | server: UploadServer
    | x-google-gfe-request-trace: acseae16:443,/bns/pf/borg/pf/bns/blobstore2/bitpusher/196.scotty,acseae16:443
    | alt-svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
    | x-google-gfe-service-trace: bitpusher-cloud-storage
    | x-google-gfe-backend-request-info: eid=QdZnWYe1FcGniQOFnavQBA
    | x-google-netmon-label: /bns/pf/borg/pf/bns/blobstore2/bitpusher/196:caf3
    | content-length: 40
    | x-guploader-customer: cloud-storage
    | x-google-dos-service-trace: main:apps-upload-cloud-storage-unified
FINE: Uploading finished (0.806s).
FINE: Saving OAuth2 credentials.
IO  : Writing 365 characters to text file /Users/devoncarew/.pub-cache/credentials.json.
ERR : Failed to upload the package.
FINE: Exception type: ApplicationException
FINE: package:pub/src/utils.dart 815                                                fail
    | package:pub/src/command/lish.dart 106                                         LishCommand._publish
    | package:pub/src/command/lish.dart 145                                         LishCommand.run
    | package:args/command_runner.dart 194                                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                                       PubCommandRunner.runCommand.<fn>
```

**Comment by pq** [comment]
FWIW, `Pub 1.25.0-edge.e41c56580a402dd450ee291233e2ca9cc295d135` failed for me too before `1.25.0-dev.4.0` worked.

**Comment by nex3** [comment]
dart-lang/sdk@e41c56580a402dd450ee291233e2ca9cc295d135 is much older than [1.25.0-dev.4.0](https://github.com/dart-lang/sdk/tree/1.25.0-dev.4.0). Could this have been a bug that has since been fixed?

**Comment by pq** [comment]
Maybe.  But `Pub 1.25.0-dev.6.0` wasn't working for Devon either.

**Comment by nex3** [comment]
Between 1.25.0-dev.4.0 and 1.25.0-dev.6.0, Pub was upgraded from 0713718a83054fcc1c0a4b163e036f7c39ea4790 to 0f122625f8e607842afe156b9b23a9709e4ce39a, but I don't see any changes [in that range](https://github.com/dart-lang/pub/compare/0713718a83054fcc1c0a4b163e036f7c39ea4790...0f122625f8e607842afe156b9b23a9709e4ce39a) that would affect publishing at all. Nor does the SDK include any changes to the HTTP infrastructure. All this makes me think that it must have been either a flake or a server-side change in the HTTP API.

**Comment by nshahan** [comment]
I am seeing the same error on the SDK version:
Dart VM version: 1.25.0-dev.7.0 (Mon Jul 17 02:47:13 2017) on "macos_x64"

**Comment by nshahan** [comment]
I just uninstalled the dev version of the SDK and installed the stable version:
Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"

That allowed me to publish without any problems.

**Comment by kevmoo** [comment]
Yeah – this feels like a server bug. Would someone use the issue mover to...move it?

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#230

**Comment by kevmoo** [comment]
I think this *is* an issue with the client – well, w/ the storage service. It seems they don't like `application/octet-stream` for the mimetype of the upload.

Patch coming shortly...

**Comment by kevmoo** [comment]
Not fixed. Escalated to GCS folks - http://b/63855519 (internal link)

**Comment by kevmoo** [comment]
Root cause: https://github.com/dart-lang/http/issues/105
