### ISSUE TITLE
use of compiler_unsupported

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#1668]
I see `compiler_unsupported` in the pubspec: https://github.com/dart-lang/pub/blob/a1dc64f7bf8625a2d012f790feb8fec4fa7b7caf/pubspec.yaml#L16. This is just an fyi that dartpad no longer uses `compiler_unsupported`, and the package is now likely wholly unsupported.

We switched to invoking compiles via the cli dart2js binary. We benchmarked this, and it's slower than using a warm version of package:compiler_unsupported, but not as much slower as it had been, before the advent of app-jit snapshots.

**Comment by nex3** [comment]
We don't use `compiler_unsupported` for performance reasons, but because we need access to the internal Dart2js APIs to integrate them with the transformer infrastructure. We use `compiler_unsupported` so we can run our tests outside the SDK.

What's the process for rolling new updates into `compiler_unsupported`? I'm going on leave soon, but after that I could probably take over maintenance if it's not too difficult.

**Comment by nex3** [comment]
Another potential option here would be to use a git path dependency to the version in the SDK. That would require its pubspec to be updated, but it could work...

**Comment by devoncarew** [comment]
There is a script to automate the roll process (https://github.com/dart-lang/compiler_unsupported/blob/master/tool/updating.md), but it more or less needs maintence with every sdk release, to deal with refactoring of the dart2js related packages.

If you plan to stick with using dart2js from the source, you may want to try and motivate actual publishes of package:compiler, or see if you can swizzle things to use dart2js as a new git partial dep (git dependency on subdirs).

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
