### ISSUE TITLE
always add absolute paths to `.packages` 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1681]
My `.packages` file contains

```
my_proj:../../other/foo/my_proj/lib/
```

I tried to fix an issue, where the https://pub.dartlang.org/packages/transform_sass can't resolve the path to a *.scss file from this dependency, 
when the current working directory is not the same as the location of the `.packages` file.
 
I haven't found any way to get back the absolute path of an import when the current working directory is not the same as the location of the `.packages` file.

**Comment by natebosch** [comment]
The paths are always relative to the `.packages` file, not the `cwd`. If the SASS transformer isn't finding these file it is doing the translation from `.packages` to absolute path incorrectly.

Pub uses absolute paths when it has an absolute path (like a package in the pub cache), and relative paths when it has a relative path (like a path dependency) - this lets you move around a group of packages on disk without invalidating the `.packages` file.

**Comment by natebosch** [comment]
Using `package:path` this would look something like:

```dart
var packages;// The path to .packages
var pathFrom = path.dirname(packages);
var basePath; // Read from the file
var fullPath = path.isAbsolute(basePath) ? basePath : path.join(pathFrom, basePath);
```

If you want you can use `path.canonicalize` to strip out the redundant `../`

**Comment by zoechi** [comment]
There is no `basePath` available at the place where I need the path to be resolved.
(the current working directory is not the same as the directory that contains the `.packages` file)
The issue might be in dart-lang/package_resolver#7

**Comment by natebosch** [comment]
Here `basePath` is what you'd read from the file: `'../../other/foo/my_proj/lib/'` in your example. Instead of `cwd` use the `path.dirname()` of the `.packages` file.

**Comment by natebosch** [comment]
I suspect that `SyncPackageResolver.loadConfig` should work if you point it at the `.packages` file, it should correctly resolve relative paths that way.
https://www.dartdocs.org/documentation/package_resolver/1.0.2/package_resolver/SyncPackageResolver/loadConfig.html

**Comment by zoechi** [comment]
@natebosch you are right. This way `SyncPackageResolver` returns absolute paths. 
The test in sass-dart and the code in transform-sass which use `new SyncPackageResolver.config(...)` caused the problem.
Thanks a lot for the help.
