### ISSUE TITLE
Make sure analysis_options.yaml can only impact DDC builds on the local package

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#1684]
We *might* want to look for analysis_options.yaml in other packages and try to honor those - but at the least the local analysis options should not leak into DDC behavior when compiling other modules.

I think we disallow strongly connected components between packages so it should always be possible to determine the analysis_options.yaml for a module.

This will mean recreating the logic that the analyzer uses since we'll have to pass --options explicitly rather than let it get picked up based on directory structure. cc @bwilkerson

**Comment by natebosch** [comment]
Some alternatives:

- always pass `--options=/dev/null` - this is in opposition to @leafpetersen and @jmesserly described intended behavior in https://github.com/dart-lang/sdk/issues/29713
- juggle temp directories or however we're invoking DDC such that the modules we build for other packages don't appear to be under a directory with the local analysis options - @jakemac53 do you know if there is something we can do to that end?

**Comment by natebosch** [comment]
We might also consider adding a config in the pubspec to let us override which analysis options is passed to DDC.

**Comment by jakemac53** [comment]
Going to try out passing an empty analysis options file for all dependencies, but not the root package so that will still get whatever settings you have.

This will not support custom analysis options in dependencies but I think that is probably fine.
