### ISSUE TITLE
summary generation test failing in latest dev sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1687]
You can repro by running `pub run test test/dartdevc/summaries_test.dart`.

My guess is this is related to recent changes relating to analysis driver in analyzer_cli?

I will be out starting 8/22 but can take a look when I get back if this is still an issue.

**Comment by jakemac53** [comment]
cc @scheglov

**Comment by scheglov** [comment]
Thank you for fixing this!
