### ISSUE TITLE
Pub build reports "0" when a transformer had an error

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1691]
_From @chalin on August 17, 2017 13:17_

When I run `pub build` over the Angular doc examples, it exits with a status of 0 even if the `TemplateGenerator` reports errors. E.g.:

```nocode
toh-1 > pub build
Loading source assets... 
Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers... 
Building angular_tour_of_heroes... (25.1s)
[BuilderTransformer: Instance of 'LibraryBuilder' on angular_tour_of_heroes|primary]:
Error running TemplateGenerator for angular_tour_of_heroes|lib/app_component.dart.
Error: Template parse errors:
line 6, column 14 of AppComponent: ParseErrorLevel.FATAL: Can't bind to 'ngModel' since it isn't a known native property or known directive. Please fix typo or add to directives list.
[(ngModel)]="hero.name"
^^^^^^^^^^^^^^^^^^^^^^^
...
Built 518 files to "build".
toh-1 > echo $?
0
```

I'm unsure if this is an issue with the transformer or pub.

Of course, this is a problem when running `pub build` as part of build scripts on Travis, etc.

Angular: 4.0.0-alpha+3

cc @kwalrath 

_Copied from original issue: dart-lang/angular#584_

**Comment by matanlurey** [comment]
_From @alorenzen on August 17, 2017 15:50_

NgModel is now part of angular_forms. Did you add an import / dependency on that?

**Comment by matanlurey** [comment]
_From @chalin on August 17, 2017 16:33_

Yes, but this issue isn't about the specifics of the failure (which were easy to solve). It asks why pub returns an exit status of 0 (i.e., that everything is fine), when the template generator actually failed.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.

**Comment by chalin** [comment]
FYI, a [build_runner page](https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner) is up on the 5-dev version of the webdev site. I hadn't seen the recent development of the webdev CLI. Very nice!
