### ISSUE TITLE
Support PUB_ALLOW_PRERELEASE_SDK environment variable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1692]
Details TBD

**Comment by kevmoo** [comment]
Consider adding support for `PUB_ENFORCE_SDK`
The default for `--enforce-sdk-constraint` becomes
`Platform.environment['PUB_ENFORCE_SDK'] ?? 'warn'`

This will make it easier to roll Travis and some other tools where it's easier to set one environment variable than to dig into every invocation of pub

**Comment by jakemac53** [comment]
Are we just doing the environment variable for now or should I do the flag as well?
