### ISSUE TITLE
Consider adding option for controlling dartdevc build resource usages

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/pub#1695]
Building with dartdevc requires a great amount of resources. This can be a problem and make build fail in serveral contexes (like in workstation/ci server with less than 8gb of ram available which is not so uncommon).

Please consider adding some option to limit resources usages (like number of worker threads and they memory limit) during dartdevc build such that the developer can trade off between build speed and resource usages.

**Comment by jakemac53** [comment]
I see ~4 ways of handling this:

- pubspec.yaml configuration, probably an additional option under the `web` key.
- command line arg configuration, `--max-workers=x` or similar.
- system environment variable `PUB_MAX_WORKERS` or similar
- Dart environment variable ( `-DPUB_MAX_WORKERS` command line arg)

It should be noted there are also two types of workers (analyzer and ddc), so any of these numbers would be multiplied by 2 in actuality. We could make this more obvious by letting you configure it per-worker (--max-ddc-workers, --max-analyzer-workers, etc).

cc @natebosch @kevmoo @munificent for thoughts

**Comment by jakemac53** [comment]
I am going to run with the system environment variable for now as that works the nicest with Travis I think and it will have to exist regardless to override settings for bot builds.

We can add more options later if needed, but I would like to keep it simple for now.

**Comment by jakemac53** [comment]
Going to call it `PUB_MAX_WORKERS_PER_TASK` so try and make it clear that its actually multiplier

**Comment by jakemac53** [comment]
I am working on a merge into the sdk this week with some other changes, not sure when the next release will be though.

In the meantime you can add a git dev dependency on pub and run `pub run pub ...`.

The dev dependency would look like:

```
dev_dependencies:
  pub:
    git: https://github.com/dart-lang/pub.git
```

**Comment by dam0vm3nt** [comment]
FWIW : using the latest pub and setting `PUB_MAX_WORKERS_PER_TASK` to `1` now my builds are working on our CI servers too. Thanks!
