### ISSUE TITLE
Dart is getting hung while using high CPU

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1696]
_From @bitsmaker on September 2, 2017 14:56_

I am building a web app using dart that has in its 'web' directory two sub-directories called 'data' and 'img' along with the other default directories. The 'img' directory has about 82000 png files using 1.1 GB. The 'data' directory has about 500 json files using 26M. The application is such that the user does not have to view all the data from all the files at once. Only small chunks will be sent.

When I issue a 'pub serve' command it utilizes 100% CPU and gets hung. I let it run for several hours and it never came back. Using the 'top' command I could see that 'dart' was using the maximum CPU. I removed those two directories from the web directory and pub worked and did not hang.

Is there anything I can do to prevent the hanging issue from happening?

Thanks for all your help!

P.S This happens on the latest of both stable and dev builds as well as DDC

_Copied from original issue: dart-lang/sdk#30607_

**Comment by jakemac53** [comment]
Pub serve does do some amount of work per file under the directories you are serving. At a minimum it lists the directory and I think sets up a file watcher per file.

If you have any transformers it will also call `isPrimary` on each transformer for each asset. You can setting up a `$include` or `$exclude` option for your transformers to help with that, but I don't know how much it will help, see https://www.dartlang.org/tools/pub/assets-and-transformers#how-to-control-which-assets-are-processed for more info.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
