### ISSUE TITLE
Pub build "Network is unreachable" error message

### ISSUE THREAD

**Issue by unibeck** [dart-lang/pub#1699]
I recently had an issue with `pub build` failing in my CI environment and is logged here https://github.com/dart-lang/pub-dartlang-dart/issues/336. Looking at the build output error message doesn't provide a lot of usage information:
`Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dartlang.org, port = 443`. It would be nice to see why the network was unreachable, IP of the server, and/or any http status codes.

**Comment by nex3** [comment]
We just forward whatever information the underlying `dart:io` exception provides us; if there's extra information to be had, please file an issue against [the core SDK](https://github.com/dart-lang/sdk/issues/new) to expose it. In this case, though, I suspect there isn't. This looks like an OS-level socket error, which means that it happened before any kind of IP connection was established or HTTP requests sent out.
