### ISSUE TITLE
version solver takes a long time

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub#1702]
```
git clone https://github.com/dart-lang/args
cd args
pub upgrade
```

It takes a long time to complete, there should be a faster way to resolve a single dependency...

**Comment by zoechi** [comment]
Seems to be a dup of #912

**Comment by kevmoo** [comment]
Args is *very* broken because it it's version is now `1.0.0` but most of the other tools (analyzer, etc) don't support v1.

So pub goes on a wild goose chase to find some set of dependencies that work – when there really aren't any.

This is a Duplicate of #912 – but a very special one-off
