### ISSUE TITLE
Add a --no-dev flag to "pub get" et al

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#1713]
It's useful in some circumstances to be able to resolve a package's main dependencies without also resolving its dev dependencies. For example, dartdocs.org only documents the libraries in lib/ and so has no need for dev dependencies which may cause version resolution errors (such as [this one for `async`](https://www.dartdocs.org/documentation/async/2.0.0/log.txt)).

**Comment by aemino** [comment]
To stay in line with other package managers, I think it would be good if the flag was named something like `--prod` or `--production`.

**Comment by nex3** [comment]
I think that would be pretty confusing. We already have a `--no-dev` flag for `pub deps`, which this would match. Dev dependencies may also be useful for production situations where they might be necessary for e.g. tool scripts.

**Comment by nex3** [comment]
This would be useful for Sass as well: when users install via Homebrew, we run `pub get` on their machine so we can build an app snapshot for them. We have no use for dev dependencies there, and they can cause conflicts like https://github.com/sass/homebrew-sass/issues/10.

**Comment by sigurdm** [comment]
I think this is the same as https://github.com/dart-lang/pub/issues/2036

Closing this as duplicate since the other issue has a bit more discussion.
