### ISSUE TITLE
`pub build` should cache some dependencies to speed up compiling time

### ISSUE THREAD

**Issue by orklann** [dart-lang/pub#1717]
In my project, `pub build` took a long time always while build dart code to js.

```
Loading source assets...
Loading dart_to_js_script_rewriter transformers...
Building Typo...
[Info from Dart2JS]:
Compiling Typo|web/index.dart...
[Info from Dart2JS]:
Took 0:00:24.951657 to compile Typo|web/index.dart.
Built 6 files to "build".
```

Is there any way to cache some dependencies while building to speed up the build process?

**Comment by kevmoo** [comment]
We're working on a new serve/build model that will have caching at its core – see https://github.com/dart-lang/build/milestone/11
