### ISSUE TITLE
Generate a .packages file in the build/ output folder

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/pub#1725]
This would be a step towards getting rid of the logic that uses `packages/` folders to resolve `package:` URIs.

For context, we run into this because the new FE doesn't have support for the `packages/` folder, so when we compile code using the output of `pub build --mode=debug` we are accidentally resolving package imports with the .packages file from the project root (which points to the pub cache folder and wont contain generated code).

/cc @efortuna @jakemac53

**Comment by efortuna** [comment]
cc @nex3 for discussion as well
