### ISSUE TITLE
(2.0-dev) Pub build fails every after pub get?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1733]
If I add a dependency on run `pub get`, and then `pub build` I get:

"Dart 2.0.0-dev.6.0 is incompatible with your dependencies' SDK constraints. Please run "pub get" again."

If I run `pub get`, and then `pub build` again, the error goes away. It comes back forces to me re-run `pub get` later on - I _think_ after adding a dependency but I'm not 100% sure.

**Comment by nex3** [comment]
I can't reproduce this... do you have a sample package that consistently demonstrates the issue?

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
