### ISSUE TITLE
Brand New Project in WebStorm Pub Get Error

### ISSUE THREAD

**Issue by tmudd** [dart-lang/pub#1737]
Created a new project in a branch and tried to do a pub get on a fresh auto generated pubspec.yaml file.
`Process finished with exit code 65`

Was instructed to do a
`pub --trace get`
and attach log.
[pubgetlog.txt](https://github.com/dart-lang/pub/files/1447834/pubgetlog.txt)

**Comment by nex3** [comment]
Duplicate of #1735.
