### ISSUE TITLE
Can pub cache deps to make incremental work faster?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1746]
Related: https://github.com/dart-lang/pub/issues/1745.

Considering its not technically possible to pull packages or versions _from_ pub, it would be nice to be able to store a local copy of some dependency information to make re-running expensive checks cheaper.

**Comment by nex3** [comment]
I think we're already caching as much as we can, given that we want to guarantee that pub operations give the same result regardless of what's in your system cache. We'll always at least need to check which versions of a package are available (unless we can use the locked version), and in practice that's the only HTTP request we make. We could possibly extend the protocol to send less information if we have some locally, but I think most of the overhead exists in making the request in the first place.

If you want to opt out of the guarantee that operations are cache-independent, you can also pass `--offline` which will treat your system cache as the source of truth and thereby avoid any HTTP requests at all.
