### ISSUE TITLE
Platform analysis is wrong if package has bin-directory

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/pub#1760]
This package https://pub.dartlang.org/packages/git_version is tagged for FLUTTER + SERVER.
https://github.com/MikeMitterer/dart-git_version

This is wrong - It's more or less a transformer-package that replaces `%version%` in html or dart-files with the latest git tag. I think what confuses your analyzer is that this package has also a bin-dir. The package offers a little cmdline-tool that shows the latest git tag (version).

**Comment by jakemac53** [comment]
I think this is just a misunderstanding about what the "platform" means.

Transformers run on the "SERVER" (really that just means the dart vm). They do not run on the web - meaning they aren't imported directly from your web app entrypoints.

If this package does have a web-compatible library which you are intended to import in your actual web application then it would have platform "WEB".

**Comment by zoechi** [comment]
Transformers are only supported for web applications.
I'd also say that `Flutter` and `Server` are misleading because there is no way to apply transformers to Flutter or server code.

**Comment by natebosch** [comment]
> Transformers are only supported for web applications.

I don't think there is any particular reason you couldn't use a transformer then run the code in the VM.

**Comment by zoechi** [comment]
How can a transformer be applied for server-side code?
I know only `pub serve`.
Is there something else?

**Comment by jakemac53** [comment]
I think that `pub run` can run transformers - but I could be wrong.

**Comment by natebosch** [comment]
`pub build` then run from the `build/` directory. `pub run` might also do it but I'm not sure.

**Comment by zoechi** [comment]
Ok, but that are rather rare exceptions and not officially supported.

I have no strong opinion here and was just curious. 
I do not maintain any packages that contain a transformer.

**Comment by matanlurey** [comment]
Given the dubious future of transformers does this even matter?

**Comment by natebosch** [comment]
>Given the dubious future of transformers does this even matter?

I think we'll see similar stuff crop up with package:build.

**Comment by nex3** [comment]
This issue was moved to dart-lang/pana#188
