### ISSUE TITLE
Wrong "pub publish" warning - This package doesn't depend on...

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1767]
_From @MikeMitterer on December 6, 2017 18:4_

If I "publish" my l10n lib it gives me the following warning:

Example: https://github.com/MikeMitterer/dart-l10n-gettext/tree/master/example/cmdline
Package: https://github.com/MikeMitterer/dart-l10n-gettext

```
* The name of "lib/l10n/L10NImpl.dart", "L10NImpl", should be lower-case. Maybe use "l10nimpl"?
* The name of "lib/l10n/L10NTranslate.dart", "L10NTranslate", should be lower-case. Maybe use "l10ntranslate"?
* The name of "lib/parser/Lexer.dart", "Lexer", should be lower-case. Maybe use "lexer"?
* The name of "lib/parser/Parser.dart", "Parser", should be lower-case. Maybe use "parser"?
* The name of "lib/parser/Statement.dart", "Statement", should be lower-case. Maybe use "statement"?
* The name of "lib/parser/Token.dart", "Token", should be lower-case. Maybe use "token"?
* line 6, column 1 of example/cmdline/bin/cmdline.dart: This package doesn't depend on l10n_sample_cmdline.
  import 'package:l10n_sample_cmdline/cmdline.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 7, column 1 of example/cmdline/bin/cmdline.dart: This package doesn't depend on l10n_sample_cmdline.
  import 'package:l10n_sample_cmdline/locale/messages.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 28, column 1 of example/cmdline/lib/cmdline.dart: This package doesn't depend on logging_handlers.
  import 'package:logging_handlers/logging_handlers_shared.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 38, column 1 of example/cmdline/lib/cmdline.dart: This package doesn't depend on l10n_sample_cmdline.
  import 'package:l10n_sample_cmdline/locale/messages.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```

OK - I ignore those uppercase/lowercase warnings because I hate it if Dart wants to tell me how I should name my files... (plural / singular - the same ...)

But what's really annoying is the warning with "line 6" "line 7" and so on.
Thats the reason why all my examples are in **samples**-folder instead of **example** 
It must be possible to have a standalone example!!! - an example with it's own pubspec.yaml 

Please change this behavior

_Copied from original issue: dart-lang/sdk#31563_

**Comment by jakemac53** [comment]
It does seem like only the directories which are exposed directly by pub to your users should be checked, which I believe are exclusively `bin` (pub run) and `lib` (package: imports)?

**Comment by nex3** [comment]
The `example` directory is intended to be runnable using your package's dev dependencies.

**Comment by efortuna** [comment]
This feels like this makes less sense in the realm of Flutter where the `example` might show a lot more complicated usage than what you want your package to have a dependency on, though right?

**Comment by jakemac53** [comment]
> This feels like this makes less sense in the realm of Flutter where the `example` might show a lot more complicated usage than what you want your package to have a dependency on, though right?

That does seem like a valid use case. In general, nested packages are really difficult to deal with, and have caused issues for tools throughout darts history, so avoiding them would be ideal.

Now that we support git dependencies to sub-paths of a repo, I think the justification for complicated examples that live under the package directory is less, and we should instead encourage users to create a separate, top level directory next to their package (or even multiple, one per example).

For instance it is also worth noting that the entire package directory gets shipped to pub today even though its not accessible (without digging through the pub cache). So there is at least one advantage to doing it this way - less code for your users to download.

All that being said - pub could special case subdirectories that contain a `pubspec.yaml` and not analyze them, and probably should.

**Comment by jakemac53** [comment]
cc @kevmoo @natebosch wdyt?
