### ISSUE TITLE
Invalid argument(s): Minimum version ("2.0.0-dev.15.0") must be less than maximum ("2.0.0-dev.14.0").

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1770]
Running `pub --trace upgrade` causes this exception

[log.txt](https://github.com/dart-lang/pub/files/1600816/log.txt)

`pub get` (with existing `pubspec.lock`) completes without an error.

**Comment by nex3** [comment]
I'm working on a fix, but for now this can be worked around by upgrading to 2.0.0-dev.15.0.

**Comment by zoechi** [comment]
Good to know it's a known problem.
I tried `brew upgrade` but dev-15.0` doesn't seem to be available yet (as of yesterday). I'll check again.

**Comment by nex3** [comment]
You may need to wait until 2.0.0-dev.15 actually releases.
