### ISSUE TITLE
Recent travis failure

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1773]
https://travis-ci.org/dart-lang/pub/jobs/325134717

`test/build/outputs_results_to_json_test.dart: outputs results to JSON in a successful build`
https://travis-ci.org/dart-lang/pub/jobs/325134717#L583

**Comment by kevmoo** [comment]
CC @grouma @nex3

**Comment by nex3** [comment]
Looks like just a change in dart2js diagnostics.

**Comment by nex3** [comment]
Hmm, actually, this seems to be a flake—dart2js can print a message if compilation takes 10s or more, but it usually doesn't. We should filter those out, I guess.
