### ISSUE TITLE
pub serve doesn't recover from an empty directory in .pub directory

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub#1777]
I recently had a frustrating problem with a missing dependency when trying to run `pub serve` in web package with a dependency on angular. I was seeing the error:

```
[Error from Dart2JS on angular_components_example|web/main.dart]:
web/packages/angular/src/common/pipes/date_pipe.dart:1:1:
Can't read 'package:intl/intl.dart' (Could not find asset intl|lib/intl.dart.).
import 'package:intl/intl.dart';
```

When investigating I noted that the angular package has a dependency on intl in it's pubspec. Running `pub get` and `pub upgrade` succeeded without errors. The correct path to the intl/lib was located in my `.packages` file. All of the intl files were in the location listed in the `.packages` file. Running `pub cache repair` does not fix the issue.

@jakemac53 helped me find the issue. There was an empty intl directory in my projects `.pub` directory. The only fix was to manually delete the empty directory. That fixed it for me but we had to clone the pub repo and place print statements all over to finally figure out what was going on. 

We suspect that maybe this was due to an old version of intl that relied on a transformer but the current version does not.

You can repro this scenario in any web package by deleting all of the `.dart` files from any directory in .pub directory for any package you are working in. Then try to run `pub serve`. 

Interestingly, everything seems to works fine if you run `pub build`.

**Comment by matanlurey** [comment]
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.
