### ISSUE TITLE
Certificate handshake error in client

### ISSUE THREAD

**Issue by tmst** [dart-lang/pub#1786]
I have no idea how certificates work:

/home/tom/work/dart-sdk/bin/pub get
Resolving dependencies...
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(ssl_cert.c:345))
Process finished with exit code 1

[certificate_error.txt](https://github.com/dart-lang/pub/files/1647812/certificate_error.txt)
[certs.txt](https://github.com/dart-lang/pub/files/1647845/certs.txt)

**Comment by nex3** [comment]
Pub doesn't do anything special with certificates, it just calls out to `dart:io`. I suspect the underlying issue here is your OS configuration, but I'm going to move this to the SDK repo because the folks there will probably have more expertise with which to help you diagnose the issue.

**Comment by nex3** [comment]
This issue was moved to dart-lang/sdk#31948
