### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/pub#1787]
_From @maksimr on January 20, 2018 20:34_

Hello,

I'm going through ["Angular tutorial"](https://webdev.dartlang.org/angular/tutorial/toh-pt3)
and when I run `pub serve` it took **9 seconds** to compile templates. When I change something it compiles a little bit faster **5 seconds** but is it expected compilation time?

I have tried *dart@1.24.3/pub@1.24.3* and *dart@2.0.0-dev.9.0/pub@2.0.0-dev.9.0* both have same compilation time

Thanks

Additional information
*Operating system*: macOs High Sierra
*Browser*: Chrome
*Sample project*: https://github.com/angular-examples/quickstart

```dart
Loading source assets...
Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers...
Serving angular_app web  on http://localhost:8080
Serving angular_app test on http://localhost:8081
Build completed successfully
[web]  GET Served 3 assets.
[Info from Dart2JS]:
Compiling angular_app|web/main.dart...
[Info from Dart2JS]:
Took 0:00:09.503145 to compile angular_app|web/main.dart.
Build completed successfully
[web]  GET main.dart.js → angular_app|web/main.dart.js
[web]  GET main.dart.js.map → angular_app|web/main.dart.js.map
Build completed successfully
[web]  GET Served 3 assets.
[Info from Dart2JS]:
Compiling angular_app|web/main.dart...
[Info from Dart2JS]:
Took 0:00:04.611908 to compile angular_app|web/main.dart.
Build completed successfully
[web]  GET main.dart.js → angular_app|web/main.dart.js
[web]  GET main.dart.js.map → angular_app|web/main.dart.js.map
```

<img width="1429" alt="2018-01-20_2335" src="https://user-images.githubusercontent.com/616193/35187796-baed15ca-fe3a-11e7-9598-8db94ecad84c.png">

_Copied from original issue: dart-lang/pub-dartlang-dart#937_

**Comment by jakobr-google** [comment]
This repo is for the pub server running at pub.dartlang.org. The issue here is probably more on the SDK side (DDC/dart2js), or the pub client.

**Comment by jakemac53** [comment]
This looks like it is primarily dart2js compilation time. You can try `--web-compiler=dartdevc` which might be a little bit slower for the first build but the incremental build should be faster.

The [new build system](https://github.com/dart-lang/build/blob/master/docs/getting_started.md) should make this better as well.

**Comment by jakemac53** [comment]
@maksimr yes, all js compilation in pub serve is actually on demand (refresh).

With build_runner (the new build system) it is ahead of time though. For dart2js at least that isn't actually what you want in most cases, so we may add back an on-demand version just for that later on.

**Comment by jakemac53** [comment]
@maksimr do you consider this bug closed with the dartdevc support? That is the only compiler which is intended to be fast (its the development compiler). The dart2js compiler does a lot of optimizations for deployment that slow it down, and it isn't modular like dartdevc.

**Comment by maksimr** [comment]
@jakemac53 Yes, sure

Thanks
