### ISSUE TITLE
Provide independent authorization flow

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/pub#1788]
Hello there! Let's be realistic, today Dart is not popular and therefore widely used across developers. Among other problems, the one that persist is Dart high addiction of Google, such addiction we can see in different things. Specifically, current pub authorization flow. To simply publish library to pub, I must create Google Account to be able to log in with OAuth2 through it. In objectives, I think, pub should has independent authorization mechanism (like npm has), or more trustable by developers (i.e. GitHub, currently implemented by Rust package manager - Cargo).

**Comment by nex3** [comment]
Authorization is more of a server concern, so I'm moving this to the pub server repository.

For historical context, we started with Google account support mostly because it was easy to integrate with App Engine. I think it could make a lot of sense to add GitHub account support as well.

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#946
