### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED Error when running pub get

### ISSUE THREAD

**Issue by tomialagbe** [dart-lang/pub#1790]
For the past few days i've been getting the following error message whenever i try to run `pub get` on dart projects or `flutter packages get` on flutter projects
```
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(ssl_cert.c:345))
```
I'm running on Windows 10 and my dart version is 1.25.0-dev.11.0

**Comment by nex3** [comment]
Duplicate of dart-lang/sdk#31948.
