### ISSUE TITLE
"Invalid upload: no pubspec.yaml file" on macosx sierra

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/pub#1793]
Seams that `pub` is using the wrong options when calling macosx `bsdtar` command, so `pub publish` with fail.

I've worked around it be `brew` installing gnu tar and adding a wrapper script that will replace `@/dev/stdin`  with `-T/dev/stdin` .

**Comment by nex3** [comment]
Unfortunately, pub only works with the operating system's built-in tar command currently. See #1602 for details.

**Comment by dam0vm3nt** [comment]
mmh, there's something wrong then, I've installed `gnu-tar` because it was not working with the native command.

**Comment by natebosch** [comment]
@dam0vm3nt - can you reopen the issue with a repro using `bsdtar`?

What options was `pub` using that are unsupported? What version of `bsdtar` do you have?

I don't see any changes in our usage of `tar` in a while, and my mac should be up to date and has `bsdtar 2.8.3 - libarchive 2.8.3` which has been the version for a while AFAIK and should work with the options `pub` is passing.

**Comment by dam0vm3nt** [comment]
I'll investigate it a bit more. Meanwhile I can confirm that `bsdtar` is `bsdtar 2.8.3 - libarchive 2.8.3`. 

When launching the same command that `pub` executes (captured from the logs launching with `--verbose`) in the terminal :

    git ls-files --cached --others --exclude-standard | tar --format=ustar --create --gzip --directory $PWD @/dev/stdin > /tmp/file.tar.gz

the resulting file was always 10240 bytes long (while the correct size would be greater) and it was actually empty.

Also from the man page : 

![image](https://user-images.githubusercontent.com/2409466/35592826-80d2322c-060e-11e8-887c-853ee3da7146.png)

Seams like the `@` char is wrong here.

**Comment by dam0vm3nt** [comment]
@natebosch I've got no power to reopen the issue, the only thing I can do is open another one citing this one. Do you want me to do it ?

**Comment by natebosch** [comment]
AFAIK the `@` is legal and being used correctly here.

Can you paste the results of the first part in that pipeline? `git ls-files --cached --others --exclude-standard`

**Comment by dam0vm3nt** [comment]
Yep!

Running `git ls-files --cached --others --exclude-standard` will give : 

![image](https://user-images.githubusercontent.com/2409466/35673910-32e7f5fc-0743-11e8-85b0-290696a9dcdc.png)

...

![image](https://user-images.githubusercontent.com/2409466/35673950-561d1106-0743-11e8-95f4-bcdd1fdbd06e.png)

As you can see there's a `pubspec.yaml` there. If I save the result in a file (`files.list`) and then I issue a  

    cat files.list| tar --format=ustar --create --gzip --directory $PWD/. @/dev/stdin > a.tar.gz

this is the result : 

![image](https://user-images.githubusercontent.com/2409466/35674083-d26d35c4-0743-11e8-8d79-f43fa7f54b4c.png)

instead if I replace `@` with `-T` (according to the bsdtar man page - see below) and issue this command : 

    cat files.list| tar --format=ustar --create --gzip --directory $PWD/. -T /dev/stdin > a.tar.gz

this is the result

![image](https://user-images.githubusercontent.com/2409466/35674332-a49afa0e-0744-11e8-8515-7acdf662f18f.png)

That is the correct behavior. Infact from the `bsdtar` man page : 

![image](https://user-images.githubusercontent.com/2409466/35674287-80dc9ec4-0744-11e8-936e-d58d65c62be9.png)

The `tar` I'm using is : 

![image](https://user-images.githubusercontent.com/2409466/35674409-e4707fd2-0744-11e8-9c23-714e5e4bf990.png)

So it seams like something has changed in the last macos version of tar ...

**Comment by natebosch** [comment]
@nex3  - can you take a look? I think you're more familiar with how we use `tar` here.

**Comment by nex3** [comment]
I don't have an OS X device to test this on... can someone who does look into it?

**Comment by natebosch** [comment]
Ah, the commands that are printed with `pub lish -v` don't tell you the whole story.

The command is _not_ `git ls-files --cached --others --exclude-standard | tar --format=ustar --create --gzip --directory $PWD @/dev/stdin`

Instead its something more like:
```sh
git ls-files --cached --others --exclude-standard | sed '0,/^/s//#mtree\n\/set uname=pub gname=pub type=file\n/' | tar --format=ustar --create --gzip --directory $PWD @/dev/stdin
```

When I run it this way it looks like the usage is correct.
We use this because `bsdtar` doesn't give us another way to set `uname` and `gname`
https://github.com/dart-lang/pub/blob/a13bf1d1c8ca94de8cf0a1fc9dd29743ebf30293/lib/src/io.dart#L1058

This is working for me on mac with the same version of bsdtar. Likely something else had been different for you - maybe `git ls-files` didn't have `pubspec.yaml` or something?

**Comment by dam0vm3nt** [comment]
Actually there's something strange. According to the `bsdtar` man page and the behavior on my mac the "@" option is definitively wrong. The correct one is `-T`. Furthermore my `ls-files` shows a `pubspec.yaml` (see the image I've attached). I'll check if the problem is with the `sed` command but honestly I don't believe it.

I understand at the moment I'm the only one having this problem so I figure there should be something wrong on my machine ?

**Comment by natebosch** [comment]
> the "@" option is definitively wrong

It's being used correctly by pub and works for others.

> I figure there should be something wrong on my machine?

Sounds like it. How reliably can you reproduce this with a clean `pub` and a clean `tar` install (not replacing it with something from brew)? Does it happen in multiple pub packages? If you make a fresh git checkout of your package does the publish work there?

**Comment by dam0vm3nt** [comment]
> Sounds like it. How reliably can you reproduce this with a clean pub and a clean tar install (not replacing it with something from brew)? Does it happen in multiple pub packages? If you make a fresh git checkout of your package does the publish work there?

That's exactly the reason why I was insisting. This happens to me to all project with vanilla bsdtar on vanilla mac os sierra. But as we say in my country: "when you are on an highway and you see all the cars are going toward you in the other direction it is safer to think you have taken the wrong lane instead of thinking everyone did the same mistake".

So I'll stay with my wrapper for now until I found the culprit or someone else will raise the same issue.

**Comment by dnfield** [comment]
I'm having this issue as well.  macOS Sierra, bsdtar 2.8.3

**Comment by dnfield** [comment]
Seems like issue is being caused by a file that has a space in the name.

**Comment by natebosch** [comment]
@dnfield - can you give an example reproduction? Is it enough to have a file anywhere in the package with a space in the name?

**Comment by dnfield** [comment]
I'm working on coming up with a minimal case right now.

**Comment by dnfield** [comment]
Yes, appears to be enough to have a file anywhere in package that has a space in it.  Trying to figure out how that space is supposed to be escaped.

**Comment by dnfield** [comment]
Got it.  Spaces need to be escaped as `\040`.
