### ISSUE TITLE
Discussion - Move `.pub` to `.dart_tool/pub`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#1795]
See https://github.com/dart-lang/site-www/issues/444#issuecomment-350500251

We are using `.dart_tool/` directory for the build system because we didn't want to mix with `.pub/`. 
This directory has another level of namespacing (we use `.dart_tool/build` today) which would let us add `.dart_tool/pub` and reduce the number of directories the user needs to ignore.

Moving would be good in the long term, but add some short term pain during the transition.

cc @kevmoo

**Comment by kevmoo** [comment]
👍– fewer directories is goodness.

**Comment by mit-mit** [comment]
re-titling to reflect that this wasn't just a discussion, the actual change was made
