### ISSUE TITLE
Pub makes bogus claims about precompiling executables

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/pub#1804]
```
...
Precompiling executables... 
Precompiled testing:run_tests.
Precompiled markdown:markdown.
Precompiled testing:testing.
Precompiled vector_math:mesh_generator.
Precompiled csslib:css.
...
```

The VM included in the Dart SDK does not include the ability to precompile Dart apps.

**Comment by nex3** [comment]
In VM terms, it's creating a snapshot of these applications. I think it's clearer to end-users who are unfamiliar with Dart VM terminology to call it "precompiling", though.
