### ISSUE TITLE
Warning on `pub publish` a library that includes an `/example` with separate pubspec

### ISSUE THREAD

**Issue by mehaase** [dart-lang/pub#1813]
I have written a library for some web components, and I have also written a little demo web app to show off those components. Here is a simplified layout of my library:

```
|-- CHANGELOG.md
|-- LICENSE
|-- MAINTENANCE.md
|-- README.md
|-- example
|   |-- README.md
|   |-- lib
|   |   |-- about.dart
|   |   |-- about.html
|   |   |-- body.dart
|   |   | (32 more...)
|   |-- pubspec.yaml
|   '-- web
|       |-- index.html
|       '-- main.dart
|-- lib
|   |-- ng_modular_admin.dart
|   |-- src
|   |   |-- components
|   |   |   |-- app.css
|   |   |   |-- app.dart
|   |   |   |-- app.html
|   |   |   | (78 more...)
|   |   |-- framework.dart
|   |   '-- services
|   |       |-- side_nav.dart
|   |       '-- toast.dart
|   |-- util.dart
|   '-- validators.dart
|-- pubspec.yaml
'-- tool
    '-- build-styles.dart
```

The library is called `ng_modular_admin` and it contains a `/lib` directory with a bunch of Angular components. The demo app is called `ng_modular_admin_demo` and it lives in `/example` and it has its own `/example/pubspec.yaml`, `/example/lib`, and `/example/web`. The demo app depends on the library. In the demo app, the `/example/web/main.dart` imports an application component like this: `package:ng_modular_admin_demo/body.dart`. 

This works fine when I'm testing the library and the demo, but when I run `pub publish`, it issues a warning about importing from the `ng_modular_admin_demo` package without depending on it. I think I understand why it is warning on this, because `ng_modular_admin` does not depend on `ng_modular_admin_demo`, and I guess `pub publish` ignores the nested `pubspec.yaml`, but I'm not clear on whether or how I should address this warning.

Is this user error? A violation of packaging guidelines? Or should `pub` handle a nested `/example/pubspec.yaml` more gracefully? If this is user error, I would be happy to submit a PR to clarify the documentation.

The source code for the library and demo is [on github](https://github.com/HyperionGray/ng_modular_admin). Full `pub publish` output is [in a gist](https://gist.github.com/mehaase/66fc5a9e6264a43b234c1b10917c83a9).

**Comment by nex3** [comment]
Pub thinks of examples as part of your package (after all, they're published as part of it!). They're also mostly expected to be individual Dart files that show off your API rather than full-fledged demo applications. If you're creating something that big, I suggest putting it in a separate repository... it doesn't really make sense to have all your users download an entire app along with your package.
