### ISSUE TITLE
.pub directory: print a hint/FYI about being safely deleted?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1814]
Probably don't want to delete them for the user – but it'd be good to get folks to clean them up ASAP as they migrate to Dart 2.

**Comment by nex3** [comment]
We already do delete them for the user. Is that a problem?

**Comment by kevmoo** [comment]
> We already do delete them for the user. Is that a problem?

Maybe not? I guess if they roll back to a previous release they will just have to regenerate.

I didn't check – do we tell folks we're deleting them?

**Comment by nex3** [comment]
No... the directory is just a cache, and it's considered an implementation detail except to the extent that the user has to know to gitignore it. If they're storing something they care about in there, they're living deep in sin.

**Comment by kevmoo** [comment]
ack

**Comment by nex3** [comment]
Can I close this out?

**Comment by kevmoo** [comment]
Please. Thanks
