### ISSUE TITLE
"pub lish" should warn of missing README.md and homepage

### ISSUE THREAD

**Issue by wstrange** [dart-lang/pub#1819]
To promote better packages, pub should warn the user if there is a missing README.md and/or a package homepage:

**Comment by matanlurey** [comment]
+1, or something like this. I think its often not understood you can safely use a Git/GitHub repository for "just testing" or personal packages/projects, instead of publishing essentially a hello world to pub.

/cc @mit-mit

**Comment by nex3** [comment]
We [already require a `homepage` field](https://github.com/dart-lang/pub/blob/master/lib/src/validator/pubspec_field.dart#L17). I'm on board for warning about a readme as well.

**Comment by mit-mit** [comment]
sgtm, thanks!
