### ISSUE TITLE
Add a `summarize` command – print dart sdk version + collapsed version of pubspec.lock

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1827]
Something that is easy to copy-paste into a bug

**Comment by kevmoo** [comment]
```
2.0.0-dev.37.0
bar: 1.3.2 direct main
baz: 0.2.3 transitive
foo: 1.2.3 direct dev
zoo: 8.7.2 direct main – via path
```

**Comment by nex3** [comment]
This is pretty much identical to `pub deps --style compact`, isn't it?

**Comment by kevmoo** [comment]
Ooo...yeah.

If there SDK was there, it'd be perfect.

...and if the items in [...] were sorted

**Comment by kevmoo** [comment]
Will likely land as part of -dev.41
