### ISSUE TITLE
Relax the warning when publishing files with a dot in the name

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub#1834]
It is common practice for generated dart files to contain a dot in the name: `foo.gen.dart`.
If you include the generated file when you publish, pub gives a warning:

```
Suggestions:
* The name of "lib/foo.gen.dart", "foo.gen", may only contain letters, numbers, and underscores.
  Using a valid Dart identifier makes the name usable in Dart code.
```

**Comment by nex3** [comment]
Can you put these files in `src/`? Requiring users to write `.gen` in their import statements seems like a design smell.

**Comment by nshahan** [comment]
Agreed, I would like to hide them better. If they get moved to `src/` will that warning go away when publishing?

**Comment by nex3** [comment]
Yeah, the validator only cares about public libraries.

**Comment by nex3** [comment]
Is that sufficient? Can I close this out?

**Comment by nshahan** [comment]
I can't really move the files at this time, but I agree that the implementation detail of generated files should be hidden better. I'll close it out and look around the warnings for now.
