### ISSUE TITLE
Support peer dependencies 

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1837]
From NPM: https://nodejs.org/en/blog/npm/peer-dependencies/

There is an increasing number of packages (`built_*`, `json_*`, `angular`, so others for Flutter) that require a specific `dev_dependency` range for compatible tooling/code generation. For example, the [`json_annotation`](https://pub.dartlang.org/packages/json_annotation) package is platform agnostic, but requires the [`json_serializable`](https://pub.dartlang.org/packages/json_serializable) package for code generation.

It would be nice to be able to write, in `pubspec.yaml`:

```yaml
name: json_annotation

peer_dependencies:
  json_serializable: ^1.0.0
```

... so that, `dev_dependencies` on `json_serializable` are validated against this range.

/cc @kevmoo @mit-mit

**Comment by kevmoo** [comment]
Yes, please!

**Comment by zoechi** [comment]
What is the difference to a normal dependency?

**Comment by cah4a** [comment]
Hey, 

I'm developing [nock](https://pub.dev/packages/nock) package.
I think the correct way to describe the dependencies of such packages is to make a peer dependency to `test` package.

Is there any plans to implement peer dependencies support?

**Comment by sigurdm** [comment]
... looking through old issues.

A peer_dependency is a constraint on another package but doesn't require that other package to be included in the resolution?

Am I understanding this right?

What happens if you just make a regular dependency? Don't you always need [json_serializable](https://pub.dartlang.org/packages/json_serializable) when you use [json_annotation](https://pub.dartlang.org/packages/json_annotation)?

**Comment by cah4a** [comment]
Peer dependency is a dependency that a user should explicitly specify in a pubspec.

A good article about the corresponding npm feature [here](https://nodejs.org/es/blog/npm/peer-dependencies/).

**Comment by kevmoo** [comment]
@sigurdm – you are correct. If you have a dependency on `json_annotation` you almost certainly want/need a dev_dependency on `json_serializable`

**Comment by sigurdm** [comment]
> Peer dependency is a dependency that a user should explicitly specify in a pubspec.

Sorry I don't get this (might need more coffee). Can you spell out a scenario where a peer dependency solves a problem that a regular dependency wont (in the pub model where all dependencies are shared in a resolution).

**Comment by kevmoo** [comment]
@matanlurey was the original idea maker here. I may have lost the thread....

**Comment by uvlek** [comment]
It would be nice to have implementation of peer dependencies in flutter pubspec

**Comment by sigurdm** [comment]
@uvlek can you explain some scenarios where you would use them? I'm still unsure about what they exactly can help us with.
