### ISSUE TITLE
type 'Symbol' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1856]
[pub_upgrade.log](https://github.com/dart-lang/pub/files/1870768/pub_upgrade.log)

Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "macos_x64"

**Comment by nex3** [comment]
This issue was moved to dart-lang/pub_semver#20
