### ISSUE TITLE
Requesting interop with a Fuchsia SDK for Dart

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1862]
As discussed, we'd like to produce a Fuchsia SDK for Dart which itself contains Dart packages. We are requesting that the pub client become aware of Fuchsia SDK for Dart as a new "source for sdk package dependencies".

Our environment variable wishes to be `FUCHSIA_DART_SDK_ROOT`

Our Fuchsia SDK for Dart layout wishes to match the layout from Flutter SDK:

* VERSION file at the root
* `packages/` directory, itself containing various packages

Please let us know what other info you need. Thank you!

**Comment by nex3** [comment]
When the user tries to install a package that requires Fuchsia but `FUCHSIA_DART_SDK_ROOT` isn't set, what error message should we produce?

**Comment by sethladd** [comment]
* Proposal: "Sorry, we cannot locate a Fuchsia SDK for Dart, which is required by one or more of your dependencies. Please set  
 the FUCHSIA_DART_SDK_ROOT environment variable to point to the Fuchsia SDK for Dart root. To learn more, please visit [some link]."
* `version` (lower-case) is fine, thanks for checking!

(if you like the proposal, I'll dig up the link for you)

**Comment by shrike69** [comment]
This LGTM.

**Comment by nex3** [comment]
> Proposal: "Sorry, we cannot locate a Fuchsia SDK for Dart, which is required by one or more of your dependencies. Please set the FUCHSIA_DART_SDK_ROOT environment variable to point to the Fuchsia SDK for Dart root. To learn more, please visit [some link]."

How does this sound:

> Please set the FUCHSIA_DART_SDK_ROOT environment variable to point to the root of the Fuchsia SDK for Dart. To learn more, see [some link]."

That would show up after version solver output that includes something like "foo requires the Fuchsia SDK".

**Comment by sethladd** [comment]
Ah, if there's already a message for "foo requires the Fuchsia SDK" then lgtm for "Please set the FUCHSIA_DART_SDK_ROOT environment variable to point to the root of the Fuchsia SDK for Dart. To learn more, see [some link].""

Thanks!

**Comment by sethladd** [comment]
Awesome, thank you!

**Comment by nex3** [comment]
You're welcome!

Merging pub into the SDK is blocked on [migrating observatory's build process off barback](https://dart-review.googlesource.com/c/sdk/+/51740), but Nate thinks that won't take much longer.

**Comment by shrike69** [comment]
Hey Seth, would you create a JIRA ticket to track the change we need to make to the existing SDK once this patch lands in Fuchsia?

**Comment by sethladd** [comment]
Sure thing!

**Comment by sethladd** [comment]
@nex3 is there an issue for "merging pub into the Dart SDK"? Something for us to track, so we know when to perform our changes?

**Comment by nex3** [comment]
I think the closest thing to track is the CL I linked above.

**Comment by sethladd** [comment]
For anyone following along, the CL linked above was merged 👍
