### ISSUE TITLE
No matching version of a package even though it exists

### ISSUE THREAD

**Issue by mriede** [dart-lang/pub#1869]
Hi ...

I'm getting this error while running `pub get`:
```
Resolving dependencies... (2.2s)
Package password_hasher has no versions that match 0.2.0 derived from:
- xxxxx depends on version 0.2.0
```

and I'm 100% sure this version exists, as you can see here:
https://pub.dartlang.org/packages/password_hasher
https://pub.dartlang.org/documentation/password_hasher/0.2.0/

So, where is this error coming from? How do I fix it?

**Edit:** Possible duplicate of #1750 
Ran fine with `pub upgrade`

**Comment by eernstg** [comment]
@mriede, this is not directly addressing your issue, but in case you need to explore the dependency relationships, and in case you don't know this already, you might want to take a look at [pubviz](https://pub.dartlang.org/packages/pubviz).
