### ISSUE TITLE
SDK version used by pub does not align with Platform.version on Flutter

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1887]
We'll get pub reporting/using `Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`

Where Platform.version is something like `2.0.0-dev.48.0.flutter-fe606f890b`

**Comment by nex3** [comment]
I think this is a Flutter/SDK issue, not a Pub issue. We just look at the `version` file in the root of the Dart SDK directory.

**Comment by kevmoo** [comment]
Turns out this is not fixed. Hoping #1897 does the trick

**Comment by natebosch** [comment]
Is this what is causing https://github.com/flutter/flutter/issues/17656 ?
