### ISSUE TITLE
pub tests failing on -dev.55+

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1898]
See https://travis-ci.org/dart-lang/pub/builds/380860559

-dev.54: fine
-dev.55: broken

CC @natebosch

**Comment by natebosch** [comment]
Broken by https://github.com/dart-lang/sdk/issues/33166

**Comment by nex3** [comment]
We need that in a release to get the tests green.

**Comment by kevmoo** [comment]
Fixed in Dart -dev.57 - https://travis-ci.org/dart-lang/pub/builds/380859567
