### ISSUE TITLE
Support all operations with `--preview-dart-2`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#1899]
We've so far validated the `pub run` code path. We need to verify Dart 2 runtime semantics for all other pub commands.

So far @kevmoo has hit a problem with `pub upgrade` - can you add details?

**Comment by kevmoo** [comment]
I think this is due to `pkg:async` being a dot release behind in the SDK. Trying now...

**Comment by kevmoo** [comment]
I think it comes down to this: https://github.com/dart-lang/http_throttle/pull/7

**Comment by kevmoo** [comment]
This helps a bit with `pub upgrade` – but there are still issues https://dart-review.googlesource.com/c/sdk/+/55988

**Comment by dgrove** [comment]
What needs to happen to do that?

**Comment by kevmoo** [comment]
Run the tests with DART_VM_OPTIONS=--preview-dart-2

See failures. Fix failures.

I published pkg:test last night that works with the flag. Some tests do
pass...

**Comment by nex3** [comment]
> What needs to happen to do that?

There's some work that needs to be done making the tests run pub processes in Dart 2 mode, and of course https://github.com/dart-lang/pub/issues/1898 needs to be fixed, but the biggest blocker is performance. Pub has 272 test files, and those tests contain 537 invocations of pub as a subprocess. If each test file takes five seconds to parse and each pub invocation takes ten, that's almost two hours of pure overhead for each full test iteration, on top of the time it takes to actually *run* the tests. We need to bring that down substantially before it's feasible to iterate on these tests or run them on CI to ensure that we don't regress Dart 2 semantics.

**Comment by dgrove** [comment]
At tip of bleeding edge app-jit snapshots are mostly working (there seems
to be a race condition that I suspect shows up if you're not building from
a clean SDK build - see https://github.com/dart-lang/sdk/issues/33167 ).

There should enough functioning now to make progress here.

**Comment by nex3** [comment]
Creating snapshots isn't an issue--since the slowdown is all in the parsing phase, script snapshots give us all the speedup we'd need anyway. The issue is that we'd need to recompile snapshots for each test file as we iterate on the code, which takes even longer than just running the tests from source.

**Comment by natebosch** [comment]
We've been running with Dart 2 for a bit now and nothing new has come up.
