### ISSUE TITLE
This is an unexpected error. Please run      pub --trace get

### ISSUE THREAD

**Issue by jzzhrqp** [dart-lang/pub#1905]
Working dir: E:\WebstormProjects\dart_smartchat_demo1
F:\Dart\dart-sdk\bin\pub.bat get
Resolving dependencies...
+ analyzer 0.30.0+4 (0.32.0 available)
+ angular 4.0.0+2 (5.0.0-alpha+12 available)
+ angular_compiler 0.3.0+1 (0.4.0-alpha+12 available)
+ angular_components 0.8.0 (0.9.0-alpha+12 available)
+ angular_forms 1.0.0 (2.0.0-alpha+4 available)
+ angular_test 1.0.1 (2.0.0-alpha+10 available)
+ ansicolor 0.0.9 (0.1.0 available)
+ archive 1.0.33
+ args 0.13.7 (1.4.3 available)
+ async 1.13.3 (2.0.7 available)
+ barback 0.15.2+14 (0.15.2+16 available)
+ boolean_selector 1.0.3
+ browser 0.10.0+3
+ build 0.11.2 (0.12.6 available)
+ build_barback 0.4.0+2 (0.5.0+4 available)
+ build_config 0.2.5 (0.2.6+2 available)
+ charcode 1.1.1
+ cli_util 0.1.3
+ code_builder 1.0.4 (3.0.3 available)
+ code_transformers 0.5.1+5
+ collection 1.14.6 (1.14.9 available)
+ convert 2.0.1
+ crypto 2.0.2+1 (2.0.3 available)
+ csslib 0.14.3 (0.14.4 available)
+ dart_style 1.0.9+1 (1.0.14 available)
+ dart_to_js_script_rewriter 1.0.3
+ fixnum 0.10.7
+ front_end 0.1.0-alpha.4.1 (0.1.0 available)
+ func 1.0.0
+ glob 1.1.5
+ html 0.13.3
+ http 0.11.3+16
+ http_multi_server 2.0.4
+ http_parser 3.1.2
+ intl 0.15.6
+ io 0.3.2+1
+ isolate 1.1.0 (2.0.0 available)
+ js 0.6.1
+ kernel 0.3.0-alpha.1.1 (0.3.0 available)
+ logging 0.11.3+1
+ matcher 0.12.1+4 (0.12.2+1 available)
+ meta 1.1.5
+ mime 0.9.5 (0.9.6+1 available)
+ multi_server_socket 1.0.1
+ node_preamble 1.4.1
+ observable 0.20.4+3 (0.22.1+2 available)
+ package_config 1.0.3
+ package_resolver 1.0.2
+ pageloader 2.2.6
+ path 1.5.1
+ perf_api 0.1.0
+ plugin 0.2.0+2
+ pool 1.3.4 (1.3.5 available)
+ pub_semver 1.4.1
+ quiver 0.25.0 (0.29.0+1 available)
+ quiver_hashcode 1.0.0
+ sass 1.1.1 (1.3.2 available)
+ sass_builder 1.2.0 (2.0.0 available)
+ scratch_space 0.0.1+3 (0.0.2+1 available)
+ shelf 0.7.3 (0.7.3+1 available)
+ shelf_packages_handler 1.0.3
+ shelf_static 0.2.7 (0.2.7+1 available)
+ shelf_web_socket 0.2.2 (0.2.2+1 available)
+ source_gen 0.7.4+3 (0.8.1+1 available)
+ source_map_stack_trace 1.1.4
+ source_maps 0.10.5
+ source_span 1.4.0
+ stack_trace 1.9.2
+ stream_channel 1.6.6
+ string_scanner 1.0.2
+ term_glyph 1.0.0
+ test 0.12.34 (0.12.38+1 available)
+ tuple 1.0.1
+ typed_data 1.1.5
+ unittest 0.11.7 (0.12.4+1 available)
+ utf 0.9.0+3 (0.9.0+4 available)
+ uuid 0.5.3 (1.0.0 available)
+ watcher 0.9.7+6 (0.9.7+7 available)
+ web_socket_channel 1.0.6 (1.0.7 available)
+ webdriver 1.2.3 (2.0.0-beta available)
+ yaml 2.1.13 (2.1.14 available)
Downloading code_transformers 0.5.1+5...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 125                _PubHttpClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 30  ThrottleClient.send.<fn>
This is an unexpected error. Please run

    pub --trace get

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Process finished with exit code 69

**Comment by sigurdm** [comment]
I don't know why the server would ever respond with 424. That makes no sense.

Closing as stale.

Please reopen if you can still reproduce.
