### ISSUE TITLE
This is an unexpected error

### ISSUE THREAD

**Issue by oreo** [dart-lang/pub#1907]
[HTTP error 424: Failed Dependency
package:pub/src/http.dart 220                                                            _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33                                              ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 304                                                   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 199                                                   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372                                                      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                                                               runZoned
package:pub/src/http.dart 275                                                            withDependencyType
package:pub/src/entrypoint.dart 367                                                      Entrypoint._get
package:pub/src/entrypoint.dart 229                                                      Entrypoint.acquireDependencies.<fn>
dart:async                                                                               Future.wait
package:pub/src/entrypoint.dart 229                                                      Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 41                                                  UpgradeCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 194                                                     CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                  PubCommandRunner.runCommand.<fn>
dart:async                                                                               new Future.sync
package:pub/src/utils.dart 115                                                           captureErrors.<fn>
dart:async                                                                               runZoned
package:pub/src/utils.dart 134                                                           captureErrors
package:pub/src/command_runner.dart 168                                                  PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                  PubCommandRunner.run
===== asynchronous gap ===========================
/b/build/slave/Mac_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8  main
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
](url)

**Comment by jonasfj** [comment]
Please reopen if this is still a problem?

Assume you were using Chinese community mirror :)
