### ISSUE TITLE
No retry on "error 69"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1910]
Not sure why, and not sure why it didn't retry. This is on travis BTW:

```
Connection closed before full header was received
The command "pub get" failed and exited with 69 during .
Your build has been stopped.
```

https://travis-ci.org/dart-lang/angular/jobs/383427039

**Comment by sigurdm** [comment]
Not sure exactly what went wrong here...

Is this still reproducible?

**Comment by sigurdm** [comment]
Closing, assuming stale.
