### ISSUE TITLE
Transitive dependency on a non-existent package provides an unhelpful error

### ISSUE THREAD

**Issue by grouma** [dart-lang/pub#1913]
I am creating a new package `build_runner_core` which is dependent on by `build_runner`. `build_runner` has a path override to this new package since it isn't publish yet.

Now all packages that depend on `build_runner` with a path overrides give the following error:

```
Because every version of build_runner from path depends on build_runner_core any which is forbidden, build_runner from path is forbidden.
So, because build_config depends on build_runner from path, version solving failed.
```

It was not obvious that the issue is due to the fact that `build_runner_core` does not exist yet. The temporary solution was to provide a path override to `build_runner_core`.

**Comment by jakemac53** [comment]
Note that there was actually a version dependency on `build_runner_core` in the `build_runner` pubspec as well, not an `any` dependency as indicated in the message.

**Comment by sigurdm** [comment]
Not exactly sure when we changed here. But it seems we have better messages here.

I create `pubspec.yaml`:

```
name: sample
environment:
  sdk: ^2.12.0
dependencies:
  a:
    path: a
```

and `a/pubspec.yaml`:

```
name: a

environment:
  sdk: ^2.12.0

dependencies:
  does_not_exist_yet:
```

With sdk 2.12.0 I get:
```
> dart pub get
Resolving dependencies... 
Because every version of a from path depends on does_not_exist_yet any which is forbidden, a from path is forbidden.
So, because sample depends on a from path, version solving failed.
```

But with dart 3.5.0 I get

```
> dart pub get
Resolving dependencies... 
Because every version of a from path depends on does_not_exist_yet any which doesn't exist (could not find package
  does_not_exist_yet at https://pub.dev), a from path is forbidden.
So, because sample depends on a from path, version solving failed.
```

I think that is quite readable.

Closing as fixed.
