### ISSUE TITLE
pub global run foo results in "Unable to spawn isolate ... Error: Not found: package:foo/foo.dart"

### ISSUE THREAD

**Issue by chalin** [dart-lang/pub#1914]
When I try to run globally installed pub commands, I get the following error (not only for stagehand):

```console
> pub global run stagehand web-angular
Unable to spawn isolate: Error: Could not resolve the package 'stagehand' in 'package:stagehand/stagehand.dart'.
Error: Could not resolve the package 'stagehand' in 'package:stagehand/src/cli_app.dart'.
package:stagehand/stagehand.dart: Error: Not found: package:stagehand/stagehand.dart.
```

This is my environment:

```console
> dart --version
Dart VM version: 2.0.0-dev.60.0 (Mon Jun 4 22:09:13 2018 +0200) on "macos_x64"
> set | grep DART
DART_VM_OPTIONS=--preview-dart-2
```

Among other things, this is breaking the build for site-www -- e.g., see [this Travis log](https://travis-ci.org/dart-lang/site-www/jobs/388409825).

cc @kevmoo @kwalrath

**Comment by natebosch** [comment]
I think there had been a bug about the `spawnUri` API not handling packages arguments correctly but I thought that had been closed...

**Comment by natebosch** [comment]
Ah, we're not using the latest pub in the SDK, that's the likely issue. Attempting now to verify that updating the pub version will solve this.

**Comment by natebosch** [comment]
yeah, latest pub seems to fix this. Pulling it in with https://dart-review.googlesource.com/c/sdk/+/58804

**Comment by chalin** [comment]
Dart VM version: 2.0.0-dev.61.0 (Mon Jun 11 15:46:09 2018 +0200) on "macos_x64" seems to contain the fix.
