### ISSUE TITLE
Proxy failed to establish tunnel (503 Service Unavailable)

### ISSUE THREAD

**Issue by hanjole** [dart-lang/pub#1915]
Running "flutter packages get" in myapp...
Proxy failed to establish tunnel (503 Service Unavailable)
package:pub/src/source/hosted.dart 344                                                     BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 144                                                     BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 168                                                            BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76                                              PackageLister._versions.<fn>.<fn>
dart:async                                                                                 runZoned
package:pub/src/http.dart 275                                                              withDependencyType
package:pub/src/solver/package_lister.dart 75                                              PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                                                 new Future.sync
package:async/src/async_memoizer.dart 43                                                   AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74                                              PackageLister._versions
package:pub/src/solver/package_lister.dart 111                                             PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 355                                             VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 309                                                             minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 351                                             VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 98                                              VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35                                                             resolveVersions.<fn>
package:pub/src/log.dart 378                                                               progress
package:pub/src/solver.dart 32                                                             resolveVersions
package:pub/src/entrypoint.dart 193                                                        Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38                                                        GetCommand.run
package:args/command_runner.dart 194                                                       CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                    PubCommandRunner.runCommand.<fn>
dart:async                                                                                 new Future.sync
package:pub/src/utils.dart 115                                                             captureErrors.<fn>
dart:async                                                                                 runZoned
package:pub/src/utils.dart 134                                                             captureErrors
package:pub/src/command_runner.dart 168                                                    PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                    PubCommandRunner.run
===== asynchronous gap ===========================
/b/build/slave/Linux_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1)
---------------------------------------------
I encountered this problem for the first time
This is the company's computer,
But I can visit google
There is also a problem that stuck in executing flutter run "Resolving dependencies..."
help me
thanks

**Comment by DayDayYiDay** [comment]
add https://pub.dartlang.org to your proxy rules,I fix it with this

**Comment by sigurdm** [comment]
This issue is very old now - is this still reproducing?

**Comment by sigurdm** [comment]
Closing, assuming stale
