### ISSUE TITLE
flutter packages get failed. problem with cupertino_icons?

### ISSUE THREAD

**Issue by mgudipati** [dart-lang/pub#1930]
---- Log transcript ----
FINE: Pub 1.24.3
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - cupertino_icons ^0.1.2 from hosted (cupertino_icons) (locked to 0.1.2)
    | - cloud_firestore ^0.7.3 from hosted (cloud_firestore)
    | - flutter any from sdk (flutter) (locked to 0.0.0)
IO  : Get versions from https://pub.dartlang.org/api/packages/cloud_firestore.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cloud_firestore
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 95E76CEA-3860-4CF1-81E7-CDCDF6FA41B7
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cloud_firestore
    | took 0:00:00.772661
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 06:06:27 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: * start at root
SLVR: | cupertino_icons 0.1.2 from hosted is locked
IO  : Describe package at https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 95E76CEA-3860-4CF1-81E7-CDCDF6FA41B7
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2
    | took 0:00:00.348560
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 06:06:28 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/cupertino_icons.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 95E76CEA-3860-4CF1-81E7-CDCDF6FA41B7
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cupertino_icons
    | took 0:00:00.396702
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 06:06:28 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | version 0.1.1 of cupertino_icons doesn't match >=0.1.2 <0.2.0:
    | |   baby_names 0.0.0 (root) -> cupertino_icons ^0.1.2 from hosted (cupertino_icons)
SLVR: | version 0.1.0 of cupertino_icons doesn't match >=0.1.2 <0.2.0:
    | |   baby_names 0.0.0 (root) -> cupertino_icons ^0.1.2 from hosted (cupertino_icons)
SLVR: BacktrackingSolver took 0:00:01.640160 seconds.
    | - Tried 1 solutions
    | - Requested 2 version lists
    | - Looked up 0 cached version lists
    | 
FINE: Resolving dependencies finished (1.6s).
ERR : Package cupertino_icons has no versions that match >=0.1.2 <0.2.0 derived from:
    | - baby_names depends on version ^0.1.2
FINE: Exception type: NoVersionException
FINE: package:pub/src/entrypoint.dart 194                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                    PubCommandRunner.run
    | /Users/whesse/dart/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                 _Completer.completeError
    | package:pub/src/entrypoint.dart 242                        Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                 _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 191                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                 new Future.microtask
    | package:args/command_runner.dart 142                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
---- End log transcript ----

**Comment by zoechi** [comment]
You seem to be using Flutter and it looks like an older version (`Dart pub 1.24.3` - not sure which version of pub is packed with which version of Flutter.

If you use Flutter, don't use `pub` directly (not sure if you did), use instead `flutter packages get`.
In this case please add the output of `flutter doctor`.

**Comment by mgudipati** [comment]
Thanks. I tried various things, the latest being, switching to master channel. Here is the flutter doctor output:

[✓] Flutter (Channel master, v0.5.6-pre.39, on Mac OS X 10.13.5 17F77, locale en-IN)
    • Flutter version 0.5.6-pre.39 at /Users/mgudipati/Development/flutter
    • Framework revision a18f5e84a1 (8 hours ago), 2018-06-20 20:23:51 -0400
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/mgudipati/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

Also, here is my partial pubspec.yaml file:
name: myapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by zoechi** [comment]
Can you please wrap the `pubspec.yaml` content with ```.
Unformatted YAML is like encrypted yaml pretty much unreadable.

Can you please try with the `dev` channel as well instead of `master`?

**Comment by mgudipati** [comment]
I get this after switching to dev channel.

---- Log transcript ----
FINE: Pub 1.24.3
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - cupertino_icons ^0.1.2 from hosted (cupertino_icons)
    | - cloud_firestore any from hosted (cloud_firestore)
    | - flutter any from sdk (flutter)
IO  : Get versions from https://pub.dartlang.org/api/packages/cupertino_icons.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7015EFA9-60CE-4DF6-AE53-245D16C51810
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cupertino_icons
    | took 0:00:00.724086
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 08:32:55 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/cloud_firestore.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cloud_firestore
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7015EFA9-60CE-4DF6-AE53-245D16C51810
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cloud_firestore
    | took 0:00:00.375501
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 08:32:56 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: Could not get versions for flutter from sdk:
    | The Flutter SDK is not available.
    | 
    | package:pub/src/source/sdk.dart 98                        BoundSdkSource._verifiedPackagePath
    | package:pub/src/source/sdk.dart 85                        BoundSdkSource._loadPubspec
    | package:pub/src/source/sdk.dart 72                        BoundSdkSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 229            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 137  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart 252            SolverCache.getVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/source/hosted.dart 143                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                _Completer.completeError
    | package:pub/src/source/sdk.dart 76                        BoundSdkSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/source/sdk.dart 63                        BoundSdkSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 229            SolverCache.getVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_solver.dart 203            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 115  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 44   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 137  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart 252            SolverCache.getVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/source/hosted.dart 143                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                Future.forEach
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select
    | ===== asynchronous gap ===========================
    | dart:async                                                _asyncThenWrapperHelper
    | package:pub/src/solver/version_selection.dart 53          VersionSelection.select
    | package:pub/src/solver/backtracking_solver.dart 171       BacktrackingSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/backtracking_solver.dart 157       BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 41             resolveVersions.<fn>
    | package:pub/src/log.dart 409                              progress
    | package:pub/src/solver/version_solver.dart 39             resolveVersions
    | package:pub/src/entrypoint.dart 192                       Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/entrypoint.dart 191                       Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                       GetCommand.run
    | package:args/command_runner.dart 194                      CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:args/command_runner.dart 142                      CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand.<fn>
    | dart:async                                                new Future.sync
    | package:pub/src/utils.dart 102                            captureErrors.<fn>
    | package:stack_trace                                       Chain.capture
    | package:pub/src/utils.dart 117                            captureErrors
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand
SLVR: Could not get versions for flutter from sdk:
    | The Flutter SDK is not available.
    | 
    | package:pub/src/source/sdk.dart 98                        BoundSdkSource._verifiedPackagePath
    | package:pub/src/source/sdk.dart 85                        BoundSdkSource._loadPubspec
    | package:pub/src/source/sdk.dart 72                        BoundSdkSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 229            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 137  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart 252            SolverCache.getVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/source/hosted.dart 143                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                _Completer.completeError
    | package:pub/src/source/sdk.dart 76                        BoundSdkSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/source/sdk.dart 63                        BoundSdkSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 229            SolverCache.getVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_solver.dart 203            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 115  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 44   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 137  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart 252            SolverCache.getVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/source/hosted.dart 143                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                Future.forEach
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select
    | ===== asynchronous gap ===========================
    | dart:async                                                _asyncThenWrapperHelper
    | package:pub/src/solver/version_selection.dart 53          VersionSelection.select
    | package:pub/src/solver/backtracking_solver.dart 171       BacktrackingSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/backtracking_solver.dart 157       BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 41             resolveVersions.<fn>
    | package:pub/src/log.dart 409                              progress
    | package:pub/src/solver/version_solver.dart 39             resolveVersions
    | package:pub/src/entrypoint.dart 192                       Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/entrypoint.dart 191                       Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                       GetCommand.run
    | package:args/command_runner.dart 194                      CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:args/command_runner.dart 142                      CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand.<fn>
    | dart:async                                                new Future.sync
    | package:pub/src/utils.dart 102                            captureErrors.<fn>
    | package:stack_trace                                       Chain.capture
    | package:pub/src/utils.dart 117                            captureErrors
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand
SLVR: * start at root
SLVR: BacktrackingSolver took 0:00:01.266572 seconds.
    | - Tried 1 solutions
    | - Requested 3 version lists
    | - Looked up 1 cached version lists
    | 
FINE: Resolving dependencies finished (1.2s).
ERR : The Flutter SDK is not available.
    | Depended on by:
    | - myapp 
FINE: Exception type: DependencyNotFoundException
FINE: package:pub/src/entrypoint.dart 194                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                    PubCommandRunner.run
    | /Users/whesse/dart/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                 _Completer.completeError
    | package:pub/src/entrypoint.dart 242                        Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                 _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 191                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                 new Future.microtask
    | package:args/command_runner.dart 142                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
---- End log transcript ----

**Comment by zoechi** [comment]
That doesn't look too good. Perhaps you need to run `flutter doctor`, but `flutter channel` should invoke that itself at the end.

**Comment by mgudipati** [comment]
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.5 17F77, locale en-IN)
    • Flutter version 0.5.5 at /Users/mgudipati/Development/flutter
    • Framework revision 020e0ef55c (7 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/mgudipati/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by mgudipati** [comment]
I was just trying to follow along https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#8

and ran into this issue right after adding cloud_firestore: dependency :(

**Comment by zoechi** [comment]
Your `cloud_firestore:` entry in the `pubpsec.yaml` part you posted above  seems to be missing a version constraint, or did you leave that just out when you copy/pasted?

**Comment by mgudipati** [comment]
I tried mentioning the version but that failed too. So I thought this would point to "any"!!

**Comment by mgudipati** [comment]
cloud_firestore: ^0.7.3

**Comment by mgudipati** [comment]
I reinstalled flutter on my mac. 

flutter --version
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

created a new project
added cloud_firestore: ^0.7.3 dependency
flutter packages get

NO LUCK!!

Package cupertino_icons has no versions that match >=0.1.2 <0.2.0 derived from:
- baby_names depends on version ^0.1.2
---- Log transcript ----
FINE: Pub 1.24.3
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - cupertino_icons ^0.1.2 from hosted (cupertino_icons) (locked to 0.1.2)
    | - cloud_firestore ^0.7.3 from hosted (cloud_firestore)
    | - flutter any from sdk (flutter) (locked to 0.0.0)
IO  : Get versions from https://pub.dartlang.org/api/packages/cloud_firestore.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cloud_firestore
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 5266C21E-5D40-4A6F-A3D7-E9733E7271CE
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cloud_firestore
    | took 0:00:00.795316
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 09:38:05 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: * start at root
SLVR: | cupertino_icons 0.1.2 from hosted is locked
IO  : Describe package at https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 5266C21E-5D40-4A6F-A3D7-E9733E7271CE
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cupertino_icons/versions/0.1.2
    | took 0:00:00.348993
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 09:38:06 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/cupertino_icons.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 5266C21E-5D40-4A6F-A3D7-E9733E7271CE
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.24.3
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cupertino_icons
    | took 0:00:00.398356
    | transfer-encoding: chunked
    | date: Thu, 21 Jun 2018 09:38:06 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | version 0.1.1 of cupertino_icons doesn't match >=0.1.2 <0.2.0:
    | |   baby_names 0.0.0 (root) -> cupertino_icons ^0.1.2 from hosted (cupertino_icons)
SLVR: | version 0.1.0 of cupertino_icons doesn't match >=0.1.2 <0.2.0:
    | |   baby_names 0.0.0 (root) -> cupertino_icons ^0.1.2 from hosted (cupertino_icons)
SLVR: BacktrackingSolver took 0:00:01.667211 seconds.
    | - Tried 1 solutions
    | - Requested 2 version lists
    | - Looked up 0 cached version lists
    | 
FINE: Resolving dependencies finished (1.6s).
ERR : Package cupertino_icons has no versions that match >=0.1.2 <0.2.0 derived from:
    | - baby_names depends on version ^0.1.2
FINE: Exception type: NoVersionException
FINE: package:pub/src/entrypoint.dart 194                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                    PubCommandRunner.run
    | /Users/whesse/dart/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                 _Completer.completeError
    | package:pub/src/entrypoint.dart 242                        Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                 _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 191                        Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                 new Future.microtask
    | package:args/command_runner.dart 142                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
---- End log transcript ----

**Comment by zoechi** [comment]
Does't seem to even try `0.1.2`. It only tries `0.1.0` and `0.1.1`.

**Comment by sigurdm** [comment]
This issue is very old.

Does this still reproduce?

**Comment by sigurdm** [comment]
Closing assuming stale
