### ISSUE TITLE
pub global activate doesn't work on dev.64.1

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#1932]
It looks like it's because we're trying to run the Dart 1 snapshot with a Dart 2 VM

**Comment by alorenzen** [comment]
This is blocking anyone using `webdev` externally for angular development from working. If someone is assigned to look into the issue, can we please mark them as Assignee?

**Comment by natebosch** [comment]
The workaround for now is `pub global run webdev` which seems to work

**Comment by alorenzen** [comment]
@kevmoo is IntelliJ integration for `webdev` broken because of this?

**Comment by kevmoo** [comment]
Likely – webdev won't be able to run...

**Comment by munificent** [comment]
https://github.com/dart-lang/pub/pull/1933

**Comment by dougreese** [comment]
The `pub global run webdev` workaround does not work for me.  

Using `build_runner: ^0.9.0` results in: 
```
webdev could not run for this project.
The `build_runner` version – 0.9.0 – is not within the allowed constraint – ^0.8.2.
```

Using `build_runner: ^0.8.2` or `^0.8.3` results in a bunch of precompile errors, such as:
```
Failed to precompile build_runner:graph_inspector:
file:///home/me/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/phase.dart:10:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
```

**Comment by kevmoo** [comment]
I'll have a new release of webdev out tomorrow!

**Comment by alorenzen** [comment]
@munificent what's the status here?

**Comment by natebosch** [comment]
@alorenzen, the next release of the SDK should have a (temporarily) working `pub global activate` and run. The release after that might start having problems due to https://github.com/dart-lang/sdk/issues/33577

**Comment by alorenzen** [comment]
Do we have an ETA for the next SDK release?

**Comment by thosakwe** [comment]
By any chance, would this be related to this error as well?

```
[SEVERE] Failed after 11.6s
NoSuchMethodError: Class '_SingleBuild' has no instance method 'runPostProcessBuilder'.
Receiver: Instance of '_SingleBuild'
Tried calling: runPostProcessBuilder(Instance of 'ModuleCleanup', Instance of 'AssetId', Instance of 'SingleStepReader', Instance of 'AssetWriterSpy', Instance of 'BuildForInputLogger', Instance of 'AssetGraph', Instance of 'PostProcessAnchorNode', 464)
```

Happens with `build_runner@^0.8.0`, `build_web_compilers@^0.4.0`, and Dart `2.0.0-dev.59.0`. It worked before, but of the blue stopped working. I'm not sure which dependency changed, but I'm assuming there's some sort of incompatibility that crept up.

**Comment by kevmoo** [comment]
@thosakwe – not really.

We have some version solving silly happening. To get around your issue, you need to set the constraint on `build_runner` to `^0.8.10` or better yet `0.9.0`

**Comment by natebosch** [comment]
We're using Dart 2 mode all the time in the sable SDK.
