### ISSUE TITLE
Delete pub package "threejs_facade_test"

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub#1935]
_From @patlillis on June 21, 2018 17:35_

https://pub.dartlang.org/packages/threejs_facade_test

This was a temporary project that I was using to test some things. I didn't realize that there wouldn't be a way for me to delete it from pub.dartlang.org. There are no users, it's less than a week old, and clearly has the word "_test" in the name, so this shouldn't cause any problems.

I just found out about "publish_to: none" (https://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package), but alas it's too late :(

Thanks a lot for the help, much appreciated.

_Copied from original issue: dart-lang/sdk#33562_

**Comment by natebosch** [comment]
@anders-sandholm - for future reference `dart-lang/pub` is the client

@kevmoo - is  `dart-lang/pub-dartlang-dart` the appropriate repo for deletion requests?

**Comment by kevmoo** [comment]
>  is dart-lang/pub-dartlang-dart the appropriate repo for deletion requests?

Yup!

**Comment by anders-sandholm** [comment]
my bad... moving (again)

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/pub-dartlang-dart#1407
