### ISSUE TITLE
Loading angular use a lot of memory 

### ISSUE THREAD

**Issue by ichengde** [dart-lang/pub#1936]
dart 1.24.3
ubuntu 16.04

step:
1. stagehand web-angular
2. pub get
...
![wx20180625-003812](https://user-images.githubusercontent.com/4899969/41821285-ccba8af8-7810-11e8-99b3-d8b2183e6219.png)

It seems that it takes a lot of memory to make it inoperable. any help? Or need more resource to do it?

**Comment by matanlurey** [comment]
I don't know if we have a specific goal or SLA for amount of memory or CPU to use during pub get. The good news is in the Dart 2 SDK I think lots of these precompile steps happen lazily.

Closing because Dart 1.x is no longer supported. Please try the latest 2.x and AngularDart 5 alpha and give us your feedback!

**Comment by ichengde** [comment]
I have updated the Dart 2 SDK and  AngularDart 5 alpha. Taking some time, It works.

![image](https://user-images.githubusercontent.com/4899969/41843134-48d9b3be-789f-11e8-8240-bee6d2fc3485.png)
![image](https://user-images.githubusercontent.com/4899969/41843707-ccc161f8-78a0-11e8-80f2-9b6238ca00e5.png)
Obviously it need number of memory.

**Comment by natebosch** [comment]
> The good news is in the Dart 2 SDK I think lots of these precompile steps happen lazily

These are not lazy, though we have discussed that possibility

**Comment by natebosch** [comment]
@ichengde - the screenshot in your last update is messages from `build_runner` which is independent of `pub`. If you are having problems running builds please file an issue at https://github.com/dart-lang/build/issues
