### ISSUE TITLE
'Packages get' has been run    Click Upgrade dependencies below is the log.

### ISSUE THREAD

**Issue by chenzhicheng163** [dart-lang/pub#1941]
**C:\Users\chenzhicheng\flutter\flutter\bin\flutter.bat --no-color packages get**
Running "flutter packages get" in flutter_app...
Bad state: Origin is only applicable schemes http and https: c:
package:pub/src/source/hosted.dart 344                                                         BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 144                                                         BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 168                                                                BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76                                                  PackageLister._versions.<fn>.<fn>
dart:async                                                                                     runZoned
package:pub/src/http.dart 275                                                                  withDependencyType
package:pub/src/solver/package_lister.dart 75                                                  PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                                                     new Future.sync
package:async/src/async_memoizer.dart 43                                                       AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74                                                  PackageLister._versions
package:pub/src/solver/package_lister.dart 111                                                 PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 355                                                 VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 309                                                                 minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 351                                                 VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 98                                                  VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35                                                                 resolveVersions.<fn>
package:pub/src/log.dart 378                                                                   progress
package:pub/src/solver.dart 32                                                                 resolveVersions
package:pub/src/entrypoint.dart 193                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38                                                            GetCommand.run
package:args/command_runner.dart 194                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                     new Future.sync
package:pub/src/utils.dart 115                                                                 captureErrors.<fn>
dart:async                                                                                     runZoned
package:pub/src/utils.dart 134                                                                 captureErrors
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1)
Process finished with exit code 1

### log is on below.

C:\Users\chenzhicheng>pub --trace --verbosity=warning get --no-precompile
Could not find a file named "pubspec.yaml" in "C:\Users\chenzhicheng".
---- Log transcript ----
FINE: Pub 1.24.3
IO  : Spawning "cmd /c ver" in C:\Users\chenzhicheng\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.17134.112]
    | Nothing output on stderr.
ERR : Could not find a file named "pubspec.yaml" in "C:\Users\chenzhicheng".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 419                    new Pubspec.load
    | package:pub/src/package.dart 138                    new Package.load
    | package:pub/src/entrypoint.dart 146                 new Entrypoint
    | package:pub/src/command.dart 42                     PubCommand.entrypoint
    | package:pub/src/command/get.dart 38                 GetCommand.run
    | package:args/command_runner.dart 194                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168             PubCommandRunner.runCommand.<fn>
    | dart:async                                          new Future.sync
    | package:pub/src/utils.dart 102                      captureErrors.<fn>
    | package:stack_trace                                 Chain.capture
    | package:pub/src/utils.dart 117                      captureErrors
    | package:pub/src/command_runner.dart 168             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117             PubCommandRunner.run
    | D:\src\sdk1\sdk\third_party\pkg\pub\bin\pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                          _Completer.completeError
    | package:args/command_runner.dart 195                CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                          new Future.microtask
    | package:args/command_runner.dart 142                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168             PubCommandRunner.runCommand.<fn>
    | dart:async                                          new Future.sync
    | package:pub/src/utils.dart 102                      captureErrors.<fn>
    | package:stack_trace                                 Chain.capture
    | package:pub/src/utils.dart 117                      captureErrors
    | package:pub/src/command_runner.dart 168             PubCommandRunner.runCommand
---- End log transcript ----

**Comment by natebosch** [comment]
This is likely because of a manually configured `PUB_HOSTED_URL` missing the scheme (`https://`). Please try updating your config to add that and reopen if it doesn't solve your issue.

We added a more explicit error message for this case in #1972 but it will take some time to roll through the SDK and in to flutter.
