### ISSUE TITLE
pub get fails - dart 2.0.0-dev.67.0

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/pub#1944]
from a previous issue about pub, I managed to get a sample project created using"

    > pub global run stagehand web-angular

Before I can run the app, I need to:

    > **pub get**

This gives me lots of instances of the following message:
 `
    Error: NoSuchMethodError: Class 'BuildStepImpl' has no instance method 'digest'.
    Receiver: Instance of 'BuildStepImpl'
    Tried calling: digest(Instance of 'AssetId')
    [BuilderTransformer: Instance of 'SassBuilder' on angular_components|primary]:
`

**Comment by jakemac53** [comment]
This sounds like it is trying to run transformers - but that shouldn't be possible in `2.0.0-dev.67.0`?

Are you sure you are running that version?

**Comment by biancashouse** [comment]
(on Ubuntu)

After uninstalled Dart v? (sudo apt remove dart) and installing Dart 2, pub
is not found !
Does this mean you have to install Dart 1 followed by Dart 2 ?

Cheers for the response Jacob.

Ian

**Comment by zoechi** [comment]
You might need to add `dart-sdk/bin` to your `PATH`

**Comment by biancashouse** [comment]
Doh, dart sdk was hiding in /usr/lib/dart.

Many thanks.

**Comment by biancashouse** [comment]
Found that the dart-sdk is installed in /usr/lib/dart.
I was looking under /usr/local !

So in my profile I do:

export DATK_SDK_HOME=/usr/lib/dart
export PATH=$PATH......:$DART_SDK_HOME/bin

Now pub works as documented. Phew.

**Comment by biancashouse** [comment]
Found that the dart-sdk is installed in /usr/lib/dart.
I was looking under /usr/local !

So in my profile I do:

export DATK_SDK_HOME=/usr/lib/dart
export PATH=$PATH......:$DART_SDK_HOME/bin

Now pub works as documented. Phew.
