### ISSUE TITLE
feature: Provide a way to define version constraints globally

### ISSUE THREAD

**Issue by munificent** [dart-lang/pub#1946]
_From @MikeMitterer on June 4, 2018 9:31_

I have ~25 Dart packages in my repo, some private some public.
Almost all of these packages are using "logging" as a dependency.
If the version for logging changes I have to touch every single project to update the version numer

This is more than annoying...

Gradle for example let me define global vars in `~/.gradel/init.gradle`. With these global vars (version numbers in this case) it's very easy to update version constraints for all my internal projects at once.

_Copied from original issue: dart-lang/sdk#33323_

**Comment by munificent** [comment]
_From @lrhn on June 4, 2018 11:33_

Can you explain why you have to update version numbers so often that this becomes a problem?

You should be able to stay at the old major version number and your packages will still work.
If the package was updated with a new major version number, then it has probably changed in a non-backwards compatible way, and automatically updating a lot of packages to use the new version seems dangerous. You will have to run the tests of each package to ensure that they still work, and then actually updating the version number is not as big an overhead.

I can see that `logger` is at version `0.11.something`, which is effectively 11 major beta-versions. That's a lot of versions, and most packages don't do major updates that often. (Also, it's a <1.0 version, so depending on the package is known to come with a risk of instability, as you are experiencing).

In any case, this sounds like a request for the [`pub` tool](https://github.com/dart-lang/pub). Would it suffice to have a way to automatically update-and-test a dependency, say `pub try-version logger:^0.12.0` which updates the version of logger in the .packages and run the tests, and if successful, updates the `pubspec.yaml` constraint? Then you can do that for each package in your repo, and if they are all successful, you are done.

**Comment by natebosch** [comment]
This is a similar request to https://github.com/dart-lang/pub/issues/1847

**Comment by MikeMitterer** [comment]
I have e.g. eight package, they all relate on logger 0.1
If I want to upgrade to logger 0.2 I have to update every single package to 0.2 
With Gradle I have my .versions in ~/.gradle. I change the version number in this file and every lib get automatically the new logger version. This is an easy way to avoid dependency hell in Java/Kotlin

**Comment by munificent** [comment]
> If I want to upgrade to logger 0.2

Do you want to upgrade your *constraint* on logger, or just upgrade your currently selected *version* of logger? The former currently requires you to edit the pubspec of each package. The latter should just require running `pub upgrade` on each package, provided the new version is still within your packages' existing constraints.

**Comment by sigurdm** [comment]
Consider using something like https://melos.invertase.dev/ or https://github.com/google/mono_repo.dart to manage your related repositories. That way you can issue a `dart pub upgrade logger` or `dart pub upgrade --major-versions logger` across all the repos.

If the repos are not organized that way, consider a script that can run `dart pub upgrade --major-versions logger` across all your repos.

To upgrade to a specific version you can use `dart pub add logger:^0.2` (only upgrades versions after dart 2.19).

Closing as I don't think we can do much more here. Please reopen if there are still cases not well supported.
