### ISSUE TITLE
Can't access pub.dartlang.org from CLI or browser

### ISSUE THREAD

**Issue by Zirogravity** [dart-lang/pub#1950]
Hello, Every attempt to access packages through the pub.dartlang.org is not working.

**Comment by natebosch** [comment]
For future reference the repo for the pub _site_ is https://github.com/dart-lang/pub-dartlang-dart. This is the repo for the pub _client_

It appears up and stable for me now, if you're still having trouble accessing it please file an issue at the linked repository.

**Comment by Zirogravity** [comment]
Thanks. its back up now.

**Comment by abasiama** [comment]
> Thanks. its back up now.

how do you get packages from github. step by step
