### ISSUE TITLE
"pub get" is deleting my source code.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub#1951]
When using `flutter packages get`, which just calls `pub get` under the covers, I see some dangerous behavior: If there happens to be a directory called `packages` in the same directory as the pubspec.yaml, the entire directory gets silently removed, even if the contents have nothing to do with pub's legacy `packages` directory.

Pub should no longer remove this directory, or should at least verify that it only contains what the legacy `packages` directory contained before doing so (e.g. check that there are only symlinks being removed).

See https://github.com/flutter/flutter/issues/19859 for a more detailed description, but basically, pub is nuking my source code.

**Comment by jakemac53** [comment]
At this point, it is probably reasonable to remove this "feature" altogether. We are well past the transition period from packages directory to .packages file, and with Dart 2 the vast majority of tools will work just fine if there is a packages directory present.

**Comment by natebosch** [comment]
I'll try to find the code doing the deleting and rip it out.

It'll take a bit more work but we'll also drop any notion of the packages directory from pub: https://github.com/dart-lang/pub/issues/1952
