### ISSUE TITLE
pub.flutter-io.cn/api/packages/cupertino_icons’

### ISSUE THREAD

**Issue by lichenglan** [dart-lang/pub#1969]
My project is always reporting errors‘ Bad state: Cannot use origin without a scheme: pub.flutter-io.cn/api/packages/cupertino_icons’，and I excuted flutter packages get,flutter upgrade,but  it still doesn't work.

**Comment by natebosch** [comment]
What pub command are you executing when you get this error? Can you add the full output?

**Comment by lichenglan** [comment]
I excuted pub command ,but they are not recognized.

**Comment by natebosch** [comment]
What command produced this error?

**Comment by lichenglan** [comment]
pub --trace --verbosity=warning upgrade --no-precompile

**Comment by natebosch** [comment]
Can you paste the full output of that command?

**Comment by lichenglan** [comment]
pub --trace --verbosity=warning upgrade --no-precompile
pub : 无法将“pub”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，
如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ pub --trace --verbosity=warning upgrade --no-precompile
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pub:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by natebosch** [comment]
This paste looks like an error from powershell - perhaps you should run `flutter packages upgrade --trace`

Which command specifically produced the error `Bad state: Cannot use origin without a scheme: pub.flutter-io.cn/api/packages/cupertino_icons`?

**Comment by lichenglan** [comment]
I unloaded it and reinstalled it. I tried it many times but it didn't work

**Comment by natebosch** [comment]
It's still not clear to me what command is the problematic one - what command did you run which produced the output `Bad state: Cannot use origin without a scheme: pub.flutter-io.cn/api/packages/cupertino_icons`

**Comment by lichenglan** [comment]
I created a new project to run properly and reported the error.D:\Polyhome\SoftWare\flutter\bin\flutter.bat --no-color packages upgrade
Running "flutter packages upgrade" in flutter_app...
Bad state: Cannot use origin without a scheme: pub.flutter-io.cn/api/packages/cupertino_icons

can't solve the problem by following the instructions

**Comment by lichenglan** [comment]
I'm using Android studio，and run flutter doctor add the full output：
PS C:\Users\24216> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by natebosch** [comment]
can you post the content of you `pubspec.yaml`?

**Comment by lichenglan** [comment]
name: sky_engine
version: 0.0.99
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Dart SDK extensions for dart:ui
homepage: http://flutter.io
# sky_engine requires sdk_ext support in the analyzer which was added in 1.11.x
environment:
  sdk: '>=1.11.0 <2.0.0'

**Comment by natebosch** [comment]
ah, looks like you are probably using `PUB_HOSTED_URL` and might have it set to `pub.flutter-io.cn` instead of `https://pub.flutter-io.cn`

Please update your environment variable to include a schemed.

**Comment by natebosch** [comment]
we've added a check with a more direct error message for this case - it will take some time but eventually it will get synced to flutter. Please let us know if adding a scheme to your environment variable doesn't solve this issue.

**Comment by lichenglan** [comment]
Thank you very much. I will try it
