### ISSUE TITLE
flutter packages get failed

### ISSUE THREAD

**Issue by Randyshu2018** [dart-lang/pub#1970]
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 344:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 144:7           BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _AsyncAwaitCompleter.completeError
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _asyncErrorWrapperHelper
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
package:pub/src/source.dart 168:12                 BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
dart:async                                         runZoned
package:pub/src/http.dart 275:10                   withDependencyType
package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/utils.dart                         minByAsync
package:pub/src/solver/version_solver.dart 351:25  VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/solver/version_solver.dart         VersionSolver.solve
package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
package:pub/src/log.dart 378:18                    progress
package:pub/src/solver.dart 32:10                  resolveVersions
package:pub/src/entrypoint.dart 210:24             Entrypoint.acquireDependencies
---- Log transcript ----
FINE: Pub 2.0.0
MSG : Resolving dependencies...
SLVR: fact: startup_namer is 0.0.0
SLVR: derived: startup_namer
SLVR: fact: startup_namer depends on cupertino_icons ^0.1.2
SLVR: fact: startup_namer depends on flutter any from sdk
SLVR: fact: startup_namer depends on english_words ^3.1.0
SLVR: fact: startup_namer depends on flutter_test any from sdk
SLVR:   selecting startup_namer
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: english_words ^3.1.0
SLVR:   derived: flutter any from sdk
SLVR:   derived: cupertino_icons ^0.1.2
IO  : Get versions from https://pub.dartlang.org/api/packages/english_words.
IO  : HTTP GET https://pub.dartlang.org/api/packages/english_words
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: BDF33E21-4544-4D3E-9186-5A6D349F269D
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.0.0
SLVR: Version solving took 0:00:00.182257 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.1s).
ERR : The setter 'readEventsEnabled=' was called on null.
    | Receiver: null
    | Tried calling: readEventsEnabled=false
FINE: Exception type: NoSuchMethodError
ERR : package:pub/src/source/hosted.dart 344:7           BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 144:7           BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncErrorWrapperHelper
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 168:12                 BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
    | dart:async                                         runZoned
    | package:pub/src/http.dart 275:10                   withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/utils.dart                         minByAsync
    | package:pub/src/solver/version_solver.dart 351:25  VersionSolver._choosePackageVersion
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 210:24             Entrypoint.acquireDependencies
---- End log transcript ----

**Comment by Randyshu2018** [comment]
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /opt/workspace/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices
    • Android SDK at /Users/shurenwei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L232m
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
It's probably better to file the issue in https://github.com/dart-lang/pub/issues/new.
The content of the `pubspec.yaml` file might be useful to diagnose the problem as well.

**Comment by natebosch** [comment]
How reliably can you reproduce this? It looks like a bug in the socket code within the SDK to me, if we can get a reliable repro I'll file an issue there.

**Comment by hamidpp** [comment]
google_maps_flutter: ^0.5.16
location: ^2.3.5
geolocator: '^5.0.0'

i can not get these packages

**Comment by jonasfj** [comment]
@hamidpp, is this the same log, the same errors, the same os, if not please file a separate issue.
