### ISSUE TITLE
Consider warning about unrecognized fields when parsing pubspecs

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1971]
The pubpsec parser has to be lenient to allow for any old pubspec to be properly parsed, but this provides negative value at development time because simple spelling mistakes cause sections to be skipped instead of giving errors or warnings.

This came up recently with the `sdk` constraints in gitter - a user was confused about where to put the constraint, partly because [this page](https://www.dartlang.org/dart-2#migrating-packages) is misleading (it omits the `environment` key).

Another common mistake is misspelling `dev_dependencies` or `dependency_overrides`, or using the singular version of those (I have seen googlers do this several times in person).

My initial though is to emit a warning message about unrecognized fields by default (but not fail). We could also hide it behind a separate command but that would have far less value as it wouldn't be very discoverable.

We could also add a --strict flag that causes it to actually fail on unrecognized fields.

Thoughts?

**Comment by natebosch** [comment]
> What should happen with additional fields supported by Flutter?

That's a good callout - we could ignore those as well but it does introduce a point of coupling that is sub-optimal...

**Comment by jakemac53** [comment]
I wonder if flutter would be willing to modify pub in their version of the sdk to support parsing those fields, then they would maintain/own the logic for it at least.

**Comment by natebosch** [comment]
looking again - I guess flutter already nests everything under `flutter` so we could ignore that entirely and skip the complexity of an extra configuration file...
