### ISSUE TITLE
pub get effecting the dev speed.

### ISSUE THREAD

**Issue by hzmnet** [dart-lang/pub#1973]
seem pub get will connect to any website and online package.

when the links are not stable. every change of the code will take 10min ~ serval hour.
hope it checks local first but not connect pub.dartlang.org every time.

**Comment by hzmnet** [comment]
Resolving dependencies...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.

**Comment by zoechi** [comment]
What do you mean by "when the links are not stable."?
Perhaps `pub get --offline` helps in some cases.
Do you have such a bad internet connection?

**Comment by hzmnet** [comment]
My internet is as well as could watch high-quality video on YOUTUBE.
I mean the `pub get ` is not stable。there have 99% will jamming and show below message.
I am tried several computers are same

```
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
```

**Comment by zoechi** [comment]
> Dart should be the same between WEB & PHONE

What do you mean by that?
There is no Dart installation for a phone.
You can build applications using Flutter and Dart and install the created app on a phone.
