### ISSUE TITLE
Running 'pub uploader' commands on unpublished package results in 500

### ISSUE THREAD

**Issue by cbracken** [dart-lang/pub#1974]
Running `pub uploader add foo@bar.com` in a package that is as-yet-unpublished currently results in a server-side error, triggering the following output from the client:

```
% pub uploader add foo@bar.com
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
[...... long pause ......]
HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/some_package/uploaders.
This is likely a transient error. Please try again later.
```

Expected behaviour:
Server checks if the package exists. If not, it returns an error to the client, which is then published immediately.

**Comment by sigurdm** [comment]
pub uploader is no longer supported
