### ISSUE TITLE
Feature request: Only give a warning of Version constraints

### ISSUE THREAD

**Issue by jianggaocheng** [dart-lang/pub#1977]
I am follow the 「dev」 channel to build my Flutter apps.
Today, when i open my IDE visual studio code，it upgrade my SDK version automatically. And when I rebuild my Flutter app, it throw an error 
```
Running "flutter packages get" in flutter_demos_gallery...
The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

Because throttle_debounce 0.1.2+1 requires SDK version <2.0.0 and no versions of throttle_debounce match >0.1.2+1 <0.2.0, throttle_debounce ^0.1.2+1 is forbidden.
So, because flutter_demos_gallery depends on throttle_debounce ^0.1.2+1, version solving failed.

pub get failed (1)
```

I know the error is because that the environment constraints in pubspec.yaml. But I think maybe we can use a better way not throw an error.

I can understand why the minimum version limit is set, maybe some package use the new sdks feature, so it can not support the low version.
But I can't understand that we set a strict maximum version limit. For example the package `throttle_debounce 0.1.2+1` I use. Was last upload in 2016, I think that nobody can imagine that how will the package support in the future version. When I upgrade the SDK version to 2.1.0, I can not use the package anymore.

And the same reason as #1959  I submitted. All the package are in the same global folder. I can modify the version constraints in the `pubspec.yaml` file of my PC to make it pass the version check. But it is not a good way. because all project share the same pub package. And I can't make the change to version control tool. Other people checkout my source will meet the same problem.

The way I can resolve the problem is copy the pub package into my project, I think it is really a bad way.

I think maybe we can only give a warning of the version constraints. Not a error.
Or give a way to make it can "ignore"  version constraints

**Comment by matanlurey** [comment]
You can use `dev_dependencies` to override:
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

**Comment by jianggaocheng** [comment]
@matanlurey, I think `dependency_overrides ` is a way but not the best way.
- I can use `dependency_overrides ` to make it use my local package instead of remote, but I need to push the  copy of package to source version control tool to make others can get this package and not get an error when building. 
- It will be a hard work that if there are many packages need to override. because all project'  dependency packages are in one folder.

I think maybe we need a way to 「override」 the version constraints, not override the dependency.

**Comment by zoechi** [comment]
The best way is to get the throttle_debounce package fixed. 
If the maintainer does not respond publish a fork that claims to be compatible with Dart ">=2.0.0 <3.0.0". Everything else are just ugly hacks that lead to ever deeper rabbit holes.
