### ISSUE TITLE
What is commit number are the 2.0.0

### ISSUE THREAD

**Issue by zhangjianlin77** [dart-lang/pub#1978]
I need to add some code into the pub on my native pub code

Because  I update my flutter version to 0.7.0,  but the dart sdk version in flutter is update to 2.0.0 too.
 I need to execute "dart --checked --snapshot=pub.dart.snapshot bin/pub.dart" on my native pub code.  and copy the snapshot file to cover "flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot" with my snapshot that I build out

**Comment by natebosch** [comment]
I'm not sure I understand what this request is.

Are you asking for which commit updated to work with Dart 2 semantics? I think 58fe996eab8d54f28f5109c407ff0ab62fbd835d is probably the minimum. The runtime semantics were fixed earlier but this is the minimum commit where snapshots would work correctly.

Are you asking for which commit was used in the SDK for the 2.0.0 SDK? That's also 58fe996eab8d54f28f5109c407ff0ab62fbd835d

I also can't follow the reasoning behind needing this - are you maintaining a fork of pub? What is the reason for needing to do that? If you do have a fork of pub I would try to stay on the latest commit from master that you can.

**Comment by natebosch** [comment]
Note that you don't need a special version of pub for a package to work with the Dart 2 SDK - that comes down to setting the environment constraints in the pubspec.

```yaml
environment:
  sdk: ">=2.0.0 <3.0.0"
```

**Comment by natebosch** [comment]
Closing since we haven't had a followup.

**Comment by zhangjianlin77** [comment]
ok.Thanks
