### ISSUE TITLE
flutter packages get （Error）

### ISSUE THREAD

**Issue by lebow01** [dart-lang/pub#1980]
![image](https://user-images.githubusercontent.com/23068980/45091987-a3e01980-b146-11e8-8e0b-c008a3595548.png)
![image](https://user-images.githubusercontent.com/23068980/45091852-4055ec00-b146-11e8-876a-6f67ae049c47.png)
![image](https://user-images.githubusercontent.com/23068980/45091761-02f15e80-b146-11e8-8df6-d3410f17db70.png)
![image](https://user-images.githubusercontent.com/23068980/45091775-0edd2080-b146-11e8-8a25-b15e00e80749.png)

Running "flutter packages get" in helloword...
Bad state: Origin is only applicable schemes http and https: d:
package:pub/src/source/hosted.dart 341:7                                                          BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 142:7                                                          BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                                                BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                                                  PackageLister._versions.<fn>.<fn>
dart:async                                                                                        runZoned
package:pub/src/http.dart 272:10                                                                  withDependencyType
package:pub/src/solver/package_lister.dart 75:33                                                  PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                                                        new Future.sync
package:async/src/async_memoizer.dart 43:42                                                       AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                                                  PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                                                 PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                                                 VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                                                 minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                                                 VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                                                  VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                                                 resolveVersions.<fn>
package:pub/src/log.dart 378:18                                                                   progress
package:pub/src/solver.dart 32:10                                                                 resolveVersions
package:pub/src/entrypoint.dart 200:24                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                                            GetCommand.run
package:args/command_runner.dart 194:27                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168:39                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                        new Future.sync
package:pub/src/utils.dart 109:12                                                                 captureErrors.<fn>
dart:async                                                                                        runZoned
package:pub/src/utils.dart 126:5                                                                  captureErrors
package:pub/src/command_runner.dart 168:13                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117:11                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run
    pub --trace --verbosity=warning get --no-precompile
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1)
Exited (1)

**Comment by lebow01** [comment]
I have solved the problem of restarting editor Vscode.

**Comment by natebosch** [comment]
I think you might be hitting something similar to https://github.com/dart-lang/pub/pull/1972

Are you setting `PUB_HOSTED_URL` in your environment? If so, it needs to start with `http://` or `https://`

**Comment by kevmoo** [comment]
Can we close this @natebosch ?

**Comment by natebosch** [comment]
Yeah I think we have something more concrete/actionable at #2046 that will solve this the rest of the way.
