### ISSUE TITLE
When doing packages pub publish --dry-run I am being warned that my package does not depend on its example

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/pub#1985]
Reference - https://stackoverflow.com/questions/52537386/why-is-my-flutter-package-suddenly-warning-me-that-it-doesnt-depend-on-its-exam

Package source code: https://github.com/GroovinChip/groovin_material_icons

The warnings are as follows:
```
Suggestions:
* line 4, column 1 of example\GroovinMaterialIconsExample\lib\main.dart: This package doesn't depend on groovin_material_icons_testapp.
  import 'package:groovin_material_icons_testapp/icon_map.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 5, column 1 of example\GroovinMaterialIconsExample\lib\main.dart: This package doesn't depend on groovin_material_icons_testapp.
  import 'package:groovin_material_icons_testapp/search.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 3, column 1 of example\GroovinMaterialIconsExample\lib\search.dart: This package doesn't depend on groovin_material_icons_testapp.
  import 'package:groovin_material_icons_testapp/icon_map.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jakemac53** [comment]
This is WAI right now, but we are considering changing that I think... cc @natebosch

**Comment by GroovinChip** [comment]
What does 'WAI' stand for?

**Comment by jakemac53** [comment]
Working as intended, the `example` directory by convention has special meaning (it gets surfaced on the pub site) and is not expected to be a package in itself.

**Comment by GroovinChip** [comment]
Alright. This warning has not surfaced for previous publishes - why would it be showing now? Should I ignore it and publish my latest version?

**Comment by jakemac53** [comment]
I am not sure on the details of when it was added, but it should be safe to publish and ignore the warning as far as I know.

**Comment by jonasfj** [comment]
See also https://github.com/dart-lang/pub/issues/1813
