### ISSUE TITLE
Unable to download packages from https://pub.dartlang.org

### ISSUE THREAD

**Issue by samueladekunle** [dart-lang/pub#1989]
I am trying to build an application using the Flutter SDK, but on running `flutter packages get` in the application's directory, what I get is
```
Running "flutter packages get" in startup_namer...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...
```
This was initially reported on Flutter's issues page [here](https://github.com/flutter/flutter/issues/22474), but I was directed to post the issue here.

I am not behind any proxy connection, and am located in Nigeria. A fellow Nigerian also complained about this on [stackoverflow](https://stackoverflow.com/questions/52158282/got-socket-error-trying-to-find-package-cupertino-icons-at-https-pub-dartlang).

`flutter doctor -v` prints
```
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.286], locale en-US)
    • Flutter version 0.8.2 at C:\Flutter\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\AUNTYHANNAH\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Users\AUNTYHANNAH\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\AUNTYHANNAH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.17.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

# Solution
Still experiencing this issue? Try to see if you can reach https://dartlang-pub-dev.appspot.com/ in your browser

If it is accessible, declare `PUB_HOSTED_URL` as a system environment variable and give it the value `https://dartlang-pub-dev.appspot.com/`

**Comment by HemlockBane** [comment]
Hello Samuel, has your issue been resolved? Mine isn't working either.

**Comment by a-oboh** [comment]
@samueladekunle I'm also in Nigeria and i faced this same issue. I then resolved to using a VPN, and it worked for me. I think we in Nigeria and some other parts of the world have this issue with some packages.

**Comment by natebosch** [comment]
Is the https://pub.dartlang.org/ site reachable in a browser?

cc @mit-mit

**Comment by samueladekunle** [comment]
@HemlockBane I had to switch in between a public Wi-Fi and a VPN service for some weeks, but rather strangely, after switching from Windows to Linux have not experienced the same issue on my home network.

**Comment by far11ven** [comment]
I'm facing the same issue, @natebosch https://pub.dartlang.org/  is reachable in my browser.
Could it be coz of Corporate laptop I'm using having restrictions? I'm in india btw

**Comment by leodavinci1** [comment]
Here in Brazil the website **https://pub.dartlang.org/** that flutter uses to get the packages with **flutter packages get** isn't reachable. I tried using TunnelBear VPN connecting to a USA network and it all worked fine.

**Comment by jonasfj** [comment]
@leodavinci1, could you check if this is ipv6 related (or DNS related, try using `8.8.8.8`)

**Comment by leodavinci1** [comment]
Tested with 8.8.8.8 DNS config and the website **https://pub.dartlang.org/** worked perfectly. When I removed that DNS config, website became unreachable again.

**Comment by chenxiaoyanemile** [comment]
Hi , i also got this problem in China , do you have a solve way for me ? thanks .

**Comment by jonasfj** [comment]
@chenxiaoyanemile, you can use the [Chinese community mirror](https://flutter.dev/community/china).

**Comment by chenxiaoyanemile** [comment]
@jonasfj  Hi , thank you for your answer . but i have try it , it doesn't work for me .

**Comment by chenxiaoyanemile** [comment]
fixed it in China  with this method.

 https://www.jianshu.com/p/c524d4ffe605.

**Comment by fioan89** [comment]
Got the same issue recently while trying to setup flutter. Turn's out I did not set-up the proxy correctly.
If you are also behind a proxy then please make sure you strictly follow the format from https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

If you are on Windows and you run the flutter/pub command from PowerShell, the usual recommendation `set https_proxy=proxy.yourproxy.com:8080` will not work.  The correct ways is:
`$env:https_proxy='proxy.yourproxy.com:8080`

**Comment by jonasfj** [comment]
@fioan89,
Uh, nice trick with PowerShell, please consider contributing to the documentation page you referenced :)

**Comment by fioan89** [comment]
@jonasfj got it. Thanks for the tip.

**Comment by lvcster** [comment]
Running '$env:https_proxy='proxy.yourproxy.com:8080' on Powershell gives and error =>_**The filename, directory name, or volume label syntax is incorrect.**_
Any help?

**Comment by lvcster** [comment]
> $

I also tried running without the $, like 'env:https_proxy='proxy.yourproxy.com:8080'. I am not sure if I am missing something.

**Comment by lvcster** [comment]
I found the problem and fixed it...
set https_proxy=proxy.yourproxy.com:8080 must be wrapped within single quotes like 
_set https_proxy=**'proxy.yourproxy.com:8080'**_. This is in Windows.

**Comment by fioan89** [comment]
:( weird, what version of PowerShell do you have?

**Comment by fioan89** [comment]
> Running '$env:https_proxy='proxy.yourproxy.com:8080' on Powershell gives and error =>_**The filename, directory name, or volume label syntax is incorrect.**_
> Any help?

Are you sure you are running this with PowerShell and not Command Prompt? :) I just ran the expression in `Command Prompt` and it returns the exact same error as you mentioned.

**Comment by tejismcool** [comment]
Had thesame issue from Nigeria. I think the issue maybe from my network provider. I fixed it following by declaring PUB_HOSTED_URL as a system environment variable and give it the value `https://pub.dev/`

don't know if it helps

**Comment by vishnuiiit** [comment]
please do not just copy blindly above solution given by @samueladekunle , you may need to create PUB_HOSTED_URI, but probably link that you need to enter is dependent on your location, for ex- for me it was https://pub.dev/ instead

**Comment by Tarhex** [comment]
Try to see if you can reach https://dartlang-pub-dev.appspot.com/ in your browser

If it is accessible, declare PUB_HOSTED_URL as a system environment variable and give it the value https://dartlang-pub-dev.appspot.com/

Then exit and reopen your cmd window and try again.

**Comment by jonasfj** [comment]
**Do not use** `https://dartlang-pub-dev.appspot.com/`.

This is a staging site used for development and stuff.. data is outdated and often incorrect.

**Comment by borysHozh77** [comment]
Hello, everyone, I am facing an issue like below when run flutter pub get.
"Running "flutter pub get" in flutter_application...                     
(This is taking an unexpectedly long time.) "
I want to fix this, could you explain how to fix this issue?

**Comment by apwia** [comment]
Hey everyone !

I was having this same problem executing the command in the VSCode terminal:

```bash
$ flutter pub get
Got socket error trying to find package sqflite at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Got socket error trying to find package sqflite at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Running "flutter pub get" in contacts_list...
```

And using the linux terminal I could execute the command with no problems:

```bash
$ flutter pub get
Running "flutter pub get" in contacts_list...                       6.4s
```

and I don't know why ¯\_(ツ)_/¯

**Comment by Arvinth-Krishna** [comment]
> Hey everyone !
> 
> I was having this same problem executing the command in the VSCode terminal:
> 
> ```shell
> $ flutter pub get
> Got socket error trying to find package sqflite at https://pub.dartlang.org.
> pub get failed (server unavailable) -- attempting retry 1 in 1 second...
> Got socket error trying to find package sqflite at https://pub.dartlang.org.
> pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
> Running "flutter pub get" in contacts_list...
> ```
> 
> And using the linux terminal I could execute the command with no problems:
> 
> ```shell
> $ flutter pub get
> Running "flutter pub get" in contacts_list...                       6.4s
> ```
> 
> and I don't know why ¯_(ツ)_/¯

is this problem solved?

**Comment by a-oboh** [comment]
Yeah it is

**Comment by NduO** [comment]
From Nigeria, I switched from AIRTEL network to MTN network and it connected to pub.dartlang.org and resolved

**Comment by pouyaSanjari** [comment]
hi
i can connect to pub.dev but can`t download any dependecy of it!
when i run pub upgrade it show upgrades but dont download!
any help?

**Comment by patrickubong** [comment]
This a straight forward solution, just get a VPN and use a US IP and you will be fine. Using Free version of ProtonVPN with free US IP worked for me. Flutter Doctor and Pub Get issues resolved instantly
