### ISSUE TITLE
Feature request: warn if version to be published is absent from changelog

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/pub#2003]
I have a devil of a time remembering to update my changelog prior to publishing a new version of a package, and I know the `publish` command is capable of kicking out warnings prior to publication if it finds anything that looks fishy. I'd love it if pub automatically scanned the changelog.md file in my package for the version number I'm trying to publish, and warned me if it wasn't present.

**Comment by jakemac53** [comment]
That seems pretty reasonable to me, fwiw @RedBrogdon this would be fairly easy to add yourself if you wanted to make a contribution :).

**Comment by jakemac53** [comment]
Ok sure, also not a requirement just mentioning that is an option (and probably a faster one than waiting for somebody else to come fix this)

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/pub/blob/master/lib/src/validator/name.dart for an example validator

**Comment by jakemac53** [comment]
cc @jonasfj @sigurdm how you do both feel about this? Willing to accept a contribution for it?

**Comment by sigurdm** [comment]
I believe we already have this: https://github.com/dart-lang/pub/blob/master/lib/src/validator/changelog.dart#L46

Please reopen if something else was meant.

**Comment by RedBrogdon** [comment]
I think this is my fault for leaving the bug open. I was still new to working with the Dart team back then and probably didn't feel confident claiming I'd actually fixed something. 😄

**Comment by jakemac53** [comment]
Huh, I just accidentally published a package yesterday which had no changelog at all which this check appears to allow https://github.com/dart-lang/pub/issues/2003#L22.

I would consider making that a warning as well as all packages should have a changelog.

**Comment by sigurdm** [comment]
I agree we should warn about that. Opened https://github.com/dart-lang/pub/issues/2337
