### ISSUE TITLE
pub get should upgrade dependencies that don't have an explicit version

### ISSUE THREAD

**Issue by Meai1** [dart-lang/pub#2005]
When I write:

```
dev_dependencies:
  json_serializable:
  build_runner:
  build_web_compilers:
```

I dont expect to be stable but when I write no version or any version into the field then I reasonably expect that dart will always give me the latest one, not the last one that I ever downloaded. 
I mean.. why would I want the last one? If I wanted to be safe, I'd specify the exact version. Now it works the opposite way, I get the old version even though I specifically allow any version.

What prompts this request by me? 
Well everytime I upgrade Dart SDK, I get weird build error and it takes me a while to remember that oh, maybe some kind of build dependency that I never touch has to be upgraded. Weird, when I already told my pubspec file that I dont care about which version it takes.

**Comment by jakemac53** [comment]
You have to use `pub upgrade` not `pub get`. `pub get` will always use the versions in your `pubspec.lock` file if one exists. This allows you to have a consistent version of dependencies across people if you check it in to your repo, which some people like to do.
