### ISSUE TITLE
Pub should limit pub's upgrade "available" messages based on a package's minimum required SDK version

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/pub#2007]
_From @Stargator on November 27, 2018 20:19_

* Dart SDK Version: 2.1.0
* MacOSX
----

It would be useful if when pub states what updates are available for packages that it checks if those new versions fit within the existing SDK constraints

-----

_Copied from original issue: dart-lang/sdk#35276_

**Comment by sigurdm** [comment]
I think the existence of a newer version can be relevant even if it requires you to update sdk.

**Comment by sigurdm** [comment]
I think we are where we want with this.

"Newer versions available" are relevant even if it requires an sdk update.

We have `dart pub outdated` That will show what versions of a package is compatible with your current constraints.
