### ISSUE TITLE
When I run pub publish I got an error "The setter 'readEventsEnabled=' was called on null."

### ISSUE THREAD

**Issue by rangaofei** [dart-lang/pub#2008]
冉高飞  09:09:11

Publishing saka_image 0.0.1 to https://pub.flutter-io.cn:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- lib
|   |-- saka_image.dart
|   '-- src
|       |-- compose_frame_image_stream.dart
|       |-- image_type.dart
|       |-- loading_state.dart
|       |-- log.dart
|       |-- main_image.dart
|       |-- network_image.dart
|       '-- raw_image.dart
'-- pubspec.yaml

Looks great! Are you ready to upload your package (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A58427&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
Authorization received, processing...
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:http/src/io_client.dart 33:23                    IOClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 68:39                          _PubHttpClient.send
===== asynchronous gap ===========================
package:http_retry/http_retry.dart 97:33                 RetryClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 194:43                         _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31           ThrottleClient.send
===== asynchronous gap ===========================
package:http/src/base_client.dart 169:38                 BaseClient._sendUnstreamed
===== asynchronous gap ===========================
package:http/src/base_client.dart 54:7                   BaseClient.post
package:oauth2/src/authorization_code_grant.dart 282:38  AuthorizationCodeGrant._handleAuthorizationCode
===== asynchronous gap ===========================
package:oauth2/src/authorization_code_grant.dart 231:18  AuthorizationCodeGrant.handleAuthorizationResponse
===== asynchronous gap ===========================
package:pub/src/oauth2.dart 197:17                       _authorize.<fn>.<fn>
package:shelf/shelf_io.dart 88:29                        handleRequest
===== asynchronous gap ===========================
package:shelf/shelf_io.dart 64:34                        serveRequests.<fn>.<fn>

I don't know why this happen!

**Comment by rangaofei** [comment]
I have solve this problem.Just because I am in China,and I use lantern,maybe this is the reason ,when  I change my propxy to ss,everything is Ok.so publish to pub cannot use lantern

**Comment by sigurdm** [comment]
@rangaofei if you are using lantern you should probably not be using a mirror like https://pub.flutter-io.cn:, but use pub.dartlang.org as is default.
