### ISSUE TITLE
Publish validation is slow

### ISSUE THREAD

**Issue by munificent** [dart-lang/pub#2012]
I notice that when I publish a package, the validation step takes about 10-15 seconds. That's long enough that the process looks hung without any output. If we can't speed this up, I think it's worth adding either a little progress bar, or perhaps printing out the name of each validation step as its performed. That way users know something is going on.

**Comment by jakemac53** [comment]
My assumption here is the script that is doing the validation is running from source - it got slow with Dart 2.

**Comment by munificent** [comment]
Is it not just part of the pub executable itself?

**Comment by natebosch** [comment]
I think it is part of the executable.

It is doing a lot of work though, the more Dart code in your package the slower it gets.

**Comment by jakemac53** [comment]
Did we add more checks recently or something? This was definitely not an issue before. I thought maybe it was invoking some binary from package:pana or something but that is just random speculation :joy:

**Comment by sigurdm** [comment]
@munificent did the validation time suddenly take more time or it has been like this always?

**Comment by munificent** [comment]
It's a recent thing. Validation used to be nearly instantaneous. Maybe it was this change: https://github.com/dart-lang/pub/commit/9f1e9521b335c2772ec2b48090d8b4fba211a1a1? That looks like it might be doing full analysis where before I think the validation was just syntactic.
