### ISSUE TITLE
Unhandled exception: SocketException: OS Error

### ISSUE THREAD

**Issue by scroollocker** [dart-lang/pub#2013]
Hello, I have a corporate proxy server configured. 

set http_proxy=ip: port 
set https_proxy=ip: port. 

When I launch the pub. I get error:
```
Unhandled exception:
SocketException: OS Error: .
, errno = 0, port = 0
#0      runProcess.<anonymous closure> (package:pub/src/io.dart:648:18)
<asynchronous suspension>
#1      new Future.sync (dart:async/future.dart:224:31)
#2      Pool.withResource.<anonymous closure> (package:pool/pool.dart:126:18)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl
.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:5
16:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart
:115:13)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patc
h.dart:172:5)
```
I don't have a proxy at home. Home works well.

**Comment by jonasfj** [comment]
Try `set https_proxy=<ip>:<port>` (it's not clear that you configured the env vars correctly), see:
https://www.dartlang.org/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

You can also try out:
https://api.dartlang.org/stable/2.2.0/dart-io/HttpClient/findProxyFromEnvironment.html

But generally, I would assume it something wrong with the proxy (maybe it's set to block some sites).
Try to make a minimal hello world using `HttpClient` from `dart:io` and an http proxy... Or prove that this doesn't work in a reproducible setup.
