### ISSUE TITLE
Running "flutter packages get" in Stuck

### ISSUE THREAD

**Issue by crajygemer** [dart-lang/pub#2015]
Last 2 days I'm trying to create flutter project but failed to receive the package from pub.dartlang.org
Also, I check Ping. it says request timeout. What should I do now? Looks like there is some network problem between my network and dart network. Please help me out.

H:\apps>flutter create app_b
Creating project app_b...
  app_b\.gitignore (created)
  app_b\.idea\libraries\Dart_SDK.xml (created)
  app_b\.idea\libraries\Flutter_for_Android.xml (created)
  app_b\.idea\libraries\KotlinJavaRuntime.xml (created)
  app_b\.idea\modules.xml (created)
  app_b\.idea\runConfigurations\main_dart.xml (created)
  app_b\.idea\workspace.xml (created)
  app_b\.metadata (created)
  app_b\android\app\build.gradle (created)
  app_b\android\app\src\main\java\com\example\appb\MainActivity.java (created)
  app_b\android\build.gradle (created)
  app_b\android\app_b_android.iml (created)
  app_b\android\app\src\main\AndroidManifest.xml (created)
  app_b\android\app\src\main\res\drawable\launch_background.xml (created)
  app_b\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  app_b\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  app_b\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  app_b\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  app_b\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  app_b\android\app\src\main\res\values\styles.xml (created)
  app_b\android\gradle\wrapper\gradle-wrapper.properties (created)
  app_b\android\gradle.properties (created)
  app_b\android\settings.gradle (created)
  app_b\ios\Runner\AppDelegate.h (created)
  app_b\ios\Runner\AppDelegate.m (created)
  app_b\ios\Runner\main.m (created)
  app_b\ios\Runner.xcodeproj\project.pbxproj (created)
  app_b\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  app_b\ios\Flutter\AppFrameworkInfo.plist (created)
  app_b\ios\Flutter\Debug.xcconfig (created)
  app_b\ios\Flutter\Release.xcconfig (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  app_b\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  app_b\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  app_b\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  app_b\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  app_b\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  app_b\ios\Runner\Base.lproj\Main.storyboard (created)
  app_b\ios\Runner\Info.plist (created)
  app_b\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  app_b\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  app_b\lib\main.dart (created)
  app_b\app_b.iml (created)
  app_b\pubspec.yaml (created)
  app_b\README.md (created)
  app_b\test\widget_test.dart (created)
Running "flutter packages get" in app_b...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...

**Comment by crajygemer** [comment]
You can see more details here https://github.com/flutter/flutter/issues/25433

**Comment by sigurdm** [comment]
This sounds rather mysterious.
Can you access https://pub.dartlang.org from a browser?

**Comment by crajygemer** [comment]
No I can't. But If I change the IP/Location I can access :(

**Comment by sigurdm** [comment]
Can you disclose what your country is?

**Comment by sigurdm** [comment]
And what other countries you are thinking about

**Comment by crajygemer** [comment]
I'm from **Bangladesh** 
 It was working totally fine. But last 2 days I can't get packages or ping pub.dartlang.org :(
I can see same problem Nigeria too

**Comment by crajygemer** [comment]
If you search you can found lots of same issue in github/stackoverflow but for now I can understand that, pub.dartlang block our country network :( Please help me out.

**Comment by crajygemer** [comment]
Screenshot http://prntscr.com/lvyzs2

**Comment by isoos** [comment]
We had similar report from other places, e.g.:
https://github.com/dart-lang/pub-dartlang-dart/issues/1767

If you can reach https://dartlang-pub.appspot.com/  but you can't reach https://www.dartlang.org/ it is likely that the issue is at your ISP (internet provider).

**Comment by crajygemer** [comment]
I can access both sites but can't access/reach https://pub.dartlang.org/

**Comment by isoos** [comment]
Sorry, I meant to write https://news.dartlang.org/ can you access that?

**Comment by crajygemer** [comment]
NO I can't

**Comment by zoechi** [comment]
@isoos perhaps you can make sense about the comments about VPN in https://github.com/flutter/flutter/issues/25433

**Comment by crajygemer** [comment]
Should I contact my ISP? Do they fix that network issue? Cause hard to working with VPN.

**Comment by isoos** [comment]
I have insufficient knowledge about what is happening here, but seems to be that traffic routing at the IPS level may be misconfigured, and VPN helps in that because you end up using a different ISP at the end of the VPN connection.

@crajygemer connecting to the ISP is important, but I doubt that they will act fast. VPN or switching ISPs could work. (My Hungarian ISP's mobile service does not route international SMS messages for years, despite reported it many times)

**Comment by crajygemer** [comment]
Thanks for your comment @isoos but could you please tell me what should be my next step :(

**Comment by isoos** [comment]
1. Contact ISP, get to technical person, otherwise will be ignored.
2. Evaluate alternative ISPs, or use VPN.

**Comment by crajygemer** [comment]
Thank you But VPN must be the bad choice for work. Cause it makes internet slow. So I'll contact ISP and get back to here again. Thanks for your time @isoos

**Comment by jonasfj** [comment]
@crajygemer, could you try:
```
curl -v https://pub.dartlang.org -4
curl -v https://pub.dartlang.org --resolve 'pub.dartlang.org:443:172.217.14.211'
```

@sortie suggested that here: https://github.com/dart-lang/pub-dartlang-dart/issues/1767#issuecomment-437531730 if that works, then it might be that there is something wrong with your IPv6 setup (or your ISPs IPv6 setup).

**Comment by crajygemer** [comment]
Finally, I update DNS based on this instructions. Now I can get packages from pub.dartlang.org. Also, I can visit the site also, But still can't visit news.dartlang.org but won necessarily. Source URL is given below.
https://www.wiknix.com/how-to-fix-err_connection_timed_out-error/

Thanks to all :)

**Comment by RayOkaah** [comment]
Contributing to the above, from Nigeria and I can confirm that indeed an ISP is blocked from accessing Pub and the user will need a vpn to access this.

Some other ISPs work fine.

**Comment by SweetSourPeter** [comment]
Same issue here from China. I have tried all kinds of VPNs.
