### ISSUE TITLE
Invalid lint for part files

### ISSUE THREAD

**Issue by grouma** [dart-lang/pub#2024]
I am trying to publish built value generated code and I'm getting the following suggestion:

* The name of "lib/data/log_to_paths_request.g.dart", "log_to_paths_request.g", may only contain letters, numbers, and underscores.

This seems like an invalid lint since periods should be allowed in file names. I would imagine Angular code has similar issues as Angular applications often contain "file.template.dart".

**Comment by lukepighetti** [comment]
I am running into this as well. Did you find a workaround?

**Comment by natebosch** [comment]
This check was added here:
https://codereview.chromium.org/11444018

The original wording was "must be a valid Dart identifier" and now it it says "Using a valid Dart identifier makes the name usable in Dart code." - however I don't know when you'd use a file name as a variable name etc...

I think that this check has most likely outlived it's usefulness.

**Comment by jonasfj** [comment]
> I am running into this as well. Did you find a workaround? Is this a regression?

You can ignore the suggestion, or if you really need to work around it move your code into `lib/src/` and export it from a `lib/my_library.dart` using `export 'src/my_library.ugly.name.dart';`.

**Comment by jonasfj** [comment]
It's also possible we should update the suggestion to suggest that generated files are moved to `lib/src/`, see: https://github.com/dart-lang/pub/issues/1900
