### ISSUE TITLE
Bad state: Cannot use origin without a scheme: pub.flutter-io.cn/api/packages/cupertino_icons

### ISSUE THREAD

**Issue by b5702906** [dart-lang/pub#2025]
looks like #1969 ， i set Correct environment and it l doesn't  work. PUB_HOSTED_URL https://pub.flutter-io.cn FLUTTER_STORAGE_BASE_URL ： https://storage.flutter-io.cn. I also use Android studio

**Comment by b5702906** [comment]
Restart the computer to take effect

**Comment by Frank-Xin** [comment]
Restarting works
