### ISSUE TITLE
"Packages get" hangs with package from a SSH based private git repository

### ISSUE THREAD

**Issue by raveesh-me** [dart-lang/pub#2026]
## Steps to Reproduce
* Upload a dart package to a private github/gitlab repo
* Set up SSH based authentication
* Add the dependency as:
```
  my_package:
    git: git@gitlab.com:company/my_package.git
```
### When run in terminal as `flutter packages get`, 
It runs fine. When accessing hosted repository, it will ask for passphrase for the private SSH key

### When run using the Packages get button on top left of editor
![screenshot from 2019-01-09 15-19-05](https://user-images.githubusercontent.com/15698263/50891278-ef227580-1421-11e9-8c6b-190c53a564d9.png)

```
/home/raveesh/MyCode/sdk/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in guru_app...      
```
comes up in the messages tab, and the plugin has no way to ask for a SSH password if prompted.
This is where the flutter command hangs and all flutter commands fails because `packages get` does not release the lock

### Current Solution
run:
```
sudo killall dart
```
and then run flutter packages get manually in terminal.

## Version info

```
/home/raveesh/MyCode/sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_IN)
    • Flutter version 1.0.0 at /home/raveesh/MyCode/sdk/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/raveesh/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/raveesh/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/raveesh/Android/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Moto G 5 Plus • 192.168.1.4:5555 • android-arm • Android 8.1.0 (API 27)

• No issues found!
Process finished with exit code 0
```

**Comment by eseidelGoogle** [comment]
Can `sss_agent` be used as a workaround?

**Comment by jonasfj** [comment]
@raveesh-me, how is your environment configured, if you do: `git clone git@gitlab.com:company/my_package.git` does it ask for password or interaction of any kind, or does it just clone?

I agree, we should pass `SSH_AGENT` through if we're not already doing that..

**Comment by jonasfj** [comment]
Based on:

https://github.com/dart-lang/pub/blob/bb2b8b28fb95f824aa62b2d8019fc62d213deb59/lib/src/io.dart#L642-L644

We do inherit the environment from the parent.. Notice how `includeParentEnvironment` defaults to `true` in [`Process.run`](https://api.dartlang.org/stable/2.2.0/dart-io/Process/run.html).

**Comment by raveesh-me** [comment]
@jonasfj In this case:
My local SSH key, in this case, uses a password every time it is used. Git would use the SSH key because it is configured to use it by default.

But to use the SSH_KEY it will need a password(which I set when I was creating the said key). Currently(haven't tested this on the recent updates) Android Studio has no way to ask us for that local key, instead, it would just hang.

**On the other hand....**
Things are perfectly fine when we do not specify a password when we generate the key. Which is how I use it right now. I made a key without an auth password and added its signature to the said repo. And hence Android Studio is handling this case just fine. (given that we are using the system's SSH client and not Android Studio's inbuilt SSH client, which is yet another step in the setup process.)

**Comment by jonasfj** [comment]
It seems to me that we are forwarding the systems ssh-agent (well, all environment variables really).
Probably the editor plugin needs to ensure that:
 * `pub` is not invoked in an interactive shell that users can't interact with.
 * `DISPLAY` and `SSH_ASKPASS` is set if calling in an non-interactive shell.

See: https://man.openbsd.org/ssh#SSH_ASKPASS

----

@raveesh-me, sorry, but juggling you back and forth, but I suspect it's worth re-opening https://github.com/flutter/flutter-intellij/issues/3055 and fixing the issue there :)

Or it's worth deciding that this issue can't be fixed.. You can probably also set `SSH_ASKPASS` in your `~/.profile` or `~/.bashrc`.
