### ISSUE TITLE
Request to delete  package from pub

### ISSUE THREAD

**Issue by dopefaceee** [dart-lang/pub#2027]
Hi I have a package uploaded to pub named 'atomic_app_customer_musteat_id'. Can you remove that packages ?  It's uploaded by mistake and shouldn't be provided for public. It contains our client project and we had migrated to our private git repo. But have no clue how to remove it. Thank you.

**Comment by zoechi** [comment]
To prevent that in the future you can use https://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package/25131121#25131121

**Comment by kevmoo** [comment]
I've emailed the uploader to confirm the delete request

**Comment by dopefaceee** [comment]
Okay thanks, confirmed.

**Comment by kevmoo** [comment]
Removed!
