### ISSUE TITLE
Support global activate from a different pub server

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/pub#2039]
`pub global activate` already supports hosted, path, and git sources, but the `hosted` option defaults to the main pub server with no way to activate from a separate server. We have a private pub server for our internal packages and it would be nice to be able to globally activate some of them using the standard version constraints.

It looks like this idea was at least considered previously in this issue: https://github.com/dart-lang/pub/issues/1044

> pub global activate foo ">=1.0 <2.0" --server http://...

Is there any reason not to support this? And if not, would it be something that you would accept a PR for? Looking at the implementation of the global activate command, it looks like it might require a separate cache for each pub server, but otherwise seems to be straightforward.

**Comment by evanweible-wf** [comment]
I've put up a proposed solution here: https://github.com/dart-lang/pub/pull/2041

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/pub/commit/980fc947db32bca6ae7d07fbb4ad0fcdba0050ec

Tracking issue to include this in an SDK - https://github.com/dart-lang/sdk/issues/36026
