### ISSUE TITLE
flutter_dialogflow dependencies error: Could not un-tar (exit code 2). Error:

### ISSUE THREAD

**Issue by henryejemuta** [dart-lang/pub#2043]
7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Enrico-Systems\AppData\Local\Temp\pub_738669a6-2891-11e9-b44e-e02a8294ef52\data.tar

Extracting  doc\api\__404error.html
Extracting  doc\api\categories.json
Extracting  doc\api\flutter_dialogflow\AIResponse-class.html
Extracting  doc\api\flutter_dialogflow\AIResponse\AIResponse.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getId.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getLang.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getMessageResponse.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getResult.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getSpeechResponse.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getStatus.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getTimestamp.html
Extracting  doc\api\flutter_dialogflow\AIResponse\getsessionId.html
Extracting  doc\api\flutter_dialogflow\AIResponse\hashCode.html
Extracting  doc\api\flutter_dialogflow\AIResponse\id.html
Extracting  doc\api\flutter_dialogflow\AIResponse\lang.html
Extracting  doc\api\flutter_dialogflow\AIResponse\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\AIResponse\operator_equals.html
Extracting  doc\api\flutter_dialogflow\AIResponse\result.html
Extracting  doc\api\flutter_dialogflow\AIResponse\runtimeType.html
Extracting  doc\api\flutter_dialogflow\AIResponse\sessionId.html
Extracting  doc\api\flutter_dialogflow\AIResponse\status.html
Extracting  doc\api\flutter_dialogflow\AIResponse\timestamp.html
Extracting  doc\api\flutter_dialogflow\AIResponse\toString.html
Extracting  doc\api\flutter_dialogflow\Dialogflow-class.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\Dialogflow.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\hashCode.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\language.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\operator_equals.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\runtimeType.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\sendQuery.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\sessionId.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\timezone.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\toString.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\token.html
Extracting  doc\api\flutter_dialogflow\Dialogflow\version.html
Extracting  doc\api\flutter_dialogflow\Fulfillment-class.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\Fulfillment.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\getMessageResponse.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\getMessages.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\getSApeech.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\getSpeechResponse.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\hashCode.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\messages.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\operator_equals.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\runtimeType.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\speech.html
Extracting  doc\api\flutter_dialogflow\Fulfillment\toString.html
Extracting  doc\api\flutter_dialogflow\Metadata-class.html
Extracting  doc\api\flutter_dialogflow\Metadata\Metadata.html
Extracting  doc\api\flutter_dialogflow\Metadata\getIntentId.html
Extracting  doc\api\flutter_dialogflow\Metadata\getIntentName.html
Extracting  doc\api\flutter_dialogflow\Metadata\getWebhookForSlotFillingUsed.html
Extracting  doc\api\flutter_dialogflow\Metadata\getWebhookUsed.html
Extracting  doc\api\flutter_dialogflow\Metadata\hashCode.html
Extracting  doc\api\flutter_dialogflow\Metadata\intentId.html
Extracting  doc\api\flutter_dialogflow\Metadata\intentName.html
Extracting  doc\api\flutter_dialogflow\Metadata\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\Metadata\operator_equals.html
Extracting  doc\api\flutter_dialogflow\Metadata\runtimeType.html
Extracting  doc\api\flutter_dialogflow\Metadata\toString.html
Extracting  doc\api\flutter_dialogflow\Metadata\webhookForSlotFillingUsed.html
Extracting  doc\api\flutter_dialogflow\Metadata\webhookUsed.html
Extracting  doc\api\flutter_dialogflow\Result-class.html
Extracting  doc\api\flutter_dialogflow\Result\Result.html
Extracting  doc\api\flutter_dialogflow\Result\action.html
Extracting  doc\api\flutter_dialogflow\Result\actionIncomplete.html
Extracting  doc\api\flutter_dialogflow\Result\contexts.html
Extracting  doc\api\flutter_dialogflow\Result\fulfillment.html
Extracting  doc\api\flutter_dialogflow\Result\getAction.html
Extracting  doc\api\flutter_dialogflow\Result\getActionIncomplete.html
Extracting  doc\api\flutter_dialogflow\Result\getContexts.html
Extracting  doc\api\flutter_dialogflow\Result\getFulfillment.html
Extracting  doc\api\flutter_dialogflow\Result\getMetadata.html
Extracting  doc\api\flutter_dialogflow\Result\getParameters.html
Extracting  doc\api\flutter_dialogflow\Result\getResolvedQuery.html
Extracting  doc\api\flutter_dialogflow\Result\getScore.html
Extracting  doc\api\flutter_dialogflow\Result\getSource.html
Extracting  doc\api\flutter_dialogflow\Result\hashCode.html
Extracting  doc\api\flutter_dialogflow\Result\metadata.html
Extracting  doc\api\flutter_dialogflow\Result\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\Result\operator_equals.html
Extracting  doc\api\flutter_dialogflow\Result\parameters.html
Extracting  doc\api\flutter_dialogflow\Result\resolvedQuery.html
Extracting  doc\api\flutter_dialogflow\Result\runtimeType.html
Extracting  doc\api\flutter_dialogflow\Result\score.html
Extracting  doc\api\flutter_dialogflow\Result\source.html
Extracting  doc\api\flutter_dialogflow\Result\toString.html
Extracting  doc\api\flutter_dialogflow\Status-class.html
Extracting  doc\api\flutter_dialogflow\Status\Status.html
Extracting  doc\api\flutter_dialogflow\Status\code.html
Extracting  doc\api\flutter_dialogflow\Status\errorDetails.html
Extracting  doc\api\flutter_dialogflow\Status\errorType.html
Extracting  doc\api\flutter_dialogflow\Status\getCode.html
Extracting  doc\api\flutter_dialogflow\Status\getErrorDetails.html
Extracting  doc\api\flutter_dialogflow\Status\getErrorType.html
Extracting  doc\api\flutter_dialogflow\Status\hashCode.html
Extracting  doc\api\flutter_dialogflow\Status\noSuchMethod.html
Extracting  doc\api\flutter_dialogflow\Status\operator_equals.html
Extracting  doc\api\flutter_dialogflow\Status\runtimeType.html
Extracting  doc\api\flutter_dialogflow\Status\toString.html
Extracting  doc\api\flutter_dialogflow\flutter_dialogflow-library.html
Extracting  doc\api\index.html
Extracting  doc\api\index.json
Extracting  doc\api\static-assets\URI.js
Extracting  doc\api\static-assets\css\bootstrap.css
Extracting  doc\api\static-assets\css\bootstrap.css.map
Extracting  doc\api\static-assets\css\bootstrap.min.css
Extracting  doc\api\static-assets\favicon.png
Extracting  doc\api\static-assets\github.css
Extracting  doc\api\static-assets\highlight.pack.js
Extracting  doc\api\static-assets\play_button.svg
Extracting  doc\api\static-assets\readme.md
Extracting  doc\api\static-assets\script.js
Extracting  doc\api\static-assets\sdk_footer_text.html
Extracting  doc\api\static-assets\styles.css
Extracting  doc\api\static-assets\typeahead.bundle.min.js
Extracting  doc\api\utils_Language\Language-class.html
Extracting  doc\api\utils_Language\Language\CHINESE_CANTONESE.html
Extracting  doc\api\utils_Language\Language\CHINESE_SIMPLIFIED.html
Extracting  doc\api\utils_Language\Language\CHINESE_TRADITIONAL.html
Extracting  doc\api\utils_Language\Language\DANISH.html
Extracting  doc\api\utils_Language\Language\DUTCH.html
Extracting  doc\api\utils_Language\Language\ENGLISH.html
Extracting  doc\api\utils_Language\Language\ENGLISH_AUSTRALIAN_LOCALE.html
Extracting  doc\api\utils_Language\Language\ENGLISH_CANADIAN_LOCALE.html
Extracting  doc\api\utils_Language\Language\ENGLISH_GREAT_BRITANI_LOCALE.html
Extracting  doc\api\utils_Language\Language\ENGLISH_INDIAN_LOCALE.html
Extracting  doc\api\utils_Language\Language\ENGLISH_US_LOCALE.html
Extracting  doc\api\utils_Language\Language\FRENCH.html
Extracting  doc\api\utils_Language\Language\FRENCH_CANADIAN_LOCALE.html
Extracting  doc\api\utils_Language\Language\FRENCH_FRANCE_LOCALE.html
Extracting  doc\api\utils_Language\Language\GERMAN.html
Extracting  doc\api\utils_Language\Language\HINDI.html
Extracting  doc\api\utils_Language\Language\INDONESIAN.html
Extracting  doc\api\utils_Language\Language\ITALIAN.html
Extracting  doc\api\utils_Language\Language\JAPANESE.html
Extracting  doc\api\utils_Language\Language\KOREAN.html
Extracting  doc\api\utils_Language\Language\Language.html
Extracting  doc\api\utils_Language\Language\NORWEGIAN.html
Extracting  doc\api\utils_Language\Language\PORTUGUESE.html
Extracting  doc\api\utils_Language\Language\PORTUGUESE_BRAZILIAN.html
Extracting  doc\api\utils_Language\Language\RUSSIAN.html
Extracting  doc\api\utils_Language\Language\SPANISH.html
Extracting  doc\api\utils_Language\Language\SPANISH_LATIN_AMERICA.html
Extracting  doc\api\utils_Language\Language\SPANISH_SPAIN.html
Extracting  doc\api\utils_Language\Language\SWEDISH.html
Extracting  doc\api\utils_Language\Language\THAI.html
Extracting  doc\api\utils_Language\Language\UKRANIAN.html
Extracting  doc\api\utils_Language\Language\hashCode.html
Extracting  doc\api\utils_Language\Language\noSuchMethod.html
Extracting  doc\api\utils_Language\Language\operator_equals.html
Extracting  doc\api\utils_Language\Language\runtimeType.html
Extracting  doc\api\utils_Language\Language\toString.html
Extracting  doc\api\utils_Language\utils_Language-library.html
Extracting  doc\api\v2_auth_google\AuthGoogle-class.html
Extracting  doc\api\v2_auth_google\AuthGoogle\AuthGoogle.html
Extracting  doc\api\v2_auth_google\AuthGoogle\build.html
Extracting  doc\api\v2_auth_google\AuthGoogle\fileJson.html
Extracting  doc\api\v2_auth_google\AuthGoogle\getProjectId.html
Extracting  doc\api\v2_auth_google\AuthGoogle\getReadJson.html
Extracting  doc\api\v2_auth_google\AuthGoogle\getSessionId.html
Extracting  doc\api\v2_auth_google\AuthGoogle\getToken.html
Extracting  doc\api\v2_auth_google\AuthGoogle\hasExpired.html
Extracting  doc\api\v2_auth_google\AuthGoogle\hashCode.html
Extracting  doc\api\v2_auth_google\AuthGoogle\noSuchMethod.html
Extracting  doc\api\v2_auth_google\AuthGoogle\operator_equals.html
Extracting  doc\api\v2_auth_google\AuthGoogle\post.html
Extracting  doc\api\v2_auth_google\AuthGoogle\runtimeType.html
Extracting  doc\api\v2_auth_google\AuthGoogle\scope.html
Extracting  doc\api\v2_auth_google\AuthGoogle\sessionId.html
Extracting  doc\api\v2_auth_google\AuthGoogle\toString.html
Extracting  doc\api\v2_auth_google\v2_auth_google-library.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse-class.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\AIResponse.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\diagnosticInfo.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\getListMessage.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\getMessage.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\intentDetectionConfidence.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\languageCode.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\queryResult.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\responseId.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\toString.html
Extracting  doc\api\v2_dialogflow_v2\AIResponse\webhookStatus.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo-class.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\DiagnosticInfo.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\toString.html
Extracting  doc\api\v2_dialogflow_v2\DiagnosticInfo\webhookLatencyMs.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow-class.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\Dialogflow.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\authGoogle.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\detectIntent.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\language.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\Dialogflow\toString.html
Extracting  doc\api\v2_dialogflow_v2\Intent-class.html
Extracting  doc\api\v2_dialogflow_v2\Intent\Intent.html
Extracting  doc\api\v2_dialogflow_v2\Intent\displayName.html
Extracting  doc\api\v2_dialogflow_v2\Intent\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\Intent\name.html
Extracting  doc\api\v2_dialogflow_v2\Intent\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\Intent\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\Intent\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\Intent\toString.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult-class.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\QueryResult.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\action.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\allRequiredParamsPresent.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\fulfillmentMessages.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\fulfillmentText.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\intent.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\parameters.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\queryText.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\QueryResult\toString.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus-class.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\WebhookStatus.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\hashCode.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\message.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\noSuchMethod.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\operator_equals.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\runtimeType.html
Extracting  doc\api\v2_dialogflow_v2\WebhookStatus\toString.html
Extracting  doc\api\v2_dialogflow_v2\v2_dialogflow_v2-library.html
Extracting  doc\api\v2_message\BasicCardDialogflow-class.html
Extracting  doc\api\v2_message\BasicCardDialogflow\BasicCardDialogflow.html
Extracting  doc\api\v2_message\BasicCardDialogflow\buttons.html
Extracting  doc\api\v2_message\BasicCardDialogflow\formattedText.html
Extracting  doc\api\v2_message\BasicCardDialogflow\hashCode.html
Extracting  doc\api\v2_message\BasicCardDialogflow\image.html
Extracting  doc\api\v2_message\BasicCardDialogflow\noSuchMethod.html
Extracting  doc\api\v2_message\BasicCardDialogflow\operator_equals.html
Extracting  doc\api\v2_message\BasicCardDialogflow\runtimeType.html
Extracting  doc\api\v2_message\BasicCardDialogflow\subtitle.html
Extracting  doc\api\v2_message\BasicCardDialogflow\title.html
Extracting  doc\api\v2_message\BasicCardDialogflow\toString.html
Extracting  doc\api\v2_message\ButtonDialogflow-class.html
Extracting  doc\api\v2_message\ButtonDialogflow\ButtonDialogflow.html
Extracting  doc\api\v2_message\ButtonDialogflow\hashCode.html
Extracting  doc\api\v2_message\ButtonDialogflow\noSuchMethod.html
Extracting  doc\api\v2_message\ButtonDialogflow\operator_equals.html
Extracting  doc\api\v2_message\ButtonDialogflow\postback.html
Extracting  doc\api\v2_message\ButtonDialogflow\runtimeType.html
Extracting  doc\api\v2_message\ButtonDialogflow\text.html
Extracting  doc\api\v2_message\ButtonDialogflow\toString.html
Extracting  doc\api\v2_message\CardDialogflow-class.html
Extracting  doc\api\v2_message\CardDialogflow\CardDialogflow.html
Extracting  doc\api\v2_message\CardDialogflow\buttons.html
Extracting  doc\api\v2_message\CardDialogflow\hashCode.html
Extracting  doc\api\v2_message\CardDialogflow\imageUri.html
Extracting  doc\api\v2_message\CardDialogflow\noSuchMethod.html
Extracting  doc\api\v2_message\CardDialogflow\operator_equals.html
Extracting  doc\api\v2_message\CardDialogflow\runtimeType.html
Extracting  doc\api\v2_message\CardDialogflow\subtitle.html
Extracting  doc\api\v2_message\CardDialogflow\title.html
Extracting  doc\api\v2_message\CardDialogflow\toString.html
Extracting  doc\api\v2_message\ImageDialogflow-class.html
Extracting  doc\api\v2_message\ImageDialogflow\ImageDialogflow.html
Extracting  doc\api\v2_message\ImageDialogflow\accessibilityText.html
Extracting  doc\api\v2_message\ImageDialogflow\hashCode.html
Extracting  doc\api\v2_message\ImageDialogflow\imageUri.html
Extracting  doc\api\v2_message\ImageDialogflow\noSuchMethod.html
Extracting  doc\api\v2_message\ImageDialogflow\operator_equals.html
Extracting  doc\api\v2_message\ImageDialogflow\runtimeType.html
Extracting  doc\api\v2_message\ImageDialogflow\toString.html
Extracting  doc\api\v2_message\ListTextDialogflow-class.html
Extracting  doc\api\v2_message\ListTextDialogflow\ListTextDialogflow.html
Extracting  doc\api\v2_message\ListTextDialogflow\hashCode.html
Extracting  doc\api\v2_message\ListTextDialogflow\listText.html
Extracting  doc\api\v2_message\ListTextDialogflow\noSuchMethod.html
Extracting  doc\api\v2_message\ListTextDialogflow\operator_equals.html
Extracting  doc\api\v2_message\ListTextDialogflow\runtimeType.html
Extracting  doc\api\v2_message\ListTextDialogflow\toString.html
Extracting  doc\api\v2_message\QuickReplies-class.html
Extracting  doc\api\v2_message\QuickReplies\QuickReplies.html
Extracting  doc\api\v2_message\QuickReplies\hashCode.html
Extracting  doc\api\v2_message\QuickReplies\noSuchMethod.html
Extracting  doc\api\v2_message\QuickReplies\operator_equals.html
file doc\api\v2_message\QuickReplies\quickReplies.html
already exists. Overwrite with 
doc\api\v2_message\QuickReplies\quickReplies.html?
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
ERROR: Can't allocate required memory!

package:pub/src/io.dart 944:7               _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 821:20              withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 915:10              _extractTarGzWindows
package:pub/src/io.dart 843:18              extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 367:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning upgrade --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub upgrade failed (1)
Process finished with exit code 1

**Comment by jonasfj** [comment]
Please include a minimal `pubspec.yaml` that produces this...

Also maybe give `pub cache repair` a chance, I suspect you cache could be broken.

**Comment by henryejemuta** [comment]
> pub cache repair

Below is the content of my pubspec.yaml without comments

```
name: the_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_dialogflow: ^0.1.0
  flutter:
    sdk: flutter

	
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - img/placeholder.png
    - img/logo.png
    - assets/flutter-projects-0001-fab4bd2cc007.json

```

**Comment by jonasfj** [comment]
@henryejemuta 
Did you try to run `pub cache repair`?
This sounds to me like a corrupted download, maybe deleting the `.pub-cache` folder would help.

Could you try to make a minimal `pubspec.yaml` that produces the issue.

Also:
 * what version of flutter do you have `flutter version` or `flutter --version`
 * what platform are you on? windows? what version?

**Comment by sigurdm** [comment]
To run `pub cache repair` using flutter run:
```sh
$ flutter packages pub cache repair
```

**Comment by jonasfj** [comment]
Reading this again:
 >file doc\api\v2_message\QuickReplies\quickReplies.html
>already exists. Overwrite with
>doc\api\v2_message\QuickReplies\quickReplies.html?

This has to do with you being on a file system that is case-insensitive.

This is a problem with the package:
https://github.com/VictorRancesCode/flutter_dialogflow/issues/7

We're working to make it impossible to publish packages with files that are case-insensitive equal.
