### ISSUE TITLE
Validate `PUB_HOSTED_URL` variable format

### ISSUE THREAD

**Issue by dongfuting** [dart-lang/pub#2046]
Running "flutter packages upgrade" in flutter_app...            
Illegal scheme character (at character 7)
export PUB_HOSTED_URL=https://pub.flutter-io.cn/api/packages/cupertino_icons
      ^
dart:core                                                                                         Uri.parse
package:pub/src/source/hosted.dart 165:16                                                         BoundHostedSource._makeUrl
package:pub/src/source/hosted.dart 132:15                                                         BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                                                BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                                                  PackageLister._versions.<fn>.<fn>
dart:async                                                                                        runZoned
package:pub/src/http.dart 272:10                                                                  withDependencyType
package:pub/src/solver/package_lister.dart 75:33                                                  PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                                                        new Future.sync
package:async/src/async_memoizer.dart 43:42                                                       AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                                                  PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                                                 PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                                                 VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                                                 minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                                                 VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                                                  VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                                                 resolveVersions.<fn>
package:pub/src/log.dart 378:18                                                                   progress
package:pub/src/solver.dart 32:10                                                                 resolveVersions
package:pub/src/entrypoint.dart 200:24                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 43:22                                                        UpgradeCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 194:27                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168:39                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                        new Future.sync
package:pub/src/utils.dart 109:12                                                                 captureErrors.<fn>
dart:async                                                                                        runZoned
package:pub/src/utils.dart 126:5                                                                  captureErrors
package:pub/src/command_runner.dart 168:13                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117:11                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning upgrade --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub upgrade failed (65)
Process finished with exit code 65

**Comment by natebosch** [comment]
@dongfuting - it looks like you've configured the `PUB_HOSTED_URL` to be the entire command to set the environment variable, not the value of the variable itself. You might want to look up how to set environment variables on your OS. I think you'll want the value to be `https://pub.flutter-io.cn/` and not the full URI you have in your example since that points to a specific package.

@mit-mit - I've been seeing this flavor of issue crop up a lot. A while back I added a little more validation before using this evironment variable but it looks like there is more we can do, and probably can handle it with a nicer error message and a link to some instructions. This might be something we should prioritize soon.

**Comment by mit-mit** [comment]
cc @jonasfj

**Comment by mit-mit** [comment]
cc @natebosch did you not add this already in https://github.com/dart-lang/pub/pull/1972 ?

**Comment by natebosch** [comment]
I think that what I added in #1972 was incomplete, I handled _some_ malformed config, but I think we need to catch a `FormatException` thrown by `Uri.parse`.

**Comment by mit-mit** [comment]
OK, maybe @jonasfj can help with that?

**Comment by sigurdm** [comment]
I believe this was fixed in https://github.com/dart-lang/pub/pull/3030
