### ISSUE TITLE
flutter packages get

### ISSUE THREAD

**Issue by mablue** [dart-lang/pub#2048]
mab@linux-4pg7:~/Documents/azharja-flutter> flutter packages get
Running "flutter packages get" in azharja-flutter...             
HTTP error 403: Forbidden
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 1 in 1 second...
^C
mab@linux-4pg7:~/Documents/azharja-flutter>

**Comment by jonasfj** [comment]
* Is this a persistent error?
 * Can you make a minimal `pubspec.yaml` that produces this?
 * What operating system are you on?
 * What version of flutter do you have installed?

**Comment by mit-mit** [comment]
Closing as unactionable

**Comment by hamidpp** [comment]
after add "location: ^2.3.5" to pubspec.yaml get this error, please help me
flutter 1.2.1 and windows is 10

**Comment by jonasfj** [comment]
Please file a separate issue... if this is not exactly the same..

Please make sure to post a minimal pubspec.yaml that causes the problem.

Are you under WSL (windows subsystem for linux), there is a few known bugs there.
