### ISSUE TITLE
error in getting dependencies

### ISSUE THREAD

**Issue by hamidjahandideh** [dart-lang/pub#2052]
HTTP error 403: Forbidden
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

**Comment by mit-mit** [comment]
Where in the world are you running this from?

**Comment by jonasfj** [comment]
Are running behind an http proxy? on a corporate network? or from China (see [community mirror](https://flutter.dev/community/china)).

Please, reopen if this is still an issue, and let us know what packages you're trying to fetch :)

**Comment by AhmedArnaout123** [comment]
i tried many countries servers and Honk Kong worked for me.
you can get it from an app called windscribe, it has good limits for free access.
some people used china server.
