### ISSUE TITLE
Tell developers when newer, non-compatible versions are available

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2053]
Developers often struggle with package resolution that won't resolve when package versions are incompatible. As an example, consider:

``` 
  json_annotation: ^1.0.0
  json_serializable: ^0.5.0
```

For this combination, `pub get` will fail:

```
Because json_serializable >=0.5.8+1 <1.0.0 depends on json_annotation >=0.2.9 <0.2.10 and json_serializable >=0.1.0+1 <=0.5.8 requires SDK version >=1.22.1 <2.0.0-∞, json_serializable >=0.1.0+1 <1.0.0 requires json_annotation >=0.2.9 <0.2.10.
So, because constraints depends on both json_serializable ^0.5.0 and json_annotation ^1.0.0, version solving failed.
```

I believe the resolution is to move json_serializable to ^1.0.0, however `pub upgrade` won't do that, as `0.5.0` and `1.0.0` are not compatible per semver.

The present request suggests we print additional information to the developer telling them which newer versions are available for them to update their pubspec's to use, e.g.:

```
Note: Newer versions of the following packages are available, but are not allowed
by the constraints in your pubspec. Consider upgrading the constraints.

Package               Current constraint   Most recent version
json_annotation       ^1.0.0               2.3.1
json_serializable:    ^0.5.0               1.3.1
```

**Comment by mit-mit** [comment]
cc @jonasfj, request I mentioned

**Comment by jonasfj** [comment]
This was solved a long time ago..
