### ISSUE TITLE
Version solving failed when add dependency "http: ^0.12.0+1" to pubspec.yaml

### ISSUE THREAD

**Issue by vulture29** [dart-lang/pub#2058]
Before adding dependency, I changed the version from 1.0.0 to 0.0.1. Not sure if this caused the problem

---- Log transcript ----
FINE: Pub 2.1.1
MSG : Resolving dependencies...
SLVR: fact: money_diary is 0.0.1+1
SLVR: derived: money_diary
SLVR: fact: money_diary depends on cupertino_icons ^0.1.2
SLVR: fact: money_diary depends on path_provider ^0.5.0
SLVR: fact: money_diary depends on objectdb ^1.0.5
SLVR: fact: money_diary depends on flutter any from sdk
SLVR: fact: money_diary depends on english_words ^3.1.0
SLVR: fact: money_diary depends on flutter_test any from sdk
SLVR:   selecting money_diary
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: english_words ^3.1.0
SLVR:   derived: flutter any from sdk
SLVR:   derived: objectdb ^1.0.5
SLVR:   derived: path_provider ^0.5.0
SLVR:   derived: cupertino_icons ^0.1.2
SLVR:   fact: no versions of flutter_test from sdk match 0.0.0
SLVR:   derived: not flutter_test 0.0.0 from sdk
SLVR:   fact: flutter_test from sdk doesn't exist (the Flutter SDK is not available)
SLVR:   conflict: flutter_test from sdk doesn't exist (the Flutter SDK is not available)
SLVR:   ! flutter_test any from sdk is satisfied by flutter_test any from sdk
SLVR:   ! which is caused by "money_diary depends on flutter_test any from sdk"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:00.057298 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.0s).
ERR : Because money_diary depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.
    | 
    | Flutter users should run `flutter packages get` instead of `pub get`.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- End log transcript ----

**Comment by jonasfj** [comment]
Can you share the `dependencies` section of your pubspec?

If we can reproduce we might be able to find the bug..

**Comment by vulture29** [comment]
Here is my pubspec. Thanks

name: money_diary
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  objectdb: ^1.0.5
  path_provider: ^0.5.0
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

**Comment by asjqkkkk** [comment]
I meet the same problem

**Comment by vulture29** [comment]
Magically the error disappeared when I retried the same command today. I was using my PC with vscode so I am sure nothing changed. I have no idea what happened. Maybe this issue can be closed if @asjqkkkk don't have any problem

**Comment by thevishvajeet** [comment]
yeh if any one else is facing this problem try to paste the line correctly.....
