### ISSUE TITLE
Can not resolve the package cached_network_image

### ISSUE THREAD

**Issue by 4Mi** [dart-lang/pub#2059]
pubspec.yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^0.6.0

Error:

HTTP error 424: Failed Dependency

package:pub/src/http.dart 218:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache

===== asynchronous gap ===========================

package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>

===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning upgrade --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub upgrade failed (69) -- attempting retry 1 in 1 second...

HTTP error 424: Failed Dependency

package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================

**Comment by jonasfj** [comment]
Seems similar to the other reports we got when the chinese community mirror was down last week. This should be fixed... 

Please reopen if this unrelated... and let me know if you're using a mirror or an http proxy :)
