### ISSUE TITLE
flutter packages get(HTTP error 424:Failed Dependency)

### ISSUE THREAD

**Issue by 1ntouchble** [dart-lang/pub#2061]
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 1 in 1 second...

**Comment by zoechi** [comment]
Might be https://flutter.dev/community/china

**Comment by chenglu** [comment]
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Comment by jonasfj** [comment]
We should probably improve the error messages going forward, but I'll close this for now.

-----

@chenglu, thanks for fixing the mirror!
I'm slightly curious to learn how you're running this, hit me at jonasfj@google.com if you have time :)

**Comment by 1ntouchble** [comment]
> It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

thx,it works
