### ISSUE TITLE
pub get failed with HTTP ERROR 434

### ISSUE THREAD

**Issue by lhl09120** [dart-lang/pub#2062]
MSG : + analyzer 0.35.2
    | + archive 2.0.8
    | + args 1.5.1
    | + async 2.0.8
    | + bazel_worker 0.1.20
    | + build 1.1.1
    | + build_config 0.3.1+4
    | + build_daemon 0.4.0
    | + build_modules 1.0.8
    | + build_resolvers 1.0.3
    | + build_runner 1.2.7
    | + build_runner_core 2.0.3
    | + build_web_compilers 1.1.0
    | + built_collection 4.1.0
    | + built_value 6.3.0
    | + charcode 1.1.2
    | + code_builder 3.2.0
    | + collection 1.14.11
    | + convert 2.1.1
    | + crypto 2.0.6
    | + csslib 0.14.6
    | + dart_style 1.2.3
    | + fixnum 0.10.9
    | + front_end 0.1.12
    | + glob 1.1.7
    | + graphs 0.2.0
    | + html 0.13.3+3
    | + http 0.12.0+1
    | + http_multi_server 2.0.5
    | + http_parser 3.1.3
    | + io 0.3.3
    | + js 0.6.1+1
    | + json_annotation 2.0.0
    | + kernel 0.3.12
    | + logging 0.11.3+2
    | + matcher 0.12.4
    | + meta 1.1.7
    | + mime 0.9.6+2
    | + package_config 1.0.5
    | + package_resolver 1.0.7
    | + path 1.6.2
    | + pedantic 1.5.0
    | + plugin 0.2.0+3
    | + pool 1.4.0
    | + protobuf 0.13.3
    | + pub_semver 1.4.2
    | + pubspec_parse 0.1.4
    | + quiver 2.0.1
    | + scratch_space 0.0.3+2
    | + shelf 0.7.4
    | + shelf_web_socket 0.2.2+4
    | + source_maps 0.10.8
    | + source_span 1.5.4
    | + stack_trace 1.9.3
    | + stream_channel 1.6.8
    | + stream_transform 0.0.15
    | + string_scanner 1.0.4
    | + term_glyph 1.1.0
    | + timing 0.1.1+1
    | + typed_data 1.1.6
    | + utf 0.9.0+5
    | + watcher 0.9.7+10
    | + web_socket_channel 1.0.9
    | + yaml 2.1.15
IO  : Get package from https://pub.flutter-io.cn/packages/js/versions/0.6.1+1.tar.gz.
MSG : Downloading js 0.6.1+1...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirufFwKJ
IO  : Get package from https://pub.flutter-io.cn/packages/logging/versions/0.11.3+2.tar.gz.
MSG : Downloading logging 0.11.3+2...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirNsNCip
IO  : Get package from https://pub.flutter-io.cn/packages/scratch_space/versions/0.0.3+2.tar.gz.
MSG : Downloading scratch_space 0.0.3+2...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirXOHnaP
IO  : Get package from https://pub.flutter-io.cn/packages/plugin/versions/0.2.0+3.tar.gz.
MSG : Downloading plugin 0.2.0+3...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirdSfUNx
IO  : Get package from https://pub.flutter-io.cn/packages/build_config/versions/0.3.1+4.tar.gz.
MSG : Downloading build_config 0.3.1+4...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirpnOGH0
IO  : Get package from https://pub.flutter-io.cn/packages/shelf_web_socket/versions/0.2.2+4.tar.gz.
MSG : Downloading shelf_web_socket 0.2.2+4...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirohY54i
IO  : Get package from https://pub.flutter-io.cn/packages/timing/versions/0.1.1+1.tar.gz.
MSG : Downloading timing 0.1.1+1...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirXPITXE
IO  : Get package from https://pub.flutter-io.cn/packages/mime/versions/0.9.6+2.tar.gz.
MSG : Downloading mime 0.9.6+2...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirLiWdNM
IO  : Get package from https://pub.flutter-io.cn/packages/watcher/versions/0.9.7+10.tar.gz.
MSG : Downloading watcher 0.9.7+10...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirKdkuMj
IO  : Get package from https://pub.flutter-io.cn/packages/html/versions/0.13.3+3.tar.gz.
MSG : Downloading html 0.13.3+3...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirfGu2B5
IO  : Get package from https://pub.flutter-io.cn/packages/utf/versions/0.9.0+5.tar.gz.
MSG : Downloading utf 0.9.0+5...
IO  : Created temp directory /Users/a09120/.pub-cache/_temp/dirhhr9b8
IO  : HTTP GET https://pub.flutter-io.cn/packages/js/versions/0.6.1+1.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/logging/versions/0.11.3+2.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/scratch_space/versions/0.0.3+2.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/plugin/versions/0.2.0+3.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/build_config/versions/0.3.1+4.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/shelf_web_socket/versions/0.2.2+4.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/timing/versions/0.1.1+1.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/mime/versions/0.9.6+2.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/watcher/versions/0.9.7+10.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/html/versions/0.13.3+3.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP GET https://pub.flutter-io.cn/packages/utf/versions/0.9.0+5.tar.gz
    | user-agent: Dart pub 2.1.1
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/js/versions/0.6.1+1.tar.gz
    | took 0:00:05.807904
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:34 GMT
    | ali-swift-global-savetime: 1551027274
    | x-oss-request-id: 5C72CC4AF651CD19EDD85F29
    | x-m-reqid: j20AAHuPxIgWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs457;SRCPROXY:xs485;SRC:650/424;SRCPROXY:650/424;QNM3:651/424
    | server: Tengine
    | x-oss-server-time: 618
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:34 GMT
    | via: cache13.l2ot7-1[1253,424-1280,M], cache12.l2ot7-1[1253,0], cache3.us3[1512,424-1280,M], cache8.us3[1513,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733274663e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/logging/versions/0.11.3+2.tar.gz
    | took 0:00:05.811838
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:34 GMT
    | ali-swift-global-savetime: 1551027274
    | x-oss-request-id: 5C72CC4A4C1E0BCE4F5FE61E
    | x-m-reqid: 0BwAAKTYjJIWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:jjh1899;SRCPROXY:jjh1493;SRC:621/424;SRCPROXY:621/424;QNM3:622/424
    | server: Tengine
    | x-oss-server-time: 612
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:34 GMT
    | via: cache2.l2ot7-1[1312,424-1280,M], cache30.l2ot7-1[1312,0], cache8.us3[1572,424-1280,M], cache8.us3[1575,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733454682e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/plugin/versions/0.2.0+3.tar.gz
    | took 0:00:05.820306
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:34 GMT
    | ali-swift-global-savetime: 1551027274
    | x-oss-request-id: 5C72CC4A1672CD194BE24094
    | x-m-reqid: 50oAAMc-4ZMWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs1185;SRCPROXY:xs486;SRC:642/424;SRCPROXY:642/424;QNM3:642/424
    | server: Tengine
    | x-oss-server-time: 626
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:34 GMT
    | via: cache15.l2ot7-1[1329,424-1280,M], cache38.l2ot7-1[1329,0], cache3.us3[1594,424-1280,M], cache8.us3[1594,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733694712e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/timing/versions/0.1.1+1.tar.gz
    | took 0:00:05.888260
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:34 GMT
    | ali-swift-global-savetime: 1551027275
    | x-oss-request-id: 5C72CC4A6A0713858EE15874
    | x-m-reqid: A14AAOqqC5kWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:jjh1902;SRCPROXY:jjh1499;SRC:597/424;SRCPROXY:597/424;QNM3:598/424
    | server: Tengine
    | x-oss-server-time: 577
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:35 GMT
    | via: cache29.l2ot7-1[1395,424-1280,M], cache34.l2ot7-1[1395,0], cache5.us3[1656,424-1280,M], cache8.us3[1658,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733604705e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/shelf_web_socket/versions/0.2.2+4.tar.gz
    | took 0:00:05.939893
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:34 GMT
    | ali-swift-global-savetime: 1551027275
    | x-oss-request-id: 5C72CC4A1672CD194BE240AE
    | x-m-reqid: B0oAANG_uJUWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:jjh1521;SRCPROXY:jjh1540;SRC:703/424;SRCPROXY:703/424;QNM3:731/424
    | server: Tengine
    | x-oss-server-time: 693
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:35 GMT
    | via: cache1.l2ot7-1[1466,424-1280,M], cache8.l2ot7-1[1467,0], cache4.us3[1728,424-1280,M], cache8.us3[1729,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733414678e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/build_config/versions/0.3.1+4.tar.gz
    | took 0:00:05.996272
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:35 GMT
    | ali-swift-global-savetime: 1551027275
    | x-oss-request-id: 5C72CC4A9523832754FC8EA2
    | x-m-reqid: TFQAAO8P7ZoWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs449;SRCPROXY:xs1756;SRC:701/424;SRCPROXY:702/424;QNM3:702/424
    | server: Tengine
    | x-oss-server-time: 688
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:35 GMT
    | via: cache14.l2ot7-1[1580,424-1280,M], cache33.l2ot7-1[1581,0], cache9.us3[1844,424-1280,M], cache8.us3[1846,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733044644e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/mime/versions/0.9.6+2.tar.gz
    | took 0:00:06.013863
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:35 GMT
    | ali-swift-global-savetime: 1551027275
    | x-oss-request-id: 5C72CC4A3DD5FC7377D16B50
    | x-m-reqid: lUQAADmbGJ8WW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs1166;SRCPROXY:xs1756;SRC:638/424;SRCPROXY:638/424;QNM3:639/424
    | server: Tengine
    | x-oss-server-time: 622
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:35 GMT
    | via: cache12.l2ot7-1[1559,424-1280,M], cache1.l2ot7-1[1560,0], cache8.us3[1825,424-1280,M], cache8.us3[1826,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733294665e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/html/versions/0.13.3+3.tar.gz
    | took 0:00:06.073470
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:35 GMT
    | ali-swift-global-savetime: 1551027275
    | x-oss-request-id: 5C72CC4AA925579FD6AF9544
    | x-m-reqid: jR0AACVb86IWW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs476;SRCPROXY:xs486;SRC:653/424;SRCPROXY:653/424;QNM3:653/424
    | server: Tengine
    | x-oss-server-time: 624
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:35 GMT
    | via: cache26.l2ot7-1[1602,424-1280,M], cache29.l2ot7-1[1603,0], cache4.us3[1867,424-1280,M], cache8.us3[1868,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733574699e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/watcher/versions/0.9.7+10.tar.gz
    | took 0:00:08.057337
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:37 GMT
    | ali-swift-global-savetime: 1551027277
    | x-oss-request-id: 5C72CC4C41381DAB7A66AA95
    | x-m-reqid: w0AAACnM0RYXW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:jjh1904;SRCPROXY:jjh1531;SRC:606/424;SRCPROXY:606/424;QNM3:607/424
    | server: Tengine
    | x-oss-server-time: 595
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:37 GMT
    | via: cache16.l2ot7-1[2453,424-1280,M], cache8.l2ot7-1[2454,0], cache7.us3[2715,424-1280,M], cache2.us3[2716,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24215510272743956547e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/utf/versions/0.9.0+5.tar.gz
    | took 0:00:09.089487
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:38 GMT
    | ali-swift-global-savetime: 1551027278
    | x-oss-request-id: 5C72CC4D8AFF98C401B4D618
    | x-m-reqid: SVYAAKEDbFEXW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:jjh1876;SRCPROXY:jjh1541;SRC:621/424;SRCPROXY:621/424;QNM3:622/424
    | server: Tengine
    | x-oss-server-time: 612
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:38 GMT
    | via: cache14.l2ot7-1[1472,424-1280,M], cache22.l2ot7-1[1472,0], cache5.us3[1733,424-1280,M], cache2.us3[1735,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24215510272763978714e
IO  : HTTP response 424 Failed Dependency for GET https://pub.flutter-io.cn/packages/scratch_space/versions/0.0.3+2.tar.gz
    | took 0:00:09.591187
    | connection: keep-alive
    | date: Sun, 24 Feb 2019 16:54:38 GMT
    | ali-swift-global-savetime: 1551027278
    | x-oss-request-id: 5C72CC4E7444FA7B187CC88E
    | x-m-reqid: 8DcAACToSXcXW4YV
    | content-type: application/xml
    | x-swift-error: orig response 4XX error,orig response 4XX error
    | x-swift-cachetime: 0
    | x-m-log: QNM:xs1171;SRCPROXY:xs1752;SRC:610/424;SRCPROXY:610/424;QNM3:611/424
    | server: Tengine
    | x-oss-server-time: 594
    | timing-allow-origin: *
    | content-length: 255
    | x-swift-savetime: Sun, 24 Feb 2019 16:54:38 GMT
    | via: cache14.l2ot7-1[5136,424-1280,M], cache28.l2ot7-1[5136,0], cache5.us3[5397,424-1280,M], cache8.us3[5400,0]
    | x-cache: MISS TCP_MISS dirn:-2:-2
    | x-qnm-cache: Miss
    | eagleid: 42c6b24815510272733424679e
ERR : HTTP error 424: Failed Dependency
FINE: Exception type: PubHttpException
ERR : package:pub/src/http.dart 218:5                 _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                      _AsyncAwaitCompleter.completeError
    | package:pub/src/http.dart                       _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                      _asyncThenWrapperHelper
    | package:pub/src/http.dart                       _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                      _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart        ThrottleClient.send
    | package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
    | ===== asynchronous gap ===========================
    | dart:async                                      _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart                 Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 41:23          GetCommand.run
    | package:args/command_runner.dart 194:27         CommandRunner.runCommand
---- End log transcript ----

**Comment by jonasfj** [comment]
This looks like an issue with the mirror you're using... a few other people reported similar issues. Could you give it another try?

**Comment by jonasfj** [comment]
Issues with the chinese community mirror was resolved last week, please reopen if this is an issue.
