### ISSUE TITLE
flutter出现424

### ISSUE THREAD

**Issue by fancycy** [dart-lang/pub#2063]
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

**Comment by buhuiming** [comment]
424

**Comment by zoechi** [comment]
Might be https://flutter.dev/community/china

**Comment by xuwankang** [comment]
怎么解决的

**Comment by Konoha-orz** [comment]
可能国内镜像的问题，如果有使用镜像的试试把对应环境变量删除重启，PUB_HOSTED_URL 跟FLUTTER_STORAGE_BASE_URL

**Comment by ibabyblue** [comment]
国内镜像的问题，删除环境变量重启并翻墙

**Comment by jlcool** [comment]
@ibabyblue 方便翻墙还用啥镜像哦

**Comment by chenglu** [comment]
是中文镜像的问题各位宝宝们，已经修复了，详见 [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967)，给大家说一声抱歉。

**Comment by jonasfj** [comment]
Seems likely this was related to the chinese community mirror issues last week (should be resolved now), please reopen if this a different issue :)
