### ISSUE TITLE
Feature Request: Multi-platform project builds

### ISSUE THREAD

**Issue by paulreimer** [dart-lang/pub#2065]
I am a user of the `flutter-desktop-embedding` project and thrilled with the possibility of cross-platform app development from a single dev workstation.

I ran into an issue when trying to use the same shared filesystem to develop a macOS and Windows app -- in summary, when building the app on one machine, it would populate a `.packages` file with the correct paths for that machine. When re-using the same filesystem mounted on a different machine/architecture, the paths in `.packages` were not valid for the new machine.
https://github.com/google/flutter-desktop-embedding/issues/292

I would like a multi-platform way to use the exact same project sources (in `lib/`) on a shared filesystem.

**Comment by jonasfj** [comment]
I doubt this is something we intend to support.

For git you would always put `.packages` in your gitignore... Probably you'll have to sync file systems in a manner that ignores `.packages`.

You could also make a wrapper script for pub that renames your `.packages` file before/after running a pub/dart/flutter command...

Files are stored different places in different platforms, and Dart does not understand packages it only understands the mapping in `.packages`..

Personally, I've made my `.packages` relocatable by moving my `.pub-cache/` to the same location on both computers...  But that doesn't work if one of them is windows.. :)

**Comment by paulreimer** [comment]
OK, no worries!

I managed to resolve it for my `flutter` use-case -- there is a hidden `--packages` command that can override the path to `.packages`.
