### ISSUE TITLE
 Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left) HTTP error 424: Failed Dependency

### ISSUE THREAD

**Issue by SilenceZhou** [dart-lang/pub#2071]
I try delegate cache （~/flutter/bin/cache）, try again 'flutter doctor'; And use prosoxy soft Astrill（I can accese google.com , It's meaning net work is good）, please tell me how deal with the problem.

Downloading Dart SDK from Flutter engine f7306394e303a210a9971acb60f9ba11d7c64ec8...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 71.3M 100 71.3M 0 0 8932k 0 0:00:08 0:00:08 --:--:-- 10.3M
Building flutter tool...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31 ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37 BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13 BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48 Entrypoint._get.
===== asynchronous gap ===========================
dart:async runZoned
package:pub/src/http.dart 272:10 withDependencyType
package:pub/src/entrypoint.dart 367:12 Entrypoint._get
dart:async Future.wait
package:pub/src/entrypoint.dart 228:18 Entrypoint.acquireDependencies
dart:async _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart VersionSolver.solve
dart:async _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart VersionSolver._result
This is an unexpected error. Please run

```
pub --trace upgrade --verbosity=error
```
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
HTTP error 424: Failed Dependency

**Comment by dulinshun** [comment]
me too

**Comment by nobewp** [comment]
me too

**Comment by SilenceZhou** [comment]
I solved this problem:

1. Change the storage directory of flutter, change '~/' to '~/Documents'
2.git clone -b stable https://github.com/flutter/flutter.git
3.flutter deoctor
4.It’s ok

The log is as follows
-------
iMac:flutter hello$ cd ~/Documents/

iMac:Documents hello$ git clone -b stable https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 157865 (delta 5), reused 4 (delta 1), pack-reused 157842
Receiving objects: 100% (157865/157865), 54.87 MiB | 324.00 KiB/s, done.
Resolving deltas: 100% (120116/120116), done.

iMac:Documents hello$ cd flutter/

iMac:flutter hello$ fluttr doctor
-bash: fluttr: command not found
iMac:flutter zhouyun$ flutter doctor
Downloading Dart SDK from Flutter engine 7375a0f414bde4bc941e623482221db2fc8c4ab5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.7M  100 49.7M    0     0   9.8M      0  0:00:05  0:00:05 --:--:-- 10.7M
Building flutter tool...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust
this source!
Downloading Material fonts...                                0.4s
Downloading package sky_engine...                            0.4s
Downloading common tools...                                  0.8s
Downloading darwin-x64 tools...                              2.8s
Downloading android-arm-profile/darwin-x64 tools...          0.9s
Downloading android-arm-release/darwin-x64 tools...          0.6s
Downloading android-arm64-profile/darwin-x64 tools...        1.0s
Downloading android-arm64-release/darwin-x64 tools...        0.5s
Downloading android-x86 tools...                             1.6s
Downloading android-x64 tools...                             3.0s
Downloading android-arm tools...                             3.4s
Downloading android-arm-profile tools...                     1.1s
Downloading android-arm-release tools...                     0.8s
Downloading android-arm64 tools...                           1.1s
Downloading android-arm64-profile tools...                   0.9s
Downloading android-arm64-release tools...                   0.6s
Downloading android-arm-dynamic-profile tools...             0.7s
Downloading android-arm-dynamic-release tools...             0.8s
Downloading android-arm64-dynamic-profile tools...           1.1s
Downloading android-arm64-dynamic-release tools...           2.1s
Downloading ios tools...                                     3.4s
Downloading ios-profile tools...                             3.4s
Downloading ios-release tools...                             2.1s
Downloading Gradle Wrapper...                                0.3s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.31.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


iMac:flutter hello$ flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by SilenceZhou** [comment]
> me too

it's ok! Please see above

**Comment by SilenceZhou** [comment]
> me too

it's ok! Please see above

**Comment by SilenceZhou** [comment]
> > me too
> 
> it's ok! Please see above

According to my operation, if you can, please give me feedback.

**Comment by SilenceZhou** [comment]
> me too

According to my operation, if you can, please give me feedback.

**Comment by SilenceZhou** [comment]
> me too

According to my operation, if you can, please give me feedback.

**Comment by jonasfj** [comment]
Seems related to errors from the Chinese community mirrror, these should have been fixed... 

Please let us know if there is still issues..
