### ISSUE TITLE
Failed Dependency package:pub/src/http.dart 218:5                 _ThrowingClient.send

### ISSUE THREAD

**Issue by nobewp** [dart-lang/pub#2073]
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async

**Comment by soloFZZ** [comment]
me too, Who has a solution

**Comment by zoechi** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment]
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.
