### ISSUE TITLE
Unable to 'pub upgrade' flutter too

### ISSUE THREAD

**Issue by yeminliu2010** [dart-lang/pub#2075]

**Comment by zoechi** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment]
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Comment by jonasfj** [comment]
Please open a new issue with more details if this is still a problem..
