### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\flutter\bin\cache\dart-sdk\bin"

### ISSUE THREAD

**Issue by vopee** [dart-lang/pub#2076]
Could not find a file named "pubspec.yaml" in "C:\flutter\bin\cache\dart-sdk\bin"

**Comment by zoechi** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment]
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Comment by jonasfj** [comment]
Please reopen if this is still a problem...

Maybe include a stack trace, verbose logging or some information on what you're trying to do :)
