### ISSUE TITLE
Encode the URL

### ISSUE THREAD

**Issue by chenglu** [dart-lang/pub#2082]
Hi Team:

I'd like to give this advice to you, could we encode the URL before HTTP request based on the spec of RFC3986? Since some of our files will have special characters like `plugin-0.2.0+3.tar.gz`, thanks a lot!

cc+ @zoechi, WDYT?

**Comment by jonasfj** [comment]
Where are you thinking? Is this on the server?

The server component is: https://github.com/dart-lang/pub-dartlang-dart

I found that it might be an issue in the redirect targets and filed: https://github.com/dart-lang/pub-dartlang-dart/issues/2093

**Comment by chenglu** [comment]
The context is the mirror site issue just happened, finally I found the new file system was strict and allowed the encode URL only, so it will throw 424 error when the special characters were included in the URL, so I was wondering if we could encode the URL when we start to have the HTTP request by the `pub` command.

The dart-lang/pub-dartlang-dart#2093 --you are right, the resource that `pub get` is 301 to the new location with the decoded URL, but GCS support both encoded and decoded URL when we try to get the resource, seems we don't have any solution for this right now, but thanks for your time!
