### ISSUE TITLE
flutter run fails

### ISSUE THREAD

**Issue by Andy1984** [dart-lang/pub#2086]
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 341:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 142:7           BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _AsyncAwaitCompleter.completeError
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _asyncErrorWrapperHelper
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
package:pub/src/source.dart 167:12                 BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
dart:async                                         runZoned
package:pub/src/http.dart 272:10                   withDependencyType
package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/utils.dart                         minByAsync
package:pub/src/solver/version_solver.dart 350:25  VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/solver/version_solver.dart         VersionSolver.solve
package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
package:pub/src/log.dart 378:18                    progress
package:pub/src/solver.dart 32:10                  resolveVersions
package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- Log transcript ----
FINE: Pub 2.1.0
MSG : Resolving dependencies...
SLVR: fact: bob_demo is 1.0.0+1
SLVR: derived: bob_demo
SLVR: fact: bob_demo depends on dio ^2.0.5
SLVR: fact: bob_demo depends on intl ^0.15.7
SLVR: fact: bob_demo depends on flutter any from sdk
SLVR: fact: bob_demo depends on dio_flutter_transformer ^2.0.6
SLVR: fact: bob_demo depends on cupertino_icons ^0.1.2
SLVR: fact: bob_demo depends on sy_flutter_qiniu_storage ^0.1.4
SLVR: fact: bob_demo depends on flutter_screenutil ^0.5.1
SLVR: fact: bob_demo depends on flutter_blue 0.5.0
SLVR: fact: bob_demo depends on json_annotation ^2.0.0
SLVR: fact: bob_demo depends on flutter_svg ^0.10.4
SLVR: fact: bob_demo depends on path_provider ^0.5.0
SLVR: fact: bob_demo depends on build_runner ^1.0.0
SLVR: fact: bob_demo depends on json_serializable ^2.0.0
SLVR: fact: bob_demo depends on flutter_test any from sdk
SLVR:   selecting bob_demo
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: json_serializable ^2.0.0
SLVR:   derived: build_runner ^1.0.0
SLVR:   derived: path_provider ^0.5.0
SLVR:   derived: flutter_svg ^0.10.4
SLVR:   derived: json_annotation ^2.0.0
SLVR:   derived: flutter_blue 0.5.0
SLVR:   derived: flutter_screenutil ^0.5.1
SLVR:   derived: sy_flutter_qiniu_storage ^0.1.4
SLVR:   derived: cupertino_icons ^0.1.2
SLVR:   derived: dio_flutter_transformer ^2.0.6
SLVR:   derived: flutter any from sdk
SLVR:   derived: intl ^0.15.7
SLVR:   derived: dio ^2.0.5
IO  : Get versions from https://pub.flutter-io.cn/api/packages/flutter_svg.
IO  : HTTP GET https://pub.flutter-io.cn/api/packages/flutter_svg
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.1.0
SLVR: Version solving took 0:00:00.125414 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.1s).
ERR : The setter 'readEventsEnabled=' was called on null.
    | Receiver: null
    | Tried calling: readEventsEnabled=false
FINE: Exception type: NoSuchMethodError
ERR : package:pub/src/source/hosted.dart 341:7           BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 142:7           BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncErrorWrapperHelper
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                 BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
    | dart:async                                         runZoned
    | package:pub/src/http.dart 272:10                   withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/utils.dart                         minByAsync
    | package:pub/src/solver/version_solver.dart 350:25  VersionSolver._choosePackageVersion
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- End log transcript ----

**Comment by Andy1984** [comment]
I am from China and I did the configuration. However, I didn't write export http_proxy before, so everything is okay. Yesterday I write export http_proxy in my .zshrc. It does not work. Thus, I delete the special configuration about flutter in China. Everything is good again.

**Comment by jonasfj** [comment]
> Everything is good again.

Okay, I understand this to mean the issue is related to your internet connection and should be closed, please reopen if that was incorrect.
