### ISSUE TITLE
Carousel Pro

### ISSUE THREAD

**Issue by shefftt** [dart-lang/pub#2088]
pub get failed (69) -- attempting retry 5 in 16 seconds...
HTTP error 403: Forbidden
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

**Comment by sigurdm** [comment]
How is your pubspec?
Did this work before?
What is your OS? Are you using windows for linux?

**Comment by jonasfj** [comment]
Are you behind an HTTP proxy of some sort? A quick grep through our logs didn't show any 403s for GET requests... well, could be we grepped the logs incorrectly (this was just a quick look).

**Comment by shefftt** [comment]
> 
> 
> How is your pubspec?
> Did this work before?
> What is your OS? Are you using windows for linux?

My OS windows 
No did not work before

**Comment by jonasfj** [comment]
What version of Windows?

Are you running on WSL (Windows Subsystem for Linux)?

What packages are you trying to download in your `pubspec.yaml`?

Is this is an issue?

Have you tried to use `8.8.8.8` as DNS server for your system?

**Comment by jonasfj** [comment]
Please reopen if this is still an issue..
