### ISSUE TITLE
consider including analysis_options in package archives

### ISSUE THREAD

**Issue by pq** [dart-lang/pub#2094]
I'm working on a tool to help reason about published pub packages and it would be handy for my analyses to have access to their analysis_options.

Prototype here: https://github.com/pq/pub_crawl/

I'm guessing these are excluded from source archives for space reasons?

**Comment by natebosch** [comment]
As I dig through `~/.pub_cache/hosted/pub.dartlang.org/` I'm seeing a bunch of `analysis_options.yaml` files - so it looks like they must be in the archive.

Some packages that are developed in a "mono repo" put their analysis options outside of the directory for an individual package and so these would be missing from the archives.

What packages are you seeing with analysis options that you expect to have them?

**Comment by pq** [comment]
Hey @natebosch.  Thanks for following up.  Looks like this was actually my mistake.  I fetched a bunch of projects and saw no options files and jumped to conclusions.  I'll close this out but if I see anything surprising I'll re-open.

Thanks again for checking!
