### ISSUE TITLE
err

### ISSUE THREAD

**Issue by crazy1017** [dart-lang/pub#2098]
Bad state: Origin is only applicable schemes http and https: e:%5CAndroidSDK%5Cflutter%5Cbin/api/packages/cupertino_icons
package:pub/src/source/hosted.dart 341:7                                        BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 142:7                                        BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                              BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                                PackageLister._versions.<fn>.<fn>
dart:async                                                                      runZoned
package:pub/src/http.dart 272:10                                                withDependencyType
package:pub/src/solver/package_lister.dart 75:33                                PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                                      new Future.sync
package:async/src/async_memoizer.dart 43:42                                     AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                                PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                               PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                               VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                               minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                               VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                                VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                               resolveVersions.<fn>
package:pub/src/log.dart 378:18                                                 progress
package:pub/src/solver.dart 32:10                                               resolveVersions
package:pub/src/entrypoint.dart 200:24                                          Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 43:22                                      UpgradeCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 194:27                                         CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168:39                                      PubCommandRunner.runCommand.<fn>
dart:async                                                                      new Future.sync
package:pub/src/utils.dart 109:12                                               captureErrors.<fn>
dart:async                                                                      runZoned
package:pub/src/utils.dart 126:5                                                captureErrors
package:pub/src/command_runner.dart 168:13                                      PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117:11                                      PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\rr\tmpxc66kk\w\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace upgrade

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by jonasfj** [comment]
What were you trying to do?

Where are you located?

What command did you execute?

What did the pubspec.yaml look like?

What environment variables did you set ?

Are you trying to use a different pub server than `pub.dartlang.org`?

----
I should probably get around to update our issue templates :)

**Comment by jonasfj** [comment]
Please reopen if this is still an issue, or you have additional information :)
