### ISSUE TITLE
Should precompiled executables be in the Pub cache?

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/pub#2100]
The compilation step tends to make processes like `pub get` fairly time-intensive. Oftentimes, these are executables that consumers of the package might not even directly use. For example, I have never used `build_runner:graph_inspector`, but there are at least a few dozen separate instances of it compiled on my system.

As far as I can tell, versions of Pub packages are immutable, so the source code of, say `build_runner@1.0.0` is always the same. So I would also assume that the precompiled executable is also always identical.

Packages are already stored in a cache so that they will only be downloaded once. If executables are also stored there, then each version will only have to be compiled once, system-wide.

I saw on another issue a suggestion (I think by jakemac?) that executables could be compiled lazily/as-needed, instead of on get/upgrade. I think that if lazy compilation were combined with a global cache, the overall user experience would be smoother.

Thoughts?

P.S. I’m willing to submit a PR for this.

**Comment by jonasfj** [comment]
Using a global cache has some issues, notably, that the dependencies might be different in two different projects... 

Two projects might use the same version of `build_runner`, but one of them could have a `pubspec.lock` that pins `build` to an older version than the other.. So they wouldn't be able to use the same pre-compiled executables.

One could use a hash of dependencies to resolve this, but then the cache might grow huge, and it'll never be garbage collected.

----

I think lazy compilation is a good start... I haven't looked at this part of the code yet, but if you want to work on it I'll be happy to do the reviews.
