### ISSUE TITLE
Stack trace for `pub uploader add <email>`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2108]
Stack Trace:

```
The getter 'length' was called on null.
Receiver: null
Tried calling: length
dart:core                                    Uri.parse
package:pub/src/command/uploader.dart 23:25  UploaderCommand.server
package:pub/src/command/uploader.dart 63:25  UploaderCommand.run.<fn>.<fn>
package:pub/src/oauth2.dart 97:14            withClient.<fn>
This is an unexpected error. Please run

    pub --trace uploader add <email>
```

Repro steps: run `pub uploader add <email>` from a package

Workaround: add `--server https://pub.dartlang.org` (this wasn't required before, so I think maybe there is a bug in the defaulting?)

**Comment by jonasfj** [comment]
This was fixed in https://github.com/dart-lang/pub/pull/2102

Credit @natebosch, I know @sigurdm is in the process of rolling this into the dart-sdk.

**Comment by jakemac53** [comment]
oh ok great! Feel free to close this or leave it open until it is published just so you get fewer dupes.

**Comment by sigurdm** [comment]
https://dart-review.googlesource.com/c/sdk/+/97638 has landed
