### ISSUE TITLE
Highlight when a Flutter package only works on one platform (iOS only / Android only)

### ISSUE THREAD

**Issue by MarkOSullivan94** [dart-lang/pub#2109]
I believe a great addition to the pub site would be for there to be a review of new Flutter packages to ensure that they work on both iOS and Android, if not a warning tag should be added beside the package.

That might require quite a bit of manual work reviewing every package however it would definitely help ensure devs are well informed when picking a package.

An alternative would be a report functionality where people could report if it only works on one platform. 

For example, I've just been doing some testing of music packages on Flutter and I've discovered that (Flutter-AssetsAudioPlayer)[https://github.com/florent37/Flutter-AssetsAudioPlayer/] doesn't work on iOS but unfortunately there's no information other than this issue: https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/1

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/pub-dartlang-dart/issues/187

**Comment by MarkOSullivan94** [comment]
Thanks for link @kevmoo!
