### ISSUE TITLE
flutter packages get (Error)

### ISSUE THREAD

**Issue by ketonium10** [dart-lang/pub#2110]
![Dart](https://user-images.githubusercontent.com/39912882/55072434-1a2b7580-50b1-11e9-9122-16a3d13fd720.PNG)
![dart2](https://user-images.githubusercontent.com/39912882/55072450-27e0fb00-50b1-11e9-965a-ab447e22632d.PNG)

Overwrite with 
doc\api\v2_message\QuickReplies\quickReplies.html?

(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
ERROR: Can't allocate required memory!

package:pub/src/io.dart 944:7               _extractTarGzWindows.<fn>

===== asynchronous gap ===========================

package:pub/src/io.dart 821:20              withTempDir

===== asynchronous gap ===========================

package:pub/src/io.dart 915:10              _extractTarGzWindows

package:pub/src/io.dart 843:18              extractTarGz

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache

===== asynchronous gap ===========================

package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================

dart:async                                  runZoned

package:pub/src/http.dart 272:10            withDependencyType

package:pub/src/entrypoint.dart 367:12      Entrypoint._get

dart:async                                  Future.wait

package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver.solve

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver._result

This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (1)
Process finished with exit code 1

**Comment by ketonium10** [comment]
Hello. I'm trying to import dependencies of dialogflow and tts.

**Comment by jonasfj** [comment]
This package is known to be broken on systems with case insensitive filesystems, see:
https://github.com/VictorRancesCode/flutter_dialogflow/issues/7

**Comment by jonasfj** [comment]
We've updated our servers to not accept such packages in the future :)
