### ISSUE TITLE
run flutter packages pub publish

### ISSUE THREAD

**Issue by huoshulei** [dart-lang/pub#2112]
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:http/src/io_client.dart 33:23                    IOClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 68:39                          _PubHttpClient.send
===== asynchronous gap ===========================
package:http_retry/http_retry.dart 97:33                 RetryClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 194:43                         _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31           ThrottleClient.send
===== asynchronous gap ===========================
package:http/src/base_client.dart 169:38                 BaseClient._sendUnstreamed
===== asynchronous gap ===========================
package:http/src/base_client.dart 54:7                   BaseClient.post
package:oauth2/src/authorization_code_grant.dart 282:38  AuthorizationCodeGrant._handleAuthorizationCode
===== asynchronous gap ===========================
package:oauth2/src/authorization_code_grant.dart 231:18  AuthorizationCodeGrant.handleAuthorizationResponse
===== asynchronous gap ===========================
package:pub/src/oauth2.dart 197:17                       _authorize.<fn>.<fn>
package:shelf/shelf_io.dart 88:29                        handleRequest
===== asynchronous gap ===========================
package:shelf/shelf_io.dart 64:34                        serveRequests.<fn>.<fn>
This is an unexpected error. Please run

    pub --trace publish

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub finished with exit code 1

**Comment by jonasfj** [comment]
Where are you located? If you've configured the Chinese community mirror publishing won't work.

**Comment by huoshulei** [comment]
> 你现在在哪里？如果你配置了中文社区镜像发布将无法正常工作。



> Where are you located? If you've configured the Chinese community mirror publishing won't work.


I am in China, do you mean to cancel the Chinese community configuration?

**Comment by jonasfj** [comment]
Yeah, you'll be unable to publish if connected through `export PUB_HOSTED_URL=https://pub.flutter-io.cn`. I am aware that some users in China have problems connecting to `pub.dartlang.org` and `https://storage.googleapis.com/pub-packages/....` which would make it hard to publish packages.

Note. to publish you'll need to sign-in with a Google account. I don't know which network services is available in China, so I can't advise on how to do that.

**Comment by jonasfj** [comment]
I filed #2556 to mention this on the flutter website about the community mirror.

**Comment by jonasfj** [comment]
note. I closed this, as I don't see how we can help.

**Comment by huoshulei** [comment]
谢谢
