### ISSUE TITLE
Document behavior of dependency_override in published pubspecs

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#2117]
If I depend on a package with a dependency_override in its pubspec it does not take effect when I do `pub get` in my package.

This should be clarified in our documentation: https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

Having a `dependency_override` in a library can simplify development of [mono_repo](https://github.com/dart-lang/mono_repo)'s 
(eg. I could dependency_override-depend on a path version of protobuf from protoc_plugin inside https://github.com/dart-lang/protobuf, making it easy to test current tip-of-tree versions together).

**Comment by jonasfj** [comment]
We should double check this behavior too...  and write a test case for it if we don't have one (from a quick look it doesn't seem like we do).

**Comment by sigurdm** [comment]
This has been clarified now. https://dart.dev/tools/pub/dependencies#dependency-overrides states: Only the dependency overrides in a package’s own pubspec are considered during package resolution. Dependency overrides inside any depended-on packages are ignored.
