### ISSUE TITLE
run travis tests on osx and windows

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2118]
Example of this in grpc:
https://github.com/grpc/grpc-dart/blob/0cbc5401c82500bf20b89654c4adbde355dcc8d3/.travis.yml#L31-L34

Hopefully, this is just a matter of configuring the travis file.

**Comment by irvifa** [comment]
Hi, I come across and saw this is already implemented in https://github.com/dart-lang/pub/blob/3606265962da4248d34d352aa3d170aae4496a90/.travis.yml#L8 I guess we can close this issue then?

**Comment by sigurdm** [comment]
Yeah - we are running CI on all three platforms now!
