### ISSUE TITLE
Shouldn't "pub publish" allow missing homepage if repository is provided?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#2127]
The website suggests that both `homepage` and `repository` are optional in `pubspec.yaml` but that's recommended to supply at least one. I populated only `repository` since my package has no website, but when I run `pub publish --dry-run` it reports:

```
Missing requirements:
* Your pubspec.yaml is missing a "homepage" field.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://www.dartlang.org/tools/pub/cmd/pub-lish.
```

Many projects have a repo URL with no specific website. It feels weird to force the repo URL to be copied into `homepage` - pub could fall back to `repository` where it really wants a URL, but by keeping them separate it would avoid the repo being mis-labelled as the homepage.

So, could/should this validation be relaxed to allow *either* field?

**Comment by jonasfj** [comment]
Yeah, I think this validation is from before we had the `repository` field.

We should only require that either `homepage` or `repository` is given.

**Comment by jonasfj** [comment]
Note: we might need to patch the pub.dartlang.org service to accept either `homepage` or `repository`.

**Comment by sigurdm** [comment]
Furthermore I think we should move towards a situation where the client has no hard constraints on publishing, only warnings, and the server is doing the rejection. It would allow us to move much faster.
Even when we fix this in the client, it still affects all older sdks.

**Comment by Albert221** [comment]
I just had the same issue. Also, this validation doesn't match [The pubspec file docs](https://dart.dev/tools/pub/pubspec#homepage) which say that **both** `homepage` and `repository` are optional (but recommended).
