### ISSUE TITLE
SECURITY: pub dumps sensitive information if it fails to parse credentials.json

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#2132]
Tested on pub 2.3.0.

If pub fails to parse the contents of a `credentials.json` file, it prints the `FormatException` message, which is highly likely to include sensitive information. If pub is being run in a public place, this can cause credentials to be leaked publicly. This happened in practice when deploying the [sass/migrator](https://github.com/sass/migrator) package via Travis CI. Luckily the credentials were revoked before any malicious actors used them, but the next user to fall afoul of this may not be so lucky.

**Comment by sigurdm** [comment]
Not sure why we never got to this, it no longer seems that critical now we have better support for automated publishing. But a fix seems trivial here.
