### ISSUE TITLE
Add option to upload git commit when publishing a package

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/pub#2138]
Today `pub publish` ignores the presence of `.git` directory when publishing. When you upload a new version but forget to tag it in git (like I did recently), it is hard to figure out what exact git revision is now on pub.

It would be great if `pub publish` could attach the current git commit to the published package. This feature can be implemented without a git dependency. All information is stored in well-known plain-text files. For example:

```
$ cat .git/HEAD
ref: refs/heads/master
$ cat .git/refs/heads/master
252d1c71ac171d9044f145a301d19749b1cabba1
```

**Comment by natebosch** [comment]
We'd probably want to avoid this if the repo is dirty...

**Comment by cbracken** [comment]
There's also no guarantee that the repo is a git repo -- e.g. I've seen people asking about which bits of their package they can ignore in svn/hg/p4 on StackOverflow.

**Comment by yjbanov** [comment]
I wouldn't _assume_ it's always git, but when it is git we could enable this feature. If there's strong desire to add support for other source control systems, we could add them too.

**Comment by jonasfj** [comment]
There is been other calls for this..

Similarly, we could help tag in git and/or check that git isn't dirty...

**Comment by yjbanov** [comment]
I imagine checking if git is dirty or not would actually require a dependency on the `git` command. My original feature request does not require any extra dependencies. It is literally implementable as:

```dart
import 'dart:io' as io;

void main() {
  final io.Directory dotGit = io.Directory('.git');
  if (!dotGit.existsSync()) {
    print('Not a git repo');
    return;
  }

  final String head = io.File('.git/HEAD').readAsStringSync().split(':').last.trim();
  final String commit = io.File('.git/${head}').readAsStringSync().trim();
  print('Current git commit: ${commit}');
}
```

I certainly wouldn't mind a dirty check as an extra feature, but it would be great to get this one asap before expanding scope.

**Comment by sigurdm** [comment]
We could also make a way of publishing a tagged commit ignoring the working directory.

**Comment by sigurdm** [comment]
I think that now we have automated publishing from github this is obsolete.

Please reopen if you think we still need this.
