### ISSUE TITLE
Command to highlight direct dependencies with newer versions

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2140]
Originally filed as https://github.com/dart-lang/pub-dev/issues/2320, credits @ShivamArora.

**Example** `pubspec.yaml`
```yaml
name: hackpkg
dependencies:
  shelf_router_generator: 0.7.0+1
```

If I have a single direct dependency `shelf_router_generator` which has a constraint that prevents a newer version from being used, `pub upgrade` will print the following:
```
$ pub upgrade
Resolving dependencies... (8.2s)
  analyzer 0.35.4 (0.36.3 available)
  args 1.5.1
  async 2.2.0
  build 1.1.4
  build_config 0.3.2 (0.4.0 available)
  built_collection 4.2.2
  built_value 6.5.0
  charcode 1.1.2
  code_builder 3.2.0
  collection 1.14.11
  convert 2.1.1
  crypto 2.0.6
  dart_style 1.2.4 (1.2.7 available)
  fixnum 0.10.9
  front_end 0.1.14 (0.1.18 available)
  glob 1.1.7
  http_methods 1.0.0
  http_parser 3.1.3
  json_annotation 2.4.0
  kernel 0.3.14 (0.3.18 available)
  logging 0.11.3+2
  matcher 0.12.5
  meta 1.1.7
  package_config 1.0.5
  path 1.6.2
  pedantic 1.7.0
  pub_semver 1.4.2
  pubspec_parse 0.1.4
  quiver 2.0.3
  shelf 0.7.5
  shelf_router 0.7.0+1
  shelf_router_generator 0.7.0+1 (0.7.1 available)
  source_gen 0.9.4+2
  source_span 1.5.5
  stack_trace 1.9.3
  stream_channel 2.0.0
  string_scanner 1.0.4
  term_glyph 1.1.0
  typed_data 1.1.6
  watcher 0.9.7+10
  yaml 2.1.15
No dependencies changed.
```

Maybe we could:
 * Highlight the direct dependency more clearly than the indirect ones?
 * Change the order, so direct dependencies appear separate from indirect dependencies?
 * Add a `pub outdated` command that only shows which direct dependencies are out-dated?

@mit-mit, this might be related to something you were talking about earlier.

**Comment by sigurdm** [comment]
I think `pub upgrade --dry-run` already does what `pub outdated` would do.
Highlighting and/or printing direct dependencies first would be a nice touch.

**Comment by sigurdm** [comment]
We have `dart pub outdated` now. I think this is done.
