### ISSUE TITLE
use absolute path to tar

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2144]
See: https://github.com/dart-lang/pub/blob/ecd5b413271f2699f8cd9e23aa4eebb5030c964f/lib/src/io.dart#L881

If the current folder contains a `tar/` folder, then this command will fail to run.

**Comment by sigurdm** [comment]
This is actually a security issue.
If you include a malicious `tar` executable in your github repo you can execute arbitrary code on `pub get`.

**Comment by jonasfj** [comment]
This was fixed upstream.
