### ISSUE TITLE
Could not un-tar (exit code 2). Error:

### ISSUE THREAD

**Issue by zhouzhijin0908** [dart-lang/pub#2145]
Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\asus\AppData\Local\Temp\pub_ab175342-81bf-11e9-b955-88d7f6c568ee\data.tar

Extracting  .gitignore
Extracting  CHANGELOG.md
Extracting  LICENSE
Extracting  README.md
Extracting  analysis_options.yaml
Extracting  android\.gitignore
Extracting  android\build.gradle
Extracting  android\gradle.properties
Extracting  android\settings.gradle
Extracting  android\src\main\AndroidManifest.xml
Extracting  android\src\main\java\com\flutter_webview_plugin\BrowserClient.java
Extracting  android\src\main\java\com\flutter_webview_plugin\FlutterWebviewPlugin.java
Extracting  android\src\main\java\com\flutter_webview_plugin\ObservableWebView.java
Extracting  android\src\main\java\com\flutter_webview_plugin\WebviewManager.java
Extracting  android\src\main\res\xml\filepaths.xml
Extracting  example\.gitignore

Extracting  example\README.md
Extracting  example\android.iml
Extracting  example\android\.gitignore
Extracting  example\android\app\build.gradle
Extracting  example\android\app\src\main\AndroidManifest.xml

Extracting  example\android\app\src\main\java\com\yourcompany\flutter_webview_plugin_example\MainActivity.java
Extracting  example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
Extracting  example\android\app\src\main\res\mipmap-hdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-mdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png
Extracting  example\android\build.gradle
Extracting  example\android\gradle.properties
Extracting  example\android\settings.gradle
Extracting  example\flutter_webview_plugin_example.iml
Extracting  example\ios\.gitignore
Extracting  example\ios\Flutter\AppFrameworkInfo.plist
Extracting  example\ios\Flutter\Debug.xcconfig
Extracting  example\ios\Flutter\Release.xcconfig
Extracting  example\ios\Flutter\flutter_assets\AssetManifest.json

Extracting  example\ios\Flutter\flutter_assets\FontManifest.json
Extracting  example\ios\Flutter\flutter_assets\LICENSE
Extracting  example\ios\Flutter\flutter_assets\fonts\MaterialIcons-Regular.ttf
Extracting  example\ios\Podfile
Extracting  example\ios\Runner.xcodeproj\project.pbxproj
Extracting  example\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata
Extracting  example\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme
Extracting  example\ios\Runner.xcworkspace\contents.xcworkspacedata
Extracting  example\ios\Runner.xcworkspace\xcshareddata\Runner.xcscmblueprint
Extracting  example\ios\Runner\AppDelegate.h
file example\ios\Runner\AppDelegate.m
already exists. Overwrite with 
example\ios\Runner\AppDelegate.m?
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
ERROR: Can't allocate required memory!

package:pub/src/io.dart 938:7               _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 815:20              withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 909:10              _extractTarGzWindows
package:pub/src/io.dart 837:18              extractTarGz

===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 310:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 204:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 374:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 370:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 231:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1)
Process finished with exit code 1

**Comment by jonasfj** [comment]
Which package is this... It's probably due to two filenames that are case insensitive the same, but case sensitive different...

We've already made it impossible to publish such packages, but a few exist..

Otherwise, try to delete ~/.pub-cache/ and see if that helps... This will force you to download all packages again, even in other projects.

**Comment by yinde0** [comment]
Sorry, Is there anyother way out?

**Comment by sigurdm** [comment]
We no longer rely on the system tar.

Closing assuming stale.
