### ISSUE TITLE
Allow caret constraints on the SDK version

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2153]
The following error is really annoying:
> ^ version constraints aren't allowed for SDK constraints since older versions of pub don't support them.

This happens when publishing a package a `pubspec.yam` containing:
```yaml
environment:
  sdk: ^2.2.0
```

We should allow this caret notation in SDK constraints because writing `sdk: '>= 2.2.0 < 3.0.0'` is really annoying, and it's hard to read.

Possible solutions include:
 A) Rewrite the `pubspec.yaml` automatically before publishing to rewrite the constraint,
 B) Rewrite the `pubspec.yaml` automatically server side (after accepting the tarball),
 C) Test how far back `pub` doesn't support caret notation and decide if breaking them for new packages using this is acceptable.
 D) Don't serve the versions from the pub server if the user-agent is an old pub version.

**Comment by jonasfj** [comment]
I did a quick check yesterday and caret notation is supported by Dart 1.24.3 which is the latest Dart 1.x.

**Comment by iLoveDocs** [comment]
@jonasfj Should this issue be closed now?

**Comment by jonasfj** [comment]
(C) probably still needs to be determined... Inorder to decide if (B) is necessary.

**Comment by sigurdm** [comment]
Did some digging and it seems dart 1.11.0 is the first to support ^ deps.

**Comment by jonasfj** [comment]
We have precedence for server-side rewrites like (B) in:
https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/src/pubspec_content_override.dart

But I'm not entirely sure that's how we should solve it, because this was done to fix a case where newer versions of `pub_semver` couldn't understand what we had written before. Which is not the case here.

We could also investigate the amount of traffic from dart < 1.11.0

**Comment by sigurdm** [comment]
> Did some digging and it seems dart 1.11.0 is the first to support ^ deps.

Sorry, my tests were done wrong. 1.8.0 already supports ^ constraints.

It also seems that we have already broken pre-1.8.0 dart, because as far as I can tell it parses the entire pubspec during resolution and fails hard when it sees a ^ constraint anywhere:

```
#/usr/bin/env bash

rm -rf cache pubspec.lock dart-sdk pubspec.yaml packages

wget $1 -O a.zip
unzip a.zip > /dev/null
trap "rm -rf  " EXIT
rm a.zip

cat << EOF > pubspec.yaml
name: ttt
dependencies:
  collection: any
EOF

PUB_CACHE=cache DART_SDK=dart-sdk dart-sdk/bin/pub --version
PUB_CACHE=cache DART_SDK=dart-sdk dart-sdk/bin/pub get
```
Call like
```
./script https://storage.googleapis.com/dart-archive/channels/stable/release/41096/sdk/dartsdk-linux-x64-release.zip # 1.7.2
```
And the output is:
```
--2022-11-14 14:20:46--  https://storage.googleapis.com/dart-archive/channels/stable/release/41096/sdk/dartsdk-linux-x64-release.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.184.128, 142.251.5.128, 66.102.1.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.184.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11363231 (11M) [application/zip]
Saving to: ‘a.zip’

a.zip                            100%[=========================================================>]  10.84M  13.3MB/s    in 0.8s    

2022-11-14 14:20:47 (13.3 MB/s) - ‘a.zip’ saved [11363231/11363231]

Pub 1.7.2
Resolving dependencies... 
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/collection/versions/1.17.0: Invalid version constraint: Could not parse version "^1.0.0". Unknown text at "^1.0.0".
```

Which indicates to me that pre-1.8.0 sdk's already are broken, and there is not much backwards compatibility we can maintain.

**Comment by jonasfj** [comment]
For reference the source code for 1.7.2 is in:
https://storage.googleapis.com/dart-archive/channels/stable/release/41096/linux_packages/debian_wheezy/dart_1.7.2.orig.tar.gz

**Comment by jonasfj** [comment]
I think our conclusion from tests and offline discussion is that this won't interfere with Dart 1.8.0 or later, and that earlier versions are already more or less unable to resolve dependencies -- unless there is a lockfile or versions are pinned.

That said, I think we should move forward with allowing caret syntax.

-------

If it becomes a problem for anyone we can tweak the `<hosted-url>/api/packages/<package>/versions/<version>` to always re-intepret version ranges as `>=... <...` instead of caret notation. That will allow old versions to solve.
And the end-point is also deprecated, so it should be fine to do:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md#deprecated-inspect-a-specific-version-of-a-package

**Comment by jonasfj** [comment]
This is fixed.
