### ISSUE TITLE
cmd     pub get     get  bad state

### ISSUE THREAD

**Issue by rukdm** [dart-lang/pub#2156]
Bad state: Origin is only applicable schemes http and https: d:%5Cflutter-1.7.1/api/packages/http

**Comment by jonasfj** [comment]
I need a bit more context:
  * Command line output use code fencing: https://help.github.com/en/articles/creating-and-highlighting-code-blocks
 * What are you trying to do?
 * What is the minimal pubspec causing this issue?

**Comment by jonasfj** [comment]
are you using a proxy?

**Comment by rukdm** [comment]
I need a HTTP plug-ins，When I using pub get，Get the error message

**Comment by jonasfj** [comment]
If you're in china, you'll likely need to use a VPN or the [Chinese community mirror](https://flutter.dev/community/china).

**Comment by rukdm** [comment]
fine
