### ISSUE TITLE
Possibility to disable setting the modification time of pubspec.lock

### ISSUE THREAD

**Issue by enyo** [dart-lang/pub#2158]
Since dart version `2.3.2` any command that runs `pub run` tries to update the modification time of `pubspec.lock`. I have no idea why this was introduced, but it is problematic in our CI environment, since all version control files are read only.

It would be great if this behaviour could be disabled.

**Comment by jonasfj** [comment]
If any one wants to find out if this was introduced by accident or intentionally for some reason, it might be a good idea to simply test it out on different revisions of this repository.

This could be a bug :)

**Comment by sigurdm** [comment]
Is this still a thing?

`pub run` is now deprecated

If you can reproduce this behavior with `dart run` please open a new issue with a reproduction.
