### ISSUE TITLE
Old url in pub publish

### ISSUE THREAD

**Issue by vinicentus** [dart-lang/pub#2162]
# Environment

- `pub version` or `flutter pub version`: 2.4.0
- OS version: Windows 10 1903
- Are you using the Chinese community mirror or a corporate firewall?
No.

# Problem

All the URLs aren't updated to the new pub.dev domain.

For example when I run

`pub publish`
The output starts with
Publishing package_name 1.0.0 to https://pub.dartlang.org:

There are probably more places where this should be fixed.

**Comment by jonasfj** [comment]
For now this is intentional...

See comments in the source for discussion... Just git grep for the domain name :)
