### ISSUE TITLE
pub get failed (1)

### ISSUE THREAD

**Issue by songyazhi** [dart-lang/pub#2163]
Running "flutter packages get" in flutter_app...                

The getter 'isEmpty' was called on null.
Receiver: null

Tried calling: isEmpty

dart:core                                   Object.noSuchMethod

package:path/src/style/windows.dart 40:14   WindowsStyle.rootLength

package:path/src/internal_style.dart 45:18  InternalStyle.getRoot

package:path/src/parsed_path.dart 43:22     new ParsedPath.parse

package:path/src/context.dart 1056:41       Context._parse

package:path/src/context.dart 125:18        Context.dirname

package:path/path.dart 173:40               dirname

package:pub/src/sdk/dart.dart 32:37         DartSdk._rootDirectory.<fn>

package:pub/src/sdk/dart.dart 35:4          DartSdk._rootDirectory

package:pub/src/sdk/dart.dart 27:23         DartSdk._rootDirectory

package:pub/src/sdk/dart.dart 47:31         DartSdk.rootDirectory

package:pub/src/io.dart 520:11              _sdkAssetPath
package:pub/src/io.dart 897:36              _pathTo7zip.<fn>
package:pub/src/io.dart 899:3               _pathTo7zip
package:pub/src/io.dart 896:14              _pathTo7zip
package:pub/src/io.dart 918:40              _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 815:20              withTempDir

===== asynchronous gap ===========================
package:pub/src/io.dart 909:10              _extractTarGzWindows
package:pub/src/io.dart 837:18              extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 310:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 204:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 374:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51            withDependencyType
package:pub/src/entrypoint.dart 370:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 231:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1)

**Comment by jonasfj** [comment]
What is the `dependencies` and `dev_dependencies` you're trying to get. Can you share parts of the pubspec?

Is this a persistent problem?

**Comment by songyazhi** [comment]
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by jonasfj** [comment]
Please see. https://help.github.com/en/articles/creating-and-highlighting-code-blocks
(I took the liberty of editing your comment to make it readable)

**Comment by jonasfj** [comment]
I had no problem running `flutter packages get`.

Are you behind a corporate firewall? or located in China?

**Comment by songyazhi** [comment]
Yes. I am in China.

**Comment by jonasfj** [comment]
@songyazhi, have you tried: https://flutter.dev/community/china ?

**Comment by songyazhi** [comment]
I have already set two environment variables,  but it still out of work.

**Comment by shukaka** [comment]
i meet the same error on arm64 based windows system
