### ISSUE TITLE
flutter packages get from git is not satisfied error

### ISSUE THREAD

**Issue by peiweioo** [dart-lang/pub#2169]
Bad state: [BUG] my_flutter_sdk <0.6.17-∞ or >0.6.17 from git is not satisfied.
package:pub/src/solver/partial_solution.dart 157:5                        PartialSolution.satisfier
package:pub/src/solver/version_solver.dart 254:27                         VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 131:27                         VersionSolver._propagate
package:pub/src/solver/version_solver.dart 96:9                           VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                         resolveVersions.<fn>
package:pub/src/log.dart 378:18                                           progress
package:pub/src/solver.dart 32:10                                         resolveVersions
package:pub/src/entrypoint.dart 203:24                                    Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                    GetCommand.run
package:args/command_runner.dart 194:27                                   CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                                PubCommandRunner.runCommand.<fn>
dart:async                                                                new Future.sync
package:pub/src/utils.dart 109:12                                         captureErrors.<fn>
dart:async                                                                runZoned
package:pub/src/utils.dart 126:5                                          captureErrors
package:pub/src/command_runner.dart 171:13                                PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                                PubCommandRunner.run
===== asynchronous gap ===========================
C:\b\s\w\ir\k\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter packages get" in flutter_portal...
pub get failed (1)

**Comment by jonasfj** [comment]
Please use code fences: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

Maybe include the relevant parts of the pubspec, preferably the minimal required to reproduce.

**Comment by sigurdm** [comment]
@peiweioo can you still reproduce this? A reproduction in the shape of a pubspec.yaml would be very appreciated.

**Comment by sigurdm** [comment]
Closing as stale.

Please comment if you can still reproduce.
