### ISSUE TITLE
Warn against 1.x.y+z packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#2171]
The Dart ecosystem has an unfortunate history of leaving packages with a major version of `0` for a long time. Starting with `1.0.0` the pattern should be `major.feature.patch` and a `+n` should never happen (sometimes a `-dev` or `-alpha.x` makes sense, but `+` is against convention). With a leading `0` we use a pattern like `0.major.feature+patch`. This has had the unfortunate effect of training the community to _always_ use `+patch` releases.

We could help train against this by warning whenever we see a `+` without a leading `0`.

**Comment by jonasfj** [comment]
When publishing `major.minor.patch` I've used `+1` to publish a new version with "packaging only changes". By that I mean fixing typos, updating a `CHANGELOG.md` messages. Things that are not code changes.

I'm not sure there is any value in this distinction :)

-------
If we want to take an opinion then perhaps we should discourage `build` numbers in all cases.
If you have `0.2.0` and you are making a tiny bug fix, then it seems saner to publish as `0.2.1` than `0.2.0+1`.

We don't really have builds, so maybe we should discourage build numbers completely. I guess some Flutter plugins might contain binary blobs that are indeed built. Packages for web might embed images?

**Comment by natebosch** [comment]
I'm not sure there is much value in differentiating patch level code changes from non code changes. From what I can tell the `+1` is more often caused by confusion than intention. We could also be careful with the wording to make it clear that it's OK to ignore if it is intentional.

**Comment by jonasfj** [comment]
Just some context, we actually do have a convention for using `+build` for `patch`, in `0.` versions.

https://github.com/dart-lang/site-www/blob/d16aec227c94b291ec80b5f62c122bbee5a859b7/src/tools/pub/versioning.md

> Although semantic versioning doesn't promise any compatibility between versions
prior to `1.0.0`, the Dart community convention is to treat those versions
semantically as well. The interpretation of each number is just shifted down one
slot: going from `0.1.2` to `0.2.0` indicates a breaking change, going to
`0.1.3` indicates a new feature, and going to `0.1.2+1` indicates a change that
doesn't affect the public API.

**Comment by sigurdm** [comment]
Do we still want to do this?

**Comment by natebosch** [comment]
I do still see this happen occasionally, but we are also making a bigger push to go to `1.x` package versions. I think it's a valid feature, but I can definitely see a strong argument for closing the issue as too low value to implement.

**Comment by sigurdm** [comment]
Yeah - I think I'll close as a won't-fix.
