### ISSUE TITLE
Avoid using gzip from the system

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2186]
This causes problems on OSX when pigz is installed, and the dart-sdk does ship with a gzip implementation already.

See: https://github.com/dart-lang/pub/issues/2126

**Comment by natebosch** [comment]
More discussion in https://github.com/dart-lang/pub/issues/1602

**Comment by jonasfj** [comment]
Yes, but even if we just used gzip provided with dart that might be an improvement on OS X where pigz is installed.

That said I generally agree we should do a tar-stream implementation in Dart.
