### ISSUE TITLE
Investigate what magic packages are and remove them if possible

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2188]
A quick trace didn't show anything that used this:

https://github.com/dart-lang/pub/blob/92b52682e8fc6eed9ef2e77ed890647f75570165/lib/src/package_name.dart#L35-L42

All the constructors that could set this to true appears to not be used. Hence, this can probably be removed.

**Comment by natebosch** [comment]
Yeah this looks like something left over from when pub was the build system and shouldn't impact anything to remove it.
