### ISSUE TITLE
Can't use package from path if it is a hosted sub-dependency

### ISSUE THREAD

**Issue by devxpy** [dart-lang/pub#2194]
- Pub 2.4.0
- Mac 10.14.4

Given the following dependency tree:
```
             root
              +
              |
              |
      +-------v--------+
      |                |
      |                |
      |                |
      v                v
 pkg1 (x.x.x)    pkg2 (path: ../pkg3)
     +
     |
     |
     |
     v
pkg2 (x.x.x)
```

Pub will complain:
```
$ flutter packages get
Because pkg1 >=x.x.x depends on pkg2 from hosted and root depends on pkg2 from path, pkg1 >=x.x.x is forbidden.
So, because root depends on pkg1 x.x.x, version solving failed.
pub get failed (1)
```

I am the author of pkg2, and want to test out a change I made, without publishing buggy code to pub. How do I achieve this?

Happy to provide tarball / git repo as example if needed.

**Comment by sigurdm** [comment]
You can use a dependency_override if you control the root: https://dart.dev/tools/pub/dependencies#dependency-overrides
