### ISSUE TITLE
Bump version of pubspec

### ISSUE THREAD

**Issue by JasCodes** [dart-lang/pub#2197]
Cli should allow to bump version major, minor build

Thx

**Comment by jonasfj** [comment]
Anything that mutates the `pubspec.yaml` will require:
 A) that we strip all formatting and comments
 B) That we write a library that modify YAML without throwing away all comments.

(A) has significant downsides as it's common to comment out `dependency_overrides` and other hacks used during development. But it might be what we end up doing.

If anyone is interested in taking on (B) writing an abstract syntax tree for YAML and support mutating it that would make adding this feature very easy.

**Comment by jascodes** [comment]
Or C we only parse out version key rather then fully implementing whole YAML implementation :stuck_out_tongue:

**Comment by jakemac53** [comment]
Parsing out the version key is harder than you would think - yaml has like a billion ways of doing the same thing.

That being said you could use the source code information from the parsed yaml to specifically edit that node without to much headache I think. I don't know if it is really worth doing though and would be a potential source of bugs and/or race conditions.

**Comment by jascodes** [comment]
@jacob314 You might be right, I might just going with sed command in my script. I know its no trivial task to implement full yaml spec in dart.

Thx

**Comment by jonasfj** [comment]
@jascodes, so @sigurdm suggested it might be possible by forking [dart-lang/yaml](https://github.com/dart-lang/yaml), extending the [scanner](https://github.com/dart-lang/yaml/blob/4d016bc3227621e329895db6504dfd78cd9fabca/lib/src/scanner.dart) to emit comments for which there is [currently no token type](https://github.com/dart-lang/yaml/blob/4d016bc3227621e329895db6504dfd78cd9fabca/lib/src/token.dart#L114-L139). Then it might be possible to write something that mutates the token stream and rebuild a YAML string from the token stream.
This would probably be a pain retain formatting, but if comments are retained that might be good enough :)
If anyone wants to give this approach a go, by all means raise your hand (I'm happy to give feedback/reviews, etc -- I suspect it'll be a bit of work).

**Comment by Levi-Lesches** [comment]
Check out the package [cider](https://pub.dev/packages/cider) on pub.dev. The `cider bump` command can bump any part of the version, such as: 
- breaking (means y for 0.y.z and x for x.y.z)
- major
- minor
- patch
- build
- pre (short for pre-release)

Here are a few sample commands: 

1. Read the current version
```
cider version
```
2. Change the version number to 1.2.3
  ```
  cider version 1.2.3
  ```
3. Bump to a new breaking version. For `1.2.3`, will update to `2.0.0`, and for `0.1.2`, will update to `0.2.0`
```
cider bump breaking
```
4. Bump the major version, regardless of pre-`1.0.0` releases
```
cider bump major
```

**Comment by sigurdm** [comment]
Note this has a WIP PR: https://github.com/dart-lang/pub/pull/2617 . Not sure when we'll get back to that...

**Comment by Levi-Lesches** [comment]
@sigurdm, If you want the `bump` functionality, why not just officially merge the `cider` package (or at least that part of it) into pub? As per https://github.com/f3ath/cider/issues/4, they fixed the issue of comments and formatting by simply using regex and not a YAML parser. @f3ath, what do you think?

**Comment by f3ath** [comment]
@Levi-Lesches I have no objection to merging any part of Cider code into pub, but regex (that's what Cider uses) does indeed seem too hacky for an official tool.

**Comment by sigurdm** [comment]
> but regex does indeed seem too hacky for an official tool.

Yeah - especially now that we have made the actual yaml-edit tool.
