### ISSUE TITLE
"pub run" should probably check .dart_tool/pub/bin/sdk-version

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2200]
Assuming `.dart_tool/pub/bin/sdk-version` exists precisely because snapshots are not portable across sdk versions, it would seem prudent of `pub run <package>:<executable> <args>` to check `.dart_tool/pub/bin/sdk-version` matches the current SDK, and if not recompile.
```
[pub]$dvm use 2.3.0
[pub]$pub get
Resolving dependencies...
Got dependencies!
Precompiling executables... (15.7s)
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
Precompiled test:test.
[pub]$ls -lh --full-time .dart_tool/pub/bin/build_runner/
total 40M
-rw-r----- 1 jonasfj primarygroup 22M 2019-09-03 23:38:38.569576668 +0200 build_runner.dart.snapshot.dart2
-rw-r----- 1 jonasfj primarygroup 19M 2019-09-03 23:38:36.909563414 +0200 graph_inspector.dart.snapshot.dart2
[pub]$dvm use 2.4.0
[pub]$pub run build_runner --help
...
[pub]$ls -lh --full-time .dart_tool/pub/bin/build_runner/
total 40M
-rw-r----- 1 jonasfj primarygroup 22M 2019-09-03 23:38:38.569576668 +0200 build_runner.dart.snapshot.dart2
-rw-r----- 1 jonasfj primarygroup 19M 2019-09-03 23:38:36.909563414 +0200 graph_inspector.dart.snapshot.dart2
```
I would have expected a precompilation after `pub run build_runner --help` above, as I changed the dart-sdk after `pub get`.

Maybe I'm missing something, because the above does seem to work in this case... so maybe snapshots sometimes work across dart SDK releases.

**Comment by jonasfj** [comment]
Note: we using script snapshots, which is probably why it works :)

**Comment by jakemac53** [comment]
Yes they are sometimes compatible (just not guaranteed to be so). I believe that pub has some sort of retry behavior already, so that if the isolate fails to spawn then it re-snapshots?

**Comment by sigurdm** [comment]
We now include the sdk version in the snapshot name.

Not sure it is the perfect solution - but at least this issue should not be relevant anymore.
