### ISSUE TITLE
pub install won't create a pubspec.yaml when none exists

### ISSUE THREAD

**Issue by paul-hammant** [dart-lang/pub#2205]
```
mkdir silly_dart_test
cd silly_dart_test
cat >test.dart <<EOL
void main() {
  print('Hello, World!');
}
EOL
dart test.dart

# this errors, which is arbitrary:

pub install intl
```

Yields:

```
Hello, World!
Could not find a file named "pubspec.yaml" in "path/to/silly_dart_test".
```

There's no pub-init to make the missing shim file.

'pub' should have pub-init, or silent creation of the file, not neither.

**Comment by jakemac53** [comment]
I don't think pub will ever create a pubspec.yaml - there are some questions around what package name it should fill in as well as what sdk constraint, description, homepage, etc. It could just use placeholder content but that will inevitably end up getting published on pub with packages if we make it to automatic...

**Comment by jonasfj** [comment]
Well, we could generate a pubspec with values that makes publishing impossible...
```yaml
name: <package-name>
```

But it might be better to simply print a message directing users at a tutorial or maybe `pub global activate stagehand`.

Putting templating into pub risks scope creep.

**Comment by paul-hammant** [comment]
Printing a message seems like a good idea.
