### ISSUE TITLE
Unable to Resolve dependencies...

### ISSUE THREAD

**Issue by Srinivas-Dolai** [dart-lang/pub#2210]
Working dir: C:\Users\lenovo\Desktop\codecanyon-24020929-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore-woo 1.4.1\source
C:\Dart\dart-sdk\bin\pub.bat get
Resolving dependencies...
The method 'contains' was called on null.
Receiver: null
Tried calling: contains("\\")
dart:core                                                            Object.noSuchMethod
package:pub/src/io.dart 788:41                                       _doProcess
package:pub/src/io.dart 687:16                                       runProcessSync
package:pub/src/source/git.dart 441:27                               BoundGitSource._cleanInvalidGitRepoCache
package:pub/src/source/git.dart 402:5                                BoundGitSource._ensureRepoCache
===== asynchronous gap ===========================
package:pub/src/source/git.dart 214:11                               BoundGitSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                   BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                     PackageLister._versions.<fn>.<fn>
dart:async                                                           runZoned
package:pub/src/http.dart 272:10                                     withDependencyType
package:pub/src/solver/package_lister.dart 75:33                     PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                           new Future.sync
package:async/src/async_memoizer.dart 43:42                          AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                     PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                    PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                    VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                    minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                    VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                     VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                    resolveVersions.<fn>
package:pub/src/log.dart 378:18                                      progress
package:pub/src/solver.dart 32:10                                    resolveVersions
package:pub/src/entrypoint.dart 203:24                               Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                               GetCommand.run
package:args/command_runner.dart 194:27                              CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                           PubCommandRunner.runCommand.<fn>
dart:async                                                           new Future.sync
package:pub/src/utils.dart 109:12                                    captureErrors.<fn>
dart:async                                                           runZoned
package:pub/src/utils.dart 126:5                                     captureErrors
package:pub/src/command_runner.dart 171:13                           PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                           PubCommandRunner.run
===== asynchronous gap ===========================
C:\b\s\w\ir\cache\builder\sdk\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace get

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Process finished with exit code 1

**Comment by Srinivas-Dolai** [comment]
Kindly help to resolve the dependencies:

Working dir: C:\Users\lenovo\Desktop\FluxStore-woo 1.4.4\source
C:\Dart\dart-sdk\bin\pub.bat get
Resolving dependencies...
The method 'contains' was called on null.
Receiver: null
Tried calling: contains("\\")
dart:core                                                            Object.noSuchMethod
package:pub/src/io.dart 788:41                                       _doProcess
package:pub/src/io.dart 687:16                                       runProcessSync
package:pub/src/source/git.dart 441:27                               BoundGitSource._cleanInvalidGitRepoCache
package:pub/src/source/git.dart 402:5                                BoundGitSource._ensureRepoCache
===== asynchronous gap ===========================
package:pub/src/source/git.dart 214:11                               BoundGitSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                   BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                     PackageLister._versions.<fn>.<fn>
dart:async                                                           runZoned
package:pub/src/http.dart 272:10                                     withDependencyType
package:pub/src/solver/package_lister.dart 75:33                     PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                           new Future.sync
package:async/src/async_memoizer.dart 43:42                          AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                     PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                    PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                    VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                    minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                    VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                     VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                    resolveVersions.<fn>
package:pub/src/log.dart 378:18                                      progress
package:pub/src/solver.dart 32:10                                    resolveVersions
package:pub/src/entrypoint.dart 203:24                               Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                               GetCommand.run
package:args/command_runner.dart 194:27                              CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                           PubCommandRunner.runCommand.<fn>
dart:async                                                           new Future.sync
package:pub/src/utils.dart 109:12                                    captureErrors.<fn>
dart:async                                                           runZoned
package:pub/src/utils.dart 126:5                                     captureErrors
package:pub/src/command_runner.dart 171:13                           PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                           PubCommandRunner.run
===== asynchronous gap ===========================
C:\b\s\w\ir\cache\builder\sdk\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace get

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Process finished with exit code 1

**Comment by jakemac53** [comment]
It looks like this is because the top level `command` getter in `git.dart` can return null https://github.com/dart-lang/pub/blob/cfa9dc760b6b601f9473e65d15f15b60a319336d/lib/src/git.dart#L72.

But it is never checked where it is used.

**Comment by jakemac53** [comment]
So basically I think that means it couldn't find `git` installed on  your machine @Srinivas-Dolai . Installing that should fix it?

**Comment by jonasfj** [comment]
This should be fixed in https://github.com/dart-lang/pub/pull/2209, so that we will display a proper error message again.
