### ISSUE TITLE
Require a major version bump to opt in to NNBD

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#2212]
When a package migrates to NNBD it will be a breaking API change (unless _every_ argument on _every_ publish signature has a `?`) but it won't always be clear to the author. It would be nice to have a publish time check that if a package has a min SDK allowing NNBD it doesn't share a major version with any published package with a wider SDK constraint.

cc @jakemac53

**Comment by jakemac53** [comment]
This. It will not be clear to all package authors that they are making a breaking change - even many members of the dart team didn't realize the implications.

It is really important that we help keep package authors on the rails here.
