### ISSUE TITLE
Issue while package get in pubspec.yaml

### ISSUE THREAD

**Issue by Unnikrishnanvenad** [dart-lang/pub#2213]
/Users/dart/Developer/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in mobile-app...                      
Error on line 482, column 9 of pubspec.lock: Invalid version constraint: Expected version number after "<" in "<empty>", got "empty>".
    ╷
482 │   dart: "<empty>"
    │         ^^^^^^^^^
    ╵
package:pub/src/lock_file.dart 189:7                                    LockFile._wrapFormatException
package:pub/src/lock_file.dart 175:12                                   LockFile._parseVersionConstraint

package:pub/src/lock_file.dart 116:13                                   LockFile._parse.<fn>

dart:collection                                                         MapView.forEach

package:pub/src/lock_file.dart 113:23                                   LockFile._parse

package:pub/src/lock_file.dart 78:21                                    new LockFile.load

package:pub/src/entrypoint.dart 92:28                                   Entrypoint.lockFile

package:pub/src/entrypoint.dart 204:19                                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                  GetCommand.run
package:args/command_runner.dart 194:27                                 CommandRunner.runCommand

===== asynchronous gap ===========================

package:pub/src/command_runner.dart 171:39                              PubCommandRunner.runCommand.<fn>

dart:async                                                              new Future.sync

package:pub/src/utils.dart 109:12                                       captureErrors.<fn>

dart:async                                                              runZoned

package:pub/src/utils.dart 126:5                                        captureErrors

package:pub/src/command_runner.dart 171:13                              PubCommandRunner.runCommand

===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                              PubCommandRunner.run
===== asynchronous gap ===========================
/b/s/w/ir/k/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (65)
Process finished with exit code 65

**Comment by jonasfj** [comment]
Can you try `flutter pub pub --trace get` and drop the log...

Also, if possible, can you share your `pubspec.yaml` and `pubspec.lock`, I'm curious to see what they look like. If we have  `dart: ""` in the `pubspec.lock` that suggests a possible bug.

-----

Side note. Please paste with [code fences](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to link to a [gist](https://gist.github.com).

**Comment by Unnikrishnanvenad** [comment]
Thanks for your reply i fixed my issue with flutte package upgrade

**Comment by Unnikrishnanvenad** [comment]
> Can you try `flutter pub pub --trace get` and drop the log...
> 
> Also, if possible, can you share your `pubspec.yaml` and `pubspec.lock`, I'm curious to see what they look like. If we have `dart: ""` in the `pubspec.lock` that suggests a possible bug.
> 
> Side note. Please paste with [code fences](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to link to a [gist](https://gist.github.com).

Thanks for your time .
