### ISSUE TITLE
Consider making a missing dependency an error and not a warning

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2214]
See https://github.com/dart-lang/sdk/issues/38482 and https://github.com/dart-lang/sdk/issues/38483 for recent problems regarding this.

Currently pub allows you to publish a package that is known to have fatal errors (missing dependencies).

I would like to propose making those errors, so that publishing would not be allowed at all in that case.

**Comment by jonasfj** [comment]
Yeah, this seems like a solid warning.

I suspect there could be cases where such imports are intentionally ignored.
Say if `package:my_pkg/use_with_other_pkg.dart` imports `other_pkg`, but is only intended to be used if `other_pkg` is already a dependency. For such cases, we won't have proper versioning constraints since we don't support `peerDependencies`/`optionalDependencies`, so forbidding this behavior seems reasonable.

**Comment by jakemac53** [comment]
Ya I really don't think there are any valid use cases here.

**Comment by mit-mit** [comment]
Marking high pri as this affects the overall stability of the package system

**Comment by jakemac53** [comment]
Fwiw I ran a test using `pub_crawl` and `surveyor` to check how many strict deps errors exist in a random sampling of around 1000 existing pub packages, and here is the output:

```
Found 18 packages with strict deps errors (out of 1008 total analyzed packages).
The package amplitude_flutter_example is missing the following deps {amplitude_flutter}
The package appmetrica_sdk_example is missing the following deps {appmetrica_sdk}
The package artemis is missing the following deps {glob, dart_style}
The package auto_animated_example is missing the following deps {auto_animated}
The package essential_components is missing the following deps {http}
The package example is missing the following deps {angular_forms}
The package flutter_local_notifications_example is missing the following deps {flutter_local_notifications}
The package fluxmap_example is missing the following deps {device, flutter_map, geopoint, latlong, map_controller, pedantic}
The package flutter_map_demo is missing the following deps {latlong, geopoint, pedantic}
The package example is missing the following deps {bloc}
The package example is missing the following deps {flutter_map, latlong, pedantic}
The package r_flutter is missing the following deps {glob}
The package sass is missing the following deps {js}
The package sass_migrator is missing the following deps {js}
The package signalr_core is missing the following deps {meta}
The package sqflite_example is missing the following deps {matcher, pedantic, synchronized, meta}
The package tencent_kit_example is missing the following deps {tencent_kit}
The package xmpp_stone is missing the following deps {meta}
```

These are primarily all red herrings (examples which aren't actually published but are analyzed by surveyor), with a few legitimate failures that would all be easy to fix.

I am going to go ahead and send out a PR for at least the client side validation part of this since its trivial to change.

**Comment by jakemac53** [comment]
I don't have a sense of how difficult the validation for this would be to implement on the server side or if we have much existing server side validation at all - feel free to close if we think the client side validation is sufficient.

**Comment by jonasfj** [comment]
Consistency between server and client side acceptance checks is something we're slowly working towards, but not tracking on a per-check basis.
