### ISSUE TITLE
flutter pub upgrade 

### ISSUE THREAD

**Issue by AhmedAlaa96** [dart-lang/pub#2215]
I'm trying to upgrade dependencies in darts
but always get :
Could not resolve URL "https://pub.dartlang.org".
pub upgrade failed (69) -- attempting retry 1 in 1 seconds...

I have manual proxy to connect to my network

**Comment by jonasfj** [comment]
Check out docs for proxy configuration:
https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall
