### ISSUE TITLE
Could not resolve URL "https://pub.dartlang.org".

### ISSUE THREAD

**Issue by AhmedAlaa96** [dart-lang/pub#2217]
I can't  download lib in **pubspec.yaml** 

I tried to run `flutter pub get` and get this error 

> Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

![2](https://user-images.githubusercontent.com/17764800/65899723-9b432c80-e3b4-11e9-903d-c91c51721561.PNG)
when I try check connection because I have a manual proxy get connectio9n successful 
![1](https://user-images.githubusercontent.com/17764800/65899774-ba41be80-e3b4-11e9-9bbd-26d5904cdd2f.PNG)
I deactivate my firewall and windows defender protection but nothing happend

**Comment by jonasfj** [comment]
https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

I don't think this works with proxy from Android Studio.
That might be a bug worth filing against the Android studio plugin for Flutter/Dart

**Comment by AhmedAlaa96** [comment]
@jonasfj  That's work for me thank you

**Comment by jonasfj** [comment]
This is already filed in https://github.com/flutter/flutter-intellij/issues/2914

**Comment by string-MFathi** [comment]
Just check if your are connected to internet and run again

**Comment by leah25** [comment]
@string-MFathi yes that worked for me. Thank you

**Comment by yoga-viss** [comment]
> https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall
> 
> I don't think this works with proxy from Android Studio.
> That might be a bug worth filing against the Android studio plugin for Flutter/Dart

really helped thank you
