### ISSUE TITLE
pub get not working on my windows

### ISSUE THREAD

**Issue by yesyesyesyesyesyesyesyesyesyes** [dart-lang/pub#2218]
[New Text Document.txt](https://github.com/dart-lang/pub/files/3678584/New.Text.Document.txt)

**Comment by jonasfj** [comment]
Are you behind a proxy: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

Or located in china: https://flutter.dev/community/china

Or Nigeria, we have some users who report network issues from there.

**Comment by HusamiRami** [comment]
I tried with and without using vpn. Same results
I'm located in Syria

**Comment by sigurdm** [comment]
Closing this as stale.

For general troubles with reaching pub.dev you could try using the chinese community mirror: https://flutter.dev/community/china .
