### ISSUE TITLE
Publish an ignored file to Pub

### ISSUE THREAD

**Issue by dmdashenkov** [dart-lang/pub#2222]
I'm trying to publish my first Pub package.

[The doc](https://dart.dev/tools/pub/publishing#what-files-are-published) states that the files under `.gitignore` are not published.

My question is: is there a way to work around the `.gitignore` and publish the files which are not on Git?

Background: I'm working with code generation and generating Dart from Protobuf. It's not ideal to store generated sources in Git (it looks ugly and distorts the viewers from the real source code which implements some logic).

I can always copy the required files into a separate directory and publish from there instead. However, it'be nice to avoid that.

However, the coupling between Git and Pub seems a bit odd. I'm sure that a reverse situation (when something is on Git and should now be published to Pub) is even more common.

**Comment by jonasfj** [comment]
There is no workaround at this point. My suggestion would be to check the generated code into source control.

It's ugly, but it also means that you only have to re-generate the files when the input change. It makes it easier for new developers joining your project.

That said, this is something we could solve with a `.pubignore` file or an `ignores` section in `pubspec.yaml` which overrides the behavior of `.gitignore`. But I have mixed feelings about that.

**Comment by dmdashenkov** [comment]
@jonasfj, thanks for the suggestion.

For now, I'll stick to the workaround of copying the required source files into a separate directory and publishing from there. With a little scripting, it's a pretty robust approach.

Though, if this feature is implemented in future, I will most certainly use it.

**Comment by natebosch** [comment]
Note that within the Dart team we always track all published files in git. We also tag commits with the version number when we publish. This means that we can visit the git repo and see exactly what is published for a given version without downloading the archiver from pub to see the source files.

**Comment by jonasfj** [comment]
@natebosch, yeah, I think that's a good answer to this problem.
Probably we could even score packages that match a tag in github higher, though we'd need to solve mono-repo resolution in the process :)

**Comment by mveroukis** [comment]
Really? .gitignore should be just for git, not for build or publish tools. So I guess another solution is to just not use git at all. Honestly, this is terrible. There should be a .publishignore file or something, and let the developers do things their way. Shit like this that really makes me hate software development.

**Comment by sigurdm** [comment]
@mveroukis please update your message to use kinder language. Even though you are frustrated we need to keep a sober tone.

**Comment by sigurdm** [comment]
Also to your question there is now the possibility to put a .pubignore file in folders which override the .gitignore file in the same folder for pubs consideration.
