### ISSUE TITLE
Using Dart in China

### ISSUE THREAD

**Issue by cheblin** [dart-lang/pub#2229]
guys, **have you ever tested** your package dependency manager on how it behaves in bad environment?  What if connection is interrupted? 
Just try on **a second** pullout the Ethernet cable, when you package manager downloading dependencies.
It just hangs!
Do not even trying to reconnect, even the connection became available and shows something like this

 

> Resolving dependencies ...
> + analyzer 0.38.5
> + args 1.5.2
> + async 2.4.0
> + boolean_selector 1.0.5
> + charcode 1.1.2
> + collection 1.14.12
> + convert 2.1.1
> + coverage 0.13.3
> + crypto 2.1.3
> + csslib 0.16.1
> + front_end 0.1.27
> + glob 1.2.0
> + html 0.14.0 + 3
> + http 0.12.0 + 2
> + http_multi_server 2.1.0
> + http_parser 3.1.3
> + io 0.3.3
> + js 0.6.1 + 1
> + kernel 0.3.27
> + logging 0.11.3 + 2
> + matcher 0.12.5
> + meta 1.1.7
> + mime 0.9.6 + 3
> + multi_server_socket 1.0.2
> + node_interop 1.0.3
> + node_io 1.0.1 + 2
> + node_preamble 1.4.8
> + package_config 1.1.0
> + package_resolver 1.0.10
> + path 1.6.4
> + pedantic 1.8.0 + 1
> + pool 1.4.0
> + pub_semver 1.4.2
> + shelf 0.7.5
> + shelf_packages_handler 1.0.4
> + shelf_static 0.2.8
> + shelf_web_socket 0.2.3
> + source_map_stack_trace 1.1.5
> + source_maps 0.10.8
> + source_span 1.5.5
> + stack_trace 1.9.3
> + stream_channel 2.0.0
> + string_scanner 1.0.5
> + term_glyph 1.1.0
> + test 1.9.2
> + test_api 0.2.9
> + test_core 0.2.13
> + typed_data 1.1.6
> + vm_service 1.2.0 (2.1.1 available)
> + watcher 0.9.7 + 12
> + web_socket_channel 1.1.0
> + yaml 2.2.0
> Downloading front_end 0.1.27 ...
> Connection closed while receiving data
> Process finished with exit code 69

**The same problem with your installer**

This is especially noticeable if you in China. Since all active cross-border traffic periodically interrupted by grate Chinese firewall.
It's make impossible to use Dart just because of the fact that the package manager is written poorly

Please fix it.

**Comment by jonasfj** [comment]
I guess it might be the Flutter installer, please have a look at:
https://flutter.dev/community/china

**Comment by cheblin** [comment]
> I don't know of any Dart installer. Can you point me to what you mean?
I mean [both cases](https://dart.dev/get-dart)  They are downloading some zip and are stuck if connection is interrupted for moment.

**Comment by jonasfj** [comment]
Can we limit this issue to being `pub` related and move discussion of the installer somewhere else.

We generally have a hard time simulating network conditions in China. From what little I've come to understand I suspect that `https://storage.googleapis.com/` is blocked in China, how it's blocked, whether it's streaming slowly or breaks the connection is unclear to me.

But yes, we should provide better error messages for when HTTPS connections to our servers are not possible.

**Comment by cheblin** [comment]
>We generally have a hard time simulating network conditions in China

just pullout Ethernet cable for a 5 seconds, and return it back. that's it.

and yes, problem with downloading dependencies much more concern.
is it retrying to get the stuff? can it continue downloading or it always start from beginning?

**Comment by jonasfj** [comment]
> is it retrying to get the stuff? 

Yes, it should be :)

See `_download` uses `httpClient`.
https://github.com/dart-lang/pub/blob/dfb49792c5194c1249e67586178ae57b62ef448a/lib/src/source/hosted.dart#L314-L333

And `httpClient` is a wrapped `RetryClient`.
https://github.com/dart-lang/pub/blob/dfb49792c5194c1249e67586178ae57b62ef448a/lib/src/http.dart#L223-L225

If the TCP connection is kept alive but data isn't allowed to flow, then `package:http` has a bug where it doesn't time out. So maybe that's what happens, but that would be different from unplugging the ethernet cable.

**Comment by natebosch** [comment]
> then `package:http` has a bug where it doesn't time out.

I think `http` is intentionally unopinionated about timeouts. If you want to use the timeout feature from `HttpClient` in `dart:io`, construct one of those and use it to create the `http.IoClient`.

**Comment by sigurdm** [comment]
We have improved our retries, so I believe this should work much better.

Please open a new issue if your downloads do not get retried.
