### ISSUE TITLE
Change pub registry

### ISSUE THREAD

**Issue by mm44m6** [dart-lang/pub#2230]
I'm trying to use Flutter in my company but we have a security policy that doesn't allow us to use a public registry only an internal one (we're using Artifactory) to download packages. I searched how to change pubspec.yaml to get dependencies from a different registry but couldn't find anything helpful. What I was thinking was a feature like npm has, where I can use `npm set registry` and just change it to whatever I need.
Is there a way to accomplish this?

**Comment by jonasfj** [comment]
See: https://dart.dev/tools/pub/dependencies#hosted-packages

You can reference other registries in your pubspec, or you can set `PUB_HOSTED_URL` environment variable.

**Comment by jonasfj** [comment]
Also there is: https://pub.dev/packages/mpp which makes it easy to run a custom pub server.
There are other pub servers out there too.
