### ISSUE TITLE
pubspec.lock: Invalid version constraint: Expected version number after "<" in "<empty>", got "empty>".

### ISSUE THREAD

**Issue by Sachinsowri** [dart-lang/pub#2246]
i worked  a project in beta version now I  upgrade the flutter stabe version and reopen the same project i got given below error  while flutter package get 

Error on line 596, column 9 of pubspec.lock: Invalid version constraint: Expected version number after "<" in "<empty>", got "empty>".

    ╷
596 │   dart: "<empty>"

    │         ^^^^^^^^^

    ╵

package:pub/src/lock_file.dart 189:7                                    LockFile._wrapFormatException
package:pub/src/lock_file.dart 175:12                                   LockFile._parseVersionConstraint
package:pub/src/lock_file.dart 116:13                                   LockFile._parse.<fn>

dart:collection                                                         MapView.forEach
package:pub/src/lock_file.dart 113:23                                   LockFile._parse

package:pub/src/lock_file.dart 78:21                                    new LockFile.load
package:pub/src/entrypoint.dart 92:28                                   Entrypoint.lockFile

package:pub/src/entrypoint.dart 204:19                                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================

package:pub/src/command/get.dart 41:23                                  GetCommand.run

package:args/command_runner.dart 194:27                                 CommandRunner.runCommand
===== asynchronous gap ===========================

package:pub/src/command_runner.dart 171:39                              PubCommandRunner.runCommand.<fn>

dart:async                                                              new Future.sync

package:pub/src/utils.dart 109:12                                       captureErrors.<fn>
dart:async                                                              runZoned
package:pub/src/utils.dart 126:5                                        captureErrors
package:pub/src/command_runner.dart 171:13                              PubCommandRunner.runCommand

===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                              PubCommandRunner.run
===== asynchronous gap ===========================

/b/s/w/ir/k/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8:22  main

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (65)
exit code 65

how to Solve this issue i tried flutter packages upgrade also but still i got this error

**Comment by jonasfj** [comment]
What does your `pubspec.yaml` look like?

**Comment by Sachinsowri** [comment]
> What does your `pubspec.yaml` look like?

 this is solved

Rename The pubspec.lock

and run this cmd flutter --no-color packages get
