### ISSUE TITLE
flutter HTTP error 403: forbidden on some packages

### ISSUE THREAD

**Issue by N-Razzouk** [dart-lang/pub#2251]
Hi there...

Sorry for being troublesome but whenever I run 'flutter packages get' I get 'HTTP error 403: forbidden' and a list of failed get requests with asynchronous gap lines in between...

and the weirdest part about it is.... only for some packages... for example it never did that on the cupertino icons package... and now, after a little bit of experimentation it doesn't show an error on 'http' or 'english_words'... whereas 'google_sign_in' and 'audioplayers' for example show the 403 error... 

Could anyone help, please? 
Thank you very much :)

**Comment by jonasfj** [comment]
Are you behind a proxy: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

In china? Or Nigeria, a few people have reported network errors here.

**Comment by sigurdm** [comment]
Closing as stale
