### ISSUE TITLE
Ignore git submodules on publish

### ISSUE THREAD

**Issue by pd4d10** [dart-lang/pub#2255]
# Environment

- `pub version` or `flutter pub version`: 2.5.0
- OS version: macOS 10.15
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

According to [this documentation](https://dart.dev/tools/pub/publishing#what-files-are-published), all files version controlled by git will be published to Pub.

It there a way to ignore git submodules?

For example, in [my project](https://github.com/pd4d10/flutter-vector-icons), the submodule([react-native-vector-icons](https://github.com/pd4d10/flutter-vector-icons/tree/master/vendor), written in JavaScript) is only for Dart code generation. Seems it should not be published to Pub.

**Comment by jonasfj** [comment]
No, there is no support for pub-specific ignore patterns at this point.

You can make a bash script that wraps `pub publish` and copies everything you want to publish into a separate folder.

> According to this documentation, all files version controlled by git will be published to Pub.

Close, but not quite. The documentation says that all files ignored by `.gitignore` will be ignored by `pub publish`. It will publish files in your folder that are not under git control, if they are not in your `.gitignore` file.

**Comment by jonasfj** [comment]
I think this is somewhat similar to: https://github.com/dart-lang/pub/issues/2222

**Comment by pd4d10** [comment]
OK, get it. Let's track this in #2222. Closing
