### ISSUE TITLE
pub clean

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/pub#2267]
Please, add a command to `pub` to clean the project.

Build and dependencies sometimes doesn't work, specially when you move workspace from a computer to another.

Common commands to other build environments can help:

- pub clean: to clean all current project directory build files.
- pub refresh-dependencies: to clean and rebuild all the dependencies and build of the current project.

**Comment by gmpassos** [comment]
```
rm -rf .dart_tool
pub get
```

**Comment by sigurdm** [comment]
If we really wanted this it should be `dart clean` as other tools might put stuff in `.dart_tool`.

I think we won't do this.
