### ISSUE TITLE
Issue of installing Sass

### ISSUE THREAD

**Issue by chiweilin830908** [dart-lang/pub#2271]
# Environment

- `pub version` or `flutter pub version`: no idea
- OS version: 10.14.2
- Are you using the Chinese community mirror or a corporate firewall? I am in Shanghai, China. But I use Astrill as the VPN

# Problem
Homebrew and dart 2.6.1 already installed, but I can't install sass by running `brew install sass/sass/sass`

Here's the screenshot from the terminal:
<img width="949" alt="Screen Shot 2019-12-03 at 6 20 36 AM" src="https://user-images.githubusercontent.com/49460434/70000031-0bc52000-1595-11ea-87cb-a2c2f6f56381.png">

Have already reported this issue at https://github.com/sass/homebrew-sass/issues/26#issuecomment-560548055

<img width="902" alt="Screen Shot 2019-12-03 at 6 22 03 AM" src="https://user-images.githubusercontent.com/49460434/70000104-3d3deb80-1595-11ea-996f-4d92099bc35c.png">

I am pretty new to this knowledge, appreciate if anyone can help.

```yaml
<copy/paste pubspec.yaml>
```

## --trace output

```
<copy/paste the full output>
```

**Comment by jonasfj** [comment]
This could be anything mac specific... Maybe you have installed / overwritten the default `tar` / `gunzip`.

To debug this further you'll need to install the dart-sdk and paste log from running `pub global activate sass`.

**Comment by marshalc** [comment]
I have also just encountered this install issue (and followed the thread from <https://github.com/sass/homebrew-sass/issues/26#issuecomment-560548055>).

```
➜  ~ brew install sass/sass/sass
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 10 formulae.

==> Installing sass from sass/sass
==> Tapping dart-lang/dart
Cloning into '/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart'...
remote: Enumerating objects: 1837, done.
remote: Total 1837 (delta 0), reused 0 (delta 0), pack-reused 1837
Receiving objects: 100% (1837/1837), 336.73 KiB | 1.11 MiB/s, done.
Resolving deltas: 100% (1127/1127), done.
Tapped 15 formulae (41 files, 439.2KB).
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/2.10.4/sdk/dartsdk-macos-x64-release.zip
######################################################################## 100.0%
==> Downloading https://github.com/sass/dart-sass/archive/1.30.0.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/1.30.0
##O#- #                                                                       
==> Installing dependencies for sass/sass/sass: dart-lang/dart/dart
==> Installing sass/sass/sass dependency: dart-lang/dart/dart
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec
==> Summary
🍺  /usr/local/Cellar/dart/2.10.4: 510 files, 429MB, built in 6 seconds
==> Installing sass/sass/sass
==> /usr/local/opt/dart/bin/pub get
Last 15 lines from /Users/carl/Library/Logs/Homebrew/sass/01.pub:
2020-12-24 14:54:50 +0000

/usr/local/opt/dart/bin/pub
get

Resolving dependencies...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

➜  ~ 
```

Google's most referenced results on a similar error come from Flutter <https://github.com/flutter/flutter/issues/71483> 

The overlaps I noted here are that I'm on Big Sur (macOS 11.1) and have AdGuard <https://adguard.com/> installed - though the AdGuard log shows no calls being blocked from the install process - only calls from Safari, so this seems off target.

Unfortunately I'm entirely unfamiliar with Dart, and I'm not seeing an SDK package in Homebrew's library - thus `pub` doesn't exist as a command to get extra data as suggested above.

I will note that I've been able to successfully install this (`sass/sass/sass`) package successfully on another Big Sur machine, so I would conclude this is somehow related to the build order... in which case I'll also post this back into the `homebrew-sass` thread also.

**Comment by sigurdm** [comment]
This is an old issue. Does it still reproduce?

**Comment by sigurdm** [comment]
Closing as stale.

Please comment or open a new issue if this is still happening.
