### ISSUE TITLE
Because e_commerce_app depends on cloud_firestore >=0.13.0+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed. pub get failed (1) exit code 1

### ISSUE THREAD

**Issue by sifatullahshah1** [dart-lang/pub#2282]
I am adding 
cloud_firestore: ^0.13.0+1      to pubspac.yml file for cloud firestore but giving me below error

Because e_commerce_app depends on cloud_firestore >=0.13.0+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
pub get failed (1)
exit code 1

**Comment by jonasfj** [comment]
Assuming you have Flutter versions less than `1.10` then this error seems very reasonable.

You can upgrade flutter, or loosen ypur constraint on `^0.13.0+1`.
