### ISSUE TITLE
Feature Request: Option to disable strict SSL 

### ISSUE THREAD

**Issue by PaulHMason** [dart-lang/pub#2283]
I'm behind a corporate firewall the uses a self-signed certificate for SSL interception which breaks pub for Dart and Flutter. I haven't been able to get any of the proposed solutions to work (proxy and certificate path). Other package managers (npm and bower) offer the option to disable strict SSL - would it not be possible to do this with pub as well?

**Comment by kiran-cmyk** [comment]
Hi Paul, Did you find any workaround to resolve this issue?

**Comment by PaulHMason** [comment]
> Hi Paul, Did you find any workaround to resolve this issue?

Unfortunately not - I've tried all the things with certificate paths that I've found, but nothing works. It pretty much puts Flutter out of the running for me.

**Comment by jonasfj** [comment]
Have you tried: `DART_VM_OPTIONS="--root-certs-file=path/to/cert.pem"`

So set environment variables: `https_proxy`, `http_proxy` (see [Troubleshooting pub](https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall))

And environment variable `DART_VM_OPTIONS="--root-certs-file=path/to/cert.pem"`.

Before doing `pub run`, `flutter pub get` or `flutter packages get`. Is the certificate PEM encoded?

What OS are you on?

-----------
I think adding a `--ca-file=path/to/file.pem` flag to `pub` would be more reasonable (I think that's what motivated https://github.com/flutter/flutter/issues/56607).
Allowing users to disable TLS outright seems dangerous... From what I can see npm currently advocates a config option to set a custom certificate.

**Comment by sigurdm** [comment]
Closing as stale as there was no response.

Please open a new issue if this is still a problem, and the suggestion above didn't help.
