### ISSUE TITLE
docuementation for dependency_override needs improvements.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#2285]
I've been trying to use dependency_overrides and have had some difficulty using it as the documentation is inadequate.

The documentation needs to be updated to clearly state:

1) dependency_overrides affect both dependencies and dev_dependencies
2) How the overrides are treated by pub publish
 -- I'm guessing that when published the overrides are ignored.
3) when exactly are the overrides used
4) when exactly are the overrides not used
5) the documentation should cover how the likes of travis treats the overrides.

**Comment by jonasfj** [comment]
Similar to https://github.com/dart-lang/pub/issues/2117

**Comment by bsutton** [comment]
> I think this is besides the point. It affects all packages in the resolution (also transitive dependencies).

Given that I as an experience dart developer, didn't realise it covered transitive dependencies, I would argue that it should be covered.
I shouldn't have to guess how a system works.

**Comment by sigurdm** [comment]
The first sentence of the documentation says:

> You can use dependency_overrides to temporarily override all references to a dependency.

How should we phrase it differently?

**Comment by sigurdm** [comment]
Please open a new issue with suggestions for further improvements.
