### ISSUE TITLE
pub get failed when loading new package

### ISSUE THREAD

**Issue by sanjidtt** [dart-lang/pub#2288]
URL: https://dartlang-pub-dev.appspot.com/

When using new packages in pubspec.yaml, it shows 

Error: (OS Error: The semaphore timeout period has expired.
, errno = 121, address = storage.googleapis.com, port = 52465
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
).

The new package is " carousel_slider " in this case

If new package is commented and Packages get is clicked then it runs successfully
![Annotation 2020-01-02 123404](https://user-images.githubusercontent.com/40223567/71654492-466cd480-2d5c-11ea-9b80-f113f9d90572.png)

**Comment by jonasfj** [comment]
Seems most likely related to `pub` command line tool, hence, transferred the issue.

**Comment by jonasfj** [comment]
try running `flutter pub get --trace`

**Comment by sanjidtt** [comment]
> try running `flutter pub get --verbose`

After running `flutter pub get --verbose` in terminal the following is shown in terminal { It goes on and on .... }

[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +16 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.11
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.6.4
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on image 2.1.4
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on quiver 2.0.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.3
[  +14 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on archive 2.0.11
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on args 1.5.2
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.4.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 1.0.5
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.2
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on convert 2.1.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on crypto 2.1.3
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.6
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.1.8
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on pedantic 1.8.0+1
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on petitparser 2.4.0
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.5.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
[   +2 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
[   +3 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.1.6
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on xml 3.5.0
[   +1 ms] SLVR:     selecting flutter_test 0.0.0 from sdk
[   +1 ms] SLVR:     derived: xml 3.5.0
[   +1 ms] SLVR:     derived: typed_data 1.1.6
[        ] SLVR:     derived: term_glyph 1.1.0
[        ] SLVR:     derived: string_scanner 1.0.5
[        ] SLVR:     derived: stream_channel 2.0.0
[        ] SLVR:     derived: source_span 1.5.5
[        ] SLVR:     derived: petitparser 2.4.0
[  +12 ms] SLVR:     derived: pedantic 1.8.0+1
[   +1 ms] SLVR:     derived: meta 1.1.8
[        ] SLVR:     derived: matcher 0.12.6
[        ] SLVR:     derived: crypto 2.1.3
[   +1 ms] SLVR:     derived: convert 2.1.1
[        ] SLVR:     derived: collection 1.14.11
[        ] SLVR:     derived: charcode 1.1.2
[        ] SLVR:     derived: boolean_selector 1.0.5
[        ] SLVR:     derived: async 2.4.0
[        ] SLVR:     derived: args 1.5.2
[        ] SLVR:     derived: archive 2.0.11
[        ] SLVR:     derived: vector_math 2.0.8
[   +1 ms] SLVR:     derived: stack_trace 1.9.3
[   +1 ms] SLVR:     derived: quiver 2.0.5
[        ] SLVR:     derived: image 2.1.4
[        ] SLVR:     derived: path 1.6.4
[        ] SLVR:     derived: test_api 0.2.11
[        ] SLVR:     fact: http 0.12.0+3 depends on async >=1.10.0 <3.0.0
[        ] SLVR:     fact: http 0.12.0+3 depends on http_parser >=0.0.1 <4.0.0
[        ] SLVR:     fact: http 0.12.0+3 depends on path >=0.9.0 <2.0.0
[        ] SLVR:     fact: http 0.12.0+3 depends on pedantic ^1.0.0
[   +1 ms] SLVR:       selecting http 0.12.0+3
[        ] SLVR:       derived: http_parser >=0.0.1 <4.0.0
[        ] SLVR:       fact: firebase_core 0.4.3+1 depends on firebase_core_platform_interface ^1.0.0
[        ] SLVR:       fact: firebase_core 0.4.3+1 depends on flutter any from sdk
[        ] SLVR:       fact: firebase_core 0.4.3+1 depends on meta ^1.0.5
[        ] SLVR:       fact: firebase_core 0.4.3+1 depends on firebase_core_web ^0.1.1
[   +1 ms] SLVR:         selecting firebase_core 0.4.3+1
[        ] SLVR:         derived: firebase_core_web ^0.1.1
[        ] SLVR:         derived: firebase_core_platform_interface ^1.0.0
[        ] SLVR:         fact: firebase_auth 0.15.3 depends on meta ^1.0.4
[   +2 ms] SLVR:         fact: firebase_auth 0.15.3 depends on firebase_core ^0.4.0
[   +1 ms] SLVR:         fact: firebase_auth 0.15.3 depends on firebase_auth_platform_interface ^1.1.1
[   +1 ms] SLVR:         fact: firebase_auth 0.15.3 depends on firebase_auth_web ^0.1.1
[        ] SLVR:         fact: firebase_auth 0.15.3 depends on flutter any from sdk
[        ] SLVR:           selecting firebase_auth 0.15.3
[        ] SLVR:           derived: firebase_auth_web ^0.1.1
[        ] SLVR:           derived: firebase_auth_platform_interface ^1.1.1
[        ] SLVR:           fact: cloud_firestore 0.13.0+1 depends on flutter any from sdk
[        ] SLVR:           fact: cloud_firestore 0.13.0+1 depends on meta ^1.0.5
[        ] SLVR:           fact: cloud_firestore 0.13.0+1 depends on collection ^1.14.3
[        ] SLVR:           fact: cloud_firestore 0.13.0+1 depends on firebase_core ^0.4.0
[        ] SLVR:             selecting cloud_firestore 0.13.0+1
[        ] SLVR:               selecting cupertino_icons 0.1.3
[        ] SLVR:               fact: flutter 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:               fact: flutter 0.0.0 from sdk depends on meta 1.1.8
[        ] SLVR:               fact: flutter 0.0.0 from sdk depends on typed_data 1.1.6
[        ] SLVR:               fact: flutter 0.0.0 from sdk depends on vector_math 2.0.8
[        ] SLVR:               fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:                 selecting flutter 0.0.0 from sdk
[   +2 ms] SLVR:                 derived: sky_engine any from sdk
[        ] SLVR:                 fact: xml 3.5.0 depends on petitparser ^2.3.0
[        ] SLVR:                 fact: xml 3.5.0 depends on collection ^1.14.0
[        ] SLVR:                 fact: xml 3.5.0 depends on convert ^2.1.0
[        ] SLVR:                   selecting xml 3.5.0
[        ] SLVR:                     selecting typed_data 1.1.6
[        ] SLVR:                       selecting term_glyph 1.1.0
[        ] SLVR:                       fact: string_scanner 1.0.5 depends on charcode ^1.1.0
[   +1 ms] SLVR:                       fact: string_scanner 1.0.5 depends on meta ^1.1.0
[        ] SLVR:                       fact: string_scanner 1.0.5 depends on source_span ^1.4.0
[        ] SLVR:                         selecting string_scanner 1.0.5
[        ] SLVR:                         fact: stream_channel 2.0.0 depends on async >=1.11.0 <3.0.0
[   +1 ms] SLVR:                           selecting stream_channel 2.0.0
[        ] SLVR:                           fact: source_span 1.5.5 depends on charcode ^1.0.0
[   +1 ms] SLVR:                           fact: source_span 1.5.5 depends on path ^1.2.0
[        ] SLVR:                           fact: source_span 1.5.5 depends on term_glyph ^1.0.0
[        ] SLVR:                             selecting source_span 1.5.5
[        ] SLVR:                             fact: petitparser 2.4.0 depends on meta ^1.1.0
[        ] SLVR:                               selecting petitparser 2.4.0
[        ] SLVR:                                 selecting pedantic 1.8.0+1
[        ] SLVR:                                   selecting meta 1.1.8
[        ] SLVR:                                   fact: matcher 0.12.6 depends on stack_trace ^1.2.0
[        ] SLVR:                                     selecting matcher 0.12.6
[        ] SLVR:                                     fact: crypto 2.1.3 depends on collection ^1.0.0
[   +1 ms] SLVR:                                     fact: crypto 2.1.3 depends on convert >=1.0.0 <3.0.0
[  +14 ms] SLVR:                                     fact: crypto 2.1.3 depends on typed_data ^1.0.0
[        ] SLVR:                                       selecting crypto 2.1.3
[        ] SLVR:                                       fact: convert 2.1.1 depends on charcode ^1.1.0
[        ] SLVR:                                       fact: convert 2.1.1 depends on typed_data ^1.1.0
[        ] SLVR:                                         selecting convert 2.1.1
[        ] SLVR:                                           selecting collection 1.14.11
[        ] SLVR:                                             selecting charcode 1.1.2
[        ] SLVR:                                             fact: boolean_selector 1.0.5 depends on source_span ^1.0.0
[        ] SLVR:                                             fact: boolean_selector 1.0.5 depends on string_scanner >=0.1.1 <2.0.0
[        ] SLVR:                                               selecting boolean_selector 1.0.5
[        ] SLVR:                                               fact: async 2.4.0 depends on collection ^1.5.0
[        ] SLVR:                                                 selecting async 2.4.0
[        ] SLVR:                                                   selecting args 1.5.2
[        ] SLVR:                                                   fact: archive 2.0.11 depends on crypto ^2.0.0
[        ] SLVR:                                                   fact: archive 2.0.11 depends on args ^1.4.0
[   +1 ms] SLVR:                                                   fact: archive 2.0.11 depends on path ^1.5.1
[        ] SLVR:                                                     selecting archive 2.0.11
[        ] SLVR:                                                       selecting vector_math 2.0.8
[        ] SLVR:                                                       fact: stack_trace 1.9.3 depends on path ^1.2.0
[        ] SLVR:                                                         selecting stack_trace 1.9.3
[        ] SLVR:                                                         fact: quiver 2.0.5 depends on matcher >=0.10.0 <0.13.0
[        ] SLVR:                                                         fact: quiver 2.0.5 depends on meta ^1.0.0
[        ] SLVR:                                                           selecting quiver 2.0.5
[        ] SLVR:                                                           fact: image 2.1.4 depends on archive >=1.0.16 <3.0.0
[        ] SLVR:                                                           fact: image 2.1.4 depends on xml ^3.2.5
[        ] SLVR:                                                             selecting image 2.1.4
[        ] SLVR:                                                               selecting path 1.6.4
[   +1 ms] SLVR:                                                               fact: test_api 0.2.11 depends on async ^2.0.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on boolean_selector
^1.0.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on collection ^1.8.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on meta ^1.1.5
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on path ^1.2.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on pedantic ^1.0.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on source_span ^1.4.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on stack_trace ^1.9.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on stream_channel
>=1.7.0 <3.0.0
[   +1 ms] SLVR:                                                               fact: test_api 0.2.11 depends on string_scanner ^1.0.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on term_glyph ^1.0.0
[        ] SLVR:                                                               fact: test_api 0.2.11 depends on matcher >=0.12.6
<0.12.7
[   +1 ms] SLVR:                                                                 selecting test_api 0.2.11
[        ] SLVR:                                                                 fact: http_parser 3.1.3 depends on charcode ^1.1.0
[        ] SLVR:                                                                 fact: http_parser 3.1.3 depends on collection
>=0.9.1 <2.0.0
[        ] SLVR:                                                                 fact: http_parser 3.1.3 depends on source_span
^1.0.0
[        ] SLVR:                                                                 fact: http_parser 3.1.3 depends on string_scanner
>=0.0.0 <2.0.0
[        ] SLVR:                                                                 fact: http_parser 3.1.3 depends on typed_data ^1.1.0
[        ] SLVR:                                                                   selecting http_parser 3.1.3
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on
firebase ^7.0.0
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on
firebase_core_platform_interface ^1.0.0
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on flutter
any from sdk
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on
flutter_web_plugins any from sdk
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on meta
^1.1.7
[        ] SLVR:                                                                   fact: firebase_core_web 0.1.1+1 depends on js
^0.6.1
[        ] SLVR:                                                                     selecting firebase_core_web 0.1.1+1
[        ] SLVR:                                                                     derived: js ^0.6.1
[        ] SLVR:                                                                     derived: flutter_web_plugins any from sdk
[        ] SLVR:                                                                     derived: firebase ^7.0.0
[        ] SLVR:                                                                     fact: firebase_core_platform_interface 1.0.2
depends on flutter any from sdk
[        ] SLVR:                                                                     fact: firebase_core_platform_interface 1.0.2
depends on meta ^1.0.5
[        ] SLVR:                                                                     fact: firebase_core_platform_interface 1.0.2
depends on quiver ^2.0.0
[        ] SLVR:                                                                       selecting firebase_core_platform_interface
1.0.2
[        ] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
firebase_auth_platform_interface ^1.0.0
[        ] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
flutter any from sdk
[        ] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
flutter_web_plugins any from sdk
[        ] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
firebase ^7.0.0
[        ] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
http_parser ^3.1.3
[  +15 ms] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on
meta ^1.1.7
[   +1 ms] SLVR:                                                                       fact: firebase_auth_web 0.1.1+1 depends on js
^0.6.1
[        ] SLVR:                                                                         selecting firebase_auth_web 0.1.1+1
[        ] SLVR:                                                                         fact: firebase_auth_platform_interface 1.1.2
depends on flutter any from sdk
[        ] SLVR:                                                                         fact: firebase_auth_platform_interface 1.1.2
depends on meta ^1.0.5
[        ] SLVR:                                                                           selecting firebase_auth_platform_interface
1.1.2
[   +1 ms] SLVR:                                                                             selecting sky_engine 0.0.99 from sdk
[        ] SLVR:                                                                               selecting js 0.6.1+1
[        ] SLVR:                                                                               fact: flutter_web_plugins 0.0.0 from
sdk depends on flutter any from sdk
[        ] SLVR:                                                                               fact: flutter_web_plugins 0.0.0 from
sdk depends on collection 1.14.11
[   +1 ms] SLVR:                                                                               fact: flutter_web_plugins 0.0.0 from
sdk depends on meta 1.1.8
[        ] SLVR:                                                                               fact: flutter_web_plugins 0.0.0 from
sdk depends on typed_data 1.1.6
[        ] SLVR:                                                                               fact: flutter_web_plugins 0.0.0 from
sdk depends on vector_math 2.0.8
[        ] SLVR:                                                                                 selecting flutter_web_plugins 0.0.0
from sdk
[        ] SLVR:                                                                                 fact: firebase 7.1.0 depends on http
>=0.11.3 <0.13.0
[        ] SLVR:                                                                                 fact: firebase 7.1.0 depends on
http_parser ^3.0.0
[        ] SLVR:                                                                                 fact: firebase 7.1.0 depends on js
^0.6.0
[   +1 ms] SLVR:                                                                                   selecting firebase 7.1.0
[        ] SLVR:                                                                                   fact: carousel_slider >=0.0.7
depends on flutter any from sdk
[        ] SLVR:                                                                                     selecting carousel_slider 1.4.0
[        ] SLVR: Version solving took 0:00:01.503103 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (1.506s).
[        ] MSG : + carousel_slider 1.4.0
[  +15 ms] IO  : Get package from https://pub.dartlang.org/packages/carousel_slider/versions/1.4.0.tar.gz.
[        ] MSG : Downloading carousel_slider 1.4.0...
[        ] IO  : Created temp directory H:\src\Flutter\flutter\.pub-cache\_temp\dirba012d91-2d79-11ea-85b0-7cd30a80fbf1
[        ] IO  : HTTP GET https://pub.dartlang.org/packages/carousel_slider/versions/1.4.0.tar.gz
[        ]     | X-Pub-OS: windows
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: DF02ACDC-6881-4106-99C8-AA98156B3BA0
[        ]     | X-Pub-Environment: flutter_cli:get
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.7.0
[+10579 ms] IO  : HTTP error:
[   +1 ms]     | HandshakeException: Connection terminated during handshake

**Comment by jonorozcoc** [comment]
> Is this persistent? Are you on a network provider that blocks some google cloud resources. Or behind a corporate proxy?

What I can do if I'm corporate proxy? (Sophos)

**Comment by mamunur34** [comment]
I am facing the same issue for 3 days. Any update?

**Comment by Fahmid-Shuvo** [comment]
Dear All, Hows everything during this pandemic situation. Hopefully everyone is sound and safe. I am learning Flutter. from yesterday I started to face problem while I add http: ^0.12.0+4 in my pub spec.yaml file. after running pub get it shows  pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Any solution please. Is the problem related to my network or it is the Flutter dev server>>??

**Comment by Basher7** [comment]
I'm also facing same issue when i trying to upgrade progress_dialog version 1.2.0 to 1.2.1

**Comment by Basher7** [comment]
@sanjidtt can you find any solution about this issue?

**Comment by Basher7** [comment]
@sanjidtt still facing this problem or found any solution?

**Comment by sigurdm** [comment]
@sanjidtt do you happen to also be in Bangladesh?

**Comment by jonasfj** [comment]
@Basher7 , @Fahmid-Shuvo, @sanjidtt, @mamunur34, @jonorozcoc, Can you please answer following questions:

* What country are you located in?
* Can you load `https://pub.dartlang.org/api/packages/retry` in a browser (without VPN)?
* Can you download `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` in a browser (without a VPN)?

Please reply in this thread. We currently have `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` redirecting to `storage.googleapis.com/...` (serving directly from Google Cloud Storage). Maybe, your ISP is blocking access to `storage.googleapis.com`, I don't know why anyone would censor the internet. Or if we can do anything about it. But if this is the problem we would like to know about it -- maybe we can avoid redirecting to `storage.googleapis.com`.

**Comment by sigurdm** [comment]
It could be due to restricted access. You could try to use a VPN or perhaps try the instructions here for using a mirror: https://flutter.dev/community/china .

**Comment by sigurdm** [comment]
For a temporary solution try accessing pub using a VPN.
Or use a mirror following the instructions here: https://flutter.dev/community/china

**Comment by razu-shaikh** [comment]
> @Basher7 , @Fahmid-Shuvo, @sanjidtt, @mamunur34, @jonorozcoc, Can you please answer following questions:
> 
> * What country are you located in?
> * Can you load `https://pub.dartlang.org/api/packages/retry` in a browser (without VPN)?
> * Can you download `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` in a browser (without a VPN)?
> 
> Please reply in this thread.
> 
> We currently have `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` redirecting to `storage.googleapis.com/...` (serving directly from Google Cloud Storage). Maybe, your ISP is blocking access to `storage.googleapis.com`, I don't know why anyone would censor the internet. Or if we can do anything about it. But if this is the problem we would like to know about it -- maybe we can avoid redirecting to `storage.googleapis.com`.

Sir, I am also facing same problem from bangladesh!
Your first url...`https://pub.dartlang.org/api/packages/retry` load successfully
and get json, like:::
{
"name": "retry",
"latest": {
"archive_url": "https://pub.dartlang.org/packages/retry/versions/3.0.0%2B1.tar.gz",
"pubspec": {
"authors": [
"Jonas Finnemann Jensen <jonasfj@google.com>"
],
"repository": "https://github.com/google/dart-neats.git",
"version": "3.0.0+1",
"name": "retry",
"description": "Utility for wrapping an asynchronous function in automatic retry logic with
exponential back-off, useful when making requests over network.
",
"environment": {
"sdk": ">=2.0.0 <3.0.0"
},
"homepage": "https://github.com/google/dart-neats/tree/master/retry",
"issue_tracker": "https://github.com/google/dart-neats/labels/pkg:retry",
"dev_dependencies": {
"test": "^1.5.1",
"pedantic": "^1.4.0"
}
},
"version": "3.0.0+1"
},
"versions": [
{
"archive_url": "https://pub.dartlang.org/packages/retry/versions/1.0.0.tar.gz",
"pubspec": {
"homepage": "https://github.com/gwTumm/dart-retry",
"version": "1.0.0",
"name": "retry",
"author": "Tim Kluge <timklge@gmail.com>",
"description": "Execute a function repeatedly until no exception is thrown",
"dev_dependencies": {
"test": "any"
}
},
"version": "1.0.0"
},
{
"archive_url": "https://pub.dartlang.org/packages/retry/versions/2.0.0.tar.gz",
"pubspec": {
"authors": [
"Jonas Finnemann Jensen <jonasfj@google.com>"
],
"repository": "https://github.com/google/dart-neats.git",
"version": "2.0.0",
"name": "retry",
"description": "Utility for wrapping an asynchronous function in automatic retry logic with
exponential backoff, useful when making requests over network.
",
"environment": {
"sdk": ">=2.0.0 <3.0.0"
},
"homepage": "https://github.com/google/dart-neats/tree/master/retry",
"issue_tracker": "https://github.com/google/dart-neats/labels/pkg:retry",
"dev_dependencies": {
"test": "^1.5.1",
"pedantic": "^1.4.0"
}
},
"version": "2.0.0"
},
{
"archive_url": "https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz",
"pubspec": {
"authors": [
"Jonas Finnemann Jensen <jonasfj@google.com>"
],
"repository": "https://github.com/google/dart-neats.git",
"version": "3.0.0",
"name": "retry",
"description": "Utility for wrapping an asynchronous function in automatic retry logic with
exponential back-off, useful when making requests over network.
",
"environment": {
"sdk": ">=2.0.0 <3.0.0"
},
"homepage": "https://github.com/google/dart-neats/tree/master/retry",
"issue_tracker": "https://github.com/google/dart-neats/labels/pkg:retry",
"dev_dependencies": {
"test": "^1.5.1",
"pedantic": "^1.4.0"
}
},
"version": "3.0.0"
},
{
"archive_url": "https://pub.dartlang.org/packages/retry/versions/3.0.0%2B1.tar.gz",
"pubspec": {
"authors": [
"Jonas Finnemann Jensen <jonasfj@google.com>"
],
"repository": "https://github.com/google/dart-neats.git",
"version": "3.0.0+1",
"name": "retry",
"description": "Utility for wrapping an asynchronous function in automatic retry logic with
exponential back-off, useful when making requests over network.
",
"environment": {
"sdk": ">=2.0.0 <3.0.0"
},
"homepage": "https://github.com/google/dart-neats/tree/master/retry",
"issue_tracker": "https://github.com/google/dart-neats/labels/pkg:retry",
"dev_dependencies": {
"test": "^1.5.1",
"pedantic": "^1.4.0"
}
},
"version": "3.0.0+1"
}
]
}
 But second url not loading!!!

**Comment by mahmudtopu3** [comment]
Getting this error again and again.  storage.googleapis.com is not accessible from broadband or any mobile networks in Bangladesh.

**Comment by shahinmahmudahil** [comment]
> Getting this error again and again. storage.googleapis.com is not accessible from broadband or any mobile networks in Bangladesh.

do you get the solution ? i am facing same problem

**Comment by Basher7** [comment]
> @Basher7 , @Fahmid-Shuvo, @sanjidtt, @mamunur34, @jonorozcoc, Can you please answer following questions:
> 
> * What country are you located in?
> * Can you load `https://pub.dartlang.org/api/packages/retry` in a browser (without VPN)?
> * Can you download `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` in a browser (without a VPN)?
> 
> Please reply in this thread.
> 
> We currently have `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` redirecting to `storage.googleapis.com/...` (serving directly from Google Cloud Storage). Maybe, your ISP is blocking access to `storage.googleapis.com`, I don't know why anyone would censor the internet. Or if we can do anything about it. But if this is the problem we would like to know about it -- maybe we can avoid redirecting to `storage.googleapis.com`.

> I'm from Bangladesh.
> https://pub.dartlang.org/api/packages/retry - load this data successfully.
> https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz - this link redirect to https://storage.googleapis.com/pub-packages/packages/retry-3.0.0.tar.gz that not accessible. But when I browse https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz link from mobile browser file downloaded successfully.

**Comment by Basher7** [comment]
> @Basher7 , @Fahmid-Shuvo, @sanjidtt, @mamunur34, @jonorozcoc, Can you please answer following questions:
> 
> * What country are you located in?
> * Can you load `https://pub.dartlang.org/api/packages/retry` in a browser (without VPN)?
> * Can you download `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` in a browser (without a VPN)?
> 
> Please reply in this thread.
> 
> We currently have `https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz` redirecting to `storage.googleapis.com/...` (serving directly from Google Cloud Storage). Maybe, your ISP is blocking access to `storage.googleapis.com`, I don't know why anyone would censor the internet. Or if we can do anything about it. But if this is the problem we would like to know about it -- maybe we can avoid redirecting to `storage.googleapis.com`.

> **I'm from Bangladesh.**
> **https://pub.dartlang.org/api/packages/retry - load this data successfully.**
> **https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz - this link redirect to https://storage.googleapis.com/pub-packages/packages/retry-3.0.0.tar.gz that not accessible. But when I browse https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz link from mobile browser file downloaded successfully.**

**Comment by Basher7** [comment]
@mamunur34 , @Fahmid-Shuvo , @mahmudtopu3 , @shahinmahmudahil , @razu-shaikh still facing this problem or found any solution?

sorry for tagging all.

**Comment by mahmudtopu3** [comment]
Haven't tried today . Did you have tried ?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Basher7** [comment]
Unable to access storage.googleapis.com. For this reason I  use a mirror following the instructions here: https://flutter.dev/community/china. Thanks @sigurdm.

**Comment by jeet892** [comment]
Just connect any VPN on windows/mac, it'll work 1000%

**Comment by mahmudtopu3** [comment]
Still it fails to get packages. Why we need VPN ?

**Comment by sigmondg** [comment]
> storage.googleapis.com

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>MissingSecurityHeader</Code>
<Message>Your request was missing a required header.</Message>
<Details>Authorization</Details>
</Error>

when i go onto storage.googleapis.com  , what can i do please?

**Comment by sigurdm** [comment]
> Still it fails to get packages. Why we need VPN ?

We are not sure - it seems to be a problem local to Bangladesh.

The VPN is needed to access storage.googleapis.com via somewhere else.

**Comment by pappu687** [comment]
> Still it fails to get packages. Why we need VPN ?

Because the intelligent BTCL blocked `storage.googleapis.com`

**Comment by Dogunfx** [comment]
> * https://pub.dartlang.org/api/packages/retry

i could not load the URL, 

it keeps saying this site can not be reach

**Comment by Fahmid-Shuvo** [comment]
Use VPN. It works for me for the time being.

**Comment by Tusar0003** [comment]
@Fahmid-Shuvo can you please tell me which VPN you are using??? and which location it's giving you???  because using VPN I am still facing the same problem.

**Comment by Basher7** [comment]
@Tusar0003 Don't need to use a vpn.
replace this link
https://storage.googleapis.com/download.flutter.io by http://download.flutter.io/ at your flutter.gradle file line no 44
and resolve_dependencies.gradle file line no 21

you can find those file C:\flutter\packages\flutter_tools\gradle\
Note that replace C by your root directory where store your flutter sdk

**Comment by Tusar0003** [comment]
@Basher7 thanks bro
It was already added as I downloaded flutter SDK from mirror site but still I couldn't get the packages. Then I had to change the hosted url by adding this two lines. Finally it worked perfectly :)

$ set PUB_HOSTED_URL=https://pub.flutter-io.cn
$ set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

you can check the hosted url by this command:
$ echo %PUB_HOSTED_URL%

NOTE: All this commands for windows only

**Comment by ZHENGGEGE** [comment]
Same question

**Comment by BalanaguYashwanth** [comment]
simple use this command :
killall -9 dart

once try i will resolve

**Comment by dsp1589** [comment]
Its failing now!

Added new dep : '  websafe_svg: ^1.1.0 '

<img width="559" alt="Screen Shot 2020-07-21 at 4 59 34 PM" src="https://user-images.githubusercontent.com/1726017/88050011-b5344280-cb73-11ea-8b42-52b382eedced.png">

**Comment by Tarikul711** [comment]
This is a country-specific problem. In some countries, you got this error like Bangladesh and some African countries. I got a solution to this problem, that is use VPN software when you want to get Packages. VPN software uses other country's IP addresses where this google service works perfectly, So you can easily download packages.

**Comment by Basher7** [comment]
@dsp1589 you can also use flutter mirror from [https://flutter.dev/community/china](url) to overcome this problem.

**Comment by wisdomspine** [comment]
I had to change my ISP to get the package downloaded, I don't why using a VPN could not solve it though.

**Comment by sigurdm** [comment]
I think this issue is stale - I will close for now. Please open new issues if you have problems accessing pub.dev

Some countries/regions have problems reaching pub.dev.

Most of the time we cannot suggest much else than using a VPN or trying  the Chinese community mirror: https://docs.flutter.dev/community/china .

**Comment by individual-777** [comment]
всех приветствую, у меня возникла проблема при добавлении пакета   url_launcher и нажатии кнопки Pub get, происходит длительная загрузка и не добавляется пакет, перепробовал буквально все, кто что может подсказать?
конечная ошибка:
Превышен таймаут семафора.
pub get failed
command: "C:\src\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\src\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\Individyal\AppData\Local\Pub\Cache",
}
exit code: 69

Process finished with exit code 69
