### ISSUE TITLE
when PUB_HOSTED_URL is set to http server, html escape failed.

### ISSUE THREAD

**Issue by pouloghost** [dart-lang/pub#2309]
# Environment

Pub 2.5.0
Mac OS 
Location China

# Problem
when PUB_HOSTED_URL is set to http server, file path in .packages is not escaped properly. http%2558%2547%2547 is found, but actual file in .pub-cache is http%58%47%47. And to my understanding http%58%47%47 is correct.
## Expected behavior

escape in .packages is http%58%47%47

## Actual behavior

http%2558%2547%2547

**Comment by pouloghost** [comment]
https works fine

**Comment by sigurdm** [comment]
Does this create problems - then please reopen?
This works as intended I believe.
We do a pseudo-uri encoding to make a directory-name out of the url (https://github.com/dart-lang/pub/blob/master/lib/src/source/hosted.dart#L421).
Then we do a uri-encoding of that to write that in the ,packages file. (https://github.com/dart-lang/pub/blob/master/lib/src/lock_file.dart#L227)

That should then be uri-decoded to find the actual path by the dart vm.

**Comment by pouloghost** [comment]
> Does this create problems - then please reopen?
> This works as intended I believe.
> We do a pseudo-uri encoding to make a directory-name out of the url (https://github.com/dart-lang/pub/blob/master/lib/src/source/hosted.dart#L421).
> Then we do a uri-encoding of that to write that in the ,packages file. (https://github.com/dart-lang/pub/blob/master/lib/src/lock_file.dart#L227)
> 
> That should then be uri-decoded to find the actual path by the dart vm.

Local file is in %58 rather than %2558. So indexing and auto complete fails, compiling works fine.

**Comment by sigurdm** [comment]
What development environment are you using?
What indexing and auto-completion tools fail to work?

All tools should ideally load `.packages` the same way, and do url-decoding on the paths (for example using https://pub.dev/documentation/package_config/latest/package_config.packages_file/package_config.packages_file-library.html).

**Comment by pouloghost** [comment]
> What development environment are you using?
> What indexing and auto-completion tools fail to work?
> 
> All tools should ideally load `.packages` the same way, and do url-decoding on the paths (for example using https://pub.dev/documentation/package_config/latest/package_config.packages_file/package_config.packages_file-library.html).

I'm using android studio 3.5.3 dart plugin 191.8593. I think the problem is .pub_cache path is different from .packages, nothing wrong with IDE or environment. AS reads .packages and fails to index a non-existing folder seems ok to me.
