### ISSUE TITLE
'The pubspec file' page issue

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub#2312]
Page URL: https://dart.dev/tools/pub/pubspec.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/pubspec.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The docs say:

>Homepage
>
>This should be a URL pointing to the website for your package. For hosted packages, this URL is linked from the package’s page. While providing a homepage is optional, please provide it or repository (or both). It helps users understand where your package is coming from.

But I don't have a Homepage, so I just provided Repository instead. But then when I run ` flutter pub publish --dry-run` I get an error saying:

>Your pubspec.yaml is missing a "homepage" field.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
pub finished with exit code 65

The docs say `While providing a homepage is optional, please provide it or repository`, but `pub publish` say it's required and just Repository is not enough. Either the tool is wrong or the docs should be updated.

**Comment by sigurdm** [comment]
We need to update the server logic too.
