### ISSUE TITLE
Add a validator that users don't attempt to upgrade their language version for any files

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2316]
In order to support code generators I believe we have decided that the compilers will accept language _upgrades_ as well as downgrades in the per file overrides. Upgrades are allowed to make things easier on code generators.

However, language version upgrades are unsafe for published packages on pub. Therefore, we need to have a validator that no file upgrades the language version beyond the minimum sdk specified in the pubspec.

cc @leafpetersen did this get officially specified anywhere do you know?

**Comment by jakemac53** [comment]
Note also that it would be very important to get this validator into the very first published version of the SDK which allows NNBD otherwise people can always publish bad packages with that version that work locally and break their users.

**Comment by jonasfj** [comment]
Agreed, this seems like a good idea.

@sigurdm, any thoughts?

**Comment by sigurdm** [comment]
I believe we need the analyzer to expose the exact language version of each library to make this validation.

**Comment by sigurdm** [comment]
Fixed by https://github.com/dart-lang/pub/pull/2338
