### ISSUE TITLE
i get this issue The gzip file did not contain a tar file  whene i add library in pubspec.ymal

### ISSUE THREAD

**Issue by Mostafa-SA-developer** [dart-lang/pub#2324]
The gzip file did not contain a tar file.

package:pub/src/io.dart 936:7               _extractTarGzWindows.<fn>.<fn>

dart:collection                             ListMixin.firstWhere

package:pub/src/io.dart 935:10              _extractTarGzWindows.<fn>

===== asynchronous gap ===========================

package:pub/src/io.dart 820:20              withTempDir

package:pub/src/io.dart 914:10              _extractTarGzWindows

package:pub/src/io.dart 842:18              extractTarGz

package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 400:48      Entrypoint._get.<fn>

package:pub/src/http.dart 271:51            withDependencyType

package:pub/src/entrypoint.dart 396:12      Entrypoint._get

dart:async                                  Future.wait

package:pub/src/entrypoint.dart 245:18      Entrypoint.acquireDependencies

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver.solve

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
Process finished with exit code 65

**Comment by jonasfj** [comment]
What OS? What Dart/pub version? What is the `pubspec.yaml` you're running on?
Can you share the full log?

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by Mostafa-SA-developer** [comment]
```
The gzip file did not contain a tar file.
package:pub/src/io.dart 936:7               _extractTarGzWindows.<fn>.<fn>
dart:collection                             ListMixin.firstWhere
package:pub/src/io.dart 935:10              _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 820:20              withTempDir
package:pub/src/io.dart 914:10              _extractTarGzWindows
package:pub/src/io.dart 842:18              extractTarGz
package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 388:48      Entrypoint._get.<fn>
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 384:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 245:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_mandobs...
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

**Comment by Mostafa-SA-developer** [comment]
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (11 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by godilite** [comment]
I have the same issue, How did you solve this please

**Comment by Alloco225** [comment]
Same issue here

**Comment by Mostafa-SA-developer** [comment]
@godilite yes i had sloved i copy the bin foldar in dart sdk **flutter\bin\cache\dart-sdk\bin** 
to my  current flutter folder

**Comment by Mostafa-SA-developer** [comment]
@ Alloco225 this issue occurs when loss the gzip from this path ** flutter \ bin \ cache \ dart-sdk **
Because windows defender or any anit virus delete gzip sometimes delete the dart patch so i stoped the windows defender and if you you have another flutter you downloaded any where just copy the bin folder in dart sdk to current dart sdk folder

**Comment by Alloco225** [comment]
@Mostafa-SA-developer can you please explain more clearly and step by step how to solve it

**Comment by Mostafa-SA-developer** [comment]
@Alloco225   ok pro  i sayed this issue accours whene the  windows defender delete some file from bin in this folder **flutter \ bin \ cache \ dart-sdk**  so open the bin folder You must have these files as in the picture

![image](https://user-images.githubusercontent.com/53539929/81461458-9b11d780-91b4-11ea-9d25-a7a97eb0364a.png)

**Comment by Alloco225** [comment]
Thank you very much. It worked.

**Comment by sigurdm** [comment]
This should be fixed now we implement tar extraction ourselves, and no longer rely on an external tool to extract tar.gz files.
