### ISSUE TITLE
package:pub/src/http.dart 218:5                 _ThrowingClient.send

### ISSUE THREAD

**Issue by RogueYBJ** [dart-lang/pub#2326]
package:pub/src/http.dart 218:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 322:37       BoundHostedSource._download

package:pub/src/source/hosted.dart 217:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 388:48          Entrypoint._get.<fn>

package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 384:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 245:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by lidong-biubiubiu** [comment]
I have the same problem, is there a solution?

**Comment by lidong-biubiubiu** [comment]
the solution see https://github.com/dart-lang/build/issues/2528#issuecomment-563313269
