### ISSUE TITLE
pub should warn (error?) when publishing without a changelog.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#2337]
Came up here: https://github.com/dart-lang/pub/issues/2003

**Comment by jonasfj** [comment]
Can we warn if it's not called `CHANGELOG.md`? And then update docs so that this is our recommended file name?

**Comment by jakemac53** [comment]
We do already recommend that file name https://dart.dev/tools/pub/package-layout#changelog

**Comment by jakemac53** [comment]
We do already recommend that file name https://dart.dev/tools/pub/package-layout#changelog

**Comment by jonasfj** [comment]
I think our recommendation could be more clear. In fact, we should probably just make it the only filename we allow, filed https://github.com/dart-lang/site-www/issues/2289 to discuss this. As the first step is updating documentation for the packaging format.

**Comment by jonasfj** [comment]
@sigurdm, didn't we fix this?

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pub/pull/2339
