### ISSUE TITLE
pub.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18) pub.flutter-io.cn%0D

### ISSUE THREAD

**Issue by AndyRoyal** [dart-lang/pub#2340]
pub.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%0D

package:pub/src/command_runner.dart 171:13                                          PubCommandRunner.runCommand
===== asynchronous gap ===========================                      
package:pub/src/command_runner.dart 119:11                                          PubCommandRunner.run
/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8:22  main
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment]
It looks like you got some extra characters when setting up the `PUB_HOSTED_URL` variable.

The correct command (from https://flutter.dev/community/china) is:
```
export PUB_HOSTED_URL=https://pub.flutter-io.cn
```

Please try again.
If it still doesn't work, please copy paste all the commands you use to do `pub get`.

**Comment by AndyRoyal** [comment]
看起来是这样的错误提示，我已经做过尝试，不好使，不过现在OK了，thankyou

**Comment by ytandhz** [comment]
> 看起来是这样的错误提示，我已经做过尝试，不好使，不过现在OK了，thankyou

请问是怎么解决的呢？ 执行flutter pub get 出现类似的错误：
pub get failed (65; Because flutter_module depends on json_serializable any which doesn't exist (Got badly formatted response trying to find package json_serializable at https://pub.flutter-io.cn%0D), version solving failed.)
