### ISSUE TITLE
pub upgrade failed

### ISSUE THREAD

**Issue by godilite** [dart-lang/pub#2342]
I have been suffering this issue for a week now. I have tried to add a new package or while trying to upgrade pub. I get this error
`
C:\flutter\bin\flutter.bat --no-color packages upgrade
Running "flutter pub upgrade" in apaproapp...                   
The gzip file did not contain a tar file.

package:pub/src/io.dart 936:7               _extractTarGzWindows.<fn>.<fn>

dart:collection                             ListMixin.firstWhere

package:pub/src/io.dart 935:10              _extractTarGzWindows.<fn>

===== asynchronous gap ===========================

package:pub/src/io.dart 820:20              withTempDir

package:pub/src/io.dart 914:10              _extractTarGzWindows

package:pub/src/io.dart 842:18              extractTarGz

package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 388:48      Entrypoint._get.<fn>

dart:async                                  runZoned

package:pub/src/http.dart 272:10            withDependencyType

package:pub/src/entrypoint.dart 384:12      Entrypoint._get

dart:async                                  Future.wait

package:pub/src/entrypoint.dart 245:18      Entrypoint.acquireDependencies

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver.solve

dart:async                                  _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart  VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' upgrade --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub upgrade failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
Process finished with exit code 65
`
I have read through similar issue and there are yet no working solutions. I have changed ISP still no solution

**Comment by godilite** [comment]
I've found a fix to this issue, by running 

```
git clean -xfd
git pull
flutter doctor
```
In the flutter directory

**Comment by sigurdm** [comment]
We are no longer depending on system tar.

Closing assuming stale.
