### ISSUE TITLE
Issue while package get in pubspec.yaml

### ISSUE THREAD

**Issue by HamidSeyfi** [dart-lang/pub#2344]
Running "flutter pub get" in startup_namer...                   
HTTP error 403: Forbidden

package:pub/src/http.dart 218:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 322:37       BoundHostedSource._download

package:pub/src/source/hosted.dart 217:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 388:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 272:10                withDependencyType

package:pub/src/entrypoint.dart 384:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 245:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment]
This could be related to a blocked connection to pub.dev from your location.

Can you access `pub.dev` from a browser?

Could you try running `flutter pub  get --verbose --no-precompile` to get the full logs?
And include the logs in this issue (using code fencing: ```)
