### ISSUE TITLE
Changing package name in a directory (via git checkout) causes pub upgrade to crash!

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#2345]
# Environment

- `pub version` or `flutter pub version`: Pub 2.8.0-dev.10.0
- OS version: Mac

# Problem

This is a weird case. I'm in a directory with a package.

* working on git branch `alpha` the package name is `pathx`.
* checkout git branch `beta` the package name is `path`.
* Run `pub upgrade`

Guessing pub client is confused since the package name changed with all of it's artifacts (pubspec.lock, .packages, .dart_tool/package-config) assuming the name is something else

## Expected behavior

It should "just work"

## Actual behavior

Crash!

## --trace output

```
ERR : The method 'formatDescription' was called on null.
    | Receiver: null
    | Tried calling: formatDescription("path")
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                   Object.noSuchMethod
    | package:pub/src/solver/report.dart 241:35   SolveReport._writeId
    | package:pub/src/solver/report.dart 190:5    SolveReport._reportPackage
    | package:pub/src/solver/report.dart 110:9    SolveReport._reportChanges
    | package:pub/src/solver/report.dart 44:5     SolveReport.show
    | package:pub/src/solver/result.dart 91:65    SolveResult.showReport
    | package:pub/src/entrypoint.dart 236:12      Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 113:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 126:11           captureErrors
    | package:pub/src/command_runner.dart 174:13  PubCommandRunner.runCommand
---- End log transcript ----
```

**Comment by kevmoo** [comment]
Work-around: deleted `.packages` and `pubspec.lock` – not sure if both were needed, though!

**Comment by sigurdm** [comment]
I was not able to reproduce by just renaming the package in a `pubspec.yaml` followed by an upgrade.

Are you able to give the two reproducing `pubspec.yaml`s (from branch alpha and beta) 

Also reproduction steps, if it is not just `pub get` with pubspec a, followed by `pub upgrade` with pubspec b.

**Comment by kevmoo** [comment]
> I was not able to reproduce by just renaming the package in a `pubspec.yaml` followed by an upgrade.
> 
> Are you able to give the two reproducing `pubspec.yaml`s (from branch alpha and beta)
> 
> Also reproduction steps, if it is not just `pub get` with pubspec a, followed by `pub upgrade` with pubspec b.

1) Check out `package:path` source.
2) pubspec.yaml: rename `path` to `pathx`
3) run `pub upgrade`
4) pubspec.yaml: rename `pathx` to `path`
5) pub upgrade

I'm guessing it's special when dealing with packages that are used transitively by their own dependencies!

**Comment by kevmoo** [comment]
Also: workaround is to just delete `pubspec.lock`

**Comment by jonasfj** [comment]
@kevmoo, why is this 'high priority' ? (curious, if this blocks samples or something)

**Comment by kevmoo** [comment]
> @kevmoo, why is this 'high priority' ? (curious, if this blocks samples or something)

It crashes pub and gives no instructions on how to fix.

Perhaps medium priority is more appropriate – since this is likely rare.
