### ISSUE TITLE
pub get failed (server unavailable) -- attempting

### ISSUE THREAD

**Issue by alaalsalam** [dart-lang/pub#2357]

**Comment by sigurdm** [comment]
Can you provide any more information?

Are you behind a firewall? Has this worked before? Can you access `pub.dev` in the browser?

**Comment by Goldenbwuoy** [comment]
I'm having the same issue here. I'm in China and I can access pub.dev in the browser.

**Comment by mamunur34** [comment]
I am having the same issue. My location is Bangladesh. I am not using any proxy. The system was working until yesterday. I am ready to share any more information you require. For testing, I have created a brand new project. but it still the same issue. I have tried in both macOS and windows.The same in both 
OS Error: The semaphore timeout period has expired. , errno = 121, address = storage.googleapis.com, port = 3318

**Comment by mit-mit** [comment]
For those in China, please see https://flutter.dev/community/china

**Comment by mit-mit** [comment]
@mamunur34 are you still seeing the issue? Are other cloud-based services working as expected?

**Comment by mamunur34** [comment]
I have faced the issue on yesterday as well. Additionally, Firebase storage public url also not working with public url.

**Comment by lbuse** [comment]
I'm in Brazil, and for me the problem seems to be related to Cloudflare's DNS, I just removed from my router and now it's working again, but I would like to keep using their DNS.

I've noticed this in january, but I wasn't sure, as it is not a constant problem.

**Comment by sigurdm** [comment]
This is getting rather old, and might cover several different problems. I will close this as stale.

Please open new issues if you still have these problems.

If opening a new issue:

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.
