### ISSUE TITLE
Warn about "is:discontinued" packages in "pub get|upgrade|outdated"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2361]
When a package is flagged as "discontinued" on `pub.dev` (by the package owner), consumers of the package should get a warning.

This warning should appear, whenever, the user runs:
 * `pub outdated`, here we could show a summary of discontinued packages.
 * `pub upgrade`, similar to how we inform of new versions being available, we should inform about packages being discontinued. Hence, the information should appear in the log.
 * `pub get`, unless the package in question is pinned in `pubspec.yaml` or locked by `pubspec.lock` (and our resolution says to install the version in `pubspec.lock`). Hence, we do now warn about discontinued packages if you're just installing packages listed in your lock file, it's only when you make a new resolution that makes choices over a discontinued package).
 * `pub get`, if version resolution fails AND the discontinued package is party to the version conflict.

Notably, this aims to reduce noise from discontinued versions when you have pinned or locked to a specific version. Installing pinned or locked versions of a package is a sign that you're not considering upgrading the package (in the current workflow).

For example, there is no need to warn me when my app is being tested in CI. I want the warning when I'm upgrading packages, get a version conflict or add a new dependency on a package that is discontinued.

**Comment by jonasfj** [comment]
Thoughts @amirh, @mit-mit, @sigurdm?

**Comment by jonasfj** [comment]
This is important for flutter and thoughts around possible package migrations.

API for this is not in place on pub.dev yet. probably this needs to be part of the version listing end-point to avoid extra round-trips.

**Comment by sigurdm** [comment]
I'm all for.

We should think this together with other plans we have:
- Marking versions "broken"
- The idea of making "staged" packages available from `pub get` but issuing a warning.

These might all fit in the same extension of the listing api.

**Comment by sigurdm** [comment]
> For example, there is no need to warn me when my app is being tested in CI. I want the warning when I'm upgrading packages, get a version conflict or add a new dependency on a package that is discontinued.

Why don't we want to warn from CI. Would that be a usability-problem?

**Comment by mit-mit** [comment]
I think this would be great.

I would warn on any pub get (to make sure this visible enough). Maybe something like:

```console
$ pub get
Resolving dependencies...
Warning: You have 4 discontinued dependencies. Run `pub outdated` for details.
Got dependencies!
```

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/pub-dev/issues/2457 – we could do this generally. It only works if we send a full version map to the server to check, though. `pub get` (for instance) doesn't necessarily request all used packages if local constraints are met!

**Comment by sigurdm** [comment]
This was done back in https://github.com/dart-lang/pub/pull/2835
