### ISSUE TITLE
Support file names with unicode characters

### ISSUE THREAD

**Issue by JonasWanke** [dart-lang/pub#2362]
# Environment

- `pub version`: Pub 2.7.1
- OS version: Windows 10 Home 1909
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

I was trying to `pub lish` a new package, but `pub` fails when a file called `🦄.yml` exists in the project folder.

## Expected behavior

`pub` shouldn't crash and upload the package.

## Actual behavior

`pub` crashes:
```
> pub lish
Exists failed, path = '.\"\360\237\246\204.yml"' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
```
(File `🦄.yml` lies in the same folder as `pubspec.yaml` and I'm executing `pub lish` from that directory.)

The error is reproducible with other unicode characters (`ä.yml`, `á.yml`) and files in subdirectories (`.\lib\🦄.yml`, `.\lib\src\🦄.yml`, `.\.github\🦄.yml`).

Even more interestingly, the issue even persisted after deleting the mentioned file and still referenced the original file name. This also occurred after copying the whole project to a new location and deleting the `.dart_tool`-directory. I only got it working after deleting my `.git`-folder…

## --trace output

```
> pub lish --trace
Exists failed, path = '.\"\360\237\246\204.yml"' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
---- Log transcript ----
FINE: Pub 2.7.1
IO  : Spawning "cmd /c ver" in D:\p\black_hole_flutter\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.18363.657]
    | Nothing output on stderr.
IO  : Spawning "cmd /c git --version" in D:\p\black_hole_flutter\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 2.17.0.windows.1
    | Nothing output on stderr.
FINE: Determined git command git.
IO  : Spawning "cmd /c git check-ignore --quiet ." in D:\p\black_hole_flutter\.
IO  : Finished git. Exit code 1.
    | Nothing output on stdout.
    | Nothing output on stderr.
IO  : Spawning "cmd /c git ls-files --cached --others --exclude-standard" in D:\p\black_hole_flutter\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | "\360\237\246\204.yml"
    | | .github/FUNDING.yml
    | | .github/ISSUE_TEMPLATE/1-bug-report.md
    | | .github/ISSUE_TEMPLATE/2-feature-request.md
    | | .github/PULL_REQUEST_TEMPLATE.md
    | | .gitignore
    | | ".\360\237\246\204.yml"
    | | LICENSE
    | | README.md
    | | analysis_options.yaml
    | | lib/black_hole_flutter.dart
    | | lib/src/bottom_sheet.dart
    | | lib/src/buttons.dart
    | | lib/src/chip_group.dart
    | | lib/src/color.dart
    | | lib/src/color_material.dart
    | | lib/src/context.dart
    | | lib/src/separated_buttons.dart
    | | pubspec.yaml
    | Nothing output on stderr.
ERR : Exists failed, path = '.\"\360\237\246\204.yml"' (OS Error: The filename, directory name, or volume label syntax is incorrect.
    | , errno = 123)
FINE: Exception type: FileSystemException
FINE: dart:io                                     _Directory.existsSync
    | package:pub/src/io.dart 307:46              dirExists
    | package:pub/src/package.dart 255:14         Package.listFiles.<fn>
    | dart:core                                   Iterable.toList
    | package:pub/src/package.dart 283:8          Package.listFiles
    | package:pub/src/command/lish.dart 123:33    LishCommand.run
    | package:args/command_runner.dart 197:27     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39  PubCommandRunner.runCommand.<fn>
    | dart:async                                  new Future.sync
    | package:pub/src/utils.dart 109:12           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 109:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
    | dart:async                                  _completeOnAsyncReturn
    | package:pub/src/command_runner.dart         PubCommandRunner._validatePlatform
    | dart:async                                  _completeOnAsyncReturn
    | package:pub/src/io.dart                     runProcess.<fn>
---- End log transcript ----
```

**Comment by natebosch** [comment]
Even if we make this work in `pub` it's almost certainly going to fail in other places for consumers of the package.

Please don't put any characters into the file name that aren't valid in Dart identifiers. The standard is to use lowercase with underscores.

https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores

I am a bit curious as to how the `.git` directory was poisoning the publish even after the file was renamed...

**Comment by JonasWanke** [comment]
Hi @natebosch, thanks for the quick reply!

The `.🦄.yml` file isn't intended to be used by consumers of the package or in Dart at all — it's a configuration file for [🦄 Unicorn](https://github.com/JonasWanke/Unicorn), a project/repository automation tool (similar to the `.github`-directory or `.travis.yml`-file).

**Comment by irvifa** [comment]
Any ideas on ignoring specific file like 🦄 or `.git` when we use `pub lish` ?

**Comment by sigurdm** [comment]
(stumbling on this old issue).

I believe we handle this correctly now - probably when we reimplemented the . I'll add a regression test.

> Any ideas on ignoring specific file like 🦄 or .git when we use pub lish ?

Any file starting with "." is ignored by default.

To ignore other files when publishing, but keeping them checked into git use a .pubignore file (https://stackoverflow.com/questions/69760021/what-should-be-ignored-in-darts-pubignore).
