### ISSUE TITLE
Failed to Install package yaml

### ISSUE THREAD

**Issue by CEbbinghaus** [dart-lang/pub#2380]
Platforn: ClearLinux

I Tried just adding the YAML Dependency but it gave me a error:
![image](https://user-images.githubusercontent.com/31423391/77240564-9a8ca400-6c3b-11ea-86fc-33ae9d6db356.png)

The Log output of `pub --trace get` can be found [here](https://pastebin.com/q2ecUfmi)

**Comment by sigurdm** [comment]
What os are you using?

What does `gzip --version` and `tar --version` print?

Maybe this would be solved by: https://github.com/dart-lang/pub/pull/2382

**Comment by sigurdm** [comment]
We no longer rely on system tar/gzip.

Closing assuming stale.
