### ISSUE TITLE
pub outdated is missing colors when integrated into Flutter

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2385]
# Repro steps

Integrate pub outdated into Flutter:

Patch in https://github.com/mit-mit/flutter/commit/e5b40151ad88e69c658c1c7bd0a6ac454db5a404

$ cd ~/dev/pub
$ dart --snapshot=pub.dart.snapshot bin/pub.dart
$ cp pub.dart.snapshot ~/dev/flutter/bin/cache/dart-sdk/bin/snapshots/
$ rm ~/dev/flutter/bin/cache/flutter_tools.snapshot
$ flutter outdated

Test on a package:
$ cd ~/tmp
$ git clone https://github.com/google/charts.git
$ cd charts/charts_flutter
$ flutter pub get
$ flutter pub outdated

=> colors are missing; running `outdated --format=color` restores them

**Comment by mit-mit** [comment]
cc @jonahwilliams, does the flutter tool do anything special for stdin? @sigurdm says pub is testing for `stdin.hasTerminal` ?

**Comment by sigurdm** [comment]
@jonasfj suggest pub should be run with mode: `io.ProcessStartMode.inheritStdio`. That would let pub see the original stdout.

**Comment by mit-mit** [comment]
I tried this patch https://gist.github.com/mit-mit/ed6d04c8459361916a98e559839259ad, but that doesn't seem to fix it. Is there something else we can try?

**Comment by sigurdm** [comment]
This works on flutter master now.
