### ISSUE TITLE
pub "check" command – validate my dependencies for outdated, discontinued, bad versions, etc

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#2388]
* post the set of package + versions to the pub server (but ONLY those hosted on the server)
* get a JSON response outlining any issues with those packages + versions
  * outdated
  * discontinued
  * version marked broken

This could be run automatically when users run `pub get` and `pub upgrade` (without --offline)

See also

https://github.com/dart-lang/pub/issues/2165 - support arbitrary messages from pub server
https://github.com/dart-lang/pub/issues/2361 - warn about discontinued
https://github.com/dart-lang/pub-dev/issues/378 - allow marking a specific package version as broken

**Comment by kevmoo** [comment]
Implementation suggestion: support a general response from the server (see https://github.com/dart-lang/pub/issues/2165) so the server can provide new types of messages to the client without the client knowing every possible response)

etc etc

**Comment by cedx** [comment]
Very useful feature: other package managers (i.e. npm, composer) have a similar "outdated" command which I use regularly in order to know if I should update the version constraint of my dependencies.

**Comment by sigurdm** [comment]
Parts of this is covered by `pub outdated`.

We still want to implement some handling of discontinued (and versions marked broken) that is covered by issue: https://github.com/dart-lang/pub/issues/2361
