### ISSUE TITLE
`pub outdated --format=json` should not print "Resolving..."

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2391]
From my CLI:
```
pub outdated --format=json
{esolving... (1.8s)
  "packages": [
    {
      "package": "http_parser",
      "current": "3.1.3",
      "upgradable": "3.1.4",
      "resolvable": "3.1.4",
      "latest": "3.1.4"
    }
  ]
}
```

If format is `json`, I propose that we don't show any spinners :)

**Comment by jonasfj** [comment]
Note, I think this is only an issue in the terminal if I do: `pub outdated --format=json | tee` then I don't get any spinners.

```
pub outdated --format=json | tee
{
  "packages": [
    {
      "package": "http_parser",
      "current": "3.1.3",
      "upgradable": "3.1.4",
      "resolvable": "3.1.4",
      "latest": "3.1.4"
    }
  ]
}
```

**Comment by sigurdm** [comment]
It does terminal detection, but I agree. json-formatting will probably be mainly for programmatic use, and then showing the progress never makes sense
