### ISSUE TITLE
pub outdated format option

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#2393]
`outdated` has a `--format` option:

```
--format=<FORMAT>          Defines how the output should be formatted. Defaults to color when connected to a terminal, and no-color otherwise.
```

- the docs don't specify what we should use for `FORMAT`
- if this flag just controls using ansi colors, I would either remove it entirely and rely on ansi console detection, or, add a `--[no-]color` option to the main pub command

**Comment by sigurdm** [comment]
Good point - --[no-]-color might be better

**Comment by sigurdm** [comment]
There is also the --format=json option. But as you point out it was not documented.

It could have its own flag

--[-no]-color
--json

**Comment by devoncarew** [comment]
Some tools use `--machine` to indicate that it will output in a json format. That's less of a ~standard though than using `--no-color` to indicate turning off ansi detection.
