### ISSUE TITLE
pub outdated mark option

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#2395]
I'm unclear what the `mark` option does.

```
    --mark=<OPTION>            Highlight packages with some property in the report.
                               [outdated (default), none]
```

Do we need an option for this? I feel like we can just determine the best presentation for the report w/o having a user flag for it.

**Comment by sigurdm** [comment]
Yes this option is amputated currently. It is the plan to have options for marking null-safety and perhaps tags from pub.dev. That is planned for the first release supporting null-safety.

But we could remove it until then. @jonasfj what do you think.

**Comment by jonasfj** [comment]
@sigurdm, we can just hide the flag from `--help`... `package:args` has an option for this..
