### ISSUE TITLE
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.

### ISSUE THREAD

**Issue by atajohny** [dart-lang/pub#2396]

**Comment by sigurdm** [comment]
Could you reproduce your pubspec.yaml?
Please post a stack trace from `flutter pub get --trace`.

Can you access pub.dartlang.org in a browser?
Are you behind a firewall?
Are you in China?
Has this worked for you before?

**Comment by sigurdm** [comment]
Closing as inactive for now.

Please reopen with more information
