### ISSUE TITLE
HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by Yasha-dev** [dart-lang/pub#2433]
Having this issue for 3 days now . Cannot get any package from pub. When there is no dependency added the command shows no error.
#result of flutter pub get
```
Running "flutter pub get" in promedia...                 
OS Error: Connection reset by peer, errno = 104, address = storage.googleapis.com, port = 53940                    
pub get failed (server unavailable) -- attempting retry 1 in 1 second... 

Tried 'flutter clean' and flutter pub cache repair. result:
nspiron-5559:~/Desktop/work-space/promedia$ flutter pub cache repair
Resetting Git repository for assets_for_android_views 0.1.0...
Downloading _discoveryapis_commons 0.1.9...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
Failed to repair _discoveryapis_commons 0.1.9 from https://pub.dartlang.org. Error:
SocketException: OS Error: Connection reset by peer, errno = 104, address = storage.googleapis.com, port = 54110
Downloading analyzer 0.38.5...
Failed to repair analyzer 0.38.5 from https://pub.dartlang.org. Error:
HandshakeException: Connection terminated during handshake
Downloading analyzer_plugin 0.2.1...
Failed to repair analyzer_plugin 0.2.1 from https://pub.dartlang.org. Error:
HandshakeException: Connection terminated during handshake
Downloading archive 2.0.11...
Failed to repair archive 2.0.11 from https://pub.dartlang.org. Error:
HandshakeException: Connection terminated during handshake
Downloading args 1.5.2...
Failed to repair args 1.5.2 from https://pub.dartlang.org. Error:
HandshakeException: Connection terminated during handshake
Downloading async 2.4.0...
Failed to repair async 2.4.0 from https://pub.dartlang.org. Error:
HandshakeException: Connection terminated during handshake
Downloading battery 0.3.1+4...
Failed to repair battery 0.3.1+4 from https://pub.dartlang.org. Error:
SocketException: OS Error: Connection reset by peer, errno = 104, address = storage.googleapis.com, port = 54256
```

Here is the version details
```
flutter --version
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (8 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```
OS: Ubuntu 18.04lts

**Comment by Yasha-dev** [comment]
I can access `pub.dev ` from browser and ping from terminal is OK too.

I dont think I am behind corporate proxy and my location is Bangladesh. I did notice one thing while reinstalling everything. The flutter sdk is not available to download to me if i don't use vpn. 

Can't download `https://storage.googleapis.com/pub-packages/packages/retry-3.0.0%2B1.tar.gz`

Here is the report 
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.217.26.208...
* TCP_NODELAY set
* Connected to storage.googleapis.com (172.217.26.208) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 
`

Just a quick note though it was working fine till 2-3 days ago. No network setting was changed (in my device at least).

**Comment by mdrashedbinkuddus** [comment]
Same problem here. I am also from Bangladesh. I tried every solution I found on the internet. One of my friends can't download the `https://storage.googleapis.com/pub-packages/packages/retry-3.0.0%2B1.tar.gz`

**Comment by kiran-cmyk** [comment]
Hello All, I am also facing the same issue. Please let me know if there is a workaround.

I am behind corporate proxy.

I am able to download from https://storage.googleapis.com/pub-packages/packages/retry-3.0.0%2B1.tar.gz

Get TLS error during flutter pub get.

**Comment by Tarikul711** [comment]
This is a country-specific problem. In some countries, you got this error like Bangladesh and some African countries. I got a solution to this problem, that is use VPN software when you want to get Packages. VPN software uses other country's IP addresses where this google service works perfectly, So you can easily download packages.

**Comment by sigurdm** [comment]
For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china

Closing this issue now as it is very old, and not clear what we can do to improve access to pub.dev.
