### ISSUE TITLE
pub run doesn't support --enable-experiment=non-nullable

### ISSUE THREAD

**Issue by a-siva** [dart-lang/pub#2436]
@mit-mit commented on [Mon Apr 06 2020](https://github.com/dart-lang/sdk/issues/41355)

```
bin mit$ ./pub run --enable-experiment=non-nullable ~/tmp/app01/bin/main.dart
Could not find an option named "enable-experiment".
```

**Comment by jakemac53** [comment]
@kevmoo filed another issue somewhere - this likely need to be implemented in the batch script since pub itself most likely has to be launched with the experiment in order for its isolates to inherit it.

**Comment by kevmoo** [comment]
This should go back to the SDK. The way to implement this will be in the SDK wrapper scripts – not in code in this repo.
