### ISSUE TITLE
Warn when first null-safety compliant version of a package is published

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2439]
When a null-safety compliant version of an existing package is published for the first time, we should provide a warning with a link to the null-safety migration guide.

There are many pitfalls one can fall into when migrating, ideally the migration guide would have a check list and we can reference this check list.

note. We want to surface a warning containing a URL to the migration guide, this way the migration guide can be adjusted as lessons are learned.

**Comment by sigurdm** [comment]
This is when the sdk constraint lower bound crosses 2.10 and Not when all dependencies are null-safe etc..

 Right?

**Comment by sigurdm** [comment]
More questions: 

Should we display the warning when the immediately preceding version is not-opted in or if the latest published version is not opted in.

For example for existing versions:

* 0.5.0 (not opted in)
* 1.0.0 (opted in)

Should we warn when publishing 0.7 (opted in).

Also should we give some warning if you are about to opt-out of null-safety, if the preceding version was opted in?

**Comment by jonasfj** [comment]
> Also should we give some warning if you are about to opt-out of null-safety, if the preceding version was opted in?

I think that's a nice extension... I find the issue unlikely, but adding such a warning would be harmless.

**Comment by jonasfj** [comment]
> Should we display the warning when the immediately preceding version is not-opted in or if the latest published version is not opted in.

This sounds reasonable to me. Also can make sure to ignore preceding pre-release versions?
If the immediately preceding non-pre-release version is not null-safety opted in, then we give a warning.
