### ISSUE TITLE
flutter pub get error 403: Forbidden

### ISSUE THREAD

**Issue by HussamFarhat** [dart-lang/pub#2450]
hello there 
i'm trying to use flutter_staggered_grid_view so i went to pubspec.yaml file and i put this line under 
dependencies:
`flutter_staggered_grid_view: ^0.3.0` 
now , when i press get dependencies  i got this error below but just for you to know i'm from syria which some times we have a forbidden sites so i tried Psiphon and no thing happen :(
error message:

HTTP error 403: Forbidden
package:pub/src/http.dart 221:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>
dart:async                                      runZoned
package:pub/src/http.dart 279:10                withDependencyType
package:pub/src/entrypoint.dart 403:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching
dart:async                                      _completeOnAsyncReturn
package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling
dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run
    pub --trace '--verbosity=warning' get --no-precompile
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by sigurdm** [comment]
Is this the same for all packages, or specific to flutter_staggered_grid_view?
