### ISSUE TITLE
pub with git ,package name hasSubfix commit_id

### ISSUE THREAD

**Issue by HitlerHunter** [dart-lang/pub#2453]
in my subspec.yaml :
ybb_base_module:
    git:
      url: 'http://git.talkyun.com.cn/ybb_app_flutter/ybb_base_module.git'
      ref: v0.0.1

and then I'm pub get, the  package is auto named "ybb_base_module-e756f6e415a5afcfca565a0a95b73107a908ef05".
"e756f6e415a5afcfca565a0a95b73107a908ef05" is a commit's id in my git project.
what can i do to fix it? I'm just want  package named "ybb_base_module".

**Comment by sigurdm** [comment]
How does the pubspec.yaml of `ybb_base_module` look?

Remember you can use [code fencing ](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

Where does it have that name? How does your .dart_tool/package_config.json look?

**Comment by sigurdm** [comment]
Closing for lack of response.

Please reopen with more information if this issue persists.
