### ISSUE TITLE
 flutter_test from sdk doesn't exist 

### ISSUE THREAD

**Issue by majianquan** [dart-lang/pub#2454]
[flutter_music] flutter packages get
Running "flutter pub get" in flutter_music...                   
Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\jianquanma\AppData\Local\Temp\pub_7b2e3cb5-7fcf-11ea-acbe-8cec4ba0aab4\data.tar

Extracting  CHANGELOG.md
Extracting  LICENSE

Extracting  README.md
Extracting  android\build.gradle
Extracting  android\gradle.properties

Extracting  android\settings.gradle
Extracting  android\src\main\AndroidManifest.xml

Extracting  android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java
Extracting  android\src\main\java\io\flutter\plugins\pathprovider\StorageDirectoryMapper.java

Extracting  android\src\test\java\io\flutter\plugins\pathprovider\StorageDirectoryMapperTest.java
Extracting  example\README.md

Extracting  example\android\app\build.gradle

Extracting  example\android\app\gradle\wrapper\gradle-wrapper.properties
Extracting  example\android\app\src\androidTest\java\EmbeddingV1ActivityTest.java

Extracting  example\android\app\src\androidTest\java\MainActivityTest.java
Extracting  example\android\app\src\main\AndroidManifest.xml

Extracting  example\android\app\src\main\java\io\flutter\plugins\pathproviderexample\EmbeddingV1Activity.java

Extracting  example\android\app\src\main\java\io\flutter\plugins\pathproviderexample\MainActivity.java
Extracting  example\android\app\src\main\res\mipmap-hdpi\ic_launcher.png

Extracting  example\android\app\src\main\res\mipmap-mdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png

Extracting  example\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png
Extracting  example\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png

Extracting  example\android\build.gradle
Extracting  example\android\gradle.properties

Extracting  example\android\gradle\wrapper\gradle-wrapper.properties
Extracting  example\android\settings.gradle

Extracting  example\ios\Flutter\AppFrameworkInfo.plist
Extracting  example\ios\Flutter\Debug.xcconfig

Extracting  example\ios\Flutter\Release.xcconfig

Extracting  example\ios\Runner.xcodeproj\project.pbxproj

Extracting  example\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata

Extracting  example\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme
Extracting  example\ios\Runner.xcworkspace\contents.xcworkspacedata

Extracting  example\ios\Runner\AppDelegate.h
file example\ios\Runner\AppDelegate.m

already exists. Overwrite with 

example\ios\Runner\AppDelegate.m?
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 

ERROR: Can't allocate required memory!

package:pub/src/io.dart 943:7               _extractTarGzWindows.<fn>
===== asynchronous gap ===========================

package:pub/src/io.dart 820:20              withTempDir
package:pub/src/io.dart 914:10              _extractTarGzWindows

package:pub/src/io.dart 842:18              extractTarGz
package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 388:48      Entrypoint._get.<fn>

dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType

package:pub/src/entrypoint.dart 384:12      Entrypoint._get
dart:async                                  Future.wait

package:pub/src/entrypoint.dart 245:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub --trace '--verbosity=warning' get --no-precompile

---- Log transcript ----
FINE: Pub 2.7.2
IO  : Spawning "cmd /c ver" in E:\workspace_demo\flutter_music\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.17134.1184]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: fact: flutter_music is 1.0.0+1
SLVR: derived: flutter_music
SLVR: fact: flutter_music depends on flutter any from sdk
SLVR: fact: flutter_music depends on cupertino_icons ^0.1.2
SLVR: fact: flutter_music depends on path_provider ^1.6.5
SLVR: fact: flutter_music depends on flutter_test any from sdk
SLVR:   selecting flutter_music
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: path_provider ^1.6.5
SLVR:   derived: cupertino_icons ^0.1.2
SLVR:   derived: flutter any from sdk
IO  : Get versions from https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/path_provider.
IO  : HTTP GET https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/path_provider
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.7.2
IO  : HTTP response 200 OK for GET https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/path_provider
    | took 0:00:00.494832
    | date: Thu, 16 Apr 2020 10:47:36 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | content-length: 1632
    | strict-transport-security: max-age=31536000; preload
    | x-frame-options: SAMEORIGIN
    | content-type: application/json
    | via: 1.1 google
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: Caddy,Caddy,dart:io with Shelf
IO  : Get versions from https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/cupertino_icons.
IO  : HTTP GET https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/cupertino_icons
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.7.2
IO  : HTTP response 200 OK for GET https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/cupertino_icons
    | took 0:00:00.319042
    | date: Thu, 16 Apr 2020 10:47:36 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | content-length: 432
    | strict-transport-security: max-age=31536000; preload
    | x-frame-options: SAMEORIGIN
    | content-type: application/json
    | via: 1.1 google
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: Caddy,Caddy,dart:io with Shelf
SLVR:   fact: no versions of flutter_test from sdk match 0.0.0
SLVR:   derived: not flutter_test 0.0.0 from sdk
SLVR:   fact: flutter_test from sdk doesn't exist (the Flutter SDK is not available)
SLVR:   conflict: flutter_test from sdk doesn't exist (the Flutter SDK is not available)
SLVR:   ! flutter_test any from sdk is satisfied by flutter_test any from sdk
SLVR:   ! which is caused by "flutter_music depends on flutter_test any from sdk"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:00.888821 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.8s).
ERR : Because flutter_music depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available),
    |   version solving failed.
    |
    | Flutter users should run `flutter pub get` instead of `pub get`.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.catchError
    | package:pub/src/utils.dart 109:52                  captureErrors.<fn>
    | package:stack_trace                                Chain.capture
    | package:pub/src/utils.dart 122:11                  captureErrors
    | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand
    | dart:async                                         _completeOnAsyncReturn
    | package:pub/src/command_runner.dart                PubCommandRunner._validatePlatform
    | dart:async                                         _completeOnAsyncReturn
    | package:pub/src/io.dart                            runProcess.<fn>
---- End log transcript ----

**Comment by sigurdm** [comment]
You need to run `FLUTTER_ROOT=path/to/flutter pub --trace '--verbosity=warning' get --no-precompile` for the flutter sdk to be known.

We should improve this error message.

**Comment by sigurdm** [comment]
Closing this for lack of inactivity.

Please open a new issue with the correct trace if this issue persists.
