### ISSUE TITLE
 ‘major’ was called on null

### ISSUE THREAD

**Issue by rimidalv** [dart-lang/pub#2455]
# Environment

- `pub version` or `flutter pub version`:
- OS version:
- Are you using the Chinese community mirror or a corporate firewall?

# Problem

```yaml
<copy/paste pubspec.yaml>
```

## --trace output

```
<copy/paste the full output>
```

**Comment by sigurdm** [comment]
Curious - what version of pub where you running?
This sounds like it could be a bug in the LanguageVersionValidator, but that should not really be possible, because it has a null check here: https://github.com/dart-lang/pub/blob/master/lib/src/validator/language_version.dart#L58
