### ISSUE TITLE
Could not un-tar (exit code 2), can not open uptput file.

### ISSUE THREAD

**Issue by sivaramghanta** [dart-lang/pub#2459]
I'm trying to test a windows desktop supported project. so the flutter pub get or upgrade is failing with the error - can not open uptput file.

**Comment by sivaramghanta** [comment]
Running "flutter pub get" in flutter_test...                    
 Could not un-tar (exit code 2). Error:
 7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
 Processing archive: C:\Windows\Temp\pub_87103393-8322-11ea-ae27-f4d1086b3540\data.tar
 can not open output file .gitignore
 can not open output file .travis.yml
 can not open output file AUTHORS
 can not open output file CHANGELOG.md
 can not open output file CONTRIBUTING.md
 can not open output file LICENSE
 can not open output file README.md
 can not open output file data.csv
 can not open output file lib\src\generated\ascii_glyph_set.dart

**Comment by sigurdm** [comment]
That is weird.

What version of flutter are you using.

How is your pubspec.yaml?

Does this happen repeatedly or just once?

**Comment by sigurdm** [comment]
We no longer rely on the system tar

Closing this assuming stale.
