### ISSUE TITLE
pub get fail

### ISSUE THREAD

**Issue by luckberry** [dart-lang/pub#2464]
C:\src\flutter\bin\flutter.bat --no-color packages upgrade
Running "flutter pub upgrade" in demo1...                       

pub.flutter-io.cn%20 is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%20

                 ^

package:pub/src/source/hosted.dart 362:7                                              BoundHostedSource._throwFriendlyError

package:pub/src/source/hosted.dart 163:7                                              BoundHostedSource.doGetVersions

===== asynchronous gap ===========================

package:pub/src/source.dart 167:12                                                    BoundSource.getVersions

package:pub/src/solver/package_lister.dart 76:44                                      PackageLister._versions.<fn>.<fn>

dart:async                                                                            runZoned

package:pub/src/http.dart 272:10                                                      withDependencyType

package:pub/src/solver/package_lister.dart 75:33                                      PackageLister._versions.<fn>

dart:async                                                                            new Future.sync

package:async/src/async_memoizer.dart 43:42                                           AsyncMemoizer.runOnce

package:pub/src/solver/package_lister.dart 74:58                                      PackageLister._versions

package:pub/src/solver/package_lister.dart 111:21                                     PackageLister.countVersions

package:pub/src/solver/version_solver.dart 354:44                                     VersionSolver._choosePackageVersion.<fn>

package:pub/src/utils.dart 301:39                                                     minByAsync

package:pub/src/solver/version_solver.dart 350:25                                     VersionSolver._choosePackageVersion

package:pub/src/solver/version_solver.dart 97:22                                      VersionSolver.solve

===== asynchronous gap ===========================

package:pub/src/solver.dart 35:10                                                     resolveVersions.<fn>

package:pub/src/log.dart 378:18                                                       progress

package:pub/src/solver.dart 32:10                                                     resolveVersions

package:pub/src/entrypoint.dart 217:24                                                Entrypoint.acquireDependencies

package:pub/src/command/upgrade.dart 43:22                                            UpgradeCommand.run

package:args/command_runner.dart 197:27                                               CommandRunner.runCommand

package:pub/src/command_runner.dart 171:39                                            PubCommandRunner.runCommand.<fn>

dart:async                                                                            new Future.sync

package:pub/src/utils.dart 109:12                                                     captureErrors.<fn>

dart:async                                                                            runZoned

package:pub/src/utils.dart 126:5                                                      captureErrors

package:pub/src/command_runner.dart 171:13                                            PubCommandRunner.runCommand

===== asynchronous gap ===========================

package:pub/src/command_runner.dart 119:11                                            PubCommandRunner.run

C:\b\s\w\ir\cache\builder\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' upgrade --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub upgrade failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
Process finished with exit code 65

**Comment by sigurdm** [comment]
My guess is that you have an extra space character at the end of your PUB_HOSTED_URL.

**Comment by sigurdm** [comment]
Please reopen if fixing the PUB_HOSTED_URL did not work.
