### ISSUE TITLE
Pub get fails resolving with what pub outdated says is Resolvable

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2468]
Repro steps:

1. `git clone https://github.com/dart-lang/stagehand`
1. `cd templates/web-angular`
1. `pub get`
1. `pub outdated`

```
Dependencies                Current    Upgradable  Resolvable  Latest
all up-to-date

dev_dependencies
angular_test                2.3.0      2.3.0       2.4.0       2.4.0
build_test                  0.10.12+1  0.10.12+1   1.0.0       1.0.0
build_web_compilers         2.9.0      2.9.0       2.9.0       2.10.0
test                        1.6.3      1.6.3       1.14.2      1.14.2
```

1. Now, edit `pubspec.yaml` to `angular_test: ^2.4.0`
1. `pub get`

=>

```
Resolving dependencies...
Because angular_test >=2.4.0 depends on angular ^6.0.0-alpha+1 and __projectName__ depends on angular ^5.3.0, angular_test >=2.4.0 is forbidden.
So, because __projectName__ depends on angular_test ^2.4.0, version solving failed.
```

**Comment by jonasfj** [comment]
The resolvable column says that packages:
* `angular_test`
* `build_test`
* `build_web_compilers`
* `test`

Are resolvable together, and that you can get versions:
* `angular_test` version `2.4.0`
* `build_test` version `1.0.0`
* `build_web_compilers` version `2.9.0`
* `test` version `1.14.2`

However, you must upgrade everything in `pubspec.yaml` to allow these resolvable version ranges. Thus, you must upgrade `build_test` in `pubspec.yaml` to allow `1.0.0`.

-----
But it does seem we have an unfortunate corner case here. Where we don't show `angular` as outdated because the latest version is a pre-release. Yet, to get the latest resolvable version of `angular_test` you must upgrade `angular` to `^6.0.0-alpha+1` (in addition to `build_test`).

**Comment by mit-mit** [comment]
Ah, I had not thought of that corner case. Should outdated be resolving and reporting stable versions only?

**Comment by mit-mit** [comment]
Also, actually upgrading to those pre-releases leads to this interesting outdated report:

```
Dependencies            Current         Upgradable      Resolvable      Latest
angular                 6.0.0-alpha+1   6.0.0-alpha+1   6.0.0-alpha+1   5.3.1
angular_components      0.14.0-alpha+1  0.14.0-alpha+1  0.14.0-alpha+1  0.13.0+1

dev_dependencies
build_web_compilers     2.9.0           2.9.0           2.9.0           2.10.0

transitive dependencies
analyzer                0.37.1+1        0.37.1+1        0.37.1+1        0.39.8
dart_style              1.2.10          1.2.10          1.2.10          1.3.6
front_end               0.1.21+1        0.1.21+1        0.1.21+1        0.1.29
intl                    0.15.8          0.15.8          0.15.8          0.16.1
kernel                  0.3.21+1        0.3.21+1        0.3.21+1        0.3.29
protobuf                0.13.16+1       0.13.16+1       0.13.16+1       1.0.1
source_gen              0.9.4+4         0.9.4+6         0.9.4+6         0.9.5

transitive dev_dependencies
bazel_worker            0.1.21          0.1.21          0.1.21          0.1.23+1
boolean_selector        1.0.5           2.0.0           2.0.0           2.0.0
build_modules           2.8.1           2.8.1           2.8.1           2.9.0
build_resolvers         1.2.1           1.2.1           1.2.1           1.3.7
shelf_packages_handler  1.0.4           2.0.0           2.0.0           2.0.0
```

**Comment by jonasfj** [comment]
> ```
> angular                 6.0.0-alpha+1   6.0.0-alpha+1   6.0.0-alpha+1   5.3.1
> ```

This highlights a different issue to me.

**Comment by mit-mit** [comment]
Opened https://github.com/dart-lang/pub/issues/2469 for that

**Comment by sigurdm** [comment]
I think this would be solved by: https://github.com/dart-lang/pub/issues/2471. Closing in favor of that.
