### ISSUE TITLE
Some `pub outdated` colors disappear on black background

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub#2473]
# Environment

- `pub version` or `flutter pub version`: Pub 2.8.0-20.11.beta
- OS version: macOS Catalina

# Problem

If you have a terminal with a black background, some of the output of `pub outdated` isn't visible. 

White backgrounds seem to be fine. I tested this using the Mac Terminal command with a custom black, Pro (black), Homebrew (black), and Basic (white) profiles.

Black background (custom profile):
![image](https://user-images.githubusercontent.com/2164483/80776177-909d7100-8b16-11ea-9df0-3de3b3dbe143.png)

With selection:
![image](https://user-images.githubusercontent.com/2164483/80776206-a874f500-8b16-11ea-993b-34674562e55e.png)

Black background (Homebrew):
![image](https://user-images.githubusercontent.com/2164483/80776728-e1619980-8b17-11ea-9aca-34b0ec140f56.png)

With selection:
![image](https://user-images.githubusercontent.com/2164483/80776716-dad32200-8b17-11ea-84ec-43a31517024f.png)

**Comment by sigurdm** [comment]
Interesting - these are supposed to be grey and show up as such in my black-background terminal...

**Comment by sigurdm** [comment]
We are using "bold black" as grey. It seems some terminals do not display 'bold' as a brighter color: https://apple.stackexchange.com/questions/21517/how-do-i-get-the-mac-terminal-to-show-the-gray-font-color

**Comment by sigurdm** [comment]
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

Using bold-black as grey keeps us within 4-bit colors (with bold-extension).

I guess most terminals today supports at least 255 colors, so we could probably get away with Bright Black.

Unfortunately I don't think we have a reliable way of detecting if 255 colors are supported.
