### ISSUE TITLE
Using Lanten proxy error

### ISSUE THREAD

**Issue by medz** [dart-lang/pub#2497]
```
Building flutter tool...
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                         _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync
package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run

    pub --trace upgrade '--verbosity=error' --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

After using the Lantern proxy, I run pub get and report an error. But the problem has been solved in https://github.com/dart-lang/sdk/issues/37808!

My Dart version is 2.8.2

**Comment by jonasfj** [comment]
Hmm, sounds like an issue with the underlying HttpClient... @medz are you sure https://github.com/dart-lang/sdk/issues/37808 have been fixed? (what flutter and dart version?)

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/82310749-5a596000-99f7-11ea-83ee-791760caaf82.png)

@jonasfj In the final reply of https://github.com/dart-lang/sdk/issues/37808 , the developers of the sdk library believe that it has been fixed, and the corresponding https://github.com/dart-lang/sdk/commit/236dd991e540e26db22473998cc5354051464bf1 The commit includes 2.8.2 Tag, but this problem still exists.

I haven't tested whether writing the service code in Dart still has this bug. But confirm that this bug still exists in the Pub tool!

![image](https://user-images.githubusercontent.com/5564821/82311065-ca67e600-99f7-11ea-9c5b-7242b40044ab.png)

**Comment by medz** [comment]
@jonasfj https://github.com/dart-lang/sdk/issues/37808#issuecomment-606039293

![image](https://user-images.githubusercontent.com/5564821/82311316-1f0b6100-99f8-11ea-9648-6a37eceaf758.png)

**Comment by jonasfj** [comment]
> I haven't tested whether writing the service code in Dart still has this bug.

We probably have to start here :)

Can we check if `HttpClient` works:
```dart
import 'dart:io';

Future<void> main() async {
  final c = HttpClient();
  final req = await c.getUrl(Uri.parse('https://httpbin.org/get'));
  final res = await req.close();
  print('Status: ${res.statusCode}'); // should print: Status 200
  await res.drain();
  c.close(force: true);
}
```

If this doesn't work, then it's likely not `pub` specific, and we'll have to track down the issue in `dart:io`.

Background: The `pub` command is written in Dart, and uses the same Dart version as the Pub Version reported by `pub --version` (or `flutter pub --version`).

**Comment by medz** [comment]
@jonasfj 
![image](https://user-images.githubusercontent.com/5564821/82430773-6bba6f00-9ac0-11ea-86c0-44c9d30836be.png)

The not using Lantern proxy run command options:

![image](https://user-images.githubusercontent.com/5564821/82430821-7e34a880-9ac0-11ea-8694-2fd84a2d96f7.png)

=========================

Using Lantern proxy run command options:
![image](https://user-images.githubusercontent.com/5564821/82431031-ba680900-9ac0-11ea-8bef-167c6e5a9bea.png)


====================

Using other VPN proxy run command option:

![image](https://user-images.githubusercontent.com/5564821/82431230-fd29e100-9ac0-11ea-9c10-0d7b4c21dd75.png)

**Comment by medz** [comment]
@jonasfj As can be seen from the above results, the problem is the bug of http-client described in https://github.com/dart-lang/sdk/issues/37808, and Dart io has not fixed it. It really fixes this bug.

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/82431892-dc15c000-9ac1-11ea-8b05-ef1f69cdc759.png)

**Comment by medz** [comment]
@jonasfj  Please forgive me for submitting this issue here, because in the Dart / sdk issue the developer finally concluded that the issue has been fixed in 2.8.x and above. But I still use 2.8.2! So wrongly think that this is a problem with the Pub tool!😫

If the VPN proxy cannot be handled correctly, it is too painful for the programmers in the network authorized area!

**Comment by medz** [comment]
Lantern is very stable in China, so Lantern is a very popular VPN proxy software in China

**Comment by jonasfj** [comment]
> Lantern is very stable in China, so Lantern is a very popular VPN proxy software in China

There are some [mirrors in china](https://flutter.dev/community/china).

@medz, can you try using the [Dart SDK (download here)](https://dart.dev/get-dart)?
So run `dart get.dart` (assuming `get.dart` is the file I paste above).

**Comment by medz** [comment]
@jonasfj Yes, there is of course no problem using the mirror to download the contents of the package.

But we are also producers of packages, and we need to pub.dev to publish application packages. Then using VPN to log in to the goole account is the only way.

In addition, I think it is more convenient to use Dart & Flutter for application development now. The reality is that we need to release the package.

I do n’t think it ’s a good thing to use mirroring, maybe our government ca n’t realize it! Well, without discussing politics, it is difficult for a citizen to refute the government's decision.

VPN is perhaps the only way we can use the services well. 😫

**Comment by sigurdm** [comment]
I think we cannot really do anything more here - if anything this should be fixed on the sdk level I believe..

Closing for now.
