### ISSUE TITLE
pub.flutter-io.cn%EF%BC%9B is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)

### ISSUE THREAD

**Issue by 903328615** [dart-lang/pub#2505]
Working dir: D:\software\flutter\examples\hello_world
D:\software\dartsdk\2.8.2\bin\pub.bat get
Resolving dependencies...
pub.flutter-io.cn%EF%BC%9B is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%EF%BC%9B
                 ^
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                         _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync
package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run

    pub --trace get

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Process finished with exit code 65

**Comment by 903328615** [comment]
What should I do

**Comment by sigurdm** [comment]
It seems like you did not set up PUB_HOSTED_URL correctly (seems to have been uri-encoded somehow). Try following https://docs.flutter.dev/community/china).

Closing this for now as it is very old, and probably stale.

**Comment by rungnaphasealian2-a11y** [comment]
QR pay ditnow me QR QR w service xed price xed PR processo skillshop Puah shop Puah to talk GRAB taxi One wallet cards paypal pay tango live transfer go support Dev Worid class all Times mcptt 1xc expetoption mobile cross account msgbmk 4.900% 200ct CORP 2026
