### ISSUE TITLE
pub upgrade should also change version numbers in pubspec.yaml

### ISSUE THREAD

**Issue by rajveermalviya** [dart-lang/pub#2506]
Currently `pub upgrade` upgrade's the dependencies and changes the version numbers in only `pubspec.lock`, this makes it hard to discover what has been changed.
If the updated version numbers are also changed in `pubspec.yaml` it makes it easy to discover what's changed.

`pubspec.lock` also shows the transitive dependency's changes.
Updating the version numbers in `pubspec.yaml` would give a simple gist of upgraded direct dependencies, by a simple `git diff pubspec.yaml`.

**Comment by rajveermalviya** [comment]
For some reference, golang does something similar with go mod files.
when running `go get -u` (update dependencies command). It writes new version numbers in both 
`go.mod` (similar to `pubspec.yaml`) and `go.sum` (similar to `pubspec.lock`).

**Comment by jakemac53** [comment]
Wide version ranges are better in terms of making your package compatible with more versions of other packages, helping everybody else be able to get a version solve. We do not generally recommend increasing your lower bound on each pub upgrade.

Note that pub upgrade also lists a summary of the updated deps when you run the command which should serve as a good overview of what changed.

**Comment by mit-mit** [comment]
Closing as by-design

**Comment by sigurdm** [comment]
We have implemented 
```
pub upgrade --major-versions
```
That will upgrade the bounds in the pubspec.yaml to the latest versions resolving. Not entirely what is asked for here - but possibly useful anyway.

**Comment by minhqdao** [comment]
It's now:

```bash
flutter pub upgrade --major-versions --tighten
```

And:

```bash
dart pub upgrade --major-versions --tighten
```

I know this is an old issue, but I just researched it myself and thought this might be useful to some.
