### ISSUE TITLE
Getting package archive is empty(size = 0) error on publish.

### ISSUE THREAD

**Issue by frencojobs** [dart-lang/pub#2510]
# Environment

- `pub version`: 2.8.1
- `flutter pub version`: 2.8.3
- OS version: Windows 10
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

I am getting this error on `pub publish`.
```bash
Package archive is empty(size = 0)
```

I'm trying to bump a package from version 0.0.2 to version 1.0.0 because 
1. the code won't be changed or be updated
2. and to get a better score on pub.dev

I was fixing all the warnings from pub.dev by
1. changing lowercase `changelog.md` to `CHANGELOG.md`,
2. changing `readme.md` to `README.md` and
3. updating the package description to a longer and more descriptive one.

So, files updated were changelog and readme filenames, version and description in `pubspec.yaml`. 
The error does not occur during the `pub publish --dry-run`, the dry-run only says `package has 0 warnings.`

**Comment by jonasfj** [comment]
Are you on WSL?

**Comment by frencojobs** [comment]
No. I'm on PowerShell.

**Comment by frencojobs** [comment]
My bad. The error on having two readme files with one lowercase and one uppercase was undetectable on Windows, as it assumes both files to be one. I think these two files were bugging the pub. I removed them and now it seems to be working perfectly as expected.

**Comment by sigurdm** [comment]
I was not aware that was even possible to have two files differing only in casing on windfows.

Is this something we could detect and warn about from the pub client?
