### ISSUE TITLE
flutter创建项目失败

### ISSUE THREAD

**Issue by TmHaert** [dart-lang/pub#2515]
Creating project first_app...
pub.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%0D                                                    
                 ^                                                      
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================                      
dart:async                                         _CustomZone.runUnary 
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         
new Future.sync      package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_tools...                           
pub get failed (65; and include the logs in an issue on
https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment]
It looks like a malformed PUB_HOSTED_URL.

Closing as stale.

Please reopen if there still is a problem
