### ISSUE TITLE
Request for 'pub cache clean' in addition to Repair, Add

### ISSUE THREAD

**Issue by robinjohn** [dart-lang/pub#2521]
Raising this as a new issue as I didn't find an existing one.
Related one was old one linked below and probably sidelined or down-prioritised.

**Why:** flutter SDK is set up as local, and user can switch between flutter project/application repositories and also switch between flutter channels (beta/stable) which affects the common flutter environment. This involves pub to accumulate some cache old packages which user don't want to use anymore of some package worked many months or years before. Hence instead of repairing, user could prefer a complete new pub get on the flutter projects being work after cleaning cache and running pub get.

_Related to post by @nex3 in https://github.com/dart-lang/pub/issues/1587#issuecomment-331013040_

**Comment by sigurdm** [comment]
This should probably exist for completeness, but all it would do is equivalent to `rm -r $PUB_CACHE`, right?

**Comment by sigurdm** [comment]
Or should it be able to prune, leaving the dependencies of a specified number of projects behind...

**Comment by robinjohn** [comment]
Ideally it should be an equivalent of rm -r at this stage, just because most other pub commands don't take effect per project but rather to users development environment in general. 
(Sorry for my late response, didn't get notified here).

**Comment by robinjohn** [comment]
Linked Issue:
Relates to [https://github.com/flutter/flutter/issues/77029]
