### ISSUE TITLE
Usage error printing during script snapshot creation (first run only)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2525]
See this travis failure https://travis-ci.org/github/dart-lang/build/jobs/698366117#L289.

To reproduce you can check out the [build](https://github.com/dart-lang/build) repo, change to the `build_modules` directory, and run this command `dart $(pub run build_runner generate-build-script) test`, which prints:

```
Cannot specify arguments before a command.
Usage: dart [<vm-flags>] <command|dart-file> [<arguments>]
...
```

You can keep reproducing it by deleting the snapshot created for build_runner under `.dart_tool/pub/`.

If you separate the command into two separate lines it does work as expected:

```
pub run build_runner generate-build-script
dart .dart_tool/build/entrypoint/build.dart test
```

**Comment by natebosch** [comment]
This is because the command that `dart` sees is effectively `dart Precompiling test` or something  along those lines.

**Comment by jakemac53** [comment]
Oh right, that totally makes sense. Did this change from printing on stdout vs stderr or something possibly?

**Comment by sigurdm** [comment]
pub used to precompile on `pub get`.

But the precompilation  message should only be printed if there is an attached terminal. Looks like I broke that with the latest refactor.
