### ISSUE TITLE
Confusion with version_solver_test

### ISSUE THREAD

**Issue by OhMyBuggg** [dart-lang/pub#2533]
I have a question about test case "circular dependency" in file "pub/test/version_solver_test.dart" line 122.
Why circular dependency is acceptable in pub, I found that other package resolver like pip don't accept circular dependency.

**Comment by sigurdm** [comment]
Well - why is it not acceptable in pip?
Circular dependencies can often be useful.

**Comment by OhMyBuggg** [comment]
Sorry for my misunderstanding about pip's test case.
Actually circular dependency case in pip is xfail case, which means it expect to fail for some reason.
They said they does not complain about cycles, and there was no right and wrong.

So I just want to know why pub use this kind of test case.
Will there be some packages which have circular dependency?

**Comment by sigurdm** [comment]
https://groups.google.com/a/dartlang.org/g/misc/c/50ZyspG7Qcc/m/ltFybJH-BvEJ is an old, but still relevant answer to the same question.

Sometimes it can be convenient to split implementation over two packages even if they depend on each other.

**Comment by sigurdm** [comment]
Closing as stale
