### ISSUE TITLE
环境配置都通过了 ，编译项目一直报     pub --trace '--verbosity=warning' get --no-precompile

### ISSUE THREAD

**Issue by androidhero** [dart-lang/pub#2537]
E:\FluterWorker\flutter_app>flutter packages get
pub.flutter-io.cn%20 is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at
character 18)
pub.flutter-io.cn%20
                 ^
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                         _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync
package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_app...
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

E:\FluterWorker\flutter_app>flutter packages get
pub.flutter-io.cn%20 is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at
character 18)
pub.flutter-io.cn%20
                 ^
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                         _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync
package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

**Comment by sigurdm** [comment]
`pub.flutter-io.cn%20` should not contain %20.
Somehow you got an extra space in your `PUB_HOSTED_URL`.

**Comment by sigurdm** [comment]
Closing as stale. Please reopen if this issue is still a problem, and the solution didn't help.
