### ISSUE TITLE
Path dependency on an existing, but not-valid path gives poor error message

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#2539]
cc @dcharkes 

With a path dependency on eg. `..` (exists, but there is no pubspec.yaml:
```
/home/a $ pub get
Resolving dependencies... 
Could not find a file named "pubspec.yaml" in "home/".
```
Note that the dependency name doesn't occur in the error message.

But if the path (here "../../../../ffigen") doesn't exist we get an easier to understand message like:

```
$ pub get
Resolving dependencies... 
Because sqlite3 depends on ffigen from path which doesn't exist (could not find package ffigen at
  "../../../../ffigen"), version solving failed.
```

**Comment by bsutton** [comment]
I just got burnt on this same issue.
I thought for some reason it couldn't find the local pubsec.yaml.
It took me fifteen minutes to realise that it was complaining because of a relative dependency.

**Comment by sigurdm** [comment]
This was fixed in the linked PR
