### ISSUE TITLE
Hardcoded tar paths are problematic in some environments

### ISSUE THREAD

**Issue by themightychris** [dart-lang/pub#2546]
I just went through a pretty gnarly bug hunt caused by [the hardcoding of `tar` paths](https://github.com/dart-lang/pub/blob/03b7f9a5a27f46bf554f2a3bdef965e7354c69b0/lib/src/io.dart#L829)

I'm running pub in a Chef Habitat environment, where `PATH` gets managed based on application dependencies. So path looks something like `PATH=/hab/pkgs/core/coreutils/8.30/20200305231640/bin:/hab/pkgs/core/tar/1.32/20200305233447/bin:...` rather than something like `PATH=/bin:/usr/bin`.

So my environment provides an appropriate version of GNU `tar` via `$PATH`, and then pub goes and uses `/bin/tar` instead even though `/bin` isn't in PATH, and it finds a busybox version of tar that doesn't support all the options it uses

Is this hardcoding of paths necessary? Could it be a fallback behavior instead if no `tar` is found in PATH?

**Comment by jonasfj** [comment]
Hmm, using `tar` from `PATH` has other issues on other platforms...

@sigurdm did we find somewhere in POSIX where it said that `tar` was always in `/bin/tar`?
Maybe we should make `pub` able to work with busybox tar...

Or maybe we just need to write a proper tar library in Dart.

**Comment by themightychris** [comment]
Would it be too expensive or uncacheable across big ops to interrogate --version upfront and pick a best tar from PATH and standard locations?

Currently the only fix is to stick GNU tar on top of the BusyBox /bin/tar in all my envs

**Comment by sigurdm** [comment]
> Is this hardcoding of paths necessary? Could it be a fallback behavior instead if no tar is found in PATH?

I seem to remember we did that to avoid some other problems where a stray tar in the path would override the working one from the system installation... hard to please everyone :)

https://github.com/dart-lang/pub/issues/2286

> Or maybe, in the shorter term, at least provide an env var for explicitly overidding tar path?

That would be simple, and at least provide a workaround for all those hard-to-reach edge cases!

> @sigurdm did we find somewhere in POSIX where it said that tar was always in /bin/tar?
Maybe we should make pub able to work with busybox tar...

I think that was https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.pdf . It is not posix, but linux.

> ? Would it be too expensive or uncacheable across big ops to interrogate --version upfront and pick a best tar from PATH and standard locations?

I don't think it would be too expensive. But we would need to investigate and encode knowledge of all working  tar implementations and their `--version` output. That sounds like a bigger job than implementing tar itself.

**Comment by themightychris** [comment]
> I don't think it would be too expensive. But we would need to investigate and encode knowledge of all working tar implementations and their --version output. That sounds like a bigger job than implementing tar itself.

I think all that really needs to be done is checking whether it's GNU tar of a sufficient minimum version, it seems to be pretty common for `./configure` scripts to sniff for GNU tar and use that as the standard. Given that crashes already result from use of options only GNU `tar` has I don't think there's much value in worrying about non-GNU tar's that could theoretically work too. Weird obscure failures happen otherwise, and neither using `/bin/tar` or using what's in PATH is a safe assumption.

By expensive, what I was wondering is for example, in a high-level flutter command that maybe invokes `pub` thousands of times, would there be any way to avoid shelling out to `tar --version` at the start of every single `pub` invocation?

**Comment by jonasfj** [comment]
This should be fixed in Dart 2.14

> Pub now uses a Dart library to read and write tar files. This should fix several issues we had with incompatibilities between different system tars.

https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2140
