### ISSUE TITLE
????

### ISSUE THREAD

**Issue by hechao633139** [dart-lang/pub#2547]
pub.flutter-io.cn%20 is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%20
                 ^
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                         _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync
package:pool/pool.dart 126:18                      Pool.withResource.<fn>

**Comment by jonasfj** [comment]
You probably have whitespace in your `PUB_HOSTED_URL` environment variable.

In either case, please provide more information if you think there is a bug somewhere.
