### ISSUE TITLE
`pub publish` http request is not sent to `PUB_HOSTED_URL`

### ISSUE THREAD

**Issue by MisterJimson** [dart-lang/pub#2551]
# Environment

- Tested on `Pub 2.7.2` and `Pub 2.8.4`
- OS version: macOS 10.15.5
- Are you using the Chinese community mirror or a corporate firewall? No.

# Problem
The `pub publish` upload http request is not sent to `PUB_HOSTED_URL`
## Expected behavior
When publishing a package with `pub publish` or `flutter pub publish` the first request should be a GET made to `PUB_HOSTED_URL/api/packages/versions/new` to get the URL for where to upload the tar to.

## Actual behavior
Instead only the host of the value exported as `PUB_HOSTED_URL` is extracted and used for this specific call. 

`<host-only>/api/packages/versions/new`

An example of why this is a problem. If I want to host my private pub server at `www.mycompany.com/devtools/pub` the request is made to:

`www.mycompany.com/api/packages/versions/new`
instead of
`www.mycompany.com/devtools/pub/api/packages/versions/new`

Note that this seems to be the **only** request that does this. `<PUB_HOSTED_URL>/api/packages/<PACKAGE>` correctly uses the value in `PUB_HOSTED_URL` and the server seems to fully support all projects I work with expect for publishing.

**Comment by MisterJimson** [comment]
@tusharojha I would suggest working off of this PR #2273

**Comment by sigurdm** [comment]
This was fixed by https://github.com/dart-lang/pub/pull/3778
