### ISSUE TITLE
Pub get not stopping after 5 retries

### ISSUE THREAD

**Issue by Pe-te** [dart-lang/pub#2553]
Hi,

According to issue https://github.com/dart-lang/pub/issues/2049 the "pub get" should stop after 5 retries.

But for some reason it is retrying hundreds of times when it is called during the flutter build process?

Our "problem" was that someone checked in a url with ssh:// instead of https://, which is not supported on our infrastructure, but I think any other problem would/could trigger that behaviour?

Any ideas? Is this a flutter problem or general pub?

> Git error. Command: `git clone --mirror ssh://git@git.ourcompany.com:7999/project/myprojectname.git /Users/jenkins/.fluttersdk/.pub-cache/git/cache/myprojectname-5137927b676a3995b2bd36ebabf80adc51e89ca3`
stdout: 
stderr: Cloning into bare repository '/Users/jenkins/.fluttersdk/.pub-cache/git/cache/myprojectname-5137927b676a3995b2bd36ebabf80adc51e89ca3'...
Repository nicht gefunden
Das angeforderte Repository existiert nicht oder Sie sind nicht zugriffsberechtigt.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
exit code: 128
pub get failed (server unavailable) -- attempting retry 232 in 64 seconds...

**Comment by jonasfj** [comment]
This is a bug in flutter_tools, when wrapping `pub` they retry indefinitely.

**Comment by Pe-te** [comment]
Related issue for anyone who comes along:
https://github.com/dart-lang/pub/issues/2242
