### ISSUE TITLE
Don't advertize prerelease packages in `pub get`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2555]
Running `pub get` on just about any project now shows the new prerelease nullsafety packages, e.g.:

```
Resolving dependencies... (2.6s)
+ _fe_analyzer_shared 5.0.0
+ analyzer 0.39.12
+ args 1.6.0
+ async 2.4.2
+ benchmark_harness 1.0.5
+ boolean_selector 2.0.0
+ charcode 1.1.3
+ collection 1.14.13 (1.15.0-nnbd available)
+ convert 2.1.1
+ coverage 0.14.0
+ crypto 2.1.5
...
```

We should prune the "available" messages to not show prerelease versions

**Comment by mit-mit** [comment]
Potential fix: Remove the `if else` from https://github.com/dart-lang/pub/blob/master/lib/src/solver/report.dart#L253 ?

**Comment by jonasfj** [comment]
Fixed in https://github.com/dart-lang/pub/pull/2556
