### ISSUE TITLE
Concrete example of multiple derived incompatibilities?

### ISSUE THREAD

**Issue by mpizenberg** [dart-lang/pub#2558]
PubGrub solver guide mentions in the ["Error Reporting"][error-reporting] section the eventuality of an incompatibility to cause multiple derived incompatibilities. This property prevents using a simple binary tree if we want to identify those nodes, in favor of a graph (a DAG).

I've been implementing PubGrub in another language, and would like to verify the behavior of the reporting code in such a case. I can't find however any example for that. Even the ["Branching Error Reporting"][example] does not contain such incompatibilities causing multiple derived others in the graph.

I'm trying to come up with an example for this but didn't found how yet. Maybe pub already has a test case for this that I didn't find (I'm not familiar with pub's code base)?

[error-reporting]: https://github.com/dart-lang/pub/blob/master/doc/solver.md#error-reporting
[example]: https://github.com/dart-lang/pub/blob/master/doc/solver.md#branching-error-reporting

**Comment by sigurdm** [comment]
Sorry this issue has gotten old. I'm not sure I can give you an answer off-hand. Is this still relevant to you?

**Comment by mpizenberg** [comment]
Hey, indeed this isn’t relevant to me anymore ^^. Thanks for asking
