### ISSUE TITLE
"Global activate" is not updating to last available version. 

### ISSUE THREAD

**Issue by JSeppl** [dart-lang/pub#2564]
Newly activating stagehand not updates to latest version.

Package stagehand is currently active at version 3.3.7.
Resolving dependencies...

stagehand 3.3.7 (3.3.9 available)
Precompiling executables...
Precompiled stagehand:bin\stagehand.
Installed executable stagehand.
Activated stagehand 3.3.7.

**Comment by jonasfj** [comment]
What is your dart SDK version?

**Comment by sigurdm** [comment]
Closing, assuming stale
