### ISSUE TITLE
Can we ignore some files for publishing but include in the repo?

### ISSUE THREAD

**Issue by vincevargadev** [dart-lang/pub#2566]
I'd like to leave some files in a package's repository on GitHub, but at the same time, make those files excluded when I publish a package on pub.dev.

The issue is that I'd like to add images or gifs to the README so that other developers immediately understand what the package is for. However, I don't want users of my package to have to download these images when they decide to add my package as a dependency.

Can we ignore some files for publishing but include in the repo?

**Comment by sigurdm** [comment]
I think we should have a .pubignore or similar file.
@jonasfj what do you think?

**Comment by jonasfj** [comment]
We already respect `.gitignore` I think, but I can see how that doesn't work here.

Other possible use-case in https://github.com/dart-lang/pub/issues/2222.

I imagine that if you have a `.pubignore` file, then we would not honor the `.gitignore` file.

**Comment by sigurdm** [comment]
It seems we can use `git ls-files -X .pubignore --cached --others` to interpret a `.pubignore` file.

That would however put a requirement on git - which might be acceptable if we still allow having no .pubignore file.

**Comment by jonasfj** [comment]
> That would however put a requirement on git - which might be acceptable if we still allow having no .pubignore file.

External dependencies provided by the system, such as `tar` haven't exactly worked out well for us before, hehe

I suppose it works better for `.gitignore`, but ideally we would write this logic in Dart.

**Comment by jonasfj** [comment]
On the other hand, we can test if `git` is present, and we already use it.. so this might not be so bad..

**Comment by sigurdm** [comment]
>  ideally we would write this logic in Dart.

It is quite well specified: https://git-scm.com/docs/gitignore , but not trivial to implement.

Funnily enough we hardly ever get issues around our external dependency on git. I guess there is only one implementation that everybody shares.

Most of our tar issues seem to stem from the system tar being different for different systems.

**Comment by softmarshmallow** [comment]
Is there any plans on supporting .pubignore or ingore: ["", ""] in pubspec?
the suggested ways are just temporary workaround

**Comment by jonasfj** [comment]
> Is there any plans on supporting .pubignore or ingore: ["", ""] in pubspec?

I don't think it's a high priority for us at the moment. But if someone wants to work on it, I'll be happy to help define the feature, review and land it.

Otherwise, please upvote, and mention any novel use-cases you might have.
