### ISSUE TITLE
pub outdated should respect allowed_experiments.json

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2574]
See: https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/allowed_experiments.json

Package names in this file can opt-into null-safety with language version 2.10, so we need to update our detection logic.

**Comment by jonasfj** [comment]
Also 2.10 will no longer ship language version by default.

**Comment by sigurdm** [comment]
I need more details here.

Is the allowed_experiments.json file documented somewhere?

Do we know what version of the sdk will have NNBD by default?

**Comment by jonasfj** [comment]
> Do we know what version of the sdk will have NNBD by default?
No, we'll have to update this as versions roll.

> Is the `allowed_experiments.json` file documented somewhere?

Not really, my understanding is that if a package has the `non-nullable` experiment enabled, then language version `>= 2.10` means it's opted-into null-safety.

---------------------------
I don't think it's critical that we do ship this, but it would be nice for the tech-preview, as it would make `dart migrate` work without `--skip-pub-outdated` during the preview.

note. even with this `--skip-pub-outdated` will still be necessary if using `dependency_overrides` for other packages than those in the `allowed_experiments.json` list. We could consider simply interpreting `2.10` as opting into null-safety, as if we had an implicit `--enable-experiments=non-nullable` flag always passed (as calling without it makes little sense). However, it would be critical that this be changed before a final release, if we go down this path.

**Comment by sigurdm** [comment]
Should we close this?

**Comment by jonasfj** [comment]
Yes, experiments are probably going to be so important going forward.
