### ISSUE TITLE
Erroneous red error text on pub lish but no listed errors

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2581]
# Environment

Pub 2.10.0-edge.b61f57bcca1e1abf02216ced35d781e81d145451

# Problem

When trying to publish package:collection I got the following:

![image](https://user-images.githubusercontent.com/984921/88187456-66c28a80-cbeb-11ea-911f-6fd1c0ff701d.png)

This mentions 1 "hint" but I don't see anything other than `Uploads to pub.dev are subject to https://pub.dev/policy` (That might be the hint it is referring to? But it has nothing to do with this project...).

## Expected behavior

I would expect no colors in my output or "success" colors like green indicating it was safe to publish. Red should be reserved for dangerous scenarios where a likely error is present.

Using red all the time will train people to ignore it.

**Comment by sigurdm** [comment]
That is embarrassing :| we calculate the hints, but do not print them...

The only hints until now are: https://github.com/dart-lang/pub/blob/master/lib/src/validator/relative_version_numbering.dart#L52 so that is probably what happens to your package.
