### ISSUE TITLE
pub --trace '--verbosity=warning' get --no-precompile

### ISSUE THREAD

**Issue by JMFreed** [dart-lang/pub#2586]
I am trying to add a new Font family to the pubspec.yaml file of a Flutter project.

Class 'YamlList' has no instance method 'containsKey'.
Receiver: Instance of 'YamlList'
Tried calling: containsKey("version")
dart:core                                                                             Object.noSuchMethod
package:pub/src/lock_file.dart 132:24                                                 LockFile._parse.<fn>
dart:collection                                                                       MapMixin.forEach
package:pub/src/lock_file.dart 130:22                                                 LockFile._parse
package:pub/src/lock_file.dart 82:21                                                  new LockFile.load
package:pub/src/entrypoint.dart 96:28                                                 Entrypoint.lockFile
package:pub/src/entrypoint.dart 222:19                                                Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 394:18                                                       progress
package:pub/src/entrypoint.dart 216:24                                                Entrypoint.acquireDependencies
package:pub/src/command/get.dart 46:23                                                GetCommand.run
package:args/command_runner.dart 197:27                                               CommandRunner.runCommand
package:pub/src/command_runner.dart 191:39                                            PubCommandRunner.runCommand.<fn>
dart:async                                                                            new Future.sync
package:pub/src/utils.dart 113:12                                                     captureErrors.wrappedCallback
dart:async                                                                            runZoned
package:pub/src/utils.dart 130:5                                                      captureErrors
package:pub/src/command_runner.dart 191:13                                            PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 138:11                                            PubCommandRunner.run
C:\b\s\w\ir\cache\builder\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

Any help appreciated. Thanks

**Comment by sigurdm** [comment]
It looks like a bug in validating broken pubspec.lock files.

As a workaround I would try deleting your `pubspec.lock` and running `flutter pub get` again.

**Comment by JMFreed** [comment]
That did it, thank-you very much!

Should I close the issue now?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
