### ISSUE TITLE
why. "flutter packages get".    Wrong?

### ISSUE THREAD

**Issue by w8350196** [dart-lang/pub#2587]
Bad state: A https: URI should have a non-empty host name: https:https://pub.flutter-io.cn/api/packages/cupertino_icons
package:pub/src/source/hosted.dart 437:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 188:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================                      
dart:async                                         _CustomZone.runUnary 
package:pub/src/rate_limited_scheduler.dart 82:30  RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 85:30  RateLimitedScheduler._processNextTask
dart:async                                         new Future.sync      
package:pool/pool.dart 126:18                      Pool.withResource.<fn>
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_app...                             
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

"flutter Doctor".   You can see that the environment is all right

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.1)
[✓] Connected device (3 available)

**Comment by jonasfj** [comment]
Judging from the logs: `https:https://pub.flutter-io.cn/api/packages/cupertino_icons` I would say that you set the `PUB_HOSTED_URL` incorrectly.
