### ISSUE TITLE
HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by baraakhateeb** [dart-lang/pub#2601]
HTTP error 403: Forbidden

package:pub/src/http.dart 218:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 322:37       BoundHostedSource._download

package:pub/src/source/hosted.dart 217:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 388:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 272:10                withDependencyType

package:pub/src/entrypoint.dart 384:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 245:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by jonasfj** [comment]
Are you behind corporate proxy? VPN? based in China?

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by baraakhateeb** [comment]
I'm not sure but I'm in syria, so not all google services works in my country😅,
But in flutter i can install many packages like Http but other packages shows error 403

**Comment by sigurdm** [comment]
Closing, assuming stale
