### ISSUE TITLE
PUB GET IS NOT WORKING (it is 10 days now)

### ISSUE THREAD

**Issue by DanGerHOGGISH** [dart-lang/pub#2609]
Hi. I dont want to rewrite eveything. If you dont mind can you check this out please . Thank you
https://github.com/flutter/flutter/issues/63264

**Comment by Ashok-Varma** [comment]
same issue : All details are added in this ticket (flutter/flutter#63259)
@TahaTesser : can you help me understand what's the bug ? not able to wrap my head around why this is not a flutter issue

**Comment by DanGerHOGGISH** [comment]
Good morning. Now it worked but i did nothing absolutely. I think it is server problem. I want to close but @Ashok-Varma 's problem is not solved i think.

**Comment by jonasfj** [comment]
Please provide information... Like network conditions, VPN? corporate proxy. Operating system. Dart / Flutter SDK version.

Please paste logs as gists, consider trying something like `flutter pub pub get --verbose`

**Comment by Ashok-Varma** [comment]
Hi @jonasfj 
I'm using

- Network : 100 Mbps connection (no VPN)
- OS : Mac Catalina 10.15.6
-  Version : Flutter (1.2.0), Dart (dart packaged with flutter 1.2.0)
- `flutter pub pub get --verbose` gives same `Waiting for another flutter command to release the startup lock...` error. (Any flutter command is giving same error)

**Comment by jonasfj** [comment]
Flutter 1.2.0 or 1.20.0 ?

Just to clarify?

**Comment by Ashok-Varma** [comment]
Thank you @jonasfj 👍 , it's 1.20.0 😄  (updated the actual comment)

This occurred while updating to 1.20.0 and i tried all steps mentioned here flutter/flutter#63259 . Now i have `1.20.0` (as i pulled latest-flutter), still have the problem

**Comment by RoelandW** [comment]
We had similar issues (calling `flutter` results `Waiting for another flutter command to release the startup lock...` error and all the lock files are removed, etc) and after some debugging it had to do with how `flock` is executed. I'm still in the progress of finding out why this exactly happened all of a sudden, but perhaps it can help you. 

Please first check if you have `flock` installed by executing `flock` in the terminal. If you have, please try the following:

Edit file `FLUTTER_HOME/bin/internal/shared.sh`.

Change line 46 from:
`flock --nonblock --exclusive 7 2>/dev/null`
to:
`flock -n 7 2>/dev/null`

**Comment by ranudhurandar** [comment]
Am new to flutter, getting same issue from yesterday before it was working fine Any idea what could be done?  Flutter pub get giving error as:

->. Because (Project_Name) depends on dev_dependencies any which doesn't exist (could not find package dev_dependencies at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

and the command is keep running.

OS : Mac Catalina 10.15.6
Version : version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

**Comment by jonasfj** [comment]
@jonahwilliams, might this locking be related to `flutter_tools`?

**Comment by DanGerHOGGISH** [comment]
Hi. 28 days ago i opened this issue and it worked  fine. But now pub get is now working even i cannot create a new flutter project

**Comment by DanGerHOGGISH** [comment]
C:\myProjects\coffee_app>flutter pub get
Building flutter tool...
Running pub upgrade...
^CTerminate batch job (Y/N)? y

C:\myProjects\coffee_app>flutter verbose
Building flutter tool...
Running pub upgrade...
^CTerminate batch job (Y/N)? y

C:\myProjects\coffee_app>flutter doctor
Building flutter tool...
Running pub upgrade...
^CTerminate batch job (Y/N)? y

here is  my output in my terminal

**Comment by DanGerHOGGISH** [comment]
```
flutter pub pub get --verbose
[ +135 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +189 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.20.1
[  +12 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +82 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +25 ms] Using C:\src\flutter\.pub-cache for the pub cache.
[   +3 ms] executing: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat get --verbose
FINE: Pub 2.9.0
IO  : Spawning "cmd /c ver" in C:\myProjects\coffee_app\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.19041.450]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: fact: coffee_app is 1.0.0+1
SLVR: derived: coffee_app
SLVR: fact: coffee_app depends on flutter any from sdk
SLVR: fact: coffee_app depends on cupertino_icons ^0.1.3
SLVR: fact: coffee_app depends on firebase_auth ^0.16.1
SLVR: fact: coffee_app depends on provider ^4.3.2+1
SLVR: fact: coffee_app depends on flutter_spinkit ^4.1.2+1
SLVR: fact: coffee_app depends on cloud_firestore ^0.13.7
SLVR: fact: coffee_app depends on flutter_test any from sdk
SLVR:   selecting coffee_app
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: cloud_firestore ^0.13.7
SLVR:   derived: flutter_spinkit ^4.1.2+1
SLVR:   derived: provider ^4.3.2+1
SLVR:   derived: firebase_auth ^0.16.1
SLVR:   derived: cupertino_icons ^0.1.3
SLVR:   derived: flutter any from sdk
SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.17
SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.7.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on fake_async 1.1.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on clock 1.0.1
SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.5
SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.4.2
SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.0.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on characters 1.0.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.3
SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.14.13
SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.8
SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.1.8
SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.7.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.2.0
SLVR:     selecting flutter_test 0.0.0 from sdk
SLVR:     derived: typed_data 1.2.0
SLVR:     derived: term_glyph 1.1.0
SLVR:     derived: string_scanner 1.0.5
SLVR:     derived: stream_channel 2.0.0
SLVR:     derived: source_span 1.7.0
SLVR:     derived: meta 1.1.8
SLVR:     derived: matcher 0.12.8
SLVR:     derived: collection 1.14.13
SLVR:     derived: charcode 1.1.3
SLVR:     derived: characters 1.0.0
SLVR:     derived: boolean_selector 2.0.0
SLVR:     derived: async 2.4.2
SLVR:     derived: vector_math 2.0.8
SLVR:     derived: stack_trace 1.9.5
SLVR:     derived: clock 1.0.1
SLVR:     derived: fake_async 1.1.0
SLVR:     derived: path 1.7.0
SLVR:     derived: test_api 0.2.17
SLVR:     fact: cloud_firestore 0.13.7 depends on flutter any from sdk
SLVR:     fact: cloud_firestore 0.13.7 depends on meta ^1.0.5
SLVR:     fact: cloud_firestore 0.13.7 depends on firebase_core ^0.4.4
SLVR:     fact: cloud_firestore 0.13.7 depends on cloud_firestore_platform_interface ^1.0.0
SLVR:     fact: cloud_firestore 0.13.7 depends on cloud_firestore_web ^0.1.1
SLVR:       selecting cloud_firestore 0.13.7
SLVR:       derived: cloud_firestore_web ^0.1.1
SLVR:       derived: cloud_firestore_platform_interface ^1.0.0
SLVR:       derived: firebase_core ^0.4.4
IO  : Get versions from https://pub.dartlang.org/api/packages/flutter_spinkit.
IO  : HTTP GET https://pub.dartlang.org/api/packages/flutter_spinkit
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: C455178C-EFFD-463E-B6BB-150CFABCC458
    | X-Pub-Environment: flutter_cli:interactive
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.9.0
IO  : HTTP error:
    | HandshakeException: Connection terminated during handshake
    |
    | dart:_http                                          _HttpClient.openUrl
    | package:http/src/io_client.dart 31:37               IOClient.send
    | package:pub/src/http.dart 66:43                     _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33            RetryClient.send
    | package:pub/src/http.dart 165:39                    _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31      ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                          _asyncThenWrapperHelper
    | package:http/src/base_client.dart 176:38            BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 35:7              BaseClient.get
    | package:http/src/base_client.dart 125:28            BaseClient.read
    | package:pub/src/source/hosted.dart 187:31           BoundHostedSource._fetchVersions
    | dart:async                                          _CustomZone.runUnary
    | package:pub/src/rate_limited_scheduler.dart 83:30   RateLimitedScheduler._processNextTask.runJob
    | package:pub/src/rate_limited_scheduler.dart 86:30   RateLimitedScheduler._processNextTask
    | package:pool/pool.dart 127:28                       Pool.withResource
    | ===== asynchronous gap ===========================
    | dart:async                                          _asyncThenWrapperHelper
    | package:pub/src/rate_limited_scheduler.dart 130:37  RateLimitedScheduler.schedule.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                          scheduleMicrotask
    | package:pub/src/rate_limited_scheduler.dart 130:7   RateLimitedScheduler.schedule
    | package:pub/src/source/hosted.dart 253:39           BoundHostedSource.describeUncached
    | package:pub/src/source/cached.dart 40:18            CachedSource.doDescribe
    | package:pub/src/source.dart 208:21                  BoundSource.describe
    | package:pub/src/solver/package_lister.dart 173:67   PackageLister.incompatibilitiesFor.<fn>
    | dart:async                                          runZoned
    | package:pub/src/http.dart 279:10                    withDependencyType
    | package:pub/src/solver/package_lister.dart 173:17   PackageLister.incompatibilitiesFor
    | package:pub/src/solver/version_solver.dart 388:42   VersionSolver._choosePackageVersion
    | ===== asynchronous gap ===========================
    | dart:async                                          _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart 98:24    VersionSolver.solve.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                          _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart          VersionSolver.solve.<fn>
    | dart:async                                          runZoned
    | package:pub/src/source/hosted.dart 504:20           BoundHostedSource.withPrefetching.<fn>
    | package:pub/src/rate_limited_scheduler.dart 106:28  RateLimitedScheduler.withPrescheduling
    | package:pub/src/source/hosted.dart 503:29           BoundHostedSource.withPrefetching
    | package:pub/src/solver/version_solver.dart 94:40    VersionSolver.solve
    | package:pub/src/solver.dart 37:5                    resolveVersions
    | package:pub/src/entrypoint.dart 229:13              Entrypoint.acquireDependencies.<fn>
    | package:pub/src/log.dart 394:18                     progress
    | package:pub/src/entrypoint.dart 227:24              Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 45:23              GetCommand.run
    | package:args/command_runner.dart 197:27             CommandRunner.runCommand
    | package:pub/src/command_runner.dart 193:39          PubCommandRunner.runCommand.<fn>
    | dart:async                                          new Future.sync
    | package:pub/src/utils.dart 113:12                   captureErrors.wrappedCallback
    | package:stack_trace                                 Chain.capture
    | package:pub/src/utils.dart 126:11                   captureErrors
    | package:pub/src/command_runner.dart 193:13          PubCommandRunner.runCommand
IO  : Retry #1 for GET https://pub.dartlang.org/api/packages/flutter_spinkit...
IO  : HTTP GET https://pub.dartlang.org/api/packages/flutter_spinkit
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: C455178C-EFFD-463E-B6BB-150CFABCC458
    | X-Pub-Environment: flutter_cli:interactive
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.9.0

```

**Comment by DanGerHOGGISH** [comment]
This output is from my 1.20.1 Flutter SDK version
`flutter pub pub --verbose
[ +145 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +3 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +192 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.20.1
[  +11 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +3 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +70 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +35 ms] Using C:\src\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat
Pub is a package manager for Dart.

Usage: pub <command> [arguments]

Global options:
-h, --help             Print this usage information.
    --version          Print pub version.
    --[no-]trace       Print debugging information when an error occurs.
    --verbosity        Control output verbosity.

          [all]        Show all output including internal tracing messages.
          [error]      Show only errors.
          [io]         Also show IO operations.
          [normal]     Show errors, warnings, and user messages.
          [solver]     Show steps during version resolution.
          [warning]    Show only errors and warnings.

-v, --verbose          Shortcut for "--verbosity=all".

Available commands:
  cache       Work with the system cache.
  deps        Print package dependencies.
  downgrade   Downgrade the current package's dependencies to oldest versions.
  get         Get the current package's dependencies.
  global      Work with global packages.
  logout      Log out of pub.dartlang.org.
  outdated    Analyze your dependencies to find which ones can be upgraded.
  publish     Publish the current package to pub.dartlang.org.
  run         Run an executable from a package.
  upgrade     Upgrade the current package's dependencies to latest versions.
  uploader    Manage uploaders for a package on pub.dartlang.org.
  version     Print pub version.

Run "pub help <command>" for more information about a command.
See https://dart.dev/tools/pub/cmd for detailed documentation.
[ +191 ms] "flutter pub" took 341ms.
[ +275 ms] ensureAnalyticsSent: 269ms
[   +3 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0`

**Comment by jonasfj** [comment]
@DanGerHOGGISH Might be worth looking into what firewall and anti virus you have on Windows.

The error reported suggest that something is preventing the HTTP request to `https://pub.dartlang.org/api/packages/flutter_spinkit`.
(This URL returns some JSON).

Can you make such request in the browser?
Can you make such request on the commandline with `curl` or `wget` ?

**Comment by decrypted** [comment]
TIP: this also fails on an NFS mount. Workaround is to make flutter use the mkdir method

**Comment by DanGerHOGGISH** [comment]
> @DanGerHOGGISH Might be worth looking into what firewall and anti virus you have on Windows.
> 
> The error reported suggest that something is preventing the HTTP request to `https://pub.dartlang.org/api/packages/flutter_spinkit`.
> (This URL returns some JSON).
> 
> Can you make such request in the browser?
> Can you make such request on the commandline with `curl` or `wget` ?

Hey @jonasfj you were right it failed because of the network i have. I am sorry for bothering :(

**Comment by jonasfj** [comment]
@DanGerHOGGISH so a few things you can try:
 * disable ipv6 (try with and without)
 * use a different DNS server `8.8.8.8` or opendns.
 * use a VPN.

Do you have problems with `pub.dev` in the browser? on the CLI with `curl` / `wget`?
Similarly with `https://pub.dartlang.org/api/packages/flutter_spinkit` where does it work?

I'm curious, because if there is something we can do we should explore it. Or at-least explore how we can improve the failure scenario.

**Comment by Ashok-Varma** [comment]
> We had similar issues (calling `flutter` results `Waiting for another flutter command to release the startup lock...` error and all the lock files are removed, etc) and after some debugging it had to do with how `flock` is executed. I'm still in the progress of finding out why this exactly happened all of a sudden, but perhaps it can help you.
> 
> Please first check if you have `flock` installed by executing `flock` in the terminal. If you have, please try the following:
> 
> Edit file `FLUTTER_HOME/bin/internal/shared.sh`.
> 
> Change line 46 from:
> `flock --nonblock --exclusive 7 2>/dev/null`
> to:
> `flock -n 7 2>/dev/null`

Thank you @RoelandW this did work. 
Hi @jonasfj, this work around fixed the issue. Do you know why is this might be happening

**Comment by DanGerHOGGISH** [comment]
> @DanGerHOGGISH so a few things you can try:
> 
> * disable ipv6 (try with and without)
> * use a different DNS server `8.8.8.8` or opendns.
> * use a VPN.
> 
> Do you have problems with `pub.dev` in the browser? on the CLI with `curl` / `wget`?
> Similarly with `https://pub.dartlang.org/api/packages/flutter_spinkit` where does it work?
> 
> I'm curious, because if there is something we can do we should explore it. Or at-least explore how we can improve the failure scenario.

Thank you for your reply @jonasfj  In my country (Uzbekistan) pub.dev does not work sometimes. I think it is due to firewall. I use VPN but does not work.

**Comment by jonasfj** [comment]
@Ashok-Varma, I don't recall why the file-locking issue might be happening, but file a separate issue for a separate concern.

>  In my country (Uzbekistan) pub.dev does not work sometimes.

Yeah, I don't think we can do much about that.

> I think it is due to firewall.

Firewall / content-filtering by ISP, or your local firewall?

> I use VPN but does not work.

Curious, what VPN service are you using? If you use a VPN configured for the system that should work for `pub` too. Depending on how your operating system is configured, because it's probably possible to install a VPN so it only works in the browser.

**Comment by RicPiccolo** [comment]
> We had similar issues (calling `flutter` results `Waiting for another flutter command to release the startup lock...` error and all the lock files are removed, etc) and after some debugging it had to do with how `flock` is executed. I'm still in the progress of finding out why this exactly happened all of a sudden, but perhaps it can help you.
> 
> Please first check if you have `flock` installed by executing `flock` in the terminal. If you have, please try the following:
> 
> Edit file `FLUTTER_HOME/bin/internal/shared.sh`.
> 
> Change line 46 from:
> `flock --nonblock --exclusive 7 2>/dev/null`
> to:
> `flock -n 7 2>/dev/null`

Actually this is the fix for some reason for me, where I see all the time "waiting for another....."
Seems like this is the problem on MacOs 10.15 and newest xCode.
Thank you, man!

**Comment by dmgcoding** [comment]
deleting pubspeck.lock file and running flutter pub get worked for me.
