### ISSUE TITLE
Binstubs should not send analytics?

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#2613]
CC @mit-mit 

That could be considered surprising as the user of the binstub might not realize they are invoking `dart`, rather they are using an installed third-party tool. (Similar to how the `pub` tool will not send analytics while `dart pub` will).

Another possible issue is that the first invokation of the binstub might print the "The Dart tool uses Google Analytics to anonymously report feature usage" message which pollutes the stdout of the tool (this only happens in the first run - but still seems very surprising in the cases where it occurs).

A solution to this would be to create the binstub invocation with '--disable-dartdev-analytics'. This would make the binstubs not work on an sdk downgrade.

If we could have an environment variable for disabling analytics that would work with a downgrade.

**Comment by sigurdm** [comment]
Somewhat related: https://github.com/dart-lang/sdk/issues/43017

**Comment by jonasfj** [comment]
/cc @jwren

--------------
In https://github.com/dart-lang/sdk/issues/43017 I've proposed disabling analytics collection when the env var `CI=true`, but I don't think we can or should abuse said environment variable in our bin-stubs, such env var signals that the program is running in a CI system. The users program may behave differently when this is the case.

**Comment by sigurdm** [comment]
> I don't think we can or should abuse said environment variable in our bin-stubs

I agree, we would need yet another variable for this use case.

**Comment by sigurdm** [comment]
As jonasfj suggests: let's fix this when we are switching to dartdev.
Then we can do:
```
dart --disable-dartdev-analytics pub global run 
```
instead of 
```
pub global run
```
from the binstub.

**Comment by sigurdm** [comment]
Pub is no longer sending analytics itself.

This will no longer be a question if we switch to compiled executables instead of snapshots.

**Comment by sigurdm** [comment]
I think until then we'll continue sending analytics. One could argue that running the binstub is no different from running `dart pub global run`....
