### ISSUE TITLE
Update null safety detection logic to support "experimental release versions"

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#2621]
See the meta issue https://github.com/dart-lang/sdk/issues/43031.

tldr; Detection of if null safety is enabled or not will need to change - instead of the 'current' version being the version that enables it, there will be a new field in a configuration file that determines the language version required to enable the feature.

**Comment by sigurdm** [comment]
Is this issue still relevant? The linked issue has been marked closed.

**Comment by jonasfj** [comment]
I think we've decided not to go down the path.. given that beta will happen not that far in the future we'll rely on language versioning for detection.
