### ISSUE TITLE
Authentication for custom private pub repositories

### ISSUE THREAD

**Issue by TheMisir** [dart-lang/pub#2631]
I wonder is there anything implemented for handling authentication on custom private repository. I want to create my own pub.dev backend server but did not found a way to authenticate users, limit access to specified package. Because I think pub only stores authentication data only for pub.dev website. Which is stored in `credentials.json` on flutter cache folder.

**Comment by jonasfj** [comment]
See https://github.com/dart-lang/pub/issues/1381 for discussion, yes, this is something we have been thinking about, but haven't prioritized fixing yet.

There are/have-been a few contributors working on something, but so far nothing has been good enough to ship yet.
