### ISSUE TITLE
pub add <package>, can leave dev_deps empty

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2635]
``` console
$ dart pub add --dev retry
$ dart pub add retry
```
Leaves us with:
```yaml
dev_dependencies: 
  {}
```

Assuming we didn't have any `dev_dependencies` before. We probably should just remove the `dev_dependencies` or `dependencies` key, if we are deleting the last entry in the dictionary.. We risk deleting a few extra comments, but that seems rare..

We could also leave it as `dev_dependencies:`, but that seems unfortunate, and I doubt `yaml_edit` can express that.

**Comment by jonasfj** [comment]
We have similar issues with `pub remove` if you remove the last entry, it leave us with `{}`.

Come to think about it, I suspect we might have thought this was a good idea.. Let's chat :D

**Comment by walnutdust** [comment]
So the rationale behind `yaml_edit` was to maintain correctness as far as possible, and we determined that for clarity it was better to change it to an empty map because having:
```
dependencies:
```

is ambiguous in the general context. The way I see it, the solutions we can take are:

1. Updating `yaml_edit`'s behavior 
2. Updating `pub` to remove the key

thoughts?

**Comment by jonasfj** [comment]
I think the behavior is correct in `yaml_edit`. Because in the general case this is the right thing to do.

But in case if `pub add/remove` we know that:
 * Empty dictionary
 * null
 * omitted `dependencies` key

Are all equivalent, so we can do something  nice..

-------
For `pub add/remove` this bad because if you do:
```
dart pub remove path retry
dart pub add path
dart pub add retry
```
leaves you with:
```
name: mypkg
dependencies: 
  {path: ^1.7.0, retry: ^3.0.1}
```

**Comment by jonasfj** [comment]
Let's remove the dependencies key if there is no deps.. in `pub add/remove`
