### ISSUE TITLE
pub add <package> with empty `dependencies` key

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2637]
```
name: mypkg
dependencies:
environment:
  sdk: ^2.9.0-edge
dev_dependencies: {}
```
Then run:
```
[mypkg]$pub add retry
Error on line 3, column 27: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
3 │   retry: ^3.0.1environment:
  │                           ^
  ╵
```

We have two problems here.

 1. A bug in `yaml_edit`,
 2. A bug in how `pub add` catches `AssertionError`, I assume this an internal assertion in `yaml_edit` that fails.

I think it's best if `pub add` catches `AssertionError` and shows a message where it says to report it here.
We have other places where we handle internal errors and have a message.

Side note: We should probably make methods that modify `pubspec.yaml` log contents of `pubspec.yaml` as well as the change they are doing. We can log it such it only shows up with `--verbose`

**Comment by walnutdust** [comment]
I think the message comes from `package:yaml`'s error that's thrown when parsing - it should be a `YamlException` that got propagated

**Comment by jonasfj** [comment]
yeah, that sounds about right, but such internal errors thrown from `yaml_edit` are internal errors... I suggest we throw as `AssertionError`.
