### ISSUE TITLE
Pub outdated doesn't work with current null safety packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2647]
Currently `dart pub outdated --mode=null-safety` doesn't work for packages that opt into null safety via a 2.10-dev constraint, like `2.10.0-0`.

For example, package `mobx` depends just on `meta`, which already has opted into null safety. Yet:

```
mit-macbookpro4:mobx mit$ dart pub outdated --mode=null-safety
Running in 'null safety' mode.
Showing packages where the current version doesn't fully support null safety.

Dependencies                Current              Upgradable           Resolvable           Latest
meta                        1.3.0-nullsafety.2   1.3.0-nullsafety.2   1.3.0-nullsafety.2   1.3.0-nullsafety.2
```

It looks like we used `2.10` stable first, but then in https://github.com/dart-lang/pub/pull/2604 moved that to `2.11` stable. I think we should go the other way and loosen the constraint to `final _firstVersionWithNullSafety = Version.parse('2.10.0-0');`

cc @sigurdm @jonasfj @leafpetersen

**Comment by jonasfj** [comment]
This will cause publishing warnings for anyone using `2.10` dev release or later.

 * `pub publish` warning for [mixed-mode null-safety](https://github.com/dart-lang/pub/blob/73f0906e152a2de98ec881523f289db04f5b3b9b/lib/src/validator/null_safety_mixed_mode.dart#L37-L52).
 * `pub publish` warning for [first version opting into null-safety](https://github.com/dart-lang/pub/blob/73f0906e152a2de98ec881523f289db04f5b3b9b/lib/src/validator/relative_version_numbering.dart#L54-L56)
 * `pub get` warning for mixed-mode packages -- still in review https://github.com/dart-lang/pub/pull/2590

We can disable these checks (and land them in disabled mode) until null-safety ships in beta, the same way we decided that `pub outdated --mode=null-safety` is a _hidden flag_ until null-safety goes to beta.

Note that packages that currently requires `2.10.0-0.0` are not necessarily ported to null-safety (take for example [`build_runner`](https://github.com/dart-lang/build/blob/9efd5120ffa1849d94c8dab069f6273c0ac50c4d/build_runner/pubspec.yaml#L9)).

----------

These caveats considered this might be a very reasonable approximation.

**Comment by jonasfj** [comment]
I suppose this is a simpler (less elegant) way to solve https://github.com/dart-lang/pub/issues/2574

**Comment by mit-mit** [comment]
> This will cause publishing warnings for anyone using 2.10 dev release or later.

Only if they use an SDK constraint that is >= `2.10.0-0.0` right? If a package does that, then it is asking for null safety.

**Comment by jonasfj** [comment]
> Only if they use an SDK constraint that is >= 2.10.0-0.0 right?

Yes

> If a package does that, then it is asking for null safety.

Only if the package is also in the allowed_experiments list.

**Comment by mit-mit** [comment]
Yeah, I take it back. The SDK constraint is required for a package to use null safety, but it's insufficient; the flag is also needed.

And given the flag isn't in the source code, I think that means pub/pana have no way of knowing if a certain package is using null safety or not at the current stage. Once we remove the experiment flag (for beta), then the SDK constraint is a sufficient signal, and we can update the check to whatever SDK version we do that in.

**Comment by sigurdm** [comment]
Can we close this issue for now?

**Comment by jonasfj** [comment]
Yes, I think we've decided that this will work when releases without null-safety behind a flag starts happening.
