### ISSUE TITLE
Some tests are failing; feedback needed

### ISSUE THREAD

**Issue by stefandevo** [dart-lang/pub#2652]
Currently working on a PR, but some test are failing from the current repo while no changed code is touched.

https://github.com/dart-lang/pub/blob/9d236e003299309685df19223622c090f26d5cb4/test/add/hosted/non_default_pub_server_test.dart#L39

My output is 
```
Expected: <65>
  Actual: <-9>
Process `pub add` had an unexpected exit code.
package:test_api                              expect
package:test_process/test_process.dart 234:5  TestProcess.shouldExit

TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
```

and
https://github.com/dart-lang/pub/blob/ceaa86f2c7eb35f044b4c202268a17361de68d13/test/global/binstubs/binstub_runs_executable_test.dart#L14

```

Process `/private/var/folders/1s/d1jscr395hv4450v4qdy6rnh0000gn/T/dart_test_ZahQ9S/cache/bin/foo-script arg1 arg2` exited with exitCode -9. Output:
[e] Can't load Kernel binary: Invalid kernel binary format version.
    Precompiling executable...

Expected: should emit an event that 'ok [arg1, arg2]'
  Actual: <Instance of 'StreamQueue<String>'>
   Which: emitted • Precompiling executable...
            which emitted an event that is different.
                  Expected: ok [arg1,  ...
                    Actual: Precompili ...
                            ^
                   Differ at offset 0


```

I am wondering if these two are related because running this on Mac OS and doing something different.

Can somebody give feedback on these failing tests?

**Comment by sigurdm** [comment]
I get the same error on Mac OS.

Still not sure what it is about.

Feel free to upload the PR anyway.
