### ISSUE TITLE
Is it possible to support environments in the pubspec file?

### ISSUE THREAD

**Issue by xrax** [dart-lang/pub#2657]
Hello pub team, first of all thanks for the great product you have been created and improving, is really amazing.

I don't sure if this is something already covered but I haven't been able to found a way to address it from a pub perspective, so I prefer to ask it here.

I am working in a flutter mobile project an we are facing a case where we need to exclude some assets in a production build and that made me think that there could be other cases where other pubspec configurations could vary between different environments. 

Off course we can address this from a git perspective or even a script in the CI/CD process but, I feel that the best solution should came from the pubspec file itself, something like the current `dev_dependencies` but to pickup the whole file, so we could have `pubspec_dev`, `pubspec_stg`, `pubspec_dev`,... in the same way that flavors/schemes works in the native platforms.

Thanks in advance for your time.

**Comment by jonasfj** [comment]
This seems more like a flutter question... If it's flutter assets.

**Comment by sigurdm** [comment]
Is this relevant? https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b It has some detail of how to separate assets between flavors, but it seems to require a bit of manual work.
