### ISSUE TITLE
Allow suppressing "Precompiling executable..." text

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#2660]
Stagehand has a JSON mode for IDEs called like this:

```
pub global run stagehand --machine
```

It outputs JSON, but sometimes pub will first print out non-JSON output:

```
danny@Dannys-MBP tools_metadata % ~/Dev/Dart\ SDKs/nightly-2020-09-21/bin/pub global run stagehand --machine
Precompiling executable... 
Precompiled stagehand:stagehand.
[{"name":"console-full","label":"Console Application"
```

This usually happens when you change SDK version after activating pub. It would be nice if editors could suppress this to avoid having to filter it out of the output (it'd be even better if the package could do it, but since it runs before the package I'm not sure if that's feasible).

**Comment by sigurdm** [comment]
Hmm this message is only supposed to be written if there is a terminal attached - maybe the logic for that is broken...

**Comment by DanTup** [comment]
Ah, in that case testing from the command line as I pasted above isn't a good repro, so here's a script that does the same programatically (which is essentially what VS Code is doing - albeit with nodejs and not Dart):

```dart
import 'dart:io';

const sdk1 = '/Users/danny/Dev/Dart SDKs/nightly-2020-09-21';
const sdk2 = '/Users/danny/Dev/Dart SDKs/nightly-2020-09-22';

Future<void> main() async {
  await log('$sdk1/bin/pub', ['global', 'activate', 'stagehand']);
  await log('$sdk2/bin/pub', ['global', 'run', 'stagehand', '--machine']);
}

Future<void> log(String cmd, List<String> args) async {
  print('Running $cmd ${args.join(' ')}...');
  final proc = await Process.run(cmd, args);
  print(proc.stdout);
  print(proc.stderr);
}
```

The output for the second process starts like this:

```
Running /Users/danny/Dev/Dart SDKs/nightly-2020-09-22/bin/pub global run stagehand --machine...
Precompiling executable...
Precompiled stagehand:stagehand.
[{"name":"console-full","label":"Console
```

**Comment by alextekartik** [comment]
Alternatively it could also print to stderr to avoid messing any output parsing (if you specify some tools to spit out json, you don't want non json data). see #2545

**Comment by sigurdm** [comment]
Ah - checking this now - the logic for handling this is only implemented for `pub run` not `pub global run`.

Sorry for that.

**Comment by DanTup** [comment]
Aha!

No worries - I shipped a workaround in the meantime that just discarded it. Glad it was an easy fix - thanks!
