### ISSUE TITLE
Running `dart pub` from the Flutter SDK before the `version` file is generated fails

### ISSUE THREAD

**Issue by dnfield** [dart-lang/pub#2661]
In any non-Flutter project, where I'd expect to be able to run `dart pub deps` for example, this happens if I run it before `version` is generated in the Flutter SDK:

```
dart pub deps
Cannot open file, path = '/Users/dnfield/src/flutter/flutter/version' (OS Error: No such file or directory, errno = 2)
```

Full verbose output:

```
FINE: Pub 2.10.0-136.0.dev
ERR : Cannot open file, path = '/Users/dnfield/src/flutter/flutter/version' (OS Error: No such file or directory, errno = 2)
FINE: Exception type: FileSystemException
FINE: dart:io                                     _File.readAsStringSync
    | package:pub/src/io.dart 152:48              readTextFile
    | package:pub/src/sdk/flutter.dart 34:23      FlutterSdk.version
    | package:pub/src/command/deps.dart 69:63     DepsCommand.run
    | package:args/command_runner.dart 197:27     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 182:39  PubCommandRunner.runCommand.<fn>
    | dart:async                                  new Future.sync
    | package:pub/src/utils.dart 113:12           captureErrors.wrappedCallback
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 126:11           captureErrors
    | package:pub/src/command_runner.dart 182:13  PubCommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 113:52           captureErrors.wrappedCallback
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 126:11           captureErrors
    | package:pub/src/command_runner.dart 182:13  PubCommandRunner.runCommand
```

It would be nice if this at least printed something telling me to run `flutter doctor` or even `flutter --version` to fix this, if it can't just fix it itself.

**Comment by jonasfj** [comment]
Hmm, seems that  `bin/internal/shared.sh` sets up `FLUTTER_ROOT` which makes `dart pub get` think it's part of the flutter SDK, and behave the same as `flutter pub get`, which means that it'll allow fetching of packages that an SDK dependency on flutter.

It also means that it checks the flutter version, which is probably causing the problem here.

**Comment by mitjad123** [comment]
Having the same issue running (on Win10, Flutter 2.2): dart pub deps

'git' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
Cannot open file, path = 'C:\src\flutter\version' (OS Error: The system cannot find the file specified.
, errno = 2)

Flutter doctor:
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1110], locale sl-SI)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

• No issues found!

Flutter --version:
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (6 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

Need to check and correct transitive dependecies. How?

**Comment by sigurdm** [comment]
Seems to be fixed in latest flutter
```
> git clone https://github.com/flutter/flutter
> flutter/bin/dart pub deps
Downloading Linux x64 Dart SDK from Flutter engine ede2a0a3c3eb95d5010f823166fa4b8290e86e01...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  223M  100  223M    0     0  39.3M      0  0:00:05  0:00:05 --:--:-- 45.0M
Building flutter tool...
Dart SDK 3.0.0-231.0.dev
Flutter SDK 3.8.0-10.0.pre.37
flutter_test_p 1.0.0+1
├── cupertino_icons 1.0.5
....
```
