### ISSUE TITLE
“Pub get” has not been run and couldn't be get dependencies

### ISSUE THREAD

**Issue by DoraDeng629** [dart-lang/pub#2669]
I failed to update dependencies and Get dependencies, could anyone can help me ?
![image](https://user-images.githubusercontent.com/70420131/94977184-ad830980-04e5-11eb-9f5e-65fd0472c2c8.png)
![image](https://user-images.githubusercontent.com/70420131/94977203-bf64ac80-04e5-11eb-8df3-6b7369588791.png)
There are lots of errors in the page.

**Comment by mit-mit** [comment]
Sorry to hear @DoraDeng629, can you please run `flutter pub get -v` in a terminal/command prompt, copy its output into a gist.github.com, and share a link to that here?

**Comment by sigurdm** [comment]
Yes, this looks like a bug. But we need the full stack trace to investigate further.

**Comment by jonasfj** [comment]
We need stack trace from @DoraDeng629 in order to proceed further with this.
