### ISSUE TITLE
Output from `pub get` is confusing when the resolution is unsound

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2710]
After `pub get` resolves, it check if the resolved set resulted in partial/unsound null safety. If so it prints a warning. However, this warning is hard to read:

```
$ dart --no-sound-null-safety pub get
Resolving dependencies...
Got dependencies!
The package resolution is not fully migrated to null-safety.

package:test is not opted into null safety in its pubspec.yaml:
  ╷
8 │   sdk: '>=2.10.0-0 <2.12.0'
  │        ^^^^^^^^^^^^^^^^^^^^
  ╵

Either downgrade your sdk constraint, or invoke dart/flutter with
`--no-sound-null-safety`.

To learn more about available versions of your dependencies try running
`pub outdated --mode=null-safety`.

See more at https://dart.dev/null-safety/migration-guide.
```

I propose something a bit simpler which:

* Drops printing the constraint of unmigrated dependencies
* Add spacing after 'Got dependencies'
* Removes the parts about how to run code (we can show that in run).

```
$ dart --no-sound-null-safety pub get
Resolving dependencies...
Got dependencies!

Warning: The package resolution support only partial null-safety.

To learn more about available versions of your dependencies try running
`pub outdated --mode=null-safety`.

See more at https://dart.dev/null-safety/migration-guide.
```

**Comment by mit-mit** [comment]
Tagging as an experience blocker for null safety beta

**Comment by mit-mit** [comment]
One change I think we need to make to improve the usefulness of outdated: have `--mode=null-safety` automatically set `--prereleases`. I think we'll need this not just during beta, but also for at least some months past stable launch.

**Comment by jonasfj** [comment]
> have --mode=null-safety automatically set --prereleases

Agreed, filed in https://github.com/dart-lang/pub/issues/2711

**Comment by jonasfj** [comment]
```
$ dart pub get
Resolving dependencies...
Got dependencies!

Warning: Following packages are not migrated to null-safety yet:
 * build_runner
 * pedantic

To learn more about available versions of your dependencies try running
`pub outdated --mode=null-safety`.

See more at https://dart.dev/null-safety/migration-guide.
```

And we only listed packages that do not have a _default language version_ of 2.12. That is this won't warn about packages like `package:test` (which may contain a few files with language version markers, and which may have dependencies not migrated). But we will warn about `pedantic` and `build_runner` (even if they are not imported); side note: `pedantic` should be easy to migrate.


--------

Alternatively: We don't have this warning at all, as users will be warned by analyzer when importing non-migrated libraries, and `dart run` will fail when running mixed code, and this will tell the user about the problem.

**Comment by mit-mit** [comment]
Won't fixing this in favor of https://github.com/dart-lang/pub/issues/2717
