### ISSUE TITLE
Travis broken on Dart 2.12.0-13.0.dev

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#2713]
I just received a notification that my Travis build was broken. pub get is failing with the following error:

```
Error: This project cannot run with sound null safety, because one or more project dependencies do not
support null safety:
      
 - package:js
      
Run 'pub outdated --mode=null-safety' to determine if versions of your
dependencies supporting null safety are available.
Error: Compilation failed.
```

Since there hasn't been any communication on misc@dartlang.org about actions I need to take to prepare for null safety, I'm very surprised to see that enforcement of null safety has been turned on in a way that breaks my code. Also, `js` is an official Dart team package, so I'm surprised that null safety isn't enabled for it given that enforcement has been turned on.

**Comment by jonasfj** [comment]
yeah, I think we're planning to do a breaking change to require `environment.sdk` in `pubspec.yaml`, see discussion in https://github.com/dart-lang/pub/issues/2707.

In short: without an lower-bound SDK constraint, you'll automatically get latest _language version_, which means that starting from `2.12.0-0`, you'd need to support null-safety. Or add a lower-bound SDK constraint to opt-out of null-safety.

**Comment by nex3** [comment]
The package in question *does* have [an SDK constraint](https://github.com/google/dart_cli_pkg/blob/a5b1a7429b895c5cccff3673d1ec793fe454f660/pubspec.yaml#L7). The lower bound is 2.7.0, which is well before null safety was introduced by default.

**Comment by jonasfj** [comment]
Hmm, are you sure this happened in `pub get`?
```
      /home/travis/dart-sdk/bin/dart2js --server-mode -Dnode=true -Dversion=1.2.3 -Ddart-version=2.12.0-13.0.dev -obuild/my_app.dart.js build/my_app_npm.dart
      Error: This project cannot run with sound null safety, because one or more project dependencies do not
      support null safety:
      
       - package:js
      
      Run 'pub outdated --mode=null-safety' to determine if versions of your
      dependencies supporting null safety are available.
      Error: Compilation failed.
[e] 
[e] failed with exit code 1
[e] #0      run (package:grinder/src/run.dart:48:5)
[e] #1      Dart2js.compile (package:grinder/grinder_sdk.dart:308:5)
[e] #2      _js (package:cli_pkg/src/npm.dart:213:11)
[e] #3      addNpmTasks.<anon> (package:cli_pkg/src/npm.dart:178:27)
[e] #4      _rootRun (dart:async/zone.dart:1190:13)
[e] #5      _CustomZone.run (dart:async/zone.dart:1093:19)
[e] #6      _runZoned (dart:async/zone.dart:1630:10)
[e] #7      runZoned (dart:async/zone.dart:1550:10)
[e] #8      ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
[e] #9      GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
[e] #10     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
[e] #11     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
[e] #12     Future.forEach.<anon> (dart:async/future.dart:512:26)
[e] #13     Future.doWhile.<anon> (dart:async/future.dart:554:26)
[e] #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
[e] #15     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1423:26)
[e] #16     Future.doWhile (dart:async/future.dart:570:18)
[e] #17     Future.forEach (dart:async/future.dart:510:12)
[e] #18     Grinder.start (package:grinder/src/grinder.dart:167:21)
[e] #19     runTasks (package:grinder/src/cli.dart:67:38)
[e] #20     grind (package:grinder/grinder.dart:45:12)
[e] #21     main (file:///tmp/dart_test_RTKIBC/my_app/tool/grind.dart:7:9)
```
(I haven't used dart2js much, so I'm not entirely sure what's going on here)

**Comment by nex3** [comment]
Good catch, I think you're right that this is a dart2js issue. I've filed https://github.com/dart-lang/sdk/issues/44064 instead.
