### ISSUE TITLE
Simplify null-safety analysis for "pub outdated --mark=null-safety"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2716]
We currently download package versions to look for _language version markers_.

However, some packages like `package:test` will have infrastructure libraries only used by test runners that won't be ported anytime soon. Hence, such packages will show up as _null-safety in-compatible_.

To mitigate this issue, we're going to simply our analysis to only look at the _lower-bound SDK constraint of the package_. Ignoring whether transitive dependencies have been migrated out-of-order, and whether the package contains files that are opt-out using _language version markers_.

If packages are using _language version markers_ or _migrating out-of-order_ (against recommendations), we are simply going to trust that the author knows what they are doing.
(On pub.dev will we score this negatively, but in `pub outdated --mark=null-safety` we'll accepted it).

Note:
 * This means `pub outdated --mark=null-safety` won't look at _transitive dependencies_.
 * As an added benefit `pub outdated --mark=null-safety` won't need to download package versions anymore.

---------

In a further out future, we can consider refining the definition of _null-safety compatibility_ in `pub`. Perhaps by tracing imports from the users code, to identify which packages and libraries need to be _null-safety compatible_ (before then tracing imports from those packages).

**Comment by franklinyow** [comment]
@mit-mit @leafpetersen 
Beta blocker?

**Comment by leafpetersen** [comment]
@franklinyow I believe so, yes.

**Comment by leafpetersen** [comment]
Does this need to be pulled into the sdk and potentially cherry picked?

**Comment by mit-mit** [comment]
> Does this need to be pulled into the sdk and potentially cherry picked?

We have a few more pub fixes planned for today. After those we'll roll pub (via DEPS), and then we'll need a Dart roll or a cherry pick.

**Comment by jonasfj** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/170690
