### ISSUE TITLE
Pub outdated command fails for path dependency

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/pub#2725]
# Environment
Pub 2.12.0-edge.d13eaddf97d60c706f8a8969a8998ab6b083f753

# Problem
pub outdated looks at a path dependency and then just fails, when it should presumably not try to do anything with it and just report the other dependencies.

```
$ cd foo/app
$ pub outdated
Package doesn't exist (could not find package foo at https://pub.dartlang.org).

pubspec.yaml
dependency_overrides:
  foo:
    path: ../

pubspec.lock
  foo:
    dependency: "direct main"
    description:
      path: ".."
      relative: true
    source: path
    version: "1.2.3"

```

**Comment by sigurdm** [comment]
This was fixed by https://github.com/dart-lang/pub/pull/3751
