### ISSUE TITLE
`dart test` complains that `pub` is deprecated

### ISSUE THREAD

**Issue by pq** [dart-lang/pub#2734]
Not sure whether this should be filed her or in the SDK.  Happy to move.  Anyway, I'd expect `dart test` to not warn:

```
[~/src/repos/cli_util] (master) $ dart test
The `pub` command is deprecated. Run `dart pub` instead.
00:01 +4: All tests passed!
```
/cc @jonasfj @bkonyi

**Comment by sigurdm** [comment]
Fixed for now by removing the deprecation warning.
Landed in the sdk https://dart-review.googlesource.com/c/sdk/+/170980

**Comment by sigurdm** [comment]
Follow more updates in: https://github.com/dart-lang/pub/issues/2736
