### ISSUE TITLE
Terminology ^

### ISSUE THREAD

**Issue by pmcgee69** [dart-lang/pub#2744]
The nearest the documentation comes to defining ^ is halfway through the definition of Term with:
**foo >=1.0.0 ∩ not foo >=2.0.0 is foo ^1.0.0.**

It is not completely obvious to me, from that declaration, what the meaning eg of ^1.5.0 is.

**Comment by jonasfj** [comment]
It's documented here https://dart.dev/tools/pub/dependencies#caret-syntax

Also https://dart.dev/tools/pub/versioning

feel free to reopen if you think this should be documented somewhere else.
