### ISSUE TITLE
The output of `dart pub outdated --mode=null-safety` is pretty confusing for a package that's already ...ready

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#2745]
I ran the tool (Dart SDK version: 2.12.0-29.0.dev) over `pkg:convert` at https://github.com/dart-lang/convert/commit/561d73b73cfd59ec93faaf8daaf749e4f9c6196f

```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all support null safety.

dev_dependencies: all support null safety.

Current dependencies are constrained to versions listed in Resolvable.
A resolution compatible with the Latest versions doesn't exist, as they are not
mutually compatible.
```

There's clearly a bunch of stuff here assuming a table is being displayed – when there's no table!

Maybe we should just say `Congrats! 👍 ` ?

**Comment by azadprajapat** [comment]
I want to work on this issue and @kevmoo can you guide me on what output needs to be shown in this case and some relevant help.

**Comment by sigurdm** [comment]
I think the main change is that: `Current dependencies are constrained to versions listed in Resolvable.` Should not be shown if we don't show any packages in the resolvable column. And `A resolution compatible with the Latest versions doesn't exist, as they are not
mutually compatible.` Should not be shown when there is no packages in the latest column.

I think saying 'congrats' would be promising too much. Depending on the parameters to `dart pub outdated` there might still be packages to upgrade.

**Comment by tusharojha** [comment]
@sigurdm looks like the issue are resolved now!

**Comment by sigurdm** [comment]
I don't think so - I still see this with 2.12.0 stable.

**Comment by tusharojha** [comment]
This is the response I am getting in dart 2.12.0 stable is 
```dart
$ dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all support null safety.

dev_dependencies: all support null safety.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.

```
Are we supposed to remove the last 2 lines in this response. I would like to work to it.

**Comment by sigurdm** [comment]
Yes - the two last lines are confusing. When there are no rows they should not be shown. Perhaps another message saying something like 'All dependencies opt in to null-safety.'

That would be a nice contribution!

**Comment by tusharojha** [comment]
I have updated the code accordingly, and now I am getting the following output:

```dart
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all support null safety.

dev_dependencies: all support null safety.
All dependencies opt in to null-safety.

```
Is this what we wanted?

**Comment by sigurdm** [comment]
Yes that looks pretty good.
