### ISSUE TITLE
We need to handle 7-zip failures more gracefully

### ISSUE THREAD

**Issue by Hixie** [dart-lang/pub#2749]
Looking at this log:
https://github.com/flutter/flutter/issues/69697#issuecomment-726406210
...it seems that we don't handle 7-zip failures well.

We should detect when 7-zip fails, and report the error. Specifically, if the failure is "access denied", we should specify what paths 7-zip tried to write to. It might even be good to detect what the failure is (e.g. look at the ACLs of the relevant directories?) and explain how to fix it (if we can do that).

**Comment by Hixie** [comment]
Actually, in that bug the problems seems to be that actually running 7-zip fails, so the paths aren't really relevant there. We should detect that 7-zip has failed, abort `pub`, and report the problem as "7-zip failed to execute", including whatever information we can provide to help them fix the problem.

**Comment by jonasfj** [comment]
Another reason to fix the long standing issue of doing tar in Dart https://github.com/dart-lang/pub/issues/1602

**Comment by sigurdm** [comment]
But on top of that we should probably make a nicer error message if starting a sub-process fails.

**Comment by sigurdm** [comment]
We are no longer using 7-zip since: https://github.com/dart-lang/pub/pull/2817
