### ISSUE TITLE
Stop generating `.packages`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/pub#2756]
There is no need for a new SDK to generate a `.packages` file for itself. The only reason for having one is to support old third-party tools which have not started using the `.dart_tool/package_config.json` file yet.

We should identify any such tools blocking us from removing the `.packages` file, make sure they are updated, and then stop generating `.packages` files.

The sooner this is done, the better.

Would it be possible to stop generating the `.packages` file for Pub in SDK -dev builds? That should smoke out any remaining uses of the file. Maybe keep the feature available under a flag, so people really needing it can still get it that way?

**Comment by jonasfj** [comment]
ironically, `pub` might be one of the tools that depends on this file :D

Or put, differently: `pub` still expects the `.packages` file to be present when testing if dependencies are up-to-date (with `pubspec.lock` and `pubspec.yaml`).

I think we could:
 1. [ ] Ensure that `pub` doesn't require the presence of `.packages` optional,
 2. [ ] Add a `--no-packages-file` flag
 3. [ ] Send out a breaking change notification that `.packages` is going away.
 4. [ ] Flip the default value of the `--no-packages-file` to `--packages-file`
 5. [ ] Hide the `--packages-file`

**Comment by lrhn** [comment]
Another thing that we can do, before flipping the flag, is that every time a `pub run` of a globally activated package finds only a `.packages` file, it immediately generates a `.dart_tool/package_config.json` file too (maybe just blindly copying the data from the `.packages` file and adding language version `2.7` to every package).

**Comment by mit-mit** [comment]
Hi @jonasfj we need to make progress on this; can we go ahead and add the `--no-packages-file` flag?

**Comment by sigurdm** [comment]
> Hi @jonasfj we need to make progress on this; can we go ahead and add the --no-packages-file flag?

I'll start reviving the PR we have lying around.

**Comment by sigurdm** [comment]
Done in https://github.com/dart-lang/pub/pull/2757
