### ISSUE TITLE
Pubspec apparently allows `\` as path separator under windows but not linux

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/pub#2769]
# Environment

- `pub version` or `flutter pub version`: Pub 2.12.0-62.0.dev
- OS version: Debian GNU/Linux rodete
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

In an effort to help out a community contributor with the migration tool (see https://github.com/dart-lang/sdk/issues/44280) I cloned https://github.com/fluttercommunity/get_it/commit/dd56ba992994eb91838d12a9191115066782327a and then ran `flutter pub upgrade`.  This produced the following error messages:

```
Running "flutter pub upgrade" in get_it...                          3.1s
Because get_it_example depends on get_it from path which doesn't exist (could not find package get_it at "..\"), version solving failed.
Running "flutter pub upgrade" in example...                             
pub upgrade failed (66; Because get_it_example depends on get_it from path which doesn't exist (could not find package get_it at "..\"), version solving
failed.)
```

The problem is specific to this package, and appears to be due to the following text from `pubspec.yaml` in the package's `example` subdirectory ([context](https://github.com/fluttercommunity/get_it/blob/dd56ba992994eb91838d12a9191115066782327a/example/pubspec.yaml#L11)):

```yaml
dependencies:
  get_it:
    path: ..\ # Note: `\` rather than `/`
```

(If I change the `\` to a `/` the problem goes away).

Presumably all the developers of this package use Windows, so they are used to using `\` as a path separator, and did so in their pubspec, and pub didn't complain.  But pub doesn't allow `\` as a path separator on Linux.

## Expected behavior

If a `pubspec.yaml` works on Windows, it should work on Linux too.  This means that `pubspec.yaml` files should either uniformly accept `\` as a path separator regardless of OS, or uniformly reject `\` regardless of OS.

**Comment by sigurdm** [comment]
We have been doing whatever package:path does. But I agree that it is desirable to have portable pubspecs.

Now the question is how to move forward?

* If we disallow '\' on windows that would be a breaking change for those existing pubspecs.
* If we allow '\' on mac/linux it would make it impossible to name filepaths with that character.
I think that might be ok - who puts a '\' in a filename anyway? @jonasfj WDYT?

**Comment by jonasfj** [comment]
@pq could we do a quick hint in the analyzer to warn away from using `\` in path dependencies?

**Comment by pq** [comment]
@jonasfj: I don't see any reason not to add a hint.  i'd be happy to take a look when i'm back from break.

**Comment by sigurdm** [comment]
So I guess we leave the current behaviour in pub?

**Comment by pq** [comment]
Tracking issue opened in https://github.com/dart-lang/sdk/issues/44358.

**Comment by sigurdm** [comment]
Closing this as fixed. Becuse dart-lang/sdk#44358 was done.
