### ISSUE TITLE
Cannot download stagehand for dart

### ISSUE THREAD

**Issue by An7hony1998** [dart-lang/pub#2771]
Ive been trying to download for the entire day the stagehand to be able to use dart in vs code and I keep getting this error. Already tried with VPN but still doesn't work. 

PS C:\>  pub global activate stagehand
 Resolving dependencies...
 + args 1.6.0 
 + charcode 1.1.3
 + collection 1.14.13
 + http 0.12.2
 + http_parser 3.1.4
 + meta 1.2.4
 + path 1.7.0
 + pedantic 1.9.2
 + source_span 1.7.0
 + stagehand 3.3.11
 + string_scanner 1.0.5
 + term_glyph 1.1.0
 + typed_data 1.2.0
 + usage 3.4.2
 Downloading stagehand 3.3.11...
 HTTP error 403: Forbidden
 package:pub/src/http.dart 221:5                 _ThrowingClient.send
 ===== asynchronous gap ===========================
 package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
 ===== asynchronous gap ===========================
 package:pub/src/source/hosted.dart 399:37       BoundHostedSource._download
 ===== asynchronous gap ===========================
 package:pub/src/source/hosted.dart 266:13       BoundHostedSource.downloadToSystemCache
 package:pub/src/global_packages.dart 201:50     GlobalPackages._installInCache.<fn>.<fn>
 package:pub/src/http.dart 278:51                withDependencyType
 package:pub/src/global_packages.dart 197:14     GlobalPackages._installInCache.<fn>
 dart:async                                      Future.wait
 package:pub/src/global_packages.dart 196:18     GlobalPackages._installInCache
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/solver/version_solver.dart      VersionSolver.solve
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>  
 dart:async                                      _completeOnAsyncReturn
 package:pub/src/solver/version_solver.dart      VersionSolver._result
 This is an unexpected error. Please run

 pub --trace global activate stagehand

**Comment by sigurdm** [comment]
Is this still an issue?
