### ISSUE TITLE
Core pubspec package

### ISSUE THREAD

**Issue by rezi-nicospencer** [dart-lang/pub#2783]
It would be really nice to have Dart package that exports a lot of the core logic of pub e.g. spec and lock parsing, system cache management, etc. to build extra tooling around the dependency manager. There are some packages on pub.dev that do pubspec parsing and lock parsing but why not just make the real deal public? 😅

**Comment by sigurdm** [comment]
I think the main reason is that we don't want to commit to maintaining the interface.

We are building more and more cli commands that can be used for programmatically updating and modifying the cache and pubspec. I think that is the way to got.

**Comment by sigurdm** [comment]
Closing as wont-fix - (at least for now).
