### ISSUE TITLE
Support allowing platform specific dependencies

### ISSUE THREAD

**Issue by spekary** [dart-lang/pub#2785]
Please describe the feature:

A way to specify the platform for a dependency such that if the pubspec.yaml is used on a platform that is not included in the platform specification for a particular dependency, the dependency is ignored.

 and your use case.

Recently Flutter started support for Windows. However, Windows is only working on the master channel for now. Sometimes on the dev channel it works. So, I have this problem that if I want to use Flutter to create both an Android app and Windows app, and I want my Android app to be stable, I have to use two different channels, which specify two different versions of the SDK.

As part of Windows support, there is a nice library for window sizing called "windows_size". This library is not in dev.pub, so you have to use a special import to use it, like this:
```
    window_size:
      git:
        url: git://github.com/google/flutter-desktop-embedding.git
   ...
```

However, if I put this in the pubspec.yaml file, and then change to stable channel and try to build Android, the build fails and I get this:

```
The current Dart SDK version is 2.10.3.

Because <my_project> depends on window_size from git which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
```

I can use a number of techniques to make it so that my code only calls window_size from Windows code, but there does not seem to be any way around having pubspec.yaml complain about this.

Another possibility would be to be able to specify the pubspec.yaml file to use when building, so we could simply use a different file on a different platform.

 Are there any workarounds today?

- Force all builds to use the master channel, which really isn't an option
- Create a completely different project, with a different pubspec.yaml, and separate out platform specific code from platform dependent code, requiring different source code repositories and sub projects.
- Use some kind of pre-build step that swaps out and renames platform specific pubspec.yaml files.

**Comment by sigurdm** [comment]
Pub is able to get the `window_size` package no matter what platform you are on. The problem is that it requires a newer sdk.

You can try running with a dart 2.12 beta sdk.
