### ISSUE TITLE
Ignoring Files when Publishing - gitignore doesn't work 

### ISSUE THREAD

**Issue by TheHighriser** [dart-lang/pub#2786]
I have searched through the issues already and I don't find anything. Either I am doing something completely wrong or this wasn't used by anyone.

I am trying to exclude certain things from publishing. So e.g. I am trying to exclude the folder "pleaseIgnoreMe/". So I will enter "pleaseIgnoreMe/" into the .gitignore file. When doing a publish --dry-run, I can still see the folder "pleaseIgnoreMe". I then tried to do a normal publish, because I though maybe this is not working for --dry-run and exclude a folder which was not needed and it still is not working. The published artifact has "pleaseIgnoreMe".

The documentation says the only way is the .gitignore file (https://dart.dev/tools/pub/publishing#what-files-are-published). Is this working for anybody?

**Comment by sigurdm** [comment]
Yeah this seems broken. Played a bit with this.
I think the .gitignore is only respected for files not already checked in.

we should be able to use `git check-ignore --no-index`

**Comment by sigurdm** [comment]
After thinking more about this - we cannot use the .gitignore file for this. If a file is already checked in, then .gitignore should not count for that. We should not change the semantics of that. For example if a user has ignored '*.tmp' files in .gitignore, but has checked a single 'test.tmp' file in to the test suite, it would be surprising that pub does not publish that file.

Therefore I started working on a pubignore file that will allow ignoring files for publishing only: https://github.com/dart-lang/pub/pull/2787.
