### ISSUE TITLE
I cann't upgrade?!

### ISSUE THREAD

**Issue by nikaeene** [dart-lang/pub#2788]
pub --trace pub upgrade '--verbosity=error' --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
HTTP error 403: Forbidden
package:pub/src/http.dart 224:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:18  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 399:20       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 266:7        BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 435:35          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7           Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 47:5       UpgradeCommand.runProtected
This is an unexpected error. Please run

    pub --trace pub upgrade '--verbosity=error' --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)

**Comment by sigurdm** [comment]
Sorry for not answering before.

Are you using a mirror, in china or behind a VPN?

Do you still see this error?
