### ISSUE TITLE
no-op `pub global activate <package>` causes latency

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/pub#2791]
In flutter_tools/.../devtools_launcher.dart, we need to run `pub global run devtools`. At the same time, we need to make sure the devtools package is globally activated, and we need to ensure that, if it is already activated, the latest available version is in use. See https://github.com/flutter/flutter/pull/71737/files#diff-640de6fc5df0761e2783c73b6477083e9f1eeba8163f101ee0c795e0ac7e5564R50 for code and relevant discussion.

AFAIK, the only way to ensure the latest available version of devtools is activated is to run `pub global activate devtools` again. The issue is that this is creating ~4.5 seconds of latency, even when the call is a no-op (when the latest published version of package:devtools was already activated).

2 questions:
1) is there a different way to achieve the requirements of our use case (ensure devtools is activated and that the latest version is in use)? We would need a way to check the version of a globally activated package.
2) can the latency from pub be improved when the latest version of a package is already active?

**Comment by sigurdm** [comment]
Hmm - I guess we could 

* make a check is the discovered version is the same as the one currently being installed.
* Have a `--no-precompile` flag as we have for `pub get`. That would make precompilation only happen when run. 

More hacky ideas for workarounds:
As mentioned in the linked issue we have `pub global list` I guess something could be hacked up on the commandline.
The latest version of a package can be queried from pub.dev with:
```curl https://pub.dev/api/packages/devtools | jq '.["latest"]["version"]'```

As a workaround: Is there any chance you could use dev_tools as a dev_dependency? That way you can use `pub get` and take advantage of the (default) --no-precompile.
Then you would run it with `pub run devtools`

**Comment by kenzieschmoll** [comment]
> make a check is the discovered version is the same as the one currently being `installed.`

IMO, this seems like the most robust solution. Running `pub global activate <package>` should check that the package is outdated and return early if not, avoiding the heavy work of doing an additional install.

> As mentioned in the linked issue we have pub global list I guess something could be hacked up on the commandline.
> The latest version of a package can be queried from pub.dev with:
> curl https://pub.dev/api/packages/devtools | jq '.["latest"]["version"]'

Running `curl https://pub.dev/api/packages/devtools | jq '.["latest"]["version"]'` gives me an error because `jq` is not installed on my machine. This seems problematic in case a user also does not have `jq` installed.

> As a workaround: Is there any chance you could use dev_tools as a dev_dependency? That way you can use pub get and take advantage of the (default) --no-precompile.
> Then you would run it with pub run devtools

I'm not sure what this would look like. My gut response says this wouldn't be an option, because a user will be launching these commands at runtime.

@zanderso

**Comment by zanderso** [comment]
> > make a check is the discovered version is the same as the one currently being installed.
> 
> IMO, this seems like the most robust solution. Running `pub global activate <package>` should check that the package is outdated and return early if not, avoiding the heavy work of doing an additional install.

+1

> > As mentioned in the linked issue we have pub global list I guess something could be hacked up on the commandline.
> > The latest version of a package can be queried from pub.dev with:
> > curl https://pub.dev/api/packages/devtools | jq '.["latest"]["version"]'
> 
> Running `curl https://pub.dev/api/packages/devtools | jq '.["latest"]["version"]'` gives me an error because `jq` is not installed on my machine. This seems problematic in case a user also does not have `jq` installed.

Yeah, we can't rely on something like `jq` existing across all platforms. We could add code to parse the result of the `curl` to the flutter_tool, but parsing code like that tends to increase crash rate for ~2 cycles as bugs get shaken out. The delay is likely preferable to this option.

> > As a workaround: Is there any chance you could use dev_tools as a dev_dependency? That way you can use pub get and take advantage of the (default) --no-precompile.
> > Then you would run it with pub run devtools
> 
> I'm not sure what this would look like. My gut response says this wouldn't be an option, because a user will be launching these commands at runtime.

This would defeat part of the purpose of @kenzieschmoll's PR.

**Comment by sigurdm** [comment]
Yeah - the suggested workarounds are not really viable here.
