### ISSUE TITLE
Problem cloning git dependency through ssh-agent

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/pub#2800]
https://github.com/flutter/flutter/issues/71574

# Environment

Pub 2.10.4

# Problem
I've just done a clean windows 10 pro install and not installed dart sdk as the docs mention that the flutter sdk is all thats required.

I'm having difficulty with a project that has dependencies in github. I'm starting a ssh agent with start-ssh-agent, when I run flutter pub get I get the following:
```
PS D:\dev\dart\os_app> flutter pub get
Git error. Command: `git clone --mirror git@github.com:jimmyff/great_circle_distance.git D:\dev\sdks\flutter\.pub-cache\git\cache\great_circle_distance-6016cccb55950ff1b6724c8c96eed8fafb100055`
stdout: 
stderr: Cloning into bare repository 'D:\dev\sdks\flutter\.pub-cache\git\cache\great_circle_distance-6016cccb55950ff1b6724c8c96eed8fafb100055'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
exit code: 128
Its failing with the ssh key however if I immediately run git clone git@github.com:jimmyff/great_circle_distance.git test it checks out correctly? It's as if flutter isn't making use of the ssh agent.
```

pubspec:
```yaml
...
  great_circle_distance:
    git: git@github.com:jimmyff/great_circle_distance.git
...
``` 

Is the the problem with SSH agent forwarding?

Thanks

**Comment by GanongLS** [comment]
is this still open? owh god

**Comment by zionnite** [comment]
still having the same issue, were u guys able to resolve it???

**Comment by jayjah** [comment]
@zionnite Just make sure to run `flutter pub get` in a terminal where you can provide the necessary password for your ssh-key. Once provided it should work.

**Comment by zionnite** [comment]
thanks man

**Comment by sigurdm** [comment]
@jimmyff does this also solve the issue for you?

**Comment by zionnite** [comment]
what i did whats to add my system keychain to github and it fix it for me

**Comment by jimmyff** [comment]
> @jimmyff does this also solve the issue for you?

I'm confident I tried that but I'm afraid I gave up on Windows entirely (death by a thousand paper cuts). I don't have the same issue on Linux and Mac.

**Comment by sigurdm** [comment]
I will close this as I don't believe it is a problem in the pub client, rather in the ssh configuration.
