### ISSUE TITLE
Bad state: Could not find 7zip.

### ISSUE THREAD

**Issue by veekart** [dart-lang/pub#2815]
I Tried adding new dependency to my pubspec.yaml file and after running 'pub get' i have this error below

`
Bad state: Could not find 7zip.

package:pub/src/io.dart 844:3                _pathTo7zip.<fn>
package:pub/src/io.dart 845:3                _pathTo7zip
package:pub/src/io.dart                      _pathTo7zip
package:pub/src/io.dart 786:22               extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart                      extractTarGz.<fn>
package:pub/src/io.dart 732:20               withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 777:31               extractTarGz
package:pub/src/source/hosted.dart 400:11    BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 266:13    BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 435:48       Entrypoint._get.<fn>
dart:async                                   runZoned
package:pub/src/http.dart 279:10             withDependencyType
package:pub/src/entrypoint.dart 431:12       Entrypoint._get
dart:async                                   Future.wait
package:pub/src/entrypoint.dart 261:20       Entrypoint.acquireDependencies
dart:async                                   _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart   VersionSolver.solve
dart:async                                   _completeOnAsyncReturn
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching
dart:async                                   _completeOnAsyncReturn
package:pub/src/rate_limited_scheduler.dart  RateLimitedScheduler.withPrescheduling
dart:async                                   _completeOnAsyncReturn
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching.<fn>
dart:async                                   _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart   VersionSolver.solve.<fn>
dart:async                                   _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart   VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
Process finished with exit code 1`

**Comment by sigurdm** [comment]
Sounds like a broken sdk installation.

I expect you are on windows?

You dshould have file here:
`$SDK/third_party/zip/7za.exe

**Comment by jonasfj** [comment]
quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by sigurdm** [comment]
Closing this for lack of details.

Please reopen if you can give us more information on this issue.
