### ISSUE TITLE
Pub should be migrated to null safe package_config

### ISSUE THREAD

**Issue by scheglov** [dart-lang/pub#2820]
We have a [CL that migrates](https://dart-review.googlesource.com/c/sdk/+/176486) `package:analyzer` to null safety, but we cannot land it because the null safe `package:package_config` [should be pulled](https://github.com/dart-lang/package_config/issues/97) into Dart SDK repo first. But this cannot be done until `pub` stops using APIs that are removed in the null safe version of `package:package_config`.

**Comment by sigurdm** [comment]
Rolling into sdk: https://dart-review.googlesource.com/c/sdk/+/177603
