### ISSUE TITLE
Got socket error trying to find package english_words at https://pub.dartlang.org.

### ISSUE THREAD

**Issue by Ayan0904** [dart-lang/pub#2825]
pubspec.yaml

name: sasuke_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  english_words:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/download.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf

**Comment by Amenojikara** [comment]
I am not behind firewall or not using any proxy just simply using hotspot from my phone ...

**Comment by jonasfj** [comment]
quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting files..

**Comment by jonasfj** [comment]
Also can you access the site using `curl` ?

Also what country are you located in?

**Comment by sigurdm** [comment]
Closing as stale.

Please open a new issue if you can still reproduce and can provide more information.
