### ISSUE TITLE
Add a message to check LICENSE to publish

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub#2836]
Can we display a warning message, when a package author tries `pub publish` but the `LICENSE` file is empty?

(Related: https://github.com/dart-lang/pub-dev/issues/4373)

**Comment by jonasfj** [comment]
I think we should just forbid empty license files in the server: https://github.com/dart-lang/pub-dev/issues/4445

**Comment by jonasfj** [comment]
It would be nice to warn if the LICENSE doesn't match any SPDX license identifier.

**Comment by sigurdm** [comment]
So we need something like: https://github.com/spdx/spdx-license-matcher - right?
