### ISSUE TITLE
pub get failed once PUB_HOSTED_URL is set

### ISSUE THREAD

**Issue by intoxicated** [dart-lang/pub#2839]
# Environment

- `pub version` or `flutter pub version`: 2.10.4
- OS version: mac os x 10.15.7
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem

After PUB_HOSTED_URL is set, flutter pub get failed 

## Expected behavior

successfully installed

## Actual behavior

exited with fail

## --trace output

```
ERR : The method 'map' was called on null.
    | Receiver: null
    | Tried calling: map<MapEntry<PackageId, _VersionInfo>>(Closure: (dynamic) => MapEntry<PackageId, _VersionInfo>)
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                   Object.noSuchMethod
    | package:pub/src/source/hosted.dart 194:45   BoundHostedSource._fetchVersions
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 113:52           captureErrors.wrappedCallback
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 126:11           captureErrors
    | package:pub/src/command_runner.dart 182:13  PubCommandRunner.runCommand
```

**Comment by jonasfj** [comment]
What did you set it to?

Can you run with `--trace` and dump the output to a gist?

It might simply be an incorrect URL in your env var...

**Comment by jonasfj** [comment]
I'm guessing we should look to improve our JSON parsing to be more robust and detect invalid responses -- because that's probably what's happening here.
