### ISSUE TITLE
Add deprecation comment to .packages

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2843]
The first line (and afaik) only the first line of `.packages` can be a comment.
We should update this comment to highlight that the file is deprecated.

**Comment by lrhn** [comment]
No, any line of `.packages` can be a comment.
(That said, people have written non-compliant parsers before, so it's probably safer to keep the comments at the top).

**Comment by sigurdm** [comment]
Done in https://github.com/dart-lang/pub/pull/2845
