### ISSUE TITLE
SolveReport should never throw I/O error from failing to fetch status

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2854]
If we fail to fetch status of a package we should never throw in `SolveReport`...

**Comment by jonasfj** [comment]
We should probably also test that failing to prefetch a package we don't need, won't cause an error the user will see. I think that is already the case, but it's a very similar test case.

**Comment by sigurdm** [comment]
> We should probably also test that failing to prefetch a package we don't need

I believe this is part of the scheduler logic. The failures will stay inside the completers until somebody awaits them.
