### ISSUE TITLE
pub global run needs to check if it should downgrade packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#2866]
If you `pub global activate` a package on a recent SDK, and then downgrade to an older SDK, `pub global run` may try to run with the same packages that may have SDK constraints in their pubspec disallowing them.

As of today you can see this with the following example:

- On a Dart `2.12.0-` version. `pub global activate flutter_plugin_tools`. Picks up `charcode` version `1.2.0`
- Downgrade the SDK to `2.10.5`
- `pub global run flutter_plugin_tools`.

```
Precompiling executable...
Failed to precompile flutter_plugin_tools:flutter_plugin_tools:
../../.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/ascii.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/charcode.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/html_entity.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
```

**Comment by mit-mit** [comment]
cc @jonasfj @sigurdm, this might be a release blocker

**Comment by jonasfj** [comment]
**workaround**, if the root package, in this case `flutter_plugin_tools` had an SDK constraint `2.12.0-0` this wouldn't have been a problem as we do [test the root SDK constraint](https://github.com/dart-lang/pub/blob/16a6210dd0bb24e9b93738b607d600244c939dee/lib/src/global_packages.dart#L366-L379).

Hmm, I'm not sure this is new, I think the same issues existed when we shipped extension methods.
But you are more likely to hit the issue with null-safety.

There is patch in https://github.com/dart-lang/pub/pull/2867

**Comment by jonasfj** [comment]
@mit-mit, please reflag if you think this is critical. From chat I think the conclusion is that this only affects users who downgrade SDK.

In either case, the fix proposed will just print a prettier error message telling the user to run: `dart pub global activate <package>` again.

Which is better than the error message above, but hardly the end of the world. If read probably the error message above, actually says:
> The specified language version is too high. The highest supported language version is 2.10.

Which is close to indicating: that this doesn't work because you downgraded you SDK version.

**Comment by mit-mit** [comment]
I'm OK with removing critical given the new understanding.
