### ISSUE TITLE
Change pub to use latest dart cli tools 

### ISSUE THREAD

**Issue by Sameerkash** [dart-lang/pub#2869]
# Environment

- `pub version` or `flutter pub version`: Pub 2.12.0-133.7.beta
- OS version: macOS 11.0.1 Big Sur

# Problem

While running `dart pub upgrade` in `image_picker/image_picker_platform_interface` the pub output showed outdated recommendation  

## Expected behavior

No dependencies changed.
18 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` or `flutter pub outdated`for more information.

## Actual behavior

No dependencies changed.
18 packages have newer versions incompatible with dependency constraints.
Try `pub outdated` for more information.

**Comment by jonasfj** [comment]
Issue is that we write:
 * `pub outdated`
 
 when the message should be:

  * `dart pub outdated` or `flutter pub outdated`.

**Comment by sigurdm** [comment]
I think this was fixed already recently: https://github.com/dart-lang/pub/commit/6a60b0ee08e41ef75b95fa53a12d8ca67810af23

Please reopen if I am mistaken.
