### ISSUE TITLE
acceso limitado desde Cuba

### ISSUE THREAD

**Issue by ysblanco84** [dart-lang/pub#2874]
[qrreaderapp] flutter pub get
Running "flutter pub get" in qrreaderapp...                     
HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned
package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling
dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>
dart:async                                      runZoned
package:pub/src/http.dart 279:10                withDependencyType
package:pub/src/entrypoint.dart 403:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned
package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling
dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 10 in 64 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get

dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 11 in 64 seconds...

HTTP error 403: Forbidden

package:pub/src/http.dart 221:5                 _ThrowingClient.send

===== asynchronous gap ===========================

package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 397:37       BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13       BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48          Entrypoint._get.<fn>

dart:async                                      runZoned

package:pub/src/http.dart 279:10                withDependencyType

package:pub/src/entrypoint.dart 403:12          Entrypoint._get
dart:async                                      Future.wait

package:pub/src/entrypoint.dart 252:18          Entrypoint.acquireDependencies

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve

dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching

dart:async                                      _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling

dart:async                                      _completeOnAsyncReturn

package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>

dart:async                                      _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart      VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 12 in 64 seconds...

**Comment by sigurdm** [comment]
You could try using a mirror.
See instructions here: https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site

**Comment by sigurdm** [comment]
Did you try this?

**Comment by ysblanco84** [comment]
Hello Sigurd, I will try  today, then I will tell you.the result, thanks
Regards

**Comment by ysblanco84** [comment]
Hello I have a question, after I configure the global variables
assuming that everything works I have the same access denied problem
when loading the emulator and compiling it with gradle, any
suggestions to solve this and be able to run my complete environment
from Cuba.
Thank you

2021-02-09 8:24 GMT-05:00, Yoan Suarez Blanco <ysblanco.1984@gmail.com>:

**Comment by sigurdm** [comment]
Can you tell me a bit more about the network conditions you have.
Can you access pub.dev from a browser?

Can you paste the error you get from gradle?

**Comment by ysblanco84** [comment]
Hi this is error from gradle, my phone its Huawei P9
---------------------------------------------------------------------------------


Launching lib\main.dart on EVA AL10 in debug mode...
 lib\main.dart

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.0.
         > Could not get resource
'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
            > Could not GET
'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


2021-02-09 10:10 GMT-05:00, Sigurd Meldgaard <notifications@github.com>:

**Comment by sigurdm** [comment]
Hmm - I guess Gradle network issues are out of scope for the pub client. You should try finding out how to get to a mirror of those sites.

You could perhaps ask for help in github.com/flutter/flutter/issues .
