### ISSUE TITLE
dart pub get can not run on android termux

### ISSUE THREAD

**Issue by sinojelly** [dart-lang/pub#2879]
I found that on android 10 + termux, when i run dart pub get, it used /bin/tar to process downloaded archieve.tar file, this tar command is from toybox, and it says invalid tar format. I want to use the tar command in termux, what should I do? Thanks!

**Comment by sigurdm** [comment]
We have recently landed: https://github.com/dart-lang/pub/pull/2817 that implements tar in pure dart, removing the reliance on external tar.

It has not been rolled to the sdk yet. 

Meanwhile in theory you could do your own checkout of pub from this repo. But that again relies on pub to get the dependencies - that won't work :).

You could also try to find a tar implementation for android that is compatible. We test with gnu tar on linux and bsd tar on macos.

**Comment by sigurdm** [comment]
Closing this as the solution has already landed
