### ISSUE TITLE
Request delete versions

### ISSUE THREAD

**Issue by JarvanMo** [dart-lang/pub#2887]
Hi team,
Currently, I'm working on migration of null-safety and I published a wrong version to `-null-safety`.  As a result, I can't upload correct  versions because
```
You're about to publish a package that opts into null safety.The previous version (3.1.0-nullsafety.2) isn't opted in.
```
Could you please help me delete the following packages? 
[fluwx 3.1.0-nullsafety.2](https://pub.dev/packages/fluwx/versions/3.1.0-nullsafety.2)
[fluwx_no_pay 3.1.0-nullsafety.1](https://pub.dev/packages/fluwx_no_pay/versions/3.1.0-nullsafety.1)

Thanks.

**Comment by sigurdm** [comment]
The message is merely a warning. You should be able to upload anyway.

**Comment by jonasfj** [comment]
Deletion requests goes through: https://pub.dev/policy

Also as sigurdm says, this is just a warning :D
