### ISSUE TITLE
Add 'pub login' command

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/pub#2891]
It would be handy to add `pub login` to switch accounts, rather than running something like `pub publish` in order to log in. There is already `pub logout`, which deletes the `$HOME/.pub-cache/credentials.json` file.

**Comment by tusharojha** [comment]
I have just checked that `pub` on the master & beta is having a `login` command. It's not available in the stable version as of now.

**Comment by sigurdm** [comment]
Yes - we it'll be available in the next stable version, it should hopefully be out soon!
`
