### ISSUE TITLE
Unexpected character (at character 1)   

### ISSUE THREAD

**Issue by haibowen** [dart-lang/pub#2893]
flutter pub get 

Unexpected character (at character 1)                                   
<html>                                                                  
^                                                                       
dart:convert                                        jsonDecode          
package:pub/src/source/hosted.dart 192:17           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================                      
dart:async                                          _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 83:30   RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 86:30   RateLimitedScheduler._processNextTask
package:pool/pool.dart 127:28                       Pool.withResource   
===== asynchronous gap ===========================                      
package:pub/src/rate_limited_scheduler.dart 130:37  RateLimitedScheduler.schedule.<fn>

**Comment by sigurdm** [comment]
I think this should have been fixed by: https://github.com/dart-lang/pub/pull/2847

If this is still a problem in a new Dart SDK, please open a new issue with steps to reproduce.
