### ISSUE TITLE
userInfo inside pub login command doesn't contain user's name

### ISSUE THREAD

**Issue by tusharojha** [dart-lang/pub#2897]
## Description

I am new here and looking to contribute. Therefore, I stumbled upon the `pub login` command which uses oauth2 to authenticate the user and store their email & name into userInfo. But I tried with two different accounts and both resulted in a `null` for the name field.

Here is the response coming from `userinfo_endpoint`:

```dart
{
sub: 103068153864256870934, 
picture: https://lh3.googleusercontent.com/a-/AOh14GgynQMyqolmPXQ87dTgmpG5PQaLk75IlNlzEf-qUA=s96-c, 
email: tusharojha2001@gmail.com,
email_verified: true
}
``` 
Either we can remove the name property from the `UserInfo` class or the API should respond with the user's name.

**Comment by tusharojha** [comment]
@sigurdm @jonasfj PTAL.

**Comment by jonasfj** [comment]
Documentation for this is somewhere under: https://developers.google.com/identity

From what I saw we don't always get the name when we lookup userinfo.

So yes, maybe it would be good if we handle the case where it's not present. And if we reference the relevant docs in a comment.

**Comment by tusharojha** [comment]
Right!
Also, the pub login command tries to display the name even if it's null.
I guess this would work:

```dart
class _UserInfo {
  final String name;
  final String email;
  _UserInfo(this.name, this.email);
  @override
  String toString() => '<$email> ${name ?? ''}';
}

```

**Comment by sigurdm** [comment]
That looks right. Are you interested in making a PR?

**Comment by tusharojha** [comment]
Yes, I would love to do it! 😊
