### ISSUE TITLE
pub get failed (server unavailable)

### ISSUE THREAD

**Issue by mohammadakbarpour** [dart-lang/pub#2899]
hi,
When I want to add a package to my package's pubspec.yaml file, (forExample: english_words: ^3.1.5),  after click on Pub get I see this error . Please help me to solve it. Thanks

`
HTTP error 403: Forbidden
package:pub/src/http.dart 221:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 399:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 266:13       BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 430:48          Entrypoint._get.<fn>
package:pub/src/http.dart 278:51                withDependencyType
package:pub/src/entrypoint.dart 426:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 263:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching
dart:async                                      _completeOnAsyncReturn
package:pub/src/rate_limited_scheduler.dart     RateLimitedScheduler.withPrescheduling
dart:async                                      _completeOnAsyncReturn
package:pub/src/source/hosted.dart              BoundHostedSource.withPrefetching.<fn>
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve.<fn>
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...`

**Comment by RubenBenBen** [comment]
yes, me too, 
every. goddamn. time.
Seems like a location issue or idk.

**Comment by JagadeshBoopathi** [comment]
same issue for me too in Mac book. The issue does not occur in Windows on same network. 

Can we have this checked?

```
Running "flutter pub get" in project1...                       
Got socket error trying to find package async at https://pub.dartlang.org.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```

**Comment by sigurdm** [comment]
Does this still reproduce?

**Comment by sigurdm** [comment]
Closing as stale
