### ISSUE TITLE
`global_packages` are missing `pubspec.yaml`

### ISSUE THREAD

**Issue by luanpotter** [dart-lang/pub#2900]
# Environment

- `pub version`: `Pub 2.12.0-259.16.beta`
- OS version: `5.11.2-arch1-1`
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

I expect the `pubspec.yaml` file to be bundled with my packages.

Packages that are installed with `pub global activate` are stored in `~/.pub-cache/global_packages`, unlike normal packages that are reside in `~/.pub-cache/hosted`.

Packages that are normally download with `pub get` on the `hosted` folder do have a `pubspec.yaml` file as I would expect. However, packages on the `global_packages` folder do not.

My package is a CLI application that expect the file to be there so it could be read and extract metadata. In my instance, I wanted to read the `version` of the package to provide a `cmd --version` that automatically provides the right version.

The folder does contain the `pubspec.lock` file and the `.dart_tool/package_config.json` file. And I could do a workaround to try to get the version from those files, but:

* that would not allow me to access other metadata other than the version (like name, description, urls, etc)
* that is inconsistent as the version is only present in those files in the global_packages version, so it does not work locally. I would have to have distinct code to get the information when it's run locally with `dart main.dart` or via `pub global`.
* these are less standard files and might rely on some string manipulation to extract the version from file paths. The pubspec is well known and written by me so it will be always just like I expect (for my own package). Also it's probably a more stable standard as the other two are internal files.

Regardless of alternatives, I don't see why the file should not be included. It is already included for every package on the `hosted` folder, which is the vast majority. Adding it to `global_packages` not only would make it consistent, it is a single plain-text file that is usually very, very small. So I don't see reasons not to have it there; not sure if there are any that I am failing to see or if this is just a bug/unintended consequence.

The file is included in the tar file download from the pub repository, AFAICS. So should we change the pub cli tool to keep it so it can be used by apps/packages? Or am I overlooking something?

**Comment by sigurdm** [comment]
The activated package is just a lockfile pointing to where the package is actually stored in the cache.

Look at it as a package with a single dev-dependency. So you need to find the pubspec.yaml in eg. pub_cache/hosted/...

For finding the location in cache programmatically try https://api.dart.dev/stable/2.19.2/dart-isolate/Isolate/packageConfig.html.

**Comment by sigurdm** [comment]
Closing, please respond if answer was not fulfilling
