### ISSUE TITLE
pub client mentions pub.dartlang.org

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub#2909]
I think it should mention pub.dev instead.

**Comment by sigurdm** [comment]
We should indeed.

It would however be slightly lying, as the pub client still uses pub.dartlang.org (which just binds to the same host) for connecting to when using the api.

The reason for that is that we store the domain-name in the cache, and we don't want to leave people with existing cache-entries for pub.dartlang.org and then duplicate everything in pub.dev.

Not sure what the best solution is. I think the safest is to change the client to connect to pub.dev, but always rewrite that to pub.dartlang.org when storing in the cache.

Renaming stuff in the cache would work poorly if you changed back to an old client.

@jonasfj any ideas?

**Comment by jonasfj** [comment]
It's also possible that we should pick a Dart version from which we start using `pub.dev` and then accept that we have cache duplication.

So far we've been removing `pub.dartlang.org` from all public messages / errors / warnings / etc.., it mostly shows up in `PUB_CACHE` and `pubspec.lock`.

If we want to eventually get completely rid of it, I would suggest we just duplicate the cache.. That'll also alleviate any concerns about switching back and forth between different SDK versions.

**Comment by jonasfj** [comment]
@srawlins any particular place where you run into this that you think we should change?

**Comment by sigurdm** [comment]
See: https://github.com/dart-lang/pub/pull/2646

**Comment by srawlins** [comment]
Oops, sorry! I totally forgot to include _any_ details. I saw this at `dart pub --help`.

**Comment by sigurdm** [comment]
This has been fixed. We now use pub.dev everywhere in the client.
