### ISSUE TITLE
flutter doctor log

### ISSUE THREAD

**Issue by Vik001** [dart-lang/pub#2911]
pub.flutter-io.cn%E2%80%8B is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%E2%80%8B                                              
                 ^                                                      
package:pub/src/source/hosted.dart 570:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 211:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================                      
package:pub/src/rate_limited_scheduler.dart 87:11  RateLimitedScheduler._processNextTask.runJob
This is an unexpected error. Please run                                 
                                                                        
    dart pub --trace get --no-precompile                                
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_tools...                           
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment]
It looks like you got some bad characters into your PUB_HOSTED_URL environment variable.

Try following https://docs.flutter.dev/community/china to set up the variable.

**Comment by sigurdm** [comment]
Please reopen if that doesn't solve the issue.
