### ISSUE TITLE
dart pub --trace get --no-precompile log

### ISSUE THREAD

**Issue by Vik001** [dart-lang/pub#2912]
vivek@37-203-252-113-on-nets ~ % dart pub --trace get --no-precompile
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to anonymously report feature usage    ║
  ║ statistics and to send basic crash reports. This data is used to help      ║
  ║ improve the Dart platform and tools over time.                             ║
  ║                                                                            ║
  ║ To disable reporting of anonymous analytics, run:                          ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Could not find a file named "pubspec.yaml" in "/Users/vivek".

**Comment by sigurdm** [comment]
does this still reproduce?
