### ISSUE TITLE
"dart pub add" ignores extra options

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2923]
Example of extra input:
 * `dart pub add --dev test ^1.16.0` this should not work.

The correct way to do this is:
 * `dart pub add --dev test:^1.16.0`

We should probably fail if the constraint is not provided correctly. If we don't understand additional options/arguments we should always fail.
That way we can add additional options/arguments in the future.

**Comment by tusharojha** [comment]
I would like to work on it!

**Comment by tusharojha** [comment]
Would you expect it to show a common message in any case with extra arguments? Or for something very specific like the version number extras as per your example?

**Comment by sigurdm** [comment]
I think that if there is more than one argument we want to do something like: `usageException('Takes only a single argument')`.

**Comment by tusharojha** [comment]
Got it, will create a PR for it.
