### ISSUE TITLE
Integrate stagehand into pub

### ISSUE THREAD

**Issue by 89z** [dart-lang/pub#2938]
I am looking for something that will create a `pubspec.yaml` file, so that a users dont have to manually create it. I think this is the current option:

~~~
stagehand package-simple
~~~

Other languages can do this, for example D:

~~~
dub init
~~~

https://dub.pm/commandline.html#init

Go:

~~~
go mod init north
~~~

https://golang.org/cmd/go#hdr-Module_maintenance

Rust:

~~~
cargo init
~~~

https://doc.rust-lang.org/cargo/commands/cargo-init.html

**Comment by 89z** [comment]
https://github.com/dart-lang/stagehand/issues/610

**Comment by 89z** [comment]
https://github.com/dart-lang/pub/issues/1847

https://github.com/dart-lang/pub/issues/2938
https://github.com/dart-lang/sdk/issues/35364
https://github.com/dart-lang/stagehand/issues/610

**Comment by jonasfj** [comment]
This exists with `dart create`. There might be ways to improve though :D

Please move such discussions to https://github.com/dart-lang/sdk

**Comment by sigurdm** [comment]
```
$ dart create --help
Create a new project.

Usage: dart create [arguments] <directory>
-h, --help        Print this usage information.
-t, --template    The project template to use.
                  [console-simple (default), console-full, package-simple, web-simple]
    --[no-]pub    Whether to run 'pub get' after the project has been created.
                  (defaults to on)
    --force       Force project generation, even if the target directory already exists.

Run "dart help" to see global options.

Available templates:
  console-simple: A simple command-line application. (default)
    console-full: A command-line application sample.
  package-simple: A starting point for Dart libraries or applications.
      web-simple: A web app that uses only core Dart libraries.
```
