### ISSUE TITLE
Roll pub into dart-sdk

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2939]
We've recently added dependency on `package:tar` to avoid using system tar implementation.
This means migrating into Dart SDK will involve a bit of moving around with dependencies.

Specifically:
 * [x] Land `ChunkedStreamReader` in `package:async` (https://github.com/dart-lang/async/pull/161)
 * [x] Migrate `package:tar` to use `ChunkedStreamReader` from `package:async`
 * [x] Vendor `https://github.com/simolus3/tar/` in `pub`
 * [x] Re-land pub in Dart SDK ([sdk/+/192304](https://dart-review.googlesource.com/c/sdk/+/192304))
 * [x] Stop packaging 7zip with Dart SDK on Windows.

**Comment by simolus3** [comment]
I've just published (and tagged) version 0.3.3 of `package:tar`. It only depends on the `async`, `meta` and `typed_data` packages, which are available in the SDK repo.

**Comment by jonasfj** [comment]
Filed https://dart-review.googlesource.com/c/sdk/+/199040

**Comment by jonasfj** [comment]
https://dart-review.googlesource.com/c/sdk/+/199250

**Comment by jonasfj** [comment]
Starting 2.14 Dart should no longer include 7zip on windows, and not system tar on linux :D

With a little luck it'll be in the first 2.14 beta :rocket:
