### ISSUE TITLE
Bad element in version when attempting to publish.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub#2945]
I commented out the "publish_to: none" in a pubspec.yaml in a project, and attempted to run `pub publish --dry-run` in order to see what direct dependencies might be missing from the pubspec.yaml, and it crashed:

```
% pub publish --dry-run
[...]
Bad state: No element
dart:core                                         List.first
package:pub_semver/src/version.dart 142:28        Version.primary
package:pub/src/validator/dependency.dart 143:27  DependencyValidator._warnAboutSource
===== asynchronous gap ===========================
package:pub/src/validator/dependency.dart 71:9    DependencyValidator._validateDependencies
===== asynchronous gap ===========================
package:pub/src/validator/dependency.dart 38:5    DependencyValidator.validate
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 178:5           LishCommand._validate
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 153:9           LishCommand.runProtected
This is an unexpected error.
```

Here's the output of `pub publish --dry-run --trace`:
[trace.zip](https://github.com/dart-lang/pub/files/6251027/trace.zip)

The project I was trying this on was [this one](https://github.com/gspencergoog/sampler/tree/main/packages/sampler).

**Comment by sigurdm** [comment]
I could not reproduce this with a current dart sdk.

It seems like the call to Version.primary is now guarded by a condition on versions being non-empty.

Seems this was fixed here: https://github.com/dart-lang/pub/pull/2913
