### ISSUE TITLE
Adding a way to ignore files other then .gitignore.

### ISSUE THREAD

**Issue by Reductions** [dart-lang/pub#2946]
I think It would be nice to have a way to ignore files from publishing other than adding them to `.gitignor.` My use case would be I have big CSV files to test things, and I don't want to publish them as they would exceed the 10MB threshold. At the same time, I want them to be kept in the repo.

What I was thinking of is maybe adding support for .pubignore or something like that.

**Comment by SirusCodes** [comment]
`.pubignore` was already introduced in #2787

**Comment by jjangga0214** [comment]
Issue for docs website: https://github.com/dart-lang/site-www/issues/3399

**Comment by sigurdm** [comment]
This was fixed by https://github.com/dart-lang/pub/pull/2787
