### ISSUE TITLE
question regarding how changes would be made

### ISSUE THREAD

**Issue by vaibhav135** [dart-lang/pub#2950]
OS: Ubuntu 20.04lts
current experience: beginner level

Hello, currently I am exploring the dart-sdk specifically (dart-sdk/sdk/third_party/pkg/pub/lib/src part) where I am looking for the git dependencies and stuff regarding that. 
My question is let's say that if I am tinkering with some file and I do some changes and I want to see the changes made then how I do that? 
Do I need to write the test? what would be the step for it?
Do I need to create a sample app in order to see the changes made? 
My main idea is to explore pub for this issue `https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2021-Project-Ideas#idea-extends-git-source-in-pubspecyaml-to-understand-tags` 
I am very confused please help?

**Comment by jonasfj** [comment]
You don't need to work in the `dart-sdk` to work on `pub`.

All tests can run from this repository, try `dart tool/test.dart`.

You can also run `dart bin/pub.dart` in this repository and you'll have an easy way to test local changes in the repository.

**Comment by vaibhav135** [comment]
So if I change something in let's say `git.dart` then do I only have to run` dart bin/pub.dart` to see the changes.
Also, how do I write the test? Are there any guides on how to write tests on dart because I have never written tests before?

**Comment by vaibhav135** [comment]
> 
> 
> @jonasfj So if I change something in let's say `git.dart` then do I only have to run` dart bin/pub.dart` to see the changes.
> Also, how do I write the test? Are there any guides on how to write tests on dart because I have never written tests before?

@jonasfj  can you please help me with this one

**Comment by sigurdm** [comment]
Not sure this is still relevant, but `dart tool/test.dart` will run all tests.

Tests are located in `test/` - look at other examples for inspiration.

Closing this assuming stale.
