### ISSUE TITLE
Improving message for "precompiling..." in `dart run <package>`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2951]
Maybe we can say `building <package>` or something like that.

**Comment by mit-mit** [comment]
Current experience:

```
dart create -t console-full foobar
cd foobar
dart test
```

=> 

```
mit-macbookpro4:cons mit$ dart test
Precompiling executable... (13.8s)
Precompiled test:test.
00:01 +1: All tests passed!
```

Issues:

1. It's unclear to the user why they are seeing this (what "executable" is being compiled?)
2. The term "precompiling" is confusing

Suggestions:

A. Change "Precompiling executable..." to "Building package executables"
B. Change other instances of "precompiling/precompiled" to the more general "building/built"
C. Consider entirely suppressing this output specifically for the `dart test` command and it's running of `dart run test:test`

WDYT @jonasfj @sigurdm @natebosch @jakemac53 @bkonyi  @kevmoo

**Comment by jakemac53** [comment]
Options A or B sound good to me, but not option C. Option C creates a situation where users end up blaming the packages for being slow (hanging on startup). It is important to have some output here to explain why nothing appears to be running.

**Comment by mit-mit** [comment]
That is good feedback on item C. For the others, I'd like to do both A _and_ B together to keep it consistent.

**Comment by jakemac53** [comment]
Yes both A and B together also sgtm

**Comment by natebosch** [comment]
+1 for changing to "Building".

We could consider making the reason even more specific.

```
Building executable test:test for the first run after changing dependencies... (13.8s)
```

**Comment by mit-mit** [comment]
I listed the current experience above, which prints:

```
mit-macbookpro4:cons mit$ dart test
Precompiling executable... (13.8s)
Precompiled test:test.
00:01 +1: All tests passed!
```

I'm in doubt about what to do for the first line of text. One option is:
```
mit-macbookpro4:cons mit$ dart test
Building package executables... (13.8s)
Built test:test.
00:01 +1: All tests passed!
```

However, I find this a bit confusing as 'executables' has [a very specific meaning](https://dart.dev/tools/pub/pubspec#executables), and that is not what is happening here, right?

I wonder if we should say something more general like `Building package scripts`?

**Comment by jakemac53** [comment]
> However, I find this a bit confusing as 'executables' has [a very specific meaning](https://dart.dev/tools/pub/pubspec#executables), and that is not what is happening here, right?

Afaik it is the exact same thing, we just don't explicitly specify the executables. If you don't do that then there is some heuristic that happens (I think this predates the `executables` section in the pubpsec?). I think it just considers all scripts with a `main` in the `bin` dir to be executables.

**Comment by mit-mit** [comment]
| Afaik it is the exact same thing, we just don't explicitly specify the executables.

That seems to be in conflict with what the current documentation says?

_"A package may expose one or more of its scripts as executables that can be run directly from the command line. To make a script publicly available, list it under the executables field."_

Maybe another option here is to use the more general term "program" as in "Building package programs"? That matches the terminology around running:
https://dart.dev/tools/dart-run

cc @kwalrath

**Comment by jakemac53** [comment]
> That seems to be in conflict with what the current documentation says?
> 
> _"A package may expose one or more of its scripts as executables that can be run directly from the command line. To make a script publicly available, list it under the executables field."_

I think its just that the documentation isn't calling out the default behavior? Is there any observable difference here?

**Comment by mit-mit** [comment]
Fixed in https://github.com/dart-lang/pub/pull/3014 and https://github.com/dart-lang/pub/pull/3017
