### ISSUE TITLE
Request: `pub add` to accept many dependencies

### ISSUE THREAD

**Issue by isacjunior** [dart-lang/pub#2953]
Currently, the `pub add` command accepts only one package.

Would be amazing whether add command could accept many packages.

```
pub add package_one:1.0.0 package_two:2.0.0
```
I found a workaround using [getx_cli](https://github.com/jonataslaw/get_cli)

**Comment by tusharojha** [comment]
@jonasfj should I make a PR for this one?

**Comment by sigurdm** [comment]
Was fixed by https://github.com/dart-lang/pub/commit/6e03ec02ab143db1de2f637fa9e4f3c2d34e895e

**Comment by jonasfj** [comment]
Should we document this in https://dart.dev/tools/pub/cmd/pub-add
