### ISSUE TITLE
Outdated documentation on entrypoint.acquireDependencies

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/pub#2956]
The documentation for `Entrypoint.aquireDependencies` is outdated, when looking at the source code I was very confused about what `useLatest` means.

It seems like it was renamed in this commit: 
https://github.com/dart-lang/pub/commit/06bcff0981d05df871049c7fe11370892f3104fb#diff-fdb8ce649c4af89ef6afd8c67bdd9e51e661161792256adba203cbd241f64ad2

https://github.com/dart-lang/pub/blob/018c965030716038b61188d0c2171797ff16b31c/lib/src/entrypoint.dart#L207-L211

Also `upgradeAll` seems to be unused now. Not sure what that's about. 🤔

**Comment by IchordeDionysos** [comment]
`upgradeAll` actually was removed in 2015 😄 

https://github.com/dart-lang/pub/commit/7cf787c68e17f1e75a0931cba67310207c1471b2#diff-fdb8ce649c4af89ef6afd8c67bdd9e51e661161792256adba203cbd241f64ad2

**Comment by sigurdm** [comment]
This would be an easy community contribution

**Comment by AbhishekSatpathy4848** [comment]
Hey everyone!! Could I work on this issue?

**Comment by sigurdm** [comment]
@AbhishekSatpathy4848  Yes, feel free to open a PR with improved documentation
