### ISSUE TITLE
While Updating dependencies in pubspec.yaml it is running pub get in old path after changing environment var path

### ISSUE THREAD

**Issue by ritubhol** [dart-lang/pub#2957]
Updated to Flutter 2.0 and Dart 2.12.2
Also changed the environment path variables of bin & .pub_cache/bin

trying to update dependencies in pubspec.YAML but it is calling the old path of the environment variable which is showing current dart version is 2.10 

But if I check in my project dart --version it is 2.12.2

Could you suggest what am i missing ?

**Comment by sigurdm** [comment]
Is this still an issue?

**Comment by ritubhol** [comment]
No it’s resolved
