### ISSUE TITLE
Improve invalidation of precompiled executable snapshots

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#2962]
Currently (I think) we invalidate snapshots on every `pub get`, which is pessimistic. If a user adds a dependency on some package which is not a transitive dep on `test`, it would be nice if they don't need to wait again for the `Precompiling` step the next time they run tests.

We could potentially calculate the versions of the transitive deps of the specific package with the executable into a hash, and store a manifest with that hash. After a pub get we can recompute the hash and throw away the snapshot only if it has changed.

cc @mit-mit @grouma

**Comment by mit-mit** [comment]
Currently you don't even need to edit your pubspec and add a new dep. -- simply running `pub get` seems ti invalidate:

```console
$ dart pub get
Resolving dependencies...
Got dependencies!

$ dart test
Precompiling executable... (10.5s)
Precompiled test:test.
00:01 +1: All tests passed!

$ dart pub get
Resolving dependencies...
Got dependencies!

$ dart test
Precompiling executable... (10.4s)
Precompiled test:test.
00:01 +1: All tests passed!
```

**Comment by mit-mit** [comment]
cc @sigurdm @jonasfj

**Comment by mit-mit** [comment]
This seems to have been resolved (I'm using `dart` from todays Flutter master):

```
mit-macbookpro4:tmp mit$ dart create -t console-full c1
Creating c1 using template console-full...
...
mit-macbookpro4:tmp mit$ cd c1
mit-macbookpro4:c1 mit$ dart test
Precompiling executable... (8.9s)
Precompiled test:test.
00:01 +1: All tests passed!
mit-macbookpro4:c1 mit$ dart test
00:01 +1: All tests passed!
mit-macbookpro4:c1 mit$ dart test
00:01 +1: All tests passed!

```

Was this resolved as part of https://github.com/dart-lang/pub/pull/2968, @jakemac53  ?

**Comment by jakemac53** [comment]
In order to trigger the new behavior you need to run a pub get in between test runs - that is what triggers a recompile. It still does trigger a recompile but it will be much faster now. So this issue isn't directly solved but it is mitigated significantly enough that I would say we can close it personally.

**Comment by mit-mit** [comment]
Got it. That is still pretty fast:

```
$ dart test
Precompiling executable... (1.9s)
Precompiled test:test.
00:01 +1: All tests passed!

$ dart pub get
Resolving dependencies...
  analyzer 1.7.0 (1.7.1 available)
Got dependencies!

$ dart test
Precompiling executable... (1.2s)
Precompiled test:test.
00:01 +1: All tests passed!
```

Agree we can close for now.
