### ISSUE TITLE
Check that published contents does not include `.dart_tool/`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2967]
This is possible if you're checking `.dart_tool/` into git.. which you should never do!

**Comment by tusharojha** [comment]
Hi @jonasfj!
I interested in working on it. 

Should I add a check for this inside the publish command?

**Comment by jonasfj** [comment]
Check the files in the lib/src/validator folder... There is already some
here that do the same for dartdoc contents..

**Comment by sigurdm** [comment]
@jonasfj was this fixed by the associated PR?
