### ISSUE TITLE
Error running `pub global activate devtools

### ISSUE THREAD

**Issue by waleedhelalat** [dart-lang/pub#2974]
Error running `pub global activate devtools`:
HTTP error 403: Forbidden
[38;5;248mpackage:pub/src/http.dart 229:5              _ThrowingClient.send[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/http.dart 376:18             _ThrottleClient.send[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/source/hosted.dart 530:20    BoundHostedSource._download[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/source/hosted.dart 381:7     BoundHostedSource.downloadToSystemCache[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/global_packages.dart 224:37  GlobalPackages._installInCache.<fn>.<fn>[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/global_packages.dart 219:5   GlobalPackages._installInCache[39;49m
[38;5;244m===== asynchronous gap ===========================[39;49m
[38;5;248mpackage:pub/src/global_packages.dart 120:5   GlobalPackages.activateHosted[39;49m
This is an unexpected error. Please run

    dart pub --trace global activate devtools

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

Connecting to VM Service at ws://127.0.0.1:58881/D8w5kcG04Tw=/ws
D/EGL_emulation( 8515): eglMakeCurrent: 0x9fca2b00: ver 3 0 (tinfo 0x9058e4e0)
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 8515): glUtilsParamSize: unknow param 0x00008741

**Comment by sigurdm** [comment]
Are you using a mirror?

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by jonasfj** [comment]
Closing due to lack of information...


--------------

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).
