### ISSUE TITLE
Remove warning for "docs" being a plural name in directory name

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/pub#2976]
docs is used by github to publish to gh-pages. However when publishing to pub.dev this warning shows up.

```
* Rename the top-level "docs" directory to "doc".
  The Pub layout convention is to use singular directory names.
  Plural names won't be correctly identified by Pub and other tools.
```

Not a big deal though.

**Comment by jonasfj** [comment]
Things generated by `dartdoc` defaults to going into `doc/api/` (we also warn against publishing to pub.dev with this).

See also [the package layout convention](https://dart.dev/tools/pub/package-layout).

--------

I'm not sure we should change this, afaik github repositories can be reconfigured to publish from a different branch or a different folder `docs/` is just the default.

(personally, I would also have made `docs/` plural, but it feels like that ship sailed a long time ago).

**Comment by jonasfj** [comment]
Would it help if we referenced the package layout convention in the warning message?

**Comment by cedvdb** [comment]
There is a misunderstanding here, what I have in "docs" is not the dartdoc but just a running example website, however it might apply to dartdoc too.

**Comment by jonasfj** [comment]
Hmm, that's interesting.

My point was the Dart tooling generally assumes that documentation is located in `doc/`. And this is what the package layout convention formatlizes.

I don't know how many packages actually have a `doc/` folder, or what tools rely on this.
 * I know that `dartdoc` generates to `doc/api/` by default.
 * I've seen a few projects use `doc/<topic>.md` to document some topic that they would then reference in `dartdoc_options.yaml`.

So changing the _package layout convention_ might be a bit invasive. And continuing to guide uses to put their documentation in `doc/` might be a good option.

--------

What is your repository? What is inside the `docs/` folder..? Is it something we want to include when publishing a package?

Another option is that we tweak our documentation and warnings to suggest that users building jekyll sites on github pages using the `docs/` folder consider adding `./docs/` to their `.pubignore` (disclaimer: the `.pubignore` feature haven't shipped yet).

**Comment by cedvdb** [comment]
what's inside the doc folder is my built example app, so user can see a live demo

https://github.com/cedvdb/phone_form_field

**Comment by cedvdb** [comment]
maybe just deploying from a gh-page branch would do

**Comment by cedvdb** [comment]
im c

**Comment by jonasfj** [comment]
> what's inside the doc folder is my built example app, so user can see a live demo

Ah, that's pretty cool.. Yeah, you probably probably don't want to include such an app when publishing to `pub.dev`.

Normally, I would suggest `.gitignore` but that does work if you're publishing on github pages. In the future `.pubignore` is probably the fix for this situation.
