### ISSUE TITLE
Ignore .gitignore and .github/ from publish by default

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub#2979]
Potentially related to https://github.com/dart-lang/pub/issues/2946

We're publishing our CI workflows and issue templates with packages and it isn't necessary. I don't think there are many downsides other than a bit of extra disk and network usage - but the cumulative effects from all package versions might be enough to make this worthwhile.

**Comment by sigurdm** [comment]
Stumbled into this old issue.

By default we are not publishing files starting with `'.'`. (https://github.com/dart-lang/pub/blob/1bfb295dabf3951745468c89019d4712d2694f3e/lib/src/package.dart#L196)

 Can you (still) reproduce this?

**Comment by natebosch** [comment]
I don't see `.github/` directories in recently published packages.
