### ISSUE TITLE
Failure message for flutter dependency is confusing

### ISSUE THREAD

**Issue by eseidel** [dart-lang/pub#2992]
# Environment

- `pub version` or `flutter pub version`:
Dart SDK version: 2.14.0-74.0.dev (dev) (Mon May 3 05:56:14 2021 -0700) on "windows_x64"
- OS version:
```
[√] Flutter (Channel master, 2.3.0-2.0.pre.90, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.90 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f82dedd5b9 (27 hours ago), 2021-05-10 15:22:50 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
```
- Are you using the Chinese community mirror or a corporate firewall?
Nope.

# Problem

Attempting to fetch a flutter-depending package using `dart pub` prints a confusing error message:

```
[flutter_eng_cycle_times] dart pub get
Resolving dependencies...
Because every version of dio_http_cache from git depends on flutter any from sdk which is forbidden, dio_http_cache from git is forbidden.
So, because flutter_eng_cycle_times depends on dio_http_cache from git, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
exit code 69
```

I originally thought it was relating to my "git" dependency or the fact that it was "flutter any" rather than a specific flutter version or something.

What the real error is is the last line.   It's telling me that because this package depend on Flutter I need to use a different flavor of pub to fetch it. :(

**Comment by sigurdm** [comment]
This might be solved by https://github.com/dart-lang/pub/pull/3196

We are still a bit unsure if that is the right fix - the logic of the solver is not clear to us here.

**Comment by sigurdm** [comment]
Closing this for now, assuming it is fixed.
