### ISSUE TITLE
`pub publish --dry-run` doesn't catch some errors

### ISSUE THREAD

**Issue by cyanglaz** [dart-lang/pub#2996]
When running `pub publish --dry-run`, some errors are not showing up and the process is considered successful. The error that I found not showing up is: 
```
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
```

`pub publish` will catch the error and stop the publishing process.

the flutter/plugins repo uses `pub publish --dry-run` to determine if the package is publishable, so this is causing false positives.

**Steps to reproduce**
1. Create a plugin or use any existing plugin.  (We might publish this plugin in the process, so it is better to use a dummy plugin, or use a dummy pub server for this)
2. Remove the ios/ folder, set the min flutter dependency in pubspec.yaml to something lower than 1.20.0, e.g:
`flutter: ">=1.12.13+hotfix.5"`
3 Run `pub publish`, press Y when asked, see the error above.
4. Run `pub publish --dry-run`, see that it is successful.

**Expected behavior**
The step 4 above should result an error.

**Comment by sigurdm** [comment]
The pub client cannot decide what the pub server accepts.

Some validation steps will always be server-side - these cannot be part of --dry-run.

The output of --dry-run says "The server may enforce additional checks"

For this specific check we could make a client-side validation - but I think we would actually prefer the linter to handle more of these checks (such that you would not even need --dry-run to get these).
