### ISSUE TITLE
Hi i have issue in http ,http parsers

### ISSUE THREAD

**Issue by kalai-selva** [dart-lang/pub#3004]
flutter pub get
Because http 0.12.2 depends on http_parser >=0.0.1 <4.0.0 and no versions of http match >0.12.2 <0.13.0, http ^0.12.2 requires http_parser >=0.0.1 <4.0.0.
So, because helloworld depends on both http ^0.12.2 and http_parser ^4.0.0, version solving failed.

--------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by natebosch** [comment]
The error is telling you that those two package constraints you have are incompatible. You can probably correct this by changing your `http` constraint to `^0.13.0`. If that version is incompatible with other dependencies that you can't upgrade you can choose a lower version of `http_parser`.
