### ISSUE TITLE
Running "pub deps" unexpectedly modifies .dart_tool/package_config.json (when there are path dependencies)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#3016]
This came up at https://github.com/dart-lang/pub/pull/2896#issuecomment-847721517.

In VS Code, I'm using `pub deps` to render the dependencies tree. If the `package_config.json` file is modified, that triggers a refresh of the tree. This results in calling `pub deps` again. For some projects, I found that the act of calling `pub deps` modified the file, which triggered calling it again (and this went on forever).

Attaching a debugger to pub showed it occurring here, because `hasPathDependencies=true`:

https://github.com/dart-lang/pub/blob/c33f264f385f35616eb4086cd766bae76558e930/lib/src/entrypoint.dart#L512-L520

@jonasfj

**Comment by jonasfj** [comment]
Hmm, yeah, maybe it's overkill to touch it just because it has a path dependency..

**Comment by jonasfj** [comment]
Probably there is no need to do any timestamping if there is a path dependency...

**Comment by sigurdm** [comment]
@jonasfj thinks we can touch it only in the first case (`packageConfigModified.isBefore(lockFileModified)`) not the second (`hasPathDependencies`)
