### ISSUE TITLE
Display number of package installs

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/pub#3023]
# Feature request

Display number of installs of a package on pub.dev

npmjs.com:
![image](https://user-images.githubusercontent.com/6261302/120465237-6c116980-c3a6-11eb-9e60-a290b454b250.png)
Having something similar would help package authors have an idea about the number of actual users of a package and prioritize their work accordingly

**Comment by jonasfj** [comment]
duplicate: https://github.com/dart-lang/pub-dev/issues/2714
