### ISSUE TITLE
dart pub --trace get --no-precompile

### ISSUE THREAD

**Issue by phenom80** [dart-lang/pub#3032]
![Untitled](https://user-images.githubusercontent.com/57831614/121863114-c13b6c80-cd10-11eb-949e-6c9b68785d20.png)
What should I do to fix the issue ???

HTTP error 403: Forbidden
package:pub/src/http.dart 229:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 376:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 530:20  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by jonasfj** [comment]
What is your `pubspec.yaml`?

What platform are you on?

Are you behind firewall or in China?

**Comment by jonasfj** [comment]
Closed due to lack of information.
