### ISSUE TITLE
Error when I run flutter doctor

### ISSUE THREAD

**Issue by deiviszi** [dart-lang/pub#3037]
When making a new installation of flutter I got the error below as soon as I run the command flutter doctor.
Stable channel, installed on windows.

> C:\Users\usern>flutter doctor
> Bad state: A https: URI should have a non-empty host name: https:%5C%5Cpub.flutter-io.cn/api/packages/archive
> package:pub/src/source/hosted.dart 570:7 BoundHostedSource._throwFriendlyError
> package:pub/src/source/hosted.dart 211:7 BoundHostedSource._fetchVersions
> ===== asynchronous gap =============================
> package:pub/src/rate_limited_scheduler.dart 87:11 RateLimitedScheduler._processNextTask.runJob
> ===== asynchronous gap =============================
> package:pub/src/rate_limited_scheduler.dart 96:5 RateLimitedScheduler._processNextTask
> ===== asynchronous gap =============================
> package:pool/pool.dart 127:14 Pool.withResource
> This is an unexpected error. Please run
> 
>     dart pub --trace get --no-precompile
> 
> and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
> Running "flutter pub get" in flutter_tools...
> pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by Arvinth-Krishna** [comment]
C:\Users\krish>flutter doctor
Got socket error trying to find package test at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in flutter_tools...                          -

please help!! why it's coming like this?

**Comment by sigurdm** [comment]
Did you set a custom host?

What is the output of `echo $PUB_HOSTED_URL` / `echo %PUB_HOSTED_URL%`?

**Comment by sigurdm** [comment]
I think this is just a bad configuration of PUB_HOSTED_URL - you can read more about how to use the Chinese mirror here: https://flutter.dev/community/china

Please reopen if I am misunderstanding something.
