### ISSUE TITLE
Support `flutter pub global activate <package>` to allow activation of Flutter executables.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub#3039]
When I executed `flutter pub global activate sampler` on a package that has a flutter app as the `executable:` in the pubspec, it executes `dart pub global activate` in a Flutter environment, but fails to compile because it is not compiled in the Flutter environment, but in the pure Dart environment, and so it fails to find `dart:ui`. Similarly, the command `flutter pub global run sampler:sampler` fails because it can't find `dart:ui`.

This is a feature request to add the ability to `flutter pub global activate` a package with a Flutter executable. This may require coordination with the Flutter tools team, of course.

This would be a very useful and convenient way of installing a Flutter-based open-source tool or app on a desktop system.

If this feature isn't implemented, then at the very least, we should prevent users from running `flutter pub global activate` and notify them that it is not supported.

**Comment by jakemac53** [comment]
> If this feature isn't implemented, then at the very least, we should prevent users from running `flutter pub global activate` and notify them that it is not supported.

This should still generally work afaik, it is only if there are `dart:ui` imports transitively in the executable where it doesn't work.

We also had a related issue filed on the build repo where a `dart:ui` import snuck into the transitive imports of a builder, making the build script not function (https://github.com/dart-lang/build/issues/3138). I do wonder if some more general improvements to the output from the compiler here would also be worth looking at, as the current output is quite noisy and difficult to understand.

**Comment by gspencergoog** [comment]
Won't any Flutter application transitively include `dart:ui`? For example, I know that `package:flutter/painting.dart` imports dart:ui, and that file is imported by anything that needs to paint pixels.

**Comment by jakemac53** [comment]
> Won't any Flutter application transitively import `dart:ui`? For example, I know that `package:flutter/painting.dart` imports dart:ui, and that file is imported by anything that needs to paint pixels.

`[flutter] pub global activate` is not for flutter apps though - its for command line (vm) apps. These should not import `dart:ui` even transitively, because that library doesn't exist on the VM.

It sounds to me like the issue you are running into is that either:

- some people are putting flutter apps under `bin`, making pub think they are vm apps.
- some command line tools written for flutter apps are picking up transitive imports to `dart:ui` on accident (or without knowing they shouldn't).

**Comment by jakemac53** [comment]
Or maybe, after re-reading the issue, what you want is to be able to ship flutter apps as globally activated executables?

Maybe we should add a `flutter_executables` section for this? Those would afaik only be available to users who are using the flutter sdk though, which would be a bit unfortunate.

**Comment by gspencergoog** [comment]
Yes, that is what I was asking for.  I have a tool that developers will want to use for editing code samples in the Flutter repo. It's not hosted in the Flutter repo itself, and I'd like to keep it separate. It's a Flutter app, not a Dart command line tool, and I was hoping to just be able to have the instructions for using it be "run `flutter pub global activate sampler`" and then they can just run it as they would any other global activated executable.

Perhaps this is just a too-small edge case to be worth the effort/support, though: you're right that this is only useful for Flutter developers and not for the general public to install apps with.

In thinking about this some more, I'm worried that if this did exist, perhaps people would be confused that they can't distribute Flutter apps this way. It sure would be convenient for me, though. :-)

**Comment by jakemac53** [comment]
There would certainly be some things to work out here... it might be best to just have the flutter tool support running flutter apps from dependencies? Actually, does that work today? You could try `flutter run package:sampler/main.dart` to see. You wouldn't be able to access the executables from `bin` but a mechanism for doing that could be exposed.

**Comment by jakemac53** [comment]
cc @jonahwilliams that first issue doesn't seem insurmountable to resolve on the surface, flutter tool could change the working dir to that of the package being ran or something, when given a `package:` uri? Does this sound like a feasible/worthwhile feature to you?

**Comment by jakemac53** [comment]
> I was thinking I could put a stub application in the Flutter repo that just imports the `sampler` package with a main.dart that looks like:

You could actually just release a vm executable in the `sampler` package, which changes the root dir to that of the package (in the pub cache), and then runs `flutter run` from there. Maybe just crazy enough to work?

**Comment by gspencergoog** [comment]
Oh, man, that's next level.  OK, I'll give that a try and see how well it works.

**Comment by jonahwilliams** [comment]
I really like the idea of `flutter run package:sampler/main.dart`, that could be made to work pretty easily. I'm not sure about pub global activate though:

Thinking of all the cases we'd need to make clear, It could fail to run because:

1. You never uploaded windows platform files (how do we do platform discovery?)
2. The user's Flutter SDK has not enabled desktop support ( how do we handle feature discovery?)
3. The user has not completed desktop setup, and is missing requirements like Visual Studio.

Given all that, I think distributing a flutter app via pub _given_ that the user is completely setup locally to build it is probably easy. However shipping a bundle or prebuilt is going to be much simpler than installing Visual Studio and then hitting pub global run.

**Comment by sigurdm** [comment]
Should we transfer this issue to flutter?

Perhaps flutter could somehow make use of the logic in `getExecutableForCommand` like `dart run` currently does for package resolution. That would allow things like:

* `flutter run foo:tool` (runs bin/tool.dart in package:foo)
* `flutter run foo` (runs bin/foo.dart in package:foo)

**Comment by sigurdm** [comment]
Can you already do this by making a dart-cli script that runs "flutter run" and run that script with "pub global run"?

**Comment by sigurdm** [comment]
> It's very slow to start because it's compiling the app to run it instead of using pre-built executables, but it does eventually start. Overall, it feels very hacky, and I don't think I'd do it again.

Thanks for the feedback - I agree this sounds bothersome. Not sure exactly where we would fit this feature in (does it belong with flutter_tool or pub?)...

**Comment by gspencergoog** [comment]
I think it falls below the bar of what we should implement.  It would be nice to have, but I doubt the payoff is worth the investment. I'd much rather devote the energy to flutter_tool creating an installable package from a Flutter app, for instance.
