### ISSUE TITLE
Add a `doc` command

### ISSUE THREAD

**Issue by chrisnorman7** [dart-lang/pub#3052]
Hi,
I don't know if I'm missing something or not, but I feel there should be a quicker way to get to the API docs for a package than typing the absolute URL into my web browser.

The URL is known on the [pub.dev](https://pub.dev/) site, so it would be really handy if I could type `pub doc path` for example, and the link would be opened in my web browser.

Is this already implemented somewhere that I just haven't' found?

Thanks in advance.

**Comment by jonasfj** [comment]
I think this is a feature that better implemented in an IDE plugin, perhaps?

**Comment by jonasfj** [comment]
I think this outside the scope of the pub client... maybe one day, or maybe it's better as an IDE plugin.
