### ISSUE TITLE
Bad state: Could not find 7zip.

### ISSUE THREAD

**Issue by Kashif-Ali786** [dart-lang/pub#3068]
When I run flutter pub get command, I am getting this

Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip
package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in ezgigi-customer-app-master...
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment]
Hmm this is a bit mysterious - what is your `flutter doctor` output?
I expect you are on windows - is that true?
Could you run: `dir <path\to\flutter>\bin\cache\dart-sdk\lib\_internal\pub\asset\` it should contain a 7zip directory.

**Comment by phiwu1** [comment]
im also getting this error

**Comment by sigurdm** [comment]
@phiwu1 Can you provide the information I requested?

What is your flutter doctor output?
I expect you are on windows - is that true - what version?
Could you run: `dir <path\to\flutter>\bin\cache\dart-sdk\lib\_internal\pub\asset\` it should contain a 7zip directory.

**Comment by phiwu1** [comment]
Every thing is good on flutter doctor except it says android studio not
installed even though I'm using android studio. And yes the 7zip directory
is there.

**Comment by phiwu1** [comment]
Windows 10 21H1

**Comment by sigurdm** [comment]
Not sure how it is possible to get into this state - but we are seeing multiple instances of this.

What version of flutter/dart are you using?

Did you just upgrade?

**Comment by sigurdm** [comment]
It seems a workaround is to refetch the dart-sdk by removing the cache folder in `<path-to-flutter>\flutter\bin` then run dart.bat

**Comment by jonasfj** [comment]
Is people still running into this issue? I'm guessing it's most likely to happen when jumping between different versions of flutter, probably on master when we were in the process of moving away from `7zip`. It's still surprising that this would happen at all.

Please specify dart / flutter version.

----------------------

side note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by jonasfj** [comment]
No response,

**Comment by olamiji-8** [comment]
Okay...
I just experienced the same issue just now and I downloaded another flutter package and removed the former one and it worked.
