### ISSUE TITLE
Unable to publish the private package using fluter 2

### ISSUE THREAD

**Issue by tataji** [dart-lang/pub#3070]
Invalid empty scheme (at character 1)
://dartpub.privateurl.com/api/packages/versions/newUpload
^
dart:core                                Uri.parse
package:pub/src/command/lish.dart 81:33  LishCommand._publish.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 71:7   LishCommand._publish
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 160:7  LishCommand.runProtected
This is an unexpected error. Please run

**Comment by sigurdm** [comment]
Could you post your pubspec.yaml?

What does `flutter --version` say?
What platform are you on?

**Comment by tataji** [comment]
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (2 months ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Comment by tataji** [comment]
name: package name
version: 2.0
author: "author name"
homepage: homepageurl
description: client
environment:
  sdk:  ">=2.12.0 <3.0.0"
dependencies:
  http: '^0.13.3'
  intl: '^0.17.0'
  meta: '^1.7.0'
publish_to: https://dartpub.privateurl.com

**Comment by sigurdm** [comment]
I think you need quotes around the url:
```
name: package name
version: 2.0
author: "author name"
homepage: homepageurl
description: client
environment:
sdk: ">=2.12.0 <3.0.0"
dependencies:
http: '^0.13.3'
intl: '^0.17.0'
meta: '^1.7.0'
publish_to: 'https://dartpub.privateurl.com'
```

**Comment by tataji** [comment]
tried with quotes around the url, not working

**Comment by jonasfj** [comment]
Please paste the `pubspec.yaml` with [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) and proper indentation.

**Comment by sigurdm** [comment]
Closing as stale
