### ISSUE TITLE
pubspec.yaml contain chinese made flutter pub get fail 

### ISSUE THREAD

**Issue by xiedeacc** [dart-lang/pub#3071]
# Environment

- `Pub 2.13.3`
- OS version: win10 x64
- Are you using the Chinese community mirror or a corporate firewall? yes

I have try https://github.com/dart-lang/pub/issues/2028#issuecomment-455189430, but it cannot resolve my problem

# Problem

pubspec.yaml contain chinese made flutter pub get error, pubspec.yaml contain chinese:

Error on line 2, column 81: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
2 │ description: 鍩轰簬涓彴鎾斁鍣═humbPlayer鐨凢lutter鐗堟湰鎾斁鍣紝鎻愪緵瀹屽鎺ュ彛鍔熻兘鍜屼赴瀵屾彃浠躲€?version: 1.2.1

**Comment by sigurdm** [comment]
I don't seem able to reproduce.
Can you post the entire pubspec.yaml giving the error? Or a minimal example that shows the error?
Is the pubspec.yaml encoded with utf8?

**Comment by sigurdm** [comment]
Ah - I see now what is wrong, there is a colon in the description. This has nothing to do with chinese.

Try to change the line to:
```
description: '鍩轰簬涓彴鎾斁鍣═humbPlayer鐨凢lutter鐗堟湰鎾斁鍣紝鎻愪緵瀹屽鎺ュ彛鍔熻兘鍜屼赴瀵屾彃浠躲€?version: 1.2.1'
```

**Comment by xiedeacc** [comment]
ok, thanks, anyway, dart-sdk not support chinese very well

**Comment by xiedeacc** [comment]
fixed

**Comment by sigurdm** [comment]
> dart-sdk not support chinese very well

Supporting all languages is important to us.

Do you have examples of places where Chinese is not well supported?

Please file them at https://github.com/dart-lang/sdk/issues/new
