### ISSUE TITLE
Error while running "pub global activate devtools"

### ISSUE THREAD

**Issue by Abhishek-Garg-Ai** [dart-lang/pub#3072]
I am getting below error while launching new flutter project in my android. I try with flutter doctor, it showing no issue. I also tried to change fultter sdk version but same error occurs. This happened from last two days, before it everything is fine.
System Windows 10

Error running `pub global activate devtools`:
The getter 'source' was called on null.
Receiver: null
Tried calling: source
dart:core                                                                             Object.noSuchMethod
package:pub/src/global_packages.dart 287:21                                           GlobalPackages._describeActive
package:pub/src/global_packages.dart 179:7                                            GlobalPackages._installInCache
package:pub/src/global_packages.dart 120:11                                           GlobalPackages.activateHosted
package:pub/src/command/global_activate.dart 118:24                                   GlobalActivateCommand.runProtected
dart:async                                                                            new Future.sync
package:pub/src/utils.dart 113:12                                                     captureErrors.wrappedCallback
dart:async                                                                            runZonedGuarded
package:pub/src/utils.dart 130:5                                                      captureErrors
package:pub/src/command.dart 164:13                                                   PubCommand.run
package:args/command_runner.dart 196:27                                               CommandRunner.runCommand
package:pub/src/command_runner.dart 150:26                                            PubCommandRunner.runCommand
package:pub/src/command_runner.dart 138:18                                            PubCommandRunner.run
C:\b\s\w\ir\cache\builder\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 9:48  main
This is an unexpected error. Please run

    dart pub --trace global activate devtools

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment]
This bug we saw [before](https://github.com/dart-lang/pub/issues/2667). But we didn't get the chance to debug it.

Could you please show the output of:
```
$ cat ~/.pub_cache/global_packages/devtools/pubspec.lock
```
I have a feeling that some invariant is broken there when moving between pub versions.

To work around the problem you can 
```
$ pub global deactivate devtools
$ pub global activate devtools
```
And if that fails, try removing your .pub_cache:
```
$ mv ~/.pub_cache ~/.pub_cache_backup
```
and then trying again.

Please report back with your findings - we have to get this fixed.

**Comment by sigurdm** [comment]
Closing for lack of details.

Please open a new issue if this can still be reproduced on a recent sdk.
