### ISSUE TITLE
.gitignore parsing on pub publish doesn't handle all negations

### ISSUE THREAD

**Issue by kuhnroyal** [dart-lang/pub#3079]
# Environment

- `pub version` or `flutter pub version`: Pub 2.14.0-377.4.beta
- OS version: MacOS 11.5.2

# Problem

Seems like the ignore parsing add together with `.pubignore` can't handle all cases correctly.
All my build pipeline checks using `pub publish --dry-run` now fail.

`.gitignore` contains:
```
.idea
!.idea/libraries/Dart_SDK.xml
```

`pub publish --dry-run` fails with:
```
Package validation found the following potential issue:
* 1 checked in file is ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  
  Files that are checked in while gitignored:
  
  .idea/libraries/Dart_SDK.xml
  
  

Package has 1 warning.
pub finished with exit code 65
```

## Expected behavior

It should match the negated pattern correctly.

**Comment by kuhnroyal** [comment]
@sigurdm Do you have an idea why this could be happening?

**Comment by sigurdm** [comment]
Could it be that you checked the `.idea/libraries/Dart_SDK.xml` file in to git?

**Comment by sigurdm** [comment]
I am not really sure what you are trying to do. Hopefully you don't want to be publishing nor checking in `.idea/libraries/Dart_SDK.xml`.

Maybe you are being confused by this rule of gitignore patterns (from https://git-scm.com/docs/gitignore):


> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. **It is not possible to re-include a file if a parent directory of that file is excluded**. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

**Comment by kuhnroyal** [comment]
I want it to be checked in but not published. I added the file to `.pubignore` but the warning persists.

Since you are wondering, it is checked in because it contains relative links to the Flutter SDK managed by FVM (https://github.com/leoafarias/fvm/)





> **It is not possible to re-include a file if a parent directory of that file is excluded**.
This is probably my problem, thanks!

Then I would still expect the warning to disappear if I add the file to `.pubignore`.

**Comment by sigurdm** [comment]
> Then I would still expect the warning to disappear if I add the file to .pubignore.

.pubignore follows the same rules as .gitignore. It will not descend into an ignored folder.

What you can do is something along the lines of:

```
.idea/*. #. Ignore everything inside .idea (not the folder
!.idea/libraries/Dart_SDK.xml # Except this file.
```

**Comment by kuhnroyal** [comment]
Yea I went with this:
```
.idea/**/*.xml
.idea/sonarlint
!.idea/libraries/Dart_SDK.xml
```

I will close this. Thanks for your help and pointers!
