### ISSUE TITLE
Detect potential secrets prior to package publication

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3082]
Using a few common patterns we could scan files about to be published for possible API keys, and stop users from accidentally publishing these.

The fact that people accidentally commit API keys to public github repositories have been well documented in the paper: [How bad can it git?](https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_04B-3_Meli_paper.pdf). This paper also includes patterns for finding common API keys.

While we can't hope to find and stop all possible API keys for being accidentally leaked, we can hopefully stop most leaks from happening. Furthermore, authors of [How bad can it git?](https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_04B-3_Meli_paper.pdf) have demonstrated that secrets are often stored alongside other secrets, hence, detecting one secret may also help the developer notice other potential leaks.

Feature is being implemented in https://github.com/dart-lang/pub/pull/3049

------

Related work includes:
 * [awslabs/git-secrets](https://github.com/awslabs/git-secrets)
 * [gitleaks](https://github.com/zricethezav/gitleaks)
 * [shhgit](https://github.com/eth0izzle/shhgit)
 * [pownjs/leaks](https://github.com/pownjs/leaks)
 * [truffleHog](https://github.com/trufflesecurity/truffleHog)

**Comment by sigurdm** [comment]
I guess this was closed when landing: https://github.com/dart-lang/pub/pull/3049
