### ISSUE TITLE
pub publish is ignoring parent .gitignore

### ISSUE THREAD

**Issue by ryanheise** [dart-lang/pub#3102]
# Environment

- `pub version` or `flutter pub version`: 2.14.0
- OS version: Linux 5.12.14-arch1-1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

This happens when publishing this directory:

https://github.com/ryanheise/audio_service/tree/56487d8e36f8db8bfab5271094955772bb362d7f/audio_service

If you have run `flutter run` in the `example` directory first, which generates a lot of temporary files (all covered in `../.gitignore`), publishing fails. But if you copy the `.gitignore` file from the parent into the current directory it succeeds.

```
$ flutter packages pub publish --dry-run
```

## Expected behavior

If the pub tool respects `.gitignore` by default, it should look for `.gitignore` in the same places that the git tool does. In federated plugins for Flutter, it is common practice to store multiple related packages in the same git repository, and share the `.gitignore` file at the root of the git repository. In fact the 1st party Flutter plugins by Google, the same approach is used with a single shared `.gitignore` at the root of the git repository.

## Actual behavior

The pub tool only finds `.gitignore` if it is in the current directory which is not how `.gitignore` is supposed to work.

## --trace output

```
$ cd example; flutter run; cd ..
$ flutter packages pub publish --dry-run
...
* Your package is 373.5 MB. Hosted packages must be smaller than 100 MB. Consider adding a .gitignore to avoid including temporary files.
$ git status -s
(empty list)
```

But it succeeds after doing either a `flutter clean` in both the plugin directory and its `example` subdirectory, or by copying the parent `.gitignore` file into the current directory.

**Comment by sigurdm** [comment]
Hmm - yes this is not ideal - we should take any .gitignores into account until we meet a `.git` directory. 

...But there are even more git places gitignore rules might come from...
:(

**Comment by jonasfj** [comment]
I think we should take the opinion that "global git-ignore configuration" is ignored. Looking up parent directories and using `.gitignore` from those folders, if we find a `.git/` folder in some parent folder is fine.

We could probably do that.
