### ISSUE TITLE
dart.dev/go/pubignore is 404

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/pub#3105]
# Environment

- `pub version` or `flutter pub version`: Pub 2.15.0-15.0.dev
- OS version: Windows 10
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

`flutter pub publish` prints a warning if previous version of package contain now `.gitignored` files

```
Package validation found the following potential issue:
* 1 checked in file is ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.

  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore

  Files that are checked in while gitignored:

  .pubignore
```

## Expected behavior

dart.dev/go/pubignore is a valid link

## Actual behavior

dart.dev/go/pubignore is 404

**Comment by sigurdm** [comment]
Yeah - we totally forgot to add that link!

Created PR.
