### ISSUE TITLE
I am trying to add a package to my flutter project but I keep getting this error:

### ISSUE THREAD

**Issue by hloni95** [dart-lang/pub#3106]
I am trying to add a package to my flutter project but I keep getting this error: 
pub.flutter-io.cn%20 is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 18)
pub.flutter-io.cn%20
                 ^
package:pub/src/source/hosted.dart 439:7            BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 190:7            BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
dart:async                                          _CustomZone.runUnary
package:pub/src/rate_limited_scheduler.dart 83:30   RateLimitedScheduler._processNextTask.runJob
package:pub/src/rate_limited_scheduler.dart 86:30   RateLimitedScheduler._processNextTask
package:pool/pool.dart 127:28                       Pool.withResource
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 130:37  RateLimitedScheduler.schedule.<fn>
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in name_generator_app...
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment]
It looks like there is a space (%20) at the end of your PUB_HOSTED_URL variable.

**Comment by hloni95** [comment]
Thank you

**Comment by sigurdm** [comment]
@jonasfj should we `trim()` the  PUB_HOSTED_URL variable before using it? I think we have seen this come up before.

**Comment by jonasfj** [comment]
Wouldn't trimming violate the convention established in:
https://github.com/dart-lang/pub/blob/master/lib/src/source/hosted.dart#L31

In this case the input isn't a valid URL.. maybe we could improve the CLI output to say that the env var isn't a valid URL.

I'm guessing we already do something like that, but that it's not displayed because this goes through `flutter_tool` which eats our output.

**Comment by sigurdm** [comment]
Ok for now we won't do more.
