### ISSUE TITLE
Increase number of retries when CI=true

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3107]
When in a CI environment, detected using environment variable `CI=true` or `CI=1`, then we should:
 * Increase the number of retries when doing HTTP requests, and,
 * Maybe increase the delay between retries when doing HTTP requests.

CI environments are less sensitive to delays, and are a lot more sensitive to flakiness.

Maybe, we just increase the number of retries from 7 to 14?

https://github.com/dart-lang/pub/blob/d95c5713dda518ed53ada70e00789e6aadbfbe48/lib/src/http.dart#L247

**Comment by sigurdm** [comment]
Should we just retry indefinitely on CI - they will have their own timeout?

On the other hand that might give harder to understand error-messages.

**Comment by sigurdm** [comment]
@jonasfj do we still want this?
