### ISSUE TITLE
Update code to null-safety

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#3114]
Currently we are opting out in all source files, and therefore running mixed mode.

**Comment by jonasfj** [comment]
**Without ignoring `import_of_legacy_library_into_null_safe`**!

This can be done one or two files at the time. So long as the files migrated do not import code that have not been migrated.
Doing so would violate the `import_of_legacy_library_into_null_safe` lint, which causes problems further down the release pipeline (and is unsound in general).

Example a file like [ignore.dart](https://github.com/dart-lang/pub/blob/cafadd17ba285dad9ebe6d34c617bc0d70d096b3/lib/src/ignore.dart#L5) can be migrated independently.

Files like `io.dart` and `utils.dart` might have to migrated together. I'm hoping it's possible to find a few sets of files that can be migrated independently. Eventually, we'll have to migrate all files, but maybe we can start with a few at the time.

**Comment by jonasfj** [comment]
@szakarias finished this.
