### ISSUE TITLE
Token masking missing in `dart pub token add`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3119]
```
dart pub token add https://other-pub.com
Enter secret token: hello world
Requests to https://other-pub.com will now be authenticated using the secret token.
```

<details>
<summary>Expected result</summary>

```
dart pub token add https://other-pub.com
Enter secret token:
Requests to https://other-pub.com will now be authenticated using the secret token.
```
ie. no output at all, or

```
dart pub token add https://other-pub.com
Enter secret token: ***********
Requests to https://other-pub.com will now be authenticated using the secret token.
```
</details>

This might be complicated, require terminal and platform detection and possibly other hacks, see:
https://stackoverflow.com/questions/6856635/hide-password-input-on-terminal

/cc @themisir

**Comment by themisir** [comment]
I think this does contains solution we need: https://stackoverflow.com/questions/14591347/how-to-disable-stdin-echo-in-a-dart-console-application-for-password-input
