### ISSUE TITLE
flutter pub get error :   pub get failed (65; Because flutter_module depends on json_serializable any which doesn't exist (Got badly formatted response trying to find package json_serializable at https://pub.flutter-io.cn%0D), version solving failed.)

### ISSUE THREAD

**Issue by ytandhz** [dart-lang/pub#3124]

**Comment by sigurdm** [comment]
It seems there is a newline `%0D` at the end of your PUB_HOSTED_URL.

**Comment by ytandhz** [comment]
> It seems there is a newline `%0D` at the end of your PUB_HOSTED_URL.

Ok, thanks for your reply, But l don't know why there is a extra one. the path configuration is in accordance with the official document.

**Comment by sigurdm** [comment]
How did you set your PUB_HOSTED_URL? Are you on Windows?

Can you try:
```
> echo .${PUB_HOSTED_URL}.
```
Or on windows:
```
> echo .%PUB_HOSTED_URL%.
```

**Comment by ytandhz** [comment]
> How did you set your PUB_HOSTED_URL? Are you on Windows?
> 
> Can you try:
> 
> ```
> > echo .${PUB_HOSTED_URL}.
> ```
> 
> Or on windows:
> 
> ```
> > echo .%PUB_HOSTED_URL%.
> ```

I'm operating on Apple M1 and add the following contents to the $HOME/.zshrc file 
export PUB_HOSTED_URL=https://pub.flutter-io.cn

In addition, flutter doctor was executed and the result was normal

**Comment by sigurdm** [comment]
Not sure what goes wrong here. Perhaps try 
```
export PUB_HOSTED_URL="https://pub.flutter-io.cn"
```
To make sure nothing else sneaks in...

Please try running:

```
> echo .${PUB_HOSTED_URL}.
```
That should reveal if there is anything extra in your environment variable

**Comment by sigurdm** [comment]
Closing as stale
