### ISSUE TITLE
tryed to publish my first project but... 

### ISSUE THREAD

**Issue by nohkumado** [dart-lang/pub#3153]
the --dry-run went ok, but when trying the real thing i get 
```
Publishing nohfibu 0.0.1-alpha to http://pub.dev:
|-- CHANGELOG.md
|-- CODE_OF_CONDUCT.md
|-- CONTRIBUTING.md
|-- LICENSE
|-- LICENSE.md
|-- README.md
|-- assets
|   '-- wbsamples
|       |-- compta2018.csv
|       |-- compta2018.jrl
|       |-- compta2018.kpl
|       | (11 more...)
|       |-- sample.kpl
|       |-- sample.lst
|       '-- sample_org.lst
|-- bin
|   |-- fibu.dart
|   '-- wbconvert.dart
|-- dart_fibu.iml
|-- doc
|   '-- api
|       |-- __404error.html
|       |-- book
|       |   |-- Book
|       |   |   |-- Book.html
|       |   |   |-- clear.html
|       |   |   |-- execute.html
|       |   |   |-- jrl.html
|       |   |   |-- kpl.html
|       |   |   '-- toString.html
|       |   |-- Book-class.html
|       |   '-- book-library.html
|       |-- categories.json
|       | (5 more...)
|       |-- noh_fibu
|       |   |-- NohFibu
|       |   |   |-- Fibu.html
|       |   |   |-- NohFibu.html
|       |   |   |-- jrl.html
|       |   |   '-- kpl.html
|       |   |-- NohFibu-class.html
|       |   '-- noh_fibu-library.html
|       |-- settings
|       |   |-- Settings
|       |   |   |-- Settings.html
|       |   |   |-- data.html
|       |   |   |-- init.html
|       |   |   |-- operator_get.html
|       |   |   |-- operator_put.html
|       |   |   |-- parser.html
|       |   |   |-- rest.html
|       |   |   '-- usage.html
|       |   |-- Settings-class.html
|       |   '-- settings-library.html
|       '-- static-assets
|           |-- favicon.png
|           |-- github.css
|           |-- highlight.pack.js
|           |-- play_button.svg
|           |-- readme.md
|           |-- script.js
|           '-- styles.css
|-- lib
|   |-- book.dart
|   |-- csv_handler.dart
|   |-- journal.dart
|   |-- kto_plan.dart
|   '-- settings.dart
|-- pubspec.yaml
|-- tags
'-- test
    |-- book.dart
    |-- kpl_test.dart
    '-- settings_test.dart

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish nohfibu 0.0.1-alpha (y/N)? Uploading...
HTTP error 400: Bad Request
package:pub/src/http.dart 234:5           _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18          _ThrottleClient.send
===== asynchronous gap ===========================
package:oauth2/src/client.dart 114:20     Client.send
===== asynchronous gap ===========================
package:http/src/base_client.dart 93:32   BaseClient._sendUnstreamed
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 123:15  LishCommand._publish.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 94:7    LishCommand._publish
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 184:7   LishCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace pub publish --trace

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```
with a redirect to here? the error is somewhat cryptic? what did i do wrong?
oh i see in another post that the source can be helpful? its here: https://github.com/nohkumado/dart_fibu

ciao
Bruno

**Comment by jonasfj** [comment]
Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by jonasfj** [comment]
did you try `dart pub --trace pub publish --trace`

**Comment by isoos** [comment]
@nohkumado: it looks like you are using a non-default `PUB_HOSTED_URL` (`http://pub.dev`). Is there a reason for that?

**Comment by nohkumado** [comment]
István Soós ***@***.***> schrieb am Di., 28. Sept. 2021,
09:33:

> @nohkumado <https://github.com/nohkumado>: it looks like you are using a
> non-default PUB_HOSTED_URL (http://pub.dev). Is there a reason for that?
>

Oh Indeed, il assumes that was the url i was meint to use?  In the docu
there was a lot of info on how to publish but if didn't find any Info on
the where, so in assumed that url? What's the correct one?

**Comment by nohkumado** [comment]
I published the Log of the trace run?

Bruno Böttcher
--
35 rue de la république, FR-6720 Schwindratzheim
email: ***@***.***, ***@***.***
Fon:+33 3 88 89 91, Mob:+33 6 76 55 82 68
-------------------------------------------------
Dev: Java/Perl/PHP OS:GNU/LINUX, Android

Jonas Finnemann Jensen ***@***.***> schrieb am Di., 28. Sept.
2021, 09:27:

**Comment by nohkumado** [comment]
Jonas Finnemann Jensen ***@***.***> schrieb am Di., 28. Sept.
2021, 09:26:
Ok! Didn't knew that markdown works also in Mails!

Please use code fences
> <https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks>
> when posting
>
>  logs, for large log files please use a gist <https://gist.github.com/>.
>
Ok

**Comment by isoos** [comment]
@nohkumado: Can you just remove the `PUB_HOSTED_URL` override, and not use it at all? If you need to use one, please use `https` instead of `http`. `PUB_HOSTED_URL` is useful in certain cases, but for those users who are not behind a restrictive firewall, it doesn't add much.

Curious: which guide suggested to use it?

**Comment by nohkumado** [comment]
> @nohkumado: Can you just remove the `PUB_HOSTED_URL` override, and not use it at all? If you need to use one, please use `https` instead of `http`. `PUB_HOSTED_URL` is useful in certain cases, but for those users who are not behind a restrictive firewall, it doesn't add much.
> 
> Curious: which guide suggested to use it?

i was following 
https://dart.dev/tools/pub/publishing ? i removed it!
ok :D still learning.... the dart files shouldn't have the names of the classes in it, otherwise the api-doc prevents the package upload ....
seems to have uploaded it!

**Comment by nohkumado** [comment]
so it did upload, and i see it in the activity of 
#my pub.dev", but not in "my packages"? is tere a timeout? is it because its an alpha release?

**Comment by isoos** [comment]
> but not in "my packages"? 

We have a delay before the search index picks up the new package, and also have caching in front of it, so it may take a bit before you'll see it.

**Comment by nohkumado** [comment]
ok thanks!
