### ISSUE TITLE
Fix error message with --trace

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3154]
After a stack trace pub will print:
```
This is an unexpected error. Please run

    dart pub --trace pub publish --trace

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

We should probably fix that.

**Comment by jonasfj** [comment]
In error messages we should probably also print some metadata like, is `HOSTED_PUB_URL` defined?

**Comment by sigurdm** [comment]
Apparently `dart pub --trace` does not enable tracing. - one more bug :(

**Comment by sigurdm** [comment]
We no longer asks for `--trace`, but instead log the output to file.

Closing as obsolete.
