### ISSUE TITLE
create flutter new_project_name throws this dart issue

### ISSUE THREAD

**Issue by adydams** [dart-lang/pub#3175]
flutter create flutter_complete_guide
Creating project flutter_complete_guide...
  flutter_complete_guide\.gitignore (created)
  flutter_complete_guide\.idea\libraries\Dart_SDK.xml (created)
  flutter_complete_guide\.idea\libraries\KotlinJavaRuntime.xml (created)
  flutter_complete_guide\.idea\modules.xml (created)
  flutter_complete_guide\.idea\runConfigurations\main_dart.xml (created)
  flutter_complete_guide\.idea\workspace.xml (created)
  flutter_complete_guide\.metadata (created)
  flutter_complete_guide\android\app\build.gradle (created)
  flutter_complete_guide\android\app\src\main\kotlin\com\example\flutter_complete_guide\MainActivity.kt (created)
  flutter_complete_guide\android\build.gradle (created)
  flutter_complete_guide\android\flutter_complete_guide_android.iml (created)
  flutter_complete_guide\android\.gitignore (created)
  flutter_complete_guide\android\app\src\debug\AndroidManifest.xml (created)
  flutter_complete_guide\android\app\src\main\AndroidManifest.xml (created)
  flutter_complete_guide\android\app\src\main\res\drawable\launch_background.xml (created)
  flutter_complete_guide\android\app\src\main\res\drawable-v21\launch_background.xml (created)
  flutter_complete_guide\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  flutter_complete_guide\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  flutter_complete_guide\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  flutter_complete_guide\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  flutter_complete_guide\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  flutter_complete_guide\android\app\src\main\res\values\styles.xml (created)
  flutter_complete_guide\android\app\src\main\res\values-night\styles.xml (created)
  flutter_complete_guide\android\app\src\profile\AndroidManifest.xml (created)
  flutter_complete_guide\android\gradle\wrapper\gradle-wrapper.properties (created)
  flutter_complete_guide\android\gradle.properties (created)
  flutter_complete_guide\android\settings.gradle (created)
  flutter_complete_guide\ios\Runner\AppDelegate.swift (created)
  flutter_complete_guide\ios\Runner\Runner-Bridging-Header.h (created)
  flutter_complete_guide\ios\Runner.xcodeproj\project.pbxproj (created)
  flutter_complete_guide\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  flutter_complete_guide\ios\.gitignore (created)
  flutter_complete_guide\ios\Flutter\AppFrameworkInfo.plist (created)
  flutter_complete_guide\ios\Flutter\Debug.xcconfig (created)
  flutter_complete_guide\ios\Flutter\Release.xcconfig (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  flutter_complete_guide\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  flutter_complete_guide\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  flutter_complete_guide\ios\Runner\Base.lproj\Main.storyboard (created)
  flutter_complete_guide\ios\Runner\Info.plist (created)
  flutter_complete_guide\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  flutter_complete_guide\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  flutter_complete_guide\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  flutter_complete_guide\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  flutter_complete_guide\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  flutter_complete_guide\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  flutter_complete_guide\lib\main.dart (created)
  flutter_complete_guide\flutter_complete_guide.iml (created)
  flutter_complete_guide\pubspec.yaml (created)
  flutter_complete_guide\README.md (created)
  flutter_complete_guide\test\widget_test.dart (created)
  flutter_complete_guide\web\favicon.png (created)
  flutter_complete_guide\web\icons\Icon-192.png (created)
  flutter_complete_guide\web\icons\Icon-512.png (created)
  flutter_complete_guide\web\index.html (created)
  flutter_complete_guide\web\manifest.json (created)
Unexpected character (at character 1)                                   
<HTML><HEAD>
^
package:pub/src/source/hosted.dart 570:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 211:7           BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 87:11  RateLimitedScheduler._processNextTask.runJob
===== asynchronous gap ===========================
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                      Pool.withResource
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (65; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment]
Does this happen always?

What is your output of `flutter doctor`?

**Comment by sigurdm** [comment]
Closing as stale
