### ISSUE TITLE
HTTP error 403: Forbidden stack trace

### ISSUE THREAD

**Issue by leo516162** [dart-lang/pub#3191]
HTTP error 403: Forbidden
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gapHTTP error 403: Forbidden
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds... ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...

**Comment by jonasfj** [comment]
Closing due to lack of information.
