### ISSUE TITLE
flutter packages pub publish

### ISSUE THREAD

**Issue by qq627314025** [dart-lang/pub#3210]
HTTP error 400: Bad Request
package:pub/src/http.dart 229:5           _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 376:18          _ThrottleClient.send
===== asynchronous gap ===========================
package:oauth2/src/client.dart 113:20     Client.send
===== asynchronous gap ===========================
package:http/src/base_client.dart 94:32   BaseClient._sendUnstreamed
===== asynchronous gap ===========================
package:pub/src/command/lish.dart 100:15  LishCommand._publish.<fn>.<fn>
This is an unexpected error. Please run

    dart pub --trace publish

**Comment by jonasfj** [comment]
Command? Dart version? Pubspec? are you using a proxy? behind corporate firewall? Operating system?

**Comment by jonasfj** [comment]
quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by qq627314025** [comment]
Thank you. Thank you very much for your advice.
After I updated the browser kernel of my mobile phone, I found that the problem had been solved.
