### ISSUE TITLE
Ability to add multiple dependencies using `dart pub add` command

### ISSUE THREAD

**Issue by divyanshub024** [dart-lang/pub#3213]
## Description

Right now if try to add multiple dependencies through the command tool it gives an error.  

### cmd
```
dart pub add firebase_auth google_sign_in
```
### Error

```
Takes only a single argument.
```

It would be great if we could add this functionality for adding multiple dependencies through the command line.

**Comment by sigurdm** [comment]
We left this out initially because it is not clear how this mixes with `--path` and `--git`.

We could consider doing this for hosted dependencies only.

**Comment by sigurdm** [comment]
We decided we don't want to add this. It doesn't seem important enough.

Closing as wontfix.
