### ISSUE TITLE
pub finished with exit code 69

### ISSUE THREAD

**Issue by eliasrostami** [dart-lang/pub#3216]
hi
I want to installing google_fonts  but I can't because i have pub finished with exit code 69 error

**Comment by sigurdm** [comment]
We need more details.

This is probably an http-issue: https://github.com/dart-lang/pub/blob/master/lib/src/exit_codes.dart#L33 .

Can you explain what you did. Post the `pubspec.yaml` and the command you ran, and any output?

Are you on a restricted network? Can you consume other dart packages?

**Comment by vishwatejaaverager** [comment]
this error occurs because un wanted space in your 
https://stackoverflow.com/questions/56800642/how-to-fix-the-error-caused-pub-get-failed69 
do check this link for further info

**Comment by sigurdm** [comment]
Closing for lack of details.
