### ISSUE TITLE
[Suggestion] pubspec.lock use consistent path separator across different OSs

### ISSUE THREAD

**Issue by hanabi1224** [dart-lang/pub#3217]
When my flutter app references local pub packages, relative path to the local package presents in pubspec.lock , however, the path separator varies on different OSs, and result it many unnecessary commits to this file,  it will be awesome to use consistent path separator in case the file is source controlled and the project is developed on different OSs, thanks!

**Comment by sigurdm** [comment]
I thought we fixed this: https://github.com/dart-lang/pub/commit/72686563e767f8a359e48a267a2c323953a6a0ef

I cannot reproduce on my windows machine. What version are you using (`dart --version`)

If you use forward slash in your path dependency in `pubspec.yaml` it should come out as a forward slash in your `pubspec.lock`, no matter the platform.

**Comment by sigurdm** [comment]
Ah - I see now this is an old issue transferred.

Closing this as fixed :)
