### ISSUE TITLE
Create remote pub repository abstraction

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3228]
It would be nice if all HTTP requests, throttling, retry logic and meta-data attachment for interfacing a pub repository over HTTP was behind a single abstraction like:

```dart
abstract class HostedRepository {
  HostedRepository(http.Client client, String hostedUrl, Credentials? credential);

  Future<PackageVersionsResponse> listVersions(String packageName, {DependencyType reason});

  Future<Uint8List> downloadPackage(String packageName, Version version, {DependencyType reason});

  /// Publish package and return message from server.
  Future<String> publish(String packageName, Version version, Uint8List package);
}

enum DependencyType {
  none,
  dependency,
  devDependency,
  transitive,
};

abstract class PackageVersionsResponse {
  String get name;
  bool get isDiscontinued;
  String get replacedBy;
  List<PackageVersionInfo> versions;
}

class PackageVersionInfo {
  Version get version;
  bool get isRetracted;
  Pubspec get pubspec;
}

/// Base class for ALL exceptions thrown by [HostedRepository]
abstract class HostedRepositoryException implements Exception {}

class AuthenticationFailedException extends HostedRepositoryException {
  String? get serverMessage;
};

class AuthorizationFailedException extends HostedRepositoryException {
  String? get serverMessage;
};

class ConnectionFailureException extends HostedRepositoryException {};
class InternalRepositoryFailureException extends HostedRepositoryException {};
// ... whatever is necessary to cover all things that can go wrong when making an HTTP request to a hosted pub repository.
```

Basically, this is an abstraction that fully encapsulates the REST API specified in:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

It doesn't have caching, or anything else, beyond bare HTTP it handles:
 * retry logic,
 * attaching metadata,
 * attaching credentials (as given in the constructor),
 * throttling connections to avoid more than 16 concurrent HTTP requests (globally)
 * converting SocketException, IOException, etc. into various subclasses of `HostedRepositoryException` such that these are easy to handle else where...

Option questions:
 * Should `HostedRepository` include `credentials` and `hostedUrl` in the constructor, or just take `TokenStore` in the constructor, and have `hostedUrl` as a parameter for each end-point?
 * Should we have a wrapper for `HostedRepository` with in-memory caching, queuing and prefetching? (would such logic fit nicely into a wrapper, I suspect so -- if we have `hostedUrl` has a parameter on each method.

**Comment by sigurdm** [comment]
```
  Future<Uint8List> downloadPackage(String packageName, Version version, {DependencyType reason});
```
Could also take a destination for downloading and extracting directly to disk... Thus we can still be streaming, but not expose the stream. Not sure we ever need to download a package but not put on disk...

**Comment by sigurdm** [comment]
> throttling connections to avoid more than 16 concurrent HTTP requests (globally)

Perhaps that should still be handled by the http-client. We also make other http-requests (for oauth) and the total should be throttled in principle (though it might not matter in practice).

**Comment by sigurdm** [comment]
> /// Base class for ALL exceptions thrown by [HostedRepository]
> abstract class HostedRepositoryException implements Exception {}

We could use an enum to ensure exhaustive error handling

**Comment by jonasfj** [comment]
> Could also take a destination for downloading and extracting directly to disk...

We could also make it extract to a folder on disk... so streaming -> gzip -> tar -> disk..

On the other hand, streaming to file or disk is always the simplest and safest.. and this probably isn't a performance bottleneck.

**Comment by sigurdm** [comment]
Closing as stale
