### ISSUE TITLE
an unexpected error

### ISSUE THREAD

**Issue by MaahdiCodes** [dart-lang/pub#3231]
Resolving dependencies...
Invalid argument(s): Minimum version ("1.0.0") must be less than maximum ("1.0.0-0").
package:pub_semver/src/version_range.dart 67:7      new VersionRange
package:pub/src/solver/reformat_ranges.dart 58:27   _reformatTerm
package:pub/src/solver/reformat_ranges.dart 36:26   reformatRanges.<fn>
dart:_internal                                      ListIterable.toList
package:pub/src/solver/reformat_ranges.dart 37:12   reformatRanges
package:pub/src/solver/reformat_ranges.dart 136:13  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/reformat_ranges.dart 135:25  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/reformat_ranges.dart 135:25  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/reformat_ranges.dart 135:25  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/reformat_ranges.dart 135:25  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/reformat_ranges.dart 135:25  _reformatCause
package:pub/src/solver/reformat_ranges.dart 38:7    reformatRanges
package:pub/src/solver/version_solver.dart 310:24   VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 131:27   VersionSolver._propagate
package:pub/src/solver/version_solver.dart 95:11    VersionSolver.solve.<fn>
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 765:14           BoundHostedSource.withPrefetching.<fn>
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 112:14  RateLimitedScheduler.withPrescheduling
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 764:12           BoundHostedSource.withPrefetching
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 92:14    VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 237:18              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 106:5          UpgradeCommand._runUpgrade
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 102:12         UpgradeCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace pub --trace upgrade

**Comment by sigurdm** [comment]
This looks like: https://github.com/dart-lang/pub/issues/3098 that has been fixed.

What version of pub are you on?

**Comment by jonasfj** [comment]
What is your pub version and what does your pubspec.yaml look like?

**Comment by jonasfj** [comment]
Close due to lack of info.
