### ISSUE TITLE
Error message gives incorrect instructions for tracing pub

### ISSUE THREAD

**Issue by Hixie** [dart-lang/pub#3236]
When pub fails with a crash like in https://github.com/dart-lang/sdk/issues/47759, it says to run `dart pub --trace pub deps`, but that's not valid. It's even worse when run with `flutter`.

For example, set up a `pubspec.yaml` that crashes `pub deps` as in https://github.com/dart-lang/sdk/issues/47759, then run `flutter pub deps`. It tells you to run `dart pub --trace deps`. If you run that, it fails to trace and crashes telling you to run `dart pub --trace pub --trace deps`. If you run that, you get told `Cannot specify arguments before a command.`.

**Comment by sigurdm** [comment]
Yeah this is broken. `--trace` doesn't work. :)

I suggest we instead dump all log-info into a `.dart-tool/pub/pub-log.txt` - file on errors (limited to a finite size) and mention that in the error message.
