### ISSUE TITLE
Error when getting package from pub.dev

### ISSUE THREAD

**Issue by marwan-al-ali** [dart-lang/pub#3237]
PS E:\Dart Learning\flutterdemo2> dart pub --trace get --no-precompile
Resolving dependencies...
  async 2.8.1 (2.8.2 available)
+ cached_network_image 3.1.0+1
+ cached_network_image_platform_interface 1.0.0
+ cached_network_image_web 1.0.1
  characters 1.1.0 (1.2.0 available)
+ crypto 3.0.1
+ ffi 1.1.2
+ file 6.1.2
+ flutter_blurhash 0.6.0
+ flutter_cache_manager 3.1.3
+ http 0.13.4
+ http_parser 4.0.0
  matcher 0.12.10 (0.12.11 available)
+ octo_image 1.0.0+1
+ path_provider 2.0.7
+ path_provider_android 2.0.9
+ path_provider_ios 2.0.7
+ path_provider_linux 2.1.2
+ path_provider_macos 2.0.3
+ path_provider_platform_interface 2.0.1
+ path_provider_windows 2.0.4
+ pedantic 1.11.1 (discontinued replaced by lints)
+ platform 3.0.2
+ plugin_platform_interface 2.0.2
+ process 4.2.4
+ rxdart 0.27.3
+ sqflite 2.0.0+4
+ sqflite_common 2.0.1+1
+ synchronized 3.0.0
  test_api 0.4.2 (0.4.8 available)
+ uuid 3.0.5
  vector_math 2.1.0 (2.1.1 available)
+ win32 2.3.1
+ xdg_directories 0.2.0
Downloading transparent_image 2.0.0...
Downloading fake_async 1.2.0...
Downloading cached_network_image_web 1.0.1...
Downloading flutter_cache_manager 3.1.3...
Downloading win32 2.3.1...
HTTP error 403: Forbidden
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment]
Is this still an issue?

Reopen if so.

Closing assuming stale.
