### ISSUE TITLE
request on dart pub publish --dry-run

### ISSUE THREAD

**Issue by X-SLAYER** [dart-lang/pub#3246]
I think it might be helpful to add a check on the package name to avoid any conflicts because that happened to me I created a new package with a name already in use and that caused an error for me and spend some time figuring it out

**Comment by sigurdm** [comment]
Would you not just have spent that same amount of time when doing `--dry-run`?

I would prefer not copying this logic to the client.

**Comment by jonasfj** [comment]
Without authenticating against `pub.dev` we can't tell if you're trying to publish a new package or updating an existing package.

I think this easily becomes hard to do. Lots of people run `--dry-run` as part of CI, so requiring authentication would not be a good idea.
