### ISSUE TITLE
HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by Samarhussami** [dart-lang/pub#3248]
Resolving dependencies...
  async 2.8.1 (2.8.2 available)
  characters 1.1.0 (1.2.0 available)
  cloud_firestore 3.1.0 (3.1.1 available)
  cloud_firestore_platform_interface 5.4.5 (5.4.6 available)
  cloud_firestore_web 2.5.0 (2.6.0 available)
  firebase_auth 3.2.0 (3.3.0 available)
  firebase_auth_platform_interface 6.1.4 (6.1.5 available)
  firebase_auth_web 3.2.0 (3.3.0 available)
  firebase_core 1.10.0 (1.10.1 available)
  firebase_core_platform_interface 4.1.0 (4.2.0 available)
  firebase_core_web 1.2.0 (1.3.0 available)
  matcher 0.12.10 (0.12.11 available)
+ modal_progress_hud_nsn 0.1.0-nullsafety-1
  test_api 0.4.2 (0.4.8 available)
  vector_math 2.1.0 (2.1.1 available)
Downloading modal_progress_hud_nsn 0.1.0-nullsafety-1...
Downloading cloud_firestore 3.1.0...
Downloading firebase_auth 3.2.0...
Downloading firebase_auth_web 3.2.0...
Downloading firebase_auth_platform_interface 6.1.4...
HTTP error 403: Forbidden
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by Samarhussami** [comment]
this is the result when I run
dart pub --trace pub --trace get --no-precompile

**Comment by jonasfj** [comment]
Are you behind a proxy? or using a mirror? what os?


--------------------------

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).
