### ISSUE TITLE
Suggested SDK constraint should include null safety

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#3250]
# Environment

- `pub version` or `flutter pub version`: Pub 2.15.0-257.0.dev

# Problem

When creating a new package with no sdk constraint in the pubspec, a version constraint is suggested that results in a package that is not opted in to null safety.

```
> dart pub get
Resolving dependencies...
pubspec.yaml has no lower-bound SDK constraint.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '>=2.10.0 <3.0.0'

See https://dart.dev/go/sdk-constraint
```

We should suggest one that is opted in instead, or possibly just the current sdk version?

See the code here https://github.com/dart-lang/pub/blob/400f21e9883ce6555b66d3ef82f0b732ba9b9fc8/lib/src/entrypoint.dart#L877.

**Comment by sigurdm** [comment]
Yeah, let's use the current version.

**Comment by sigurdm** [comment]
This was fixed in https://github.com/dart-lang/pub/pull/3690
