### ISSUE TITLE
Error executing "flutter pub global activate get_cli" command

### ISSUE THREAD

**Issue by pmorellg** [dart-lang/pub#3251]
Resolving dependencies...
+ _fe_analyzer_shared 31.0.0
+ analyzer 2.8.0
+ ansicolor 2.0.1
+ archive 3.1.6
+ args 2.3.0
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.5.0
+ cli_menu 0.3.0-nullsafety.0
+ cli_util 0.3.5
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dart_console 1.0.0
+ dart_style 2.2.0
+ ffi 1.1.2
+ file 6.1.2
+ get_cli 1.6.0
+ glob 2.0.2
+ http 0.13.4
+ http_parser 4.0.0
+ intl 0.17.0
+ matcher 0.12.11
+ meta 1.7.0
+ package_config 2.0.2
+ path 1.8.0
+ process_run 0.12.2+2
+ pub_semver 2.1.0
+ pubspec 2.0.1
+ quiver 3.0.1+1
+ recase 4.0.0
+ source_span 1.8.1
+ stack_trace 1.10.0
+ string_scanner 1.1.0
+ synchronized 3.0.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ uri 1.0.0
+ version 2.0.0
+ watcher 1.0.1
+ win32 2.3.1
+ yaml 3.1.0
Downloading get_cli 1.6.0...
Downloading version 2.0.0...
Downloading recase 4.0.0...
Downloading cli_menu 0.3.0-nullsafety.0...
Downloading cli_dialog 0.5.0...
Downloading ansicolor 2.0.1...
Downloading dart_console 1.0.0...
Downloading process_run 0.12.2+2...
Downloading win32 2.3.1...
HTTP error 403: Forbidden
package:pub/src/http.dart 234:5              _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18             _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22    BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12               withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5     BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7     BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 231:37  GlobalPackages._installInCache.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 226:5   GlobalPackages._installInCache
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 127:5   GlobalPackages.activateHosted
This is an unexpected error. Please run

    dart pub --trace global activate get_cli

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment]
Are you behind a proxy? or using a mirror? what os?

Does this always happen?

**Comment by sigurdm** [comment]
Closing as stale
