### ISSUE TITLE
Specify git identity for dependencies

### ISSUE THREAD

**Issue by FaFre** [dart-lang/pub#3258]
I like to work with Github deployment keys, because they are read-only (unlike the main SSH-Key which is always read/write).
A deployment key is always specified per repository, and the fingerprint can only used once (same key for multiple repos not possible).

Now I have multiple repos with different deployment keys. All keys are added to the ssh-agent. When I run `pub get`, it will always use the first key in ssh-agent, because auth works for git@github.com (it's always the same user for Github). The problem here is that different keys have different repo access, so it's not possible to clone repo n +1, because the first key in ssh-agent has only access to repo n.

It would be nice to have the possibility to specify the identity in `pubspec` to tell, which key to use.

**Comment by jonasfj** [comment]
SSH is intended to be one key per host.

I don't even think `~/.ssh/config` can do what you're asking for.

I don't think we should do this.

**Comment by FaFre** [comment]
@jonasfj  fyi: SSH is a very flexible protocol. Although the standard use key would be on SSH key per user@host, the above is possible. Maybe for future references: https://snipe.net/2013/04/11/multiple-github-deploy-keys-single-server/

However, using a monorepo structure will work around this problem and is a much better solution (as I found out later).

**Comment by jonasfj** [comment]
> Maybe for future references: https://snipe.net/2013/04/11/multiple-github-deploy-keys-single-server/

ah, yeah that's a nice way to do it. And it doesn't involve tweaking pub :D
