### ISSUE TITLE
For custom command lines: Add a "New version is available" warning

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub#3259]
A common problem with Dart command lines is, it's not obvious when a new version of the package is available.

Packages could manually implement a warning to say "Hey, a new version" is available. But that's a problem which all command lines will want to implement. It may make sense to have a solution to that problem built directly within `pub`

**Comment by sigurdm** [comment]
Not sure what you mean by "custom command lines".

We do have some functionality in this space already:

`dart pub get` will tell you if you have packages with newer versions available
```
> dart pub get
Resolving dependencies... (1.4s)
  _fe_analyzer_shared 31.0.0 (32.0.0 available)
  analyzer 2.8.0 (3.0.0 available)
  coverage 1.0.3 (1.0.4 available)
  js 0.6.3 (0.6.4 available)
  path 1.8.0 (1.8.1 available)
  pedantic 1.11.1 (discontinued replaced by lints)
  test 1.19.5 (1.20.1 available)
  test_api 0.4.8 (0.4.9 available)
  test_core 0.4.9 (0.4.11 available)
  vm_service 7.5.0 (8.1.0 available)
Got dependencies!
```

`dart pub outdated` will give you an overview of you outdated dependencies, and what versions you can upgrade to without getting incompatibilities:
```
> dart pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name         Current  Upgradable  Resolvable  Latest  

direct dependencies:
analyzer             *2.8.0   *2.8.0      3.0.0       3.0.0   
path                 *1.8.0   1.8.1       1.8.1       1.8.1   

dev_dependencies:   
test                 *1.19.5  1.20.1      1.20.1      1.20.1  

transitive dependencies:
_fe_analyzer_shared  *31.0.0  *31.0.0     32.0.0      32.0.0  

transitive dev_dependencies:
coverage             *1.0.3   1.0.4       1.0.4       1.0.4   
js                   *0.6.3   *0.6.3      *0.6.3      0.6.4   
test_api             *0.4.8   0.4.9       0.4.9       0.4.9   
test_core            *0.4.9   0.4.11      0.4.11      0.4.11  
vm_service           *7.5.0   8.1.0       8.1.0       8.1.0   

6 upgradable dependencies are locked (in pubspec.lock) to older versions.
To update these dependencies, use `dart pub upgrade`.
```

Furthermore we are working on dependabot integration for automatically creating pr's upgrading your outdated dependencies.

https://github.com/dependabot/dependabot-core/pull/4510

**Comment by sigurdm** [comment]
Please reopen with a clarification if you meant something different.

**Comment by rrousselGit** [comment]
That's closing issues a bit too fast. I would've answered

**Comment by sigurdm** [comment]
No problem - we just reopen :)

**Comment by rrousselGit** [comment]
Ah, I already made a new one https://github.com/dart-lang/pub/issues/3266. So closing
