### ISSUE TITLE
`dot packages deprecation` web page looks unreachable

### ISSUE THREAD

**Issue by talisk** [dart-lang/pub#3265]
https://github.com/dart-lang/pub/blob/2fd6b5f0ece29867a2abaa0a679732dadeab929f/lib/src/lock_file.dart#L223-L229

The url `https://dart.dev/go/dot-packages-deprecation` looks unreachable.

**Comment by sigurdm** [comment]
I think we have forgot to write this document.

**Comment by sigurdm** [comment]
This is fixed now.
