### ISSUE TITLE
Add a "New version is available" warning to `pub global run`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub#3266]
A common problem with Dart command lines is, it's not obvious when a new version of the package is available.

Packages could manually implement a warning to say "Hey, a new version" is available. But that's a problem which all command lines will want to implement. It may make sense to have a solution to that problem built directly within pub

Such that we have:

```
$ dart pub global activate my_command_line

$ my_command_line
Warning: A new version of my_command_line is available on pub.
Run `dart pub global activate my_command_line` to upgrade

<actual input from the command line>
```

**Comment by sigurdm** [comment]
Ah now I see what you meant!

I understand wanting to do this, but I think we generally don't want network access on the fast path (running the program).

Also, the bin-stub we install in `.pub_cache/bin` will try to invoke the program directly without entering pub. Not sure we want to change that.

We could have a command like `pub global check-up-to-date [program]` that each global command could invoke if it wanted.

@jonasfj what do you think?

**Comment by rrousselGit** [comment]
Indeed I can see a few issues too. 

> We could have a command like pub global check-up-to-date [program] that each global command could invoke if it wanted.

That sounds good. 

Then we could add an util function to [cli_util](pub.dev/packages/cli_util) to help with that:

```dart
import 'package:cli_util/cli_util.dart';

Future<void> main() async {
  await verifyUpToDate();
}
```

**Comment by jonasfj** [comment]
In general I think `dart pub global activate` could use a re-design someday. Taking the update-flow into consideration would be a good idea.

As for this specific case, if you want your application to check for updates, then... why not just ping: `https://pub.dartlang.org/api/packages/my_command_line`, and read the `latest.version` property, and compare it to the current version (using https://pub.dev/packages/build_version).

Whether or not running the commandline should check for updates probably depends on the use-case.

**Comment by sigurdm** [comment]
I will close this issue as wont-fix for now.
