### ISSUE TITLE
Support multiple packages in `dart pub add ...`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#3273]
Noted at https://github.com/Dart-Code/Dart-Code/issues/3737#issuecomment-1000548925, it would be neat to be able to provide a set of packages to add in one step, since running `dart pub add` multiple times takes much longer.

It would be really useful for copy/pasting from articles, both into the CLI or into VS Code's **Dart: Add Dependency** input box.

**Comment by sigurdm** [comment]
This was discussed in https://github.com/dart-lang/pub/issues/3213 we closed as wont-fix.

Maybe we should reconsider...

We could allow several names, but only allow them from one source (basically would only work for hosted)
```
dart pub add foo bar baz # works, comes from default host
dart pub add foo bar baz --hosted https://package-repo.com # works
dart pub add foo bar baz --git https://git.com # only one package per git repo (fails)
```

That would cover the common usecase.

If anyone is interested in contributing I think we would accept something like that.

**Comment by DanTup** [comment]
Restricting it to one source is probably reasonable for me (it'd be nice to not have to, but I suspect > 99% of users from VS Code would just want a few names from Pub).

If someone were to contribute it (not promising, but in case I do find time 🙂), am I right in thinking it would start with removing this:

https://github.com/dart-lang/pub/blob/17c5addbbf93c4462dc0dfeefcd43b48d713b1c1/lib/src/command/add.dart#L94-L95

And then running this part for each package (passing `updatedPubSpec` back in for subsequent calls):

https://github.com/dart-lang/pub/blob/17c5addbbf93c4462dc0dfeefcd43b48d713b1c1/lib/src/command/add.dart#L101-L103

Before then running the normal solving code below, and then the checks that is satisfies the requirements below also for each package?

**Comment by sigurdm** [comment]
Yes - I think that looks like the right strategy!

**Comment by ArV29** [comment]
I would like to work towards adding this feature if no one else has already started

**Comment by DanTup** [comment]
I haven't started (and probably wouldn't get to in the next few weeks), so that sounds good to me :-)

Please CC me if you do file a PR, as I may be interested in testing it for VS Code integration prior to it being out in a release to get a headstart :-)

**Comment by ArV29** [comment]
Sure,
This is going to be my first real contribution btw so I would probably need a bit of guidance initially

**Comment by ArV29** [comment]
> I haven't started (and probably wouldn't get to in the next few weeks), so that sounds good to me :-)
> 
> Please CC me if you do file a PR, as I may be interested in testing it for VS Code integration prior to it being out in a release to get a headstart :-)

I've started working on the issue and am quite close to solving it, but I'm running into a bit of a problem with this piece of code.

```dart
    on SolveFailure catch (e) {
      dataError(e.message);
    } on WrappedException catch (e) {
      /// [WrappedException]s may appear if an invalid [hostUrl] is passed in.
      dataError(e.message);
    }
```

whenever one of the multiple package names is invalid or raises an exception, a dataError is thrown which terminates the program with error code 'data', and the pub add command for the subsequent packages gets ignored.

**Comment by DanTup** [comment]
It doesn't seem particularly odd to me that if one of them fails, the whole command fails and no changes are made. As someone who will be consuming this from a tool, it would be nice to know "zero exit code means everything worked" and "non-zero exit code means it failed and nothing was done".

(I'd wait for @sigurdm's opinion though :-) )

**Comment by ArV29** [comment]
The command actually fails when it encounters an invalid package name so if the previous packages were correct then they would be added and the subsequent packages would be ignored according to the approach I'm taking towards this problem.

One thing that could be done is changing the dataError to simple print/log statements which would show the error for the respective invalid package only and continue with the others normally

**Comment by DanTup** [comment]
> The command actually fails when it encounters an invalid package name so if the previous packages were correct then they would be added and the subsequent packages would be ignored according to the approach I'm taking towards this problem.

My understanding from the code (see [my notes above](https://github.com/dart-lang/pub/issues/3273#issuecomment-1006439488)) was that the changes to the pubspec are only made in-memory initially, and then committed at the end to disk if everything works. So I would have expected a failure in package 2 of 3 would still caused none of them to be written (because `dataError()` will throw and not proceed through the function).

**Comment by ArV29** [comment]
Oh ok, I got what you're saying. I was thinking about running pub add for each package name individually which was quite a different approach from your initial notes.

**Comment by ArV29** [comment]
This is my approach with the problem now

```diff
if (argResults.rest.isEmpty) {
      usageException('Must specify a package to be added.');
-   } else if (argResults.rest.length > 1) {
-      usageException('Takes only a single argument.');
-   } 
+  } else if(argResults.rest.length>1 && gitUrl != null){
+      usageException('Only one package per git repository');
+  }   
-    final packageInformation = _parsePackage(argResults.rest.first);
-    final package = packageInformation.first;

-    /// Perform version resolution in-memory.
-    final updatedPubSpec =
-        await _addPackageToPubspec(entrypoint.root.pubspec, package);

+  var packageInformation, package;
+    Pubspec updatedPubSpec = entrypoint.root.pubspec;
+    for(var givenPackage in argResults.rest){
+      packageInformation = _parsePackage(givenPackage);
+      package = packageInformation.first;
+      updatedPubSpec =
+      await _addPackageToPubspec(updatedPubSpec, package);
+  }
late SolveResult solveResult;
```


Seems to fit most of the use cases based on the [initial requirements](https://github.com/dart-lang/pub/issues/3273#issuecomment-1006428080)

**Comment by DanTup** [comment]
I think you may need to also wrap a loop around:

https://github.com/dart-lang/pub/blob/17c5addbbf93c4462dc0dfeefcd43b48d713b1c1/lib/src/command/add.dart#L128-L129

to verify the results of each package. Right now it might be only verifying the last one? (it's probably worth including some combinations of that in tests)

**Comment by ArV29** [comment]
Okay so digging bit deeper, the

`updatePubspec()`

works for a single package only so it has too be called for every package
therefore a loop which verifies as well as adds the results to pubspec is required.
```dart
for(var givenPackage in argResults.rest){
      packageInformation = _parsePackage(givenPackage);
      package = packageInformation.first;
      final resultPackage = solveResult.packages
        .firstWhere((packageId) => packageId.name == package.name);

     /// Assert that [resultPackage] is within the original user's expectations.
      var constraint = package.constraint;
      if (!constraint.allows(resultPackage.version)) {
        var dependencyOverrides = updatedPubSpec.dependencyOverrides;
        if (dependencyOverrides.isNotEmpty) {
          dataError(
            '"${package.name}" resolved to "${resultPackage.version}" which '
            'does not satisfy constraint "${package.constraint}". This could be '
            'caused by "dependency_overrides".');
        }
        dataError(
          '"${package.name}" resolved to "${resultPackage.version}" which '
          'does not satisfy constraint "${package.constraint}".');
      }
      _updatePubspec(resultPackage, packageInformation, isDev);
    }
```

**Comment by ArV29** [comment]
I modified the test for various add commands and they seem to pass for my [implementation.](https://github.com/ArV29/pub/commit/32b75345aee881e17ceeb664b039a4ba9d3bc528).

What else should I check before going ahead with a PR?

**Comment by DanTup** [comment]
That's probably a question for a Pub dev, although it's probably worth filing a PR anyway as it may be easier to discuss the code in a PR.

btw, the changes you made tests don't seem to show up in that branch, so you may need to push them too?

And thanks! It'll be neat to wire this up in VS Code :-)

**Comment by ArV29** [comment]
I added the code for test [in this commit](https://github.com/ArV29/pub/commit/68ba2b65c191b2399ef0b12db2934ef6262d6095).

Going ahead with the PR.

**Comment by sigurdm** [comment]
Closed in https://github.com/dart-lang/pub/pull/3283
