### ISSUE TITLE
set default repository

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3274]
I'm the author of unpubd which is a Docker packaged version of unpub.

I'm trying to make setup for users easier.

Currently the user must set the environment variable pub_hosted_url to point at their private repo.

This is a little clumsy and doesn't help with an ide (unless you get the Env set at the right level).

It would be much easier if we had a command that set the default repo.

Dart pub repo http://myrepo:4000/some path.

To set the path back to pub.dev
Dart pub repo reset

Even better would be to allow users to name a repo

Dart pub repo add myrepo http://myrepo...

Then to change repos

Dart pub repo use myrepo

And reset

Dart pub repo use pub.dev

Is this a change the team would entertain?

Is there an argument that we blend it in with the token commands?

**Comment by sigurdm** [comment]
We have some vague ideas for a "mirrors" section in the pubspec.yaml where you could specify remappings for package-repository urls. I don't think we get to that soon though.

If you are only hosting private packages on the unpub instance we would recommend using explicit urls for the dependencies.

Something like:
```
dependencies:
  foo:
    hosted: http://myrepo:4000/some/path
    version: 2.0.0
```

**Comment by sigurdm** [comment]
Will close as wont-fix though hopefully one day we will do something that solves this in a general way.

**Comment by bsutton** [comment]
I'm trying to avoid having to explicitly configure each system.
If I submitted a PR is it likely to be accepted?

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by sigurdm** [comment]
I don't think we want a `Dart pub repo ` command - at least this should be configured on a per-project basis.

Not sure if our thoughts around the "mirrors" concept are far enough that we have a coherent design to implement
