### ISSUE TITLE
Provide better error messages of forbidden.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3281]
I'm working on a variant of unpub with finer grained security.

Returning a http 403 - forbidden generates the following message:

```
insufficient permissions to the resource at the http://localhost:4000 package repository.\n'
            'You can modify credentials using:\n'
            '    pub token add http://localhost:4000\n'
            'Authentication failed!\n'
            ''
```
The returned 403 includes a body with a more detailed message but pub ignores the body.

Is it viable for pub to print the body so the server can provide better guidance to the user on what action to take?

Ideally the message should read:
```
insufficient permissions to the resource at the http://localhost:4000 package repository.\n'
  <body of error>
```

The Authentication failed is really only appropriate to the the unauthorized which gives the appropriate response of:

```
Actual: 'http://localhost:4000 package repository requested authentication!\n'
            'You can provide credentials using:\n'
            '    pub token add http://localhost:4000\n'
            'Authentication failed!\n'
            ''
```

It makes sense to print the 'pub token add' and 'Authentication failed' info for unauthorised but not for forbidden.

**Comment by sigurdm** [comment]
You can provide more information from the server side by providing a `WWW-Authenticate: Bearer realm="pub", message="<message>"` header.

See:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md#missing-authentication-or-invalid-token

**Comment by sigurdm** [comment]
Closing as already done. Please reopen if I misunderstood something.
