### ISSUE TITLE
documenation on third party token refresh.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3284]
With dart 2.15 and the requirement for a third party pub server to use their own tokens I'm trying to work out how the token refresh logic works.

I've found the /token end point which hints at this functionality.

Is there some way for the server to replace the token if it has expired?

**Comment by sigurdm** [comment]
> Is there some way for the server to replace the token if it has expired?

No - you will have to do that manually.

> I've found the /token end point which hints at this functionality.

What is the /token endpoint?

**Comment by bsutton** [comment]
I've found an adequate work around. so thanks.
