### ISSUE TITLE
Could not un-tar (exit code 2). Error: 

### ISSUE THREAD

**Issue by wangpenghui0612** [dart-lang/pub#3293]
When I run "flutter pub get" in app,somethings always failed,this is log:

`
Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\21056802\AppData\Local\Temp\pub_4dd94f45-7e4f-11ec-a254-b07d64d036ca\data.tar

Extracting  .gitignore

Extracting  .idea\$PROJECT_FILE$

Extracting  .idea\.gitignore

Extracting  .idea\camera_camera.iml

Extracting  .idea\codeStyles\Project.xml

Extracting  .idea\inspectionProfiles\Project_Default.xml

Extracting  .idea\libraries\Dart_Packages.xml

Extracting  .idea\libraries\Dart_SDK.xml

Extracting  .idea\libraries\Flutter_Plugins.xml

Extracting  .idea\misc.xml

Extracting  .idea\modules.xml

Extracting  .idea\qaplug_profiles.xml

Extracting  .idea\vcs.xml

Extracting  CHANGELOG.md

Extracting  LICENSE

Extracting  README.md

Extracting  camera_camera.iml

file changelog.md

already exists. Overwrite with 

changelog.md?

(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 

ERROR: Can't allocate required memory!

package:pub/src/io.dart 970:7                _extractTarGzWindows.<fn>

===== asynchronous gap ===========================

package:pub/src/io.dart                      _extractTarGzWindows.<fn>

package:pub/src/io.dart 829:20               withTempDir

package:pub/src/io.dart 941:10               _extractTarGzWindows

package:pub/src/io.dart 871:18               extractTarGz

package:pub/src/source/hosted.dart 398:11    BoundHostedSource._download

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 264:13    BoundHostedSource.downloadToSystemCache

package:pub/src/entrypoint.dart 407:48       Entrypoint._get.<fn>

dart:async                                   runZoned

package:pub/src/http.dart 279:10             withDependencyType

package:pub/src/entrypoint.dart 403:12       Entrypoint._get

dart:async                                   Future.wait

package:pub/src/entrypoint.dart 252:18       Entrypoint.acquireDependencies

dart:async                                   _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart   VersionSolver.solve

dart:async                                   _completeOnAsyncReturn

package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching

dart:async                                   _completeOnAsyncReturn

package:pub/src/rate_limited_scheduler.dart  RateLimitedScheduler.withPrescheduling

dart:async                                   _completeOnAsyncReturn

package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching.<fn>

dart:async                                   _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart   VersionSolver.solve.<fn>

dart:async                                   _completeOnAsyncReturn

package:pub/src/solver/version_solver.dart   VersionSolver._result

This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
Process finished with exit code 1
`

I don’t find the tar in my computer in the given path “C:\Users\21056802\AppData\Local\Temp\pub_4dd94f45-7e4f-11ec-a254-b07d64d036ca\data.tar”
My computer belongs to windows，but my workmate‘s iOS computer have not this problem.

I have token a look other issues like this problem in here, and delete all files in ~/.pub-cache or run "flutter packages pub cache repair", but they are all failed.

My flutter‘s version is 1.17.2.

**Comment by sigurdm** [comment]
There is an error message saying: "ERROR: Can't allocate required memory!" Could that be the reason?

If so, try freeing some memory by closing programs, or getting a bigger computer...

**Comment by sigurdm** [comment]
Did that help?

**Comment by wangpenghui0612** [comment]
> Did that help?

That is useless.I also try to use an other windows computer, but this problem still exists.

**Comment by sigurdm** [comment]
Try upgrading to a newer flutter - we changed the tar implementation. Hopefully the new one works better.

**Comment by sigurdm** [comment]
Can you send your pubspec.yaml?

**Comment by wangpenghui0612** [comment]
`
name: synModule
description: A new flutter module project.
version: 1.0.0+1
environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # The  following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_boost: ^1.17.1
  quiver: ^2.0.3
  json_annotation: ^3.0.0
  permission_handler: ^5.0.0
  dio_http_cache: ^0.2.11
  date_format: ^1.0.9
  package_info: ^0.4.0+14d34

  retrofit_flutter: ^0.0.4

  path_provider: ^1.6.22
  #  #状态管 理
  provider: ^4.3.2+2
  #md5
  crypto: ^2.0.6
  encrypt: ^4.0.0

  #调用系统相册
  image_picker: ^0.6.7+4

  #图片拼接
  merge_images: ^1.0.3

  #轮播控件
  flutter_swiper: ^1.1.6
  dio: ^3.0.10
  video_thumbnail: ^0.2.5+1
  #图片旋转,主要用于适配ios设备拍摄的图片
  exif: ^1.0.3
  #grid view
  flutter_staggered_grid_view: 0.3.2
 #======================四个TAB=============================

  syn_home_page:
    hosted:
      name: syn_home_page
      url: http://101.200.241.211:8083
    version: 0.1.38
  syn_scene:
    hosted:
      name: syn_scene
      url: http://101.200.241.211:8083
    version: 0.4.92
  syn_discover:
    hosted:
      name: syn_discover
      url: http://101.200.241.211:8083
    version: 0.1.89
  syn_mine_pages:
    hosted:
      name: syn_mine_pages
      url: http://101.200.241.211:8083
    version: 0.2.13
 #=======================接口封装=============================
  syn_service_shop:
    hosted:
      name: syn_service_shop
      url: http://101.200.241.211:8083
      description: 商城数据请求
    version: 0.0.77
  syn_user:
    hosted:
      name: syn_user
      url: http://101.200.241.211:8083
    version: 0.0.73
  syn_service_own_request:
    hosted:
      name: syn_service_own_request
      url: http://101.200.241.211:8083
    version: 0.2.29
  syn_service_1_plus_n:
#    path: ../../组件/syn_service_1_plus_n
    hosted:
      name: syn_service_1_plus_n
      url: http://101.200.241.211:8083
    version: 0.0.14
  syn_discover_api:
    hosted:
      name: syn_discover_api
      url: http://101.200.241.211:8083
    version: 0.0.9

 #=======================base及工具=============================
  syn_main:
    hosted:
      name: syn_main
      url: http://101.200.241.211:8083
    version: 0.0.29
  syn_widget_loading:
    hosted:
      name: syn_widget_loading
      url: http://101.200.241.211:8083
    version: 0.0.34
  syn_route:
    hosted:
      name: syn_route
      url: http://101.200.241.211:8083
    version: 0.0.8
  syn_base_tools:
    hosted:
      name: syn_base_tools
      url: http://101.200.241.211:8083
    version: 0.0.75
  syn_base_config:
    hosted:
      name: syn_base_config
      url: http://101.200.241.211:8083
    version: 0.1.36
  syn_component_city_list:
#    path: ../../组件/syn_component_city_list
    hosted:
      name: syn_component_city_list
      url: http://101.200.241.211:8083
    version: 0.0.59
  openinstall_flutter_plugin:
    hosted:
      name: openinstall_flutter_plugin
      url: http://101.200.241.211:8083
    version: 0.0.5
  syn_widget_server_update:
    hosted:
      name: syn_widget_server_update
      url: http://101.200.241.211:8083
      version: 0.0.6
 #=======================智家的库=============================
  user:
    hosted:
      name: user
      url: http://101.200.241.211:8083
    version: 0.1.2
  vdn:
    hosted:
      name: vdn
      url: http://101.200.241.211:8083
    version: 0.0.26+1b2021120302

  # syn_map_launcher:
  #   hosted:
  #     name: syn_map_launcher
  #     url: http://101.200.241.211:8083
  #   version: 0.0.7

  message:
    hosted:
      name: message
      url: http://101.200.241.211:8083
    version: 0.0.13

  storage:
    hosted:
      name: storage
      url: http://101.200.241.211:8083
    version: 0.0.8

  share:
    hosted:
      name: share
      url: http://101.200.241.211:8083
    version: 0.0.16

  live:
    hosted:
      name: live
      url: http://101.200.241.211:8083
    version: 0.0.22

  camera_camera:
    hosted:
      name: camera_camera
      url: http://101.200.241.211:8083
    version: 0.0.24+1b2021122101

  photo:
    hosted:
      name: photo
      url: http://101.200.241.211:8083
    version: 0.0.32+1b2021122101

  photo_manager:
    hosted:
      name: photo_manager
      url: http://101.200.241.211:8083
    version: 0.5.18+1b2021122101

  video_player:
    hosted:
      name: video_player
      url: http://101.200.241.211:8083
    version: '1.0.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.4
  build_runner: ^1.9.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.synModule
    iosBundleIdentifier: com.example.synModule

`

**Comment by sigurdm** [comment]
Do you think you can try narrowing it down to a specific package, by removing packages and retrying `pub get`?

**Comment by wangpenghui0612** [comment]
Do you mean the project have too much packages? But all packages are userful, I don't remove anyone.
And, the bigger the project is, the more dependent packages will definitely be

**Comment by sigurdm** [comment]
No - I mean it would be interesting to find out which package causes the problem

**Comment by wangpenghui0612** [comment]
I see what you mean, I'll try

**Comment by wangpenghui0612** [comment]
I can avoid this problem by modifying the version of the dependency package, but now with the upgrade of the version of each dependency package and nesting each other, there is no way to modify a certain version of the dependency, and the fundamental problem cannot be solved. 
I hope you can still help to look at this problem.

**Comment by wangpenghui0612** [comment]
I've found that there are problems with many dependency package versions, not just one. Have you ever met?
 Could it be related to the decompression software of the Windows computer?

**Comment by sigurdm** [comment]
We no longer rely on 7zip (but have our own tar implementation)

Closing as obsolete.
