### ISSUE TITLE
[feature]  child package support

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/pub#3294]
Dependencies in a layered code base are often used in only one layer and should be hidden from the other layers. The conventional wisdom would want one to create multiple packages each with their own pubspec.yaml. However this has a few disadvantages over child packages:

  - You probably want the same lint rules everywhere, this duplicates the linting for every package
  - This creates a bunch of file polution 
  - This creates a nested folder structure that isn't always optimal
  - you might want to share other parts of your application or have general dependencies

Consider a folder structure as such

```
pubspec.yaml
lib    
  - data_sources
     data_sources.dart
  - application
     application.dart
```

Some dependencies should be available in `data_sources` and not in `application` and vice versa.

With this proposal it would be:

```
pubspec.yaml
lib
  - data_sources
     data_sources.dart
     pubspec.child.yaml
  - application
     application.dart
     pubspec.child.yaml
```
The dependencies are still there in the main pubspec.yaml

```yaml
children:
   - data_sources/pubspec.child.yaml
   - application/pubspec.child.yaml
```

So it is recognizable that there are additional dependencies not listed in the main pubspec

Currently :

```
pubspec.yaml
packages
  - data_sources
     lib
        src
            data_sources.dart
     .darttools
     .gitignore
     analysis_options.yaml
     changelog.md
     ...
     pubspec.yaml
  - application
     application.dart
     pubspec.yaml
     .darttools
     .gitignore
     analysis_options.yaml
     ...
```

Admittedly lots of the drawbacks can be overcome. Some of the generated files can be deleted, `analysis_options` can `include` the main one and the folder structure reworked. But those additional steps are less error prone with child packages. Not to mention there are still problems left, you don't have shared dependencies and you can't have interlayer communication. The point of this feature request however is not whether it's currently doable but to make it easier.

**Comment by sigurdm** [comment]
I don't think we are going to do this.

Perhaps look into [mono_repo](https://pub.dev/packages/mono_repo) or [melos](https://pub.dev/packages/melos).
