### ISSUE TITLE
If not generating .packages, then we should delete it

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3296]
If not generating `.packages`, then we should delete it.

If the user has a `.packages` file present and we stop generating it, but don't delete it. Then a user might have a very old `.packages` file sitting around, which will create problems if they delete `.dart_tool/`.

This is probably not a huge issue, since deleting `.dart_tool` will already cause problems as `.packages` doesn't support language versioning. So anything using null-safety should have issues using `.packages`.

**Comment by jonasfj** [comment]
@sigurdm thoughts?

**Comment by sigurdm** [comment]
This is already as implemented: https://github.com/dart-lang/pub/blob/master/lib/src/entrypoint.dart#L225
