### ISSUE TITLE
dart pub get failed with an error ERR : Connection closed before full header was received

### ISSUE THREAD

**Issue by ThaiBinhDuong1011** [dart-lang/pub#3307]
# Environment

- `pub version` or `flutter pub version`: Pub 2.16.0
- OS version: Linux Lenovo-ideapad-310-15ISK 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Are you using the Chinese community mirror or a corporate firewall?

# Problem

```yaml
<copy/paste pubspec.yaml>
```

## --trace output

```
<copy/paste the full output>
```

**Comment by sigurdm** [comment]
Is this persistent (does it repeat every time you try to publish)?

Are you using a mirror? Did you set PUB_HOSTED_URL?

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by marandaneto** [comment]
Running into the same error, https://github.com/getsentry/publish/runs/5723389484?check_suite_focus=true
I could reproduce that locally too, even using `dart pub publish --dry-run`, tried 2 more times and it worked, the connection was stable.

**Comment by sigurdm** [comment]
We don't have enough info to go on here. Closing as stale. Please open a new issue if this is persisting.
