### ISSUE TITLE
Introduce: `dart pub add --dry-run --json`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3333]
We probably want `dart pub add --dry-run --json` to output something along the lines of:
```js
$ dart pub add pem --dry-run --json
{
  // Text representation of the changes made, this includes multiple lines.
  // This may also include warnings of outdated, discontinued, retracted packages, etc.
  // This is intended as human readable text that printed to a log, a debug log, or simply ignored and discarded.
  "summary": "+ meta 1.7.0\n+ pem 2.0.0\n+ petitparser 4.4.0\nWill change 3 dependencies.\n",
  // Changes to be made to files on disk
  "changes": [
    {
      "file": "pubspec.yaml",
      "edits": [
        // compatible with SourceEdit for analysis_server
        {"offset": 100, "length": 0, "replacement": "  pem: ^2.0.0\n"},
      ],
    },
  ],
}
```

Just like other `dart pub` commands this will:
 * Require `pubspec.yaml` and `pubspec.lock` to be located in CWD (or specified using `dart pub add ... --directory path/to/myapp/`),
 * Modify files in `$PUB_CACHE` (notably caching version listings).

**Comment by sigurdm** [comment]
Do we know how `SourceEdit` computes offsets? Is it dart string based (number of utf16 code-units) or byte-offset in the file (or something else entirely?)

**Comment by jonasfj** [comment]
I'm closing this because it's unclear if this will be useful for `analysis_server`. The problem is that even if analysis_server can inject the fix into `pubspec.yaml` and `pubspec.lock`, it won't be able to patch `.dart_tool/package_config.json`, or download package files into `$PUB_CACHE`. Thus, the UX of this through `analysis_server` won't be great.

Anyone who needs this feel free to reopen.

**Comment by jonasfj** [comment]
Hmm, on second thought if the IDE only updates `pubspec.yaml`, then the IDE should encourage the user to run `dart pub get` because modification-times has changed.

**Comment by jonasfj** [comment]
@pq what is the time budget available for generating a quick-fix? How fast would `dart pub add --json --dry-run` have to be, for this to be an option?

**Comment by sigurdm** [comment]
@pq Do we still think this is useful?

**Comment by pq** [comment]
Great question. I'm not sure!

/fyi @bwilkerson @srawlins who can chime in on current/planned DAS work and where this might fit in

**Comment by srawlins** [comment]
I'm unaware of any use for this. Sorry for the delay.

**Comment by DanTup** [comment]
I opened a dupe at https://github.com/dart-lang/pub/issues/4712

The use case here was getting the version that `pub add` would use, but without pub modifying the file on disk because there might be unsaved changes in the IDE, so we want to add the package in the edit buffer.

**Comment by sigurdm** [comment]
What would be a good output format?

**Comment by DanTup** [comment]
For the use case I noted above, just the version numbers that would be added for the packages would be enough.

The idea up top of returning the replacements as `SourceEdit`s is interesting, but wouldn't work for the case where there are unsaved changes in the file in the editor (the offsets might be incorrect). It's also true that the resolved version numbers could also be affected by unsaved changes, but I think that one we'd just have to accept.

The specific format isn't so important, as long as we can get the version number so we could update the `dependencies` list. It's likely we'd only use it for one package a time, but if the command supports multiple then the response should ofc contain a map or list of package names/versions.
