### ISSUE TITLE
pub fails to rename directory

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub#3334]
# Environment

- `pub version` or `flutter pub version`: Dart SDK version: 2.17.0-179.0.dev (dev) (Sat Mar 5 02:12:06 2022 -0800) on "windows_x64"
- OS version: Windows 10.0.19042.1566
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

On a Google Windows workstation, `pub` intermittently fails to download dependencies:

```
[C:\src\win32] dart pub get
Resolving dependencies...
+ _fe_analyzer_shared 36.0.0
+ analyzer 3.3.1
...
+ winmd 1.0.26
+ yaml 3.1.0
Downloading winmd 1.0.26...
Downloading pub_semver 2.1.1...
Pub failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
```

I suspect this is because of a race condition with virus scanning or other malware protection. 

I see other examples of this from customers outside Google. 

I suspect it may be worth adding a wait/retry to this step to give a virus scanner time to execute and unlock the file; alternatively, there may be a non-blocking way to do this (e.g. call `WaitForSingleObject` to ensure that the file handle isn't locked before renaming).

**Comment by mit-mit** [comment]
https://github.com/dart-lang/pub/issues/1798 looks related

**Comment by mit-mit** [comment]
cc @jonasfj, @timsneath might have a repro of this, how do we proceed?

**Comment by sigurdm** [comment]
> I suspect it may be worth adding a wait/retry to this step to give a virus scanner time to execute and unlock the file;

As a matter of fact when you see that error that means the rename has been retried with delays:
https://github.com/dart-lang/pub/blob/master/lib/src/io.dart#L367

> e.g. call WaitForSingleObject to ensure that the file handle isn't locked before renaming).

That might be worth looking into.

The pub team has very little windows experience, and for multiple reasons we would far prefer staying within dart:io. That said, if we could solve these issues we should at least have a go at it.

**Comment by jonasfj** [comment]
We don't know that this is anti-virus, it could be anything that's messing with our files.
That said, my understanding is that these are generally temporary folders that we create, add files to and then are unable to atomically move.
So if it's not anti-virus (or a virus, hehe) that is messing with the system, then it's hard to know what is going on. But maybe there is a way to lock temporary directories in Windows, or create them in ways that prevents others from using them until we're done.

**Comment by mit-mit** [comment]
Given we (Tim) have a repro, could we not experiment with a "wait a bit and then try again" solution for the rename?

**Comment by sigurdm** [comment]
Tim, could you send us a way to repro? Then we will try to see if we can find a better solution (possibly just more retries...)

**Comment by timsneath** [comment]
Will reach out to you offline, since I'm using Google internal infra.

**Comment by sigurdm** [comment]
@timsneath I have landed a simple fix (simply have more retries before giving up).

Are you still able to reproduce this?

**Comment by timsneath** [comment]
I’m sorry: I haven’t reproduced it recently. But that’s likely because I’ve got exceptions for various Google security / malware software in the meantime
