### ISSUE TITLE
I use this command "flutter pub get"  and got this error "HTTP error 404: Not Found"

### ISSUE THREAD

**Issue by FLEasy** [dart-lang/pub#3338]
Running "flutter pub get" in ms_notes_pro...
HTTP error 404: Not Found
package:pub/src/http.dart 231:5                    _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 379:18                   _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 52:24   _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 803:22          BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 844:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 800:5           BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 639:7           BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 484:35             Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 479:12             Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 297:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
HTTP error 404: Not Found
package:pub/src/http.dart 231:5                    _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 379:18                   _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 52:24   _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 803:22          BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 844:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 800:5           BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 639:7           BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 484:35             Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 479:12             Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 297:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

**Comment by FLEasy** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] VS Code (version 1.65.2)

**Comment by FLEasy** [comment]
export FLUTTER_HOME=/Users/fl/Documents/workspace/flutter
export PATH=${PATH}:$FLUTTER_HOME/bin
export PATH=${PATH}:$FLUTTER_HOME/bin/cache/dart-sdk/bin
export ANDROID_HOME="/Users/fl/Library/Android/sdk"
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

**Comment by EriconYu** [comment]
睡了一觉，醒来发现没法编译了，这事你说跟谁说理去

**Comment by EriconYu** [comment]
我读了下源码，找到个方案，把环境变量改成下面的就行了 :
`export PUB_HOSTED_URL=https://pub.dev `

**Comment by FLEasy** [comment]
> 

你也遇到了这样的问题呀  我去试试看 谢谢~  我现在用的是搞成了 腾讯的一个镜像  发现可以了
export PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub
export FLUTTER_STORAGE_BASE_URL=https://mirrors.cloud.tencent.com/flutter

**Comment by AlexV525** [comment]
可否 -v 看一下详细内容？

**Comment by sigurdm** [comment]
Sounds like this is a problem with the Chinese community mirror.
@chenglu might know something

**Comment by 549064368** [comment]
> export PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub
> export FLUTTER_STORAGE_BASE_URL=https://mirrors.cloud.tencent.com/flutter

我改成腾讯，还是不行

**Comment by FLEasy** [comment]
@AlexV525 好的我去试一下

**Comment by chenglu** [comment]
提示错误之后可能要运行一下命令 `dart pub --trace get --no-precompile` 能看到是在获取哪个 package 的时候出错，或者是其他详细报错信息，麻烦 @FLEasy @549064368 也贴一下相关信息吧，辛苦啦，谢谢你们的反馈和时间！

**Comment by FLEasy** [comment]
@chenglu 当时执行了dart pub --trace get --no-precompile 但是没有效果 当时报的错误 也是 404那个错误

**Comment by 549064368** [comment]
> 

Downloading package_info_plus_web 1.0.4...
HTTP error 404: Not Found
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace pub --trace get --no-precompile

**Comment by 549064368** [comment]
> 提示错误之后可能要运行一下命令 `dart pub --trace get --no-precompile` 能看到是在获取哪个 package 的时候出错，或者是其他详细报错信息，麻烦 @FLEasy @549064368 也贴一下相关信息吧，辛苦啦，谢谢你们的反馈和时间！
Downloading package_info_plus_web 1.0.4...
HTTP error 404: Not Found
package:pub/src/http.dart 234:5            _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 382:18           _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 637:22  BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 799:12             withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 634:5   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 478:7   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 451:35     Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 446:12     Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 269:7      Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace pub --trace get --no-precompile

**Comment by chenglu** [comment]
收到，看来也是 `package_info_plus_web` 这个 package 报错了，谢谢 @549064368 反馈。

**Comment by FLEasy** [comment]
@chenglu 我刚刚切回到 
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
发现已经ok了 flutter pub get 也已经没有问题

**Comment by 549064368** [comment]
> 收到，看来也是 `package_info_plus_web` 这个 package 报错了，谢谢 @549064368 反馈。

那我现在要怎么处理，突然见项目就跑不起来了

**Comment by chenglu** [comment]
@549064368 抱歉给您带来不便，在中国镜像上重新同步了这个 package 解决了，麻烦再切回来试试看。

**Comment by sigurdm** [comment]
Closing for now

**Comment by liconlin1997** [comment]
HTTP error 404: Not Found
package:pub/src/http.dart 231:5                    _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 379:18                   _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 52:24   _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 803:22          BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 844:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 800:5           BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 639:7           BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 484:35             Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 479:12             Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 297:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
