### ISSUE TITLE
flutter HTTP error 404: Not Found

### ISSUE THREAD

**Issue by 1963828747** [dart-lang/pub#3339]
HTTP error 404: Not Found
package:pub/src/http.dart 232:5                    _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 380:18                   _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 50:24   _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 130:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 804:22          BoundHostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 845:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 801:5           BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 640:7           BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 484:35             Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 479:12             Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 297:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

**Comment by CodeCsir** [comment]
I had the same problem

**Comment by sigurdm** [comment]
@1963828747 and @CodeCsir can you give us more details about your setup?

What version of dart are you using? what os?

Can you share your pubspec.yaml?

Are you using a mirror?

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by 1963828747** [comment]
@sigurdm Thanks, I have solved the problem, it was caused by a plugin.
#  simple_tooltip: ^1.0.0
@CodeCsir You can try to annotate some plugins to see

**Comment by szakarias** [comment]
Please reopen if the problem reoccurs.
