### ISSUE TITLE
Support for backend proxy

### ISSUE THREAD

**Issue by wytrych** [dart-lang/pub#3376]
Same as https://github.com/flutter/flutter/issues/51530 but maybe this repository is a better place for such a request? In short - run a configurable proxy server for development to allow requests against different backends. It's standard practice with modern frameworks and is built into webpack for example.

**Comment by sigurdm** [comment]
Can you elaborate what exactly you are asking for?
Give an example of what it might look like?

**Comment by wytrych** [comment]
It's exactly what Webpack has: https://webpack.js.org/configuration/dev-server/#devserverproxy

The issue is that when doing local development you run into CORS issues if you run in the browser and want to make requests against a backend either running locally on a different port or a production backend. The webpack solution solves it nicely with a simple config.
