### ISSUE TITLE
pub global activate uses excessive amounts of cpu and memory

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3387]
dart 2.16.2 
linux.
I have a package dcli_scripts which contains a grab bag of scripts that I use in my development environment.

The package contains a large no. of executables (30 ish).

The problem is when I run 'dart pub global activate dcli_scripts' it will grind a reasonable configure machine to a halt.

The problem is that pub appears to try and compile every program at once.

Given that a dart compile can easily take in excess of 1GB this would seem to be fairly bad behaviour on the part of the pub command.

As an example we are running a 16GB 2 core box (ubuntu 21.04).
Trying to global active the above package on this box results in a 50+ load average and the box runs out of memory (with nothing else running).
On a box with 20 cores and 64GB or ram it used 24GB with a load average of 24.

This is also extremely problematic on rpi devices with memory constrained to 4gb.

I would like to see the pub command limit the no. of concurrent compiles.
Perhaps this should be limited based on the amount of memory and the no. of cores.
Perhaps the max of one compile per 2GB of ram and no. of cores - 1.

**Comment by sigurdm** [comment]
I think limiting number of concurrent compiles is reasonable.
