### ISSUE TITLE
Pub lish should run `[dart|flutter] analyze`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#3391]
It would be a nice extra sanity check if `pub lish` ran analysis on the project, and gave a warning if there were any diagnostics.

This would have caught a mistake I made today, where I published a version of `test_core` (after removing dependency overrides on the local version of `test_api`). I thought there were no changes in test_api that test_core depended on, and so I hadn't published a new version of that, but when I removed the override it did in fact cause some analysis errors. I didn't notice it in time, and pub didn't alert me, so I had to retract the version. Super glad I can retract versions now though!

**Comment by sigurdm** [comment]
I think this is a good idea. Surprised we don't already do this.
