### ISSUE TITLE
Github Downloaded Project Class 'String' has no instance method 'containsKey' Error

### ISSUE THREAD

**Issue by algorr** [dart-lang/pub#3398]
Hi everyone, 
I have an issue about project that is downloaded from my own github. After a while I developed the project, I download the all project from github desktop application and try to open in VsCode or Android Studio. After when I start to compile or debug I take an issue like that above:

Resolving dependencies...
Class 'String' has no instance method 'containsKey'.
Receiver: "dependency"
Tried calling: containsKey("version")
dart:core                                                        Object.noSuchMethod
package:pub/src/lock_file.dart 130:24                            LockFile._parse.<fn>
dart:collection                                                  MapMixin.forEach
package:pub/src/lock_file.dart 128:22                            LockFile._parse
package:pub/src/lock_file.dart 80:21                             new LockFile.load
package:pub/src/entrypoint.dart 103:35                           Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 97:42                            Entrypoint.lockFile
package:pub/src/entrypoint.dart 286:21                           Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 280:68                           Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                                  progress
package:pub/src/entrypoint.dart 280:26                           Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                           GetCommand.runProtected
package:pub/src/command.dart 183:45                              PubCommand.run.<fn>
package:pub/src/command.dart 183:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 183:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:dartdev/dartdev.dart 231:30                              DartdevRunner.runCommand
package:args/command_runner.dart 119:25                          CommandRunner.run.<fn>
dart:async                                                       new Future.sync
package:args/command_runner.dart 119:14                          CommandRunner.run
package:dartdev/dartdev.dart 66:29                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\tetrax\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.

If you help about this issue,  I would be grateful.
PS: I tried to pass channel beta but it not working...

**Comment by sigurdm** [comment]
It seems your pubspec.lock file is broken. Try deleting it and run pub get again.

But of course pub should not fail like this with a broken pubspec.lock, so this is indeed a bug.
