### ISSUE TITLE
Cannot pub global activate a package in a subfolder of a git repository if repository also has a pubspec.yaml in its root

### ISSUE THREAD

**Issue by acoutts** [dart-lang/pub#3403]
# Environment

- `pub version` or `flutter pub version`: Dart SDK version: 2.17.0-265.0.dev (dev) (Fri Apr 1 10:21:19 2022 -0700) on "macos_arm64"

- OS version: macOS 12.3.1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem
The melos repository has a pubspec.yaml for an unpublished package in its root, then there are 2 published packages in the `packages/` folder.

I want to install `melos` from a remote git repository:
```
dart pub global activate --source git https://github.com/bottlepay/melos.git --git-path=packages/melos --git-ref=b0dbf8764aa63c5253d7704013541608876a60b6
```

## Expected behavior

It should install the melos package located inside the `packages/melos` folder of the git repository specified.

## Actual behavior

Instead it prints this error:
```
Error on line 1, column 7: "name" field doesn't match expected name "melos_monorepo".
  ╷
1 │ name: melos
  │       ^^^^^
  ╵
```
because the `pubspec.yaml` of the repository root has `melos_monorepo` as the package name but the one i actually want to install is located in `packages/melos` where the package name is `melos`.

**Comment by osaxma** [comment]
Hey @acoutts 
Were you able to find any workaround for this? I ran into the same exact issue today...

**Comment by acoutts** [comment]
No workaround yet sadly.
