### ISSUE TITLE
Race condition in concurrent pub git clone

### ISSUE THREAD

**Issue by acoutts** [dart-lang/pub#3404]
# Environment

- `pub version` or `flutter pub version`:
```
Flutter 2.13.0-0.0.pre.366 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0b97874895 (4 weeks ago) • 2022-04-01 21:20:01 -0400
Engine • revision 801d8c530f
Tools • Dart 2.17.0 (build 2.17.0-265.0.dev) • DevTools 2.12.1
```

- OS version: macOS 12.2.1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

I have a monorepo with several packages, using melos. I upgraded to melos 2.0 which introduced concurrent pub getting. The problem is several of my packages share the same external git dependency and the very first time I run `melos bootstrap` in a fresh repository it throws the following error:
```
Could not find a file named "pubspec.yaml" in "/builds/M5hecXxM/3/bottle/pay/app/.pub-cache/git/mockito-aa841a3c3762afab2c31486677015ff0a9abc2cf".
BootstrapException: Failed to install.: common at /builds/M5hecXxM/3/bottle/pay/app/packages/common.
```

When i run `melos bootstrap` a second time, it finishes without an error. It seems like there is some kind of race condition with the pub command related to this shared git dependency which causes the pub gets to fail the first time but work the second time.

## Expected behavior

Should be able to pub get in parallel for git dependencies.

## Actual behavior

I have to do it twice to succeed.

## --trace output

```
<copy/paste the full output>
```

**Comment by jonasfj** [comment]
It's not entirely clear what is going wrong here. If someone wants to create a minimal example using only `dart pub get` and a clean `PUB_CACHE` folder that would be preferable. Or even better make a test case for pub that reproduces the error with some confidence (yeah, it's probably somewhat intermittent).

If we know for sure what bits fail, we can try to make a solution.

One option is cloning to a temporary folder and moving atomically, but this has a tendency to cause problems for users on Windows anti-virus software installed.
So if it's possible that there is some locking mechanism in `git` we're not using correctly, then we could try to use that.

It also possible we should make a temporary folder + move and copy if moving fails.

**Comment by Gustl22** [comment]
FYI @jonasfj don't know if it helps but I can reliably reproduce with this [scenario](https://github.com/flutter/flutter/issues/103981) with this [example](https://github.com/Gustl22/flutter_platform_test). But only with `flutter pub get`, not with `dart pub get`.

**Comment by ivan-dubovenko-m10** [comment]
- `flutter clean`
- `pub cache clean`
- `dart pub global activate melos`
```
command:
  bootstrap:
    runPubGetInParallel: false
```

Does not resolve the issue.

> Could not find a file named "pubspec.yaml" in ".../mobile-flutter/packages/features/request_funds".

After pulling repo, the package `/features/request_funds` was deleted from the project. But melos still looking for it.  

melos clean also fails with the same error. Actually I cant run any melos command in project dir, even `--version`, as it fails with this error

```
melos --version
3.0.1

dart --version
Dart SDK version: 2.19.5 (stable)

flutter --version
Flutter 3.7.8 • channel stable 
```

flutter pub get also fails:

```
flutter pub get
Running "flutter pub get" in mobile-flutter...
Warning: pubspec.yaml has overrides from pubspec_overrides.yaml
Resolving dependencies... 
Could not find a file named "pubspec.yaml" in "...mobile-flutter/packages/features/request_funds".
pub get failed
```

**Comment by ivan-dubovenko-m10** [comment]
https://github.com/dart-lang/pub/issues/3404#issuecomment-1534088707

Deleting `pubspec_overrides` in project root resolve it.

**Comment by samdeane** [comment]
I am seeing what appears to be a similar race condition. We have one external git dependency, used by several packages.

When we run `melos bootstrap` it fails on CI with one of a number of errors, all of which appear to be git related, and likely caused by simultaneous access. Sometimes it's a failure to get a lock, sometimes a cache issue. 

## Example Failure

<img width="833" alt="image" src="https://github.com/dart-lang/pub/assets/206306/16284fcc-4f92-4edf-a68f-6ea7c89afea8">

## Versions

> flutter --version                                                                           (deploy/internal/client)
Flutter 3.13.6 • channel [user-branch] • unknown source
Framework • revision ead455963c (5 weeks ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

> dart run melos --version                                                                    (deploy/internal/client)
3.2.0

**Comment by samdeane** [comment]
I hadn't discovered the `runPubGetInParallel` setting - that might do the trick. I will report back...
