### ISSUE TITLE
Allow pubspec.yaml to have shared content (add 'include:' field)

### ISSUE THREAD

**Issue by petro-i** [dart-lang/pub#3405]
Hi,

We have complex multi-mono :) repo dependency configuration. Currently there is the problem exists to update deps versions and overrides across multiple files every time we have to update our dependencies, some more config params are duplicated also. 

My proposal is to add new field/parameter to pubspec.yaml - 'include', to have possibility to share pubspec.yaml file content across the bunch of the pubspec files.

Requirements:
- relative paths should be relative to location of the included file
- possibility to reference to remote file (git)

Please pay attention that #2161 doesn't resolve this problem. 

As I see, the solution should be some kind of copy-paste of the 'include'  field we already have in 'analysis_options.yaml' files with additional functionality to specify git file (it is important).

**Comment by sigurdm** [comment]
I don't think we want to do this, as generally we want the pubspec.yaml to be able to stand on its own.

If publishing a package with a pubspec.yaml that includes '../shared_pubspec_deps.yaml' should that file be published too? or inlined? Both seems a bit weird.

**Comment by sigurdm** [comment]
I'm closing for now. Please follow up with comments if you think we should reconsider.

**Comment by petro-i** [comment]
Hi, 
it is really disappointing that you closed this ticket.

Please consider that:
- there is `publish_to:` field already in pubspec.yaml exists, it can serve as flag whether it is allowed  to have `include:` in the file
- for enterprise projects, I think, it is usual to have `publish_to: "none"` defined and use all deps from git.
- for enterprise projects it is also normal to have wide dependency system with similar dependencies
- there is no good private "pub dev" software in the moment, so it will be usual to have private deps in the git for enterprise projects for visible future.

**Comment by sigurdm** [comment]
Ok, I'll reopen for another round of consideration - I'm still not too keen on this mechanism. But maybe we can think of another way of serving the use case of "a bunch of git packages all depending on each other"

I don't think it's that hard to make a script that updates any duplicated information. 

> there is no good private "pub dev" software in the moment, so it will be usual to have private deps in the git for enterprise projects for visible future.

Just FYI there are companies providing hosted solutions: https://dart.dev/tools/pub/custom-package-repositories#dart-package-repositories-as-a-service.

@jonasfj WDYT

**Comment by jonasfj** [comment]
I don't understand the use-case. Please outline example pubspecs for the two scenario..
 * (A) Example of what pubspecs might look now with duplication?
 * (B) Example of how `include` will allow deduplication?

Each example can easily contain 2-3 `pubspec.yaml` files... Just publish a a single comment with 2 sections or gist... Not important. By please illustrate what fields you imagine you want to `include`.


--------------------------------------


My two cents is that this is fairly use-case specific. In many cases this can be solved with a path-dependency on a single shared package that depends on all your dependencies (and possibly re-exports files you want to use). It could also be solved with some simple tooling that generates `pubspec.yaml` from a configuration file, or modifies `pubspec.yaml` using `package:yaml_edit`.

I can see it being nice in some mono_repos, but I'm not convinced the tooling for this should be delivered by `dart pub`.

**Comment by DenisShakinov** [comment]
> I don't understand the use-case. Please outline example pubspecs for the two scenario..
> 
> * (A) Example of what pubspecs might look now with duplication?
> * (B) Example of how `include` will allow deduplication?
> 
> Each example can easily contain 2-3 `pubspec.yaml` files... Just publish a a single comment with 2 sections or gist... Not important. By please illustrate what fields you imagine you want to `include`.
> 
> My two cents is that this is fairly use-case specific. In many cases this can be solved with a path-dependency on a single shared package that depends on all your dependencies (and possibly re-exports files you want to use). It could also be solved with some simple tooling that generates `pubspec.yaml` from a configuration file, or modifies `pubspec.yaml` using `package:yaml_edit`.
> 
> I can see it being nice in some mono_repos, but I'm not convinced the tooling for this should be delivered by `dart pub`.

I guess the point is to have a single declaration point for all common dependencies versions. Imagine we have such a multipackage project:

|__root
|   |__common
|   |   |__lib
|   |   |    |__dependencies_versions.yaml
|   |   |__pubspec.yaml
|   |__mypackage1
|   |   |__lib
|   |   |__pubspec.yaml
|   |__mypackage2
|   |   |__lib
|   |   |__pubspec.yaml
|   |__mypackage3
|   |   |__lib
|   |   |__pubspec.yaml
|   |__lib
|   |__pubspec.yaml

and have `meta` dependency in each package. instead of writing `meta: ^1.8.0` in every single `pubspec.yaml` file of all packages, we could have a file like `dependencies_versions.yaml` in `common/lib` folder and store all version aliases in it:

# common/lib/dependencies_versions.yaml

`meta_version: &meta_version ^1.8.0`

then for example in `mypackage1` and `mypackage2`

# mypackageN/pubspec.yaml

```
include: package:common/dependencies_versions.yaml
...
dependencies:
  meta: *meta_version
```

when `meta` 1.9.0 is available we simply could modify its version in `dependencies_versions` instead of modifying all pubspecs in the project.

**Comment by jonasfj** [comment]
> and have meta dependency in each package. instead of writing `meta: ^1.8.0` in every single pubspec.yaml file of all packages

Each package should write the constraint on `meta` that it has. If a package only uses early features, then it could reasonably choose to have a lax constraint on `meta`.

The way dependencies work each app will only have one version of `meta` anyways.


---------------------

If you really want to synchronize constraints you can:
 * Use a single `common` package that has dependencies and re-exports everything you need to use.
 * Use a script to synchronize dependency constraints `dart pub add` can be used to programmatically modify `pubspec.yaml`.

I think that it's much simpler to have a script that this does, than `include:...` and yaml references. References makes a lot of stuff hard to do. Our programmatic modification of `pubspec.yaml` easily stops working if references are involved. And error messages are generally worse.

In general, I think it's better to keep it simple -- a little duplication or an ugly search/replace script is probably better than complicated `include: ..` logic.

Notably, if we `include` then we easily end up having to support multiple includes. And what if the file you're including is outside the package directory as in your case?

> `include: package:common/dependencies_versions.yaml`

So versions selected depends on the version of `common` selected. That's a huge complication to the solver, and would make resolution errors extremely hard to explain. Suddenly, we have to explain that all versions of `common` caused all versions of your package to not be able to resolve... And if in some cases it was `meta` and some cases it was `foo` that cause this to happen the tree explaining this might become large.

I suggest we try to keep things simple. Flutter gets away with programmatically editing `pubspec.yaml` to pin some dependencies, they do this using a script, that seems like a reasonable approach -- IMO, most mono-repos won't need this.
