### ISSUE TITLE
Host packages on Gitea and Gitlab

### ISSUE THREAD

**Issue by trymeouteh** [dart-lang/pub#3410]
The ability for a developer to host the source code of their package on a gitea instance or a gitlab instance and not be restricted to github.

I understand packages can come from Github or gitlab.com, however I am not sure if it is possible have packages from any gitlab or gitea instance.

**Comment by jonasfj** [comment]
`git`-dependencies must have a `url` that can be cloned with `git clone`. You can host it where ever you like.

You can use any protocol supported by `git` and your server, you authenticate with `git`, so can even authenticate with SSH keys, etc.. `dart pub` will shell out to `git` so anything that works with `git clone` should work (not sure if custom schemes work, but gitea and gitlab should work, if you've configured your server and client correctly).

See: https://dart.dev/tools/pub/dependencies#git-packages

**Comment by trymeouteh** [comment]
Are there any examples of packages on pub.dev that are from a gitea instance?

**Comment by sigurdm** [comment]
How would we know? We just know the repository url, not the underlying service.
