### ISSUE TITLE
Error when running `pub get` concurrently on Windows

### ISSUE THREAD

**Issue by blaugold** [dart-lang/pub#3420]
# Environment

- `pub version` or `flutter pub version`: 2.17.0
- OS version: Microsoft Windows Server 2019
- Are you using the Chinese community mirror or a corporate firewall? No.

# Problem

When running `dart/flutter pub get` concurrently, some invocations fail with the following error:

```
Rename failed, path = 'C:\hostedtoolcache\windows\flutter\.pub-cache\_temp\dirb7266b85' (OS Error: Cannot create a file when that file already exists.
, errno = 183)
```

I have only observed this on Windows and in CI. It seems to me that when the pub cache is empty and multiple `pub get` invocations try to place a downloaded package into the cache, they step on each other's toes.

There are only dependencies hosted on `pub.dev` and some path dependencies involved.

**Comment by sigurdm** [comment]
Maybe we need to add a check for error-code=183 here:

https://github.com/dart-lang/pub/commit/5bda798cd0543c51840823bc0d671beffba233bc#diff-a3aded494b57aa0e29fdca3db60a47a5d091184f22fcd8b8a62f6d4ef5d2d807R470

**Comment by blaugold** [comment]
Here are the [logs](https://github.com/dart-lang/pub/files/8680869/bootstrap.zip) for a run where the error occurs.
In the first half of the file, lines are prefixed with the package for which `pub get` is being executed. In the second half, all the output from `pub` is repeated for packages where `pub get` failed.

> Maybe we need to add a check for error-code=183 here:

That seems like the right idea to me. In the logs, I can see `shelf_web_socket-1.0.1` for example being downloaded and installed into the cache by multiple instance of `pub get`, with one failing with the error.

**Comment by sigurdm** [comment]
I believe this was fixed by https://github.com/dart-lang/pub/pull/3426.

Please reopen if this is still an issue.
