### ISSUE TITLE
GetX

### ISSUE THREAD

**Issue by elBelo94** [dart-lang/pub#3444]

**Comment by elBelo94** [comment]
hola necesito ayuda trato de correr una animacion con rive y no funciona y tampoco me cambia al modo oscuro. Me lanza estos warning cuando compilo la aplicacion

Launching lib\main.dart on SM G950U in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
/C:/development/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_render_box.dart:190:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.scheduleFrameCallback(_frameCallback) ?? -1;
                         ^
/C:/development/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_core/state_machine_controller.dart:220:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/C:/development/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/controllers/one_shot_controller.dart:40:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/development/flutter/packages/flutter/lib/src/widgets/binding.dart').
        : WidgetsBinding.instance?.addPostFrameCallback((_) => onStop?.call());

                         ^

Este es el codigo de mi vista Setting

import 'package:flutter/material.dart';
//import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:rive/rive.dart';

class setting_Page extends StatefulWidget {
  @override
  State<setting_Page> createState() => _setting_PageState();
}

class _setting_PageState extends State<setting_Page> {
  //late Artboard _riveArtboard;
  late RiveAnimationController _controller;
  bool _isDarkTheme = false;

  @override
  void initState() {
    super.initState();
    _controller = SimpleAnimation('to_light');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Settings'),
      ),
      body: SafeArea(
        child: Column(
          // ignore: prefer_const_literals_to_create_immutables
          children: [
            Padding(
              padding: const EdgeInsets.all(32),
              child: Icon(Icons.settings, size: 144, color: Colors.grey),
            ),
            ListTile(
              leading: Icon(Icons.info_outline),
              title: Text('Version 1.0.0'),
            ),
            Divider(),
            ListTile(
              leading: Icon(Icons.shop),
              title: Text('About Us'),
            ),
            Divider(),
            Flexible(
              child: Center(
                child: RiveAnimation.asset('assets/animations/git_theme.riv',
                    controllers: [_controller],
                    // Update the play state when the widget's initialized
                    onInit: (_) => setState(() {})),
              ),
            ),
            Switch(
                value: _isDarkTheme,
                onChanged: (val) {
                  setState(() {
                    _isDarkTheme = val;
                  });
                  if (_isDarkTheme) {
                    Get.changeTheme(ThemeData.dark());
                    _controller = SimpleAnimation('to_dark');
                  } else {
                    Get.changeTheme(ThemeData.light());
                    _controller = SimpleAnimation('to_light');
                  }
                })
          ],
        ),
      ),
    );
  }
}

**Comment by sigurdm** [comment]
This issue tracker is for problems with the pub client.

Open issues with packages on their own issue tracker.
