### ISSUE TITLE
pub get failed (255; .) - no log found in path below 

### ISSUE THREAD

**Issue by kenaitian** [dart-lang/pub#3463]
/Users/ken/Development/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in firebase_auth-3.3.19...            
Null check operator used on a null value
package:pub/src/entrypoint.dart 157:60                           Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 100:21                           Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 97:42                            Entrypoint.lockFile
package:pub/src/entrypoint.dart 286:21                           Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 280:68                           Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                                  progress
package:pub/src/entrypoint.dart 280:26                           Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                           GetCommand.runProtected
package:pub/src/command.dart 183:45                              PubCommand.run.<fn>
package:pub/src/command.dart 183:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 183:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:pub/src/command_runner.dart 174:24                       PubCommandRunner.runCommand
package:pub/src/command_runner.dart 159:20                       PubCommandRunner.run
package:dartdev/dartdev.dart 45:56                               runDartdev
/opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    /Users/ken/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
.
pub get failed (255; .)
Process finished with exit code 255

**Comment by jonasfj** [comment]
What version of Flutter are you using `flutter --version` output?

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by sigurdm** [comment]
Yeah - I was able to reproduce:
```
$ cd ~/.pub-cache/hosted/pub.dartlang.org/package_config-1.9.3/
 ~/.p/h/p/package_config-1.9.3$ flutter pub pub get
Building flutter tool...
Resolving dependencies...
Null check operator used on a null value
package:pub/src/entrypoint.dart 159:60                         Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 102:21                         Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 99:42                          Entrypoint.lockFile
package:pub/src/entrypoint.dart 294:21                         Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                                progress
package:pub/src/entrypoint.dart 288:26                         Entrypoint.acquireDependencies
package:pub/src/command/get.dart 55:22                         GetCommand.runProtected
package:pub/src/command.dart 189:45                            PubCommand.run.<fn>
dart:async                                                     new Future.sync
package:pub/src/utils.dart 109:12                              captureErrors.wrappedCallback
dart:async                                                     runZonedGuarded
package:pub/src/utils.dart 126:5                               captureErrors
package:pub/src/command.dart 189:13                            PubCommand.run
package:args/command_runner.dart 209:27                        CommandRunner.runCommand
package:pub/src/command_runner.dart 176:24                     PubCommandRunner.runCommand
package:pub/src/command_runner.dart 161:20                     PubCommandRunner.run
package:dartdev/dartdev.dart 45:56                             runDartdev
/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    /usr/local/google/home/sigurdm/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
.
pub finished with exit code 255
```

**Comment by Anil8000** [comment]
> What is your current working directory? I think this might happen if you run from a directory inside the pub cache...

it is working for me, Thanks!
