### ISSUE TITLE
Support --color[=WHEN]

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3465]
Similar to other CLI tools:
```
--color[=WHEN]         colorize the output; WHEN can be 'always' (default if omitted), 'auto', or 'never'; more info below
```

hence:
 * `--color`, means force colors,
 * `--color=always`, means force colors,
 * `--color=never`, means no colors,
 * `--color=auto`, means no color if `NO_COLOR` is defined (https://github.com/dart-lang/pub/issues/3464), no color if terminal not detected or terminal doesn't support color.

**Comment by sigurdm** [comment]
This is hard to implement with the current package:args. There is no way to have an option taking no argument. ie. `--color`.

Also `dart pub outdated` already allows for `--color` and `--no-color`. Let's use that instead:

* `--color` means force colors
* `--no-color` means no colors
* Flag not given means do terminal detection (unless `$NO_COLOR`).
