### ISSUE TITLE
 'Unresolved path packages' inspection on Project.

### ISSUE THREAD

**Issue by Sriraksha16** [dart-lang/pub#3477]
Hi,  I'm newbie to Flutter and I'm upgrading old project, while upgrading I'm facing these problems.
Any idea how to resolve this? 
Here i attached the image of this issue in **pubspec.yaml**, Suggestions are valuable.
version: 0.6.5+4.

<img width="1440" alt="Screenshot 2022-06-29 at 14 23 33" src="https://user-images.githubusercontent.com/98327940/176435888-36d95ab7-f0d2-4dc4-9e46-fa54b9327229.png">

And also I'm getting these problems which I attached screenshot below, I followed these steps- https://flutter.dev/go/android-plugin-migration. but nothing changes occurred.  Please can any one help me with this?
<img width="1440" alt="Screenshot 2022-06-29 at 14 37 50" src="https://user-images.githubusercontent.com/98327940/176439033-828ceccd-5f47-42df-abcc-be4df97b75a3.png">

**Comment by Sriraksha16** [comment]
Hi sigurdm, 
Thank you for your kind response. 

1._**Flutter Version**_
Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (8 days ago) • 2022-06-22 11:34:49 -0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2

2._**flutter pub outdated**_
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current   Upgradable  Resolvable  Latest   

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies: 
async                     *2.8.2    *2.8.2      *2.8.2      2.9.0    
characters                *1.2.0    *1.2.0      *1.2.0      1.2.1    
clock                     *1.1.0    *1.1.0      *1.1.0      1.1.1    
material_color_utilities  *0.1.4    *0.1.4      *0.1.4      0.1.5    
meta                      *1.7.0    *1.7.0      *1.7.0      1.8.0    
path                      *1.8.1    *1.8.1      *1.8.1      1.8.2    
source_span               *1.8.2    *1.8.2      *1.8.2      1.9.0    
string_scanner            *1.1.0    *1.1.0      *1.1.0      1.1.1    
term_glyph                *1.2.0    *1.2.0      *1.2.0      1.2.1    

transitive dev_dependencies:
fake_async                *1.3.0    *1.3.0      *1.3.0      1.3.1    
matcher                   *0.12.11  *0.12.11    *0.12.11    0.12.12  
test_api                  *0.4.9    *0.4.9      *0.4.9      0.4.11   
all dependencies are up-to-date.


3. _**pubspec.yaml**_
description: Location Sharing.

version: 1.1.8+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
 //Firebase
  firebase_dynamic_links: ^4.2.6
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  cloud_functions: ^3.2.17
  firebase_analytics: ^9.1.10

  get_it: ^7.2.0
  rxdart: ^0.27.4
  location: ^4.4.0
  google_maps_flutter: ^2.1.8
  provider: ^6.0.3
  timeago: ^3.2.2
  intl: ^0.17.0
  share: ^2.0.4
  url_launcher: ^6.1.4
  device_info: ^2.0.3
  geolocator: ^9.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/Yoo_Icon.png"

flutter:

  uses-material-design: true

//To add assets to your application, add an assets section, like this:

  assets:
   - images/icon.png
   - images/2xicon.png
   - images/qr-code.png

**Comment by Sriraksha16** [comment]
**Here is the  flutter pub get --verbose**

[        ] MSG : Got dependencies!
[        ] MSG : Logs written to /Users/username/flutter/.pub-cache/log/pub_log.txt.
[ +113 ms] Running "flutter pub get" in myproject... (completed in 3.9s)
[  +36 ms] Found plugin cloud_firestore at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.1.18/
[   +5 ms] Found plugin cloud_firestore_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.6.17/
[   +1 ms] Found plugin cloud_functions at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.17/
[   +2 ms] Found plugin cloud_functions_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions_web-4.2.16/
[   +4 ms] Found plugin device_info at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.3/
[   +3 ms] Found plugin firebase_analytics at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.1.10/
[   +2 ms] Found plugin firebase_analytics_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.4.0+15/
[   +1 ms] Found plugin firebase_auth at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.3.20/
[   +2 ms] Found plugin firebase_auth_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-3.3.17/
[   +1 ms] Found plugin firebase_core at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.18.0/
[   +1 ms] Found plugin firebase_core_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.6.5/
[   +1 ms] Found plugin firebase_dynamic_links at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.2.6/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.6/
[   +1 ms] Found plugin geolocator at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-9.0.0/
[   +1 ms] Found plugin geolocator_android at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.0/
[   +1 ms] Found plugin geolocator_apple at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.2.0/
[   +1 ms] Found plugin geolocator_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.1.5/
[   +1 ms] Found plugin geolocator_windows at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_windows-0.1.1/
[   +1 ms] Found plugin google_maps_flutter at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.1.8/
[  +10 ms] Found plugin location at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/
[   +2 ms] Found plugin location_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/location_web-3.1.1/
[   +5 ms] Found plugin share at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.4/
[   +4 ms] Found plugin url_launcher at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.4/
[   +1 ms] Found plugin url_launcher_android at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[   +1 ms] Found plugin url_launcher_ios at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[        ] Found plugin url_launcher_linux at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +1 ms] Found plugin url_launcher_macos at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +2 ms] Found plugin url_launcher_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.12/
[   +1 ms] Found plugin url_launcher_windows at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +33 ms] Found plugin cloud_firestore at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.1.18/
[   +2 ms] Found plugin cloud_firestore_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.6.17/
[        ] Found plugin cloud_functions at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.17/
[   +1 ms] Found plugin cloud_functions_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions_web-4.2.16/
[   +1 ms] Found plugin device_info at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.3/
[   +1 ms] Found plugin firebase_analytics at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.1.10/
[   +1 ms] Found plugin firebase_analytics_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.4.0+15/
[        ] Found plugin firebase_auth at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.3.20/
[   +1 ms] Found plugin firebase_auth_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-3.3.17/
[        ] Found plugin firebase_core at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.18.0/
[   +1 ms] Found plugin firebase_core_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.6.5/
[   +2 ms] Found plugin firebase_dynamic_links at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.2.6/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.6/
[   +1 ms] Found plugin geolocator at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-9.0.0/
[   +2 ms] Found plugin geolocator_android at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.0/
[        ] Found plugin geolocator_apple at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.2.0/
[   +1 ms] Found plugin geolocator_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.1.5/
[        ] Found plugin geolocator_windows at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_windows-0.1.1/
[   +2 ms] Found plugin google_maps_flutter at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.1.8/
[   +3 ms] Found plugin location at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/
[   +1 ms] Found plugin location_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/location_web-3.1.1/
[   +5 ms] Found plugin share at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.4/
[   +5 ms] Found plugin url_launcher at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.4/
[        ] Found plugin url_launcher_android at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[        ] Found plugin url_launcher_ios at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[        ] Found plugin url_launcher_linux at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +1 ms] Found plugin url_launcher_web at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.12/
[   +2 ms] Found plugin url_launcher_windows at
/Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +31 ms] Generating /Users/username/original_unedited/myproject/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +47 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +1 ms] executing: xcrun xcodebuild -version
[ +224 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 13.4.1
           Build version 13F100
[   +7 ms] "flutter get" took 4,936ms.
[ +111 ms] ensureAnalyticsSent: 105ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by Sriraksha16** [comment]
[ integration_test:
      path:../integration_test
            pedantic:^1.8.0.  ] 

Probably Yes, After removing the integration-test, the problem solved. 
Again I run the 'flutter  pub  upgrade', got some changes. That is what i shared now.

**Comment by sigurdm** [comment]
So is this solved now?

**Comment by Sriraksha16** [comment]
Yes  Problem solved ,Thank you.
