### ISSUE TITLE
Ignore pubspec_overrides.yaml by default when publishing

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3498]
There is no reason to include `pubspec_overrides.yaml` when publishing, indeed one could even say that doing so is surprising behavior.

I'm guessing we just have to add it to the default patterns used in the gitignore/pubignore logic.

**Comment by SunlightBro** [comment]
I could create a PR for this, if wanted.

- Adding pubspec_overrides.yaml to `_basicIgnoreRules` in [lib/src/package.dart#L186](https://github.com/dart-lang/pub/blob/master/lib/src/package.dart#L186)
```diff
    'pubspec.lock',
    '!pubspec.lock/', // We allow a directory called pubspec lock.
+   'pubspec_overrides.yaml',
  ];

```
- creating a `test/lish/does_not_include_pubspec_overrides_file.dart` very similar to [does_not_include_dot_file.dart](https://github.com/dart-lang/pub/blob/master/test/lish/does_not_include_dot_file.dart)
