### ISSUE TITLE
make a publisher aware of large files in their published package

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#3500]
I'm not sure whether this ideas belongs here or in the https://github.com/dart-lang/pub-dev repo; in any case:

I've been working on a tool which queries pub and downloads targeted package archives (foo-0.0.1.tar.gz). I've noticed that some of these archives are very large (10s of MBs). From inspection, many of the package publishers are accidentally including large files in their published archives - files which they don't intend to be part of the published package (native symbol files, ...).

The larger size of the archives likely doesn't have a huge negative impact for users; a package consumer might have a longer `pub get` time; things might be less robust when working on lower bandwidth networks; package publish time would take longer (and similarly be slightly less robust).

In terms of mitigating this issue, I can think of a few possibilities:
- on the package pub.dev page, have information about large files in the package; a publisher could then inspect to see whether they were all intended
- when publishing, a pre-publish step could print out the n files that were about to be published that were larger than some set limit (i.e., as part of the general output that you see before the 'ok to publish y/N' prompt)

**Comment by sigurdm** [comment]
> when publishing, a pre-publish step could print out the n files that were about to be published that were larger than some set limit (i.e., as part of the general output that you see before the 'ok to publish y/N' prompt)

I'm afraid that false positives would be annoying if these were announced as _warnings_.

We currently show a listing of all the files to be included in the package. Should we after each file show the package size?

I made a prototype, using colors to convey big files (the cutoff is 1MB - sizes larger than that are shown in yellow).

<img width="835" alt="image" src="https://user-images.githubusercontent.com/8613953/182336114-e245fcfb-6a53-482f-a01b-a5ab786101a8.png">

WDYT?

**Comment by sigurdm** [comment]
> This may not work as well if the package file listing is much longer than their terminal height - some large files might have scrolled off the screen.

This is a general problem with many files - it is hard to get an overview and see if undesired files are included...
