### ISSUE TITLE
`pub upgrade some_package` doesn't upgrade transitive dependencies

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub#3504]
# Environment

- `pub version` or `flutter pub version`: Pub 2.19.0-33.0.dev
- OS version: macOS 12.4
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

According to https://dart.dev/tools/pub/cmd/pub-upgrade#upgrading-specific-dependencies upgrading a specific package should upgrade its transitive dependencies:

> Upgrading a dependency upgrades its transitive dependencies to their latest versions as well.

(Somewhat confusingly, it also says:
> Usually, no other dependencies are updated; they stay at the versions that are locked in the lockfile. However, if the requested upgrades cause incompatibilities with these locked versions, they are selectively unlocked until a compatible set of versions is found.

I'm assuming "no other dependencies" means "dependencies that are not in the transitive dependency list of the requested packages" not, "packages other than the ones explicitly listed in the command line", because otherwise the first sentence makes no sense to me. This issue report is predicated on that understanding.)

This doesn't seem to be the actual behavior. I set up a test after seeing unexpected results in actual use, by adding `path_provider` to a new Flutter project, then manually editing `pubspec.lock` to contain older versions of its dependencies (but still compatible with `path_provider`'s constraints). At this point, `dart pub outdated` gives me the expected output:

```
$ dart pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                      Current  Upgradable  Resolvable  Latest  

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies:         
ffi                               *1.2.1   2.0.1       2.0.1       2.0.1   
path_provider_android             *2.0.6   2.0.17      2.0.17      2.0.17  
path_provider_ios                 *2.0.6   2.0.11      2.0.11      2.0.11  
path_provider_linux               *2.0.2   2.1.7       2.1.7       2.1.7   
path_provider_macos               *2.0.0   2.0.6       2.0.6       2.0.6   
path_provider_platform_interface  *2.0.0   2.0.4       2.0.4       2.0.4   
path_provider_windows             *2.0.3   2.1.0       2.1.0       2.1.0   
win32                             *2.6.1   2.7.0       2.7.0       2.7.0   

8 upgradable dependencies are locked (in pubspec.lock) to older versions.
To update these dependencies, use `dart pub upgrade`.
all dependencies are up-to-date.
```

(Except for that last line, which seems like its own bug.)

At this point I ran `dart pub upgrade path_provider`, expecting it to update all of those `path_provider` sub-packages.

## Expected behavior

Updating `path_provider_*`, `ffi`, and `win32`, all of which are transitive dependencies of `path_provider`.

## Actual behavior

Nothing was upgraded:

```
$ dart pub upgrade path_provider
Resolving dependencies... 
  async 2.9.0
  boolean_selector 2.1.0
  characters 1.2.1
  clock 1.1.1
  collection 1.16.0
  cupertino_icons 1.0.5
  fake_async 1.3.1
  ffi 1.2.1 (2.0.1 available)
  file 6.1.2
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.1
  flutter_test 0.0.0 from sdk flutter
  lints 2.0.0
  matcher 0.12.12
  material_color_utilities 0.1.5
  meta 1.8.0
  path 1.8.2
  path_provider 2.0.11
  path_provider_android 2.0.6 (2.0.17 available)
  path_provider_ios 2.0.6 (2.0.11 available)
  path_provider_linux 2.0.2 (2.1.7 available)
  path_provider_macos 2.0.0 (2.0.6 available)
  path_provider_platform_interface 2.0.0 (2.0.4 available)
  path_provider_windows 2.0.3 (2.1.0 available)
  platform 3.1.0
  plugin_platform_interface 2.1.2
  process 4.2.4
  sky_engine 0.0.99 from sdk flutter
  source_span 1.9.1
  stack_trace 1.10.0
  stream_channel 2.1.0
  string_scanner 1.1.1
  term_glyph 1.2.1
  test_api 0.4.12
  vector_math 2.1.2
  win32 2.6.1 (2.7.0 available)
  xdg_directories 0.2.0+1
No dependencies changed.
8 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
```

On the other hand, `dart pub upgrade` without any argument does upgrade them as expected:
```
$ flutter pub upgrade
Resolving dependencies...
  async 2.9.0
  boolean_selector 2.1.0
  characters 1.2.1
  clock 1.1.1
  collection 1.16.0
  cupertino_icons 1.0.5
  fake_async 1.3.1
> ffi 2.0.1 (was 1.2.1)
  file 6.1.2
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.1
  flutter_test 0.0.0 from sdk flutter
  lints 2.0.0
  matcher 0.12.12
  material_color_utilities 0.1.5
  meta 1.8.0
  path 1.8.2
  path_provider 2.0.11
> path_provider_android 2.0.17 (was 2.0.6)
> path_provider_ios 2.0.11 (was 2.0.6)
> path_provider_linux 2.1.7 (was 2.0.2)
> path_provider_macos 2.0.6 (was 2.0.0)
> path_provider_platform_interface 2.0.4 (was 2.0.0)
> path_provider_windows 2.1.0 (was 2.0.3)
  platform 3.1.0
  plugin_platform_interface 2.1.2
  process 4.2.4
  sky_engine 0.0.99 from sdk flutter
  source_span 1.9.1
  stack_trace 1.10.0
  stream_channel 2.1.0
  string_scanner 1.1.1
  term_glyph 1.2.1
  test_api 0.4.12
  vector_math 2.1.2
> win32 2.7.0 (was 2.6.1)
  xdg_directories 0.2.0+1
Changed 8 dependencies!
```

# Notes

This is really problematic for federated plugins. It's relatively common for users to report issues with 1P Flutter plugins where ultimately the problem is that they added the plugin at some point, and have manually updated it by changing the constraint in `pubspec.yaml` but never `pub upgrading` their project, so while they have the latest version of the app-facing package, they still have old versions of the implementation packages that don't have the fix for their issue. (For context, we only update the minimum constraints in the app-facing package when we actually need to, such as to pick up implementations of a new feature that we're now exposing in the app-facing package, so that we're not needlessly constraining what people can use.)

I would like in those cases to be able to say "Run `pub upgrade <app-facing package>` and see if it works", but because that doesn't work I have to tell them to either manually update their lock file, to to `pub upgrade` their entire project which may cause other changes unrelated to the issue we're trying to investigate.

And more generally, outside of the context of bug reports, I'd like us to be able to recommend in docs that people update plugins via `pub upgrade <plugin>` to minimize that problem happening in the first place.

**Comment by sigurdm** [comment]
The documentation doesn't correspond to the current behaviour. `dart pub upgrade foo` only unlocks `foo` itself.

Now the question is what is the desired behaviour?

Should `dart pub upgrade foo` also upgrade (unlock) the transitive dependencies of `foo`, even if the current values are still compatible with the constraints.

We discussed a bit, and are leaning towards changing the implementation.

**Comment by jonasfj** [comment]
I've been leaning towards `dart pub upgrade foo` should unlock everything necessary to get the most recent version of `foo` allowed by `pubspec.yaml`.

We can make a heuristic in this direction, but there is no perfect solution to it.

Upgrading transitive dependencies when not necessary isn't something I would expect it to do.

But I see the use case here. Options are:
 * We make some tooling for this,
 * Recommend users to `dart pub upgrade `,
 * Provide tighter version constraints in the plugin package consumed by the user.

**Comment by stuartmorgan** [comment]
Not having at least an optional flag with this behavior continues to be an ongoing pain point for users with federated plugins, and the Flutter team in helping support clients of our plugins.

**Comment by stuartmorgan** [comment]
Thanks! Is there an issue tracking updating the docs when this flag reaches stable? The other part of the reported issue is still true:

> According to https://dart.dev/tools/pub/cmd/pub-upgrade#upgrading-specific-dependencies upgrading a specific package should upgrade its transitive dependencies:
> 
> > Upgrading a dependency upgrades its transitive dependencies to their latest versions as well.

**Comment by sigurdm** [comment]
Good point. Created an issue
