### ISSUE TITLE
Switch external language from pub.dartlang.org to pub.dev

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub#3519]
It's been a long time since we switched the external-facing site to pub.dev now, and most Flutter and Dart users never knowingly used the old pub.dartlang.org URL. While it remains a technical implementation detail, it's confusing that we reference it in our `pub publish` process, not least because we mix and match the two URLs in our logging messages.

I'd like to propose that we now change the two references to pub.dartlang.org below to pub.dev, matching the other references:

```
[C:\src\win32_registry] dart pub publish
Publishing win32_registry 1.0.2 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- CODE_OF_CONDUCT.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- coverage.cmd
|-- example
|   |-- create_values.dart
|   |-- example.dart
|   '-- read_values.dart
|-- lib
|   |-- src
|   |   |-- access_rights.dart
|   |   |-- registry.dart
|   |   |-- registry_hive.dart
|   |   |-- registry_key.dart
|   |   |-- registry_key_info.dart
|   |   |-- registry_value.dart
|   |   |-- registry_value_type.dart
|   |   '-- utils.dart
|   '-- win32_registry.dart
|-- pubspec.yaml
'-- test
    '-- win32_registry_test.dart

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish win32_registry 1.0.2 to https://pub.dartlang.org (y/N)? y
Uploading...
Successfully uploaded https://pub.dev/packages/win32_registry "1.0.2".
```

@mit-mit for visibility / approval.

**Comment by timsneath** [comment]
As an aside, it's weird that the version number is quoted in the last line; perhaps we can fix that at the same time?

**Comment by mit-mit** [comment]
> I'd like to propose that we now change the two references to pub.dartlang.org below to pub.dev, matching the other references:

Yes, I think we can change these. We probably can't change the actual API endpoint, but these are UI messages, and they are about what you're publishing to which *is* pub.dev.

> As an aside, it's weird that the version number is "quoted" in the last line; perhaps we can fix that at the same time?

Yeah, that looks weird indeed, fixing in  https://github.com/dart-lang/pub-dev/pull/5941
