### ISSUE TITLE
pub get error

### ISSUE THREAD

**Issue by xiaojieonly** [dart-lang/pub#3525]
HTTP error 404: Not Found
package:pub/src/http.dart 231:5                    _ThrowingClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 379:18                   _ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 52:24   _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 862:22          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 885:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 859:5           HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 669:7           HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 86:9            SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 85:14           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 82:5            SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 324:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    /Library/Developer/flutter/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.

**Comment by xiaojieonly** [comment]
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus/versions/4.1.0.tar.gz
    | took 0:00:00.473157
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-002, T.2.D, V.mix-zj-sad3-001, T.85.D, M.ctn-zj-huz-067, SR-CN3X-ZJWZ-62-133:24, SR-CNCT-JXKHN-193-137:1
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.137
    | server: nginx
    | x-request-id: 34f924b53ec3a7c1d6dc4d163a548286
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_WzoZpo.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus_windows/versions/3.0.3.tar.gz
    | took 0:00:00.555781
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-002, T.2.D, V.mix-zj-sad3-004, T.87.D, M.ctn-zj-huz-086, SR-CN3X-ZJWZ-62-138:4, SR-CNCT-JXKHN-193-136:16
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.136
    | server: nginx
    | x-request-id: 16c6b263982f6bd030f237a6af7a7ca7
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_lmYmrK.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus_platform_interface/versions/2.6.0.tar.gz
    | took 0:00:00.569113
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-003, T.3.D, V.mix-zj-sad3-004, T.87.D, M.ctn-zj-huz-069, SR-CN3X-ZJWZ-62-134:1, SR-CNCT-JXKHN-193-136:18
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.136
    | server: nginx
    | x-request-id: 4bf23bd9c84e978dbcda81eb71a71790
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_sS7RY1.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus_web/versions/2.1.0.tar.gz
    | took 0:00:00.588100
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-004, T.4.D, V.mix-zj-sad3-001, T.85.D, M.ctn-zj-huz-085, SR-CN3X-ZJWZ-62-133:23, SR-CNCT-JXKHN-193-136:8
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.136
    | server: nginx
    | x-request-id: 65a21b3eb2178c1cf29c84c58198ee1e
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_K7bYRN.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus_linux/versions/2.1.1.tar.gz
    | took 0:00:00.593196
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-005, T.5.D, V.mix-zj-sad3-004, T.86.D, M.ctn-zj-huz-090, SR-CN3X-ZJWZ-62-138:23, SR-CNCT-JXKHN-193-135:2
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.135
    | server: nginx
    | x-request-id: a5116a255b428bddd7e4a762ac226120
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_uFSXV3.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/package_info_plus/versions/1.4.3%2B1.tar.gz
    | took 0:00:00.596191
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-004, T.4.D, V.mix-zj-sad3-001, T.85.D, M.ctn-zj-huz-067, SR-CN3X-ZJWZ-62-133:24, SR-CNCT-JXKHN-193-136:5
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.136
    | server: nginx
    | x-request-id: daf5fe7f7e82c3cf2b121b45bac6aa4b
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_CvDyVs.
IO  : HTTP response 404 Not Found for GET https://pub.flutter-io.cn/packages/device_info_plus_macos/versions/2.2.3.tar.gz
    | took 0:00:00.741535
    | connection: keep-alive
    | date: Fri, 12 Aug 2022 07:50:00 GMT
    | content-length: 153
    | x-via: S.mix-zj-sad3-002, T.2.D, V.mix-zj-sad3-004, T.85.D, M.ctn-zj-huz-067, SR-CN3X-ZJWZ-62-133:12, SR-CNCT-JXKHN-193-137:2
    | content-type: text/html
    | x-source: C/404
    | x-cache: MISS from 59.63.193.137
    | server: nginx
    | x-request-id: 7b6e5a363c3538bff653a7cee4a9f015
IO  : Deleting directory /private/var/folders/tp/qz3zc1sn36b1_hpgv5c2kc_00000gn/T/pub_eOj0Zw.

**Comment by coldmoonwss** [comment]
I also is such, what's the problem

**Comment by huangxiquan** [comment]
+1

**Comment by sigurdm** [comment]
@xiaojieonly  Are you using the chinese mirror?

It seems the chinese mirror is having problems.
@chenglu

**Comment by sigurdm** [comment]
I think our latest deployment gave problems with the chinese mirror.

I have migrated back - and it seems to work on my side.

@huangxiquan and @xiaojieonly could you try again?

**Comment by coldmoonwss** [comment]
I know why. It's the problem of the image source of the Chinese community of flitter. Just replace the image source with that of Tsinghua University

**Comment by huangxiquan** [comment]
> I think our latest deployment gave problems with the chinese mirror.
> 
> I have migrated back - and it seems to work on my side.
> 
> @huangxiquan and @xiaojieonly and @coldmoonwss could you try again?

it is worked

**Comment by chenglu** [comment]
Issue fixed.

Seems we moved the pub packages binary files to the new bucket `dartlang-pub-public-packages`, just fixes this by whitelisted the bucket.

**Comment by sigurdm** [comment]
@chenglu thanks for the quick fix I'll try the migration again.

**Comment by chenglu** [comment]
@sigurdm Our `FLUTTER_STORAGE_BASE_URL` is point to the Google Cloud Storage service, in order to avoid the abuse, we have a kind of "gcs-bucket-allowlist" on the CN Mirrors, so please let me know if we have the plan to the open-up the new GCS bucket for some of our services, thanks!

**Comment by sigurdm** [comment]
`dartlang-pub-public-packages` is the new bucket we serve the packages from now on. 

We don't have any more planned bucket migrations coming up.

**Comment by sigurdm** [comment]
Change was here: https://github.com/dart-lang/pub-dev/commit/ed70baa82fa63fc9a9e97bf28880bc853cc9984e

**Comment by sigurdm** [comment]
Closing this as resolved. Please open new issues if some things are still not working.
