### ISSUE TITLE
problem about getx

### ISSUE THREAD

**Issue by havaraie** [dart-lang/pub#3534]
when i want install get x in v code for application flutter,get a problem:

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub get failed (1; and attaching the relevant parts of that log file.)
exit code 1

**Comment by sigurdm** [comment]
What command are you running?
How does your pubspec.yaml looking?

Could you try running `dart pub get` and paste the output?

**Comment by sigurdm** [comment]
Closing as stale
