### ISSUE TITLE
Warnings in `dart pub publish` for Dart 3

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3552]
Consider:
 * Publish warning if not Dart 3 compatible and using >=2.12.0 <3.0.0 as SDK constraint (to either change code or use different SDK constraint)
 * Publish hint if Dart 3 compatible and using <3.0.0, suggest using <4.0.0 as SDK constraint

**Comment by sigurdm** [comment]
The first bullet is done.

I doubt we want to do the third.

**Comment by sigurdm** [comment]
Second bullet is fixed by https://github.com/dart-lang/pub/pull/3752
