### ISSUE TITLE
pub client: update solver to support language version 2.12 in Dart 3

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3554]
Implement option C from [go/dart-2 -in-dart-3](https://goto.google.com/dart-2-in-dart-3).

Specially, intepret an SDK constraint where:
 * Lower-bound is `>=2.12.0` or higher, and,
 * Upper-bound is `<3.0.0`.

**Remark** We may have to take extra care that error messages remain sane.

**Comment by mit-mit** [comment]
Confirmed working as intended in a locally patched 3.0 build after https://github.com/dart-lang/pub/issues/3600 was fixed in https://github.com/dart-lang/pub/pull/3612
