### ISSUE TITLE
Consider improved messaging when an SDK upgrade would unblock version solving

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#3564]
`dart --version`: `Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"`

![](https://user-images.githubusercontent.com/168174/190037816-5f753b04-0aa6-4429-8748-28a6b97b9d90.png)

It appears like the analyzer version (v5.0.0) isn't compatible with the state of the package, or am I missing something?

**EDIT**: After blasting away my `pubspec.lock` and calling `dart pub get`:

```txt
Resolving dependencies... 
The current Dart SDK version is 2.17.6.

Because test >=1.16.1 <1.16.6 depends on analyzer >=0.39.5 <2.0.0 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.1 <1.17.10 requires analyzer >=0.39.5 <2.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 <1.21.0 depends on analyzer >=2.0.0 <4.0.0, test >=1.16.1 <1.21.0 requires analyzer >=0.39.5 <4.0.0.
And because test >=1.21.0 <1.21.5 depends on analyzer >=2.0.0 <5.0.0 and test >=1.21.5 requires SDK version >=2.18.0-146.0.dev <3.0.0, test >=1.16.1 requires analyzer >=0.39.5 <5.0.0.
So, because linter depends on both analyzer ^5.0.0 and test ^1.16.1, version solving failed.
```

I think @pq you might have forgot to rev the pubspec dependencies?

Should the [github action][gha] check that `pub get` works for `stable` as a reminder to rev the pubspec?

[gha]: https://github.com/dart-lang/linter/blob/main/.github/workflows/build.yaml#L36-L38

**Comment by sigurdm** [comment]
The current solver-traces tell you why something doesn't work, but don't tell you what would work.

```
Resolving dependencies... 
The current Dart SDK version is 2.17.6.

Because test >=1.16.1 <1.16.6 depends on analyzer >=0.39.5 <2.0.0 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.1 <1.17.10 requires analyzer >=0.39.5 <2.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 <1.21.0 depends on analyzer >=2.0.0 <4.0.0, test >=1.16.1 <1.21.0 requires analyzer >=0.39.5 <4.0.0.
And because test >=1.21.0 <1.21.5 depends on analyzer >=2.0.0 <5.0.0 and test >=1.21.5 requires SDK version >=2.18.0-146.0.dev <3.0.0, test >=1.16.1 requires analyzer >=0.39.5 <5.0.0.
So, because linter depends on both analyzer ^5.0.0 and test ^1.16.1, version solving failed.

To make the version solving succeed you could try one of the following potential solutions:
* Upgrade your sdk to at least 2.18.0-146.0.dev.
* Downgrade the constraint on package:test to allow '1.21.4'
```
I cannot think of a better way of constructing these than:
* for each constraint in the root package (possibly just for each constraint involved in the trace), try to relax it and redo the resolution.
* Special handling for the sdk-constraint (try to redo the resolution with an imagined SDK equal to the one required in the trace)...

**Comment by jonasfj** [comment]
> I cannot think of a better way of constructing these than...

Yeah, doing some guesses and running the solver for that is probably what it'll take.
But it's hard to know if such heuristics are useful or not.

**Comment by pq** [comment]
> But it's hard to know if such heuristics are useful or not.

Agreed.

Really this could be a fools errand but I appreciate the conversation.

I'd be curious what @InMatrix thinks?
