### ISSUE TITLE
Flutter dart packaging

### ISSUE THREAD

**Issue by mlf2020** [dart-lang/pub#3578]
Whether components of a plugin or package can be packaged (without source code), similar to native integration which can rely on either source code integration or Framework/AAR integration. I wonder if it is possible to rely on the packaged plugin or package in the pubspec.yaml file of the Flutter module? (So far the code pulled down through the flutter pub get is in the form of source code)

**Comment by sigurdm** [comment]
There is currently no mechanism for consuming packages with pre-compiled dart code (and I don't think any plans of enabling it).

However the package archive can contain arbitrary files, so via [ffi](https://dart.dev/guides/libraries/c-interop#bundling-and-loading-c-libraries) or the [flutter plugin](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#plugin) mechanism it is possible to do basically anything.

**Comment by sigurdm** [comment]
Did this answer your question?

**Comment by sigurdm** [comment]
Considering this answered.

**Comment by mlf2020** [comment]
OK，Not currently，right? Is there a plan?

**Comment by mlf2020** [comment]
> 

OK，thanks!
