### ISSUE TITLE
EOF reached without finding string terminator

### ISSUE THREAD

**Issue by jsiguo** [dart-lang/pub#3594]
Do you want to publish image_picker 0.8.4 (y/N)? y
Uploading...
EOF reached without finding string terminator
pub finished with exit code 1

我将0.8.4源码下载下来，发布到自己的服务器上会报上面的错误，请问怎么解决

I will download the 0.8.4 source code and publish it to my own server. The above error will be reported. How can I solve it

**Comment by BaroneX** [comment]
I had the same problem, I shortened the file name and it worked fine.

我遇到了一样的问题，我尝试改了下文件名称 缩短了一下就好了，之前老版本的dart是没问题的，你这边解决了吗

**Comment by sigurdm** [comment]
This looks like it could be an error from your own server.

Try running `dart pub publish --verbose` for more detailed output.

**Comment by sigurdm** [comment]
Closing for lack of information
