### ISSUE TITLE
Is it possible for the Android code to be compiled to an aar file when pubulish a flutter plugin?

### ISSUE THREAD

**Issue by taibaiyinxing** [dart-lang/pub#3599]
As [this article](https://github.com/flutter/flutter/wiki/How-Flutter-apps-are-compiled-with-Gradle-for-Android) said, the android code of a plugin will be added as a subproject to the main project, and this will absolutely slow down the compilation of the flutter project. So is it possible for the plugin to compile the android code to a aar file ahead before it was published to the pub.dev, and when the plugin is added to a flutter project, the aar file was added to the android project instead of a subproject? This may speed up the complation of android.

**Comment by sigurdm** [comment]
Maybe...?

We are not so well versed in the android aar format at the pub team. But the published package can contain any files.

Perhaps ask about this in https://github.com/flutter/flutter.

Closing as I don't think the pub team will be taking care of this.
