### ISSUE TITLE
flutter pub get  Error

### ISSUE THREAD

**Issue by beehov** [dart-lang/pub#3606]
hi
I have a problem and i think that , it is probably because of new internet limitation in IRAN .
i had some problems and i fix them by running psiphon  and set proxy in android studio .
but for running  :
flutter pub get
these error happens :
Authentication error (403)
package:pub/src/authentication/client.dart 95:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 60:9    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 862:22          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 886:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 859:5           HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 669:7           HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 86:9            SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 85:14           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 82:5            SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 332:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 55:5              GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\flutter\.pub-cache\log\pub_log.txt

I think maybe i have to use a suitable VPN to handle it  or some other way .
please help

**Comment by sigurdm** [comment]
You can try using the chinese community mirror: https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site

**Comment by sigurdm** [comment]
Not sure what more we can do.

Closing for now.
