### ISSUE TITLE
Global activate doesn't support --git-ref

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/pub#3608]
Global activate says it supports checking out Git source with a `--git-ref`. However, when trying to use this capability, the Git repo is checked out with a `depth` of `1`, which only finds the `main` branch. Therefore, it currently seems to be impossible to activate a branch of a repo.

**Comment by mraleph** [comment]
Transferring to dart-lang/pub where this belongs.

**Comment by Giuspepe** [comment]
I fixed this in my PR https://github.com/dart-lang/pub/pull/3620 which is ready to be reviewed

**Comment by sigurdm** [comment]
This is fixed
