### ISSUE TITLE
Add a flag to let `publish --dry-run` run validation even for published versions

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub#3619]
## Background

In the `flutter/plugins` and `flutter/packages` repository, we have CI that runs `pub publish --dry-run` to make sure that PRs don't leave packages in a state that won't publish correctly (modulo the currently unsolvable issue of server-side checks). We also use a pinned version of `flutter` in our CI, updated by a roller, with the goal of finding any regressions due to Flutter or Dart changes in the roller, rather than randomly later.

In https://github.com/flutter/flutter/issues/113788 we were broken by https://github.com/dart-lang/pub/issues/3618, but randomly in a later PR rather than in the roller. This is because running `pub publish --dry-run` on all our packages in the roller doesn't actually do anything—there are no version changes, so everything is already published, and `--dry-run` stops immediately if the package is already published.

## Request

We'd like a flag that would essentially behave like `--dry-run` of an unpublished version, regardless of whether it's actually been published or not, so that our CI checks would find publish issues immediately (in the roller, in PRs that don't update the version, etc.) rather than the next time we happen to update the version.

## Workaround

We could potentially synthetically change the version locally every time we run the test, but then what we're testing isn't the same as the actual code, which we try to minimize as much as possible for obvious reasons.

**Comment by sigurdm** [comment]
I don't think pub publish should behave differently on a published version.

IMO we should leave it up to the server to reject existing versions.

Maybe we could print an INFO line that mentions the existing version...

**Comment by sigurdm** [comment]
I fail to reproduce this. There is no validator that considers if a version has already been published or not. That is entirely server-side. 

I think the error message in the [issue your refer](https://github.com/flutter/flutter/issues/113788) is from here: https://github.com/flutter/plugins/blob/3a03925ecb29adbb3285132d2adfd661d32823b1/script/tool/lib/src/publish_check_command.dart#L222 not from the pub client.

Closing this for now - please reopen if there still is an issue.

**Comment by stuartmorgan** [comment]
🤦🏻  Sorry about that, it didn't even occur to me to check our tooling.

**Comment by sigurdm** [comment]
No worries - took me some time to realize also...
