### ISSUE TITLE
How to remove a pkg marked in `RETRACTED` status from `pub.dev`?

### ISSUE THREAD

**Issue by kimmy214** [dart-lang/pub#3624]
How to remove a pkg marked in `RETRACTED` status from `pub.dev`?

**Comment by szakarias** [comment]
If you wish to change the `retracted` status of a package version this can be done in the Admin UI on pub.dev. 

You can also mark the entire package as `discontinued`. This can also be done in the Admin UI.

In general we do not delete a package but some exceptions can be made. For more information on this, you can take a look at our policy https://pub.dev/policy
