### ISSUE TITLE
RangeError (start): Invalid value: Not in inclusive range 0..4996: 5000

### ISSUE THREAD

**Issue by sandersaelmans** [dart-lang/pub#3625]
Upon running build runner for a package we get the following error _after_ code has been correctly generated by build_runner:
```
RangeError (start): Invalid value: Not in inclusive range 0..4996: 5000
#0      RangeError.checkValidRange (dart:core/errors.dart:358:7)
dart-lang/build#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
dart-lang/build#2      _limit (package:pub/src/log.dart:344:16)
dart-lang/build#3      dumpTranscriptToFile (package:pub/src/log.dart:370:22)
dart-lang/build#4      PubCommand.run (package:pub/src/command.dart:231:13)
<asynchronous suspension>
dart-lang/build#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
dart-lang/build#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
dart-lang/build#7      runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
dart-lang/build#8      main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

This happened after adding an additional dependency to the pubspec file of the package (the dependency does not internally use build_runner). Nothing else was touched which would impact build_runner.

This fix might be related, and could possibly solve this issue:
https://github.com/dart-lang/pub/pull/3512/files

---

Additional info:
* Dart SDK Version
  * 2.18.1
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * build_runner 2.3.0
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * We use builders for generating data classes, sum types, and translating template files into dart classes
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * MacOSX

-----

**Comment by sigurdm** [comment]
I believe this is the same bug as was fixed by https://github.com/dart-lang/pub/pull/3512.

Should be fixed in the next release (or try with a dev-release).
