### ISSUE TITLE
Pub cache corrupt ?

### ISSUE THREAD

**Issue by SuperMuel** [dart-lang/pub#3626]
# Environment

- Dart 2.18.3
- Windows 10 Pro 10.0.19044

# Problem

I've been using [dart_frog](https://github.com/VeryGoodOpenSource) to develop a dart backend for a flutter project. I use a windows 10 machine for development. 
Everything worked perfectly until I ran `dart pub cache clean` trying to fix another issue. (Turns out `dart pub upgrade` did fix this problem)

**Now I can't create any other _dart_frog_ project, and I can't run the backend of my actual project, that worked well since. It seems that my pub cache is corrupt**

[Issue opened on the dart_frog repository](https://github.com/VeryGoodOpenSource/dart_frog/issues/397) 

## Setup

- Running dart `pub cache clean`

- Checking that %LOCALAPPDATA%\Pub\Cache is empty. (running the last command again outputs _No pub cache at ~\AppData\Local\Pub\Cache._)

- removing the dart-sdk directory from ~\tools\

- Reinstalling dart 2.18.3 from a [ZIP file](https://dart.dev/get-dart/archive) in ~tools\

- Checking that `dart` path variable points to ~\tools\dart-sdk\bin

- `dart --version` outputs `Dart SDK version: 2.18.3 (stable) (Mon Oct 17 13:23:20 2022 +0000) on "windows_x64"`

As specified in the [dart_frog docs](https://dartfrog.vgv.dev/docs/overview) :
`dart pub global activate dart_frog_cli`
```
PS ~\> dart pub global activate dart_frog_cli
Resolving dependencies...
[...]
+ async 2.10.0
+ dart_frog_cli 0.2.2
[...]
+ pool 1.5.1
[...]
Downloading dart_frog_cli 0.2.2...
Downloading pub_updater 0.2.2...
[...]
Downloading pool 1.5.1...
[...]
Downloading async 2.10.0...
Building package executables...
Built dart_frog_cli:dart_frog.
Installed executable dart_frog.
Activated dart_frog_cli 0.2.2.
```

## Expected behavior
- Running `dart_frog create my_new_project` creates a project folder with no errors. Directly running `dart_frog dev` in the created directory runs the backend on the machine.

- Running `dart_frog dev` in my project runs the backend.

## Actual behavior
Running `dart_frog create server` outputs
```
PS ~\dart_debug> dart_frog create server
✓ Creating server (0.3s)
Unable to execute hook: post_gen.dart.
Error: The method 'FutureGroup' isn't defined for the class 'Pool'.
 - 'Pool' is from 'package:pool/pool.dart' ('../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pool-1.5.1/lib/pool.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FutureGroup'.
        _closeGroup = FutureGroup();
                      ^^^^^^^^^^^
```

In my actual project that worked well since, when trying to run the backend on my machine by running `dart_frog dev` in the project's directory ouputs : 

```
PS ~\project\server> dart_frog dev
⠼ Serving... (2.7s)Unable to execute hook: pre_gen.dart.
Error: 'RouteConfiguration' isn't a type.
  final RouteConfiguration configuration;
        ^^^^^^^^^^^^^^^^^^
⠋ Serving... (3.3s)
PS ~\project\server>
```

# Attempts to fix this problem :
I tried with different dart versions, and also with a lower dart_frog version. 
I searched for any other pub cache than `%localappdata%\pub\cache` but I could not find any.
Flutter is not installed on my machine anymore.

I tried to look into the `../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pool-1.5.1/` directory that seems to cause an issue.
Opening this directory with my IDE (VScode) tells me "that some packages are missing or out of date". And running `dart pub get` in this directory outputs this message :
```[pool-1.5.1] dart pub get
Resolving dependencies...
Null check operator used on a null value
package:pub/src/entrypoint.dart 159:60                 Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 102:21                 Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 99:42                  Entrypoint.lockFile
package:pub/src/entrypoint.dart 294:21                 Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                        progress
package:pub/src/entrypoint.dart 288:26                 Entrypoint.acquireDependencies
package:pub/src/command/get.dart 55:22                 GetCommand.runProtected
package:pub/src/command.dart 189:45                    PubCommand.run.<fn>
dart:async                                             new Future.sync
package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
dart:async                                             runZonedGuarded
package:pub/src/utils.dart 126:5                       captureErrors
package:pub/src/command.dart 189:13                    PubCommand.run
package:args/command_runner.dart 209:27                CommandRunner.runCommand
package:dartdev/dartdev.dart 231:30                    DartdevRunner.runCommand
package:args/command_runner.dart 119:25                CommandRunner.run.<fn>
dart:async                                             new Future.sync
package:args/command_runner.dart 119:14                CommandRunner.run
package:dartdev/dartdev.dart 66:29                     runDartdev
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    ~\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Null check operator used on a null value
#0      Entrypoint.lockFilePath (package:pub/src/entrypoint.dart:159:60)
#1      dumpTranscriptToFile (package:pub/src/log.dart:375:50)
#2      PubCommand.run (package:pub/src/command.dart:231:13)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
#5      runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

exit code 1
```

Also, the referenced log file at `~\AppData\Local\Pub\Cache\log\pub_log.txt` doesn't exists.  

Are there more cache files that can be manually deleted ? 
Thanks  for your help

**Comment by jonasfj** [comment]
> I tried to look into the ../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pool-1.5.1/ directory that seems to cause an issue.
> Opening this directory with my IDE (VScode) tells me "that some packages are missing or out of date". And running dart pub get in this directory outputs this message :

Running `dart pub get` inside the PUB_CACHE never makes sense.

**Comment by jonasfj** [comment]
Also are you sure you did `dart pub global activate dart_frog_cli` and didn't accidentally do `dart pub global activate dart_frog`

**Comment by SuperMuel** [comment]
Hello @jonasfj and thanks for your answer

I already had doubts when running `dart pub get` in PUB_CACHE ([dart_frog issue](https://github.com/VeryGoodOpenSource/dart_frog/issues/397)): 
> It explicitly tells me to open an dart-lang issue, but something tells me that running dart pub get in a cached package isn't something I'm allowed to do in the first place. 

But the error message got me confused. And I agree with you, I think this should not fail but instead just refuse to run if this doesn't make sense.

I was just about to close this issue as I'm switching to linux because of this problem. But in a last effort trying to reproduce this issue in a fresh windows install, I finally succeeded :
```
// install dart-sdk 2.18.3:
choco install dart-sdk

// Use a dart_frog project that seems to cause the problem
git clone https://github.com/SuperMuel/Kal
cd .\Kal\server\
dart pub get

cd ~
dart pub cache clean // the command that started the problem

// Trying to create a new dart_frog project:
dart pub global activate dart_frog_cli
dart_frog create dart_frog_test // succeeds
cd .\dart_frog_test
dart_frog dev // fails with :
⠋ Serving...Unable to execute hook: pre_gen.dart.
Error: 'RouteConfiguration' isn't a type.
  RouteConfiguration configuration,
  ^^^^^^^^^^^^^^^^^^
```

Here's the content of the pubspec.yaml file of the `server` directory in which I ran `dart pub get` 

```yaml
name: server
description: Official server for the Kal service
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0
  freezed_annotation: ^2.2.0

  kal_mysql_client:
    path: packages/kal_mysql_client

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
```
I am going to try to restrict the `server` project to the bare minimum to reproduce this issue and make it available. Also I'll update the dart_frog issue.

In the meantime, here are the content of the PUB_CACHE folder :
[Cache.zip](https://github.com/dart-lang/pub/files/9927739/Cache.zip)

 Thanks again !

**Comment by jonasfj** [comment]
Where does `RouteConfiguration` come from, and are you sure it's in the dependency it in your project?

It sounds like a bug in `dart_frog`. where they are not adding a dependency to `dart_frog_gen` somewhere, because it's not in your pub_cache.

**Comment by felangel** [comment]
> Where does `RouteConfiguration` come from, and are you sure it's in the dependency it in your project?
> 
> It sounds like a bug in `dart_frog`. where they are not adding a dependency to `dart_frog_gen` somewhere, because it's not in your pub_cache.

Chiming in on the Dart Frog side, `RouteConfiguration` is defined and exported from `dart_frog_gen` ([source code](https://github.com/VeryGoodOpenSource/dart_frog/blob/57d94f82353d9f6b2b97987aa38ea7ef339811d2/packages/dart_frog_gen/lib/src/build_route_configuration.dart#L244)).

I'm not able to reproduce this issue personally :(

**Comment by jonasfj** [comment]
@felangel if you look at the `Cache.zip` attached to https://github.com/dart-lang/pub/issues/3626#issuecomment-1301953172, then you'll notice that it doesn't contain `dart_frog_gen`.

So running:
```console
# Empty PUB_CACHE
dart pub cache clean

# Install CLI
dart pub global activate dart_frog_cli

# Create project
dart_frog create dart_frog_test

cd .\dart_frog_test

# This now fails, because dart_frog_gen isn't installed
dart_frog dev
⠋ Serving...Unable to execute hook: pre_gen.dart.
Error: 'RouteConfiguration' isn't a type.
  RouteConfiguration configuration,
  ^^^^^^^^^^^^^^^^^^
```
Probably, the dependencies in the `dart_frog_test/` folder wasn't installed correctly.

-------

I can't reproduce either, but I doubt it's a bug in `pub`, probably a missing dependency -- or a failed installation of dependencies.
