### ISSUE TITLE
pubspec_overrides.yaml published to a private package repository.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3629]
# Environment

- 2.18.3
- Ubuntu 22.04.1 LTS

I've just published a dart package to a private repository (https://onepub.dev).

The package had a pubspec_overrides.yaml file.

The problem is that the pubspec_overrides.yaml file was published to the private repo, whereas my understanding is that the 'dart pub publish' command should not submit the pubspec_overrides.yaml file when publishing.

Here is the output from the pub publish command. You can see that it includes the pubspec_overrides.yaml file:

```
dart pub publish
Publishing money2 3.3.2 to https://beta.onepub.dev/api/jbbxpsdavu/:
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- example
|   '-- example.dart
|-- images
|   '-- noojee-logo.png
|-- lib
|   |-- money2.dart
|   '-- src
|       |-- common_currencies.dart
|       |-- currencies.dart
|       |-- currency.dart
|       |-- encoders.dart
|       |-- exchange_rates
|       |   |-- exchange_platform.dart
|       |   '-- exchange_rate.dart
|       |-- money.dart
|       |-- money_data.dart
|       |-- pattern_decoder.dart
|       |-- pattern_encoder.dart
|       '-- version
|           '-- version.g.dart
|-- pubspec.yaml
|-- pubspec_overrides.yaml
'-- test
    |-- rounding_test.dart
    '-- src
        |-- common_currencies_test.dart
        |-- currencies_test.dart
        |-- currency_test.dart
        |-- exchange_rate_test.dart
        |-- exchange_rates
        |   '-- exchange_platform_test.dart
        |-- money_coding_test.dart
        |-- money_format_test.dart
        |-- money_parse_test.dart
        |-- money_test.dart
        |-- money_try_parse_test.dart
        |-- pattern_decoder_test.dart
        '-- readme_test.dart
Package validation found the following potential issue:
* /home/bsutton/git/money2/CHANGELOG.md doesn't mention current version (3.3.2).
  Consider updating it with notes on this version prior to publication.

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy


Package has 1 warning.. Do you want to publish money2 3.3.2 to https://beta.onepub.dev/api/jbbxpsdavu/ (y/N)? 


```

You can see the money2 code here:
https://money2.onepub.dev

Feel free to create a https://onepub.dev account it it makes testing easier (its free).

**Comment by jonasfj** [comment]
This is possibly a bug.

I don't think publishing it will cause any issues, it's just messy.

I don't see any reason to publish it, so I would suggest we add it to the list of files ignored by default. I think it's still possible to override those ignores using `.pubignore`.

**Comment by bsutton** [comment]
I'm not certain if this is a broader issue but it caused problems for our
dart documentation server (we run the https://onepub.dev private dart
repository).

Our server uses the standard dart doc code which baulked when it saw a
relative reference in the override and failed to generate the api doc.
For the moment we will modify our dartdoc process to explicitly exclude the
pubspec_override.xml.

The concern is that it may also cause pub.dev documentation server to fail
if it also sees and processes the override file.

> I would suggest we add it to the list of files ignored by default.

agreed.

**Comment by bsutton** [comment]
Just another thought on this one.

It's possible that I published the package using an older version of dart.
Any solution (if required) would need to assume that users will continue to
use an older version of dart for sometime and hence still publish the
override file.

But you probably already thought of this :)

**Comment by sigurdm** [comment]
This was fixed by https://github.com/dart-lang/pub/pull/3503 and is already in 2.19
