### ISSUE TITLE
assert up-to-date should run 'dart pub get' if the SDK has changed from what generated package_config.json

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3641]
assert up-to-date should run 'dart pub get' if the SDK has changed from what generated package_config.json

**Comment by jonasfj** [comment]
and we should probably run "assert up-to-date" for `dart test/run/doc/analyze`

**Comment by jonasfj** [comment]
Related to https://github.com/dart-lang/sdk/issues/50422

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pub/pull/3652
