### ISSUE TITLE
Flutter Pub get can not use Git depandent

### ISSUE THREAD

**Issue by Alembertcn** [dart-lang/pub#3645]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):Windows 11
- Are you using the Chinese community mirror or a corporate firewall? No 

# Problem
 I has git git version  2.33.0.windows.2  and it is run ok, but when my pubspec.yaml has git depandent then run pub get  it tip me

**Comment by sigurdm** [comment]
I think we need more details here.

Could you try running `flutter pub get --verbose` and attaching the output?

**Comment by Alembertcn** [comment]
> I think we need more details here.
> 
> Could you try running `flutter pub get --verbose` and attaching the output?

[   +1 ms] SLVR:   selecting testf
[   +1 ms] SLVR:   derived: getwidget 2.0.4
[   +5 ms] SLVR:   derived: retrofit_generator ^2.0.1
[   +1 ms] SLVR:   derived: json_serializable ^4.1.4
[   +1 ms] SLVR:   derived: excel any
[   +2 ms] SLVR:   derived: dart_style any
[   +2 ms] SLVR:   derived: build_runner ^2.1.1
[   +1 ms] SLVR:   derived: flutter_localizations from sdk
[   +5 ms] SLVR:   derived: flutter_test from sdk
[   +2 ms] SLVR:   derived: lottie 1.2.1
[   +3 ms] SLVR:   derived: flutter_gifimage ^1.0.1
[   +9 ms] SLVR:   derived: shared_preferences 2.0.7
[   +2 ms] SLVR:   derived: flutter_widget_from_html_core 0.8.4
[   +1 ms] SLVR:   derived: syncfusion_flutter_sliders 19.3.56
[   +1 ms] SLVR:   derived: syncfusion_flutter_core 19.3.56
[   +1 ms] SLVR:   derived: fl_chart 0.40.0
[   +2 ms] SLVR:   derived: flutter_echarts 2.3.0
[   +6 ms] SLVR:   derived: animate_do 2.0.0
[   +2 ms] SLVR:   derived: flutter_easyrefresh ^2.2.1
[   +1 ms] SLVR:   derived: dotted_line ^3.0.0
[   +1 ms] SLVR:   derived: bot_toast 4.0.1
[   +1 ms] SLVR:   derived: flutter_svg ^0.22.0
[   +1 ms] SLVR:   derived: auto_size_text 3.0.0
[   +1 ms] SLVR:   derived: tuple 2.0.0
[   +7 ms] SLVR:   derived: sprintf ^6.0.0
[   +1 ms] SLVR:   derived: event_bus 2.0.0
[   +1 ms] SLVR:   derived: encrypt 5.0.1
[   +1 ms] SLVR:   derived: decimal 1.3.0
[   +1 ms] SLVR:   derived: retrofit 2.0.1
[   +6 ms] SLVR:   derived: dio_cookie_manager 2.0.0
[   +2 ms] SLVR:   derived: dio 4.0.1
[   +3 ms] SLVR:   derived: cookie_jar 3.0.1
[   +8 ms] SLVR:   derived: protobuf ^2.0.0
[   +2 ms] SLVR:   derived: path_provider ^2.0.2
[   +1 ms] SLVR:   derived: intl ^0.17.0
[   +1 ms] SLVR:   derived: get_storage 2.0.3
[   +1 ms] SLVR:   derived: get 4.3.8
[   +1 ms] SLVR:   derived: flutter_screenutil 5.0.0
[   +1 ms] SLVR:   derived: flutter_boost from git
[   +1 ms] SLVR:   derived: cupertino_icons ^1.0.4
[   +5 ms] SLVR:   derived: flutter from sdk
[   +2 ms] IO  : Spawning "cmd /c git --version" in D:\WokSpance\ht-rn\android_flutter\testf\.
[  +93 ms] IO  : Finished git. Exit code 0.
[   +3 ms]     | stdout:
[   +2 ms]     | | Active code page: 65001
[   +2 ms]     | | git version 2.19.0.rc0.windows.2
[   +2 ms]     | Nothing output on stderr.
[   +2 ms] IO  : Spawning "cmd /c git.cmd --version" in D:\WokSpance\ht-rn\android_flutter\testf\.
[  +38 ms] IO  : Finished git.cmd. Exit code 1.
[   +4 ms]     | stdout:
[   +2 ms]     | | Active code page: 65001
[   +1 ms]     | stderr:
[        ]     | | 'git.cmd' is not recognized as an internal or external command,
[   +2 ms]     | | operable program or batch file.
[   +1 ms] SLVR: Version solving took 0:00:00.462999 seconds.
[   +2 ms]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (0.624s).
[   +8 ms] ERR : Cannot find a Git executable.
[   +1 ms]     | Please ensure Git is correctly installed.
[   +3 ms] FINE: Exception type: ApplicationException
[  +45 ms] FINE: package:pub/src/utils.dart 507:5                                 fail
[   +3 ms]     | package:pub/src/git.dart 52:5                                    run
[   +2 ms]     | package:pub/src/source/git.dart 521:32                           BoundGitSource._deleteGitRepoIfInvalid
[   +2 ms]     | package:pub/src/source/git.dart 475:11                           BoundGitSource._ensureRepoCache
[   +2 ms]     | package:pub/src/source/git.dart 259:13                           BoundGitSource.doGetVersions.<fn>
[   +2 ms]     | package:pub/src/source/git.dart 258:37                           BoundGitSource.doGetVersions.<fn>
[   +3 ms]     | package:pool/pool.dart 127:28                                    Pool.withResource
[   +7 ms]     | ===== asynchronous gap ===========================

**Comment by Alembertcn** [comment]
> I think we need more details here.
> 
> Could you try running `flutter pub get --verbose` and attaching the output?

My window donot have git.cmd.exe . I dont konw what it is.  I change git version for 2.11+ 2.19+ and 2.33+ ，but it is same problem

**Comment by sigurdm** [comment]
What happens if you run `git --version`?

You need to ensure that git is available on the `PATH` for pub to find it.

Perhaps you can follow the suggestions outlined here: https://stackoverflow.com/questions/26620312/git-installing-git-in-path-with-github-client-for-windows to add it to PATH.

**Comment by Alembertcn** [comment]
> What happens if you run `git --version`?
> 
> You need to ensure that git is available on the `PATH` for pub to find it.
> 
> Perhaps you can follow the suggestions outlined here: https://stackoverflow.com/questions/26620312/git-installing-git-in-path-with-github-client-for-windows to add it to PATH.

My git is ok and is available on the PATH 
git --version
git version 2.19.0.rc0.windows.2

only My pubspec.yaml has git depandent it has this problem

**Comment by Alembertcn** [comment]
Oh My god I have solved by read the fucking source code
it is help [https://blog.csdn.net/qq_37925231/article/details/110824760](url)


bool _tryGitCommand(String command) {
  // If "git --version" prints something familiar, git is working.
  try {
    var result = runProcessSync(command, ['--version']);

    if (result.stdout.length != 1) return false;
    final output = result.stdout.single;
    final match = RegExp(r'^git version (\d+)\.(\d+)\.').matchAsPrefix(output);
...

**Comment by ambboo514** [comment]
好家伙，最后一个帖子有用啊，终于解决这个问题了
