### ISSUE TITLE
Suggest >=3.0.0 <4.0.0 as SDK constraint in Dart 3

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3661]
See:
https://github.com/dart-lang/pub/blob/d54d52d336427fc6188d09b4b7be231735834b98/lib/src/entrypoint.dart#L897-L904

See also https://github.com/dart-lang/pub/issues/3659

----------------------

We don't want to do this until the 2.19 branch has been cut.

**Comment by jonasfj** [comment]
@sigurdm suggests we should always use the current SDK.

**Comment by sigurdm** [comment]
Or at least the same minor version.

That way we give access to the newest language features by default.
