### ISSUE TITLE
[3.0 alpha] non-null safe packages resolve via path dependencies

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#3698]
# repro steps

- create a package `pkg1` with SDK constraint `sdk: '>=2.9.0 <4.0.0'`
- create an app `app1` next to it with SDK constraint `sdk: '>=3.0.0-0 <4.0.0'`
- create a depoendency from `app` to `pkg` as a path dependency
- run `pub get`

Expected result: resolution fails as `pkg1` doesn't support null safety
Actual result: resolution completes with no error or warning

**Comment by sigurdm** [comment]
If the constraint is `sdk: '>=2.9.0 <4.0.0'` I believe it **should** resolve, as is is declaring support that includes 3.0.0.

I think such a constraint could make sense for an asset-only package.

**Comment by sigurdm** [comment]
If the constraint was `sdk: '>=2.9.0 <3.0.0' and it still resolved we would have an issue...

**Comment by mit-mit** [comment]
I see, yes I think that does indeed make sense. I tested with `<3.0.0` and that does fail.

**Comment by mit-mit** [comment]
@leafpetersen thoughts? Shall we just say this is by-design?

**Comment by leafpetersen** [comment]
Yes, this seems reasonable to me.
