### ISSUE TITLE
Install packages from Github, Gitlab and Gitea instances

### ISSUE THREAD

**Issue by trymeouteh** [dart-lang/pub#3701]
Github is a popular git service and Gitlab and Gitea allows you to self host your own git servers. It would be amazing to see the ability to install packages directly from any github repo and any gitlab or gitea instance.

And to have the ability to have packages use dependancies directly from Github, Gitlab and Gitea repository and not have to only rely on dependencies from the Pub.dev registry.

Such a feature will allow for decentralisation, private repositories and the ability to truly self host your own packages.

**Comment by sigurdm** [comment]
You can already use dependencies from git in your project: https://dart.dev/tools/pub/dependencies#git-packages

We don't allow packages on pub.dev to depend on packages outside pub.dev.

One reason for this is that we strive for repeatable builds and a reliable service.
If we had dependencies outside of pub.dev we would no longer be in control of whether something changes or gets removed.
