### ISSUE TITLE
The json report and transitive dependencies.

### ISSUE THREAD

**Issue by divan** [dart-lang/pub#3702]
Hi, I'm trying to parse `pub outdated` output to keep track of outdated repositories, and found `--json` flag. When I run `flutter pub outdated  --no-transitive --json` I get [this error](https://github.com/dart-lang/pub/blob/9d267d05d7738c066527c8f27416997987b7f868/lib/src/command/outdated.dart#L118):

```
Cannot specify both `--json` and `--transitive`
The json report always includes transitive dependencies.
```

I don't care about transitive dependencies for my purpose, only direct ones. It would work if JSON output could somehow tell which dependency is direct and which is transitive, but it doesn't tell that.

Is there any specific reason why JSON includes all dependencies? Any ideas how to achieve marchine parsable output for `pub outdated` which can help to get only direct deps?

Thank you!

**Comment by sigurdm** [comment]
Yeah - I think we should include that piece of information in the json report. I don't remember why we left it out.

For an intermediary fix, you could run `dart pub deps --json` to get the missing information and combine it with the output of `dart pub outdated`.

**Comment by divan** [comment]
Fantastic. Thank you so much @sigurdm for you work and quick response!
