### ISSUE TITLE
pub get failed (1; and attaching the relevant parts of that log file.)

### ISSUE THREAD

**Issue by maedehfff** [dart-lang/pub#3718]

**Comment by sigurdm** [comment]
What flutter version are you using?

Try running `flutter pub pub get -v` and attach the output.

**Comment by nourgh24** [comment]
Authentication error (403)
package:pub/src/authentication/client.dart 95:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 60:9    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 862:22          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 885:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 859:5           HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 669:7           HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 86:9            SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 85:14           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 82:5            SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 324:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5              GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\flutter\.pub-cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Running "flutter pub get" in flutter_tools...
pub get failed (1; and attaching the relevant parts of that log file.)

I have this problem how can i solve it ؟؟؟؟

**Comment by sigurdm** [comment]
@nourgh24 

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china
