### ISSUE TITLE
`dart pub token add` should sanity check the token

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3725]
We should validate that tokens consistent of characters that can be encoded in a header value.

Maybe we should stick to what is allowed in oauth bearer tokens:
```
     b64token    = 1*( ALPHA / DIGIT /
                       "-" / "." / "_" / "~" / "+" / "/" ) *"="
     credentials = "Bearer" 1*SP b64token
```

So maybe it just has to match `[a-zA-Z0-9._~+/=-]*`, then we won't get any weird errors from http.

**Comment by sigurdm** [comment]
We should probably add this to the documentation too.
