### ISSUE TITLE
Missing extension byte (at offset 69) dart:isolate  _RawReceivePortImpl._handleMessage

### ISSUE THREAD

**Issue by dushyant-yadav-cox** [dart-lang/pub#3727]
[pub_log.txt](https://github.com/dart-lang/pub/files/10382793/pub_log.txt)

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-x64, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/Dushyantyadav/FlutterDEV/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/Dushyantyadav/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/Dushyantyadav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Dushyantyadav@IN-C02D72Z8MD6M trait-ro-flutter %

**Comment by sigurdm** [comment]
The error comes from utf8-decoding - unfortunately with no trace of where we are decoding something bad.

Is this a persistent  issue?

Likely this is something we read from the pub-cache without proper exception-handling. In that case it smells like a corrupted pub cache.

If this is persistent we would love to be able to reproduce it. Try moving your pub-cache to a different location temporarily, and running again:

```
mv /Users/Dushyantyadav/FlutterDev/flutter/.pub-cache /Users/Dushyantyadav/FlutterDev/flutter/.pub-cache_tmp
```

You can restore by moving it back.

**Comment by dushyant-yadav-cox** [comment]
getting the same error again
[pub_log.txt](https://github.com/dart-lang/pub/files/10400966/pub_log.txt)
 .ZSHRC FILE 
 export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export ANDROID_NDK_HOME=$HOME/Library/Android/sdk/ndk/25.1.8937393
export PATH=$PATH:$HOME/flutter/bin

**Comment by sigurdm** [comment]
Is this only happening with this dependency?
```
  trait_core_module:
    git:
      url: git@ghe.coxautoinc.com:Mobility-Fleet-Management/trait-core-module.git
      ref: trait-ro
```

Could you try narrowing down a smallest pubspec.yaml displaying this bug?

**Comment by dushyant-yadav-cox** [comment]
no the same code  successfully run in 3 different machine

**Comment by sigurdm** [comment]
Is this still happening? If so, please open a new issue with any new details.

I'll close this as obsolete for now...
