### ISSUE TITLE
Get doesn't fail correctly on some non-null-safe SDK constraints

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#3730]
Current `pub` rejects the SDK constraint `sdk: '>=2.9.0 <3.0.0'` with:

```
$ dart pub get
Resolving dependencies...
The current Dart SDK version is 3.0.0-109.0.dev.

Because oldapp doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.9.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```

This is as expected.

But resolves with no errors or warnings if using `sdk: '>=2.9.0 <4.0.0'`, which is not expected.

It should fail on any lower constraint that isn't 2.12 or above, regardless of what the upper constraint is.

**Comment by sigurdm** [comment]
How about packages that contain only assets, and thus wants to declare that they work both before and after null-safety?

**Comment by sigurdm** [comment]
I believe we would already get an analyzer warning in 3.0 on any code inside a library with such a constraint. Such a warning would also show up before publishing.

@jonasfj suggest refusing these at the server (@isoos suggests if they contain any dart files).

**Comment by mit-mit** [comment]
> How about packages that contain only assets, and thus wants to declare that they work both before and after null-safety?

I don't think we support a single package for those. In Dart 3 and beyond, everything has null safety.

**Comment by mit-mit** [comment]
From in-office discussion:
- `>=2.12.0 <3.0.0` succeeds as the Dart 3 backwards compatibility overrides the upper constraint (`<3.0.0`) when the lower constraint has null safety (2.12.0 or later) and the upper constraint is exactly `3.0.0`
- `>=2.9.0 <3.0.0` fails as the lower constraint is outside the backwards compatibility window
- `>=2.9.0 <4.0.0` succeeds as as 3.0.0 is within the listed range

In essence, the current `pub` behavoir is to validate matches the current SDK is within the listed range. There is no validation of language versions in the solver.

This presents an issue as the analyzer only looks for invalid language versions *outside the entry point*. When pub resolves the `>=2.9.0 <4.0.0` constraint, it write this `package_config.yaml`:

```
    {
      "name": "oldapp",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.9"
    }

```

This app passes analysis, as again, the analyzer currently only looks for language markers that select invalid language versions (`illegal_language_version_override`; notice the `override` part) and importing of invalid versions (`import_of_legacy_library_into_null_safe`). Neither of these catch the case where the entry point has an old language version.

The CFE does catch it:
```
$ dart compile kernel bin/oldapp.dart
Compiling bin/oldapp.dart to kernel file bin/oldapp.dill.
Info: Compiling with sound null safety.
bin/oldapp.dart: Error: Library doesn't support null safety.
```

To repro this, take the app here, and change the constraint to `>=2.9.0 <4.0.0`:
https://github.com/mit-mit/sandbox/tree/master/dart-3/backcompat/olddart

**Comment by mit-mit** [comment]
cc @leafpetersen @lrhn @bwilkerson wdyt?

**Comment by leafpetersen** [comment]
> Neither of these catch the case where the entry point has an old language version.

This seems like an analyzer bug.  Otherwise, everything seems reasonable enough here to me.

**Comment by mit-mit** [comment]
Filed https://github.com/dart-lang/pub/issues/3733 for the analyzer part

**Comment by sigurdm** [comment]
Can we close this issue - or is there anything for pub to do?

**Comment by mit-mit** [comment]
Yes, I think we can, thanks!

**Comment by jonasfj** [comment]
Reopen because https://github.com/dart-lang/sdk/issues/51007 is apparently hard to fix. And since there is no practical use cases for `>=2.9.0 <4.0.0`.

So let's just straight up forbid these kind of SDK constraints in:
 * the root `pubspec.yaml` used by `dart pub get`.
 * when packages are uploaded to pub.dev
