### ISSUE TITLE
`dart pub add` descriptor help suggests broken syntax

### ISSUE THREAD

**Issue by parlough** [dart-lang/pub#3749]
1. The descriptor examples don't include a colon (`:`) before the descriptor
2. The descriptor examples are surrounded with single quotes (`'`) which at least fails for me in ZSH. Double quotes do work though.
3. The commands are surrounded in backticks (`) for code formatting, but my terminal (and I'm assuming many?) won't format these as code causing potential confusion.

Help message for reference:

```
For example:
  * Add a hosted dependency at newest compatible stable version:
    `dart pub add foo`
  * Add a hosted dev dependency at newest compatible stable version:
    `dart pub add dev:foo`
  * Add a hosted dependency with the given constraint
    `dart pub add foo:^1.2.3`
  * Add multiple dependencies:
    `dart pub add foo dev:bar`
  * Add a path dependency:
    `dart pub add 'foo{"path":"../foo"}'`
  * Add a hosted dependency:
    `dart pub add 'foo{"hosted":"my-pub.dev"}'`
  * Add an sdk dependency:
    `dart pub add 'foo{"sdk":"flutter"}'`
  * Add a git dependency:
    `dart pub add 'foo{"git":"https://github.com/foo/foo"}'`
  * Add a git dependency with a path and ref specified:
    `dart pub add \
      'foo{"git":{"url":"../foo.git","ref":"branch","path":"subdir"}}'`
```

Related issue for documenting the syntax on dart.dev: https://github.com/dart-lang/site-www/issues/4514

\cc @MaryaBelanger

**Comment by sigurdm** [comment]
1. These are just a typo - thanks for noticing - will fix!
2. I tried this command in zsh, and it seems to work for me:
  ```
  % dart pub add \
        'pana:{"git":{"url":"https://github.com/dart-lang/pana","ref":"master","path":"."}}'
  Resolving dependencies... 
  + csslib 0.17.2
  + html 0.15.1
  + markdown 6.0.1
  + pana 0.21.25 from git https://github.com/dart-lang/pana at bab826
  + safe_url_check 1.1.0
  Changed 5 dependencies!
  ```
3. The backticks are supposed to indicate that what they surround is code to be copy-pasted. Kind of pseudo-markdown... Not sure what is best practice here...

**Comment by sigurdm** [comment]
Closing, please reopen if you think we need to address points 2 and 3.

**Comment by parlough** [comment]
Thanks! I tried again with the single quotes and they seem to be working, I must have made another mistake in the syntax.

As for the backticks, I took a look at the Flutter CLI and commands tend to be wrapped in quotes or nothing at all, but quotes would likely be even more confusing here. The backticks should be fine, I just have to visually get used to them :)
