### ISSUE TITLE
`pub global run` fails for packages that were activated prior to `pub.dev` changes

### ISSUE THREAD

**Issue by gabrielgarciagava** [dart-lang/pub#3769]
# Environment

- Dart versions involved:
2.18.7 -> Globally activate a package
2.19.0 -> Run the package. It works.
2.19.1 -> Run the package. It fails.

# Problem

`pub` in the latest dart version (2.19.1) cannot run global packages that were installed prior to the `pub.dev` changes (e.g. dart 2.18.7).
I did a bisect in the pub repository and realized that the cuprit commit is the `0af889d315b02d6eb43a99805dac4fb47b65d835` which is a cherry-pick of `3ce46a32e14b76555de70afa9dc1281ab999159c`

Steps to reproduce:
- Checkout dart 2.18.7
- Run `dart pub global activate some_package`
- Checkout dart 2.19.0
- Run `dart pub global run some_package:main`. It works
- Checkout dart 2.19.1
- Run `dart pub global run some_package:main`. It does not work. It looks to `.pub-cache/hosted/pub.dev/some_package` trying to find the .yaml file

## Expected behavior

`dart pub global run some_package:main` should execute normally

## Actual behavior

`dart pub global run some_package:main` fails with the following error message:
`Could not find a file named "pubspec.yaml" in ".../.pub-cache/hosted/pub.dev/some_package".`

**Comment by sigurdm** [comment]
:( oh another problem with the migration

The workaround is to deactivate and activate the package again.

Not sure we will get a hotfix out for this... but highly annoying.

@jonasfj do you have good ideas here.

**Comment by gabrielgarciagava** [comment]
The workaround is exactly what we did in our build scripts haha

**Comment by gabrielgarciagava** [comment]
@sigurdm I guess this is not going to be addressed anymore, right? We are now already in dart 3, this is a problem specific to migration to 2.19.1 when some cache folders changed.

Feel free to close if you want 👍

**Comment by sigurdm** [comment]
Thanks for following up!

I guess the bug is still there in 3.0 if you upgrade straight from a 2.18 cache.
