### ISSUE TITLE
dart pub publish doesn't take pubspec_overrides.yaml into account

### ISSUE THREAD

**Issue by tamas-p** [dart-lang/pub#3781]
* In my monorepo (https://github.com/tamas-p/hisma) I have a circular dependency, but only by dev_dependencies:
   * dependencies: hisma_visual_monitor -----> hisma
   * dev_dependencies: hisma - - -> hisma_visual_monitor
 * Since using Flutter 3.7.0 (dart 2.19.0) trying `dart pub publish` in the hisma package gives me:
```
Warning: pubspec.yaml has overrides from pubspec_overrides.yaml
Resolving dependencies...
Because hisma depends on hisma_visual_monitor ^0.3.0 which doesn't match any versions, version solving failed.
```
 * Error message is correct in a sense, that yes, that version of that package in the dev_dependencies section has not yet been published (since I am doing the publishes by the `dependencies` graph, first the root, then the children).
 * if I test with Flutter 3.3.10 (dart 2.18.6), or earlier release, it works:
```
...
...
Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish hisma 0.3.0 to https://pub.dartlang.org (y/N)? 
```
 * Was the dependency check at `dart pub publish` extended to dev_dependencies on purpose at 3.7.0 (2.19.0)?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 20.04.5 LTS 5.15.0-58-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by kuhnroyal** [comment]
I have the same issue

**Comment by sigurdm** [comment]
We used to not require dependencies to resolve before publishing.

Now we require it, so we can run `dart analyze` before publishing.
To resolve against a soon-to-be-published package use a dependency_overrides entry.

See: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#pub-1

> Update dart pub publish to require a working resolution. If publishing a breaking release of mutually dependent packages use dependency_overrides to obtain a resolution.

**Comment by kuhnroyal** [comment]
Yeah, the overrides are what is not working and what `pub publish` complains about.

**Comment by sigurdm** [comment]
Ah - sorry I misread.

That is indeed a bug.

But it seems we have intentional code for this: https://github.com/dart-lang/pub/blob/048e3ad2b5e1b4ebe6883addbc95722be6904a7b/lib/src/command/lish.dart#L38

@jonasfj do you remember why we didn't want to respect the pubspec_overrides file when publishing?

(A workaround while waiting for a fix could be to move the dependency_overrides temporarily inside the pubspec.yaml).

**Comment by kuhnroyal** [comment]
Adding the overrides to `pubspec.yaml` generates a publish warning.

**Comment by sigurdm** [comment]
Yes - you still get a warning, because what you test against is not what consumers of the package will see. For circular dependencies there really is no other solution.

**Comment by kuhnroyal** [comment]
I don't have anything circular, it is a simple parent -> child package layout. I have build pipelines which run `pub publish --dry-run` - they all fail now.

**Comment by sigurdm** [comment]
Right - maybe we should downgrade the warning to an info. @jonasfj WDYT?

**Comment by kuhnroyal** [comment]
The changes for #3393 which your PR partially reverts, were specifically introduced to prevent these warnings when a `pubspec_override.yaml` is used.

**Comment by sigurdm** [comment]
Ah - forgot that whole story, thanks for digging - I still think now that we agreed to allow publishing with overrides it makes sense to take the overrides file into account when doing the pre-publishing dependency resolution.

**Comment by kuhnroyal** [comment]
> Ah - forgot that whole story, thanks for digging - I still think now that we agreed to allow publishing with overrides it makes sense to take the overrides file into account when doing the pre-publishing dependency resolution.

I agree but since those overrides are not published in the end, the warning should be info and normal exit code.

**Comment by sigurdm** [comment]
Considering this fixed with https://github.com/dart-lang/pub/pull/3782 .
