### ISSUE TITLE
Cannot find git executable when running `dart pub get`

### ISSUE THREAD

**Issue by SharpnelXu** [dart-lang/pub#3799]
# Environment

- Dart version: 
  - Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "windows_x64"
- OS kind and version: 
  - Windows 10
- Are you using the Chinese community mirror or a corporate firewall?
  - No

# Problem

Cannot find git executable when running `dart pub get`. Below is the part of the output of `flutter pub get -v`

```
IO  : Spawning "cmd /c git --version" in D:\github\chaldea\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | Active code page: 936
    | | git version 2.39.2.windows.1
    | Nothing output on stderr.
IO  : Spawning "cmd /c git.cmd --version" in D:\github\chaldea\.
IO  : Finished git.cmd. Exit code 1.
    | stdout:
    | | Active code page: 936
    | stderr:
    | | 'git.cmd' is not recognized as an internal or external command,
    | | operable program or batch file.
SLVR: Version solving took 0:00:00.156820 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.232s).
ERR : Cannot find a Git executable.
    | Please ensure Git is correctly installed.
```

This is actually caused by my CMD printing the output of `chcp 936` on startup. I fixed this issue referring to https://github.com/dart-lang/pub/issues/3645 & https://blog.csdn.net/qq_37925231/article/details/110824760

However, I was thinking if it is possible to relax the git output check, which is showed in #3645 that must start exactly with `git`, and the output must be exactly one line.
```
    // from lib/src/git.dart
    if (result.stdout.length != 1) return false;
    final output = result.stdout.single;
    final match = RegExp(r'^git version (\d+)\.(\d+)\.').matchAsPrefix(output);
```

**Comment by sigurdm** [comment]
Yeah - I think it makes sense to just require the output to contain this anywhere.
