### ISSUE TITLE
pub is deprecated error message

### ISSUE THREAD

**Issue by pryme-empire10** [dart-lang/pub#3802]
pub get failed
command: "C:\src\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\src\flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "C:\Users\BOSS-PRYME\AppData\Local\Pub\Cache",
}

**Comment by AdrielCosta420** [comment]
bro, here's response

**Comment by sigurdm** [comment]
Not sure I understand the problem.

flutter is using the `dart __deprecated_pub` because it exposes an interface compatible with the old `pub` command. At some point we want to migrate flutter to use `dart pub`.

That is why it is deprecated. We don't want new users of this interface.

**Comment by alemontesdeoca** [comment]
I'm facing the same error

**Comment by sigurdm** [comment]
@alemontesdeoca 

Can you give more details? What are you trying to do, what is the command you are running, and what is the error message you are seeing.

**Comment by alemontesdeoca** [comment]
> @alemontesdeoca
> 
> Can you give more details? What are you trying to do, what is the command you are running, and what is the error message you are seeing.

I'm trying to run 'pug get' and I'm getting `pub get failed
command: "C:\src\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --directory . get --example"     
pub env: {
  "FLUTTER_ROOT": "C:\src\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\alexa\AppData\Local\Pub\Cache",
}
exit code: 1`

**Comment by sigurdm** [comment]
What version of flutter are you using?

**Comment by sigurdm** [comment]
What is the pubspec.yaml?

Did this use to work or is this first time you run pub get? Did you just upgrade?

**Comment by alemontesdeoca** [comment]
> What is the pubspec.yaml?
> 
> Did this use to work or is this first time you run pub get? Did you just upgrade?
Before it worked ok. It started to happen last Friday when I ran "pub get"

**Yaml:**
name: public
description: description
publish_to: none

version: 20.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  firebase_app_installations: ^0.2.1+5  shared_preferences_ios: ^2.1.1
  logger: ^1.1.0
  http: ^0.13.3
  url_launcher: ^6.0.12
  intl: 0.17.0
  intl_utils: ^2.4.0
  camera: ^0.10.0+4
  shared_preferences: ^2.0.15
  path_provider: ^2.0.7
  google_maps_flutter: ^2.1.8
  package_info: ^2.0.2
  flutter_svg: ^2.0.2 
  flutter_image_compress: ^1.1.0
  stack_trace: ^1.10.0
  collection: ^1.15.0
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.0.4
  firebase_remote_config: ^3.0.4
  cloud_firestore: ^4.0.4
  firebase_analytics: ^10.0.4
  firebase_auth: ^4.1.1
  dotted_border: ^2.0.0+1
  path_drawing: ^1.0.1
  # flutter_bloc: ^7.3.3
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  equatable: ^2.0.3
  qr_flutter: ^4.0.0
  image_picker: ^0.8.4+4
  signature: ^5.1.0
  email_validator: ^2.0.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.3
  device_info: ^2.0.2
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  json_annotation: ^4.1.0
  weather: ^2.0.1
  percent_indicator: ^4.2.2
  shimmer: ^2.0.0
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  flutter_animarker: ^3.2.0
  crypto: ^3.0.1
  multiple_localization: ^0.3.0
  sentry_flutter: ^6.18.2
  dart_ipify: ^1.1.1
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  sign_in_with_apple: ^4.1.0
  store_redirect: ^2.0.0
  permission_handler: ^10.2.0
  mobile_scanner: ^3.0.0
  package_info_plus: ^3.0.1
  google_sign_in: ^5.4.4
  lottie: ^2.2.0
  restart_app: ^1.1.2
  flutter_html: ^3.0.0-alpha.6
  firebase_app_installations: ^0.2.1+5
  geocoding: ^2.0.5
 
dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4 
  mocktail: ^0.3.0
  modular_test: ^2.0.0
  patrol: ^1.0.0

patrol:    

flutter:
  uses-material-design: true
  assets:

**Comment by alemontesdeoca** [comment]
> What version of flutter are you using?

I'm using version 3.7.5 stable

**Comment by sigurdm** [comment]
Could you try running
```
dart pub get
```
and paste the output?

Please use [code fences](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by sigurdm** [comment]
Hmm, that seemed to work - weird.

Could you paste the output of
```
flutter pub get --verbose
```
?

**Comment by sigurdm** [comment]
It seems we have broken the output of a `flutter pub` failure.

**Comment by sigurdm** [comment]
@individual-777 could you try running
```
flutter --verbose pub get
```
And pasting the full output?

Please use [code fences](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by sigurdm** [comment]
Realizing this looks like https://github.com/flutter/flutter/issues/118314 that has already been fixed.

Try using the beta-channel.

**Comment by khaldoonAlmashwli** [comment]
> Hmm, that seemed to work - weird.
> 
> Could you paste the output of
> 
> ```
> flutter pub get --verbose
> ```
> 
> ?

I have the same error i need help

**Comment by khaldoonAlmashwli** [comment]
flutter pub get
Running "flutter pub get" in untitled3...
Resolving dependencies... (10.0s)

**Comment by MoElkilany** [comment]
pub get failed command: "/Users/mohamedkilany/Developer/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory . get --example" pub env: { "FLUTTER_ROOT": "/Users/mohamedkilany/Developer/flutter", "PUB_ENVIRONMENT": "flutter_cli:get", "PUB_CACHE": "/Users/mohamedkilany/.pub-cache", } exit code: 69

what is the problem here!?

**Comment by Khiemvx23** [comment]
[   +4 ms] pub get failed
           command: "/Users/khiemvx/development/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --verbose --directory . get --example"
           pub env: {
             "FLUTTER_ROOT": "/Users/khiemvx/development/flutter",
             "PUB_ENVIRONMENT": "flutter_cli:get",
             "PUB_CACHE": "/Users/khiemvx/.pub-cache",
           }
           exit code: 69
           
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:468:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:346:5)
           <asynchronous suspension>
           #3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:140:7)
           <asynchronous suspension>
           #4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:175:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

I'm facing with the same issue, can't create new flutter project also run a project existed

**Comment by bakboem** [comment]
pub get failed
command: "/Users/bakbeom/install/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/bakbeom/install/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:verify:run",
  "PUB_CACHE": "/Users/bakbeom/.pub-cache",
}
exit code: 1

**Comment by fehmidevoteam** [comment]
you should give permission to your project build folder and your entire project folder and change the owner
sudo chown -R your_mac_username: path_to_your_project/build

you can check this link for more details:
https://macpaw.com/fr/how-to/permission-denied-terminal

**Comment by rxvivek** [comment]
I am facing same issue,
 i am working on flutter migration, i am using flutter 3.7.10 v, when i moved one branch to other i need to use updated version of the flutter. it's working fine when i used low version of my project, but i want to upgrade my project in different branch, I am facing issue.

400 Bad Request trying to find package numerus at https://pub.dev.
pub get failed
command: "/Users/vivek.mavani/fvm/versions/3.7.10/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/vivek.mavani/fvm/versions/3.7.10",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/vivek.mavani/.pub-cache",
}
exit code: 69

**Comment by MaundoMoru** [comment]
I think this error occurs if you try to use deprecated version of dependencies on you flutter app.

**Comment by tntkhang** [comment]
Finally, I can solve this problem by running: flutter channel beta
After that all flutter cmd work without "_deprecated_pub --directory...."error anymore.
More info about that you can read on this: https://stackoverflow.com/a/55909127

**Comment by wenjunh111** [comment]
> 


  file_picker: ^5.2.11         remove this
