### ISSUE TITLE
"Filename too long" message on some git packages

### ISSUE THREAD

**Issue by bdlukaa** [dart-lang/pub#3803]
# Environment

- Dart version (run `dart --version`): 3.0.0-231.0.dev (dev)
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): Windows 11
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

When using some git packages, git fails to clone the project when the name of some files is too long. One example is the following package:

```yaml
  awesome_notifications:
    git:
      url: https://github.com/HannesGitH/awesome_notifications.git
```

## Expected behavior

`pub get` completed without issues

## Actual behavior

"Filename too long" message is print into the console

## --trace output

```
Resolving dependencies...
Git error. Command: `git clone C:\hostedtoolcache\windows\flutter\master-master-x64/.pub-cache\git\cache\awesome_notifications-95[8](https://github.com/bluecherrydvr/unity/actions/runs/4257681667/jobs/7408086879#step:5:9)7835634505e68ed[9](https://github.com/bluecherrydvr/unity/actions/runs/4257681667/jobs/7408086879#step:5:10)870414ac2264493afefca C:\hostedtoolcache\windows\flutter\master-master-x64/.pub-cache\git\awesome_notifications-7513b844fe9e70b9b9400345a2348ee863329e4d`
stdout: 
stderr: Cloning into 'C:\hostedtoolcache\windows\flutter\master-master-x64/.pub-cache\git\awesome_notifications-7513b844fe9e70b9b9400345a2348ee863329e4d'...
done.
error: unable to create file example/android/awn_core/src/main/java/me/carda/awesome_notifications/core/broadcasters/receivers/DismissedNotificationReceiver.java: Filename too long
error: unable to create file example/android/awn_core/src/main/java/me/carda/awesome_notifications/core/broadcasters/receivers/NotificationActionReceiver.java: Filename too long
error: unable to create file example/android/awn_core/src/main/java/me/carda/awesome_notifications/core/broadcasters/receivers/ScheduledNotificationReceiver.java: Filename too long
error: unable to create file example/android/awn_core/src/main/java/me/carda/awesome_notifications/core/completion_handlers/NotificationThreadCompletionHandler.java: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

exit code: [12](https://github.com/bluecherrydvr/unity/actions/runs/4257681667/jobs/7408086879#step:5:13)8
```

## Additional info:

Cloning is done [here](https://github.com/dart-lang/pub/blob/09c29722deefc085f841297cbf9782d3d882bc3d/lib/src/source/git.dart#L643-L664). To fix the issue, the function can pass `-c core.longpaths=true` as an argument to `git clone`.

As an workaround, `git config --system core.longpaths true` can be run on the client to fix the issue.

**Comment by sigurdm** [comment]
> To fix the issue, the function can pass -c core.longpaths=true as an argument to git clone.

Interesting.

Are there any downsides to passing this argument? Why doesn't git on Windows always enable this?

**Comment by BreSmit521** [comment]
So, I believe there might be more to this issue as well. When pulling repositories from private repositories that have files that exceed the filename limit `flutter pub get` fails entirely due to being unable to delete the temp file in the pub cache (Tested also on Windows 10).   

If I point to a GitHub repo hosting the exact same package I receive the same error reported by @bdlukaa. 

From a private repository though, the error tells me that the temp file is still in use by another program. Not completely sure if it's related, but it does seem odd the only time I experience this behavior is when it exceeds Windows filename limits.

**Comment by sigurdm** [comment]
I think this should be fixed in Git itself, an given that there is a work-around I'll close this as a won't-fix.

**Comment by alon-one-zero** [comment]
the fix in my case was to add it globally
git config --global core.longpaths true

**Comment by Nihal014** [comment]
file name too long then just add this command in terminal.
git config --global core.longpaths true
