### ISSUE TITLE
Pub.dev not accessible

### ISSUE THREAD

**Issue by FernandaKey** [dart-lang/pub#3808]
# Environment

- Dart version (run `dart --version`): 2.19.2
Flutter version 3.7.5 channel stable
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):
Windows 10 and macOS Monterey 12.6.3
- Are you using the Chinese community mirror or a corporate firewall?
no

# Problem

I can't access pub.dev at all. Ping returns a timeout, when I try accessing on the browser I get a security message saying my connection is not private. 
NET::ERR_CERT_COMMON_NAME_INVALID

If I use 4g it works fine. If I use my wifi/cable it doesnt. The only thing I did before the error started occurring was updating flutter to the latest version.
  
I already lost a day of work trying to figure this out, I have no idea what it could be and I tried a bunch of stuff already. Reinstalled everything, clean cache, change security firewall, uninstalled anti virus, got in touch with my network provider. nothing works. 

  Was the problem with a specific package you were trying to fetch? no

  If relevant, what does the `pubspec.yaml` file for your project look like:

```yaml
<copy/paste pubspec.yaml>
```

## --trace output

```
<copy/paste the full output>
```

**Comment by sigurdm** [comment]
Sounds like a problem with your isp's setup vs. our dns setup.

Might be that our IPv6 setup could be improved.

**Comment by sigurdm** [comment]
Closing as I don't think we can do much here :/
