### ISSUE TITLE
Problem when starting a new flutter project using VS Code

### ISSUE THREAD

**Issue by indrariansyah** [dart-lang/pub#3809]
Dear Support Team,

Appreciate your kind help with the attached issue log. I'm facing a problem when starting a new flutter project using Visual Studio Code. Thank you.

Regards,
Indra R.

[pub_log.txt](https://github.com/dart-lang/pub/files/10866391/pub_log.txt)

**Comment by sigurdm** [comment]
For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china

**Comment by indrariansyah** [comment]
> For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china

Hi @sigurdm thanks for the info. Other than that, is there any specific info on what kind of network restrictions in my laptop so that I can fix it by myself?

**Comment by sigurdm** [comment]
Sorry for never coming back here.

Is this still a problem.

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network. Maybe we can see something.

Also - where are you located?
