### ISSUE TITLE
Timeout when downloading dependencies from pub.dartlang.org, while pub.dev itself is accessible

### ISSUE THREAD

**Issue by ahmednfwela** [dart-lang/pub#3836]
# Environment

- Dart version: Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "windows_x64"
- OS kind and version: Windows 10 Pro N 19045.2728
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem

doing dart pub get fails due to timeout
```
IO  : Attempt #7 for downloading "https://pub.dartlang.org/packages/built_value_generator/versions/8.4.4.tar.gz"
IO  : Attempt #7 for downloading "https://pub.dartlang.org/packages/one_of_serializer/versions/1.5.0.tar.gz"
IO  : Attempt #7 for downloading "https://pub.dartlang.org/packages/dart_style/versions/2.3.0.tar.gz"
IO  : Attempt #7 for downloading "https://pub.dartlang.org/packages/one_of/versions/1.5.0.tar.gz"
IO  : HTTP GET https://pub.dartlang.org/packages/built_value_generator/versions/8.4.4.tar.gz
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 81C11413-1E6E-4F43-B12C-EAD3B83448C9
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.19.4
```

I can't even download these files via browser

**Comment by gsavignac** [comment]
I have the same problem on linux mint 21. I couldn't find a solution

`IO  : HTTP GET https://pub.dev/api/packages/test
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: get
    | X-Pub-Session-ID: D0B2BE45-0316-4D72-8857-0A1CFA66E406
    | X-Pub-Environment: flutter_cli:get
    | user-agent: Dart pub 2.19.4
`

it only stays that way for a long time

**Comment by gsavignac** [comment]
this worked for me in Linux

```
export PUB_HOSTED_URL=https://pub.flutter-io.cn 
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```

in Windows you can try this

```
name: PUB_HOSTED_URL value: https://pub.flutter-io.cn/
name: FLUTTER_STORAGE_BASE_URL value: https://storage.flutter-io.cn/
```
