### ISSUE TITLE
pub get error in flutter

### ISSUE THREAD

**Issue by hoaghabo** [dart-lang/pub#3859]
--

[flutter_application_2] flutter pub get
Running "flutter pub get" in flutter_application_2...
Resolving dependencies...
Authentication error (403)
package:pub/src/authentication/client.dart 90:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 56:7    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 364:30                   RequestSending.fetchAsStream
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1081:28         HostedSource._download.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 283:60                   retryForHttp.<fn>.<fn>
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                      Pool.withResource
===== asynchronous gap ===========================
package:pub/src/http.dart 283:19                   retryForHttp.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 723:14                  retry
===== asynchronous gap ===========================
package:pub/src/http.dart 282:10                   retryForHttp
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1078:9          HostedSource._download.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 128:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1073:7          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 887:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1036:12         HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 784:21          HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 230:20           SystemCache.downloadPackage
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 70:20           SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 68:18           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 65:32           SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372:25             Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 60:5              GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\Hussein\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub get failed
command: "C:\Users\Hussein\Documents\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\Users\Hussein\Documents\flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "C:\Users\Hussein\AppData\Local\Pub\Cache",
}
exit code: 1

exit code 1

my error completely
who can help me?

**Comment by sigurdm** [comment]
What version of flutter are you using?
Where are you located?

For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china

**Comment by Dawid-Dlugosz** [comment]
I'm from Poland and I have the same issue. 
Flutter version 3.10.2
Dart version 3.0.2

**Comment by sigurdm** [comment]
@Dawid-Dlugosz 

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by Dawid-Dlugosz** [comment]
I have this error after update dependency, so i back to previous version. In my case package that caused the error was:   `package_info_plus:`

**Comment by sigurdm** [comment]
@Dawid-Dlugosz

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

Can you also give the output of `flutter pub get --verbose`?
