### ISSUE TITLE
Have a option to choose a different file to refer instead of pubspec.yaml

### ISSUE THREAD

**Issue by W1N3** [dart-lang/pub#3868]
## Use case

In a scenario where we have multiple project dependencies which the maintenance is provided by the company itself, those various projects can have feature branches that is simultaneously dependent.

Having a vanilla CI/CD, it will be harsh to github actions check be sincronized - unless we approve those multiple branches pull requests in a chained dependent way - because the pubspec is refered to the root branch of the project.

## Proposal

Given the scenario described above, would be nice if the `dart pub get` have a cli option to specify a different *.yaml file to be the source of dependencies of the package/project.

Something like `dart pub get --custom-deps=<path to file>.yaml` or `dart pub get --custom-pubspec=<path to file>.yaml`.

Then this feature will smooth CI/CD scripting and maintenance.

**Comment by W1N3** [comment]
As a CLI option or by file handling (making `mv pubspec.yaml pubsec_main.yaml && mv pubspec_dev.yaml pubspec.yaml` when is a development context and making the inverse to back to)?

My proposal is a more general approach due to the hardness that we are dealing, which can cover other cases.

**Comment by sigurdm** [comment]
I don't think we're interested in supporting this.

Our best suggestion is to write a script that moves the files around.

**Comment by sigurdm** [comment]
If others have similar needs, please elaborate on the use-case.
