### ISSUE TITLE
pub get not working

### ISSUE THREAD

**Issue by Inzimam786** [dart-lang/pub#3882]
pub get failed
command: "C:\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\HP\AppData\Local\Pub\Cache",
}
exit code: 65

**Comment by sigurdm** [comment]
What version of flutter are you on?

Is it working now?
