### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by binkapS** [dart-lang/pub#3884]
pub get failed
command: "/home/binkap/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory
snap/flutter/common/flutter/packages/flutter_tools get --example"
pub env: {
  "FLUTTER_ROOT": "/home/binkap/snap/flutter/common/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
}
exit code: 69

**Comment by sigurdm** [comment]
What version of flutter are you on?

**Comment by binkapS** [comment]
3.7 release

**Comment by sigurdm** [comment]
Is this a persistent problem?

How is your pubspec.yaml?
Could you try doing `flutter pub get --verbose`?
Could you try using the flutter beta channel?
