### ISSUE TITLE
its happend when i'try to import a sharedprefrence on flutter any help plz?? notes sharedprefrence its  not working on my laptop 

### ISSUE THREAD

**Issue by anas2027** [dart-lang/pub#3899]
[newloginwithlaravel] flutter pub get
Resolving dependencies...
Authentication error (403)
package:pub/src/authentication/client.dart 92:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 56:7    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/http.dart 373:30                   RequestSending.fetchAsStream
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1136:28         HostedSource._download.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 287:58                   retryForHttp.<fn>.<fn>
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                      Pool.withResource
===== asynchronous gap ===========================
package:pub/src/http.dart 287:17                   retryForHttp.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 721:14                  retry
===== asynchronous gap ===========================
package:pub/src/http.dart 286:10                   retryForHttp
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1133:9          HostedSource._download.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 130:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1128:7          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 962:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1090:12         HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 821:21          HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 239:20           SystemCache.downloadPackage
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 70:20           SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 68:18           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 65:32           SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 383:25             Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 73:5              GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\ASUS_PC\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
exit code 1

**Comment by anas2027** [comment]
icant even import it on my project ?

**Comment by sigurdm** [comment]
Hio @anas2027 

Where are you located?

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

For general network restrictions, consider trying the Chinese community mirror: https://docs.flutter.dev/community/china
