### ISSUE TITLE
This is an unexpected error. The full log and other details are collected in:      C:\Users\pc\AppData\Local\Pub\Cache\log\pub_log.txt

### ISSUE THREAD

**Issue by lina-reslan** [dart-lang/pub#3905]

**Comment by lina-reslan** [comment]
i have problem when i try to create new flutter project using cmd
and i have this Error:
This is an unexpected error. The full log and other details are collected in: C:\Users\pc\AppData\Local\Pub\Cache\log\pub_log.txt
i deleted pub folder in local/Pub/ but problem not solved

**Comment by jonasfj** [comment]
If you are comfortable sharing the log file from `C:\Users\pc\AppData\Local\Pub\Cache\log\pub_log.txt` please upload it as a gist and give us a link to it.
