### ISSUE TITLE
Update pub run URI

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#3906]
https://github.com/dart-lang/pub/blob/2c2eb2cd31ceeb47aa37dc131f98c26ce9af11d5/lib/src/command/run.dart#L23

https://dart.dev/tools/pub/cmd/pub-run redirects to https://dart.dev/tools/dart-run

**Comment by jonasfj** [comment]
Yeah, I guess the argument is that there is no documentation for `dart pub run` anymore, just a redirect to docs for `dart run` (which replaced `dart pub run`).
