### ISSUE TITLE
i dont know

### ISSUE THREAD

**Issue by haidarkali** [dart-lang/pub#3912]
pub get failed
command: "/home/haidara/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub
--color --directory flutter/packages/flutter_tools get --example"
pub env: {
  "FLUTTER_ROOT": "/home/haidara/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/root/.pub-cache",
}
exit code: 1

**Comment by jonasfj** [comment]
Can you explain what you're trying to do?

What SDK are you using, etc?
