### ISSUE TITLE
Increase the level of lint of the pub code base

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3918]
We use a large chunk of the pub code base to provide a familiar interface when working with the onepub private package repository.

We do this by merging the pub code into our onepub code base.
Onepub uses a much more aggressive set of lints which results in the pub code show up with hundreds of errors.

We would like to contribute to the pub code by gradually increasing the lints that apply to pub.

The intent would be to enable one lint at a time and raise a PR for that lint.

The first effort would be to enable the 'strict-casts: true' setting.

Whilst these changes will benefit future onepub merges I believe that stronger linter will also be of value to the broader community for obvious reasons.

Would a series of PRs of this nature be accepted?

**Comment by sigurdm** [comment]
One one hand yes, I think we would be willing to accept such PRs.

On the other hand, you should not be importing pub as a library. We will break anything at any time. There is a reason it is not published as a package on pub.dev.

Please integrate with the dart CLI instead.

**Comment by bsutton** [comment]
We will review the use of pub as a library, I don't actually remember why we went in that direction.

I'm still happy to continue through the linting process if you are happy to accept the lints.

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pub/pull/3919
