### ISSUE TITLE
Random error after updating to Flutter 3.10

### ISSUE THREAD

**Issue by almanza1112** [dart-lang/pub#3926]
[pub_log.txt](https://github.com/dart-lang/pub/files/11511738/pub_log.txt)
Hello I recently upgrading to flutter 3.10.0 a couple days ago and been working on my app since then successfully building it several times since the update. Today I tried to start working on it and keep getting this error. 

I tried flutter clean and flutter pub get and it keeps producing the same error.

Don't know what happen overnight that caused this but I am literally stuck.

**Comment by almanza1112** [comment]
[pub_log.txt](https://github.com/dart-lang/pub/files/11511710/pub_log.txt)

**Comment by sigurdm** [comment]
Seems like your lockfile is corrupted 

Try deleting `pubspec.lock` and running `flutter pub get` again.

This is still a bug, pub should not crash.
