### ISSUE TITLE
Pub Publish Incorrectly Publishes 'packages' folder

### ISSUE THREAD

**Issue by rayliverified** [dart-lang/pub#3948]
# Environment

Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "windows_x64"

# Problem

Publishing packages is bugged and broken for me because the excluded 'packages' folder is no longer excluded. When publishing my packages NavigationUtils and ResponsiveFramework, I notice that the previously excluded 'packages' folder is now included in the published files.

1. Clone a package (https://github.com/Codelessly/ResponsiveFramework)
2. Run `flutter pub publish --dry-run`.
3. See that the 'packages' folder is included in the list of files to publish.
4. Publishing results in an error because the files in the packages folder are too large. `* Your package is 193.0 MB. Hosted packages must be smaller than 100 MB.`

![image](https://github.com/dart-lang/pub/assets/19896174/2c450ba9-5e12-4817-a07d-6857a09b125b)

## Expected behavior

The 'packages' folder is excluded.

From the Flutter publishing documentation [https://dart.dev/tools/pub/publishing#What%20Files%20Are%20published?](https://dart.dev/tools/pub/publishing#What%20Files%20Are%20published?)

![image](https://github.com/dart-lang/pub/assets/19896174/f8284e9b-c832-4e92-9f04-36a8267e8b13)

## Actual behavior

The 'packages' folder is included with the publish files.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
[X] Windows Version (Unable to determine Windows version (command `ver` returned Microsoft Windows [Version 6.1.7601]))
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2022.2)
[√] VS Code, 64-bit edition (version 1.70.3)
[√] Connected device (3 available)
[√] Network resources
```

</details>

Reference: https://github.com/flutter/flutter/issues/129067

**Comment by rayliverified** [comment]
@huycozy verified this as well.

https://github.com/flutter/flutter/issues/129067#issuecomment-1596838882

**Comment by sigurdm** [comment]
Sorry, here the documentation is out of date.

Not publishing the packages folder was due to how `pub` would once make a folder called `packages` full of symlinks to the dependencies. Now we use the `.dart_tool/package_config.json` file to do this.

We removed special treatment of the packages folder here: https://github.com/dart-lang/pub/pull/3828

If you want to have a folder ignored when publishing, you can consider using a `.pubignore` file. It is written with syntax like a `.gitignore` (and will take precedence over a `.gitignore` in the same folder.

See more here: https://stackoverflow.com/questions/69760021/what-should-be-ignored-in-darts-pubignore

**Comment by rayliverified** [comment]
Thank you very much!
