### ISSUE TITLE
 Bad state: Could not find 7zip when I'm run the "flutter pub get" command.  And "flutter doctor" command doesn't work

### ISSUE THREAD

**Issue by AK60YT** [dart-lang/pub#3961]
Running "flutter pub get" in flutter_tools...                   
Bad state: Could not find 7zip.

package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip

package:pub/src/io.dart                   _pathTo7zip

package:pub/src/io.dart 827:22            extractTarGz.<fn>

===== asynchronous gap ===========================

package:pub/src/io.dart 773:12            withTempDir

===== asynchronous gap ===========================

package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache

===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>

===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get

===== asynchronous gap ===========================

package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
This is an unexpected error. Please run

**Comment by sigurdm** [comment]
Sounds like you are running a very old flutter version. We have not used 7zip for more than a year. Consider upgrading.

Closing as obsolete
