### ISSUE TITLE
`dart pub publish --dry-run` should check name availability

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#3966]
# Problem

You only learn about a name conflict when actually trying to publish. It would be better if the server checks could also be dry-run.

## Expected behavior

```
$ dart pub publish --dry-run
[...]
Package has 0 warnings.
Package name `c_compiler` is too similar to another active package: `ccompilers` (https://pub.dev/packages/ccompilers).
```

## Actual behavior

```
$ dart pub publish --dry-run
[...]
Package has 0 warnings.
The server may enforce additional checks.


$ dart pub publish
[...]
Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish c_compiler 0.1.0 to https://pub.dev (y/N)? y
Uploading... (2.5s)
Package name `c_compiler` is too similar to another active package: `ccompilers` (https://pub.dev/packages/ccompilers).
```

**Comment by sigurdm** [comment]
This will not be trivial because we don't want to hard-code the naming rules in the client, so it would require new API.

@jonasfj do you think we should have an API for checking name availability, then we could even make a lint that warns you about naming conflicts up-front...

**Comment by sigurdm** [comment]
I think we have decided not to implement this.

If/when we get staged publishing it will be possible to try out names up-front, and the staged package will reserve the name, but be deleted if it is not published within X days. It would not completely solve the issue of knowing about naming conflicts up front, but make things a bit more flexible.
