### ISSUE TITLE
```flutter pub get```should allow platform constraint in yaml

### ISSUE THREAD

**Issue by techwn** [dart-lang/pub#3969]
**Use case**
When I run ```flutter pub get``` in my project, it hints me there is some conflict in two plugins for ```windows``` platform.

But my project is only for ```iOS``` and ```Android```.

**Proposal**

1. I think flutter pub get should allow me to config platforms in yaml
2. Don't get unwanted platform implementations
3. Don't check unrelated platform conflicts.

**Steps to produces the issue:**
I'm using:```flutter  3.7.12```

I include in yaml with:
```
device_info_plus: 7.0.1
share_plus: 7.0.2
```
```flutter pub get``` error hints:
```
Because share_plus 7.0.2 depends on win32 >=4.0.0 <6.0.0 and device_info_plus >=7.0.0 <8.1.0 depends on win32 >=2.7.0 <4.0.0, share_plus 7.0.2 is incompatible with device_info_plus >=7.0.0 <8.1.0.
So, because flutter_app depends on both device_info_plus 7.0.1 and share_plus 7.0.2, version solving failed.
pub get failed
command: "/Users/qxy9763/Library/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/qxy9763/Library/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/qxy9763/.pub-cache",
}
exit code: 1
```

**Comment by sigurdm** [comment]
We've sometimes discussed this, and decided not to do this. We didn't want people to have different resolutions when developing for different platforms.

The best work-around is probably to push for the plugin developers to release compatible versions, or use a `dependency_overrides` in your `pubspec.yaml`.

If we implemented https://github.com/dart-lang/pub/issues/2272, that would also possibly help working around this issue.
