### ISSUE TITLE
pub get error: Connection closed before full header was received

### ISSUE THREAD

**Issue by dumabg** [dart-lang/pub#3974]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "linux_x64"
- OS kind and version: KDE neon 5.27
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

flutter pub get takes a lot of time, and when finish, appears the error: 
Connection closed before full header was received
exit code 69

A week ago it was working fine.

Only works with China mirror  (https://docs.flutter.dev/community/china)

**Comment by sigurdm** [comment]
Where are you located?

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by sigurdm** [comment]
Could you also try running `flutter pub get --verbose` and attach the output. It might contain clues about what goes wrong.

**Comment by dumabg** [comment]
It returns to the normal around 1,5 week ago.  I disconnected the China mirror and works normally. 
I was located on Spain.
Do you need the tests?

**Comment by sigurdm** [comment]
If it is working again I don't think we need the output from those commands.

Maybe there was a problem with our ipv6 configuration vs your ISP.

Closing as we cannot replicate. Please open a new issue if this reoccurs.
