### ISSUE TITLE
Add a flag to pubspec to signify dependencies are managed externally and "pub get" should not do anything

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#3979]
The Dart SDK dependencies are managed via [DEPS](https://github.com/dart-lang/sdk/blob/main/DEPS) and running `pub get` inside one of the packages results in an additional `.dart_tool/package_config.json` being created that references packages from Pub (instead of the version written by the SDK tooling into the root). This results in broken packages with spurious errors and it's not always obvious what the cause or fix is (it's usually to delete a `.dart_tool` folder from inside the `pkg` that's broken).

For some functionality (such as using the test runner in VS Code), commands like `dart test` are used, which may trigger an implicit `pub get`. To avoid this, Dart-Code detects the SDK and disables automatic `pub get` and all of the test runner functionality. There have been [requests to support this](https://github.com/Dart-Code/Dart-Code/issues/4502) (and it's something I miss myself). There are ways to make this work with dependency_overrides, but it means additional work and it still results in superfluous package_configs that could lead to confusion.

I wonder if we could have some kind of flag in pubspec (which could be added to all of the SDK's `pkg/*/pubspec.yaml` files to signify that packages are managed externally, and will prevent `dart test` (or even `pub get`) from fetching packages or creating new `package_config.json`s:

```yaml
name: dds
version: 2.9.4
deps: external    # something like this (we can't call it dependencies :) )
```

This flag should _only_ be used to suppress fetching/resolving packages and creating `package_config.json`s and shouldn't impact anything else (for example `pub publish` for SDK packages should continue to work as they currently do).

@jonasfj @sigurdm

**Comment by sigurdm** [comment]
I like the general idea. This would also improve support for other mono-repos.

I think there was an idea floating around for marking the dependencies external by something like:
```
name: foo
version: ....
use_package_config: ../../
```

**Comment by sigurdm** [comment]
I have written a proposal-issue (that is basically this idea in more words) and closing this issue in favour of that.

https://github.com/dart-lang/pub/issues/4022

Please add any comments you have there!
