### ISSUE TITLE
exit code 1

### ISSUE THREAD

**Issue by ahmadalnaab** [dart-lang/pub#3981]
pub get failed command: `D:\sdk\flutter\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --directory . get --example" pub env: {   "FLUTTER_ROOT": "D:\sdk\flutter\flutter",   "PUB_ENVIRONMENT": "flutter_cli:get",   "PUB_CACHE": "C:\Users\User\AppData\Local\Pub\Cache", } exit code: 1`

**Comment by sigurdm** [comment]
What version of flutter are you using?
What OS
What command were you running?

Could you try `flutter pub get --verbose` and attach the output?
