### ISSUE TITLE
PubGrub: Guidance for adding graph location aware exclusions and overrides

### ISSUE THREAD

**Issue by baron1405** [dart-lang/pub#4002]
This is a question about the PubGrub solver, not pub itself. If there is a better place to post this, please let me know.

I have ported the PubGrub solver from pub/Dart to Java with Maven and NPM artifacts in order to explore version solving in a personal project. I have the solver working and passing all relevant unit tests including functional tests that go out to Maven Central and the NPM registry. What is missing is support for [Maven's `exclusions`](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions) and [NPM `overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides). I plan on using these on the artifacts as filters before supplying the artifacts to the solver (i.e. `incompatiblitiesFor`). The problem is that these constructs depend on the an artifacts path in the dependency graph. For example, an `exclusion` specified in the dependency `A` applies to any transitive dependency of `A` no matter how deep in the graph it occurs. So in order to know if an exclusion applies to a transitive dependency, I need to know the location in the dependency graph that is causing that dependency to be considered. After much investigation into the source code, I still cannot figure out how to obtain that graph and path during solving. Obviously the graph and thus the path will change as new assignments are made and when backtracking. The PubGrub implementation in `pub` supports overrides but they are global and independent of an artifact's location in the dependency graph. Any guidance on how to proceed would be greatly appreciated. I plan to make my repository public once I get this functionality implemented, so any help will likely help others as they consider using PubGrub in their projects.

Thanks in advance for any help!

**Comment by sigurdm** [comment]
Yeah, not sure how to handle something like that. As I see it a problem is that if each version can have it's own exclusions, the collected constraints of a partial resolution is no longer monotone. (Adding a version with exclusions might allow you to use package-versions you have already rejected). I'm sure there must be ways around this - but I don't have really good ideas.

@jonasfj has once been dappling with solvers. Maybe he has Ideas.

**Comment by baron1405** [comment]
@sigurdm Thanks for your reply. There is quite an active discussion of this topic on https://github.com/pubgrub-rs/pubgrub/issues/131. I would love to have your and @jonasfj's thoughts on the approach suggested there.

**Comment by baron1405** [comment]
Closing this in favor of the discussion on pubgrub-rs/pubgrub#131.
