### ISSUE TITLE
Is precompile in `dart.dart` sane?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#4003]
If inside `bin/frontendserver_testing.dart` I do:
```dart
import 'package:frontend_server_client/frontend_server_client.dart';
import 'package:path/path.dart' as p;
import 'dart:io';

Future<void> main() async {
  // TODO: Do this twice, and ask jens why it slow the second time -- if not slow second time, then we have don't something dumb in `dart run`

  final sw = Stopwatch()..start();
  final sdkRoot = p.relative(p.dirname(p.dirname(Platform.resolvedExecutable)));
  final client = await FrontendServerClient.start(
    'bin/pub.dart',
    'pub.dill',
    'lib/_internal/vm_platform_strong.dill',
    sdkRoot: sdkRoot,
    printIncrementalDependencies: false,
  );
  print('START: ${sw.elapsedMilliseconds} ms');
  sw.reset();
  final result = await client.compile();
  print('COMPILE: ${sw.elapsedMilliseconds} ms');
  client.kill();
  print(result.compilerOutputLines.join('\n'));
}
```

I get the following behavior:
```
$ rm pub.dill 
$ dart bin/frontendserver_testing.dart 
START: 63 ms
COMPILE: 6279 ms

$ dart bin/frontendserver_testing.dart 
START: 64 ms
COMPILE: 917 ms
```

So clearly building with an existing `.dill` file and reusing it from a previous compilation should be faster than not doing so.

-----------------------

But if I go inside `lib/src/entrypoint.dart` and tweak `_precompileExecutable` such that:
```dart
  Future<void> _precompileExecutable(
    Executable executable, {
    List<String> additionalSources = const [],
    String? nativeAssets,
  }) async {
    final package = executable.package;

    final sw = Stopwatch()..start();
    print('---------------- starting');
    await dart.precompile(
      executablePath: await resolveExecutable(executable),
      outputPath: pathOfExecutable(executable),
      incrementalDillPath: incrementalDillPathOfExecutable(executable),
      packageConfigPath: packageConfigPath,
      name: '$package:${p.basenameWithoutExtension(executable.relativePath)}',
      additionalSources: additionalSources,
      nativeAssets: nativeAssets,
    );
    print('---------------- compiled once: ${sw.elapsedMilliseconds} ms');
    sw.reset();
    await dart.precompile(
      executablePath: await resolveExecutable(executable),
      outputPath: pathOfExecutable(executable),
      incrementalDillPath: incrementalDillPathOfExecutable(executable),
      packageConfigPath: packageConfigPath,
      name: '$package:${p.basenameWithoutExtension(executable.relativePath)}',
      additionalSources: additionalSources,
      nativeAssets: nativeAssets,
    );
    print('---------------- compiled again: ${sw.elapsedMilliseconds} ms');
    cache.maintainCache();
  }
```
Then I get the behavior that:
```
$ dart run pub run pub                  # <-- I know this crazy, but also a bit fun!
Building package executable... (6.6s)   # <-- Ignore this, just precompiling pub so we can run it
Built pub:pub.
Building package executable... ---------------- starting
(6.5s)
Built pub:pub.
---------------- compiled once: 6535 ms       # <-- First time our pub compiles pub
Built pub:pub.
---------------- compiled again: 6501 ms      # <-- Second time our pub compiles pub (same process!)
Pub is a package manager for Dart.

Usage: pub <command> [arguments]
...
```

This suggest to me that we're doing something dumb in `precompile`.
Maybe the `copyFile` magic is a bit too smart. Maybe something else, I don't know.

But maybe we should:
 * Find out what is going on, why are we not reusing the previous compilation result.
 * Write a comment section explaining what files we are caching in `.dart_tool/pub/` and what these do.
   (Structure of folders and files, what invariants we have)
     * Maybe, we even need to document this in a markdown file in `doc/` because we might need
       to care what older pub versions might have left behind?
       (maybe not, don't we delete `.dart_tool/pub/` when we generate a new `package_config.json` or something like that? Probably we need to write these invariants down somewhere, a length comment-block might do)
 * Maybe we should reduce the number of different call steps we have, currently we pass things through:
   * `dartdev run` ->
   * `getExecutableForCommand` ->
   * `precompileExecutable` ->
   * `_precompileExecutable` ->
   * `precompile` ->
   * `FrontendServerClient.start()` (from `package:frontend_server_client`)

@sigurdm am I possibly, right that there is something sketchy here? or am I missing something (just updated my `pub` repo to check it again, and it still seems relevant).

**Comment by sigurdm** [comment]
Some of the times some things are working:
```
pub$ rm .dart_tool/ -rf
pub$ dart pub get > /dev/null 
pub$ time dart run pub > /dev/null

real    0m11.818s
user    0m14.867s
sys     0m1.563s
pub$ time dart run pub > /dev/null

real    0m2.308s
user    0m2.637s
sys     0m0.807s
```

But it seems if we get a broken file into "incrementalDillPath" then we fail remove it as long as compilation goes well:

```
# create a broken incremental-cache:
pub$ echo abc > .dart_tool/pub/incremental/pub/pub.dart.incremental.dill
pub$ time dart run pub > /dev/null

real    0m12.276s
user    0m15.053s
sys     0m1.904s
```

We should probably delete any stale incrementalDillPath files here: https://github.com/dart-lang/pub/blob/ee3f0ff740c38f8886b1b460a11dd44bb2d894e6/lib/src/dart.dart#L178

And probably start by checking for existing `outputPath` before `incrementalDillPath` here: https://github.com/dart-lang/pub/blob/ee3f0ff740c38f8886b1b460a11dd44bb2d894e6/lib/src/dart.dart#L138
