### ISSUE TITLE
Add support to skip size validation for hosted packages

### ISSUE THREAD

**Issue by SergeyShustikov** [dart-lang/pub#4013]
Currently, I'm using hosted dependencies in my project, but one of them weight more than 100 MB as set in SizeValidator
https://github.com/dart-lang/pub/blob/cb0d6f97af64bc1494c0b4432833eca1af79feec/lib/src/validator/size.dart#L22

I am totally blocked from publishing my package. I know that I could split it into a few small parts, but in my case, it's not possible.
So, it would be nice to allow developers to publish hosted packages to another pub.dev solutions (for example to JFrog Artifactory) ignoring SizeValidation.

**Comment by sigurdm** [comment]
I agree, this should be a warning, not an error. The server should provide the error if it has a size-limit.

For now you should be able to shortcut the error with: `dart pub publish --skip-validation`.

**Comment by sigurdm** [comment]
We have switched this to be a warning only.
