### ISSUE TITLE
pub upgrade

### ISSUE THREAD

**Issue by Lui-code** [dart-lang/pub#4020]
how can i solve the 'unable to pub upgrade' issue? i am new to vs code

**Comment by sigurdm** [comment]
You need to provide more details for us to see what is happening.

* Can you explain what you are doing?
* Provide your pubspec.yaml
* Attach a screenshot of vs code
* Try running `dart pub upgrade` in a terminal.
* What OS are you using?
* Are you using flutter or dart, what version?
