### ISSUE TITLE
`.pubignore` field ignores not only that file, but also files in subfolders with the same name

### ISSUE THREAD

**Issue by temeddix** [dart-lang/pub#4023]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macOS Ventura 13.5.2 (Intel)
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

This is the content of `.pubignore` file.

```
DEVNOTE.md
```

## Expected behavior

When running `dart pub publish` to publish the package to `pub.dev`, I expect only `DEVNOTE.md` at the root folder to be excluded from publishing, not those in subfolders, such as `some_folder/DEVNOTE.md`, `some_folder/deeper/DEVNOTE.md`.

## Actual behavior

All `DEVNOTE.md` inside various subfolders are excluded from publishing.

This kind of behavior is something similar to `**/DEVNOTE.md` written in `.gitignore`.

**Comment by temeddix** [comment]
Or is it because of the syntax? `/DEVNOTE.md` seems to only ignore the file at the root folder.

**Comment by sigurdm** [comment]
Yes, use the gitignore syntax, see:

https://git-scm.com/docs/gitignore#:~:text=If%20there%20is%20a%20separator%20at%20the%20beginning%20or%20middle
