### ISSUE TITLE
avoid `dart pub get` fetching package dependencies on example/ 

### ISSUE THREAD

**Issue by alestiago** [dart-lang/pub#4029]
# Environment

- Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"
- maxOs Monterey (12.2.1)
- I am not using the Chinese community mirror or a corporate firewall.

# Problem

1. Install the [Dart SDK](https://dart.dev/get-dart).

2. Create a dart package project:
```sh
dart create sample
```

3. Install the [Flutter SDK](https://docs.flutter.dev/get-started/install).

4. Create a Flutter example (from sample/):
```sh
flutter create example
```

5. Uninstall the Flutter SDK but ensure the Dart SDK is still installed.

4. Get package dependencies (from sample/):
```sh
dart pub get
```

The command should fail since example has a Flutter dependency and Flutter is not installed.

> Note: If you already have Flutter installed (because you skipped step 5) in your machine the command will succeed. Two pubspec.lock will be generated one for `sample/` and another one for `sample/example/`. 

## Expected behavior

I would like to have an option that avoids the `dart pub get` fetching packages on `sample/example`. This affects CIs where I would only want to test `sample/` and not `sample/example/` but I see myself conditioned to install Flutter on the CI and not simply Dart.

## Question

Is there something already available that could prevent `dart pub get` fetching dependencies on `sample/example/` but fetch those on `sample/`?

**Comment by sigurdm** [comment]
> Is there something already available that could prevent dart pub get fetching dependencies on sample/example/ but fetch those on sample/?

Yes, there is a (hidden) command-line flag `dart pub get --no-example` that does exactly that.

@jonasfj should we consider un-hiding this flag? (https://github.com/dart-lang/pub/blob/master/lib/src/command/get.dart#L56)

**Comment by alestiago** [comment]
Thank you @sigurdm! What if a project is under another directory not named example?
