### ISSUE TITLE
Handling package retraction

### ISSUE THREAD

**Issue by Reprevise** [dart-lang/pub#4033]
When a package gets retracted, there is little tooling to get back to a supported version, which is semi-fair considering how _rare_ it is. However, when it does happen, it's annoying. I'm proposing a couple of things.

- Highlight retracted versions in `pub outdated`
    - Currently, the only way you can tell a package is retracted is noticing your current version is ahead of the one shown in the "Latest" column
- Add some way to get back to the supported version
    - The "easiest" way I know how is running `pub downgrade` then running `pub upgrade` again

**Other questions**
How does `pub cache` handle reverts? Would I have to delete the folder in the cache for the reverted version if the author were to re-use the same version?

**Comment by sigurdm** [comment]
I agree pub outdated could show something. We do that for discontinued. That is probably an oversight.

> How does pub cache handle reverts? Would I have to delete the folder in the cache for the reverted version if the author were to re-use the same version?

We don't delete the version from the cache. You are still free to use it if it is in the pubspec.lock.
You cannot reuse a retracted version number.

**Comment by Reprevise** [comment]
So what about going back to a non-retracted version? I can agree it's pretty rare (though this is just an anecdote, some metrics on this would be interesting), but would it be worth adding a way to go back easily? Using `pub upgrade` doesn't make sense, and `pub downgrade` AFAIK goes to your min version constraint.

**Comment by sigurdm** [comment]
`dart pub upgrade` should get you to the latest non-retracted version (that is compatible with other dependencies...)
If you want to go to a specific version (without changing your constraint) you pretty much have to edit pubspec.lock manually. (Remember to do `dart pub get` after editing the pubspec.lock, it will warn you about the content-hash not matching, and update pubspec.lock with the correct hash).

**Comment by Reprevise** [comment]
> `dart pub upgrade` should get you to the latest non-retracted version (that is compatible with other dependencies...)

I don't recall `dart pub upgrade` going back to a non-retracted version when it happened to me. Something to look into maybe?

**Comment by sigurdm** [comment]
> I don't recall dart pub upgrade going back to a non-retracted version when it happened to me. Something to look into maybe?

By "latest" I mean newest. In most cases there will be a newer version than the retracted one available. Only if no such version exists `upgrade` should downgrade you.

**Comment by Reprevise** [comment]
> By "latest" I mean newest. In most cases there will be a newer version than the retracted one available. Only if no such version exists upgrade should downgrade you.

So you're saying, if the package author hasn't published a version after the retracted one, then `pub upgrade` should downgrade? I don't recall that happening to me, unless I have to specify the package name specifically like `pub upgrade {package}`.

**Comment by szakarias** [comment]
In the documentation https://dart.dev/tools/pub/publishing#retract we strongly encourage to publish a new version before retracting so I would think that in most cases there is a new version.

In this (hopefully rare) case, we could consider downgrading if possible.

**Comment by sigurdm** [comment]
Question is how hard it would be to implement. If I remember correctly we currently leave retracted versions out if the solve entirely unless:

* they are currently locked or
* they are pinned

If we want to implement the potential downgrade (downgrade unless no older versions exist) we would have to change the prioritization of retracted packages, and that would be a heuristic at most (not guaranteeing that we get the lower version)...

**Comment by szakarias** [comment]
It's not just a matter of implementation. There are many corner cases to consider when there is no newer version available. I am not sure we want this downgrade, because it cannot solve all these cases. I might be better to consider ways to advise users how to migrate away from retracted versions.

**Comment by szakarias** [comment]
We've decided that we don't want to do downgrading at this point. We will be adding some documentation on which flows you can use to migrate away from retracted versions when no newer version exists. 

Basically you can either do `pub downgrade foo` followed by `pub upgrade foo` or you can manually delete the package entry in pubspec.lock and then do `pub get` or `pub upgrade`. You can also completely delete pubspec.lock but then you might also get version changes for other dependencies.

The documentation is tracked here https://github.com/dart-lang/site-www/issues/5315

**Comment by Reprevise** [comment]
Well, I still think that retracted versions should be pointed out by the pub tool. Perhaps it can also link to the new documentation in the case that you're on a retracted version of a package too.

**Comment by szakarias** [comment]
I agree, it should also be pointed out in `pub outdated` so I'm not closing this issue.

**Comment by sigurdm** [comment]
Btw. this is related to an earlier issue: https://github.com/dart-lang/pub/pull/3887
