### ISSUE TITLE
Make `direct overridden` preceding to `direct main` and `direct dev` in lockfile

### ISSUE THREAD

**Issue by hyiso** [dart-lang/pub#4047]
When running `pub get`, dependencies in `dependency_overrides` are preceding to those in `depedencies` and `dev_dependencies`, but the precedence is not applied to `pubspec.lock` file according to https://github.com/dart-lang/pub/blob/master/lib/src/lock_file.dart#L470-L481

**Comment by sigurdm** [comment]
Why do we want to change this? The comment in the code explicitly says that the direct dependencies takes precedence.

Are you using these values for anything?

I think we should move the "overridden" part out of the kind - it doesn't really belong there - but not sure it's worth the effort

**Comment by hyiso** [comment]
We are writing a tool to auto change dependency's description (version or git ref) in a Flutter App/Module project.

The change logic is:

- If a package is `transitive` or `direct overridden`, the change should be made in `dependencies_overrides` section

- If a package is `direct main` or `direct dev`, the change should be made in `dependencies` or `dev_dependencies`

But if a dependency exists both in `dependencies` and `dependency_overrides`, the update logic above is broken.

As this inconsistency between `pub` tool and `pubspec.lock`, we should also read the content of `pubspec.yaml` to get the correct change section.

**Comment by sigurdm** [comment]
I think it is better to read pubspec.yaml

**Comment by hyiso** [comment]
Yes, I finally turn the change logic to:
- If a dependency is transitive, change the `dependency_overrides` section
- Else change the section it exists in `pubspec.yaml`
