### ISSUE TITLE
depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

### ISSUE THREAD

**Issue by liubaokai** [dart-lang/pub#4072]
# Environment

- Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"

- macOS 14.1.2:
- export PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub
export FLUTTER_STORAGE_BASE_URL=https://mirrors.cloud.tencent.com/flutter

执行pub get失败

**Comment by sigurdm** [comment]
You need to install the flutter sdk, not the dart sdk.
Try running `flutter pub get` instead of `dart pub get` or `pub get`.

Consider using a newer version than 2.12 if possible
