### ISSUE TITLE
Repository specification should specify how advisories are served

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#4073]
See: https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

We also need to make sure that the mechanism used to add this doesn't negatively affect 3rd-party pub servers that don't yet have support for advisories. I suspect we do this by saying clients of the API may not call the `/advisories` API unless there is an `advisoriesUpdated` is present and not `null`.

We also need to specify the `advisoriesUpdated` value.

**Comment by jonasfj** [comment]
I'd suggest that: `advisoriesUpdated´ is specified as:

```js
{
  "name": "<package>",
  "isDiscontinued": true || false, /* optional field, false if omitted */
  "advisoriesUpdated": "<date-time>", /* optional field, timestamp of the last time the contents of
                                         the advisories API changed for this package */
....
```

> The `advisoriesUpdated` property is optional, if specified the client may assume that the advisories end-point is supported by the server. If present this must be a timestamp of when the result from the advisories end-point for this package changed.

**Comment by szakarias** [comment]
Fixed by https://github.com/dart-lang/pub/pull/4134
