### ISSUE TITLE
Indicate when downloading packages (as opposed to just "Resolving...")

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/pub#4082]
When downloading lots of packages, especially over an unreliable or non-existent Internet connection, `dart pub get` could hang (not fail) trying to download packages. When combined with `dart compile` or `dart run`, which implicitly run `dart pub get`, it's unclear what's taking so long -- analyzing, compiling, running, or getting packages. Logging a message like `Downloading packages...` after `Resolving dependencies...` would be very helpful in these cases.

**Comment by sigurdm** [comment]
This is done in https://github.com/dart-lang/pub/pull/4175
