### ISSUE TITLE
`pub download` command

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#4102]
I'd like to propose a new `pub download` command, which can be used to download a package to local storage. Sample use cases for this include:

* Review the source code of a package
* Read and run the `/example` of a package
* Downloading a copy into a private pub server

This new command would take a single argument, a package name, and would then lookup the more recent stable version, and then download the files from that into a new directory `<package name>-<package version` in the current working directory.

**Comment by mit-mit** [comment]
Here's a sample implementation:
https://github.com/dart-lang/pub/pull/4103

**Comment by sigurdm** [comment]
I think it is true that the barrier for running an example from a package is too high. Maybe this is the right way to do it...

Maybe the command-name ambiguous? `dart pub download` could be confused with `dart pub get` as the command retrieving dependencies... Not sure. And also not sure I have a better name on hand.

We do have `dart pub cache add` for downloading a package to the pub-cache. But that is probably too obscure for discovery, and you cannot run examples out of the cache directly (but it would work for reviewing the code).

> Downloading a copy into a private pub server

I think this use-case is a bit speculative. Most likely a private pub-server would like to download the .tar.gz archive, not unpacked...
