### ISSUE TITLE
Large git dependencies can make "pub get" take a long time and it's not obvious what's happening

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#4104]
This might just be a me problem, but I thought it was worth raising for discussion.

I was recently trying to debug an issue that involved using webdev/dwds from source. When I ran `pub get` for DWDS, the process appeared to just hang for a long time, transferring lots of data from the web without outputting anything in the console to indicate what it was doing.

It turned out to be that there are dependency overrides (in pubspec_overrides.yaml so I didn't see them in the pubspec) that reference the Dart SDK:

https://github.com/dart-lang/webdev/blob/master/dwds/pubspec_overrides.yaml

Pub was cloning the SDK in the background, but because it wasn't one of the last things written in the `-v` output, it took me a while to realise that's what was happening (I resorted to wiping out the pub cache and seeing what it was writing - although in hindsight I probably could've seen it was connected to GitHub in the network monitor).

It could be useful if cloning repositories (or perhaps any operation still running after some amount of time) would emit some additional text (similar to how Flutter sometimes says "This is taking longer than expected") at least in `-v` mode to give an indication of what task is still ongoing if it wasn't the last thing to have written any output (`-v` is _really_ verbose!).

**Comment by sigurdm** [comment]
Agreed. It would be nice with some kind of progress indicator/spinner showing when we are cloning and downloading dependencies.

**Comment by sigurdm** [comment]
This should be fixed by https://github.com/dart-lang/pub/pull/4175
