### ISSUE TITLE
Split `dart pub publish` in two steps

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#4117]
* Create tarball: `dart pub publish --to-archive=<output.tar.gz>`
 * Publish tarball: `dart pub publish --from-archive=<output.tar.gz>`

I suggest we make the options hidden for now.

TODO: Consider if we can come up with better names for the arguments. Maybe `--upload` instead from `--from-tarball`, but then what would `--to-archive` be?

**Comment by szakarias** [comment]
fixed by https://github.com/dart-lang/pub/pull/4119
