### ISSUE TITLE
Support Git's safe.bareRepository=explicit config option

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/pub#4141]
Some environments configure GIt with the `safe.bareRepository=explicit` option in `git-config` for improved security.

With this setting Flutter's use of pub was failing due to this dependency on a package fetched through Git:
https://github.com/flutter/flutter/blob/master/dev/integration_tests/android_views/pubspec.yaml#L19

The `pubspec.yaml` specifies a Git URL and commit hash.  The `.pub-cache` was storing this package as a Git bare repository.

With `safe.bareRepository=explicit` Pub fails to locate the commit hash:
```
Package not available (Could not find git ref '64d0f6051b9b7b9933d3d16194170a38f544634a'
(fatal: cannot use bare repository '/usr/local/google/home/jsimmons/.pub-cache/git/cache/goldens-9579e0161a174b307c855fff52478bf0dc30bb1a'
(safe.bareRepository is 'explicit'))).
```

Pub should support Git in this configuration.  It may need to pass the `--git-dir` flag to Git when accessing these repositories in the cache.

**Comment by yanok** [comment]
Got affected by this today as well.
