### ISSUE TITLE
Bump package:args to 2.5.0

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#4215]
In the SDK package:args is already at 2.5.0, and it defines a `Argresults.flag` method which shadows the extension method in `lib/src/utils.dart` unused leading to unused import errors in various files in the pub code (inside the SDK).

Once args 2.5.0 is released, it should be used and the imports and util extension method removed.

FYI @devoncarew

**Comment by devoncarew** [comment]
Thanks for the heads up - `2.5.0` has been published now.

**Comment by sigurdm** [comment]
This is done
