### ISSUE TITLE
Random errors when running pub get through melos bootstrap

### ISSUE THREAD

**Issue by m2themax** [dart-lang/pub#4224]
I get random errors when running pub get through melos bootstrap (in a local multi-package flutter workspace)

The errors disappear when I make cosmetic changes to the pubspec.yaml file (e.g. switching two lines). But they are quite frequent, so this isn't really a robust workaround. 

[pub_log.txt](https://github.com/dart-lang/pub/files/14981287/pub_log.txt)

**Comment by sigurdm** [comment]
Seems like a duplicate in https://github.com/flutter/flutter/issues/143792

Analytics code has been removed from pub in newer sdk versions (and also there has been some fixes to unified analytics), so I don't think pub has this issue anymore.

**Comment by m2themax** [comment]
I am on Dart SDK 3.3.3 according to dart --version:

`Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"`

The most recent version is 3.3.4. Is this problem supposed to be fixed in 3.3.4?

**Comment by sigurdm** [comment]
>  Is this problem supposed to be fixed in 3.3.4?

No, I don't think so.

I closed this as a duplicate of the other issue. Please follow that issue.

But, at least from the pub side we stopped sending analytics at: https://github.com/dart-lang/pub/pull/4077 which is in the 3.4.0 beta. But I think that the underlying issue with analytics might pop up at other places.
