### ISSUE TITLE
Upload .gitkeep files/empty directories when publishing

### ISSUE THREAD

**Issue by vashworth** [dart-lang/pub#4262]
[Flutter is working to adopt Swift Package Manager](https://github.com/flutter/flutter/issues/126005), and has run into an issue where directories with only a `.gitkeep` are not downloaded to pub-cache. 

For example, plugin `video_player_avfoundation` (version 2.6.0) has [`video_player_avfoundation-2.6.0/darwin/video_player_avfoundation/Sources/video_player_avfoundation_ios/include/.gitkeep`](https://github.com/flutter/packages/tree/main/packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation_ios/include). However, in `.pub-cache`, both the `include` directory and the `.gitkeep` file are not found. This is a problem for Swift Package Manager as it requires an `include` directory.

I would expect `/path/to/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.6.0/darwin/video_player_avfoundation/Sources/video_player_avfoundation_ios/include/.gitkeep` to exist

See https://github.com/flutter/flutter/issues/148002

**Comment by jonasfj** [comment]
Just to clarify:
 * Empty directories are not published.
 * On publishing we ignore dot-files by default.

**Comment by jonasfj** [comment]
Options for solving this:
 * [ ] Support publishing empty directory.
 * [ ] Support `.gitkeep` files, meaning do not ignore such files.
 * [ ] Ask package authors to modify `.pubignore` to override the pattern ignoring `.gitkeep`.
 * [ ] Ask package authors to include a `README.md` in empty directories instead.

@vashworth which of these would work?

**Comment by sigurdm** [comment]
The current workaround is to add a `.pubignore` next to the .gitkeep file, containing

```
!.gitkeep
```

**Comment by vashworth** [comment]
> Options for solving this:
> 
> * [ ]  Support publishing empty directory.
> * [ ]  Support `.gitkeep` files, meaning do not ignore such files.
> * [ ]  Ask package authors to modify `.pubignore` to override the pattern ignoring `.gitkeep`.
> * [ ]  Ask package authors to include a `README.md` in empty directories instead.
> 
> @vashworth which of these would work?

We decided as a workaround to use `!.gitkeep` to unblock us for now, but in my opinion, I think we should support publishing empty directories. Using `.gitkeep` to ensure an empty directory is tracked is pretty common practice, but it seems that people use it in different ways (https://github.com/search?q=path%3A.gitkeep&type=code)

**Comment by sigurdm** [comment]
Let us include empty directories in the published tar-file.
