### ISSUE TITLE
"Packages have newer versions" disagrees with `dart pub outdated`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#4273]
On a fresh install of Dart 
(`Dart SDK version: 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "linux_arm64"`):

```sh
# I don't have a minimal repro case, but this is 100% Dart code and hopefully easy enough?
git clone https://github.com/matanlurey/dt

# In case I rev, this is the particular SHA it occurred at.
git reset --hard 620dea560ede6653efc5b58fe50a60e3d86d71ee
dart pub get
```

... resolved the following:

```sh
$ dart pub get
Resolving dependencies... 
Downloading packages... 
  lints 3.0.0 (4.0.0 available)
  macros 0.1.0-main.0 (0.1.0-main.5 available)
Got dependencies!
2 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
```

To which I tried `dart pub outdated` but got:

```sh
$ dart pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.
all dependencies are up-to-date.
```

**Comment by sigurdm** [comment]
Hmm you need `dart pub outdated --transitive`. By default we don't show outdated dependencies in `outdated`. I guess because they are less actionable.

@jonasfj should we reconsider this? There are times where transitive dependencies can be `dart pub upgraded`, so it is not really fair to say they are not actionable.

Alternatively we could detect this in `pub get` and suggest running `pub outdated --transitive`.

**Comment by jonasfj** [comment]
Yes, I think the reason we didn't do this, was that flutter causes a lot of packages to be pinned. And these packages will then all show up as outdated, but the user can't do anything about.

This is particularly bad if user uses `flutter_test` (even if it's just a dev_dependency).

**Comment by sigurdm** [comment]
> but the user can't do anything about.

They can (sometimes) upgrade flutter. Or they can file issues putting pressure on the flutter team to stop pinning the packages.

**Comment by jonasfj** [comment]
Sounds like we have 3 options:
 * (A) Show transitive in `pub outdated` by default.
 * (B) Write in `pub get` that people should use `pub outdated --transitive`
 * (C) Don't count outdated transitive dependencies in `pub get`.

**Comment by jonasfj** [comment]
After discussion we're starting think that (A) is the least worst option :rofl: 

Probably, we'll realize at some point why we didn't make `--transitive` default. Or maybe it really was a mistake.

I do remember we've had reports that people don't get notified enough about transitive dependencies being outdated, so going with (C) would probably be a bad idea. People need a hint that they should run `pub upgrade`.

**Comment by szakarias** [comment]
Fixed by https://github.com/dart-lang/pub/pull/4277

**Comment by stephane-archer** [comment]
@jonasfj Showing transitive in `pub outdated` by default is a great change.
But showing what direct dependency is responsible for this outdated transitive is necessary information otherwise what can you do with this information?

**Comment by sigurdm** [comment]
>  otherwise what can you do with this information?

If there is a newer `upgradable` version you can run `dart pub upgrade` and get that version into the pubspec lock.

If there is a newer `resolvable` version you can run `dart pub upgrade --major-versions` to reach that version.

We don't have very good tooling for showing exactly what holds a version back. The best would be to `dart pub add` the specific version, and look at the solve trace.

Eg. if you had:
```yaml
name: sample
version: 0.1.0
environment:
  sdk: ^3.0.0
dependencies:
  test: 1.25.4
```
And ran
```
> dart pub outdated --transitive
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name        Current        Upgradable     Resolvable     Latest        

direct dependencies:
test                *1.25.4        *1.25.4        1.25.5         1.25.5        

transitive dependencies:
macros              *0.1.0-main.0  *0.1.0-main.0  *0.1.0-main.0  0.1.0-main.5  
shelf_web_socket    *1.0.4         *1.0.4         2.0.0          2.0.0         
web_socket          -              -              0.1.4          0.1.4         
web_socket_channel  *2.4.5         *2.4.5         3.0.0          3.0.0 
```
You could get to know the "reason" that you cannot get web_socket_channel 3.0.0 by running:

```
> dart pub add web_socket_channel:3.0.0
Because sample depends on test 1.25.4 which depends on web_socket_channel ^2.0.0, web_socket_channel ^2.0.0 is
  required.
So, because sample depends on web_socket_channel 3.0.0, version solving failed.
```

It would be nice to have an easier way to "explore" the reasons for each dependency...

**Comment by sigurdm** [comment]
I guess it kind of is possible. But `outdated` wants to give an overview. Showing this information for each single package would be way too much.

**Comment by stephane-archer** [comment]
@sigurdm then would you consider adding ```dart pub outdated --culprit ```?
(you might choose a better name of course)
To me, there is nothing actionable when showing un-updated transitive dependencies without knowing what direct dependency I should blame.

**Comment by jonasfj** [comment]
I think for something like `--culprit` it might be more fun to just build a flutter app capable of showing your dependencies and letting you interactively play with what happens as you enforce certain upgrades.

Or building it into a vscode extension or something..

I have no idea how to even approach it, just saying a richer and more interactive approach might be more appropriate.

**Comment by stephane-archer** [comment]
@jonasfj I'm not sure to understand why you would want an interactive experience.
You just want to know why you can't use the last version of one of your transitive dependencies.
If you see the culprit, you can then go to the GitHub repo and propose a fix or raise an issue.

**Comment by gnprice** [comment]
For the feature request to find out which intermediate dependency is holding back an upgrade, there's an existing issue thread here:
* https://github.com/dart-lang/pub/issues/3545

**Comment by stephane-archer** [comment]
@gnprice I can already predict that you are going to revert back from showing transitive in `pub outdated` by default because you open more questions than you actually solve without this https://github.com/dart-lang/pub/issues/3545.

**Comment by matanlurey** [comment]
@sigurdm @szakarias Just wanted to say appreciate the quick fix!
