### ISSUE TITLE
pub.dev SSL expired

### ISSUE THREAD

**Issue by KirillArtemenko** [dart-lang/pub#4274]
NET::ERR_CERT_DATE_INVALID
Subject: pub.dev
Issuer: GTS CA 1D4

Certificate was expired May 19 2024.

**Comment by isoos** [comment]
@KirillArtemenko: this is for me right now:

![image](https://github.com/dart-lang/pub/assets/4778111/f9fcd1b3-48c6-407c-96c6-aa9cb58f1e86)

Could you please share more about your setup, network provider or proxy use?

**Comment by jonasfj** [comment]
Is this an error in your browser? `pub` client? or somewhere else?

What operating system? Have you fiddled with system certificates?

--------------

We did switch load-balancer, DNS records and certificates a month or two ago. Hitting the old IP might cause something like this because the old IP is unable to renew.

**Comment by KirillArtemenko** [comment]
openssl s_client -connect pub.dev:443 -servername pub.dev

```
CONNECTED(00000005)
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1D4
verify return:1
depth=0 CN = pub.dev
verify error:num=10:certificate has expired
notAfter=May 19 14:11:31 2024 GMT
verify return:1
depth=0 CN = pub.dev
notAfter=May 19 14:11:31 2024 GMT
verify return:1
---
Certificate chain
 0 s:CN = pub.dev
   i:C = US, O = Google Trust Services LLC, CN = GTS CA 1D4
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 19 13:21:59 2024 GMT; NotAfter: May 19 14:11:31 2024 GMT
 1 s:C = US, O = Google Trust Services LLC, CN = GTS CA 1D4
   i:C = US, O = Google Trust Services LLC, CN = GTS Root R1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Aug 13 00:00:42 2020 GMT; NotAfter: Sep 30 00:00:42 2027 GMT
 2 s:C = US, O = Google Trust Services LLC, CN = GTS Root R1
   i:C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 19 00:00:42 2020 GMT; NotAfter: Jan 28 00:00:42 2028 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFVDCCBDygAwIBAgIRAK4V+Nvn1nEPClmDbHdunSowDQYJKoZIhvcNAQELBQAw
RjELMAkGA1UEBhMCVVMxIjAgBgNVBAoTGUdvb2dsZSBUcnVzdCBTZXJ2aWNlcyBM
TEMxEzARBgNVBAMTCkdUUyBDQSAxRDQwHhcNMjQwMjE5MTMyMTU5WhcNMjQwNTE5
MTQxMTMxWjASMRAwDgYDVQQDEwdwdWIuZGV2MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAomwdn85nV3z+3cLX1Hx3BQAGKYs2IrdZjADi1uEvndaCKnwD
8KFRGkAE58x4XDhy9utlglsXH2cDMujlgyJ025xMB5XGyACOGFl2mR4x8AdX3hFn
+cfx36C7iPW9JW+oELx+kp08ZwxTpc5QwYL1SzD+zXAhjjoxIsYw6/NZLEwBfoYu
+ZY4lD/c1FODw1ZatTvzF3dO7Fybm1WfW1tp3AFarmMMU9zKZHlE2+ToURl64eVH
UwcPhNUy1uKyQeAETBxsYCUeW2tS04XPT5dm1bORwVJiChVVc/G2IVLrOGjL9e5Q
VYEmfEa3IGigWICMiIW/aJJx5SpFbcSEyWgJyQIDAQABo4ICbzCCAmswDgYDVR0P
AQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYD
VR0OBBYEFErHNwWB8Tcxyw4TfUQt3IwyYvrGMB8GA1UdIwQYMBaAFCXiGA6yV5GU
KuXUXYaQg95Ts7iSMHgGCCsGAQUFBwEBBGwwajA1BggrBgEFBQcwAYYpaHR0cDov
L29jc3AucGtpLmdvb2cvcy9ndHMxZDQvSVJ2NmFOV0NyUlUwMQYIKwYBBQUHMAKG
JWh0dHA6Ly9wa2kuZ29vZy9yZXBvL2NlcnRzL2d0czFkNC5kZXIwEgYDVR0RBAsw
CYIHcHViLmRldjAhBgNVHSAEGjAYMAgGBmeBDAECATAMBgorBgEEAdZ5AgUDMDwG
A1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmxzLnBraS5nb29nL2d0czFkNC9VNmRI
REw4QXBSSS5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgDuzdBk1dsazsVc
t520zROiModGfLzs3sNRSFlGcR+1mwAAAY3BvsCPAAAEAwBHMEUCIQCifhEUYwpL
rAbSBVVv3h3LpmxHm0eDKmOiTivFwoLQOwIgd121XgTA6dfAmFZx//RIk0Hduxba
Fb47FcGrR0GKnT4AdwDatr9rP7W2Ip+bwrtca+hwkXFsu1GEhTS9pD0wSNf7qwAA
AY3BvsDNAAAEAwBIMEYCIQCpY6wePpprHZPVdbV8Sk1+eveJj4QDcNgeHbhm3itj
8AIhAMoDSbxWzhtrnPJvepQlBJbWaCddPwtyaK1cr02+9InTMA0GCSqGSIb3DQEB
CwUAA4IBAQAkSe2qQwiV4tmXnKEIqcf09JzA+PyWX8/LsjOUTSQbpcWUmmMR6Wui
TMPV34WUmdjk57BFaJUDCaqYzKJKIFFK7lxIDMF61uErAcNki39jKeL8Dt6a6oRs
H++m5y/wS9jdP3GcPvi1mgktyOKgzAFWmAk/dU8yR4OAKzvQ+2yNyfoG/9zDgDBI
VjwlgaVQn3+lJtt/tvIUUnqUhHBQkxNfdylheOJ4kwZEkaWrrP8hIZNIrf6bj8wK
8QAQeq0tp5fNp5RRO5KivfIA8u7jxbWA/TW4KYAqka6pVsIMAZUuhSvXGOjnRs4V
kKeGWuWRJpD6Y4Zz0GXhFc4TkmdVjrw1
-----END CERTIFICATE-----
subject=CN = pub.dev
issuer=C = US, O = Google Trust Services LLC, CN = GTS CA 1D4
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4674 bytes and written 389 bytes
Verification error: certificate has expired
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 10 (certificate has expired)
---

```

**Comment by KirillArtemenko** [comment]
> Is this an error in your browser? `pub` client? or somewhere else?
> 
> What operating system? Have you fiddled with system certificates?
> 
> We did switch load-balancer, DNS records and certificates a month or two ago. Hitting the old IP might cause something like this because the old IP is unable to renew. But I'm not really sure how that could happen.

**Everything**

**Comment by KirillArtemenko** [comment]
That's what I try:
— turn on/off VPN (Netherlands)
— flush all caches (even dns cache)
— upgrade chrome
— replace DNS
— restart my mac

**Comment by KirillArtemenko** [comment]
I'm currently downloading the Sonoma 14.5 update, maybe it will help. I don't know what else to do to get a new certificate.

**Comment by jonasfj** [comment]
try:
```
$ host pub.dev
pub.dev has address 34.36.0.14
pub.dev has IPv6 address 2600:1901:0:382a::
pub.dev mail is handled by 0 smtp.google.com.
```

**Comment by jonasfj** [comment]
also try:
```
$ dig pub.dev any

; <<>> DiG 9.19.21-1-Debian <<>> pub.dev any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16787
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pub.dev.			IN	ANY

;; ANSWER SECTION:
pub.dev.		3600	IN	TXT	"v=spf1 include:_spf.google.com ~all"
pub.dev.		3600	IN	AAAA	2600:1901:0:382a::
pub.dev.		300	IN	MX	0 smtp.google.com.
pub.dev.		3600	IN	A	34.36.0.14
pub.dev.		60	IN	SOA	ns1.google.com. dns-admin.google.com. 634692657 900 900 1800 60
pub.dev.		21600	IN	CAA	0 issue "pki.goog"
pub.dev.		3600	IN	TXT	"google-site-verification=C3k_OdhshSLlONW9s05koU4-y3iQcZLTETDw5KGf5m0"

;; Query time: 39 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (TCP)
;; WHEN: Tue May 21 13:54:12 CEST 2024
;; MSG SIZE  rcvd: 317
```

**Comment by jonasfj** [comment]
also try:
```
$ curl -v https://pub.dev/debug
```

I'm guessing you should check what DNS server you're using.

Have you configured your own?

**Comment by KirillArtemenko** [comment]
Used Google DNS 8.8.8.8
curl -v https://pub.dev/debug
```
* Host pub.dev:443 was resolved.
* IPv6: (none)
* IPv4: 216.239.34.21
*   Trying 216.239.34.21:443...
* Connected to pub.dev (216.239.34.21) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* SSL certificate problem: certificate has expired
* Closing connection
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by KirillArtemenko** [comment]
Having studied the question, I can make the assumption that the problem is precisely in the server settings, due to which in some cases I receive an outdated certificate. Apparently this is due to routing features or my provider. But in the end, it is the pub.dev web-server that will issue me an outdated certificate.

**Comment by isoos** [comment]
@KirillArtemenko: I find it odd that out of the many users the site has, only you get an outdated certificate (or an outdated IP to route to). I find it more probably that there is a stale cache in your network route to the server, whether it is from the VPN or some non-standard setup that does no expiration/invalidation.

E.g. I assume that if you create a wifi hotspot on your phone and connect to pub.dev through that, it should just work the same way as you have it working through the  phone. It would suggest that it may be the vpn network that is causing an issue, either by mitm-changing something or having a split brain by routing part of the traffic through it, but other parts through the normal network.

**Comment by KirillArtemenko** [comment]
This was one of my first actions after I noticed that the site was opening from a phone, but the problem was exactly the same. I also tried using a socket connection, but no change. I tried to find a way to delete the cache on the OS but did not find it, system updates and reboots do not solve the problem. Now I trying reinstall all ssl services on my mac.

**Comment by KirillArtemenko** [comment]
Thank you for advice, but this was one of my first actions after I noticed that the site was opening from a phone, but the problem was exactly the same. I also tried using a socket connection, but no change. I tried to find a way to delete the cache on the OS but did not find it, system updates and reboots do not solve the problem. Reinstall openssl not helps. Other Macs in the office don't have this problem, only mine does. And I have no idea how to solve this problem.

**Comment by KirillArtemenko** [comment]
I found the reason, I don’t understand how I didn’t figure it earlier right away.

Web server at **216.239.34.21** returns the wrong certificate, but web server at **34.36.0.14** returns the correct one.

A few months ago, due to problems with DNS, I registered an explicit address (216.239.34.21 for pub.dev) in my _/etc/hosts_.
I could have guessed earlier, but what is still strange is why the old web server still responds with an outdated certificate, if it responded with any other error, I would have found the reason faster. 

P.S. I added it to my notes to check the _/etc/hosts_ file in case of similar problems.

### Thank you all for your help and ideas.

**Comment by jonasfj** [comment]
> A few months ago, due to problems with DNS, I registered an explicit address (216.239.34.21 for pub.dev) in my /etc/hosts.

LOL :rofl: We've all been there :rofl: 

--------------

@KirillArtemenko, thanks for figuring it out and updating us. It's really nice to know that this was just a dumb config file somewhere and not us who had misconfigured something.

I created an internal issue to see if can't cleanup the old certificates, there is no need for them to served anywhere.

**Comment by sigurdm** [comment]
Do we need to shut down the old IP address, now that it anyways has an expired certificate. I would guess that would lead to this being detected earlier.
