### ISSUE TITLE
Flutter Pub publish return error `LICENSE` file has no content.

### ISSUE THREAD

**Issue by AdilHypeteq** [dart-lang/pub#4288]
Hello,

I have try to publish flutter package but it's return `LICENSE` file has no content, but i have already added content into this file like this.

![image](https://github.com/dart-lang/pub/assets/106724238/d59ab2b7-7f66-4620-af16-55ee791e9d80)

can you please help me how to resolved this.

**Comment by sigurdm** [comment]
That is surprising. The validation is implemented here: https://github.com/dart-lang/pub/blob/cc4c1292a2191b98ae639b163a778436aeab060b/lib/src/validator/license.dart#L31

It should find the file

What is the output of running `cat LICENSE` (linux, macos) or `type LICENSE` (windows) at the root dir of your project in the terminal?

**Comment by AdilHypeteq** [comment]
i have try with another android studio and it's working fine - thanks @sigurdm
