### ISSUE TITLE
dependency_services/dependabot support for workspaces

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#4290]
At least:

* If dependency_services commands are run outside the workspace root, it should be an error.
* Constraint updates are applied to all pubspec.yaml files with a dependency on the updated package.
* Current constraints are given as the intersection of the constraint in all workspace packages.

**Comment by acoutts** [comment]
@sigurdm when setting up dependabot in a dart workspace, should i have a package-ecosystem declaration for the workspace and one for each pub package inside, or just at the workspace and it automatically takes care of the packages inside the workspace?

**Comment by sigurdm** [comment]
Just set up a single one for the whole workspace. (it will upgrade all instances of the same dependency at the same time).
