### ISSUE TITLE
`dart pub deps` does not work while `dart pub get` failed

### ISSUE THREAD

**Issue by omgseven** [dart-lang/pub#4296]
When running `dart pub get`, if it fails due to dependency version conflicts, it is currently not possible to use the `dart pub deps` command. This is problematic because in many cases, the very reason for running `dart pub deps` is to analyze the dependency graph and identify the source of conflicting dependencies. Without this tool, it becomes significantly harder to troubleshoot and resolve dependency issues.

**Comment by sigurdm** [comment]
`dart pub deps` is for showing you information the current version resolution.

When there are version conflicts, no resolution is possible, so it makes sense for `pub deps` to fail.

The failed resolution should give you the reason that there is a conflict. That is not always easy to read - but conflicts are in general not that easy to understand.

Not sure what you would expect `dart pub deps` to show when the resolution fails?
