### ISSUE TITLE
Unable to publish due to missing execution permission on server

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/pub#4311]
# Environment

- Dart SDK version: 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "macos_arm64"
- macOS 14.5

# Problem

```console
dart pub publish
...
Message from server: Failed to scan tar archive. (Exception: Directory "." has no executable mode bit.)
```

## Expected behavior

Command succeeds

## Actual behavior

Command fails

## --trace output

This adds no new information to the output

**Comment by sigurdm** [comment]
This sounds like a duplicate of: https://github.com/dart-lang/pub/issues/4305 but should not be possible with 3.4.3 stable as it does not have the buggy commit https://github.com/dart-lang/pub/commit/c9563e3cf03b92140c1170e16a8458410c420c90.

Are you completely sure you are not running with a dev release?

**Comment by Rexios80** [comment]
I'm completely sure I wasn't using the dev version, but it works now so maybe it was a server-side issue?

**Comment by sigurdm** [comment]
> so maybe it was a server-side issue?

It was a server side check that rejected the package. But that should never trigger on a package made by dart 3.4.3. And it explicitly mentions the "." entry of the package which would only be included by the buggy range of dev-releases (and corresponding main checkouts).

At least I have no clue how that would be possible.

@isoos any ideas?

**Comment by isoos** [comment]
We had a new release yesterday, but IIRC it did not affect this part of the upload checks. The only slightly related PR was https://github.com/dart-lang/pub-dev/pull/7812 which was more about the exception message exposure, and did not change the tar extraction and verification logic.

@Rexios80: can you confirm that you only use stable SDK and not any dev version (even by accident)?

**Comment by sigurdm** [comment]
> @Rexios80: can you confirm that you only use stable SDK and not any dev version (even by accident)?

They already confirmed...

**Comment by Rexios80** [comment]
I do have the dev SDK installed but I made sure I was on the stable one and still got the issue

**Comment by sigurdm** [comment]
I don't think we can do more here. Either the wrong sdk was invoked by mistake, or we have an irreproducible bug.

Thanks for providing feedback - please reopen if you see this happen again using a stable sdk.

**Comment by Rexios80** [comment]
I did think it could have been a build cache issue but I tried cleaning the project folder multiple times with no change in behavior

**Comment by sigurdm** [comment]
It has nothing to do with build cache.

This error can (I believe) only occur if the dart version used when invoking `dart pub publish` is one of the affected dev-releases

**Comment by sigurdm** [comment]
The logs confirm that this message has only been issued by the server to dev releases:
![image](https://github.com/dart-lang/pub/assets/8613953/69f61327-3258-435b-97bc-5cf89a834a56)

**Comment by Rexios80** [comment]
🤔

I made sure to run `dart --version` and then immediately `dart pub publish` but maybe I'm just crazy
