### ISSUE TITLE
some `pubspec.yaml` checks happen server side

### ISSUE THREAD

**Issue by kascote** [dart-lang/pub#4320]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "macos_arm64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macOS 14.5
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem

When try to publish a package that has a `topics` keyword with more of 5 topics, the packages analysis goes ok, but after upload it, returns the error.

## Expected behavior

When `dart pub publish` analyses the packages, this checks must be done too.

## Actual behavior

The publish action stops

## Console output

<img width="643" alt="Screenshot 2024-06-29 at 19 02 25" src="https://github.com/dart-lang/pub/assets/9757/52fad9d5-cf15-4511-8306-e822cfbd1cab">

**Comment by sigurdm** [comment]
The pub client can upload to multiple different servers. And it cannot know the policies of each up front.

We also prefer not hardcoding some of these checks in the client, as it is very hard to change old clients moving forwards.

Therefore this check is not implemented on the client side.

**Comment by sigurdm** [comment]
@szakarias might have more context

**Comment by szakarias** [comment]
+1 to what @sigurdm said.

Also, we set the limit to 5, because we would like to encourage people to prioritize the topics they choose. 

If you have duplicate topics a.k.a. different topics that are aliases, you are very welcome to submit a pull request with an addition to ``` https://github.com/dart-lang/pub-dev/blob/master/doc/topics.yaml``` which merges similar topics.
