### ISSUE TITLE
Flutter build error, build recommended that I report the build error - Null check operator used on a null value

### ISSUE THREAD

**Issue by dhoffer** [dart-lang/pub#4355]
flutter packages pub run build_runner build --delete-conflicting-outputs
Fails with error.
ERR : Null check operator used on a null value
FINE: Exception type: _TypeError

I have attached the build log file.

[pub_log.txt](https://github.com/user-attachments/files/16649996/pub_log.txt)

**Comment by sigurdm** [comment]
Thanks for reporting. There is indeed a bug here.

As a workaround use `dart run build_runner build` instead of `dart pub run build_runner build` or do a `pub get` before using `pub run`.
