### ISSUE TITLE
Issue on flutter pub get

### ISSUE THREAD

**Issue by Eiad-Rehawe** [dart-lang/pub#4371]
[pub_log.txt](https://github.com/user-attachments/files/16874272/pub_log.txt)

**Comment by sigurdm** [comment]
Crash in pub/src/source/hosted.dart 778:33


Should be fixed by https://github.com/dart-lang/pub/pull/4337

Do we need a cherry pick?

**Comment by sigurdm** [comment]
I think we're not cherry-picking here.
