### ISSUE TITLE
DevTools extensions detection logic fails to work in workspaces

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/pub#4379]
https://github.com/flutter/devtools/issues/7944

**Comment by sigurdm** [comment]
I'm not really sure there's much we can do from the pub client side.

I can try to investigate the dtd side of this. Around https://github.com/dart-lang/sdk/blob/ba8306735d7efa8aabfbf4d8f9a618bd00bfbcbd/pkg/dtd_impl/lib/src/service/file_system_service.dart#L204 But I'm not sure I have the best context for making changes there.

@bkonyi and @CoderDake might want to give a comment.

**Comment by sigurdm** [comment]
I updated the title, as strictly speaking we don't break anything in existing (non-workspace) projects

**Comment by bkonyi** [comment]
I think I'll need more context to really understand what the issue here is and what we need to resolve it. Then either @derekxu16 or I can dig into it (@CoderDake is no longer at Google).

**Comment by kenzieschmoll** [comment]
The underlying issue here is https://github.com/dart-lang/pub/issues/4218. I created this issue as a tracking issue for the "Shipping Pub Workspaces" project since I couldn't add https://github.com/flutter/devtools/issues/7944 directly.

**Comment by sigurdm** [comment]
This was fixed in https://github.com/flutter/devtools/pull/8347
