### ISSUE TITLE
Pub workspaces should suggest removing old pubspec.lock files

### ISSUE THREAD

**Issue by orestesgaolin** [dart-lang/pub#4382]
After migrating to new pub workspaces and applying `resolution: workspace` to my local packages I can still see previous `pubspec.lock` files as well as `.dart_tool` folders. Not sure if they are needed, but my intuition is that the individual lock files should no longer be necessary.

I would suggest that after first `flutter pub get` run these files get deleted automatically or the output should suggest removing them by the user.

**Comment by orestesgaolin** [comment]
Oh interesting, perhaps it somehow failed to do it for me? Let me double check, I might have looked at the file system at the wrong time while they were still there? Will report back.

**Comment by sigurdm** [comment]
@orestesgaolin did you find out?

**Comment by orestesgaolin** [comment]
No, I think it works fine now and then :)
