### ISSUE TITLE
Ability to publish package by name on workspace environments

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/pub#4388]
### Please describe the feature and your use case.
It would also be great to have the possibility of running `dart pub publish` command with the name of the package attached within a worskapce, so we avoid the need of opening Terminal within the sub-package's folder and then  run the `dart pub publish`.

**Something like:**
I am using intelliJ IDEA, and I am within the workspace directory in Terminal, I should be able to just run `dart pub publish packageName` .

### Are there any workarounds today? 
 
Open the package folder in Terminal an drun the dart publish command

**Comment by sigurdm** [comment]
You can run `dart pub -C path/to/package publish`
Does that work for you?

**Comment by pedromassango** [comment]
> You can run `dart pub -C path/to/package publish` Does that work for you?

I want to be able to simply specify the name of the package

**Comment by sigurdm** [comment]
Sorry - I don't think we'll do this.

**Comment by pedromassango** [comment]
> Sorry - I don't think we'll do this.

Would be great to share the motivations behind this decision

**Comment by sigurdm** [comment]
> Would be great to share the motivations behind this decision

There is a perfectly fine workaround, just a few characters longer.

It would take time away from other features that we want to work on. We sometimes have to prioritize

It is not clear what other pub commands should have the same behavior. Many commands already take an argument, and that would conflict with this argument. But only having this for `publish` would also be weird.

**Comment by sigurdm** [comment]
One more reason is that with -C you get tab-completion of the path!
