### ISSUE TITLE
"Error: The non-abstract class '_StaticTypeImpl' is missing implementations"

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/pub#4406]
I just switched to the `master` channel of Flutter, and a project that uses the analyzer as a library (Serverpod) reports this error:

```
$ ../../../.pub-cache/hosted/pub.dev/analyzer-6.5.0/lib/src/summary2/macro_application.dart:1261:7: Error: The non-abstract class '_StaticTypeImpl' is missing implementations for these members:
 - StaticType.asInstanceOf
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _StaticTypeImpl implements macro.StaticType {
      ^^^^^^^^^^^^^^^
/opt/flutter/bin/cache/dart-sdk/pkg/_macros/lib/src/api/introspection.dart:119:28: Context: 'StaticType.asInstanceOf' is defined here.
  Future<NamedStaticType?> asInstanceOf(TypeDeclaration declaration);
                           ^^^^^^^^^^^^
```

* Dart version 3.5.0 (build 3.5.0-214.0.dev)
* Flutter version 3.23.0-13.0.pre.80 on channel master
* Framework revision 5e448f4ce5 (10 hours ago), 2024-06-03 12:44:39 -0700

**Comment by sigurdm** [comment]
Thinking again we can do something simpler without sacrificing the fast path.

The sdk should recognize that the snapshot is not valid, and return a specific error code.
The binstub then invokes `dart global run` which is recompiling the snapshot.

`dart global run` could (and should) validate that the  resolution is still good using the `ensurePubspecResolved` mechanism that `dart run` also uses.

**Comment by sigurdm** [comment]
Hmm .. seems we are already validating the sdk constraints:

https://github.com/dart-lang/pub/blob/d86e3c979a3889fed61b68dae9f9156d0891704d/lib/src/global_packages.dart#L402

Not sure what is going wrong here then.

**Comment by sigurdm** [comment]
I can reproduce this with:
```console
$ flutter channel stable && flutter upgrade --force
[...]
$ flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter
Framework • revision 2663184aa7 (4 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
$  flutter pub global activate intl_utils
[...]
Activated intl_utils 2.8.7.
$ cat ~/.pub-cache/global_packages/intl_utils/pubspec.lock 
[...]
sdks:
  dart: ">=3.4.0 <4.0.0"
$ flutter channel stable && flutter upgrade --force
[...]
$ flutter --version
Flutter 3.26.0-1.0.pre.397 • channel master • https://github.com/flutter/flutter
Framework • revision e695cd6e9a (2 hours ago) • 2024-10-08 10:41:09 +0200
Engine • revision 7e8011f3cc
Tools • Dart 3.6.0 (build 3.6.0-330.0.dev) • DevTools 2.40.0
$ flutter pub global run intl_utils:generate
Building package executable... (3.6s)
Failed to build intl_utils:generate:
../../.pub-cache/hosted/pub.dev/analyzer-6.8.0/lib/src/summary2/macro_declarations.dart:57:3: Error: The implicitly called unnamed constructor from 'ConstructorDeclarationImpl' has required parameters.
```

So it seems like checking the sdk constraint is not enough in this case.
We should do the complete `ensureUpToDate`, that would discover that we no longer have the right _macros package version (actually that would fail as soon as the dart sdk is new).

**Comment by jakemac53** [comment]
Yeah, the issue isn't actually the SDK constraint it's the `package:macros` constraint, which ends up enforcing a certain SDK.

If this is an issue only created by SDK vendored packages, it might matter less.... although it might be an issue for flutter packages also?

**Comment by sigurdm** [comment]
> If this is an issue only created by SDK vendored packages, it might matter less.... although it might be an issue for flutter packages also?

Flutter packages cannot be `global activate`d. So I believe the issue is currently mainly around `package:_macros`.

**Comment by sigurdm** [comment]
This was fixed (or at least has a better error message) in https://github.com/dart-lang/pub/pull/4410

**Comment by lukehutch** [comment]
Thanks! Although the issue number you cited seems unrelated.

**Comment by sigurdm** [comment]
> Thanks! Although the issue number you cited seems unrelated.

Hmm - I think it is the right one.

Now instead of getting "Error: The non-abstract class '_StaticTypeImpl' is missing implementations" when doing `dart pub global run` you will now get asked to re-activate the globally activated package. We do this check by testing if the existing resolution is valid given the current sdk.
