### ISSUE TITLE
Null check operator used on a null value in ._getAdvisories.readAdvisoriesFromCache

### ISSUE THREAD

**Issue by NivashiniD** [dart-lang/pub#4422]
D:\fluttersdk\flutter\bin\flutter.bat --no-color pub get
Resolving dependencies...
Downloading packages...
Null check operator used on a null value
package:pub/src/source/hosted.dart 778:33              HostedSource._getAdvisories.readAdvisoriesFromCache
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 796:12              HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1084:24             HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 416:26              SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 220:18              SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 75:21               SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 580:5                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 76:5                  GetCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                     PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 236:18                    DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 47:16                     runDartdev
===== asynchronous gap ===========================
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 13:5  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\dell\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Process finished with exit code 1

**Comment by jonasfj** [comment]
quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

Also please note that the logs you posted reference `C:\Users\dell\AppData\Local\Pub\Cache\log\pub_log.txt`, which you could share as a gist.

**Comment by sigurdm** [comment]
This has a fix in https://github.com/dart-lang/pub/pull/4337/files

What version of dart are you using?

**Comment by NivashiniD** [comment]
3.5.3

**Comment by sigurdm** [comment]
Hmm - seems the fix will be included only in th 3.6.0 release.

You could try out the beta branch.

**Comment by NivashiniD** [comment]
Ok I ll try thank you

**Comment by maulikchak** [comment]
try flutter upgrade it's work for me (Upgrading Flutter to 3.24.5 from 3.24.2)

**Comment by jonasfj** [comment]
A decent workaround might be `dart pub cache clean`, ofcourse you'll have to do `dart pub get` in all projects.

This is fixed in the upcoming 3.6 release, you can try a 3.6 beta release now, to get the fix today.
