### ISSUE TITLE
solve the problem

### ISSUE THREAD

**Issue by fadumoAli1** [dart-lang/pub#4466]
# Environment

- Dart version (run `dart --version`):
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):
- Are you using the Chinese community mirror or a corporate firewall?

# Problem

```yaml
<copy/paste pubspec.yaml>
```

## --trace output

```
<copy/paste the full output>
```

**Comment by sigurdm** [comment]
???
I was not able to understand your issue. Please add a description of the problem.
