### ISSUE TITLE
Nested workspaces don't work

### ISSUE THREAD

**Issue by mosuem** [dart-lang/pub#4468]
# Environment

`Dart SDK version: 3.7.0-207.0.dev (dev) (Mon Dec 2 12:02:22 2024 -0800) on "linux_x64"`

# Problem

When using a top-level workspace `pubspec.yaml` and a workspace in the subfolder `source_gen`, the resolution in the subfolder fails with

```
The file `../pubspec.yaml` is located in a directory between the workspace root at
`.` and a workspace package at `.`. But is not a member of the
workspace.

This blocks the resolution of the package at `.`.

Consider removing it.

See https://dart.dev/go/workspaces-stray-files for details.
```

See https://github.com/dart-lang/build/pull/3778/commits/a6206cfa6191bcca2102afe469c84c65f55c8a8d to reproduce.

cc @sigurdm

**Comment by sigurdm** [comment]
Thanks for catching this!
